// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
    description: "app.description",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      snapshots: "layout.nav.snapshots",
      resolver: "layout.nav.resolver",
      devices: "layout.nav.devices",
      optimization: "layout.nav.optimization",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      latestSnapshot: "pages.dashboard.latestSnapshot",
      resolverStatus: "pages.dashboard.resolverStatus",
      adapterCapabilities: "pages.dashboard.adapterCapabilities",
      optimizationReadiness: "pages.dashboard.optimizationReadiness",
      privacyPosture: "pages.dashboard.privacyPosture",
      monitoring: "pages.dashboard.monitoring",
      monitoringSchedule: "pages.dashboard.monitoringSchedule",
      monitoringRun: "pages.dashboard.monitoringRun",
      monitoringAlerts: "pages.dashboard.monitoringAlerts",
      monitoringEmpty: "pages.dashboard.monitoringEmpty",
      monitoringBaselineRequired: "pages.dashboard.monitoringBaselineRequired",
      noSnapshots: "pages.dashboard.noSnapshots",
      supported: "pages.dashboard.supported",
      unsupported: "pages.dashboard.unsupported",
      ready: "pages.dashboard.ready",
      blocked: "pages.dashboard.blocked",
    },
    snapshots: {
      title: "pages.snapshots.title",
      description: "pages.snapshots.description",
      run: "pages.snapshots.run",
      export: "pages.snapshots.export",
      metrics: "pages.snapshots.metrics",
      findings: "pages.snapshots.findings",
      empty: "pages.snapshots.empty",
      report: "pages.snapshots.report",
    },
    resolver: {
      title: "pages.resolver.title",
      description: "pages.resolver.description",
      upstreams: "pages.resolver.upstreams",
      previewUpstreams: "pages.resolver.previewUpstreams",
      policyTarget: "pages.resolver.policyTarget",
      policyAction: "pages.resolver.policyAction",
      policyValues: "pages.resolver.policyValues",
      previewPolicy: "pages.resolver.previewPolicy",
      approveApply: "pages.resolver.approveApply",
      rollback: "pages.resolver.rollback",
      previewRequired: "pages.resolver.previewRequired",
      confirmation: "pages.resolver.confirmation",
      profiles: "pages.resolver.profiles",
      profileName: "pages.resolver.profileName",
      profileGroup: "pages.resolver.profileGroup",
      profileStrength: "pages.resolver.profileStrength",
      profileSchedule: "pages.resolver.profileSchedule",
      profileOverride: "pages.resolver.profileOverride",
      saveProfile: "pages.resolver.saveProfile",
      evaluateSchedule: "pages.resolver.evaluateSchedule",
      scheduleEvaluation: "pages.resolver.scheduleEvaluation",
      guidance: "pages.resolver.guidance",
      guidanceTarget: "pages.resolver.guidanceTarget",
      endpointPlatform: "pages.resolver.endpointPlatform",
      endpointBrowser: "pages.resolver.endpointBrowser",
      managementMode: "pages.resolver.managementMode",
      bypassGuidance: "pages.resolver.bypassGuidance",
      dohGuidance: "pages.resolver.dohGuidance",
      strength: {
        light: "pages.resolver.strength.light",
        standard: "pages.resolver.strength.standard",
        strict: "pages.resolver.strength.strict",
        off: "pages.resolver.strength.off",
      },
      override: {
        manualRequired: "pages.resolver.override.manualRequired",
        parentOverride: "pages.resolver.override.parentOverride",
        temporaryPause: "pages.resolver.override.temporaryPause",
      },
      actions: {
        allowlist: "pages.resolver.actions.allowlist",
        denylist: "pages.resolver.actions.denylist",
        blocklist: "pages.resolver.actions.blocklist",
        pause: "pages.resolver.actions.pause",
        resume: "pages.resolver.actions.resume",
      },
    },
    devices: {
      title: "pages.devices.title",
      description: "pages.devices.description",
      refresh: "pages.devices.refresh",
      empty: "pages.devices.empty",
      hostname: "pages.devices.hostname",
      address: "pages.devices.address",
      group: "pages.devices.group",
      confidence: "pages.devices.confidence",
      notes: "pages.devices.notes",
    },
    optimization: {
      title: "pages.optimization.title",
      description: "pages.optimization.description",
      start: "pages.optimization.start",
      score: "pages.optimization.score",
      approve: "pages.optimization.approve",
      empty: "pages.optimization.empty",
      comparison: "pages.optimization.comparison",
    },
    settings: {
      title: "pages.settings.title",
      description: "pages.settings.description",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      retentionHeading: "pages.settings.retentionHeading",
      visibilityHeading: "pages.settings.visibilityHeading",
      queryLogDays: "pages.settings.queryLogDays",
      snapshotDays: "pages.settings.snapshotDays",
      experimentDays: "pages.settings.experimentDays",
      showQueryDomains: "pages.settings.showQueryDomains",
      showDeviceHistory: "pages.settings.showDeviceHistory",
      householdMode: "pages.settings.householdMode",
    },
  },
  network: {
    loading: "network.loading",
    error: "network.error",
    unknown: "network.unknown",
    none: "network.none",
    status: "network.status",
    created: "network.created",
    profile: "network.profile",
    backend: "network.backend",
    filtering: "network.filtering",
    enabled: "network.enabled",
    disabled: "network.disabled",
    metric: "network.metric",
    value: "network.value",
    unit: "network.unit",
    approvalRequired: "network.approvalRequired",
    rollbackSupported: "network.rollbackSupported",
    baseline: "network.baseline",
    interval: "network.interval",
    minutes: "network.minutes",
    timeline: {
      baseline: "network.timeline.baseline",
      candidate: "network.timeline.candidate",
      after: "network.timeline.after",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
