package heartbeat

import (
	"context"
	"testing"

	"prompt-manager/store"
)

type stubConfigStore struct {
	config *store.HeartbeatConfig
	err    error
}

func (s *stubConfigStore) GetHeartbeatConfig(ctx context.Context, teamID, agentID string) (*store.HeartbeatConfig, error) {
	return s.config, s.err
}

type captureExecutor struct {
	calls []executionCall
}

type executionCall struct {
	teamID     string
	agentID    string
	profileKey string
}

func (c *captureExecutor) Execute(ctx context.Context, teamID, agentID, profileKey string) (*ExecutionResult, error) {
	c.calls = append(c.calls, executionCall{
		teamID:     teamID,
		agentID:    agentID,
		profileKey: profileKey,
	})
	return &ExecutionResult{
		TeamID:  teamID,
		AgentID: agentID,
		Status:  store.HeartbeatStatusRunning,
	}, nil
}

func TestSchedulerUsesConfigProfileKey(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:     "team-1",
			AgentID:    "agent-1",
			Enabled:    true,
			Schedule:   "0 * * * *",
			ProfileKey: "custom-profile",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 1 {
		t.Fatalf("expected executor to be called once, got %d", len(exec.calls))
	}
	if exec.calls[0].profileKey != "custom-profile" {
		t.Fatalf("expected profileKey to be custom-profile, got %s", exec.calls[0].profileKey)
	}
}

func TestSchedulerUsesDefaultProfileWhenEmpty(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  true,
			Schedule: "0 * * * *",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 1 {
		t.Fatalf("expected executor to be called once, got %d", len(exec.calls))
	}
	if exec.calls[0].profileKey != "prompt-manager-heartbeat" {
		t.Fatalf("expected default profileKey, got %s", exec.calls[0].profileKey)
	}
}

func TestSchedulerSkipsWhenConfigMissing(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{config: nil}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 0 {
		t.Fatalf("expected executor not to be called, got %d calls", len(exec.calls))
	}
}

func TestSchedulerScheduleStandard5FieldCron(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	// Standard 5-field cron expressions generated by the UI must be accepted.
	cases := []struct {
		name     string
		schedule string
	}{
		{"daily at 10:45", "45 10 * * *"},
		{"every hour", "0 * * * *"},
		{"every 6 hours", "0 */6 * * *"},
		{"weekdays at 9am", "0 9 * * 1,2,3,4,5"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if err := scheduler.Schedule("team-1", "agent-1", tc.schedule); err != nil {
				t.Fatalf("Schedule(%q) should succeed for standard 5-field cron, got: %v", tc.schedule, err)
			}
			if next := scheduler.GetNextRun("team-1", "agent-1"); next == nil {
				t.Fatalf("GetNextRun should return a time after scheduling %q", tc.schedule)
			}
			scheduler.Unschedule("team-1", "agent-1")
		})
	}
}

func TestSchedulerGetNextRunsReturnsMultipleFutureTimes(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	if err := scheduler.Schedule("team-1", "agent-1", "0 9 * * *"); err != nil {
		t.Fatalf("Schedule failed: %v", err)
	}

	runs := scheduler.GetNextRuns("team-1", "agent-1", 5)
	if len(runs) != 5 {
		t.Fatalf("expected 5 runs, got %d", len(runs))
	}

	// Each run must be strictly after the previous one.
	for i := 1; i < len(runs); i++ {
		if !runs[i].After(runs[i-1]) {
			t.Fatalf("run[%d] (%s) is not after run[%d] (%s)", i, runs[i], i-1, runs[i-1])
		}
	}

	scheduler.Unschedule("team-1", "agent-1")

	// Should return nil for unscheduled heartbeat.
	if runs := scheduler.GetNextRuns("team-1", "agent-1", 5); runs != nil {
		t.Fatalf("expected nil for unscheduled heartbeat, got %d runs", len(runs))
	}
}

func TestSchedulerRejectsInvalidCron(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	if err := scheduler.Schedule("team-1", "agent-1", "not a cron"); err == nil {
		t.Fatal("Schedule should reject invalid cron expression")
	}
}

func TestSchedulerSkipsWhenConfigDisabled(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  false,
			Schedule: "0 * * * *",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 0 {
		t.Fatalf("expected executor not to be called, got %d calls", len(exec.calls))
	}
}

func TestSchedulerRoutesToTeamExecStore(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:     "team-1",
			AgentID:    "agent-1",
			Enabled:    true,
			Schedule:   "0 * * * *",
			ProfileKey: "custom-profile",
		},
	}
	teamExecStore := NewTeamExecutionStore(exec, t.TempDir())
	scheduler := NewScheduler(exec, nil, configStore, teamExecStore)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	// Verify the team execution store received the enqueue (executor is called via goroutine)
	status := teamExecStore.Status("team-1")
	if status.State != "active" {
		t.Fatalf("expected team state 'active', got %q", status.State)
	}
	if status.Running == nil || *status.Running != "agent-1" {
		t.Fatalf("expected running agent-1, got %v", status.Running)
	}
}

func TestSchedulerHandlesMemberAlreadyQueued(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  true,
			Schedule: "0 * * * *",
		},
	}
	teamExecStore := NewTeamExecutionStore(exec, t.TempDir())
	scheduler := NewScheduler(exec, nil, configStore, teamExecStore)

	// First call should succeed
	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	// Second call should be skipped (already running) without panic
	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	// Should still have exactly one running
	status := teamExecStore.Status("team-1")
	if status.State != "active" {
		t.Fatalf("expected team state 'active', got %q", status.State)
	}
}
