package backlog

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"

	"swarm-manager/internal/agentmanager"
	"swarm-manager/internal/execution"
	"swarm-manager/internal/identity"
	"swarm-manager/internal/pathutil"
	"swarm-manager/internal/planclient"
	"swarm-manager/internal/transitions"
	"swarm-manager/internal/workflowcontract"

	"github.com/gorilla/mux"
	executionv1 "github.com/vrooli/vrooli/packages/proto/gen/go/plan-manager/v1/execution"
	sharedv1 "github.com/vrooli/vrooli/packages/proto/gen/go/plan-manager/v1/shared"
)

// acceptancePlanClient embeds the broad client interface but overrides only
// the read methods exercised by the acceptance boundary.
type acceptancePlanClient struct {
	planclient.Client
	plan *sharedv1.Plan
}

func (c acceptancePlanClient) GetPlan(context.Context, string) (*sharedv1.Plan, error) {
	return c.plan, nil
}

func (c acceptancePlanClient) RenderMarkdown(context.Context, string, bool) (planclient.RenderMarkdownResult, error) {
	return planclient.RenderMarkdownResult{Markdown: "# plan", Plan: c.plan, QualityStatus: "pass"}, nil
}

func (c acceptancePlanClient) Resume(context.Context, *executionv1.ResumeRequest) (*executionv1.ResumeResponse, error) {
	return &executionv1.ResumeResponse{Execution: &executionv1.Execution{Id: "plan-execution-1"}}, nil
}

type acceptanceWorkflowOwner struct {
	agentmanager.WorkflowInvoker
	invocation agentmanager.Invocation
}

func (o *acceptanceWorkflowOwner) StartWorkflow(_ context.Context, invocation agentmanager.Invocation) (agentmanager.WorkflowStart, error) {
	o.invocation = invocation
	return agentmanager.WorkflowStart{ExecutionID: "workflow-1", RunID: "run-1", DefinitionDigest: "sha256:workflow", ApprovalDigest: invocation.ApprovalDigest, GrantDigest: invocation.GrantDigest}, nil
}

// [REQ:SWM-P0-004] acceptance gate: operator accept pins canonical plan
func TestAcceptPlanPinsCanonicalHashAndScopeVersion(t *testing.T) {
	h, root := setupTestHandler(t)
	item := BacklogItem{Name: "accept-me", Title: "Accept me", Description: "scope", Status: StatusBacklog, Priority: 5, ExecutionLimits: &identity.ExecutionLimits{MaxSlices: 64, MaxTokens: 2000000, MaxWallSeconds: 604800, MaxTurns: 1000, MaxChargeMicroUSD: 30000000, MaxChildren: 256, MaxNodeAttempts: 512, MaxRetries: 64}, ExecutionStrategy: ExecutionStrategyAdaptiveImprovement, PlanRef: &PlanRef{Provider: PlanRefProviderPlanManager, PlanID: "plan-1", Slug: "plan-1", Role: PlanRefRoleExecutionSpec}}
	createPayload, err := json.Marshal(map[string]any{"kind": "execute", "name": item.Name, "title": item.Title, "description": item.Description, "execution_strategy": item.ExecutionStrategy, "execution_limits": item.ExecutionLimits, "plan_ref": item.PlanRef})
	if err != nil {
		t.Fatal(err)
	}
	createResponse := httptest.NewRecorder()
	h.Create(createResponse, httptest.NewRequest(http.MethodPost, "/api/v1/backlog", strings.NewReader(string(createPayload))))
	if createResponse.Code != http.StatusCreated {
		t.Fatalf("create: %d %s", createResponse.Code, createResponse.Body.String())
	}
	stored, err := h.Store().LoadItem(KindExecute, item.Name)
	if err != nil || stored.ExecutionLimits == nil || *stored.ExecutionLimits != *item.ExecutionLimits {
		t.Fatalf("creation response did not match persisted reviewed limits: %+v %v", stored.ExecutionLimits, err)
	}
	// A finalized, never-started plan reports DRAFT because status is computed
	// from phase activity. First execution must still be accept-able.
	client := acceptancePlanClient{plan: &sharedv1.Plan{Id: "plan-1", Slug: "plan-1", ContentHash: "sha256:accepted", Status: sharedv1.PlanStatus_PLAN_STATUS_DRAFT}}
	h.SetPlanClient(client)

	req := httptest.NewRequest(http.MethodPost, "/api/v1/backlog/execute/accept-me/plan-accept", strings.NewReader(`{}`))
	req = mux.SetURLVars(req, map[string]string{"kind": "execute", "name": "accept-me"})
	response := httptest.NewRecorder()
	h.AcceptPlan(response, req)
	if response.Code != http.StatusOK {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	saved, err := h.Store().LoadItem(KindExecute, "accept-me")
	if err != nil {
		t.Fatal(err)
	}
	if saved.PlanAcceptance == nil || saved.PlanAcceptance.Actor != "operator" || saved.PlanAcceptance.PlanContentHash != "sha256:accepted" || !PlanAcceptanceMatches(saved, "sha256:accepted") {
		t.Fatalf("saved acceptance = %#v", saved.PlanAcceptance)
	}
	if err := h.ValidateAcceptedPlan(context.Background(), saved); err != nil {
		t.Fatalf("accepted current plan rejected: %v", err)
	}
	// The execution owner must consume the actual acceptance written by the
	// handler, rather than a fixture hash generated by its own projection.
	registry, err := transitions.LoadDir(pathutil.ResolveScenarioRoot("swarm-manager") + "/.vrooli/swarm-transitions")
	if err != nil {
		t.Fatal(err)
	}
	owner := &acceptanceWorkflowOwner{}
	service := execution.NewService(execution.ServiceConfig{DataRoot: root, StorePath: filepath.Join(root, "execution-runs.json"), PlanRenderer: client, TransitionRegistry: registry, PhasedPlanWorkflow: owner})
	preflight, err := service.ProcessPreflight(t.Context(), "execute", saved.Name)
	if err != nil || !preflight.Ready {
		t.Fatalf("newly accepted adaptive item cannot execute: %+v %v", preflight, err)
	}
	queued, err := service.QueueBacklog(t.Context(), execution.CreateRequest{BacklogKind: "execute", BacklogName: saved.Name, Mode: execution.ModeManual})
	if err != nil {
		t.Fatal(err)
	}
	started, err := service.Start(t.Context(), queued.ExecutionID)
	if err != nil {
		t.Fatal(err)
	}
	grant := owner.invocation.EngagementGrant
	if grant == nil || grant.MaxTokens != int32(item.ExecutionLimits.MaxTokens) || grant.MaxWallTimeSeconds != int32(item.ExecutionLimits.MaxWallSeconds) || started.MaxSlices != item.ExecutionLimits.MaxSlices || owner.invocation.ApprovalDigest != started.ApprovalDigest || owner.invocation.GrantDigest != workflowcontract.GrantDigest(started.WorkflowGrant) {
		t.Fatalf("actual creation-to-dispatch path lost accepted grant: %+v %+v", started, owner.invocation)
	}
	amended := saved
	amended.ExecutionStrategy = ExecutionStrategyPhasedPlanDrain
	if PlanAcceptanceMatches(amended, "sha256:accepted") {
		t.Fatal("changed execution strategy retained the previous operator acceptance")
	}
	amended = saved
	amended.ExecutionLimits = saved.ExecutionLimits.Clone()
	amended.ExecutionLimits.MaxTokens++
	if PlanAcceptanceMatches(amended, "sha256:accepted") {
		t.Fatal("changed execution limits retained previous acceptance")
	}
	client.plan.ContentHash = "sha256:changed"
	h.SetPlanClient(client)
	if err := h.ValidateAcceptedPlan(context.Background(), saved); err == nil {
		t.Fatal("changed plan content remained eligible for adaptive execution")
	}
}

func TestAcceptPlanRejectsArchivedPlan(t *testing.T) {
	h, root := setupTestHandler(t)
	item := BacklogItem{Name: "archived", Title: "Archived", Status: StatusBacklog, Priority: 5, PlanRef: &PlanRef{Provider: PlanRefProviderPlanManager, PlanID: "plan-1", Slug: "plan-1", Role: PlanRefRoleExecutionSpec}}
	createTestItem(t, root, KindExecute, item)
	h.SetPlanClient(acceptancePlanClient{plan: &sharedv1.Plan{Id: "plan-1", Slug: "plan-1", ContentHash: "sha256:archived", Status: sharedv1.PlanStatus_PLAN_STATUS_ARCHIVED}})

	req := httptest.NewRequest(http.MethodPost, "/api/v1/backlog/execute/archived/plan-accept", strings.NewReader(`{}`))
	req = mux.SetURLVars(req, map[string]string{"kind": "execute", "name": "archived"})
	response := httptest.NewRecorder()
	h.AcceptPlan(response, req)
	if response.Code != http.StatusConflict {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
}

func TestExecutionConsumesAcceptedOptionalPlanReferences(t *testing.T) {
	for _, ref := range []PlanRef{
		{Provider: PlanRefProviderPlanManager, PlanID: "plan-1", Role: PlanRefRoleExecutionSpec},
		{Provider: PlanRefProviderPlanManager, Slug: "plan-1", Role: PlanRefRoleExecutionSpec},
	} {
		t.Run(ref.PlanID+"/"+ref.Slug, func(t *testing.T) {
			_, root := setupTestHandler(t)
			item := BacklogItem{Kind: KindExecute, Name: "optional-ref", Title: "Optional reference", Status: StatusBacklog, PlanRef: &ref}
			item.PlanAcceptance = &PlanAcceptance{Actor: "operator", PlanContentHash: "sha256:accepted", SubjectVersion: PlanAcceptanceSubjectVersion(item)}
			createTestItem(t, root, item.Kind, item)
			client := acceptancePlanClient{plan: &sharedv1.Plan{Id: "plan-1", Slug: "plan-1", ContentHash: "sha256:accepted"}}
			service := execution.NewService(execution.ServiceConfig{DataRoot: root, StorePath: filepath.Join(root, "execution-runs.json"), PlanRenderer: client})
			preflight, err := service.ProcessPreflight(t.Context(), "execute", item.Name)
			if err != nil || !preflight.Ready {
				t.Fatalf("omitted optional reference field changed acceptance identity: %+v %v", preflight, err)
			}
		})
	}
}

// [REQ:SWM-P0-004] acceptance gate: acceptance cleared when plan/contract changes
func TestPlanAcceptanceIsClearedWhenWorkContractChanges(t *testing.T) {
	item := BacklogItem{
		Kind: KindFix, Name: "example", Title: "before",
		PlanRef:        &PlanRef{Provider: PlanRefProviderPlanManager, PlanID: "plan-1", Slug: "plan-1", Role: PlanRefRoleExecutionSpec},
		PlanAcceptance: &PlanAcceptance{Actor: "operator", AcceptedAt: "now", PlanContentHash: "sha256:one", SubjectVersion: "version"},
	}
	title := "after"
	ApplyItemPatch(&item, ItemPatch{Title: &title})
	if item.PlanAcceptance != nil {
		t.Fatalf("scope edit retained acceptance: %#v", item.PlanAcceptance)
	}
}

func TestPlanAcceptanceSubjectVersionOmitsDefaultContinuationAndScopePolicy(t *testing.T) {
	item := BacklogItem{Kind: KindExecute, Name: "audio-tools-portable-voice-development", Title: "Audio", Status: StatusBacklog, Priority: 5}
	before := PlanAcceptanceSubjectVersion(item)
	item.Continuation = ContinuationManual
	item.ScopePolicy = ScopePolicyFixed
	after := PlanAcceptanceSubjectVersion(item)
	if before != after {
		t.Fatalf("default continuation/scope policy changed accepted subject version: before=%s after=%s", before, after)
	}
	item.Continuation = ContinuationUntilAllowance
	if PlanAcceptanceSubjectVersion(item) == after {
		t.Fatal("non-default continuation did not participate in accepted subject version")
	}
}
