services:
  home-assistant:
    image: homeassistant/home-assistant@sha256:a21689ef0510df9760ee11bab4d6b2fef3ed5c1a29ed9c3224271597a23729eb
    container_name: home-assistant
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: America/New_York
    volumes:
      - ${RESOURCE_CONFIG_DIR}:/config
      - /etc/localtime:/etc/localtime:ro
