#!/usr/bin/env bash
# Matrix Synapse Resource - Default Configuration
# This file defines default values for all configuration variables

# Port Configuration (from port registry)
export MATRIX_SYNAPSE_PORT="${MATRIX_SYNAPSE_PORT:-8008}"
export MATRIX_SYNAPSE_METRICS_PORT="${MATRIX_SYNAPSE_METRICS_PORT:-8009}"

# Server Configuration
export MATRIX_SYNAPSE_SERVER_NAME="${MATRIX_SYNAPSE_SERVER_NAME:-vrooli.local}"
export MATRIX_SYNAPSE_REPORT_STATS="${MATRIX_SYNAPSE_REPORT_STATS:-no}"
export MATRIX_SYNAPSE_ENABLE_REGISTRATION="${MATRIX_SYNAPSE_ENABLE_REGISTRATION:-true}"

# Database Configuration (uses postgres resource)
export MATRIX_SYNAPSE_DB_HOST="${MATRIX_SYNAPSE_DB_HOST:-localhost}"
export MATRIX_SYNAPSE_DB_PORT="${MATRIX_SYNAPSE_DB_PORT:-5433}"
export MATRIX_SYNAPSE_DB_NAME="${MATRIX_SYNAPSE_DB_NAME:-synapse}"
export MATRIX_SYNAPSE_DB_USER="${MATRIX_SYNAPSE_DB_USER:-synapse}"
export SYNAPSE_DB_PASSWORD="${SYNAPSE_DB_PASSWORD:-}"

# Security Configuration
export SYNAPSE_REGISTRATION_SECRET="${SYNAPSE_REGISTRATION_SECRET:-}"
export MATRIX_SYNAPSE_MACAROON_SECRET="${MATRIX_SYNAPSE_MACAROON_SECRET:-}"
export MATRIX_SYNAPSE_FORM_SECRET="${MATRIX_SYNAPSE_FORM_SECRET:-}"

# Federation Configuration
export MATRIX_SYNAPSE_FEDERATION_ENABLED="${MATRIX_SYNAPSE_FEDERATION_ENABLED:-false}"
export MATRIX_SYNAPSE_FEDERATION_PORT="${MATRIX_SYNAPSE_FEDERATION_PORT:-8448}"

# Media Configuration
export MATRIX_SYNAPSE_MAX_UPLOAD_SIZE="${MATRIX_SYNAPSE_MAX_UPLOAD_SIZE:-50M}"
export MATRIX_SYNAPSE_MEDIA_STORE_PATH="${MATRIX_SYNAPSE_MEDIA_STORE_PATH:-./data/media_store}"

# Performance Configuration
export MATRIX_SYNAPSE_CACHE_FACTOR="${MATRIX_SYNAPSE_CACHE_FACTOR:-0.5}"
export MATRIX_SYNAPSE_EVENT_CACHE_SIZE="${MATRIX_SYNAPSE_EVENT_CACHE_SIZE:-10K}"

# Directory Paths
export MATRIX_SYNAPSE_DATA_DIR="${MATRIX_SYNAPSE_DATA_DIR:-${HOME}/.vrooli/resources/matrix-synapse}"
export MATRIX_SYNAPSE_CONFIG_DIR="${MATRIX_SYNAPSE_CONFIG_DIR:-${MATRIX_SYNAPSE_DATA_DIR}/config}"
export MATRIX_SYNAPSE_LOG_DIR="${MATRIX_SYNAPSE_LOG_DIR:-${MATRIX_SYNAPSE_DATA_DIR}/logs}"

# Process Management
export MATRIX_SYNAPSE_PID_FILE="${MATRIX_SYNAPSE_PID_FILE:-${MATRIX_SYNAPSE_DATA_DIR}/synapse.pid}"
export MATRIX_SYNAPSE_LOG_FILE="${MATRIX_SYNAPSE_LOG_FILE:-${MATRIX_SYNAPSE_LOG_DIR}/homeserver.log}"

# Installation Configuration
export MATRIX_SYNAPSE_INSTALL_METHOD="${MATRIX_SYNAPSE_INSTALL_METHOD:-pip}"  # pip or docker
export MATRIX_SYNAPSE_VERSION="${MATRIX_SYNAPSE_VERSION:-latest}"

# Timeout Configuration
export MATRIX_SYNAPSE_STARTUP_TIMEOUT="${MATRIX_SYNAPSE_STARTUP_TIMEOUT:-60}"
export MATRIX_SYNAPSE_SHUTDOWN_TIMEOUT="${MATRIX_SYNAPSE_SHUTDOWN_TIMEOUT:-30}"
export MATRIX_SYNAPSE_HEALTH_CHECK_TIMEOUT="${MATRIX_SYNAPSE_HEALTH_CHECK_TIMEOUT:-5}"