// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  integrations: {
    mode: {
      label: "integrations.mode.label",
      loading: "integrations.mode.loading",
      off: "integrations.mode.off",
      passive: "integrations.mode.passive",
      full: "integrations.mode.full",
      unknown: "integrations.mode.unknown",
    },
    settings: {
      title: "integrations.settings.title",
      description: "integrations.settings.description",
      overrideLabel: "integrations.settings.overrideLabel",
      overrideAuto: "integrations.settings.overrideAuto",
      overrideForceOff: "integrations.settings.overrideForceOff",
      overrideForcePassive: "integrations.settings.overrideForcePassive",
      nameHeader: "integrations.settings.nameHeader",
      stateHeader: "integrations.settings.stateHeader",
      latencyHeader: "integrations.settings.latencyHeader",
      samplesHeader: "integrations.settings.samplesHeader",
      reasonHeader: "integrations.settings.reasonHeader",
      empty: "integrations.settings.empty",
      error: "integrations.settings.error",
      profileTitle: "integrations.settings.profileTitle",
      profileDescription: "integrations.settings.profileDescription",
      profileLabel: "integrations.settings.profileLabel",
      profileClient: "integrations.settings.profileClient",
      profileLocalControl: "integrations.settings.profileLocalControl",
      profileAutomation: "integrations.settings.profileAutomation",
      endpointLabel: "integrations.settings.endpointLabel",
      endpointPlaceholder: "integrations.settings.endpointPlaceholder",
      saveProfile: "integrations.settings.saveProfile",
      profileSaved: "integrations.settings.profileSaved",
      profileReady: "integrations.settings.profileReady",
      missingCapabilities: "integrations.settings.missingCapabilities",
      profileInvalidEndpoint: "integrations.settings.profileInvalidEndpoint",
    },
    state: {
      available: "integrations.state.available",
      degraded: "integrations.state.degraded",
      unavailable: "integrations.state.unavailable",
      unknown: "integrations.state.unknown",
      unspecified: "integrations.state.unspecified",
    },
  },
  search: {
    omnibox: {
      title: "search.omnibox.title",
      description: "search.omnibox.description",
      inputLabel: "search.omnibox.inputLabel",
      placeholder: "search.omnibox.placeholder",
      loading: "search.omnibox.loading",
      empty: "search.omnibox.empty",
      degraded: "search.omnibox.degraded",
    },
  },
  chat: {
    title: "chat.title",
    sidebar: {
      label: "chat.sidebar.label",
      description: "chat.sidebar.description",
      newChat: "chat.sidebar.newChat",
      newAgent: "chat.sidebar.newAgent",
      newGroup: "chat.sidebar.newGroup",
      newChatTitle: "chat.sidebar.newChatTitle",
      newAgentTitle: "chat.sidebar.newAgentTitle",
      newGroupTitle: "chat.sidebar.newGroupTitle",
      ungrouped: "chat.sidebar.ungrouped",
      empty: "chat.sidebar.empty",
    },
    controls: {
      mode: "chat.controls.mode",
      modeLlm: "chat.controls.modeLlm",
      modeAgent: "chat.controls.modeAgent",
      model: "chat.controls.model",
      modelFast: "chat.controls.modelFast",
      modelReasoning: "chat.controls.modelReasoning",
      webSearch: "chat.controls.webSearch",
    },
    empty: {
      description: "chat.empty.description",
    },
    message: {
      roleUser: "chat.message.roleUser",
      roleAssistant: "chat.message.roleAssistant",
      roleAgent: "chat.message.roleAgent",
      branchCount: "chat.message.branchCount",
      previousBranch: "chat.message.previousBranch",
      nextBranch: "chat.message.nextBranch",
      edit: "chat.message.edit",
      editPrompt: "chat.message.editPrompt",
      regenerate: "chat.message.regenerate",
      searchAttachments: "chat.message.searchAttachments",
      agentActivity: "chat.message.agentActivity",
      streaming: "chat.message.streaming",
      speak: "chat.message.speak",
      stopSpeaking: "chat.message.stopSpeaking",
      speechUnavailable: "chat.message.speechUnavailable",
      speechFailed: "chat.message.speechFailed",
    },
    composer: {
      label: "chat.composer.label",
      placeholder: "chat.composer.placeholder",
      skills: "chat.composer.skills",
      skillsPlaceholder: "chat.composer.skillsPlaceholder",
      send: "chat.composer.send",
      stop: "chat.composer.stop",
      voiceStart: "chat.composer.voiceStart",
      voiceStop: "chat.composer.voiceStop",
      voiceUnavailable: "chat.composer.voiceUnavailable",
    },
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
  surfaces: {
    title: "surfaces.title",
    refresh: "surfaces.refresh",
    description: "surfaces.description",
    loading: "surfaces.loading",
    refreshFailed: "surfaces.refreshFailed",
    sourceUnavailable: "surfaces.sourceUnavailable",
    empty: "surfaces.empty",
    select: "surfaces.select",
    none: "surfaces.none",
    unavailableSelection: "surfaces.unavailableSelection",
    selectionMissing: "surfaces.selectionMissing",
    owner: "surfaces.owner",
    terminal: "surfaces.terminal",
    desktop: "surfaces.desktop",
    browser: "surfaces.browser",
    scenario: "surfaces.scenario",
    device: "surfaces.device",
    stale: "surfaces.stale",
    ready: "surfaces.ready",
    denied: "surfaces.denied",
    unavailable: "surfaces.unavailable",
    checkRequired: "surfaces.checkRequired",
    inspectOnly: "surfaces.inspectOnly",
    devicePanelTitle: "surfaces.devicePanelTitle",
    devicePanelDescription: "surfaces.devicePanelDescription",
    deviceButtons: "surfaces.deviceButtons",
    deviceProperties: "surfaces.deviceProperties",
    deviceCapabilityUnavailable: "surfaces.deviceCapabilityUnavailable",
  },
  desktop: {
    title: "desktop.title",
    email: "desktop.email",
    password: "desktop.password",
    signIn: "desktop.signIn",
    register: "desktop.register",
    signedIn: "desktop.signedIn",
    signOut: "desktop.signOut",
    observe: "desktop.observe",
    control: "desktop.control",
    observeActive: "desktop.observeActive",
    controlActive: "desktop.controlActive",
    refresh: "desktop.refresh",
    stop: "desktop.stop",
    failed: "desktop.failed",
    uncertain: "desktop.uncertain",
    image: "desktop.image",
    clickImage: "desktop.clickImage",
    scrollCenter: "desktop.scrollCenter",
    scrollUp: "desktop.scrollUp",
    scrollDown: "desktop.scrollDown",
    scrollLeft: "desktop.scrollLeft",
    scrollRight: "desktop.scrollRight",
    applicationFields: "desktop.applicationFields",
    insertDraft: "desktop.insertDraft",
    inspectApplication: "desktop.inspectApplication",
    editableField: "desktop.editableField",
    chooseField: "desktop.chooseField",
    unnamedField: "desktop.unnamedField",
    characterPosition: "desktop.characterPosition",
    fieldsExpired: "desktop.fieldsExpired",
    insertText: "desktop.insertText",
    discoverApplications: "desktop.discoverApplications",
    application: "desktop.application",
    chooseApplication: "desktop.chooseApplication",
    unnamedApplication: "desktop.unnamedApplication",
    noApplications: "desktop.noApplications",
    applicationsExpired: "desktop.applicationsExpired",
    window: "desktop.window",
    chooseWindow: "desktop.chooseWindow",
    unnamedWindow: "desktop.unnamedWindow",
    noWindows: "desktop.noWindows",
    noFields: "desktop.noFields",
    reauthenticate: "desktop.reauthenticate",
    recoverSignIn: "desktop.recoverSignIn",
  },
  desktopFlows: {
    title: "desktopFlows.title",
    help: "desktopFlows.help",
    failed: "desktopFlows.failed",
    insert: "desktopFlows.insert",
    assert: "desktopFlows.assert",
    window: "desktopFlows.window",
    field: "desktopFlows.field",
    text: "desktopFlows.text",
    expected: "desktopFlows.expected",
    position: "desktopFlows.position",
    remove: "desktopFlows.remove",
    addInsert: "desktopFlows.addInsert",
    addAssert: "desktopFlows.addAssert",
    run: "desktopFlows.run",
    check: "desktopFlows.check",
    passed: "desktopFlows.passed",
    uncertain: "desktopFlows.uncertain",
    context: "desktopFlows.context",
    save: "desktopFlows.save",
    savedId: "desktopFlows.savedId",
    version: "desktopFlows.version",
    load: "desktopFlows.load",
    loaded: "desktopFlows.loaded",
    replay: "desktopFlows.replay",
  },
  companion: {
    presentation: "companion.presentation",
    expanded: "companion.expanded",
    palette: "companion.palette",
    pill: "companion.pill",
    stopChat: "companion.stopChat",
    stopDesktop: "companion.stopDesktop",
    failed: "companion.failed",
    workspace: "companion.workspace",
    chat: "companion.chat",
    desktop: "companion.desktop",
    shortcut: "companion.shortcut",
    contextCapturing: "companion.contextCapturing",
    dismissContext: "companion.dismissContext",
    contextReady: "companion.contextReady",
    contextUnavailable: "companion.contextUnavailable",
    shortcutSetting: "companion.shortcutSetting",
    applyShortcut: "companion.applyShortcut",
    shortcutUnavailable: "companion.shortcutUnavailable",
    hidden: "companion.hidden",
    checkStatus: "companion.checkStatus",
    agentUncertain: "companion.agentUncertain",
    quitTitle: "companion.quitTitle",
    quitTasks: "companion.quitTasks",
    cancelQuit: "companion.cancelQuit",
    keepRunning: "companion.keepRunning",
    stopAndQuit: "companion.stopAndQuit",
    recovering: "companion.recovering",
    recoveryFailed: "companion.recoveryFailed",
    previewContext: "companion.previewContext",
    previewLoading: "companion.previewLoading",
    previewAlt: "companion.previewAlt",
    previewLocal: "companion.previewLocal",
    closePreview: "companion.closePreview",
    previewFailed: "companion.previewFailed",
    selectRegion: "companion.selectRegion",
    drawAnnotation: "companion.drawAnnotation",
    resetAnnotations: "companion.resetAnnotations",
    annotationOverlay: "companion.annotationOverlay",
    regionCoordinates: "companion.regionCoordinates",
    width: "companion.width",
    retainContext: "companion.retainContext",
    contextRetained: "companion.contextRetained",
    contextPending: "companion.contextPending",
    recoverContext: "companion.recoverContext",
    deleteRetainedContext: "companion.deleteRetainedContext",
    retainContextFailed: "companion.retainContextFailed",
    cancelContextImport: "companion.cancelContextImport",
    previewRenderedContext: "companion.previewRenderedContext",
    renderedContextAlt: "companion.renderedContextAlt",
    attachContext: "companion.attachContext",
    detachContext: "companion.detachContext",
    contextAttached: "companion.contextAttached",
    embeddedUnavailable: "companion.embeddedUnavailable",
    retryEmbedded: "companion.retryEmbedded",
    x: "companion.x",
    y: "companion.y",
    height: "companion.height",
  },
} as const;

export type Strings = typeof strings;
