/**
 * Desktop App Main Process
 *
 * DOC: docs/internal/SEAMS.md#main-process
 *
 * This is the orchestration layer for the Electron desktop application.
 * All domain logic has been extracted into focused modules:
 * - telemetry/  - Event recording and upload
 * - runtime/    - Bundled runtime process management
 * - storage/    - Sandboxed file system access
 * - ipc/        - IPC handler registration
 * - auth/       - Authentication management
 * - bundle/     - Bundle manifest validation
 * - splash/     - Splash window management
 * - window-state/ - Window position persistence
 */

import { app, BrowserWindow, net as electronNet, session, shell, Menu, ipcMain, dialog, Tray, nativeImage, clipboard, safeStorage, screen, contentTracing } from "electron";
import { type ChildProcess, fork, spawn } from "node:child_process";
import * as nodeNet from "node:net";
import { createHash, randomUUID } from "node:crypto";
import { createServer } from "node:http";
import * as fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { autoUpdater } from "electron-updater";

// DOC: docs/internal/SEAMS.md#splash-window-module
import {
    type ISplashWindowManager,
    type SplashStatus,
    type StartupPhase,
    type ReadinessConfig,
    createSplashManager,
    createElectronReadinessChecker,
    checkServerReadiness,
    DEFAULT_READINESS_CONFIG,
    PHASE_MESSAGES,
} from "./splash";

// DOC: docs/internal/SEAMS.md#window-state-module
import {
    type IWindowStateManager,
    WindowStateManager,
    createWindowStateStorage,
    createDisplayProvider,
} from "./window-state";

// DOC: docs/internal/SEAMS.md#telemetry-module
import {
    type ITelemetryRecorder,
    type ITelemetryUploader,
    type TelemetryLevel,
    createTelemetryRecorder,
    createTelemetryUploader,
    createFetchHttpClient,
    createNodeFileSystem as createTelemetryFileSystem,
    createNodePathUtils as createTelemetryPathUtils,
    createLaunchTraceRecorder,
    type LaunchTraceRecorder,
    createLaunchProfiler,
    type LaunchProfiler,
    type ProfileArtifact,
    type ProfileMode,
} from "./telemetry";

// DOC: docs/internal/SEAMS.md#runtime-module
import {
    type IRuntimeControlClient,
    type RuntimeExitInfo,
    type RuntimeDiagnostics,
    type RuntimeReadyResponse,
    type RuntimePortsResponse,
    type RuntimeTelemetryResponse,
    type RuntimeSecretsResponse,
    type RuntimeSecret,
    type RuntimeValidationResponse,
    createInitialExitInfo,
    createExitTracker,
    createRuntimeControlClient,
    createFetchRuntimeHttpClient,
    createRealTimer,
    createNodeRuntimeFileSystem,
    matchErrorPattern,
    DEFAULT_ERROR_PATTERNS,
} from "./runtime";

// DOC: docs/internal/SEAMS.md#storage-module
import {
    type IAppStorage,
    createAppStorage,
    createNodeStorageFileSystem,
    createNodeStoragePathUtils,
} from "./storage";

// DOC: docs/internal/SEAMS.md#ipc-module
import {
    registerAllHandlers,
    type HandlerRegistration,
} from "./ipc";

// DOC: docs/internal/SEAMS.md#auth-module
import {
    type IAuthManager,
    createAuthManager,
    createElectronSafeStorage,
    createElectronAuthHttpClient,
    createElectronShell,
    createRealAuthTimer,
    createRealUuidGenerator,
} from "./auth";

// DOC: docs/internal/SEAMS.md#bundle-module
import {
    type BundleValidationResult,
    validateBundlePreFlight,
    createNodeBundleFileSystem,
    createNodeBundlePathUtils,
    createRealPlatformInfo,
} from "./bundle";
import { isOwnedValidationURL, readDesktopValidationContext, validationHeaders, validationOrigins } from "./runtime/validation-context";

// ===== TEMPLATE CONFIGURATION - GENERATED BY SCENARIO-TO-DESKTOP =====
const APP_CONFIG = {
    APP_NAME: "{{APP_NAME}}",
    APP_DISPLAY_NAME: "{{APP_DISPLAY_NAME}}",
    APP_VERSION: "{{VERSION}}",
    APP_URL: "{{APP_URL}}",
    SERVER_TYPE: "{{SERVER_TYPE}}" as "node" | "static" | "external" | "executable",
    SERVER_PORT: {{SERVER_PORT}},
    SERVER_PATH: "{{SERVER_PATH}}",
    API_ENDPOINT: "{{API_ENDPOINT}}",
    DEPLOYMENT_MODE: "{{DEPLOYMENT_MODE}}" as "external-server" | "cloud-api" | "bundled",
    WINDOW_WIDTH: {{WINDOW_WIDTH}},
    WINDOW_HEIGHT: {{WINDOW_HEIGHT}},
    WINDOW_BACKGROUND: "{{WINDOW_BACKGROUND}}",
    WINDOW_TITLE: "{{APP_DISPLAY_NAME}}",
    ENABLE_SPLASH: {{ENABLE_SPLASH}},
    ENABLE_MENU: {{ENABLE_MENU}},
    ENABLE_SYSTEM_TRAY: {{ENABLE_SYSTEM_TRAY}},
    ENABLE_AUTO_UPDATER: {{ENABLE_AUTO_UPDATER}},
    ENABLE_SINGLE_INSTANCE: {{ENABLE_SINGLE_INSTANCE}},
    ENABLE_DEV_TOOLS: {{ENABLE_DEV_TOOLS}},
    SERVER_CHECK_INTERVAL_MS: 500,
    SERVER_CHECK_TIMEOUT_MS: 30000,
};

const LOCAL_VROOLI_BOOTSTRAP = {
    ENABLE: {{AUTO_MANAGE_VROOLI}},
    SCENARIO_NAME: "{{SCENARIO_NAME}}",
    VROOLI_BINARY: "{{VROOLI_BINARY_PATH}}",
};

const BUNDLED_RUNTIME = {
    SUPPORTED: {{BUNDLED_RUNTIME_SUPPORTED}},
    ROOT: "{{BUNDLED_RUNTIME_ROOT}}",
    IPC_HOST: "{{BUNDLED_RUNTIME_IPC_HOST}}",
    IPC_PORT: {{BUNDLED_RUNTIME_IPC_PORT}},
    TOKEN_REL: "{{BUNDLED_RUNTIME_TOKEN_PATH}}",
    UI_SERVICE: "{{BUNDLED_RUNTIME_UI_SERVICE}}",
    UI_PORT_NAME: "{{BUNDLED_RUNTIME_UI_PORT_NAME}}",
    TELEMETRY_UPLOAD_URL: "{{BUNDLED_RUNTIME_TELEMETRY_UPLOAD_URL}}",
    DOCS_URL: "docs/deployment/tiers/tier-2-desktop.md",
};

// Port configuration from service.json
const PORTS: Record<string, { envVar: string; port: number }> = {{PORTS_CONFIG}};

const UPDATE_CONFIG = {
    CHANNEL: "{{UPDATE_CHANNEL}}" as "dev" | "beta" | "stable",
    PROVIDER: "{{UPDATE_PROVIDER}}" as "github" | "generic" | "none",
    AUTO_CHECK: {{UPDATE_AUTO_CHECK}},
    SERVER_URL: "{{UPDATE_SERVER_URL}}",
};

const AUTH_CONFIG = {
    PROTOCOL: "vrooli",
    LPBS_URL: "{{LPBS_URL}}",
    TOKENS_FILE: "auth/tokens.enc",
    USER_FILE: "auth/user.json",
    TOKEN_REFRESH_BUFFER_MS: 5 * 60 * 1000,
};

// ===== MODULE STATE =====
let serverProcess: ChildProcess | null = null;
let runtimeProcess: ChildProcess | null = null;
let mainWindow: BrowserWindow | null = null;
let splashManager: ISplashWindowManager | null = null;
let windowStateManager: IWindowStateManager | null = null;
let tray: Tray | null = null;
let ipcRegistration: HandlerRegistration | null = null;

// Module instances (initialized in app.whenReady)
let telemetryRecorder: ITelemetryRecorder | null = null;
let telemetryUploader: ITelemetryUploader | null = null;
let appStorage: IAppStorage | null = null;
let authManager: IAuthManager | null = null;
let runtimeControlClient: IRuntimeControlClient | null = null;
let exitTracker: ReturnType<typeof createExitTracker> | null = null;

// Session tracking
const sessionId = randomUUID();
let sessionKind = "app";
let appSessionStartedAt: string | null = null;
let appSessionReadyAt: string | null = null;
let appSessionFailureMessage: string | null = null;
let appSessionRecorded = false;
let runtimeAppDataRoot: string | null = null;

async function runLoopbackAuthorization(
    buildAuthorizationURL: (redirectURI: string) => string,
): Promise<{ code: string; state: string; redirectURI: string }> {
    let listenerRedirectURI = "";
    return new Promise((resolve, reject) => {
        const server = createServer((request, response) => {
            const callbackURL = new URL(request.url || "/", "http://127.0.0.1");
            if (callbackURL.pathname !== "/callback") {
                response.statusCode = 404;
                response.end();
                return;
            }
            response.end("Authentication complete. You may return to the app.");
            server.close();
            resolve({
                code: callbackURL.searchParams.get("code") || "",
                state: callbackURL.searchParams.get("state") || "",
                redirectURI: listenerRedirectURI,
            });
        });
        server.once("error", reject);
        server.listen(0, "127.0.0.1", () => {
            const address = server.address();
            if (!address || typeof address === "string") {
                reject(new Error("loopback listener did not expose a port"));
                return;
            }
            listenerRedirectURI = `http://127.0.0.1:${address.port}/callback`;
            void shell.openExternal(buildAuthorizationURL(listenerRedirectURI)).catch(reject);
        });
    });
}

// Derived configuration
const SERVER_URL = APP_CONFIG.SERVER_TYPE === "external"
    ? APP_CONFIG.SERVER_PATH
    : `http://localhost:${APP_CONFIG.SERVER_PORT}`;
const desktopValidationContext = readDesktopValidationContext(process.env);
const desktopValidationAPIURL = process.env.VROOLI_VALIDATION_API_URL?.trim() ?? "";
const desktopValidationRendererURL = process.env.VROOLI_VALIDATION_RENDERER_URL?.trim() ?? "";
// Validation launches may point the generated renderer at the live scenario
// UI port. The baked-in template URL is only a build-time default and is not
// necessarily the port assigned to the scenario instance under test.
const desktopValidationTargetURL = desktopValidationRendererURL
    ? desktopValidationRendererURL
    : SERVER_URL;
// Chromium may expose the local renderer as 127.0.0.1 even when the generated
// app configuration names localhost. Treat that loopback alias as the same
// target-owned renderer origin; do not broaden this to arbitrary hosts.
const desktopValidationOrigins = validationOrigins([
    APP_CONFIG.APP_URL,
    APP_CONFIG.API_ENDPOINT,
    APP_CONFIG.SERVER_PATH,
    SERVER_URL,
    `http://127.0.0.1:${APP_CONFIG.SERVER_PORT}`,
    desktopValidationRendererURL,
    desktopValidationAPIURL,
]);

function installDesktopValidationPropagation(): void {
    if (!desktopValidationContext) return;
    const headers = validationHeaders(desktopValidationContext);
    let validationAPI: URL | null = null;
    try {
        validationAPI = desktopValidationAPIURL ? new URL(desktopValidationAPIURL) : null;
    } catch {
        validationAPI = null;
    }
    if (validationAPI) {
        session.defaultSession.webRequest.onBeforeRequest({ urls: ["<all_urls>"] }, (details, callback) => {
            try {
                const requestURL = new URL(details.url);
                if (requestURL.pathname.startsWith("/api/") && isOwnedValidationURL(details.url, desktopValidationOrigins) && requestURL.origin !== validationAPI?.origin) {
                    requestURL.protocol = validationAPI.protocol;
                    requestURL.host = validationAPI.host;
                    callback({ cancel: false, redirectURL: requestURL.toString() });
                    return;
                }
            } catch {
                // Invalid URLs are left to Chromium's normal request handling.
            }
            callback({ cancel: false });
        });
    }
    session.defaultSession.webRequest.onBeforeSendHeaders({ urls: ["<all_urls>"] }, (details, callback) => {
        if (isOwnedValidationURL(details.url, desktopValidationOrigins)) {
            details.requestHeaders = { ...details.requestHeaders, ...headers };
        }
        callback({ cancel: false, requestHeaders: details.requestHeaders });
    });
}
const shouldBootstrapLocalVrooli = APP_CONFIG.DEPLOYMENT_MODE === "external-server"
    && LOCAL_VROOLI_BOOTSTRAP.ENABLE
    && Boolean(LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME);
const isBundledMode = APP_CONFIG.DEPLOYMENT_MODE === "bundled";
const isSmokeTest = process.argv.includes("--smoke-test") || process.env.SMOKE_TEST === "1";
// Test harness only: accepts the normal update-ready confirmation after the
// updater has verified and downloaded an update. Regular desktop sessions
// retain the user-facing confirmation dialog.
const isUpdateApplyTest = process.env.VROOLI_DESKTOP_UPDATE_APPLY_TEST === "1";
if (isSmokeTest) sessionKind = "smoke_test";
const smokeTestUploadURL = process.env.SMOKE_TEST_UPLOAD_URL || "";
const smokeTestTimeoutCandidate = Number(process.env.SMOKE_TEST_TIMEOUT_MS || "");
const smokeTestTimeoutMs = Number.isFinite(smokeTestTimeoutCandidate) && smokeTestTimeoutCandidate > 0
    ? smokeTestTimeoutCandidate
    : APP_CONFIG.SERVER_CHECK_TIMEOUT_MS;
// Demo mode: after the headless smoke test passes, the Go service launches
// the app a second time WITHOUT --smoke-test to capture the real startup
// experience (splash screen, window frame, natural positioning) on video.
const isSmokeTestDemo = process.env.SMOKE_TEST_DEMO === "1";
// The smoke-test service sets this for the full scripted desktop journey.
// Keep a long safe fallback for older launchers that omit the variable.
const smokeTestDemoHoldMs = Number(process.env.SMOKE_TEST_DEMO_HOLD_MS) || 30000;

const launchTrace: LaunchTraceRecorder = createLaunchTraceRecorder({
    runId: process.env.SMOKE_TEST_RUN_ID,
    runKind: isSmokeTestDemo ? "demo" : "protocol",
    tracePath: process.env.S2D_TRACE_PATH,
    record: (event, details, level) => recordTelemetry(event, details, level),
});
const profileModeValue = process.env.S2D_PROFILE_MODE?.trim() || "disabled";
const profileMode: ProfileMode = ["disabled", "chromium", "cpu", "heap", "all"].includes(profileModeValue) ? profileModeValue as ProfileMode : "disabled";
const launchProfiler: LaunchProfiler = createLaunchProfiler(profileMode, process.env.S2D_PROFILE_DIR || path.join(app.getPath("userData"), "performance"), {
    startChromium: () => contentTracing.startRecording({ included_categories: ["blink", "browser", "gpu", "renderer", "v8"] }),
    stopChromium: (filePath) => contentTracing.stopRecording(filePath).then(() => undefined),
});
let profilerStartError = "";
let demoTraceFinalizing = false;
let demoRecordingEnded = false;

// Stability check configuration
const POST_SUCCESS_STABILITY_DELAY_MS = 2000;
const STABILITY_CHECK_INTERVAL_MS = 200;

// Runtime control configuration (mutable for port allocation)
const RUNTIME_CONTROL = {
    ENABLED: (isBundledMode && BUNDLED_RUNTIME.SUPPORTED) || Boolean(
        process.env.RUNTIME_CONTROL_HOST ||
        process.env.RUNTIME_CONTROL_PORT ||
        process.env.RUNTIME_CONTROL_TOKEN_PATH ||
        process.env.RUNTIME_TELEMETRY_UPLOAD_URL
    ),
    HOST: process.env.RUNTIME_CONTROL_HOST || BUNDLED_RUNTIME.IPC_HOST || "127.0.0.1",
    PORT: Number(process.env.RUNTIME_CONTROL_PORT || BUNDLED_RUNTIME.IPC_PORT || 47710),
    TOKEN_PATH_ENV: process.env.RUNTIME_CONTROL_TOKEN_PATH || "",
    TELEMETRY_UPLOAD_URL: process.env.RUNTIME_TELEMETRY_UPLOAD_URL || BUNDLED_RUNTIME.TELEMETRY_UPLOAD_URL || "",
    LOG_LINES: Number(process.env.RUNTIME_CONTROL_LOG_LINES || 200),
};

// Local Vrooli state
const localVrooliRuntime = { startedByApp: false, vrooliBinary: "" };
let bootstrapStateCache: { vrooliPath?: string; setupCompleted?: boolean } | null = null;
let bootstrapStatePath: string | null = null;

// ===== SMOKE TEST PROTOCOL =====
const SmokeTestProtocol = {
    init: () => console.info(`SMOKE_TEST_INIT=started session_id=${sessionId}`),
    ready: () => console.info("SMOKE_TEST_READY=true"),
    result: (passed: boolean, message?: string) => {
        console.info(passed ? "SMOKE_TEST_RESULT=passed" : `SMOKE_TEST_RESULT=failed ${message || ""}`);
    },
    upload: (ok: boolean, error?: string) => {
        console.info(ok ? "SMOKE_TEST_UPLOAD=ok" : `SMOKE_TEST_UPLOAD=error ${error || ""}`);
    },
    exit: () => console.info("SMOKE_TEST_EXIT=clean"),
    error: (kind: "config" | "network" | "runtime" | "validation", message: string) => {
        console.info(`SMOKE_TEST_ERROR kind=${kind} msg="${message.replace(/"/g, '\\"')}"`);
    },
    stage: {
        bundleResolving: () => console.info("SMOKE_TEST_STAGE=bundle_resolving"),
        runtimeStarting: () => console.info("SMOKE_TEST_STAGE=runtime_starting"),
        waitingForToken: () => console.info("SMOKE_TEST_STAGE=waiting_for_token"),
        runtimeHealthz: () => console.info("SMOKE_TEST_STAGE=runtime_healthz"),
        runtimeReadyz: () => console.info("SMOKE_TEST_STAGE=runtime_readyz"),
        runtimePorts: () => console.info("SMOKE_TEST_STAGE=runtime_ports"),
        uiServerCheck: () => console.info("SMOKE_TEST_STAGE=ui_server_check"),
    },
};

// ===== HELPER FUNCTIONS =====

function delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

// Deterministic launch-latency seam used by generated smoke fixtures. It is
// deliberately opt-in, bounded, and inactive for normal desktop sessions.
function configuredStartupDelay(phase: string): number {
    if (!isSmokeTest) return 0;
    const candidate = Number(process.env[`S2D_TEST_DELAY_${phase.toUpperCase()}`] || 0);
    if (!Number.isFinite(candidate) || candidate <= 0) return 0;
    return Math.min(Math.floor(candidate), 30_000);
}

async function applyStartupDelay(phase: string): Promise<void> {
    const durationMs = configuredStartupDelay(phase);
    if (durationMs <= 0) return;
    await recordTelemetry("launch_fixture_delay", { phase, duration_ms: durationMs });
    await delay(durationMs);
}

async function pathExists(filePath: string): Promise<boolean> {
    try {
        await fs.promises.access(filePath);
        return true;
    } catch {
        return false;
    }
}

function getRuntimeAppDataRoot(): string {
    if (runtimeAppDataRoot) return runtimeAppDataRoot;
    runtimeAppDataRoot = path.join(app.getPath("userData"), "runtime");
    return runtimeAppDataRoot;
}

async function recordTelemetry(event: string, details: Record<string, unknown> = {}, level: TelemetryLevel = "info"): Promise<void> {
    if (!telemetryRecorder) return;
    await telemetryRecorder.record(event, details, level);
}

async function stopLaunchProfiler(): Promise<ProfileArtifact[]> {
    const artifacts = await launchProfiler.stop();
    if (artifacts.length > 0) {
        await recordTelemetry("profiling_completed", { mode: profileMode, artifacts: artifacts.map((artifact) => ({ kind: artifact.kind, path: artifact.path, checksum: artifact.checksum, size_bytes: artifact.sizeBytes, available: artifact.available, reason: artifact.reason })) });
    }
    if (profilerStartError) await recordTelemetry("profiling_unavailable", { mode: profileMode, reason: profilerStartError }, "warn");
    return artifacts;
}

async function startLaunchProfiler(): Promise<void> {
    try {
        await launchProfiler.start();
    } catch (error) {
        profilerStartError = String(error);
        await recordTelemetry("profiling_unavailable", { mode: profileMode, reason: profilerStartError }, "warn");
    }
}

async function finalizeDemoTrace(): Promise<void> {
    if (!isSmokeTestDemo || demoTraceFinalizing) return;
    demoTraceFinalizing = true;
    if (!demoRecordingEnded) {
        demoRecordingEnded = true;
        await launchTrace.emit("recording_ended", "screen-recorder", "recorder");
    }
    await launchTrace.complete();
    await stopLaunchProfiler();
    await shutdownRuntime();
    app.quit();
    process.exit(0);
}

async function recordAppSessionOutcome(reason?: string): Promise<void> {
    if (appSessionRecorded || !telemetryRecorder) return;
    const failedReason = appSessionFailureMessage || reason || (appSessionReadyAt ? "" : "app_exit_before_ready");
    const succeeded = failedReason === "";
    await telemetryRecorder.record(
        succeeded ? "app_session_succeeded" : "app_session_failed",
        { started_at: appSessionStartedAt, ready_at: appSessionReadyAt, reason: failedReason },
        succeeded ? "info" : "error"
    );
    appSessionRecorded = true;
}

// ===== RUNTIME CONTROL CLIENT INTEGRATION =====

async function resolveRuntimeTokenPath(): Promise<string | null> {
    if (!RUNTIME_CONTROL.ENABLED) return null;
    if (RUNTIME_CONTROL.TOKEN_PATH_ENV) return RUNTIME_CONTROL.TOKEN_PATH_ENV;
    if (!app.isReady()) await app.whenReady();
    const rel = BUNDLED_RUNTIME.TOKEN_REL || "runtime/auth-token";
    return path.join(app.getPath("userData"), rel);
}

async function initializeRuntimeControlClient(): Promise<void> {
    if (!RUNTIME_CONTROL.ENABLED) return;
    const tokenPath = await resolveRuntimeTokenPath();
    // DOC: docs/internal/SEAMS.md#runtime-control-client
    // Factory order: (http, fs, timer, config) - matches control-client.ts signature
    runtimeControlClient = createRuntimeControlClient(
        createFetchRuntimeHttpClient(),              // Uses global fetch (no argument needed)
        createNodeRuntimeFileSystem(fs.promises),    // Requires fs.promises, not fs
        createRealTimer(),                           // Real timer for production
        {
            enabled: RUNTIME_CONTROL.ENABLED,
            host: RUNTIME_CONTROL.HOST,
            port: RUNTIME_CONTROL.PORT,
            tokenPath: tokenPath ?? "",              // Empty string if undefined (module handles this)
            telemetryUploadUrl: RUNTIME_CONTROL.TELEMETRY_UPLOAD_URL,
            logLines: 100,                           // Default log tail lines for diagnostics
        }
    );
}

async function collectRuntimeDiagnostics(): Promise<RuntimeDiagnostics> {
    if (!runtimeControlClient) throw new Error("Runtime control client not initialized");
    const [ready, ports, telemetry] = await Promise.all([
        runtimeControlClient.request<RuntimeReadyResponse>("/readyz"),
        runtimeControlClient.request<RuntimePortsResponse>("/ports"),
        runtimeControlClient.request<RuntimeTelemetryResponse>("/telemetry"),
    ]);
    const logs: Record<string, string> = {};
    const services = new Set<string>();
    Object.keys((ready as RuntimeReadyResponse)?.details || {}).forEach(svc => services.add(svc));
    Object.keys((ports as RuntimePortsResponse)?.services || {}).forEach(svc => services.add(svc));
    for (const serviceId of services) {
        try {
            const logData = await runtimeControlClient.request<string>(
                `/logs/tail?serviceId=${encodeURIComponent(serviceId)}&lines=${RUNTIME_CONTROL.LOG_LINES}`,
                { expectText: true }
            );
            if (typeof logData === "string") logs[serviceId] = logData;
        } catch (error) {
            logs[serviceId] = `Failed to load logs: ${error}`;
        }
    }
    const diagnostics: RuntimeDiagnostics = { ready: ready as RuntimeReadyResponse, ports: ports as RuntimePortsResponse, logs };
    if ((ready as RuntimeReadyResponse)?.gpu) diagnostics.gpu = (ready as RuntimeReadyResponse).gpu;
    const tel = telemetry as RuntimeTelemetryResponse;
    if (tel?.path) diagnostics.telemetryPath = tel.path;
    if (tel?.upload_url) diagnostics.telemetryUploadUrl = tel.upload_url;
    return diagnostics;
}

async function showRuntimeDiagnostics(): Promise<void> {
    if (!RUNTIME_CONTROL.ENABLED) {
        await dialog.showMessageBox({ type: "info", title: "Runtime diagnostics unavailable", message: "Runtime control is disabled for this build." });
        return;
    }
    try {
        const diagnostics = await collectRuntimeDiagnostics();
        const messageLines = [`Ready: ${diagnostics.ready.ready ? "yes" : "no"}`, `Services: ${Object.keys(diagnostics.ports.services || diagnostics.ready.details || {}).length}`];
        const detailLines: string[] = [];
        // Build detail lines (GPU, readiness, ports, logs)
        const gpuInfo = diagnostics.gpu || diagnostics.ready.gpu;
        if (gpuInfo) {
            detailLines.push(`GPU: ${gpuInfo.available ? "available" : "not available"}${gpuInfo.method ? ` via ${gpuInfo.method}` : ""}${gpuInfo.reason ? ` (${gpuInfo.reason})` : ""}`);
        }
        for (const [svc, info] of Object.entries(diagnostics.ready.details || {})) {
            detailLines.push(`- ${svc}: ${info.ready ? "ready" : "not ready"}${info.message || info.reason ? ` (${info.message || info.reason})` : ""}`);
        }
        if (diagnostics.ports.services) {
            detailLines.push("Ports:");
            for (const [svc, svcPorts] of Object.entries(diagnostics.ports.services)) {
                detailLines.push(`- ${svc}: ${Object.entries(svcPorts as Record<string, number>).map(([n, v]) => `${n}=${v}`).join(", ")}`);
            }
        }
        const buttons: string[] = ["Close"];
        const uploadURL = RUNTIME_CONTROL.TELEMETRY_UPLOAD_URL || diagnostics.telemetryUploadUrl || "";
        if (diagnostics.telemetryPath) buttons.unshift("Copy telemetry path");
        if (uploadURL && diagnostics.telemetryPath) buttons.unshift("Upload telemetry");
        const result = await dialog.showMessageBox({
            type: diagnostics.ready.ready ? "info" : "warning",
            title: "Bundled runtime diagnostics",
            message: messageLines.join("\n"),
            detail: detailLines.join("\n"),
            buttons,
            defaultId: buttons.length - 1,
        });
        const picked = buttons[result.response];
        if (picked === "Copy telemetry path" && diagnostics.telemetryPath) {
            clipboard.writeText(diagnostics.telemetryPath);
            void recordTelemetry("runtime_diag_copy_path", { path: diagnostics.telemetryPath });
        } else if (picked === "Upload telemetry" && diagnostics.telemetryPath && uploadURL && telemetryUploader) {
            try {
                await telemetryUploader.upload(diagnostics.telemetryPath, uploadURL, "manual");
                await dialog.showMessageBox({ type: "info", title: "Telemetry uploaded", message: "Runtime telemetry uploaded successfully." });
            } catch (error) {
                await dialog.showMessageBox({ type: "error", title: "Telemetry upload failed", message: String(error) });
            }
        }
    } catch (error) {
        await dialog.showMessageBox({ type: "error", title: "Runtime diagnostics", message: `Failed to query runtime: ${error}` });
    }
}

// ===== SECRET PROMPT UI =====

function escapeHTML(input: string): string {
    return input.replace(/[&<>"']/g, char => {
        const map: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
        return map[char] || char;
    });
}

async function promptForSecretValue(secret: RuntimeSecret): Promise<string | null> {
    const channel = `secret-submit-${Date.now()}-${Math.random().toString(16).slice(2)}`;
    const modal = new BrowserWindow({
        modal: true, width: 460, height: 320, resizable: false, minimizable: false, maximizable: false,
        title: `Configure ${APP_CONFIG.APP_DISPLAY_NAME}`,
        webPreferences: { nodeIntegration: true, contextIsolation: false },
        show: false,
        ...(mainWindow && { parent: mainWindow }),
    });
    const label = escapeHTML(secret.prompt?.label || secret.id);
    const description = escapeHTML(secret.prompt?.description || secret.description || "Enter a value for this secret.");
    const body = `<!doctype html><html><body style="font-family:sans-serif;padding:16px;background:#0f172a;color:#e2e8f0;"><h2 style="margin-top:0;">${label}</h2><p style="margin-bottom:12px;">${description}</p><form id="secret-form" style="display:flex;flex-direction:column;gap:12px;"><input id="secret-value" type="password" placeholder="Value" autofocus style="padding:10px 12px;border-radius:8px;border:1px solid #334155;background:#1e293b;color:#e2e8f0;"><div style="display:flex;justify-content:flex-end;gap:8px;"><button type="button" id="cancel" style="padding:8px 12px;border-radius:6px;border:1px solid #334155;background:#0f172a;color:#e2e8f0;">Cancel</button><button type="submit" style="padding:8px 12px;border-radius:6px;border:none;background:#10b981;color:#0f172a;font-weight:600;">Save</button></div></form><script>const{ipcRenderer}=require('electron');const form=document.getElementById('secret-form');const input=document.getElementById('secret-value');form.addEventListener('submit',e=>{e.preventDefault();ipcRenderer.send('${channel}',input.value);});document.getElementById('cancel').addEventListener('click',()=>{ipcRenderer.send('${channel}',null);});</script></body></html>`;
    await modal.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(body)}`);
    modal.once("ready-to-show", () => modal.show());
    return new Promise<string | null>(resolve => {
        let settled = false;
        const finish = (value: string | null) => {
            if (settled) return;
            settled = true;
            ipcMain.removeAllListeners(channel);
            if (!modal.isDestroyed()) modal.close();
            resolve(value);
        };
        ipcMain.once(channel, (_event, value: string | null) => finish(value));
        modal.on("closed", () => finish(null));
    });
}

async function ensureRuntimeSecretsIfNeeded(): Promise<void> {
    if (!RUNTIME_CONTROL.ENABLED || !runtimeControlClient) return;
    try {
        const fetchSecrets = async (): Promise<RuntimeSecret[]> => {
            const status = await runtimeControlClient!.request<RuntimeSecretsResponse>("/secrets");
            return (status as RuntimeSecretsResponse)?.secrets || [];
        };
        const current = await fetchSecrets();
        const missing = current.filter(sec => sec.class === "user_prompt" && sec.required && !sec.has_value);
        if (missing.length === 0) return;
        const collected: Record<string, string> = {};
        for (const secret of missing) {
            const value = await promptForSecretValue(secret);
            if (value?.trim()) collected[secret.id] = value.trim();
        }
        if (Object.keys(collected).length === 0) throw new Error("Required secrets were not provided.");
        await runtimeControlClient.request("/secrets", { method: "POST", body: { secrets: collected } });
        const refreshed = await fetchSecrets();
        const stillMissing = refreshed.filter(sec => sec.class === "user_prompt" && sec.required && !sec.has_value);
        if (stillMissing.length > 0) throw new Error(`Secrets still missing: ${stillMissing.map(s => s.id).join(", ")}`);
    } catch (error) {
        console.error("[Desktop App] Failed to sync runtime secrets:", error);
        dialog.showErrorBox("Secrets required", String(error));
        throw error;
    }
}

// ===== LOCAL VROOLI BOOTSTRAP =====

async function getBootstrapStatePath(): Promise<string> {
    if (!bootstrapStatePath) {
        if (!app.isReady()) await app.whenReady();
        bootstrapStatePath = path.join(app.getPath("userData"), "local-vrooli-bootstrap.json");
    }
    return bootstrapStatePath;
}

async function loadBootstrapState(): Promise<{ vrooliPath?: string; setupCompleted?: boolean }> {
    if (bootstrapStateCache) return bootstrapStateCache;
    try {
        const raw = await fs.promises.readFile(await getBootstrapStatePath(), "utf-8");
        bootstrapStateCache = JSON.parse(raw);
    } catch {
        bootstrapStateCache = {};
    }
    return bootstrapStateCache!;
}

async function saveBootstrapState(state: { vrooliPath?: string; setupCompleted?: boolean }): Promise<void> {
    bootstrapStateCache = state;
    await fs.promises.writeFile(await getBootstrapStatePath(), JSON.stringify(state, null, 2));
}

async function locateBinaryInPath(binary: string): Promise<string | null> {
    return new Promise(resolve => {
        const locator = process.platform === "win32" ? "where" : "which";
        const checker = spawn(locator, [binary], { shell: false });
        let output = "";
        checker.stdout?.on("data", data => { output += data.toString(); });
        checker.on("error", () => resolve(null));
        checker.on("close", code => {
            if (code === 0) {
                const line = output.split(/\r?\n/).find(item => item.trim().length > 0);
                resolve(line?.trim() || binary);
            } else {
                resolve(null);
            }
        });
    });
}

async function resolveVrooliCommand(): Promise<string | null> {
    if (!shouldBootstrapLocalVrooli) return null;
    if (localVrooliRuntime.vrooliBinary) return localVrooliRuntime.vrooliBinary;
    const preferred = LOCAL_VROOLI_BOOTSTRAP.VROOLI_BINARY?.trim();
    if (preferred && preferred !== "vrooli" && (preferred.includes(path.sep) || preferred.includes("/"))) {
        if (await pathExists(preferred)) { localVrooliRuntime.vrooliBinary = preferred; return preferred; }
    } else if (preferred && preferred !== "" && preferred !== "vrooli") {
        localVrooliRuntime.vrooliBinary = preferred; return preferred;
    }
    const state = await loadBootstrapState();
    if (state.vrooliPath && await pathExists(state.vrooliPath)) { localVrooliRuntime.vrooliBinary = state.vrooliPath; return state.vrooliPath; }
    const located = await locateBinaryInPath("vrooli");
    if (located) { localVrooliRuntime.vrooliBinary = located; return located; }
    if (process.platform === "win32") {
        const locatedCmd = await locateBinaryInPath("vrooli.cmd");
        if (locatedCmd) { localVrooliRuntime.vrooliBinary = locatedCmd; return locatedCmd; }
    }
    // Prompt user to locate binary
    const response = await dialog.showMessageBox({ type: "question", title: "Locate Vrooli", message: "The Vrooli CLI is required. Locate the vrooli binary or cancel.", buttons: ["Locate Vrooli", "Cancel"], defaultId: 0, cancelId: 1 });
    if (response.response !== 0) return null;
    const openResult = await dialog.showOpenDialog({ title: "Select vrooli executable", properties: ["openFile"], filters: [{ name: "Executable", extensions: process.platform === "win32" ? ["exe", "cmd", "bat"] : ["sh", ""] }] });
    if (openResult.canceled || openResult.filePaths.length === 0) return null;
    const userSelection = openResult.filePaths[0]!;
    const updatedState = await loadBootstrapState();
    updatedState.vrooliPath = userSelection;
    await saveBootstrapState(updatedState);
    localVrooliRuntime.vrooliBinary = userSelection;
    return userSelection;
}

async function runVrooliCommand(binary: string, args: string[], options: { timeoutMs?: number; ignoreErrors?: boolean } = {}): Promise<{ success: boolean; stdout: string; stderr: string; code: number }> {
    return new Promise(resolve => {
        const cmd = process.platform === "win32" && binary.includes(" ") ? `"${binary}"` : binary;
        const child = spawn(cmd, args, { shell: process.platform === "win32" });
        let stdout = "", stderr = "", finished = false;
        const timeout = options.timeoutMs ? setTimeout(() => { if (!finished) { finished = true; child.kill(); resolve({ success: false, stdout, stderr: `${stderr}\nCommand timed out`, code: -1 }); } }, options.timeoutMs) : null;
        child.stdout?.on("data", data => { stdout += data.toString(); });
        child.stderr?.on("data", data => { stderr += data.toString(); });
        child.on("error", error => { if (timeout) clearTimeout(timeout); if (!finished) { finished = true; resolve({ success: false, stdout, stderr: error.message, code: -1 }); } });
        child.on("close", code => { if (timeout) clearTimeout(timeout); if (!finished) { finished = true; resolve({ success: code === 0, stdout, stderr, code: code ?? -1 }); } });
    });
}

async function ensureLocalVrooliReady(): Promise<void> {
    if (!shouldBootstrapLocalVrooli) return;
    const vrooliBinary = await resolveVrooliCommand();
    if (!vrooliBinary) { void recordTelemetry("local_vrooli_bootstrap_skipped", { reason: "vrooli_not_found" }); dialog.showErrorBox("Vrooli CLI Missing", "Install the Vrooli CLI or run the scenario manually."); return; }
    const state = await loadBootstrapState();
    if (!state.setupCompleted) {
        void recordTelemetry("local_vrooli_setup_attempt");
        const setupResult = await runVrooliCommand(vrooliBinary, ["setup", "--yes", "yes", "--skip-sudo", "yes"], { timeoutMs: 5 * 60 * 1000 });
        if (!setupResult.success) { void recordTelemetry("local_vrooli_setup_failed", { stderr: setupResult.stderr }); dialog.showErrorBox("Vrooli Setup Failed", "Unable to run 'vrooli setup'. Please run it manually."); return; }
        state.setupCompleted = true;
        await saveBootstrapState(state);
    }
    const statusResult = await runVrooliCommand(vrooliBinary, ["scenario", "status", LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME!], { ignoreErrors: true, timeoutMs: 60 * 1000 });
    if (statusResult.success) { void recordTelemetry("local_vrooli_already_running"); return; }
    void recordTelemetry("local_vrooli_start_attempt");
    const startResult = await runVrooliCommand(vrooliBinary, ["scenario", "start", LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME!], { timeoutMs: 3 * 60 * 1000 });
    if (!startResult.success) { void recordTelemetry("local_vrooli_start_failed", { stderr: startResult.stderr }); dialog.showErrorBox("Unable to Start Scenario", `vrooli failed to start ${LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME}.`); return; }
    localVrooliRuntime.startedByApp = true;
    for (let i = 0; i < 10; i++) {
        const checkResult = await runVrooliCommand(vrooliBinary, ["scenario", "status", LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME!], { ignoreErrors: true, timeoutMs: 60 * 1000 });
        if (checkResult.success) { void recordTelemetry("local_vrooli_started"); return; }
        await delay(3000);
    }
    void recordTelemetry("local_vrooli_start_timeout");
    dialog.showErrorBox("Scenario Not Ready", `${LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME} did not become healthy in time.`);
}

async function shutdownLocalVrooli(): Promise<void> {
    if (!shouldBootstrapLocalVrooli || !localVrooliRuntime.startedByApp || !localVrooliRuntime.vrooliBinary) return;
    void recordTelemetry("local_vrooli_stop_attempt");
    await runVrooliCommand(localVrooliRuntime.vrooliBinary, ["scenario", "stop", LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME!], { timeoutMs: 60 * 1000, ignoreErrors: true });
    localVrooliRuntime.startedByApp = false;
}

// ===== SERVER READINESS =====

async function checkServerReady(url: string, timeout: number): Promise<void> {
    await applyStartupDelay("SERVER_READY");
    const httpClient = createElectronReadinessChecker(electronNet);
    const config: ReadinessConfig = { url, timeoutMs: timeout, pollIntervalMs: APP_CONFIG.SERVER_CHECK_INTERVAL_MS, acceptableStatusCodes: DEFAULT_READINESS_CONFIG.acceptableStatusCodes, acceptAny2xx: true };
    const result = await checkServerReadiness(httpClient, config, undefined, (attempt, elapsed) => {
        if (attempt % 10 === 0) console.log(`[Desktop App] Server check attempt ${attempt}, elapsed: ${elapsed}ms`);
        if (splashManager) splashManager.updateStatus({ phase: "loading-ui", message: `Waiting for server... (${Math.round(elapsed / 1000)}s)`, progress: Math.min(90, Math.round((elapsed / timeout) * 100)) });
    });
    if (result.ready) {
        console.log(`[Desktop App] Server ready at ${url} (status: ${result.statusCode}, took: ${result.durationMs}ms)`);
        void recordTelemetry("server_ready", { url, statusCode: result.statusCode, durationMs: result.durationMs });
        await launchTrace.emit("server_ready", "scenario-service", "scenario_service", { status: String(result.statusCode ?? "ok") });
    } else {
        const errorMsg = result.statusCode !== undefined
            ? `Server at ${url} returned status ${result.statusCode} (expected 2xx). ${result.error ?? ""}`.trim()
            : result.error ?? `Server not ready at ${url} within ${timeout}ms`;
        console.error(`[Desktop App] ${errorMsg}`);
        void recordTelemetry("dependency_unreachable", { url, timeoutMs: timeout, lastStatusCode: result.statusCode, error: result.error }, "error");
        throw new Error(errorMsg);
    }
}

// ===== SPLASH WINDOW HELPERS =====

function updateSplashStatus(phase: StartupPhase, customMessage?: string, progress?: number): void {
    if (!splashManager) return;
    const status: SplashStatus = { phase, message: customMessage ?? PHASE_MESSAGES[phase], ...(progress !== undefined && { progress }) };
    splashManager.updateStatus(status);
}

function buildStartupErrorLogs(): string[] {
    const logs = [`Session ID: ${sessionId}`, `Deployment Mode: ${APP_CONFIG.DEPLOYMENT_MODE}`, `Server Type: ${APP_CONFIG.SERVER_TYPE}`];
    const exitInfo = exitTracker?.info;
    if (exitInfo?.exited) {
        logs.push(`Runtime Exit Code: ${exitInfo.code}`);
        if (exitInfo.signal) logs.push(`Runtime Signal: ${exitInfo.signal}`);
        if (exitInfo.exitedAt) logs.push(`Exit Time: ${exitInfo.exitedAt.toISOString()}`);
    }
    return logs;
}

function showSplashError(title: string, message: string, options: { recoverable?: boolean; suggestion?: string; logs?: string[]; stderr?: string; exitCode?: number | null } = {}): void {
    if (!splashManager) return;
    const errorDetails: SplashStatus["error"] = { title, message, recoverable: options.recoverable ?? false };
    if (options.logs !== undefined) errorDetails.logs = options.logs;
    if (options.stderr !== undefined) errorDetails.stderr = options.stderr;
    if (options.exitCode !== undefined) errorDetails.exitCode = options.exitCode;
    if (options.suggestion !== undefined) errorDetails.suggestion = options.suggestion;
    splashManager.updateStatus({ phase: "error", message: title, error: errorDetails });
}

function setupSplashErrorHandlers(options: { recoverable?: boolean; includeStderr?: boolean } = {}): void {
    if (!splashManager) return;
    splashManager.onEscapePressed(() => { console.log("[Desktop App] User pressed escape on error screen, quitting..."); app.quit(); });
    if (options.recoverable) splashManager.onRetry(() => { console.log("[Desktop App] User requested retry, restarting app..."); app.relaunch(); app.quit(); });
    splashManager.onCopyLogs(() => {
        const logs = buildStartupErrorLogs();
        const exitInfo = exitTracker?.info;
        if (options.includeStderr && exitInfo?.stderr) logs.push("", "--- Runtime stderr ---", exitInfo.stderr);
        return logs.join("\n");
    });
}

// ===== BUNDLED RUNTIME STARTUP =====

function runtimePlatformKey(): string {
    const arch = process.arch === "x64" ? "x64" : process.arch;
    const os = process.platform === "darwin" ? "mac" : process.platform === "win32" ? "win" : "linux";
    return `${os}-${arch}`;
}

async function isPortFree(host: string, port: number): Promise<boolean> {
    return new Promise(resolve => {
        const server = nodeNet.createServer();
        server.once("error", () => resolve(false));
        server.once("listening", () => { server.close(() => resolve(true)); });
        server.listen(port, host);
    });
}

async function allocateIpcPort(host: string, preferred: number): Promise<{ port: number; changed: boolean }> {
    return new Promise((resolve, reject) => {
        const server = nodeNet.createServer();
        server.once("error", reject);
        server.listen(0, host, () => {
            const address = server.address();
            const port = typeof address === "object" && address ? address.port : 0;
            server.close(() => resolve({ port, changed: port !== preferred }));
        });
    });
}

async function resolveBundleRoot(): Promise<{ found: boolean; path: string | null; candidatesChecked: string[] }> {
    const bundleRoot = BUNDLED_RUNTIME.ROOT || "bundle";
    const candidates = [path.join(process.resourcesPath, bundleRoot), path.join(app.getAppPath(), bundleRoot)];
    for (const candidate of candidates) {
        if (await pathExists(candidate)) {
            console.log(`[Desktop App] Bundle found at: ${candidate}`);
            return { found: true, path: candidate, candidatesChecked: candidates };
        }
    }
    console.error(`[Desktop App] Bundle not found. Checked: ${candidates.join(", ")}`);
    return { found: false, path: null, candidatesChecked: candidates };
}

async function waitForFile(filePath: string, timeoutMs = 15000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
        if (await pathExists(filePath)) return;
        await delay(150);
    }
    if (isSmokeTest) SmokeTestProtocol.error("runtime", `Timed out waiting for file: ${filePath}`);
    throw new Error(`file not found within timeout: ${filePath}`);
}

function formatValidationErrors(result: BundleValidationResult): string {
    const lines: string[] = [];
    if (result.missingBinaries.length > 0) { lines.push("Missing binaries:"); for (const mb of result.missingBinaries) lines.push(`  - ${mb.serviceId}: ${mb.path} (${mb.platform})`); }
    if (result.missingAssets.length > 0) { lines.push("Missing assets:"); for (const ma of result.missingAssets) lines.push(`  - ${ma.serviceId}: ${ma.path}`); }
    if (result.errors.length > 0 && lines.length === 0) { lines.push("Validation errors:"); for (const err of result.errors) lines.push(`  - ${err}`); }
    return lines.join("\n");
}

async function startBundledRuntime(): Promise<string> {
    if (isSmokeTest) SmokeTestProtocol.stage.bundleResolving();
    updateSplashStatus("validating-bundle", "Resolving bundle...");
    const bundleResolution = await resolveBundleRoot();
    if (!bundleResolution.found || !bundleResolution.path) throw new Error(`Bundled payload missing. Checked: [${bundleResolution.candidatesChecked.join(", ")}].`);
    const bundleRoot = bundleResolution.path;
    const manifestPath = path.join(bundleRoot, "bundle.json");
    if (!(await pathExists(manifestPath))) throw new Error(`Bundled manifest missing at ${manifestPath}`);

    updateSplashStatus("validating-bundle", "Reading bundle manifest...", 10);
    let manifestContent: any;
    try { manifestContent = JSON.parse(await fs.promises.readFile(manifestPath, "utf-8")); } catch (err) { throw new Error(`Failed to read bundle manifest: ${err}`); }

    updateSplashStatus("allocating-ports", "Allocating network ports...", 15);
    const ipcHost = manifestContent?.ipc?.host || "127.0.0.1";
    const preferredPort = Number(manifestContent?.ipc?.port) || 39200;
    const { port: runtimePort, changed } = await allocateIpcPort(ipcHost, preferredPort);
    if (changed) console.log(`[Desktop App] IPC port ${preferredPort} was busy; using ${runtimePort} instead`);
    manifestContent.ipc = manifestContent.ipc || {};
    manifestContent.ipc.port = runtimePort;
    RUNTIME_CONTROL.PORT = runtimePort;

    const appData = path.join(app.getPath("userData"), "runtime");
    await fs.promises.mkdir(appData, { recursive: true });
    runtimeAppDataRoot = appData;
    const stagedManifestPath = path.join(appData, "bundle.json");
    await fs.promises.writeFile(stagedManifestPath, JSON.stringify(manifestContent, null, 2), "utf-8");
    const portPath = path.join(appData, "runtime", "ipc_port");
    await fs.promises.mkdir(path.dirname(portPath), { recursive: true });
    await fs.promises.writeFile(portPath, `${runtimePort}`, "utf-8");

    // Pre-flight validation
    // DOC: docs/internal/SEAMS.md#bundle-module
    // Factory functions create testable wrappers around Node.js modules
    console.log("[Desktop App] Performing pre-flight bundle validation...");
    const bundleFs = createNodeBundleFileSystem(fs.promises);  // Requires fs.promises, not fs
    const bundlePathUtils = createNodeBundlePathUtils(path);
    const platformInfo = createRealPlatformInfo();             // No arguments - reads process internally
    const validationResult = await validateBundlePreFlight(bundleRoot, stagedManifestPath, bundleFs, bundlePathUtils, platformInfo);
    if (!validationResult.valid) {
        const errorDetails = formatValidationErrors(validationResult);
        await recordTelemetry("bundle_validation_failed", { errors: validationResult.errors, missingBinaries: validationResult.missingBinaries, missingAssets: validationResult.missingAssets });
        throw new Error(`Bundle validation failed:\n${errorDetails}`);
    }
    console.log("[Desktop App] Pre-flight bundle validation passed");

    const runtimePath = path.join(bundleRoot, "runtime", runtimePlatformKey(), process.platform === "win32" ? "runtime.exe" : "runtime");
    if (!(await pathExists(runtimePath))) throw new Error(`Bundled runtime binary not found for this platform (${runtimePath})`);
    const tokenRel = BUNDLED_RUNTIME.TOKEN_REL || "runtime/auth-token";
    const tokenPath = path.join(appData, tokenRel);
    RUNTIME_CONTROL.TOKEN_PATH_ENV = tokenPath;

    const args = ["--manifest", stagedManifestPath, "--bundle-root", bundleRoot, "--app-data", appData, "--dry-run=false"];
    const runtimeEnv: Record<string, string | undefined> = {
        ...process.env,
        VROOLI_API_SKIP_STALE_CHECK: "true",
        VROOLI_LIFECYCLE_MANAGED: "true",
        VROOLI_DESKTOP_MODE: "true",
        // Backward-compatible root used by existing scenarios.
        VROOLI_DATA: appData,
        // Canonical root for api-core/storage class directories.
        VROOLI_STORAGE_ROOT: path.join(appData, "storage"),
    };
    for (const [portKey, portConfig] of Object.entries(PORTS)) {
        if (portConfig.envVar && portConfig.port) { runtimeEnv[portConfig.envVar] = String(portConfig.port); console.log(`[Desktop App] Setting ${portConfig.envVar}=${portConfig.port}`); }
    }

    // Initialize exit tracker
    exitTracker = createExitTracker();
    exitTracker.reset();

    if (isSmokeTest) SmokeTestProtocol.stage.runtimeStarting();
    updateSplashStatus("starting-runtime", "Starting runtime services...", 30);

    runtimeProcess = spawn(runtimePath, args, { stdio: ["inherit", "inherit", "pipe"], env: runtimeEnv });
    await launchTrace.emit("runtime_spawned", "bundled-runtime", "bundled_runtime");
    let stderrErrorEmitted = false;
    if (runtimeProcess.stderr) {
        runtimeProcess.stderr.on("data", (data: Buffer) => {
            const chunk = data.toString();
            exitTracker!.appendStderr(chunk);
            process.stderr.write(chunk);
            if (isSmokeTest && !stderrErrorEmitted) {
                const match = matchErrorPattern(chunk, DEFAULT_ERROR_PATTERNS);
                if (match) { SmokeTestProtocol.error(match.kind as any, match.message); stderrErrorEmitted = true; }
            }
        });
    }
    runtimeProcess.on("exit", (code, signal) => {
        exitTracker!.recordExit(code, signal);
        void recordTelemetry("bundled_runtime_exit", { code, signal });
        if (isSmokeTest && code !== 0 && code !== null) {
            const exitInfo = exitTracker!.info;
            const errorMsg = exitInfo.stderr.trim() ? `Runtime crashed (exit ${code}): ${exitInfo.stderr.slice(0, 200)}` : `Runtime crashed with exit code ${code}`;
            SmokeTestProtocol.error("runtime", errorMsg);
        }
    });

    if (isSmokeTest) SmokeTestProtocol.stage.waitingForToken();
    updateSplashStatus("waiting-for-token", "Waiting for authentication token...", 40);
    console.log(`[Desktop App] Waiting for runtime auth token at: ${tokenPath}`);
    await waitForFile(tokenPath, APP_CONFIG.SERVER_CHECK_TIMEOUT_MS);
    await launchTrace.emit("runtime_token_available", "bundled-runtime", "bundled_runtime", { available: "true" });

    await initializeRuntimeControlClient();

    if (isSmokeTest) SmokeTestProtocol.stage.runtimeHealthz();
    updateSplashStatus("checking-health", "Checking service health...", 50);
    await runtimeControlClient!.waitForHealth(APP_CONFIG.SERVER_CHECK_TIMEOUT_MS);
    await launchTrace.emit("runtime_health_ready", "bundled-runtime", "bundled_runtime");

    await ensureRuntimeSecretsIfNeeded();

    await applyStartupDelay("RUNTIME_READY");

    if (isSmokeTest) SmokeTestProtocol.stage.runtimeReadyz();
    updateSplashStatus("checking-ready", "Verifying services are ready...", 60);
    const readyDeadline = Date.now() + APP_CONFIG.SERVER_CHECK_TIMEOUT_MS;
    let runtimeReady = false;
    while (Date.now() < readyDeadline) {
        try {
            const ready = await runtimeControlClient!.request<RuntimeReadyResponse>("/readyz");
            if ((ready as RuntimeReadyResponse)?.ready) {
                runtimeReady = true;
                break;
            }
        } catch { /* runtime may still be starting */ }
        await delay(350);
    }
    if (!runtimeReady) {
        const error = `Bundled runtime did not become ready within ${APP_CONFIG.SERVER_CHECK_TIMEOUT_MS}ms`;
        await launchTrace.emit("runtime_ready", "bundled-runtime", "bundled_runtime", { available: "false" }, "error");
        throw new Error(error);
    }
    await launchTrace.emit("runtime_ready", "bundled-runtime", "bundled_runtime");

    if (isSmokeTest) SmokeTestProtocol.stage.runtimePorts();
    updateSplashStatus("discovering-ports", "Discovering service endpoints...", 70);
    const ports = await runtimeControlClient!.request<RuntimePortsResponse>("/ports");
    const serviceId = BUNDLED_RUNTIME.UI_SERVICE || Object.keys((ports as RuntimePortsResponse).services || {})[0];
    const portName = BUNDLED_RUNTIME.UI_PORT_NAME || "http";
    const svcPorts = (ports as RuntimePortsResponse).services?.[serviceId!];
    const port = svcPorts?.[portName];
    if (!serviceId || !port) throw new Error("Bundled runtime started but did not expose a UI port");
    await launchTrace.emit("port_discovered", "bundled-runtime", "bundled_runtime", { service: serviceId, port_name: portName });

    updateSplashStatus("loading-ui", "Starting user interface...", 80);
    const url = `http://127.0.0.1:${port}/`;
    await recordTelemetry("bundled_runtime_ready", { bundleRoot, serviceId, portName, port });
    return url;
}

async function shutdownRuntime(): Promise<void> {
    const child = runtimeProcess;
    runtimeProcess = null;
    if (RUNTIME_CONTROL.ENABLED && runtimeControlClient) {
        try { await runtimeControlClient.request("/shutdown", { method: "POST" }); } catch (error) { console.warn("[Desktop App] Failed to request runtime shutdown", error); }
    }
    if (!child || child.exitCode !== null) return;
    const waitForExit = async (timeoutMs: number): Promise<boolean> => await new Promise(resolve => {
        const timer = setTimeout(() => { child.removeListener("exit", onExit); resolve(false); }, timeoutMs);
        const onExit = () => { clearTimeout(timer); resolve(true); };
        child.once("exit", onExit);
    });
    if (await waitForExit(5000)) return;
    try { child.kill("SIGTERM"); } catch { /* process already exited */ }
    if (await waitForExit(2000)) return;
    try { child.kill("SIGKILL"); } catch { /* process already exited */ }
    await waitForExit(1000);
}

// ===== SCENARIO SERVER (NON-BUNDLED MODES) =====

async function startScenarioServer(): Promise<void> {
    if (APP_CONFIG.SERVER_TYPE === "external") { console.log(`[Desktop App] Using external server: ${APP_CONFIG.SERVER_PATH}`); void recordTelemetry("external_server_mode", { serverPath: APP_CONFIG.SERVER_PATH }); return; }
    if (APP_CONFIG.SERVER_TYPE === "static") { console.log("[Desktop App] Using static files, no server to start"); return; }
    const serverPath = path.resolve(app.getAppPath(), APP_CONFIG.SERVER_PATH);
    console.log(`[Desktop App] Starting scenario server: ${serverPath}`);
    try {
        const serverStdioCfg: "inherit" | ["inherit", "inherit", "pipe"] = isSmokeTest ? ["inherit", "inherit", "pipe"] : "inherit";
        let serverStderr = "";
        if (APP_CONFIG.SERVER_TYPE === "node") {
            serverProcess = fork(serverPath, [], { env: { ...process.env, PORT: APP_CONFIG.SERVER_PORT.toString(), DESKTOP_MODE: "true", API_ENDPOINT: APP_CONFIG.API_ENDPOINT }, stdio: serverStdioCfg });
        } else if (APP_CONFIG.SERVER_TYPE === "executable") {
            serverProcess = spawn(serverPath, [], { env: { ...process.env, PORT: APP_CONFIG.SERVER_PORT.toString(), DESKTOP_MODE: "true", API_ENDPOINT: APP_CONFIG.API_ENDPOINT }, stdio: serverStdioCfg });
        }
        await launchTrace.emit("runtime_spawned", "scenario-service", "scenario_service", { mode: APP_CONFIG.SERVER_TYPE });
        void recordTelemetry("local_server_started", { mode: APP_CONFIG.SERVER_TYPE, serverPath });
        if (serverProcess) {
            if (isSmokeTest && serverProcess.stderr) serverProcess.stderr.on("data", (data: Buffer) => { const chunk = data.toString(); serverStderr += chunk; process.stderr.write(chunk); });
            serverProcess.on("error", error => { console.error(`[Desktop App] Server process error: ${error}`); if (isSmokeTest) SmokeTestProtocol.error("runtime", `Server error: ${error.message}`); else dialog.showErrorBox("Server Error", `Failed to start scenario server: ${error.message}`); });
            serverProcess.on("exit", (code, signal) => { console.log(`[Desktop App] Server process exited with code ${code} and signal ${signal}`); if (isSmokeTest && code !== 0 && code !== null) SmokeTestProtocol.error("runtime", serverStderr.trim() ? `Server crashed (exit ${code}): ${serverStderr.slice(0, 200)}` : `Server crashed with exit code ${code}`); });
        }
    } catch (error) {
        console.error(`[Desktop App] Failed to start server: ${error}`);
        if (isSmokeTest) SmokeTestProtocol.error("runtime", `Failed to start scenario server: ${error}`);
        throw error;
    }
}

// ===== WINDOW CREATION =====

function getAppIcon(): string | undefined {
    const iconPath = path.join(app.getAppPath(), "assets");
    if (process.platform === "win32") return path.join(iconPath, "icon.ico");
    if (process.platform === "darwin") return path.join(iconPath, "icon.icns");
    return path.join(iconPath, "icon.png");
}

async function createSplashWindowManager(): Promise<void> {
    if (!APP_CONFIG.ENABLE_SPLASH) {
        await launchTrace.emit("splash_created", "electron", "splash", { availability: "unavailable" });
        await launchTrace.emit("splash_load_completed", "electron", "splash", { availability: "unavailable" });
        await launchTrace.emit("splash_first_paint", "electron", "splash", { availability: "unavailable" });
        return;
    }
    console.log("[Desktop App] Creating splash window...");
    splashManager = createSplashManager(BrowserWindow, app, ipcMain, path, clipboard, {
        alwaysOnTop: false,
        allowEscapeClose: true,
        onPhase: async (phase) => {
            if (phase === "load_completed") await applyStartupDelay("SPLASH_LOAD");
            const names = {
                created: "splash_created",
                load_completed: "splash_load_completed",
                ready_to_show: "splash_ready_to_show",
                shown: "splash_shown",
                first_paint: "splash_first_paint",
            } as const;
            void launchTrace.emit(names[phase], "electron", "splash");
            // The splash owner knows when the window is visible even when the
            // renderer's optional IPC-ready signal is delayed or interrupted
            // by a fast journey quit. Treat visibility as the stable first
            // paint seam; the IPC callback remains supplemental telemetry.
            if (phase === "shown") void launchTrace.emit("splash_first_paint", "electron", "splash");
        },
    });
    splashManager.onEscapePressed(() => { console.log("[Desktop App] User requested startup cancellation via ESC"); void handleStartupCancellation(); });
    const created = await splashManager.create();
    if (!created) { console.warn("[Desktop App] Failed to create splash window, continuing without it"); splashManager = null; }
}

async function handleStartupCancellation(): Promise<void> {
    console.log("[Desktop App] Cancelling startup...");
    void recordTelemetry("startup_cancelled_by_user");
    if (splashManager) { await splashManager.close(); splashManager = null; }
    if (runtimeProcess) await shutdownRuntime();
    if (serverProcess) { serverProcess.kill(); serverProcess = null; }
    app.quit();
}

async function closeSplashWindow(): Promise<void> {
    if (!splashManager) return;
    const result = await splashManager.close();
    if (!result.success && result.error) console.warn("[Desktop App] Error closing splash window:", result.error);
    splashManager = null;
}

async function createMainWindow(): Promise<BrowserWindow> {
    console.log("[Desktop App] Creating main window (hidden)...");
    const storage = createWindowStateStorage(app, fs, path);
    const displayProvider = createDisplayProvider(screen);
    const debugLogPath = path.join(app.getPath("userData"), "window-state-debug.log");
    windowStateManager = new WindowStateManager({ storage, displayProvider, debugLogPath }, { defaultWidth: APP_CONFIG.WINDOW_WIDTH, defaultHeight: APP_CONFIG.WINDOW_HEIGHT, minWidth: 400, minHeight: 300 });
    const windowState = await windowStateManager.getInitialState();
    const shouldRestoreFullScreen = windowStateManager.wasFullScreen();
    console.log("[Desktop App] Window state:", windowState);
    console.log("[Desktop App] Will restore fullscreen:", shouldRestoreFullScreen);
    const appIcon = getAppIcon();
    mainWindow = new BrowserWindow({
        ...(!shouldRestoreFullScreen && { x: windowState.x, y: windowState.y, width: windowState.width, height: windowState.height }),
        fullscreen: shouldRestoreFullScreen, show: false, backgroundColor: APP_CONFIG.WINDOW_BACKGROUND, title: APP_CONFIG.WINDOW_TITLE,
        webPreferences: { preload: path.join(__dirname, "preload.js"), nodeIntegration: false, contextIsolation: true },
        ...(appIcon && { icon: appIcon }),
    });
    await launchTrace.emit("main_window_created", "electron", "renderer");
    windowStateManager.manage(mainWindow);
    mainWindow.webContents.setWindowOpenHandler(({ url }) => { shell.openExternal(url); return { action: "deny" }; });
    mainWindow.on("closed", () => { mainWindow = null; });
    if (APP_CONFIG.ENABLE_DEV_TOOLS && !app.isPackaged) mainWindow.webContents.openDevTools();
    return mainWindow;
}

// ===== MENU AND TRAY =====

function createSystemTray(): void {
    if (!APP_CONFIG.ENABLE_SYSTEM_TRAY) return;
    const iconPath = getAppIcon();
    if (!iconPath) return;
    try {
        const icon = nativeImage.createFromPath(iconPath);
        tray = new Tray(icon.resize({ width: 16, height: 16 }));
        const contextMenu = Menu.buildFromTemplate([
            { label: `Show ${APP_CONFIG.APP_DISPLAY_NAME}`, click: () => { if (mainWindow) { mainWindow.show(); mainWindow.focus(); } } },
            { label: `About ${APP_CONFIG.APP_DISPLAY_NAME}`, click: () => { dialog.showMessageBox(mainWindow!, { type: "info", title: `About ${APP_CONFIG.APP_DISPLAY_NAME}`, message: APP_CONFIG.APP_DISPLAY_NAME, detail: `Version ${APP_CONFIG.APP_VERSION}\n\nBuilt with scenario-to-desktop` }); } },
            { type: "separator" },
            { label: "Quit", click: () => { app.quit(); } },
        ]);
        tray.setToolTip(APP_CONFIG.APP_DISPLAY_NAME);
        tray.setContextMenu(contextMenu);
        tray.on("double-click", () => { if (mainWindow) { mainWindow.show(); mainWindow.focus(); } });
    } catch (error) { console.error("[Desktop App] Failed to create system tray:", error); }
}

function createApplicationMenu(): void {
    if (!APP_CONFIG.ENABLE_MENU) return;
    const template: Electron.MenuItemConstructorOptions[] = [
        { label: "File", submenu: [
            { label: "New", accelerator: "CmdOrCtrl+N", click: () => { if (mainWindow) mainWindow.webContents.send("menu-action", { action: "new" }); } },
            { label: "Open", accelerator: "CmdOrCtrl+O", click: async () => { if (!mainWindow) return; const result = await dialog.showOpenDialog(mainWindow, { properties: ["openFile"], filters: [{ name: "All Files", extensions: ["*"] }] }); if (!result.canceled && result.filePaths.length > 0) mainWindow.webContents.send("menu-action", { action: "open", filePath: result.filePaths[0] }); } },
            { type: "separator" },
            process.platform === "darwin" ? { role: "close" } : { role: "quit" },
        ] },
        { label: "Edit", submenu: [{ role: "undo" }, { role: "redo" }, { type: "separator" }, { role: "cut" }, { role: "copy" }, { role: "paste" }, { role: "selectAll" }] },
        { label: "View", submenu: [
            { role: "reload" }, { role: "forceReload" }, { role: "toggleDevTools" }, { type: "separator" },
            { role: "resetZoom" }, { role: "zoomIn" }, { role: "zoomOut" }, { type: "separator" }, { role: "togglefullscreen" },
            ...(RUNTIME_CONTROL.ENABLED ? [{ type: "separator" as const }, { label: "Runtime Diagnostics", click: () => { void showRuntimeDiagnostics(); } }] : []),
        ] },
        { label: "Window", submenu: [{ role: "minimize" }, { role: "close" }] },
        { label: "Help", submenu: [
            { label: "Check for Updates...", enabled: UPDATE_CONFIG.PROVIDER !== "none", click: () => { void checkForUpdatesManually(); } },
            { type: "separator" },
            { label: `About ${APP_CONFIG.APP_DISPLAY_NAME}`, click: () => { const channelInfo = UPDATE_CONFIG.PROVIDER !== "none" ? `\nUpdate Channel: ${UPDATE_CONFIG.CHANNEL}` : ""; dialog.showMessageBox(mainWindow!, { type: "info", title: `About ${APP_CONFIG.APP_DISPLAY_NAME}`, message: APP_CONFIG.APP_DISPLAY_NAME, detail: `Version ${APP_CONFIG.APP_VERSION}${channelInfo}\n\nBuilt with scenario-to-desktop\n\n${APP_CONFIG.APP_URL || ""}` }); } },
        ] },
    ];
    Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}

// ===== AUTO-UPDATER =====

function setupAutoUpdater(): void {
    if (!APP_CONFIG.ENABLE_AUTO_UPDATER || !app.isPackaged || UPDATE_CONFIG.PROVIDER === "none") { console.log("[Desktop App] Auto-updater disabled"); return; }
    autoUpdater.logger = console;
    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;
    // electron-updater resolves its default stable feed as latest-<platform>.yml.
    // Assigning "stable" explicitly changes that lookup to stable-<platform>.yml,
    // which electron-builder does not emit for its normal stable channel.
    if (UPDATE_CONFIG.CHANNEL !== "stable") autoUpdater.channel = UPDATE_CONFIG.CHANNEL;
    if (UPDATE_CONFIG.PROVIDER === "github") autoUpdater.allowPrerelease = UPDATE_CONFIG.CHANNEL !== "stable";
    console.log(`[Desktop App] Auto-updater configured: Provider=${UPDATE_CONFIG.PROVIDER}, Channel=${UPDATE_CONFIG.CHANNEL}`);
    autoUpdater.on("checking-for-update", () => { console.log("[Desktop App] Checking for update..."); recordTelemetry("update_check_started", { channel: UPDATE_CONFIG.CHANNEL }); });
    autoUpdater.on("update-available", info => { console.log("[Desktop App] Update available:", info.version); recordTelemetry("update_available", { version: info.version, channel: UPDATE_CONFIG.CHANNEL }); if (mainWindow && !mainWindow.isDestroyed()) dialog.showMessageBox(mainWindow, { type: "info", title: "Update Available", message: `A new version (${info.version}) is available and will be downloaded automatically.`, buttons: ["OK"] }); });
    autoUpdater.on("update-not-available", info => { console.log("[Desktop App] Already on latest version:", info.version); });
    autoUpdater.on("error", err => { console.error("[Desktop App] Update error:", err.message); recordTelemetry("update_error", { error: err.message, channel: UPDATE_CONFIG.CHANNEL }); });
    autoUpdater.on("download-progress", progressObj => { console.log(`[Desktop App] Download progress: ${Math.round(progressObj.percent)}%`); });
    autoUpdater.on("update-downloaded", info => {
        console.log("[Desktop App] Update downloaded:", info.version);
        recordTelemetry("update_downloaded", { version: info.version, channel: UPDATE_CONFIG.CHANNEL });
        const applyUpdate = () => { recordTelemetry("update_apply_requested", { version: info.version, channel: UPDATE_CONFIG.CHANNEL }); autoUpdater.quitAndInstall(false, true); };
        if (isUpdateApplyTest) { applyUpdate(); return; }
        if (mainWindow && !mainWindow.isDestroyed()) dialog.showMessageBox(mainWindow, { type: "info", title: "Update Ready", message: `Version ${info.version} has been downloaded. The application will restart to apply the update.`, buttons: ["Restart Now", "Later"], defaultId: 0 }).then(({ response }) => { if (response === 0) applyUpdate(); });
    });
    if (UPDATE_CONFIG.AUTO_CHECK) setTimeout(() => { console.log("[Desktop App] Performing automatic update check..."); autoUpdater.checkForUpdatesAndNotify().catch(err => { console.error("[Desktop App] Failed to check for updates:", err.message); }); }, 3000);
}

async function checkForUpdatesManually(): Promise<void> {
    if (UPDATE_CONFIG.PROVIDER === "none") { if (mainWindow && !mainWindow.isDestroyed()) dialog.showMessageBox(mainWindow, { type: "info", title: "Updates Disabled", message: "Auto-updates are not configured for this application.", buttons: ["OK"] }); return; }
    try {
        console.log("[Desktop App] Manual update check triggered");
        const result = await autoUpdater.checkForUpdates();
        if (!result?.updateInfo && mainWindow && !mainWindow.isDestroyed()) dialog.showMessageBox(mainWindow, { type: "info", title: "No Updates", message: "You are running the latest version.", buttons: ["OK"] });
    } catch (err) { console.error("[Desktop App] Manual update check failed:", err); if (mainWindow && !mainWindow.isDestroyed()) dialog.showMessageBox(mainWindow, { type: "error", title: "Update Check Failed", message: `Could not check for updates: ${err instanceof Error ? err.message : String(err)}`, buttons: ["OK"] }); }
}

// ===== SMOKE TEST RUNNER =====

async function runSmokeTest(): Promise<void> {
    SmokeTestProtocol.init();
    // Initialize telemetry for smoke test
    const userData = app.getPath("userData");
    const telemetryPath = path.join(userData, "deployment-telemetry.jsonl");
    telemetryRecorder = createTelemetryRecorder(createTelemetryFileSystem(fs.promises), { filePath: telemetryPath, sessionId, sessionKind, deploymentMode: APP_CONFIG.DEPLOYMENT_MODE, serverType: APP_CONFIG.SERVER_TYPE });
    await telemetryRecorder.initialize();
    await startLaunchProfiler();
    await recordTelemetry("smoke_test_started", { deploymentMode: APP_CONFIG.DEPLOYMENT_MODE, serverType: APP_CONFIG.SERVER_TYPE });
    let success = false, failureMessage = "", runtimeUrl = "";
    try {
        if (isBundledMode) {
            const bundleResolution = await resolveBundleRoot();
            if (!bundleResolution.found || !bundleResolution.path) { const errorMsg = `Bundled payload missing. Checked: [${bundleResolution.candidatesChecked.join(", ")}].`; SmokeTestProtocol.error("config", errorMsg); throw new Error(errorMsg); }
            const bundleRoot = bundleResolution.path;
            const manifestPath = path.join(bundleRoot, "bundle.json");
            if (!(await pathExists(manifestPath))) { SmokeTestProtocol.error("config", `Manifest missing at ${manifestPath}`); throw new Error(`Manifest missing at ${manifestPath}`); }
            const bundleFs = createNodeBundleFileSystem(fs.promises), bundlePathUtils = createNodeBundlePathUtils(path), platformInfo = createRealPlatformInfo();
            const validationResult = await validateBundlePreFlight(bundleRoot, manifestPath, bundleFs, bundlePathUtils, platformInfo);
            if (!validationResult.valid) { const errorDetails = formatValidationErrors(validationResult); SmokeTestProtocol.error("validation", `Bundle validation failed: ${errorDetails}`); throw new Error(`Bundle validation failed: ${errorDetails}`); }
            if (!BUNDLED_RUNTIME.SUPPORTED) { SmokeTestProtocol.error("config", "Bundled runtime not supported"); throw new Error("Bundled runtime not supported"); }
            runtimeUrl = await startBundledRuntime();
            SmokeTestProtocol.stage.uiServerCheck();
            await checkServerReady(runtimeUrl, smokeTestTimeoutMs);
            // Stability check
            console.log(`[Smoke Test] Server ready, performing ${POST_SUCCESS_STABILITY_DELAY_MS}ms stability check...`);
            const stabilityStartTime = Date.now();
            while (Date.now() - stabilityStartTime < POST_SUCCESS_STABILITY_DELAY_MS) {
                if (exitTracker?.hasExitedUnexpectedly()) { const exitInfo = exitTracker.info; const errorMsg = exitInfo.stderr.trim() ? `Runtime crashed during stability check (exit ${exitInfo.code}): ${exitInfo.stderr.slice(0, 200)}` : `Runtime crashed during stability check with exit code ${exitInfo.code}`; SmokeTestProtocol.error("runtime", errorMsg); throw new Error(errorMsg); }
                await delay(STABILITY_CHECK_INTERVAL_MS);
            }
            console.log("[Smoke Test] Stability check passed");
        } else if (APP_CONFIG.SERVER_TYPE === "static") {
            const staticPath = path.resolve(app.getAppPath(), APP_CONFIG.SERVER_PATH);
            if (!(await pathExists(staticPath))) { SmokeTestProtocol.error("config", `Static UI missing at ${staticPath}`); throw new Error(`Static UI missing at ${staticPath}`); }
        } else {
            runtimeUrl = desktopValidationTargetURL;
            SmokeTestProtocol.stage.uiServerCheck();
            await checkServerReady(desktopValidationTargetURL, smokeTestTimeoutMs);
        }
        if (isBundledMode && exitTracker?.hasExitedUnexpectedly()) { const exitInfo = exitTracker.info; const errorMsg = exitInfo.stderr.trim() ? `Runtime crashed before completion (exit ${exitInfo.code}): ${exitInfo.stderr.slice(0, 200)}` : `Runtime crashed before completion with exit code ${exitInfo.code}`; SmokeTestProtocol.error("runtime", errorMsg); throw new Error(errorMsg); }
        SmokeTestProtocol.ready();
        success = true;
    } catch (error) {
        failureMessage = String(error);
        if (failureMessage.includes("not ready") || failureMessage.includes("timeout") || failureMessage.includes("ECONNREFUSED")) SmokeTestProtocol.error("network", failureMessage);
        else if (!failureMessage.includes("SMOKE_TEST_ERROR")) SmokeTestProtocol.error("runtime", failureMessage);
    } finally { if (isBundledMode) await shutdownRuntime(); }
    await stopLaunchProfiler();
    if (success) await recordTelemetry("smoke_test_passed", { serverUrl: runtimeUrl || SERVER_URL }); else await recordTelemetry("smoke_test_failed", { error: failureMessage }, "error");
    SmokeTestProtocol.result(success, failureMessage);
    if (smokeTestUploadURL && telemetryRecorder) {
        try {
            telemetryUploader = createTelemetryUploader(createTelemetryFileSystem(fs.promises), createFetchHttpClient(), createTelemetryPathUtils(path), { scenarioName: LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME || APP_CONFIG.APP_NAME, deploymentMode: APP_CONFIG.DEPLOYMENT_MODE, statePath: path.join(getRuntimeAppDataRoot(), "telemetry-upload.json") });
            await telemetryUploader.upload(telemetryRecorder.getFilePath()!, smokeTestUploadURL, "smoke-test");
            SmokeTestProtocol.upload(true);
        } catch (error) { SmokeTestProtocol.upload(false, String(error)); }
    }
    await launchTrace.emit("protocol_completed", "electron", "main", { result: success ? "passed" : "failed" }, success ? "info" : "error");
    await launchTrace.complete();
    SmokeTestProtocol.exit();
    // A smoke run has no user-facing windows and must not remain alive because
    // Electron retains an internal handle after app.exit(). The runtime has
    // already been shut down in the finally block, so force the one-shot
    // validation process to terminate after its final evidence marker.
    process.exit(success ? 0 : 1);
}

// ===== APP LIFECYCLE =====

app.whenReady().then(async () => {
    // Persist the initial markers before any launch work begins. These writes
    // used to be fire-and-forget at module load, which could leave a demo
    // trace empty when the short-lived Electron process was terminated.
    await launchTrace.emit("recorder_started", "smoke-orchestrator", "trace");
    await launchTrace.emit(isSmokeTestDemo ? "demo_spawn" : "protocol_started", "electron", "main");
    await launchTrace.emit("electron_ready", "electron", "main");
    if (isSmokeTest) { await runSmokeTest(); return; }
    if (APP_CONFIG.ENABLE_SINGLE_INSTANCE) {
        const gotTheLock = app.requestSingleInstanceLock();
        if (!gotTheLock) { app.quit(); return; }
        app.on("second-instance", (_event, commandLine) => {
            const protocolUrl = commandLine.find(arg => arg.startsWith(`${AUTH_CONFIG.PROTOCOL}://`) || arg.startsWith(`${APP_CONFIG.APP_NAME.toLowerCase()}://`));
            if (protocolUrl) { console.log(`[Desktop App] Protocol URL received (second-instance): ${protocolUrl}`); if (protocolUrl.includes("/auth/callback")) void authManager?.handleCallback(protocolUrl); else if (mainWindow) mainWindow.webContents.send("protocol-url", protocolUrl); }
            if (mainWindow) { if (mainWindow.isMinimized()) mainWindow.restore(); mainWindow.focus(); }
        });
    }
    try {
        await createSplashWindowManager();
        console.log(`[Desktop App] Version: ${APP_CONFIG.APP_VERSION}`);
        updateSplashStatus("initializing");
        setupAutoUpdater();
        createApplicationMenu();
        createSystemTray();

        // Initialize modules
        const userData = app.getPath("userData");
        const telemetryPath = path.join(userData, "deployment-telemetry.jsonl");
        telemetryRecorder = createTelemetryRecorder(createTelemetryFileSystem(fs.promises), { filePath: telemetryPath, sessionId, sessionKind, deploymentMode: APP_CONFIG.DEPLOYMENT_MODE, serverType: APP_CONFIG.SERVER_TYPE });
        await telemetryRecorder.initialize();
        await startLaunchProfiler();
        telemetryUploader = createTelemetryUploader(createTelemetryFileSystem(fs.promises), createFetchHttpClient(), createTelemetryPathUtils(path), { scenarioName: LOCAL_VROOLI_BOOTSTRAP.SCENARIO_NAME || APP_CONFIG.APP_NAME, deploymentMode: APP_CONFIG.DEPLOYMENT_MODE, statePath: path.join(getRuntimeAppDataRoot(), "telemetry-upload.json") });
        appStorage = createAppStorage(createNodeStorageFileSystem(fs.promises), createNodeStoragePathUtils(path), { userDataPath: userData });
        await appStorage.ensureDir("");
        // DOC: docs/internal/SEAMS.md#auth-module
        // createAuthManager takes a single dependency object with all seams
        authManager = createAuthManager({
            storage: { resolvePath: (p: string) => appStorage!.resolvePath(p), readFile: (p: string) => appStorage!.readFile(p), readTextFile: (p: string) => appStorage!.readTextFile(p), writeFile: (p: string, d: Buffer | string) => appStorage!.writeFile(p, d), deleteFile: (p: string) => appStorage!.deleteFile(p), ensureDir: (p: string) => appStorage!.ensureDir(p) },
            safeStorage: createElectronSafeStorage(safeStorage),
            http: createElectronAuthHttpClient(electronNet, desktopValidationContext ? validationHeaders(desktopValidationContext) : undefined, desktopValidationOrigins),
            shell: createElectronShell(shell),
            timer: createRealAuthTimer(),
            uuid: createRealUuidGenerator(randomUUID),
            pathUtils: { dirname: (p: string) => path.dirname(p) },
            config: { protocol: AUTH_CONFIG.PROTOCOL, lpbsUrl: AUTH_CONFIG.LPBS_URL, tokensFile: AUTH_CONFIG.TOKENS_FILE, userFile: AUTH_CONFIG.USER_FILE, tokenRefreshBufferMs: AUTH_CONFIG.TOKEN_REFRESH_BUFFER_MS, appDisplayName: APP_CONFIG.APP_DISPLAY_NAME },
            onAuthChange: (event) => { if (mainWindow && !mainWindow.isDestroyed()) mainWindow.webContents.send("auth:changed", { event }); },
            onWindowFocus: () => { if (mainWindow) { if (mainWindow.isMinimized()) mainWindow.restore(); mainWindow.focus(); } },
            onProtocolUrl: (url) => { if (mainWindow && !mainWindow.isDestroyed()) mainWindow.webContents.send("protocol-url", url); },
            onLoopbackAuthorization: runLoopbackAuthorization,
            createCodeChallenge: (verifier) => createHash("sha256").update(verifier).digest("base64url"),
            onRefreshToken: async (refreshToken) => {
                if (!runtimeControlClient) {
                    throw new Error("shared credential authority is unavailable");
                }
                await runtimeControlClient.request("/credentials/provision", {
                    method: "POST",
                    body: { identity: "vrooli/lpbs-account", field: "refresh-token", value: refreshToken },
                });
            },
            onGetRefreshToken: async () => {
                if (!runtimeControlClient) return null;
                try {
                    const result = await runtimeControlClient.request<{ value?: string }>(
                        "/credentials/resolve?identity=vrooli%2Flpbs-account&field=refresh-token",
                    );
                    return typeof result === "string" ? result : result.value ?? null;
                } catch {
                    return null;
                }
            },
            onClearRefreshToken: async () => {
                if (!runtimeControlClient) return;
                await runtimeControlClient.request("/credentials/delete", {
                    method: "POST",
                    body: { identity: "vrooli/lpbs-account", field: "refresh-token" },
                });
            },
        });
        await authManager.initialize();
        installDesktopValidationPropagation();

        appSessionStartedAt = new Date().toISOString();
        await recordTelemetry("app_start", { deploymentMode: APP_CONFIG.DEPLOYMENT_MODE, appVersion: APP_CONFIG.APP_VERSION });
        let targetUrl = desktopValidationTargetURL;

        if (isBundledMode) {
            if (!BUNDLED_RUNTIME.SUPPORTED) {
                const message = `Bundled builds require a bundle.json payload. Regenerate with DEPLOYMENT_MODE=external-server if you intended a thin client.`;
                void recordTelemetry("bundled_mode_blocked", { docsUrl: BUNDLED_RUNTIME.DOCS_URL }, "warn");
                appSessionFailureMessage = message;
                await recordAppSessionOutcome(message);
                showSplashError("Bundled Mode Unavailable", message, { recoverable: false, suggestion: `See: ${BUNDLED_RUNTIME.DOCS_URL}`, logs: buildStartupErrorLogs() });
                setupSplashErrorHandlers({ recoverable: false });
                return;
            }
            updateSplashStatus("validating-bundle");
            try { targetUrl = await startBundledRuntime(); } catch (startupError) {
                console.error("[Desktop App] Bundled runtime failed to start", startupError);
                await recordTelemetry("bundled_runtime_failed", { error: String(startupError) }, "error");
                await shutdownRuntime();
                appSessionFailureMessage = String(startupError);
                await recordAppSessionOutcome(String(startupError));
                const exitInfo = exitTracker?.info;
                showSplashError("Bundled Startup Error", String(startupError), { recoverable: true, suggestion: "Try restarting the application.", logs: buildStartupErrorLogs(), ...(exitInfo?.stderr ? { stderr: exitInfo.stderr } : {}), ...(exitInfo && exitInfo.code != null ? { exitCode: exitInfo.code } : {}) });
                setupSplashErrorHandlers({ recoverable: true, includeStderr: true });
                return;
            }
        } else {
            if (shouldBootstrapLocalVrooli) { updateSplashStatus("starting-runtime", "Starting local Vrooli..."); await ensureLocalVrooliReady(); }
            updateSplashStatus("starting-runtime");
            await startScenarioServer();
            if (RUNTIME_CONTROL.ENABLED) {
                try {
                    await initializeRuntimeControlClient();
                    updateSplashStatus("checking-health");
                    await runtimeControlClient!.waitForHealth(APP_CONFIG.SERVER_CHECK_TIMEOUT_MS);
                    await ensureRuntimeSecretsIfNeeded();
                } catch (secretError) {
                    await recordTelemetry("runtime_secrets_missing", { error: String(secretError) }, "error");
                    appSessionFailureMessage = String(secretError);
                    await recordAppSessionOutcome(String(secretError));
                    showSplashError("Secrets Required", String(secretError), { recoverable: true, suggestion: "Configure the required secrets and restart.", logs: buildStartupErrorLogs() });
                    setupSplashErrorHandlers({ recoverable: true });
                    return;
                }
            }
        }

        // Register IPC handlers
        ipcRegistration = registerAllHandlers({
            ipcMain, dialog, fs: { writeFile: (p: string, d: string) => fs.promises.writeFile(p, d), readFile: (p: string, e: "utf-8") => fs.promises.readFile(p, e) },
            storage: appStorage!, authManager: authManager!, getMainWindow: () => mainWindow,
            systemInfo: { platform: process.platform, arch: process.arch, version: APP_CONFIG.APP_VERSION },
        });

        updateSplashStatus("loading-ui", "Creating application window...");
        await createMainWindow();
        if (APP_CONFIG.SERVER_TYPE !== "static" || isBundledMode) { updateSplashStatus("loading-ui", "Waiting for server..."); await checkServerReady(targetUrl, APP_CONFIG.SERVER_CHECK_TIMEOUT_MS); }
        updateSplashStatus("loading-ui", "Loading application...", 95);
        await applyStartupDelay("MAIN_WINDOW_LOAD");
        if (APP_CONFIG.SERVER_TYPE === "static" && !isBundledMode) await mainWindow!.loadFile(path.resolve(app.getAppPath(), APP_CONFIG.SERVER_PATH)); else await mainWindow!.loadURL(targetUrl);
        await launchTrace.emit("main_window_load_completed", "electron", "renderer");
        const shouldMaximize = windowStateManager?.wasMaximized() ?? false;
        if (shouldMaximize && process.platform !== "linux") mainWindow!.maximize();
        updateSplashStatus("ready", "Ready!", 100);
        await closeSplashWindow();
        mainWindow!.show();
        await launchTrace.emit("main_window_shown", "electron", "renderer");
        if (shouldMaximize && process.platform === "linux") { await delay(50); mainWindow!.maximize(); }
        mainWindow!.focus();

        // Demo mode: the app has fully started and is visible. Hold for the
        // recording, then quit gracefully. This gives the screen capture a
        // realistic view of the complete startup experience.
        if (isSmokeTestDemo) {
            await launchTrace.emit("app_ready", "electron", "main");
            console.log(`[Desktop App] Demo recording: app ready, holding for ${smokeTestDemoHoldMs}ms`);
            await delay(smokeTestDemoHoldMs);
            console.log("[Desktop App] Demo recording: hold complete, quitting");
            await finalizeDemoTrace();
            return;
        }

        console.log(`[Desktop App] ${APP_CONFIG.APP_DISPLAY_NAME} ready!`);
        appSessionReadyAt = new Date().toISOString();
        await launchTrace.emit("app_ready", "electron", "main");
        void recordTelemetry("app_ready", { serverUrl: targetUrl, bundled: isBundledMode });
    } catch (error) {
        console.error("[Desktop App] Startup error:", error);
        if (runtimeProcess) await shutdownRuntime();
        if (serverProcess) { serverProcess.kill(); serverProcess = null; }
        void recordTelemetry("startup_error", { message: String(error) }, "error");
        appSessionFailureMessage = String(error);
        await recordAppSessionOutcome(String(error));
        const exitInfo = exitTracker?.info;
        showSplashError("Startup Error", `Failed to start ${APP_CONFIG.APP_DISPLAY_NAME}: ${error}`, { recoverable: true, suggestion: "Try restarting the application.", logs: buildStartupErrorLogs(), ...(exitInfo?.stderr ? { stderr: exitInfo.stderr } : {}), ...(exitInfo && exitInfo.code != null ? { exitCode: exitInfo.code } : {}) });
        setupSplashErrorHandlers({ recoverable: true, includeStderr: true });
    }
});

app.on("window-all-closed", () => { if (process.platform !== "darwin" && !APP_CONFIG.ENABLE_SYSTEM_TRAY) app.quit(); });
app.on("activate", async () => { if (BrowserWindow.getAllWindows().length === 0) await createMainWindow(); });
app.on("before-quit", (event) => {
    if (isSmokeTestDemo && !demoRecordingEnded) {
        event.preventDefault();
        void finalizeDemoTrace();
        return;
    }
    void launchTrace.complete();
    if (runtimeProcess) void shutdownRuntime();
    if (serverProcess) { console.log("[Desktop App] Terminating server process..."); serverProcess.kill(); serverProcess = null; }
    void shutdownLocalVrooli();
    void recordAppSessionOutcome("app_shutdown");
    void recordTelemetry("app_shutdown");
    if (ipcRegistration) ipcRegistration.unregister();
    if (authManager) authManager.dispose();
});

app.setAsDefaultProtocolClient(APP_CONFIG.APP_NAME.toLowerCase());
if (AUTH_CONFIG.PROTOCOL && AUTH_CONFIG.PROTOCOL !== APP_CONFIG.APP_NAME.toLowerCase()) app.setAsDefaultProtocolClient(AUTH_CONFIG.PROTOCOL);
app.on("open-url", (event, url) => { event.preventDefault(); console.log(`[Desktop App] Protocol URL received: ${url}`); if (url.includes("/auth/callback")) void authManager?.handleCallback(url); else if (mainWindow) mainWindow.webContents.send("protocol-url", url); });

process.on("uncaughtException", error => { console.error("[Desktop App] Uncaught exception:", error); dialog.showErrorBox("Application Error", `An unexpected error occurred: ${error.message}`); });
process.on("unhandledRejection", (reason, promise) => { console.error("[Desktop App] Unhandled rejection at:", promise, "reason:", reason); });
process.on("SIGTERM", async () => {
    console.log("[Desktop App] Received SIGTERM, recording final telemetry...");
    try {
        await recordTelemetry("smoke_test_failed", { error: "Process terminated by SIGTERM (external timeout)", signal: "SIGTERM" }, "error");
        if (smokeTestUploadURL && telemetryRecorder && telemetryUploader) { try { await telemetryUploader.upload(telemetryRecorder.getFilePath()!, smokeTestUploadURL, "sigterm"); console.log("[Desktop App] Telemetry uploaded before exit"); } catch (uploadError) { console.error("[Desktop App] Failed to upload telemetry:", uploadError); } }
    } catch (telemetryError) { console.error("[Desktop App] Failed to record final telemetry:", telemetryError); }
    process.exit(1);
});
