import { app, BrowserWindow, net, shell, Menu, ipcMain, dialog, Tray, nativeImage } from "electron";
import { type ChildProcess, fork, spawn } from "node:child_process";
import path from "node:path";
import process from "node:process";
import { autoUpdater } from "electron-updater";

// ===== TEMPLATE CONFIGURATION - GENERATED BY SCENARIO-TO-DESKTOP =====
// This configuration is automatically populated during generation
const APP_CONFIG = {
    // Application identity
    APP_NAME: "{{APP_NAME}}",
    APP_DISPLAY_NAME: "{{APP_DISPLAY_NAME}}",
    APP_VERSION: "{{VERSION}}",
    APP_URL: "{{APP_URL}}",
    
    // Server configuration
    SERVER_TYPE: "{{SERVER_TYPE}}", // Options: 'node', 'static', 'external', 'executable'
    SERVER_PORT: {{SERVER_PORT}},
    SERVER_PATH: "{{SERVER_PATH}}", // Path to server entry point (relative to app root)
    API_ENDPOINT: "{{API_ENDPOINT}}", // Scenario API endpoint
    
    // Window configuration  
    WINDOW_WIDTH: {{WINDOW_WIDTH}},
    WINDOW_HEIGHT: {{WINDOW_HEIGHT}},
    WINDOW_BACKGROUND: "{{WINDOW_BACKGROUND}}",
    WINDOW_TITLE: "{{APP_DISPLAY_NAME}}",
    
    // Feature configuration
    ENABLE_SPLASH: {{ENABLE_SPLASH}},
    ENABLE_MENU: {{ENABLE_MENU}},
    ENABLE_SYSTEM_TRAY: {{ENABLE_SYSTEM_TRAY}},
    ENABLE_AUTO_UPDATER: {{ENABLE_AUTO_UPDATER}},
    ENABLE_SINGLE_INSTANCE: {{ENABLE_SINGLE_INSTANCE}},
    ENABLE_DEV_TOOLS: {{ENABLE_DEV_TOOLS}},
    
    // Timing configuration
    SERVER_CHECK_INTERVAL_MS: 500,
    SERVER_CHECK_TIMEOUT_MS: 30000,
};

let serverProcess: ChildProcess | null = null;
let mainWindow: BrowserWindow | null = null;
let splashWindow: BrowserWindow | null = null;
let tray: Tray | null = null;

const SERVER_URL = APP_CONFIG.SERVER_TYPE === 'external' 
    ? APP_CONFIG.SERVER_PATH 
    : `http://localhost:${APP_CONFIG.SERVER_PORT}`;

// ===== UTILITY FUNCTIONS =====

function checkServerReady(url: string, timeout: number): Promise<void> {
    return new Promise((resolve, reject) => {
        let elapsedTime = 0;
        const interval = setInterval(() => {
            const request = net.request(url);
            request.on("response", (response) => {
                console.log(`[Desktop App] Server check successful (Status: ${response.statusCode}) at ${url}`);
                clearInterval(interval);
                request.abort();
                resolve();
            });
            request.on("error", (error) => {
                if (!error.message.includes("ECONNREFUSED")) {
                    console.error(`[Desktop App] Server check error: ${error.message}`);
                }
                request.abort();
            });
            request.end();

            elapsedTime += APP_CONFIG.SERVER_CHECK_INTERVAL_MS;
            if (elapsedTime >= timeout) {
                clearInterval(interval);
                console.error(`[Desktop App] Server did not become ready at ${url} within ${timeout}ms.`);
                reject(new Error(`Server not ready within timeout: ${url}`));
            }
        }, APP_CONFIG.SERVER_CHECK_INTERVAL_MS);
    });
}

function createSplashWindow() {
    if (!APP_CONFIG.ENABLE_SPLASH) return;
    
    console.log("[Desktop App] Creating splash window...");
    splashWindow = new BrowserWindow({
        width: 400,
        height: 300,
        frame: false,
        alwaysOnTop: true,
        transparent: true,
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
        },
    });

    splashWindow.loadFile(path.join(__dirname, "../splash.html"));
    
    splashWindow.on("closed", () => {
        splashWindow = null;
    });
}

async function createMainWindow() {
    console.log("[Desktop App] Creating main window (hidden)...");
    const appIcon = getAppIcon();
    mainWindow = new BrowserWindow({
        width: APP_CONFIG.WINDOW_WIDTH,
        height: APP_CONFIG.WINDOW_HEIGHT,
        show: false,
        backgroundColor: APP_CONFIG.WINDOW_BACKGROUND,
        title: APP_CONFIG.WINDOW_TITLE,
        webPreferences: {
            preload: path.join(__dirname, "preload.js"),
            nodeIntegration: false,
            contextIsolation: true,
        },
        ...(appIcon && { icon: appIcon }),
    });

    // Handle external link clicks
    mainWindow.webContents.setWindowOpenHandler(({ url }) => {
        shell.openExternal(url);
        return { action: 'deny' };
    });

    mainWindow.on("closed", () => {
        mainWindow = null;
    });

    // Enable DevTools in development
    if (APP_CONFIG.ENABLE_DEV_TOOLS && !app.isPackaged) {
        mainWindow.webContents.openDevTools();
    }

    return mainWindow;
}

function getAppIcon(): string | undefined {
    const iconPath = path.join(app.getAppPath(), "assets");
    
    if (process.platform === "win32") {
        return path.join(iconPath, "icon.ico");
    } else if (process.platform === "darwin") {
        return path.join(iconPath, "icon.icns");
    } else {
        return path.join(iconPath, "icon.png");
    }
}

function createSystemTray() {
    if (!APP_CONFIG.ENABLE_SYSTEM_TRAY) return;
    
    const iconPath = getAppIcon();
    if (!iconPath) return;
    
    try {
        const icon = nativeImage.createFromPath(iconPath);
        tray = new Tray(icon.resize({ width: 16, height: 16 }));
        
        const contextMenu = Menu.buildFromTemplate([
            {
                label: `Show ${APP_CONFIG.APP_DISPLAY_NAME}`,
                click: () => {
                    if (mainWindow) {
                        mainWindow.show();
                        mainWindow.focus();
                    }
                }
            },
            {
                label: `About ${APP_CONFIG.APP_DISPLAY_NAME}`,
                click: () => {
                    dialog.showMessageBox(mainWindow!, {
                        type: "info",
                        title: `About ${APP_CONFIG.APP_DISPLAY_NAME}`,
                        message: APP_CONFIG.APP_DISPLAY_NAME,
                        detail: `Version ${APP_CONFIG.APP_VERSION}\n\nBuilt with scenario-to-desktop`
                    });
                }
            },
            { type: "separator" },
            {
                label: "Quit",
                click: () => {
                    app.quit();
                }
            }
        ]);
        
        tray.setToolTip(APP_CONFIG.APP_DISPLAY_NAME);
        tray.setContextMenu(contextMenu);
        
        tray.on("double-click", () => {
            if (mainWindow) {
                mainWindow.show();
                mainWindow.focus();
            }
        });
    } catch (error) {
        console.error("[Desktop App] Failed to create system tray:", error);
    }
}

function createApplicationMenu() {
    if (!APP_CONFIG.ENABLE_MENU) return;
    
    const template: Electron.MenuItemConstructorOptions[] = [
        {
            label: "File",
            submenu: [
                {
                    label: "New",
                    accelerator: "CmdOrCtrl+N",
                    click: () => {
                        // Send message to renderer process
                        if (mainWindow) {
                            mainWindow.webContents.send("menu-action", { action: "new" });
                        }
                    }
                },
                {
                    label: "Open",
                    accelerator: "CmdOrCtrl+O",
                    click: async () => {
                        if (!mainWindow) return;
                        
                        const result = await dialog.showOpenDialog(mainWindow, {
                            properties: ["openFile"],
                            filters: [
                                { name: "All Files", extensions: ["*"] }
                            ]
                        });
                        
                        if (!result.canceled && result.filePaths.length > 0) {
                            mainWindow.webContents.send("menu-action", { 
                                action: "open", 
                                filePath: result.filePaths[0] 
                            });
                        }
                    }
                },
                { type: "separator" },
                process.platform === "darwin" ? { role: "close" } : { role: "quit" }
            ]
        },
        {
            label: "Edit",
            submenu: [
                { role: "undo" },
                { role: "redo" },
                { type: "separator" },
                { role: "cut" },
                { role: "copy" },
                { role: "paste" },
                { role: "selectAll" }
            ]
        },
        {
            label: "View",
            submenu: [
                { role: "reload" },
                { role: "forceReload" },
                { role: "toggleDevTools" },
                { type: "separator" },
                { role: "resetZoom" },
                { role: "zoomIn" },
                { role: "zoomOut" },
                { type: "separator" },
                { role: "togglefullscreen" }
            ]
        },
        {
            label: "Window",
            submenu: [
                { role: "minimize" },
                { role: "close" }
            ]
        },
        {
            label: "Help",
            submenu: [
                {
                    label: `About ${APP_CONFIG.APP_DISPLAY_NAME}`,
                    click: () => {
                        dialog.showMessageBox(mainWindow!, {
                            type: "info",
                            title: `About ${APP_CONFIG.APP_DISPLAY_NAME}`,
                            message: APP_CONFIG.APP_DISPLAY_NAME,
                            detail: `Version ${APP_CONFIG.APP_VERSION}\n\nBuilt with scenario-to-desktop\n\n${APP_CONFIG.APP_URL || ""}`
                        });
                    }
                }
            ]
        }
    ];

    const menu = Menu.buildFromTemplate(template);
    Menu.setApplicationMenu(menu);
}

async function startScenarioServer() {
    if (APP_CONFIG.SERVER_TYPE === "external") {
        console.log(`[Desktop App] Using external server: ${APP_CONFIG.SERVER_PATH}`);
        return;
    }
    
    if (APP_CONFIG.SERVER_TYPE === "static") {
        console.log("[Desktop App] Using static files, no server to start");
        return;
    }

    const serverPath = path.resolve(app.getAppPath(), APP_CONFIG.SERVER_PATH);
    console.log(`[Desktop App] Starting scenario server: ${serverPath}`);

    try {
        if (APP_CONFIG.SERVER_TYPE === "node") {
            serverProcess = fork(serverPath, [], {
                env: {
                    ...process.env,
                    PORT: APP_CONFIG.SERVER_PORT.toString(),
                    DESKTOP_MODE: "true",
                    API_ENDPOINT: APP_CONFIG.API_ENDPOINT,
                },
                stdio: "inherit",
            });
        } else if (APP_CONFIG.SERVER_TYPE === "executable") {
            serverProcess = spawn(serverPath, [], {
                env: {
                    ...process.env,
                    PORT: APP_CONFIG.SERVER_PORT.toString(),
                    DESKTOP_MODE: "true",
                    API_ENDPOINT: APP_CONFIG.API_ENDPOINT,
                },
                stdio: "inherit",
            });
        }

        if (serverProcess) {
            serverProcess.on("error", (error) => {
                console.error(`[Desktop App] Server process error: ${error}`);
                dialog.showErrorBox("Server Error", `Failed to start scenario server: ${error.message}`);
            });

            serverProcess.on("exit", (code, signal) => {
                console.log(`[Desktop App] Server process exited with code ${code} and signal ${signal}`);
            });
        }
    } catch (error) {
        console.error(`[Desktop App] Failed to start server: ${error}`);
        dialog.showErrorBox("Startup Error", `Failed to start scenario server: ${error}`);
    }
}

function setupAutoUpdater() {
    if (!APP_CONFIG.ENABLE_AUTO_UPDATER || !app.isPackaged) return;
    
    autoUpdater.logger = console;
    
    autoUpdater.on("checking-for-update", () => {
        console.log("[Desktop App] Checking for update...");
    });
    
    autoUpdater.on("update-available", (info) => {
        console.log("[Desktop App] Update available:", info);
    });
    
    autoUpdater.on("update-not-available", (info) => {
        console.log("[Desktop App] Update not available:", info);
    });
    
    autoUpdater.on("error", (err) => {
        console.error("[Desktop App] Update error:", err);
    });
    
    autoUpdater.on("download-progress", (progressObj) => {
        const logMessage = `Download speed: ${progressObj.bytesPerSecond} - Downloaded ${progressObj.percent}% (${progressObj.transferred}/${progressObj.total})`;
        console.log(logMessage);
    });
    
    autoUpdater.on("update-downloaded", (info) => {
        console.log("[Desktop App] Update downloaded");
        autoUpdater.quitAndInstall();
    });
    
    // Check for updates
    autoUpdater.checkForUpdatesAndNotify();
}

// ===== IPC HANDLERS =====

// File operations
ipcMain.handle("file:save", async (event, data: { content: string; defaultPath?: string }) => {
    if (!mainWindow) return null;

    const dialogOptions: Electron.SaveDialogOptions = {
        filters: [
            { name: "All Files", extensions: ["*"] }
        ]
    };

    if (data.defaultPath) {
        dialogOptions.defaultPath = data.defaultPath;
    }

    const result = await dialog.showSaveDialog(mainWindow, dialogOptions);
    
    if (result.canceled) return null;
    
    const fs = require("fs").promises;
    await fs.writeFile(result.filePath, data.content);
    return result.filePath;
});

ipcMain.handle("file:open", async () => {
    if (!mainWindow) return null;
    
    const result = await dialog.showOpenDialog(mainWindow, {
        properties: ["openFile"],
        filters: [
            { name: "All Files", extensions: ["*"] }
        ]
    });
    
    if (result.canceled || result.filePaths.length === 0) return null;
    
    const fs = require("fs").promises;
    const content = await fs.readFile(result.filePaths[0], "utf-8");
    return { filePath: result.filePaths[0], content };
});

// System information
ipcMain.handle("system:info", () => {
    return {
        platform: process.platform,
        arch: process.arch,
        version: process.version,
        appVersion: APP_CONFIG.APP_VERSION,
        isPackaged: app.isPackaged,
    };
});

// Application control
ipcMain.handle("app:minimize", () => {
    if (mainWindow) {
        mainWindow.minimize();
    }
});

ipcMain.handle("app:maximize", () => {
    if (mainWindow) {
        if (mainWindow.isMaximized()) {
            mainWindow.unmaximize();
        } else {
            mainWindow.maximize();
        }
    }
});

ipcMain.handle("app:close", () => {
    if (mainWindow) {
        mainWindow.close();
    }
});

// ===== APP EVENT HANDLERS =====

app.whenReady().then(async () => {
    // Single instance lock
    if (APP_CONFIG.ENABLE_SINGLE_INSTANCE) {
        const gotTheLock = app.requestSingleInstanceLock();
        if (!gotTheLock) {
            app.quit();
            return;
        }
        
        app.on('second-instance', () => {
            if (mainWindow) {
                if (mainWindow.isMinimized()) mainWindow.restore();
                mainWindow.focus();
            }
        });
    }

    try {
        // Create splash screen
        createSplashWindow();
        
        // Set up auto updater
        setupAutoUpdater();
        
        // Create application menu
        createApplicationMenu();
        
        // Create system tray
        createSystemTray();
        
        // Start scenario server
        await startScenarioServer();
        
        // Create main window
        await createMainWindow();
        
        // Wait for server to be ready
        if (APP_CONFIG.SERVER_TYPE !== "static") {
            await checkServerReady(SERVER_URL, APP_CONFIG.SERVER_CHECK_TIMEOUT_MS);
        }
        
        // Load the application
        if (APP_CONFIG.SERVER_TYPE === "static") {
            const staticPath = path.resolve(app.getAppPath(), APP_CONFIG.SERVER_PATH);
            await mainWindow!.loadFile(staticPath);
        } else {
            await mainWindow!.loadURL(SERVER_URL);
        }
        
        // Close splash and show main window
        if (splashWindow) {
            splashWindow.close();
        }
        mainWindow!.show();
        mainWindow!.focus();
        
        console.log(`[Desktop App] ${APP_CONFIG.APP_DISPLAY_NAME} ready!`);
        
    } catch (error) {
        console.error("[Desktop App] Startup error:", error);
        if (splashWindow) {
            splashWindow.close();
        }
        dialog.showErrorBox("Startup Error", `Failed to start ${APP_CONFIG.APP_DISPLAY_NAME}: ${error}`);
        app.quit();
    }
});

app.on("window-all-closed", () => {
    // On macOS, keep app running even when all windows are closed
    if (process.platform !== "darwin" && !APP_CONFIG.ENABLE_SYSTEM_TRAY) {
        app.quit();
    }
});

app.on("activate", async () => {
    // On macOS, re-create window when dock icon is clicked
    if (BrowserWindow.getAllWindows().length === 0) {
        await createMainWindow();
    }
});

app.on("before-quit", () => {
    // Clean up server process
    if (serverProcess) {
        console.log("[Desktop App] Terminating server process...");
        serverProcess.kill();
        serverProcess = null;
    }
});

// Handle protocol for deep linking (optional)
app.setAsDefaultProtocolClient(APP_CONFIG.APP_NAME.toLowerCase());
app.on('open-url', (event, url) => {
    event.preventDefault();
    console.log(`[Desktop App] Protocol URL received: ${url}`);
    if (mainWindow) {
        mainWindow.webContents.send("protocol-url", url);
    }
});

process.on("uncaughtException", (error) => {
    console.error("[Desktop App] Uncaught exception:", error);
    dialog.showErrorBox("Application Error", `An unexpected error occurred: ${error.message}`);
});

process.on("unhandledRejection", (reason, promise) => {
    console.error("[Desktop App] Unhandled rejection at:", promise, "reason:", reason);
});