# Deployment orchestration for scenario-to-app conversion
# This file defines HOW to deploy a scenario as a running application
apiVersion: vrooli.com/v1
kind: ScenarioApp
metadata:
  name: "image-generation-pipeline"  # Populated from metadata.yaml
  version: "1.0.0"
  labels:
    category: "{{ categories[0] }}"
    complexity: "{{ complexity }}"

# Deployment orchestration - the critical missing piece
deployment:
  # Step-by-step app initialization sequence
  startup_sequence:
    - name: validate_resources
      description: "Check that all required resources are healthy"
      action: check_health
      resources: "{{ resources.required }}"
      timeout_seconds: 30
      
    - name: initialize_database
      description: "Create database schema and seed data"
      action: execute_sql
      condition: "postgres in resources.required"
      files: 
        - "initialization/database/schema.sql"
        - "initialization/database/seed.sql"
      database_url: "{{ postgres.baseUrl }}"
      
    - name: deploy_workflows
      description: "Import workflows into automation platforms"
      action: import_workflows
      targets:
        n8n: 
          condition: "n8n in resources.required"
          files: "initialization/workflows/n8n/*.json"
          base_url: "{{ n8n.baseUrl }}"
        windmill:
          condition: "windmill in resources.required" 
          files: "initialization/workflows/windmill/scripts/*"
          base_url: "{{ windmill.baseUrl }}"
        node-red:
          condition: "node-red in resources.required"
          files: "initialization/workflows/node-red/*.json"
          base_url: "{{ node-red.baseUrl }}"
        
    - name: apply_configuration
      description: "Load runtime configuration and feature flags"
      action: load_config
      files:
        - "initialization/configuration/app-config.json"
        - "initialization/configuration/resource-urls.json"
        - "initialization/configuration/feature-flags.json"
        
    - name: seed_vector_data
      description: "Initialize vector database with embeddings"
      action: seed_vectors
      condition: "qdrant in resources.required"
      source: "initialization/vectors/"
      target_url: "{{ qdrant.baseUrl }}"
      
    - name: deploy_ui
      description: "Create professional user interface"
      action: create_app
      condition: "windmill in resources.required and requires_ui"
      source: "initialization/ui/windmill-app.json"
      target_url: "{{ windmill.baseUrl }}"
      
    - name: configure_storage
      description: "Set up object storage buckets and permissions"
      action: configure_storage
      condition: "minio in resources.required"
      source: "initialization/storage/minio-config.json"
      target_url: "{{ minio.baseUrl }}"
      
    - name: activate_triggers
      description: "Enable workflows and start background processes"
      action: enable_workflows
      config: "initialization/workflows/triggers.yaml"
      delay_seconds: 5  # Allow services to fully initialize

# Health monitoring configuration
health_checks:
  - name: app_health
    endpoint: "/api/health"
    interval: 30s
    timeout: 5s
    
  - name: workflow_health
    endpoint: "/api/workflows/status"
    interval: 60s
    timeout: 10s
    
  - name: database_health
    condition: "postgres in resources.required"
    endpoint: "/api/database/health"
    interval: 30s
    timeout: 5s

# Application URLs after deployment
urls:
  # Main application interface
  app: "{{ windmill.baseUrl }}/app/image-generation-pipeline"
  
  # Administrative interface
  admin: "{{ windmill.baseUrl }}/admin/image-generation-pipeline"
  
  # API endpoints
  api: "http://localhost:3000/api/image-generation-pipeline"
  
  # Health check endpoint
  health: "http://localhost:3000/api/image-generation-pipeline/health"
  
  # Workflow monitoring
  workflows: "{{ n8n.baseUrl }}/workflows"

# Resource configuration generation
resource_config:
  # Generate .vrooli/resources.local.json with only required resources
  enabled_only: true
  
  # Override default ports if needed
  port_overrides:
    postgres: 5433
    redis: 6380
    minio: 9000
    
  # Resource-specific settings
  postgres:
    database: "{{ scenario.id | replace('-', '_') }}"
    max_connections: 20
    
  redis:
    max_memory: "256mb"
    persistence: "rdb"
    
  minio:
    buckets:
      - "image-generation-pipeline-assets"
      - "image-generation-pipeline-uploads"

# Cleanup procedures for scenario testing
cleanup:
  # Database cleanup
  postgres:
    - "DROP SCHEMA IF EXISTS {{ scenario.id | replace('-', '_') }} CASCADE;"
    
  # Workflow cleanup  
  n8n:
    - action: delete_workflows
      filter: "tags:image-generation-pipeline"
      
  windmill:
    - action: delete_workspace
      name: "image-generation-pipeline"
      
  # Storage cleanup
  minio:
    - action: delete_buckets
      buckets: 
        - "image-generation-pipeline-assets"
        - "image-generation-pipeline-uploads"

# Validation rules
validation:
  # Pre-deployment checks
  pre_deploy:
    - check: resource_availability
      resources: "{{ resources.required }}"
      
    - check: port_availability
      ports: [3000, 5678, 5681]  # Common app ports
      
    - check: disk_space
      minimum: "1GB"
      
  # Post-deployment checks  
  post_deploy:
    - check: health_endpoints
      timeout: 60s
      
    - check: workflow_status
      condition: "n8n in resources.required or windmill in resources.required"
      
    - check: database_connectivity
      condition: "postgres in resources.required"

# Performance monitoring
monitoring:
  # Key metrics to track
  metrics:
    - name: response_time
      endpoint: "/api/health"
      target_p95: "{{ performance.latency.p95 | default('500ms') }}"
      
    - name: throughput
      endpoint: "/api/image-generation-pipeline"
      target_rps: "{{ performance.throughput.requests_per_second | default(10) }}"
      
    - name: error_rate
      endpoint: "/api/image-generation-pipeline"
      target_error_rate: "1%"

# Development mode settings
development:
  # Enable hot reloading
  hot_reload: true
  
  # Enhanced logging
  log_level: "debug"
  
  # Skip certain validations
  skip_validations: ["disk_space", "performance"]
  
  # Shorter timeouts for faster iteration
  timeouts:
    startup: 30s
    health_check: 5s