// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
    description: "app.description",
  },
  actions: {
    refresh: "actions.refresh",
  },
  states: {
    allowed: "states.allowed",
    blocked: "states.blocked",
    loading: "states.loading",
    none: "states.none",
    unknown: "states.unknown",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    sidebarNavLabel: "layout.sidebarNavLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      providers: "layout.nav.providers",
      routePreview: "layout.nav.routePreview",
      conformance: "layout.nav.conformance",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      eyebrow: "pages.dashboard.eyebrow",
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      summaryLabel: "pages.dashboard.summaryLabel",
      metrics: {
        providers: "pages.dashboard.metrics.providers",
        roles: "pages.dashboard.metrics.roles",
        routes: "pages.dashboard.metrics.routes",
        failures: "pages.dashboard.metrics.failures",
        findings: "pages.dashboard.metrics.findings",
        evidence: "pages.dashboard.metrics.evidence",
        metadataOnly: "pages.dashboard.metrics.metadataOnly",
        redaction: "pages.dashboard.metrics.redaction",
      },
      routeActivity: "pages.dashboard.routeActivity",
      policyGaps: "pages.dashboard.policyGaps",
      noEvidence: "pages.dashboard.noEvidence",
      noFindings: "pages.dashboard.noFindings",
      columns: {
        scenario: "pages.dashboard.columns.scenario",
        role: "pages.dashboard.columns.role",
        provider: "pages.dashboard.columns.provider",
        status: "pages.dashboard.columns.status",
      },
    },
    providers: {
      eyebrow: "pages.providers.eyebrow",
      title: "pages.providers.title",
      description: "pages.providers.description",
      empty: "pages.providers.empty",
      smoke: "pages.providers.smoke",
      smokeDescription: "pages.providers.smokeDescription",
      columns: {
        provider: "pages.providers.columns.provider",
        role: "pages.providers.columns.role",
        locality: "pages.providers.columns.locality",
        status: "pages.providers.columns.status",
        capabilities: "pages.providers.columns.capabilities",
        policy: "pages.providers.columns.policy",
      },
    },
    routePreview: {
      eyebrow: "pages.routePreview.eyebrow",
      title: "pages.routePreview.title",
      description: "pages.routePreview.description",
      formLabel: "pages.routePreview.formLabel",
      preview: "pages.routePreview.preview",
      execute: "pages.routePreview.execute",
      empty: "pages.routePreview.empty",
      selectedRoute: "pages.routePreview.selectedRoute",
      selectedRouteDescription: "pages.routePreview.selectedRouteDescription",
      selectedProvider: "pages.routePreview.selectedProvider",
      routePlan: "pages.routePreview.routePlan",
      fallback: "pages.routePreview.fallback",
      selected: "pages.routePreview.selected",
      fallbackCandidate: "pages.routePreview.fallbackCandidate",
      rejected: "pages.routePreview.rejected",
      fields: {
        scenario: "pages.routePreview.fields.scenario",
        operation: "pages.routePreview.fields.operation",
        role: "pages.routePreview.fields.role",
        profile: "pages.routePreview.fields.profile",
        privacy: "pages.routePreview.fields.privacy",
        timeout: "pages.routePreview.fields.timeout",
        maxCost: "pages.routePreview.fields.maxCost",
        maxTokens: "pages.routePreview.fields.maxTokens",
      },
      columns: {
        provider: "pages.routePreview.columns.provider",
        role: "pages.routePreview.columns.role",
        locality: "pages.routePreview.columns.locality",
        status: "pages.routePreview.columns.status",
        reason: "pages.routePreview.columns.reason",
        health: "pages.routePreview.columns.health",
      },
    },
    conformance: {
      eyebrow: "pages.conformance.eyebrow",
      title: "pages.conformance.title",
      description: "pages.conformance.description",
      formLabel: "pages.conformance.formLabel",
      resultLabel: "pages.conformance.resultLabel",
      scenario: "pages.conformance.scenario",
      scan: "pages.conformance.scan",
      initial: "pages.conformance.initial",
      maturity: "pages.conformance.maturity",
      findingCount: "pages.conformance.findingCount",
      findingCount_one: "pages.conformance.findingCount_one",
      empty: "pages.conformance.empty",
      recommendations: "pages.conformance.recommendations",
      columns: {
        rule: "pages.conformance.columns.rule",
        severity: "pages.conformance.columns.severity",
        path: "pages.conformance.columns.path",
        message: "pages.conformance.columns.message",
        remediation: "pages.conformance.columns.remediation",
      },
    },
    settings: {
      eyebrow: "pages.settings.eyebrow",
      title: "pages.settings.title",
      description: "pages.settings.description",
      policyHeading: "pages.settings.policyHeading",
      displayHeading: "pages.settings.displayHeading",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      privacyDefault: "pages.settings.privacyDefault",
      privacyDefaultDetail: "pages.settings.privacyDefaultDetail",
      privacyInternal: "pages.settings.privacyInternal",
      privacyConfidential: "pages.settings.privacyConfidential",
      privacySecret: "pages.settings.privacySecret",
      evidenceRetention: "pages.settings.evidenceRetention",
      evidenceRetentionDetail: "pages.settings.evidenceRetentionDetail",
      metadataOnly: "pages.settings.metadataOnly",
      shortRetention: "pages.settings.shortRetention",
      smokeBeforeExecute: "pages.settings.smokeBeforeExecute",
      smokeBeforeExecuteDetail: "pages.settings.smokeBeforeExecuteDetail",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
