package harness

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/vrooli/api-core/database"
	"github.com/vrooli/api-core/filerouting"
	"github.com/vrooli/api-core/storage"
	"vrooli-memory/internal/recall"
)

const generatedHeader = "<!-- GENERATED BY vrooli-memory; hand edits are overwritten. -->\n"

type projectionTarget struct {
	Runtime, Path string
	Cap           int
}

type ProjectionResult struct {
	Path, Content string
	SizeBytes     int64
	Overflow      bool
	DryRun        bool
}

type Projector struct {
	db      *sql.DB
	wake    *recall.Service
	roots   *filerouting.RoutedRoots
	targets map[string]projectionTarget
}

func NewProjector(db *sql.DB, wake *recall.Service, roots ...*filerouting.RoutedRoots) *Projector {
	home, _ := os.UserHomeDir()
	p := &Projector{db: db, wake: wake, targets: map[string]projectionTarget{
		"claude-code": {Runtime: "claude-code", Path: filepath.Join(home, ".claude", "projects", "-home-matthalloran8-Vrooli", "memory", "MEMORY.md"), Cap: 32768},
		"gemini":      {Runtime: "gemini", Path: filepath.Join(home, ".gemini", "GEMINI.md"), Cap: 32768},
		"codex":       {Runtime: "codex", Path: filepath.Join(home, ".codex", "AGENTS.md"), Cap: 32768},
		"opencode":    {Runtime: "opencode", Path: filepath.Join(home, ".config", "opencode", "AGENTS.md"), Cap: 32768},
		"grok":        {Runtime: "grok", Path: filepath.Join(home, ".grok", "memory", "MEMORY.md"), Cap: 32768},
	}}
	if len(roots) > 0 {
		p.roots = roots[0]
	}
	return p
}

func (p *Projector) Target(runtime string) (string, bool) {
	t, ok := p.targets[runtime]
	return t.Path, ok
}

func (p *Projector) Project(ctx context.Context, runtime string, dryRun bool) (ProjectionResult, error) {
	t, ok := p.targets[runtime]
	if !ok {
		return ProjectionResult{}, fmt.Errorf("unsupported projection runtime %q", runtime)
	}
	wake, err := p.wake.Wake(ctx, 0)
	if err != nil {
		return ProjectionResult{}, err
	}
	content := generatedHeader + "# Unified Vrooli Memory\n\n"
	for _, hit := range wake.Hits {
		chunk := "- " + strings.TrimSpace(hit.Node.Text) + "\n\n"
		if len(content)+len(chunk) > t.Cap {
			if hit.Node.Pinned {
				return ProjectionResult{}, fmt.Errorf("pinned memory exceeds %d-byte projection cap for %s", t.Cap, runtime)
			}
			return p.finish(ctx, t, content, true, dryRun)
		}
		content += chunk
	}
	return p.finish(ctx, t, content, wake.Overflow, dryRun)
}

func (p *Projector) finish(ctx context.Context, t projectionTarget, content string, overflow, dryRun bool) (ProjectionResult, error) {
	path, err := p.targetPath(ctx, t)
	if err != nil {
		return ProjectionResult{}, err
	}
	r := ProjectionResult{Path: path, Content: content, SizeBytes: int64(len(content)), Overflow: overflow, DryRun: dryRun}
	if dryRun {
		return r, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return ProjectionResult{}, err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".vrooli-memory-projection-*")
	if err != nil {
		return ProjectionResult{}, err
	}
	name := tmp.Name()
	defer os.Remove(name)
	if _, err = tmp.WriteString(content); err != nil {
		tmp.Close()
		return ProjectionResult{}, err
	}
	if err = tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return ProjectionResult{}, err
	}
	if err = tmp.Close(); err != nil {
		return ProjectionResult{}, err
	}
	if err = os.Rename(name, path); err != nil {
		return ProjectionResult{}, err
	}
	if p.roots != nil {
		p.roots.RecordWrite(ctx)
	}
	sum := sha256.Sum256([]byte(content))
	_, err = p.db.ExecContext(ctx, `INSERT INTO harness_projections(runtime,target_path,content_hash,size_bytes,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(runtime) DO UPDATE SET target_path=excluded.target_path,content_hash=excluded.content_hash,size_bytes=excluded.size_bytes,updated_at=excluded.updated_at`, t.Runtime, path, hex.EncodeToString(sum[:]), len(content), time.Now().UTC().Format(time.RFC3339Nano))
	return r, err
}

func (p *Projector) targetPath(ctx context.Context, t projectionTarget) (string, error) {
	if !database.IsTestMode(ctx) || p.roots == nil {
		return t.Path, nil
	}
	root, err := p.roots.Pick(ctx, storage.ClassData)
	if err != nil {
		return "", fmt.Errorf("resolve routed projection root: %w", err)
	}
	return filepath.Join(root, "harness-projections", t.Runtime, filepath.Base(t.Path)), nil
}
