package harness

import (
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// curatedFilesSpec is embedded so the memory scenario, rather than a runtime
// or an agent resource, owns the curated-instruction topology.
//
//go:embed curated-files.json
var curatedFilesSpec []byte

const (
	workspaceRootEnv      = "VROOLI_MEMORY_WORKSPACE_ROOT"
	wakeStart             = "<!-- vrooli-memory:wake:start -->"
	wakeEnd               = "<!-- vrooli-memory:wake:end -->"
	generatedHeader       = "<!-- GENERATED BY vrooli-memory; only the managed wake block is maintained. -->\n"
	legacyGeneratedHeader = "<!-- GENERATED BY vrooli-memory; hand edits are overwritten. -->\n"
	promptStart           = "<!-- vrooli-memory:prompt-block:start -->"
	promptEnd             = "<!-- vrooli-memory:prompt-block:end -->"
)

type curatedFiles struct {
	Canonical        string   `json:"canonical"`
	WorkspaceAliases []string `json:"workspace_aliases"`
	HomeAliases      []string `json:"home_aliases"`
}

type CuratedTopologyResult struct {
	Canonical string
	Aliases   []string
	Changed   bool
}

// EnsureCuratedTopology repairs only the declared curated instruction links.
// It never projects memory into them. If the canonical file is missing, the
// richest surviving non-generated candidate becomes the canonical content;
// distinct candidate content is appended rather than discarded.
func EnsureCuratedTopology(root, home string) (CuratedTopologyResult, error) {
	spec, err := loadCuratedFiles()
	if err != nil {
		return CuratedTopologyResult{}, err
	}
	if root == "" {
		root = os.Getenv(workspaceRootEnv)
	}
	if root == "" {
		root, err = discoverWorkspaceRoot()
		if err != nil {
			return CuratedTopologyResult{}, err
		}
	}
	root, err = filepath.Abs(root)
	if err != nil {
		return CuratedTopologyResult{}, fmt.Errorf("resolve curated workspace root: %w", err)
	}
	if home == "" {
		home, err = os.UserHomeDir()
		if err != nil {
			return CuratedTopologyResult{}, fmt.Errorf("resolve home for curated topology: %w", err)
		}
	}

	canonical := filepath.Join(root, spec.Canonical)
	paths := make([]string, 0, len(spec.WorkspaceAliases)+len(spec.HomeAliases))
	for _, alias := range spec.WorkspaceAliases {
		paths = append(paths, filepath.Join(root, alias))
	}
	for _, alias := range spec.HomeAliases {
		paths = append(paths, filepath.Join(home, alias))
	}

	canonicalContent, canonicalFound, readErr := curatedCandidate(canonical)
	if readErr != nil {
		return CuratedTopologyResult{}, readErr
	}
	var content string
	if canonicalFound {
		// Once the project-level file exists, it is authoritative. Peer files
		// are recovery inputs only; they must never rewrite operator-curated
		// canonical content just because a peer happens to be longer.
		content = canonicalContent
	} else {
		candidates := make([]string, 0, len(paths))
		for _, path := range paths {
			candidate, ok, readErr := curatedCandidate(path)
			if readErr != nil {
				return CuratedTopologyResult{}, readErr
			}
			if ok {
				candidates = append(candidates, candidate)
			}
		}
		content, err = mergeCuratedCandidates(candidates)
		if err != nil {
			return CuratedTopologyResult{}, fmt.Errorf("recover curated canonical %s: %w", canonical, err)
		}
	}
	if content == "" {
		return CuratedTopologyResult{}, fmt.Errorf("curated canonical %s is missing and no surviving candidate exists", canonical)
	}

	changed := false
	if current, err := os.ReadFile(canonical); err == nil {
		if string(current) != content || isSymlink(canonical) {
			changed = true
		}
	} else if !os.IsNotExist(err) {
		return CuratedTopologyResult{}, fmt.Errorf("read curated canonical %s: %w", canonical, err)
	} else {
		changed = true
	}
	if changed {
		if isSymlink(canonical) {
			if err := os.Remove(canonical); err != nil {
				return CuratedTopologyResult{}, fmt.Errorf("materialize curated canonical %s: %w", canonical, err)
			}
		}
		if err := writeRegularFile(canonical, []byte(content)); err != nil {
			return CuratedTopologyResult{}, err
		}
	}

	for _, alias := range paths {
		wasCorrect := isCorrectSymlink(alias, canonical)
		if err := ensureSymlink(alias, canonical); err != nil {
			return CuratedTopologyResult{}, err
		}
		if !wasCorrect {
			changed = true
		}
	}
	return CuratedTopologyResult{Canonical: canonical, Aliases: paths, Changed: changed}, nil
}

func loadCuratedFiles() (curatedFiles, error) {
	var spec curatedFiles
	if err := json.Unmarshal(curatedFilesSpec, &spec); err != nil {
		return curatedFiles{}, fmt.Errorf("parse curated-files.json: %w", err)
	}
	if spec.Canonical == "" {
		return curatedFiles{}, errors.New("curated-files.json has no canonical file")
	}
	return spec, nil
}

func discoverWorkspaceRoot() (string, error) {
	working, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("discover workspace root: %w", err)
	}
	for current := filepath.Clean(working); ; current = filepath.Dir(current) {
		if info, statErr := os.Stat(filepath.Join(current, "AGENTS.md")); statErr == nil && !info.IsDir() {
			return current, nil
		}
		// AGENTS.md may be the file being repaired. The workspace marker lets
		// recovery locate the project even after the canonical file was deleted.
		if directory(filepath.Join(current, ".vrooli")) && directory(filepath.Join(current, "scenarios")) {
			return current, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
	}
	return "", errors.New("could not find Vrooli workspace root; set VROOLI_MEMORY_WORKSPACE_ROOT")
}

func directory(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func curatedCandidate(path string) (string, bool, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return "", false, nil
	}
	if err != nil {
		return "", false, fmt.Errorf("read curated candidate %s: %w", path, err)
	}
	content, _, err := removePromptBlock(string(data))
	if err != nil {
		return "", false, fmt.Errorf("clean curated candidate %s: %w", path, err)
	}
	if generatedOnly(content) {
		return "", false, nil
	}
	content = strings.TrimRight(content, "\n") + "\n"
	return content, strings.TrimSpace(content) != "", nil
}

func mergeCuratedCandidates(candidates []string) (string, error) {
	if len(candidates) == 0 {
		return "", nil
	}
	// Prefer the richest candidate first. This recovers a deleted canonical
	// file from a peer while retaining all distinct non-generated bytes.
	sort.SliceStable(candidates, func(i, j int) bool { return len(candidates[i]) > len(candidates[j]) })
	merged := candidates[0]
	for _, candidate := range candidates[1:] {
		if candidate == merged || strings.Contains(merged, strings.TrimSpace(candidate)) {
			continue
		}
		merged = strings.TrimRight(merged, "\n") + "\n\n" + strings.TrimLeft(candidate, "\n")
	}
	return strings.TrimRight(merged, "\n") + "\n", nil
}

func removePromptBlock(text string) (string, bool, error) {
	start, end := strings.Index(text, promptStart), strings.Index(text, promptEnd)
	if start < 0 && end < 0 {
		return text, false, nil
	}
	if start < 0 || end < start {
		return "", false, fmt.Errorf("malformed vrooli-memory prompt block")
	}
	return text[:start] + text[end+len(promptEnd):], true, nil
}

func generatedOnly(text string) bool {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return true
	}
	if strings.HasPrefix(trimmed, strings.TrimSpace(generatedHeader)) || strings.HasPrefix(trimmed, strings.TrimSpace(legacyGeneratedHeader)) {
		return true
	}
	return strings.Contains(trimmed, wakeStart) && strings.Contains(trimmed, wakeEnd) && strings.TrimSpace(curatedProjectionBytes(text)) == ""
}

func curatedProjectionBytes(existing string) string {
	startCount := strings.Count(existing, wakeStart)
	endCount := strings.Count(existing, wakeEnd)
	if startCount != 1 || endCount != 1 {
		return existing
	}
	start := strings.Index(existing, wakeStart)
	end := strings.Index(existing, wakeEnd)
	if end < start {
		return existing
	}
	return existing[:start] + existing[end+len(wakeEnd):]
}

func writeRegularFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("prepare curated file %s: %w", path, err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".vrooli-memory-curated-*")
	if err != nil {
		return fmt.Errorf("create curated file %s: %w", path, err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func ensureSymlink(alias, canonical string) error {
	if info, err := os.Lstat(alias); err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			if isCorrectSymlink(alias, canonical) {
				return nil
			}
			if err := os.Remove(alias); err != nil {
				return fmt.Errorf("remove stale curated link %s: %w", alias, err)
			}
		} else if info.IsDir() {
			return fmt.Errorf("curated alias %s is a directory", alias)
		} else if err := os.Remove(alias); err != nil {
			return fmt.Errorf("replace curated alias %s: %w", alias, err)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect curated alias %s: %w", alias, err)
	}
	if err := os.MkdirAll(filepath.Dir(alias), 0o755); err != nil {
		return fmt.Errorf("prepare curated alias %s: %w", alias, err)
	}
	if err := os.Symlink(canonical, alias); err != nil {
		return fmt.Errorf("link curated alias %s -> %s: %w", alias, canonical, err)
	}
	return nil
}

func isCorrectSymlink(alias, canonical string) bool {
	target, err := os.Readlink(alias)
	return err == nil && filepath.Clean(target) == filepath.Clean(canonical)
}

func isSymlink(path string) bool {
	info, err := os.Lstat(path)
	return err == nil && info.Mode()&os.ModeSymlink != 0
}
