// Real ranked decision drawer and owner services; only fetch is replaced.
// All named subjects are disposable and no fixture implies real acceptance.
import { act, cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useLocation } from "react-router-dom";
import type { QueryClient } from "@tanstack/react-query";
import { createTestQueryClient, renderWithProviders } from "../../../test-utils";
import { useBacklogStore, backlogStoreInitialState } from "../../../stores/backlog-store";
import { useSnoozeStore } from "../../../stores/snooze-store";
import { DecisionDrawer } from "./DecisionDrawer";
import type { NextActionFeedEntry } from "../../../services/next-action-service";
let calls:{method:string;path:string;query:string;body:unknown}[];let entries:NextActionFeedEntry[];let replies:Map<string,()=>Response|Promise<Response>>;let unexpected:string[];const clients:QueryClient[]=[];
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
function entry(name="fixture-owner",action="accept_plan",patch:Partial<NextActionFeedEntry>={}):NextActionFeedEntry{return{entity_kind:"backlog_item",entity_ref:`fix/${name}`,entity_title:`Owner ${name}`,action:{id:action,compact_label:"Accept fixture",expanded_label:"Accept current fixture plan",enabled:true,effect:"state_change",reason:"Fixture exact revision"},tier:1,...patch};}
function Location(){const l=useLocation();return <output data-testid="location">{l.pathname+l.search}</output>;}
function mount({open=true,scope=null,route="/plan?keep=fixture",question=null}:{open?:boolean;scope?:string|null;route?:string;question?:string|null}={}){const client=createTestQueryClient();clients.push(client);const complete=vi.fn();const close=vi.fn();const questionChange=vi.fn();const rendered=renderWithProviders(<><Location/><DecisionDrawer isOpen={open} onClose={close} scopeItemKey={scope} currentQuestionId={question} onCurrentQuestionChange={questionChange} onCompleted={complete}/></>,{queryClient:client,initialEntries:[route]});return{client,complete,close,questionChange,...rendered};}
function mutations(){return calls.filter(c=>c.method!=="GET");}
function reads(path:string){return calls.filter(c=>c.method==="GET"&&c.path===path);}
async function ready(){await screen.findByTestId("decision-queue-header");}
beforeEach(()=>{calls=[];unexpected=[];entries=[entry()];useBacklogStore.setState({...backlogStoreInitialState,items:[],blockingMap:{}});useSnoozeStore.setState({entries:new Map()});window.localStorage.clear();replies=new Map([["POST /vrooli.swarm_manager.v1.api.TransitionService/ListTransitions",()=>json({transitions:[{key:"fixture.owner.action",subject:"backlog_item",kind:3,requires:["fixture.integration"]},{key:"fixture.goal.plan",subject:"goal",kind:2,requires:["fixture.integration"]},{key:"milestone.review",subject:"goal_milestone",kind:2,requires:["fixture.integration"]}]})],["GET /integrations",()=>json({integrations:[{id:"fixture.integration",availability:"available",diagnostic:"Fixture available"}]})],["GET /goals/fixture-goal",()=>json({goal:{name:"fixture-goal",title:"Fixture goal",milestones:[{name:"fixture-milestone",title:"Named fixture milestone",acceptance_criteria:["Fixture emits exact evidence"],items:["fix/fixture-owner"]}]}})],["GET /next-actions/feed",()=>json({entries})],["GET /backlog/summary",()=>json({pending_questions:{items:[]}})],["GET /proposal-sessions",()=>json({sessions:[]})]]);vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const r=new Request(input,init);const url=new URL(r.url);const path=url.pathname.replace(/^\/api\/v1/,"");const key=r.method+" "+path;calls.push({method:r.method,path,query:url.search,body:r.body?JSON.parse(await r.text()):undefined});if(!replies.has(key)){unexpected.push(key);throw new Error("Unexpected fixture request "+key);}return replies.get(key)!();}));});
afterEach(()=>{cleanup();clients.splice(0).forEach(c=>c.clear());expect(unexpected).toEqual([]);useBacklogStore.setState({...backlogStoreInitialState,blockingMap:{}});useSnoozeStore.setState({entries:new Map()});window.localStorage.clear();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe("ranked decision owner workflows",()=>{
 it("holds a pending owner action and prevents duplicate writes",async()=>{let release!:(r:Response)=>void;replies.set("POST /backlog/fix/fixture-owner/plan-accept",()=>new Promise(resolve=>{release=resolve}));const{complete}=mount();await ready();fireEvent.click(screen.getByRole("button",{name:"Accept fixture"}));const pending=await screen.findByRole("button",{name:"Working…"});expect(pending).toBeDisabled();fireEvent.click(pending);expect(mutations()).toHaveLength(1);expect(complete).not.toHaveBeenCalled();await act(async()=>{entries=[];release(json({}));});await waitFor(()=>expect(complete).toHaveBeenCalledTimes(1));expect(mutations()).toHaveLength(1);});
 it("confirms one destructive fixture write before refreshing the queue",async()=>{entries=[entry("fixture-owner","archive",{action:{id:"archive",compact_label:"Archive fixture",expanded_label:"Archive fixture",enabled:true,effect:"state_change",destructive:true}})];replies.set("PATCH /backlog/fix/fixture-owner/archive-item",()=>{entries=[];return json({item:{kind:"fix",name:"fixture-owner",title:"Owner fixture-owner",status:"ready",priority:2,created:"2026-10-05T00:00:00Z",updated:"2026-10-05T00:00:00Z",archived_at:"2026-10-05T00:00:00Z"}});});const{complete}=mount();await ready();fireEvent.click(screen.getByRole("button",{name:"Archive fixture…"}));const confirm=await screen.findByTestId("next-action-destructive-confirm");fireEvent.click(within(confirm).getByRole("button",{name:"Archive fixture"}));await waitFor(()=>expect(complete).toHaveBeenCalledTimes(1));expect(mutations()).toEqual([{method:"PATCH",path:"/backlog/fix/fixture-owner/archive-item",query:"",body:{}}]);});
 it("opens the exact returned fixture feedback session without completing another action",async()=>{replies.set("POST /proposal-sessions",()=>json({id:"fixture-feedback"}));const{complete}=mount();await ready();fireEvent.click(screen.getByRole("button",{name:"Feedback"}));await waitFor(()=>expect(screen.getByTestId("location")).toHaveTextContent("/sessions/fixture-feedback"));expect(mutations()).toEqual([{method:"POST",path:"/proposal-sessions",query:"",body:{kind:"swarm_operations",title:"Feedback for Owner fixture-owner",target:{type:"backlog_item",ref:"fix/fixture-owner",name:"Owner fixture-owner"}}}]);expect(complete).not.toHaveBeenCalled();});
 it("refuses feedback inline without alternate session or navigation",async()=>{replies.set("POST /proposal-sessions",()=>json({message:"Feedback owner refused"},422));const{complete}=mount();await ready();fireEvent.click(screen.getByRole("button",{name:"Feedback"}));expect(await screen.findByRole("alert")).toHaveTextContent("Feedback owner refused");expect(screen.getByTestId("location")).toHaveTextContent("/plan?keep=fixture");expect(mutations()).toHaveLength(1);expect(complete).not.toHaveBeenCalled();});
 it.each(["backlog_item","goal"] as const)("preserves the catalog's %s subject for one explicit fixture transition",async kind=>{entries=[entry("fixture-owner","fixture_action",{entity_kind:kind,entity_ref:kind==="goal"?"fixture-goal":"fix/fixture-owner",action:{id:"fixture_action",compact_label:"Apply fixture",expanded_label:"Apply declared fixture transition",enabled:true,transition_key:kind==="goal"?"fixture.goal.plan":"fixture.owner.action",effect:"state_change"}})];replies.set("POST /vrooli.swarm_manager.v1.api.TransitionService/StartTransition",()=>{entries=[];return json({executionId:"fixture-execution"});});const{complete}=mount();await ready();await waitFor(()=>expect(reads("/integrations")).toHaveLength(1));fireEvent.click(screen.getByRole("button",{name:"Apply fixture"}));await waitFor(()=>expect(complete).toHaveBeenCalledTimes(1));const starts=mutations().filter(c=>c.path.endsWith("/StartTransition"));expect(starts).toEqual([{method:"POST",path:"/vrooli.swarm_manager.v1.api.TransitionService/StartTransition",query:"",body:{transitionKey:kind==="goal"?"fixture.goal.plan":"fixture.owner.action",subjectRef:{subject:kind,value:kind==="goal"?"fixture-goal":"fix/fixture-owner"}}}]);});
 it.each(["backlog_item","goal"] as const)("retains %s transition refusal without alternate channel or refresh",async kind=>{entries=[entry("fixture-owner","fixture_action",{entity_kind:kind,entity_ref:kind==="goal"?"fixture-goal":"fix/fixture-owner",action:{id:"fixture_action",compact_label:"Apply fixture",expanded_label:"Apply declared fixture transition",enabled:true,transition_key:kind==="goal"?"fixture.goal.plan":"fixture.owner.action",effect:"state_change"}})];replies.set("POST /vrooli.swarm_manager.v1.api.TransitionService/StartTransition",()=>json({code:"permission_denied",message:"Fixture transition refused"},403));const{complete}=mount();await ready();fireEvent.click(screen.getByRole("button",{name:"Apply fixture"}));expect(await screen.findByRole("alert")).toHaveTextContent("Fixture transition refused");expect(complete).not.toHaveBeenCalled();expect(reads("/next-actions/feed")).toHaveLength(1);expect(mutations().filter(c=>!c.path.endsWith("/ListTransitions"))).toHaveLength(1);});
 it("performs goal planning only through its exact declared catalog subject",async()=>{entries=[entry("fixture-owner","plan_goal",{entity_kind:"goal",entity_ref:"fixture-goal",action:{id:"plan_goal",compact_label:"Plan fixture",expanded_label:"Plan fixture goal",enabled:true,transition_key:"fixture.goal.plan",effect:"agent_run"}})];replies.set("POST /vrooli.swarm_manager.v1.api.TransitionService/StartTransition",()=>{entries=[];return json({executionId:"fixture-goal-execution"});});const{complete}=mount();await ready();fireEvent.click(screen.getByRole("button",{name:"Plan fixture"}));await waitFor(()=>expect(complete).toHaveBeenCalledTimes(1));expect(mutations().filter(c=>c.path.endsWith("/StartTransition"))[0]!.body).toEqual({transitionKey:"fixture.goal.plan",subjectRef:{subject:"goal",value:"fixture-goal"}});});
 it("shows the named milestone's actual criteria and members before an exact review transition",async()=>{entries=[entry("fixture-owner","review",{entity_kind:"goal",entity_ref:"fixture-goal",action:{id:"review",compact_label:"Review fixture",expanded_label:"Review named milestone",enabled:true,target:"milestone_review:fixture-milestone",effect:"agent_run"}})];replies.set("POST /vrooli.swarm_manager.v1.api.TransitionService/StartTransition",()=>{entries=[];return json({executionId:"fixture-review-execution"});});const{complete}=mount();await ready();expect(await screen.findByText("Fixture emits exact evidence")).toBeVisible();expect(screen.getByText("Named fixture milestone")).toBeVisible();expect(screen.getByText("fix/fixture-owner")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Review fixture"}));await waitFor(()=>expect(complete).toHaveBeenCalledTimes(1));expect(mutations().filter(c=>c.path.endsWith("/StartTransition"))[0]!.body).toEqual({transitionKey:"milestone.review",subjectRef:{subject:"goal_milestone",value:"fixture-goal/fixture-milestone"}});});
 it("carries the exact milestone in the decision navigation instead of changing an owner",async()=>{entries=[entry("fixture-owner","review",{entity_kind:"goal",entity_ref:"fixture-goal",action:{id:"review",compact_label:"Review fixture",expanded_label:"Review named milestone",enabled:true,target:"milestone_review:fixture-milestone",effect:"agent_run"}})];mount();await screen.findByText("Fixture emits exact evidence");fireEvent.click(screen.getByTestId("decision-queue-title"));expect(screen.getByTestId("location")).toHaveTextContent("/goals/fixture-goal?drawer=decisions&decisionPosition=0&tab=milestones&milestone=fixture-milestone");expect(mutations().filter(c=>!c.path.endsWith("/ListTransitions"))).toEqual([]);});
 it("keeps an explicitly unavailable required integration disabled without a start attempt",async()=>{entries=[entry("fixture-owner","fixture_action",{action:{id:"fixture_action",compact_label:"Apply fixture",expanded_label:"Apply declared fixture transition",enabled:true,transition_key:"fixture.owner.action",effect:"state_change"}})];replies.set("GET /integrations",()=>json({integrations:[{id:"fixture.integration",availability:"unavailable",diagnostic:"Exact fixture producer unavailable"}]}));const{complete}=mount();expect(await screen.findByText("Transition unavailable: Exact fixture producer unavailable")).toBeVisible();const button=screen.getByRole("button",{name:"Apply fixture"});expect(button).toBeDisabled();fireEvent.click(button);expect(mutations().filter(c=>!c.path.endsWith("/ListTransitions"))).toEqual([]);expect(complete).not.toHaveBeenCalled();});
 it("refuses an undeclared transition locally without inventing a catalog entry or a start request",async()=>{entries=[entry("fixture-owner","fixture_action",{action:{id:"fixture_action",compact_label:"Unknown fixture",expanded_label:"Undeclared fixture transition",enabled:true,transition_key:"fixture.undeclared",effect:"state_change"}})];const{complete}=mount();await ready();fireEvent.click(screen.getByRole("button",{name:"Unknown fixture"}));expect(await screen.findByRole("alert")).toHaveTextContent("Transition fixture.undeclared is not declared.");expect(mutations().filter(c=>!c.path.endsWith("/ListTransitions"))).toEqual([]);expect(complete).not.toHaveBeenCalled();});

});
