// Real board context, drawers, action hook, stores, services and HTTP client.
// Every owner and response is disposable; previews never confirm a dispatch.
import { cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useLocation } from "react-router-dom";
import type { QueryClient } from "@tanstack/react-query";
import { createTestQueryClient, renderWithProviders } from "../../../test-utils";
import { useBacklogStore, backlogStoreInitialState } from "../../../stores/backlog-store";
import { useAgentActivitiesStore } from "../../../stores";
import { useSnoozeStore } from "../../../stores/snooze-store";
import { mapProtoBacklogItem, parseProtoResponse, backlogItemResponseSchema } from "../../../services/proto-contracts";
import { PlanBoardActions } from "./PlanBoardActions";
import { usePlanCardActions } from "./plan-card-actions-context";
import type { PlanCardData } from "../types";
import type { BacklogNextAction } from "../../../services/backlog";
const rawBase={kind:"fix",name:"fixture-owner",title:"Fixture owner",status:"ready",priority:2,tags:[],suggested_skills:[],created:"2026-10-05T00:00:00Z",updated:"2026-10-05T00:00:00Z"};
function item(raw=rawBase){return mapProtoBacklogItem(parseProtoResponse(backlogItemResponseSchema,{item:raw},"fixture owner").item!);}
const card:PlanCardData={id:"backlog-item/fix/fixture-owner",cardType:"item",action:"run",itemKind:"fix",itemName:"fixture-owner",title:"Fixture owner",status:"ready",priority:2,wave:0,milestone:"",effort:"",gate:null,outcome:"",finishedAt:"",executionId:"",unblocks:0};
const verdict:BacklogNextAction={id:"run",compactLabel:"Run",expandedLabel:"Run fixture",enabled:true,blockers:[]};
let calls:{method:string;path:string;query:string;body:unknown}[];let unexpected:string[];let replies:Map<string,()=>Response|Promise<Response>>;let owner:typeof rawBase;const clients:QueryClient[]=[];
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
function Consumer(){const a=usePlanCardActions()!;const location=useLocation();const callbacks=a.getCallbacks("fix","fixture-owner");return <div>
 <output data-testid="location">{location.pathname+location.search}</output><output data-testid="owner">{a.getBacklogItem("fix","fixture-owner")?.title}</output><output data-testid="action">{a.getNextAction("fix","fixture-owner")?.expandedLabel}</output><output data-testid="missing">{String(a.getCallbacks("fix","missing"))}/{String(a.getBacklogItem("fix","missing"))}/{String(a.getNextAction("fix","missing"))}</output>
 <button onClick={()=>callbacks?.onFollowUp()}>Inspect owner</button><button onClick={()=>callbacks?.onRun()}>Preview owner</button><button onClick={()=>callbacks?.onArchive()}>Archive fixture</button><button onClick={()=>callbacks?.onStatusChange("in_review")}>Mark fixture in review</button>
 <button onClick={()=>a.runTargets([])}>Empty run</button>{[1,3,4].map(n=><button key={n} onClick={()=>a.runTargets(Array.from({length:n},(_,i)=>({kind:"fix",name:`fixture-${i+1}`,title:`Fixture ${i+1}`})))}>Preview {n}</button>)}
 <button onClick={()=>a.openDecisions("fix/fixture-owner")}>Scoped decisions</button><button onClick={()=>a.openDecisions()}>All decisions</button>
 <button onClick={()=>a.snoozeCard(card,{label:"Fixture hour",ms:3600000})}>Snooze owner</button><button onClick={()=>a.snoozeCard({...card,itemKind:"",itemName:""},{label:"Fixture hour",ms:3600000})}>Snooze unowned</button>
 </div>;}
function mount(route="/plan?keep=fixture&decisionQuestion=old",nextActions:Record<string,BacklogNextAction>={"fix/fixture-owner":verdict}){const client=createTestQueryClient();clients.push(client);const refresh=vi.fn();const rendered=renderWithProviders(<PlanBoardActions nextActions={nextActions} onBoardRefresh={refresh}><Consumer/></PlanBoardActions>,{queryClient:client,initialEntries:[route]});return{client,refresh,...rendered};}
function mutations(){return calls.filter(c=>c.method!=="GET");}
function previews(){return calls.filter(c=>c.path.endsWith("/queue"));}
beforeEach(()=>{calls=[];unexpected=[];owner={...rawBase};useBacklogStore.setState({...backlogStoreInitialState,items:[item()],blockingMap:{},status:"success"});useAgentActivitiesStore.setState({activities:[]});useSnoozeStore.setState({entries:new Map()});window.localStorage.clear();
 replies=new Map([["GET /backlog/summary",()=>json({pending_questions:{items:[]}})],["GET /next-actions/feed",()=>json({entries:[]})],["GET /proposal-sessions",()=>json({sessions:[]})],["GET /execution/strategies",()=>json({items:[{id:"sliced",workflow_key:"fixture",display_name:"Fixture slices",description:"Fixture description",when_to_use:"Fixture only",cost_band:"fixture",cost_estimate:0}]})],["GET /execution-options",()=>json({options:[]})],["GET /backlog",()=>json({items:[owner],blocking:{}})]]);
 for(const name of ["fixture-owner","fixture-1","fixture-2","fixture-3","fixture-4"])replies.set(`POST /backlog/fix/${name}/queue`,()=>json({item:{...owner,name},dryRun:true,queued:false,blockingReasons:[],message:"Fixture preview"}));
 vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const request=new Request(input,init);const url=new URL(request.url);const path=url.pathname.replace(/^\/api\/v1/,"");const key=request.method+" "+path;const body=request.body?JSON.parse(await request.text()):undefined;calls.push({method:request.method,path,query:url.search,body});if(!replies.has(key)){unexpected.push(key);throw new Error("Unexpected fixture request "+key);}return replies.get(key)!();}));
});
afterEach(()=>{cleanup();clients.splice(0).forEach(c=>c.clear());expect(unexpected).toEqual([]);useBacklogStore.setState({...backlogStoreInitialState,blockingMap:{}});useAgentActivitiesStore.setState({activities:[]});useSnoozeStore.setState({entries:new Map()});window.localStorage.clear();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe("real board action ownership workflows",()=>{
 it("exposes only loaded owner callbacks and server verdict while missing owners remain absent",async()=>{mount();expect(screen.getByTestId("owner")).toHaveTextContent("Fixture owner");expect(screen.getByTestId("action")).toHaveTextContent("Run fixture");expect(screen.getByTestId("missing")).toHaveTextContent("undefined/undefined/undefined");await waitFor(()=>expect(calls.some(c=>c.path==="/backlog/summary")).toBe(true));expect(mutations()).toEqual([]);});
 it("navigates the exact owner's follow-up callback without sending a mutation",()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Inspect owner"}));expect(screen.getByTestId("location")).toHaveTextContent("/backlog/fix/fixture-owner");expect(mutations()).toEqual([]);});
 it("does nothing for an empty target list",()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Empty run"}));expect(screen.queryByTestId("run-sheet")).toBeNull();expect(screen.queryByText(/Run all ready/)).toBeNull();expect(previews()).toEqual([]);});
 it("opens the actual owner run sheet only as unconfirmed preflight and cancels",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Preview owner"}));const sheet=await screen.findByTestId("run-sheet");await waitFor(()=>expect(previews()).toHaveLength(1));expect(previews()[0]).toMatchObject({method:"POST",path:"/backlog/fix/fixture-owner/queue",body:{operation:"generator",mode:"yolo",confirm:false}});await screen.findByRole("radio",{name:/Fixture slices/});fireEvent.click(within(sheet).getByRole("button",{name:"Cancel"}));await waitFor(()=>expect(screen.queryByTestId("run-sheet")).toBeNull());expect(previews()).toHaveLength(1);expect(previews().every(c=>(c.body as {confirm?:boolean}).confirm===false)).toBe(true);});
 it.each([1,3])("previews %s explicit targets without the bulk confirmation and never confirms them",async n=>{mount();fireEvent.click(screen.getByRole("button",{name:`Preview ${n}`}));await screen.findByTestId("run-sheet");await waitFor(()=>expect(previews()).toHaveLength(n));expect(screen.queryByText(`Run all ready (${n} items)`)).toBeNull();expect(previews().map(c=>c.path)).toEqual(Array.from({length:n},(_,i)=>`/backlog/fix/fixture-${i+1}/queue`));expect(previews().every(c=>(c.body as {confirm?:boolean}).confirm===false)).toBe(true);});
 it("cancels a four-item confirmation before any queue preview or dispatch",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Preview 4"}));expect(await screen.findByText("Run all ready (4 items)")).toBeVisible();expect(previews()).toEqual([]);fireEvent.click(screen.getByRole("button",{name:"Cancel"}));await waitFor(()=>expect(screen.queryByText("Run all ready (4 items)")).toBeNull());expect(screen.queryByTestId("run-sheet")).toBeNull();expect(mutations()).toEqual([]);});
 it("confirmation transfers precisely four named targets to unconfirmed preflight",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Preview 4"}));await screen.findByText("Run all ready (4 items)");fireEvent.click(screen.getByRole("button",{name:"Proceed"}));await screen.findByTestId("run-sheet");await waitFor(()=>expect(previews()).toHaveLength(4));expect(screen.queryByText("Run all ready (4 items)")).toBeNull();expect(previews().map(c=>c.path)).toEqual([1,2,3,4].map(i=>`/backlog/fix/fixture-${i}/queue`));expect(previews().every(c=>(c.body as {confirm?:boolean}).confirm===false)).toBe(true);});
 it("scopes actual decision queries and clears a stale question while preserving unrelated URL state",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Scoped decisions"}));await screen.findByTestId("plan-decision-drawer");const params=new URLSearchParams(screen.getByTestId("location").textContent!.split("?")[1]);expect(params.get("drawer")).toBe("decisions");expect(params.get("decisionScope")).toBe("fix/fixture-owner");expect(params.get("decisionQuestion")).toBeNull();expect(params.get("keep")).toBe("fixture");await waitFor(()=>expect(calls.some(c=>c.path==="/proposal-sessions"&&new URLSearchParams(c.query).get("target_ref")==="fix/fixture-owner")).toBe(true));expect(mutations()).toEqual([]);});
 it("opens all decisions without retaining stale scope or question",async()=>{mount("/plan?keep=fixture&decisionScope=fix/old&decisionQuestion=old");fireEvent.click(screen.getByRole("button",{name:"All decisions"}));await screen.findByTestId("plan-decision-drawer");const params=new URLSearchParams(screen.getByTestId("location").textContent!.split("?")[1]);expect(params.get("drawer")).toBe("decisions");expect(params.get("decisionScope")).toBeNull();expect(params.get("decisionQuestion")).toBeNull();expect(params.get("keep")).toBe("fixture");await waitFor(()=>expect(calls.some(c=>c.path==="/proposal-sessions"&&c.query==="")).toBe(true));expect(mutations()).toEqual([]);});
 it("closes the real decision drawer and removes only its owned URL fields",async()=>{mount("/plan?drawer=decisions&decisionScope=fix/fixture-owner&decisionQuestion=old&keep=fixture");const drawer=await screen.findByTestId("plan-decision-drawer");fireEvent.click(within(drawer).getByRole("button",{name:"Close drawer"}));await waitFor(()=>expect(screen.queryByTestId("plan-decision-drawer")).toBeNull());expect(screen.getByTestId("location")).toHaveTextContent("/plan?keep=fixture");expect(mutations()).toEqual([]);});
 it("snoozes the exact owner locally and ignores a card without identity",()=>{const now=Date.now();mount();fireEvent.click(screen.getByRole("button",{name:"Snooze unowned"}));expect(useSnoozeStore.getState().entries.size).toBe(0);fireEvent.click(screen.getByRole("button",{name:"Snooze owner"}));const entries=useSnoozeStore.getState().entries;expect([...entries.keys()]).toEqual(["backlog:fix/fixture-owner"]);expect(entries.get("backlog:fix/fixture-owner")!.expiresAt).toBeGreaterThanOrEqual(now+3600000);expect(entries.get("backlog:fix/fixture-owner")!.expiresAt).toBeLessThanOrEqual(Date.now()+3600000);expect(mutations()).toEqual([]);});
 it("archives only the loaded fixture and refreshes canonical backlog after success",async()=>{replies.set("PATCH /backlog/fix/fixture-owner/archive-item",()=>json({}));mount();fireEvent.click(screen.getByRole("button",{name:"Archive fixture"}));await waitFor(()=>expect(calls.some(c=>c.path==="/backlog")).toBe(true));expect(mutations()).toEqual([{method:"PATCH",path:"/backlog/fix/fixture-owner/archive-item",query:"",body:{}}]);expect(useBacklogStore.getState().items[0]).toMatchObject({name:"fixture-owner",title:"Fixture owner"});});
 it("changes only the fixture status and refreshes its real store after owner success",async()=>{replies.set("PATCH /backlog/fix/fixture-owner",()=>{owner={...owner,status:"in_review"};return json({item:owner});});mount();fireEvent.click(screen.getByRole("button",{name:"Mark fixture in review"}));await waitFor(()=>expect(useBacklogStore.getState().items[0]!.status).toBe("in_review"));expect(mutations()).toEqual([{method:"PATCH",path:"/backlog/fix/fixture-owner",query:"",body:{status:"in_review"}}]);});
 it("retains canonical backlog and does not refresh or retry a refused status mutation",async()=>{replies.set("PATCH /backlog/fix/fixture-owner",()=>json({message:"Fixture status refused"},422));mount();fireEvent.click(screen.getByRole("button",{name:"Mark fixture in review"}));await waitFor(()=>expect(screen.getByText("Fixture status refused")).toBeVisible());expect(useBacklogStore.getState().items[0]!.status).toBe("ready");expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);expect(mutations()).toHaveLength(1);});
});
