// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      search: "layout.nav.search",
      findings: "layout.nav.findings",
      ops: "layout.nav.ops",
      settings: "layout.nav.settings",
      disputes: "layout.nav.disputes",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      statPlaceholderLabel: "pages.dashboard.statPlaceholderLabel",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
    search: {
      title: "pages.search.title",
      description: "pages.search.description",
    },
    findings: {
      title: "pages.findings.title",
      description: "pages.findings.description",
    },
    disputes: {
      title: "pages.disputes.title",
      description: "pages.disputes.description",
    },
    ops: {
      title: "pages.ops.title",
      description: "pages.ops.description",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  search: {
    placeholder: "search.placeholder",
    submit: "search.submit",
    modeLabel: "search.modeLabel",
    modeLive: "search.modeLive",
    modeLearnings: "search.modeLearnings",
    synthesizeLabel: "search.synthesizeLabel",
    loading: "search.loading",
    error: "search.error",
    empty: "search.empty",
    emptyLearnings: "search.emptyLearnings",
    method: "search.method",
    cached: "search.cached",
    fresh: "search.fresh",
    weak: "search.weak",
    resultScore: "search.resultScore",
    resultEngine: "search.resultEngine",
    openResult: "search.openResult",
    degraded: "search.degraded",
    synthesisHeading: "search.synthesisHeading",
    synthesisAbstained: "search.synthesisAbstained",
    synthesisCitations: "search.synthesisCitations",
  },
  history: {
    title: "history.title",
    empty: "history.empty",
    replay: "history.replay",
    clear: "history.clear",
    modeLive: "history.modeLive",
    modeLearnings: "history.modeLearnings",
  },
  ops: {
    dependenciesHeading: "ops.dependenciesHeading",
    dependenciesLoading: "ops.dependenciesLoading",
    dependenciesError: "ops.dependenciesError",
    dependencyConnected: "ops.dependencyConnected",
    dependencyDisconnected: "ops.dependencyDisconnected",
    dependencyLatency: "ops.dependencyLatency",
    noDependencies: "ops.noDependencies",
    lastQueryHeading: "ops.lastQueryHeading",
    lastQueryEmpty: "ops.lastQueryEmpty",
    lastQueryLabel: "ops.lastQueryLabel",
    cachedLabel: "ops.cachedLabel",
    cachedYes: "ops.cachedYes",
    cachedNo: "ops.cachedNo",
    degradedLabel: "ops.degradedLabel",
    degradedYes: "ops.degradedYes",
    degradedNo: "ops.degradedNo",
    degradedReasonLabel: "ops.degradedReasonLabel",
    resultCountLabel: "ops.resultCountLabel",
  },
  findings: {
    filterLabel: "findings.filterLabel",
    filterAll: "findings.filterAll",
    filterActive: "findings.filterActive",
    filterDisputed: "findings.filterDisputed",
    filterSuperseded: "findings.filterSuperseded",
    includeArchivedLabel: "findings.includeArchivedLabel",
    loading: "findings.loading",
    error: "findings.error",
    empty: "findings.empty",
    statusActive: "findings.statusActive",
    statusDisputed: "findings.statusDisputed",
    statusSuperseded: "findings.statusSuperseded",
    statusUnspecified: "findings.statusUnspecified",
    confidenceLabel: "findings.confidenceLabel",
    queryLabel: "findings.queryLabel",
    citationsLabel: "findings.citationsLabel",
    disputeNoteLabel: "findings.disputeNoteLabel",
    supersededByLabel: "findings.supersededByLabel",
    addHeading: "findings.addHeading",
    addClaimLabel: "findings.addClaimLabel",
    addClaimPlaceholder: "findings.addClaimPlaceholder",
    addConfidenceLabel: "findings.addConfidenceLabel",
    addQueryLabel: "findings.addQueryLabel",
    addQueryPlaceholder: "findings.addQueryPlaceholder",
    addCitationUrlPlaceholder: "findings.addCitationUrlPlaceholder",
    addCitationTitlePlaceholder: "findings.addCitationTitlePlaceholder",
    addCitationRow: "findings.addCitationRow",
    addCitationRemove: "findings.addCitationRemove",
    addSubmit: "findings.addSubmit",
    addError: "findings.addError",
    claimRequired: "findings.claimRequired",
    editAction: "findings.editAction",
    editSave: "findings.editSave",
    editCancel: "findings.editCancel",
    editClaimLabel: "findings.editClaimLabel",
    editConfidenceLabel: "findings.editConfidenceLabel",
    editError: "findings.editError",
    supersedeAction: "findings.supersedeAction",
    supersedeReplacementPlaceholder: "findings.supersedeReplacementPlaceholder",
    supersedeReasonPlaceholder: "findings.supersedeReasonPlaceholder",
    supersedeSubmit: "findings.supersedeSubmit",
    supersedeError: "findings.supersedeError",
    flagAction: "findings.flagAction",
    flagReasonPlaceholder: "findings.flagReasonPlaceholder",
    flagSubmit: "findings.flagSubmit",
    flagError: "findings.flagError",
    cancel: "findings.cancel",
    pruneHeading: "findings.pruneHeading",
    pruneDryRun: "findings.pruneDryRun",
    pruneApply: "findings.pruneApply",
    pruneError: "findings.pruneError",
    pruneDryRunResult: "findings.pruneDryRunResult",
    pruneDryRunResult_one: "findings.pruneDryRunResult_one",
    pruneDryRunResult_zero: "findings.pruneDryRunResult_zero",
    pruneApplied: "findings.pruneApplied",
    pruneApplied_one: "findings.pruneApplied_one",
    pruneApplied_zero: "findings.pruneApplied_zero",
    effectivenessHeading: "findings.effectivenessHeading",
    effectivenessHint: "findings.effectivenessHint",
    effectivenessLoading: "findings.effectivenessLoading",
    effectivenessError: "findings.effectivenessError",
    effectivenessEmpty: "findings.effectivenessEmpty",
    effectivenessSurfaced: "findings.effectivenessSurfaced",
    effectivenessUsed: "findings.effectivenessUsed",
    effectivenessNeverSurfaced: "findings.effectivenessNeverSurfaced",
    effectivenessLastSurfaced: "findings.effectivenessLastSurfaced",
    effectivenessScore: "findings.effectivenessScore",
  },
  disputes: {
    loading: "disputes.loading",
    error: "disputes.error",
    empty: "disputes.empty",
    noteLabel: "disputes.noteLabel",
    resolveAction: "disputes.resolveAction",
    resolutionLabel: "disputes.resolutionLabel",
    resolutionKeep: "disputes.resolutionKeep",
    resolutionSupersede: "disputes.resolutionSupersede",
    replacementPlaceholder: "disputes.replacementPlaceholder",
    reasonPlaceholder: "disputes.reasonPlaceholder",
    resolveSubmit: "disputes.resolveSubmit",
    cancel: "disputes.cancel",
    resolveError: "disputes.resolveError",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
