import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { memo, useState } from "react";
import { Check, Code, Copy, Eye, Loader2, Maximize2 } from "lucide-react";
import { useTranslation } from "react-i18next";
import { strings } from "../../../consts/strings";
import { useCodeCopy } from "../hooks/useCodeCopy";
import { useMermaidSvg } from "../hooks/useMermaidSvg";
/** Renders a mermaid diagram from source code with source/diagram toggle. */
export const MermaidDiagram = memo(function MermaidDiagram({ code, onOpenFullscreen }) {
    const { t } = useTranslation();
    const { svgHtml, error } = useMermaidSvg(code);
    const [showSource, setShowSource] = useState(false);
    const { copied, copyCode } = useCodeCopy(code);
    if (!code.trim()) {
        return (_jsxs("div", { className: "relative group rounded-lg overflow-hidden my-3", children: [_jsx("div", { className: "flex items-center justify-between px-4 py-2 bg-wc-surface-base border-b border-wc-default", children: _jsx("span", { className: "text-xs text-wc-text-muted font-mono", children: "mermaid" }) }), _jsx("div", { className: "bg-wc-surface p-8 flex items-center justify-center", children: _jsx("span", { className: "text-sm text-wc-text-faint italic", children: t(strings.mermaid.emptyDiagram) }) })] }));
    }
    return (_jsxs("div", { className: "relative group rounded-lg overflow-hidden my-3", children: [_jsxs("div", { className: "flex items-center justify-between px-4 py-2 bg-wc-surface-base border-b border-wc-default", children: [_jsx("span", { className: "text-xs text-wc-text-muted font-mono", children: "mermaid" }), _jsxs("div", { className: "flex items-center gap-2", children: [onOpenFullscreen && (_jsxs("button", { onClick: () => onOpenFullscreen(code), className: "flex items-center gap-1.5 text-xs text-wc-text-muted hover:text-wc-text-primary transition-colors", "aria-label": t(strings.mermaid.openFullscreen), title: t(strings.mermaid.openFullscreen), type: "button", children: [_jsx(Maximize2, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "hidden sm:inline", children: t(strings.mermaid.expand) })] })), _jsx("button", { onClick: () => setShowSource((prev) => !prev), className: "flex items-center gap-1.5 text-xs text-wc-text-muted hover:text-wc-text-primary transition-colors", "aria-label": showSource ? t(strings.mermaid.showDiagram) : t(strings.mermaid.showSource), type: "button", children: showSource ? (_jsxs(_Fragment, { children: [_jsx(Eye, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "hidden sm:inline", children: t(strings.mermaid.diagram) })] })) : (_jsxs(_Fragment, { children: [_jsx(Code, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "hidden sm:inline", children: t(strings.mermaid.source) })] })) }), _jsx("button", { onClick: copyCode, className: "flex items-center gap-1.5 text-xs text-wc-text-muted hover:text-wc-text-primary transition-colors", "aria-label": copied ? t(strings.mermaid.copied) : t(strings.mermaid.copy), type: "button", children: copied ? (_jsxs(_Fragment, { children: [_jsx(Check, { className: "h-3.5 w-3.5 text-green-400" }), _jsx("span", { className: "hidden text-green-400 sm:inline", children: t(strings.mermaid.copied) })] })) : (_jsxs(_Fragment, { children: [_jsx(Copy, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "hidden sm:inline", children: t(strings.mermaid.copy) })] })) })] })] }), _jsx("div", { className: "bg-wc-surface overflow-x-auto", children: showSource ? (_jsx("pre", { className: "p-4 text-sm text-wc-text-primary font-mono whitespace-pre overflow-x-auto", children: code })) : error ? (_jsxs("div", { children: [_jsx("div", { className: "px-4 py-2 bg-red-900/40 border-b border-red-700/50 text-xs text-red-300", children: error }), _jsx("pre", { className: "p-4 text-sm text-wc-text-primary font-mono whitespace-pre overflow-x-auto", children: code })] })) : svgHtml ? (_jsx("div", { className: "p-4 flex items-center justify-center [&>svg]:max-w-full", dangerouslySetInnerHTML: { __html: svgHtml } })) : (_jsx("div", { className: "p-8 flex items-center justify-center", children: _jsx(Loader2, { className: "h-6 w-6 text-wc-text-muted animate-spin" }) })) })] }));
});
