// Fictional presentation data. No host observations or operator identifiers.
export function world(now = Date.now(), step = 0) {
  const stamp = new Date(now).toISOString();
  const value = (n, units = '%') => ({ measured: n, provenance: 'authored presentation fixture', observedAt: stamp, cycleId: 'demo-cycle', units });
  const cpu = 74.3 + Math.sin(step * .8) * 1.2;
  const processes = [['scene-render',46.8,3210],['asset-worker',12.4,1840],['preview-server',6.2,760],['media-indexer',4.1,540],['sync-worker',2.8,320]].map(([name,cpuPercent,memoryMb],i) => ({pid:4100+i,name,cpuPercent,memoryMb,threads:8+i*2,connections:12+i*4,status:'running',cpuSeconds:120-i*18}));
  const current = {cycleId:'demo-cycle',cpuUsage:cpu,memoryUsage:61.2,tcpConnections:186,gpuUsage:63.8,timestamp:stamp,cpu:value(cpu),memory:value(61.2),gpu:value(63.8),disk:value(42.3),connections:value(186,'connections')};
  const samples = Array.from({length:121},(_,i) => {
    const t=i/120, c=42+20*t+8*Math.sin(i*.23)+24*Math.exp(-(((i-94)/9)**2));
    const ts=new Date(now-(120-i)*30000).toISOString();
    return {timestamp:ts,cycleId:`demo-${i}`,cpu:value(i===120?cpu:c),memory:value(55+6*t+2*Math.sin(i*.09)),gpu:value(35+30*t+13*Math.sin(i*.14)),connections:value(Math.round(132+54*t+14*Math.sin(i*.17)),'connections'),swap:value(3),cpuModeIowait:value(1.4+Math.abs(Math.sin(i*.13))*2),cpuModeSteal:value(.2),cpuStallSomeAvg10:value(2.2+Math.sin(i*.2)),cpuStallFullAvg10:value(.2)};
  });
  const detailed={timestamp:stamp,cpuDetails:{usage:cpu,usageState:value(cpu),topProcesses:processes,topCpuSecondsProcesses:processes,loadAverage:[3.4,2.8,2.2],modeBreakdown:{user:value(52.4),system:value(19.8),iowait:value(1.7),steal:value(.4)},perCoreUtilization:Object.fromEntries(Array.from({length:8},(_,i)=>[`core ${i+1}`,value(61+i*3.8)])),cpuPsiSomeAvg10:value(3.2),cpuPsiFullAvg10:value(.2),runQueueDepth:value(3,'tasks'),normalizedLoad1:value(.42,'load/core'),normalizedLoad5:value(.35,'load/core'),coreImbalanceIndex:value(12.8),quotaThrottling:{unsupportedReason:'No quota configured'},frequencyDerateRatio:value(.98,'ratio'),thermalThrottleEvidence:value(0),thermalTripPointCelsius:value(95,'°C')},memoryDetails:{usage:61.2,topProcesses:processes,swapUsage:{used:'257698038',total:'8589934592',percent:3},diskUsage:{used:'454193381376',total:'1073741824000',percent:42.3}},gpuDetails:{primaryModel:'Demo Compute GPU',driverVersion:'Demo',summary:{totalUtilizationPercent:63.8,averageUtilizationPercent:63.8,totalMemoryMb:24576,usedMemoryMb:11842,averageTemperatureC:61,deviceCount:1},devices:[{index:0,uuid:'demo-gpu-01',name:'Demo Compute GPU',utilizationPercent:63.8,memoryUtilizationPercent:48.2,memoryUsedMb:11842,memoryTotalMb:24576,temperatureC:61,fanSpeedPercent:42,powerDrawW:168,powerLimitW:300,smClockMhz:1845,memoryClockMhz:9501,processes:[{pid:4100,processName:'scene-render',memoryUsedMb:8640,smUtilizationPercent:48},{pid:4101,processName:'asset-worker',memoryUsedMb:3202,smUtilizationPercent:15.8}]}]},networkDetails:{tcpStates:{established:138,timeWait:24,closeWait:0,listen:24,total:186},networkStats:{bandwidthInMbps:84.2,bandwidthOutMbps:26.8,packetLoss:0,dnsSuccessRate:100,dnsLatencyMs:8.4}}};
  const graph={collectedAt:stamp,platform:'demo workstation',available:true,devices:[['demo-gpu-01','gpu','Demo Compute GPU'],['demo-storage-01','storage','Demo NVMe'],['demo-network-01','network','Demo Ethernet']].map(([id,cl,model])=>({id,class:cl,model,vendor:'Demo',readings:{},rungs:[{rung:'RUNG_IDENTITY',grade:'RUNG_GRADE_MEASURED',mechanism:'presentation fixture',observedAt:stamp}]}))};
  return {current,detailed,timeline:{windowSeconds:3600,sampleIntervalSeconds:30,samples},graph,processes:{timestamp:stamp,processHealth:{totalProcesses:148},resourceMatrix:processes},infrastructure:{timestamp:stamp,storageIo:{diskQueueDepth:1.2,ioWaitPercent:1.7,readMbPerSec:128.4,writeMbPerSec:42.8},databasePools:[],httpClientPools:[]}};
}
export function responseFor(path, body={}, now=Date.now(), step=0) {
 const w=world(now,step), method=path.split('/').pop();
 const services={metrics:{name:'MetricsService',methods:['GetCurrentMetrics','GetDetailedMetrics','GetMetricsTimeline','GetProcessMonitor','GetInfrastructureMonitor']},devicegraph:{name:'DeviceGraphService',methods:['GetDeviceGraph']},investigations:{name:'InvestigationsService',methods:['ListInvestigations','GetLatestInvestigation','GetTriggers','GetCooldownStatus']},scripts:{name:'ScriptsService',methods:['ListScripts']},reports:{name:'ReportsService',methods:['ListReports']},settings:{name:'SettingsService',methods:['GetMaintenanceState']}};
 const responses={GetCurrentMetrics:{metrics:w.current},GetDetailedMetrics:{metrics:w.detailed},GetMetricsTimeline:{timeline:w.timeline},GetDeviceGraph:{graph:w.graph},GetProcessMonitor:{data:w.processes},GetInfrastructureMonitor:{data:w.infrastructure},ListInvestigations:{investigations:[]},GetLatestInvestigation:{investigation:{}},ListScripts:{scripts:[]},GetTriggers:{},GetCooldownStatus:{},ListReports:{reports:[]},GetMaintenanceState:{maintenanceState:'active',success:true},SetMaintenanceState:{maintenanceState:'active',success:true}};
 for(const [namespace,service] of Object.entries(services))if(service.methods.includes(method)&&path===`/vrooli.system_monitor.v1.${namespace}.${service.name}/${method}`)return responses[method];
 if(path==='/api/v1/health'||path==='/health')return {status:'healthy',processor_active:true,maintenance_state:'active',readiness:true};
 if(path==='/api/v1/machines')return [];
 return undefined;
}
