import { useQuery } from "@tanstack/react-query";

import { listAllJournal, listPersonas } from "../api/persona";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { selectors } from "../consts/selectors";

export function JournalPage() {
  const personasQuery = useQuery({ queryKey: ["personas", "all"], queryFn: () => listPersonas(true) });
  const query = useQuery({ queryKey: ["journal", "all", personasQuery.data?.map((persona) => persona.id)], queryFn: () => listAllJournal(personasQuery.data ?? []), enabled: personasQuery.isSuccess });
  const entries = [...(query.data ?? [])].sort((a, b) => Number(b.at?.seconds ?? 0) - Number(a.at?.seconds ?? 0));
  return <section data-testid={selectors.pages.journal} aria-labelledby="journal-heading" className="flex flex-col gap-6"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-app-primary">Durable evidence</p><h2 id="journal-heading" className="mt-2 text-3xl font-semibold">Journal</h2><p className="mt-2 max-w-2xl text-app-muted-foreground">Append-only evidence of who did what, as which persona, on whose authority, and why a request was refused.</p></div><Card><CardHeader><CardTitle>Activity trail</CardTitle><CardDescription>{query.isPending ? "Loading evidence…" : `${entries.length} entry(ies) · corrections are new entries`}</CardDescription></CardHeader><CardContent>{query.isError ? <p role="alert" className="text-app-danger">The journal is unavailable. No incomplete audit view is presented as current.</p> : !entries.length && !query.isPending ? <p className="text-sm text-app-muted-foreground">No actions recorded yet.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><caption className="sr-only">Persona activity journal</caption><thead><tr className="border-b border-app-border text-xs uppercase tracking-wide text-app-muted-foreground"><th className="px-3 py-3">When</th><th className="px-3 py-3">Action</th><th className="px-3 py-3">Outcome</th><th className="px-3 py-3">Run</th><th className="px-3 py-3">Constraint</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-b border-app-border last:border-0"><td className="px-3 py-3 whitespace-nowrap">{entry.at ? new Date(Number(entry.at.seconds) * 1000).toLocaleString() : "—"}</td><td className="px-3 py-3"><span className="font-medium">{entry.verb}</span><span className="block text-xs text-app-muted-foreground">{entry.actor} · {entry.authorisingHuman || "no human recorded"}</span></td><td className="px-3 py-3"><span className={entry.outcome === "refused" ? "font-semibold text-app-danger" : "font-semibold text-app-success"}>{entry.outcome || "recorded"}</span></td><td className="px-3 py-3 font-mono text-xs">{entry.runId || "—"}</td><td className="px-3 py-3 text-app-muted-foreground">{entry.constraint || "—"}</td></tr>)}</tbody></table></div>}</CardContent></Card></section>;
}
