package cleanup

import (
	"vrooli-bridge/internal/module"

	cleanupconnect "github.com/vrooli/vrooli/packages/proto/gen/go/vrooli-bridge/v1/cleanup/cleanup_v1connect"
)

var Endpoints = []module.EndpointDescriptor{
	{ID: "cleanup_prepare", Path: cleanupconnect.CleanupServicePrepareCleanupProcedure, Method: "POST", Summary: "Prepare a protected cleanup target", Description: "Resolves the target transport and publishes only its sealing public key; it creates no cleanup operation.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)", "node_id": "string (required)", "target": "string (required)", "scope": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"target": "CleanupTarget"}}},
	{ID: "cleanup_provision_break_glass", Path: cleanupconnect.CleanupServiceProvisionBreakGlassProcedure, Method: "POST", Summary: "Provision target-bound break-glass material", Description: "Relays an opaque node-sealed passphrase to the paired helper. The operator must supply it; agents cannot select this operation.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)", "node_id": "string (required)", "target": "string (required)", "scope": "string", "operation_id": "string (required)", "sealed_passphrase": "bytes (required)", "operator_id": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}, Errors: []module.ErrorDesc{{Status: 412, Code: "failed_precondition", Description: "Target protection could not be provisioned"}}}, // #nosec G101 -- schema metadata names a request field; no credential value is embedded.
	{ID: "cleanup_reset_break_glass", Path: cleanupconnect.CleanupServiceResetBreakGlassProcedure, Method: "POST", Summary: "Retire stale target-bound break-glass material", Description: "Operator-confirmed recovery that removes only managed break-glass material and never grants cleanup authority; fresh protection must be provisioned afterward.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)", "node_id": "string (required)", "target": "string (required)", "scope": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}, Errors: []module.ErrorDesc{{Status: 412, Code: "failed_precondition", Description: "Target protection could not be retired"}}},
	{ID: "cleanup_start", Path: cleanupconnect.CleanupServiceStartCleanupProcedure, Method: "POST", Summary: "Start a Bridge-managed cleanup inventory", Description: "Creates one durable cleanup operation per machine and requests read-only inventory through the paired privileged helper.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)", "node_id": "string (required)", "target": "string (required)", "scope": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}, Errors: []module.ErrorDesc{{Status: 401, Code: "unauthenticated", Description: "Owner token required"}, {Status: 409, Code: "already_exists", Description: "A cleanup operation is already active for this machine"}, {Status: 503, Code: "unavailable", Description: "The paired node cannot be reached"}}},
	{ID: "cleanup_get", Path: cleanupconnect.CleanupServiceGetCleanupProcedure, Method: "POST", Summary: "Get a cleanup operation and events", Description: "Reads the durable cleanup operation, frozen plan, receipt, and event history.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation", "events": "array<CleanupEvent>"}}},
	{ID: "cleanup_plan", Path: cleanupconnect.CleanupServicePlanCleanupProcedure, Method: "POST", Summary: "Read a frozen cleanup plan", Description: "Returns the plan after the node has reported its read-only inventory.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}},
	{ID: "cleanup_confirm", Path: cleanupconnect.CleanupServiceConfirmCleanupProcedure, Method: "POST", Summary: "Confirm a frozen cleanup plan", Description: "Requires exact target and plan hash plus opaque node-bound authorization material. This is destructive and operator-confirmed.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)", "target": "string (required)", "plan_hash": "string (required)", "sealed_passphrase": "bytes (required)", "capability": "bytes (required)", "operator_id": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}, Errors: []module.ErrorDesc{{Status: 412, Code: "failed_precondition", Description: "Confirmation does not match the frozen plan"}}}, // #nosec G101 -- schema metadata names a request field; no credential value is embedded.
	{ID: "cleanup_apply", Path: cleanupconnect.CleanupServiceApplyCleanupProcedure, Method: "POST", Summary: "Resume a confirmed cleanup", Description: "Applies only the previously frozen plan; it never rediscovers artifacts. This is destructive, requires operator confirmation, and is never autonomous-agent eligible.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}},
	{ID: "cleanup_verify", Path: cleanupconnect.CleanupServiceVerifyCleanupProcedure, Method: "POST", Summary: "Verify cleanup result", Description: "Requests a read-only post-apply verification and records the signed result.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}},
	{ID: "cleanup_cancel", Path: cleanupconnect.CleanupServiceCancelCleanupProcedure, Method: "POST", Summary: "Cancel a cleanup operation", Description: "Cancels a non-terminal operation and releases the per-machine cleanup lease.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)", "reason": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"operation": "CleanupOperation"}}},
	{ID: "cleanup_report_event", Path: cleanupconnect.CleanupServiceReportCleanupEventProcedure, Method: "POST", Summary: "Ingest a node cleanup event", Description: "Node-facing mutual-authenticated event ingestion; omitted from the operator CLI.", Category: "cleanup", Request: &module.Schema{Type: "object", Properties: map[string]string{"event": "CleanupEvent"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"accepted": "bool"}}},
}
