# Run this file by typing: docker-compose -f docker-compose-docs.yml up -d
version: '3'

services:
  docs:
    image: squidfunk/mkdocs-material
    container_name: docs
    volumes:
      - ./packages/docs:/docs
    ports:
      - "4000:4000"
    command: serve --dev-addr=0.0.0.0:4000
