#!/bin/bash
# Airbyte Default Configuration

# Version
export AIRBYTE_VERSION="${AIRBYTE_VERSION:-0.50.0}"

# Ports (from port registry)
export AIRBYTE_WEBAPP_PORT="${AIRBYTE_WEBAPP_PORT:-8000}"
export AIRBYTE_SERVER_PORT="${AIRBYTE_SERVER_PORT:-8001}"
export AIRBYTE_TEMPORAL_PORT="${AIRBYTE_TEMPORAL_PORT:-8006}"

# Directories
export AIRBYTE_DATA_DIR="${AIRBYTE_DATA_DIR:-${RESOURCE_DIR}/data}"
export AIRBYTE_WORKSPACE_DIR="${AIRBYTE_WORKSPACE_DIR:-${AIRBYTE_DATA_DIR}/workspace}"

# Timeouts
export AIRBYTE_STARTUP_TIMEOUT="${AIRBYTE_STARTUP_TIMEOUT:-120}"
export AIRBYTE_HEALTH_CHECK_TIMEOUT="${AIRBYTE_HEALTH_CHECK_TIMEOUT:-5}"

# Resource limits
export AIRBYTE_MEMORY_LIMIT="${AIRBYTE_MEMORY_LIMIT:-4g}"
export AIRBYTE_CPU_LIMIT="${AIRBYTE_CPU_LIMIT:-2}"

# Debug mode
export DEBUG="${DEBUG:-false}"