//
//  ContentView.swift
//  VrooliScenario
//
//  Generated by scenario-to-ios
//

import SwiftUI
import WebKit

struct ContentView: View {
    @State private var isLoading = true
    @State private var error: Error?
    @State private var canGoBack = false
    @State private var canGoForward = false
    @State private var showSettings = false
    
    var body: some View {
        NavigationView {
            ZStack {
                WebView(
                    isLoading: $isLoading,
                    error: $error,
                    canGoBack: $canGoBack,
                    canGoForward: $canGoForward
                )
                
                if isLoading {
                    ProgressView("Loading...")
                        .progressViewStyle(CircularProgressViewStyle())
                        .scaleEffect(1.5)
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                        .background(Color.white.opacity(0.8))
                }
                
                if let error = error {
                    VStack(spacing: 20) {
                        Image(systemName: "wifi.exclamationmark")
                            .font(.system(size: 50))
                            .foregroundColor(.red)
                        
                        Text("Connection Error")
                            .font(.title2)
                            .fontWeight(.semibold)
                        
                        Text(error.localizedDescription)
                            .font(.body)
                            .foregroundColor(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal)
                        
                        Button(action: {
                            self.error = nil
                            self.isLoading = true
                        }) {
                            Label("Retry", systemImage: "arrow.clockwise")
                                .padding(.horizontal, 20)
                                .padding(.vertical, 10)
                                .background(Color.blue)
                                .foregroundColor(.white)
                                .cornerRadius(10)
                        }
                    }
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                    .background(Color.white)
                }
            }
            .navigationTitle("{{APP_NAME}}")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    if canGoBack {
                        Button(action: {
                            NotificationCenter.default.post(
                                name: NSNotification.Name("GoBack"),
                                object: nil
                            )
                        }) {
                            Image(systemName: "chevron.left")
                        }
                    }
                }
                
                ToolbarItem(placement: .navigationBarTrailing) {
                    HStack(spacing: 15) {
                        if canGoForward {
                            Button(action: {
                                NotificationCenter.default.post(
                                    name: NSNotification.Name("GoForward"),
                                    object: nil
                                )
                            }) {
                                Image(systemName: "chevron.right")
                            }
                        }
                        
                        Button(action: {
                            NotificationCenter.default.post(
                                name: NSNotification.Name("Reload"),
                                object: nil
                            )
                        }) {
                            Image(systemName: "arrow.clockwise")
                        }
                        
                        Button(action: {
                            showSettings = true
                        }) {
                            Image(systemName: "ellipsis.circle")
                        }
                    }
                }
            }
        }
        .sheet(isPresented: $showSettings) {
            SettingsView()
        }
    }
}

struct SettingsView: View {
    @Environment(\.presentationMode) var presentationMode
    @AppStorage("enableNotifications") var enableNotifications = true
    @AppStorage("enableLocation") var enableLocation = false
    @AppStorage("enableCamera") var enableCamera = false
    
    var body: some View {
        NavigationView {
            Form {
                Section(header: Text("Permissions")) {
                    Toggle("Push Notifications", isOn: $enableNotifications)
                    Toggle("Location Services", isOn: $enableLocation)
                    Toggle("Camera Access", isOn: $enableCamera)
                }
                
                Section(header: Text("About")) {
                    HStack {
                        Text("Version")
                        Spacer()
                        Text("{{APP_VERSION}}")
                            .foregroundColor(.secondary)
                    }
                    
                    HStack {
                        Text("Build")
                        Spacer()
                        Text("{{BUILD_NUMBER}}")
                            .foregroundColor(.secondary)
                    }
                }
                
                Section {
                    Button(action: {
                        // Clear cache
                        URLCache.shared.removeAllCachedResponses()
                        HTTPCookieStorage.shared.removeCookies(since: Date.distantPast)
                        
                        WKWebsiteDataStore.default().fetchDataRecords(
                            ofTypes: WKWebsiteDataStore.allWebsiteDataTypes()
                        ) { records in
                            records.forEach { record in
                                WKWebsiteDataStore.default().removeData(
                                    ofTypes: record.dataTypes,
                                    for: [record],
                                    completionHandler: {}
                                )
                            }
                        }
                    }) {
                        Text("Clear Cache")
                            .foregroundColor(.red)
                    }
                }
            }
            .navigationTitle("Settings")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        presentationMode.wrappedValue.dismiss()
                    }
                }
            }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}