//
//  VrooliScenarioApp.swift
//  VrooliScenario
//
//  Generated by scenario-to-ios
//

import SwiftUI

@main
struct VrooliScenarioApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
                .onAppear {
                    configureApp()
                }
        }
    }
    
    func configureApp() {
        // Configure app-wide settings
        UIApplication.shared.isIdleTimerDisabled = false
        
        // Set up network configuration for API calls
        configureNetworking()
        
        // Initialize JavaScript bridge
        JSBridge.shared.initialize()
    }
    
    func configureNetworking() {
        // Allow arbitrary loads for development
        // This should be configured properly for production
        let config = URLSessionConfiguration.default
        config.timeoutIntervalForRequest = 30
        config.timeoutIntervalForResource = 300
    }
}