#!/usr/bin/env bash
# kernel_config.sh - Configure kernel parameters required by resources
# This script sets up system-level kernel configurations needed by various
# Vrooli resources, particularly those requiring container/sandbox capabilities.
set -euo pipefail

LIB_SYSTEM_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# shellcheck disable=SC1091
source "$LIB_SYSTEM_DIR/../utils/var.sh"
# shellcheck disable=SC1091
source "${var_LOG_FILE}"
# shellcheck disable=SC1091
source "$var_LIB_UTILS_DIR/flow.sh"

# Path to persistent sysctl configuration
SYSCTL_CONF_DIR="/etc/sysctl.d"
SYSCTL_VROOLI_CONF="${SYSCTL_CONF_DIR}/99-vrooli.conf"

#######################################
# Check if a kernel parameter has a specific value
# Arguments:
#   $1 - Parameter name (e.g., kernel.apparmor_restrict_unprivileged_userns)
#   $2 - Expected value (e.g., 0)
# Returns:
#   0 if parameter has expected value, 1 otherwise
#######################################
kernel_config::check_parameter() {
    local param="$1"
    local expected="$2"
    local current
    
    current=$(sysctl -n "$param" 2>/dev/null || echo "NOT_SET")
    
    if [[ "$current" == "$expected" ]]; then
        return 0
    else
        return 1
    fi
}

#######################################
# Apply kernel configuration for Judge0 resource
# This enables unprivileged user namespaces required by isolate sandbox
#######################################
kernel_config::configure_judge0() {
    local param="kernel.apparmor_restrict_unprivileged_userns"
    local required_value="0"
    
    log::info "🔧 Configuring kernel parameters for Judge0..."
    
    # Check if already configured
    if kernel_config::check_parameter "$param" "$required_value"; then
        log::success "✅ Judge0 kernel parameters already configured"
        return 0
    fi
    
    log::warning "⚠️  Judge0 requires unprivileged user namespaces to be enabled"
    log::info "This allows the isolate sandbox to create isolated environments for code execution"
    log::info "Setting: $param=$required_value"
    
    # Apply immediately (requires sudo)
    if flow::can_run_sudo "kernel parameter configuration"; then
        if sudo sysctl -w "$param=$required_value" >/dev/null 2>&1; then
            log::success "✅ Applied kernel parameter for current session"
        else
            log::error "Failed to apply kernel parameter"
            return 1
        fi
        
        # Make persistent
        if kernel_config::make_persistent "$param" "$required_value" "Judge0 isolate sandbox"; then
            log::success "✅ Configuration saved for persistence across reboots"
        else
            log::warning "Could not save persistent configuration - manual intervention required"
        fi
    else
        log::warning "Sudo access required to configure kernel parameters for Judge0"
        log::info "Judge0 resource may not work properly without this configuration"
        log::info "Please run manually: sudo sysctl -w $param=$required_value"
        log::info "To make permanent, add to /etc/sysctl.conf: $param = $required_value"
        return 0  # Continue setup instead of failing
    fi
    
    return 0
}

#######################################
# Make a kernel parameter persistent across reboots
# Arguments:
#   $1 - Parameter name
#   $2 - Value
#   $3 - Comment describing why this is needed
# Returns:
#   0 on success, 1 on failure
#######################################
kernel_config::make_persistent() {
    local param="$1"
    local value="$2"
    local comment="$3"
    
    # Create sysctl.d directory if it doesn't exist
    if [[ ! -d "$SYSCTL_CONF_DIR" ]]; then
        if ! sudo mkdir -p "$SYSCTL_CONF_DIR"; then
            log::error "Failed to create $SYSCTL_CONF_DIR"
            return 1
        fi
    fi
    
    # Create or update Vrooli sysctl configuration
    local temp_file
    temp_file=$(mktemp)
    
    # If config file exists, preserve existing entries
    if [[ -f "$SYSCTL_VROOLI_CONF" ]]; then
        # Remove any existing entry for this parameter
        sudo grep -v "^$param" "$SYSCTL_VROOLI_CONF" > "$temp_file" || true
    else
        # Create header for new file
        cat > "$temp_file" << EOF
# Vrooli Resource Kernel Configuration
# This file contains kernel parameters required by various Vrooli resources
# Generated by: scripts/lib/system/kernel_config.sh
# 
# To apply these settings immediately: sudo sysctl -p $SYSCTL_VROOLI_CONF
# These settings are applied automatically on system boot

EOF
    fi
    
    # Add the new parameter with comment
    {
        echo ""
        echo "# $comment"
        echo "$param = $value"
    } >> "$temp_file"
    
    # Move to final location
    if sudo mv "$temp_file" "$SYSCTL_VROOLI_CONF"; then
        # Set proper permissions
        sudo chmod 644 "$SYSCTL_VROOLI_CONF"
        return 0
    else
        rm -f "$temp_file"
        return 1
    fi
}

#######################################
# Configure kernel parameters based on enabled resources
# This is the main entry point called during setup
#######################################
kernel_config::configure_for_resources() {
    log::header "🔧 Configuring kernel parameters for resources"
    
    local configs_applied=false
    local judge0_enabled=false
    
    # Check if Judge0 is enabled in resources
    if [[ -f "$var_SERVICE_JSON_FILE" ]]; then
        # Use jq if available, otherwise grep
        if command -v jq >/dev/null 2>&1; then
            judge0_enabled=$(jq -r '.judge0.enabled // false' "$var_SERVICE_JSON_FILE" 2>/dev/null || echo "false")
        else
            # Fallback: simple grep check
            if grep -q '"judge0".*"enabled".*true' "$var_SERVICE_JSON_FILE" 2>/dev/null; then
                judge0_enabled="true"
            fi
        fi
    fi
    
    # Apply Judge0 configuration if enabled
    if [[ "$judge0_enabled" == "true" ]] || [[ "${RESOURCES:-}" == *"judge0"* ]]; then
        if kernel_config::configure_judge0; then
            configs_applied=true
        else
            log::warning "Judge0 kernel configuration failed - service may not work properly"
        fi
    fi
    
    # Future: Add other resource-specific kernel configs here
    # Example: kernel_config::configure_docker_swarm
    
    if [[ "$configs_applied" == "true" ]]; then
        log::success "✅ Kernel parameters configured for resources"
        log::info "Configuration file: $SYSCTL_VROOLI_CONF"
    else
        log::info "No kernel parameter changes required for current resources"
    fi
    
    return 0
}

#######################################
# Remove Vrooli kernel configurations
# Used during cleanup or uninstall
#######################################
kernel_config::cleanup() {
    log::header "🧹 Cleaning up Vrooli kernel configurations"
    
    if [[ -f "$SYSCTL_VROOLI_CONF" ]]; then
        if flow::can_run_sudo "kernel configuration cleanup"; then
            if sudo rm -f "$SYSCTL_VROOLI_CONF"; then
                log::success "✅ Removed Vrooli kernel configuration file"
                log::info "Note: Current kernel parameters remain active until reboot"
                log::info "To reset immediately, manually run: sudo sysctl -w <param>=<original_value>"
            else
                log::error "Failed to remove configuration file"
                return 1
            fi
        else
            log::warning "Sudo required to remove kernel configuration"
            log::info "Manual cleanup: sudo rm -f $SYSCTL_VROOLI_CONF"
        fi
    else
        log::info "No Vrooli kernel configuration found to clean up"
    fi
    
    return 0
}

# If script is run directly, configure based on arguments
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-configure}" in
        configure)
            kernel_config::configure_for_resources
            ;;
        cleanup)
            kernel_config::cleanup
            ;;
        *)
            log::error "Unknown action: $1"
            log::info "Usage: $0 [configure|cleanup]"
            exit 1
            ;;
    esac
fi