#!/usr/bin/env bash
# PoR coherence test — the dogfood lint for the agent-system canon.
#
# Asserts that:
#   1. The canonical layer-mantra sentence appears exactly once under
#      docs/agent-system/ (in LAYERS.md) and zero times under
#      scenarios/prompt-manager/store/skills/.
#   2. The two skills fully absorbed in Phase 1 (skill-principles,
#      team-shared-docs-design) no longer exist as skill directories.
#   3. The docs/meta-optimization/ folder is the friction-report canon hub
#      (revived 2026-05-03 with narrow scope: friction-report taxonomy + PoR
#      only; the old broad meta-opt content remains absorbed into
#      docs/agent-system/). The folder must contain README.md, manifest.json,
#      operating/OPERATING_MODEL.md, taxonomies/friction-report/README.md, and
#      taxonomies/friction-report/taxonomy.json.
#   4. No active SKILL.md or live team/agent config references the retired
#      skill IDs. (Historical logs in *.jsonl and member last-handoff.md are
#      exempt; they are immutable runtime traces.)
#
# Run from repo root:
#   bash scenarios/prompt-manager/test/agent_system_canon_test.sh

set -uo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

fail=0
pass=0

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }

check() {
    local label="$1"; shift
    if "$@"; then
        green "PASS  $label"
        pass=$((pass+1))
    else
        red   "FAIL  $label"
        fail=$((fail+1))
    fi
}

# Use ripgrep when available (faster, respects .gitignore by default), fall
# back to grep -r otherwise.
if command -v rg >/dev/null 2>&1; then
    grep_files() { rg -l "$@" 2>/dev/null; }
else
    grep_files() { grep -rl "$@" 2>/dev/null; }
fi

# ---------------------------------------------------------------------------
# 1. Layer mantra — exactly one PoR home, zero skill residue
# ---------------------------------------------------------------------------

mantra_in_por() {
    local matches
    matches=$(grep_files "Truth lives in Plan of Record" docs/agent-system/ | wc -l)
    [[ "$matches" -eq 1 ]]
}

mantra_in_skills() {
    local matches
    matches=$(grep_files "Truth lives in Plan of Record" scenarios/prompt-manager/store/skills/ | wc -l)
    [[ "$matches" -eq 0 ]]
}

check "Layer mantra appears in exactly one file under docs/agent-system/" mantra_in_por
check "Layer mantra appears nowhere under scenarios/prompt-manager/store/skills/" mantra_in_skills

# ---------------------------------------------------------------------------
# 2. Absorbed skills are deleted
# ---------------------------------------------------------------------------

skill_principles_gone() {
    [[ ! -d scenarios/prompt-manager/store/skills/packs/core/skill-principles ]]
}

team_shared_docs_design_gone() {
    [[ ! -d scenarios/prompt-manager/store/skills/packs/core/team-shared-docs-design ]]
}

check "Skill 'skill-principles' is deleted" skill_principles_gone
check "Skill 'team-shared-docs-design' is deleted" team_shared_docs_design_gone

# ---------------------------------------------------------------------------
# 3. docs/meta-optimization/ is the friction-report canon hub
# ---------------------------------------------------------------------------
#
# Revived 2026-05-03 with narrow scope: friction-report canon only. The old
# broad meta-opt content (PRIMITIVES, LAYERS, etc.) remains absorbed into
# docs/agent-system/. The folder must hold the friction-report taxonomy +
# PoR + README; nothing else of the previous content should creep back.

meta_opt_friction_canon_present() {
    [[ -d docs/meta-optimization ]] \
      && [[ -f docs/meta-optimization/README.md ]] \
      && [[ -f docs/meta-optimization/manifest.json ]] \
      && [[ -f docs/meta-optimization/operating/OPERATING_MODEL.md ]] \
      && [[ -f docs/meta-optimization/taxonomies/friction-report/README.md ]] \
      && [[ -f docs/meta-optimization/taxonomies/friction-report/taxonomy.json ]]
}

check "Folder docs/meta-optimization/ holds friction-report canon" meta_opt_friction_canon_present

# ---------------------------------------------------------------------------
# 4. No active references to retired entities
# ---------------------------------------------------------------------------

# Active surfaces (SKILL.md files, team/agent JSON configs, shared canon docs).
# We exclude:
#   - *.jsonl  (immutable historical logs)
#   - last-handoff.md (transient member state)
#   - docs/agent-system/_outline.md and README.md (migration manifest /
#     origin note legitimately reference what was retired)
#   - store/indexes/*.json (auto-generated by `prompt-manager skill sync`)
#   - docs/plans/  (plan files are historical artifacts)
#   - shared/*_AUDIT.md, *_SCAN.md, *_LESSONS.md, *_QUEUE.md (rolling-snapshot
#     working registers; refreshed each heartbeat by their owning member)
ACTIVE_GLOBS=(
    'scenarios/prompt-manager/store/skills/packs/core/*/SKILL.md'
    'scenarios/prompt-manager/store/skills/packs/core/*/skill.json'
    'scenarios/prompt-manager/store/teams/*/team.json'
    'scenarios/prompt-manager/store/teams/*/roles.json'
    'scenarios/prompt-manager/store/teams/*/shared/TEAM.md'
    'scenarios/prompt-manager/store/teams/*/members/*/RESPONSIBILITIES.md'
    'scenarios/prompt-manager/store/teams/*/members/*/HEARTBEAT.md'
    'scenarios/prompt-manager/store/agents/*/agent.json'
    'scenarios/prompt-manager/store/agents/*/AGENTS.md'
    'scenarios/prompt-manager/store/agents/*/SOUL.md'
    'scenarios/prompt-manager/store/agents/*/TOOLS.md'
)

active_files() {
    # shellcheck disable=SC2068
    for pat in ${ACTIVE_GLOBS[@]}; do
        for f in $pat; do
            [[ -f "$f" ]] && echo "$f"
        done
    done
}

no_active_refs_to() {
    local pattern="$1"
    local found
    # shellcheck disable=SC2046
    found=$(grep -l -- "$pattern" $(active_files) 2>/dev/null | wc -l)
    [[ "$found" -eq 0 ]]
}

check "No active reference to skill-principles" no_active_refs_to "skill-principles"
check "No active reference to team-shared-docs-design" no_active_refs_to "team-shared-docs-design"

# ---------------------------------------------------------------------------
# 5. Technique-registry pairing: doc + paired skill discipline
# ---------------------------------------------------------------------------
#
# Two directions, and they are deliberately not symmetric:
#
#   1. Every <slug>.md (excluding README.md) under a registered technique-registry
#      directory MUST have a matching SKILL.md at
#      scenarios/prompt-manager/store/skills/packs/core/<slug>/SKILL.md.
#   2. Every skill *in the registry's live rotation* MUST have a matching PoR doc
#      in the registry directory.
#
# Direction 2 keys on the rotation, not on the tag alone. Until 2026-08-17 it
# keyed on the tag, which put it in disagreement with the contract it was
# enforcing: the rotation is defined by
# quality-auditor's taskParameters.rotationQuery as
#
#     skill list --mode steer --tag <tag> --without-programmatic-home
#
# so a skill that is provider-owned (programmaticHome set) or not a steer skill
# is not a rotated lens. Demanding strategic canon for those produced exactly the
# failure the registry README names — "a doc with no skill is a stale shrine" —
# one doc per provider-owned skill that no auditor rotates through. It also read
# as a pass for months while failing, because the check ran as an `external`
# sensor that reported "not collected".
#
# The asymmetry is the point. A lens that *graduates* to a provider keeps both
# its tag and its doc (screaming-architecture-audit is the worked case): the doc
# holds why the lens applied and what the contrarian challenged, which stays
# worth reading after detection mechanizes. Direction 1 keeps that doc honest by
# requiring its skill to still exist. Direction 2 stops requiring a doc the
# moment the lens leaves the rotation.
#
# Future registries plug in by appending one entry to TECHNIQUE_REGISTRIES.

TECHNIQUE_REGISTRIES=(
    "docs/scenario-qa/methods/investigation|investigation-technique"
    "docs/scenario-qa/methods/audit|audit-technique"
)

# For each registry, derive the doc slug set and the skill slug set, then
# assert symmetric difference is empty.
SKILL_PACK_DIR="scenarios/prompt-manager/store/skills/packs/core"

docs_in_registry() {
    local dir="$1"
    if [[ ! -d "$dir" ]]; then return 0; fi
    find "$dir" -maxdepth 1 -type f -name '*.md' \
        ! -name 'README.md' \
        -printf '%f\n' 2>/dev/null \
        | sed 's/\.md$//' \
        | sort -u
}

skills_with_tag() {
    local tag="$1"
    if [[ ! -d "$SKILL_PACK_DIR" ]]; then return 0; fi
    for sj in "$SKILL_PACK_DIR"/*/skill.json; do
        [[ -f "$sj" ]] || continue
        grep -q "\"$tag\"" "$sj" 2>/dev/null || continue
        basename "$(dirname "$sj")"
    done | sort -u
}

# skills_in_rotation mirrors quality-auditor's taskParameters.rotationQuery:
# a rotated lens is a steer skill carrying the registry tag whose detection has
# NOT graduated to a programmatic engine. Skills auto-prune from the rotation the
# moment a programmaticHome is recorded, and this check prunes with them.
skills_in_rotation() {
    local tag="$1"
    if [[ ! -d "$SKILL_PACK_DIR" ]]; then return 0; fi
    for sj in "$SKILL_PACK_DIR"/*/skill.json; do
        [[ -f "$sj" ]] || continue
        grep -q "\"$tag\"" "$sj" 2>/dev/null || continue
        # steer mode: the rotation is steer-only. "steer" appears in skill.json
        # only inside the modes array, so a bare literal match is sufficient and
        # avoids depending on a JSON parser in this harness.
        grep -q '"steer"' "$sj" 2>/dev/null || continue
        # graduated: a non-empty programmaticHome means a provider owns
        # detection, so the skill is not a rotated judgment lens.
        if grep -qE '"programmaticHome"[[:space:]]*:[[:space:]]*"[^"]' "$sj" 2>/dev/null; then
            continue
        fi
        basename "$(dirname "$sj")"
    done | sort -u
}

registry_pairing_clean() {
    local entry="$1"
    local dir="${entry%|*}"
    local tag="${entry#*|}"
    local docs skills rotated rc=0
    docs=$(docs_in_registry "$dir")
    skills=$(skills_with_tag "$tag")
    rotated=$(skills_in_rotation "$tag")
    # Direction 1: a doc must have a paired skill, graduated or not.
    while IFS= read -r slug; do
        [[ -z "$slug" ]] && continue
        if ! grep -qx "$slug" <<<"$skills"; then
            red "    doc '$dir/$slug.md' has no paired skill at $SKILL_PACK_DIR/$slug/SKILL.md"
            rc=1
        fi
    done <<<"$docs"
    # Direction 2: a *rotated* lens must have a paired PoR doc. A provider-owned
    # or non-steer skill is not rotated and needs none.
    while IFS= read -r slug; do
        [[ -z "$slug" ]] && continue
        if ! grep -qx "$slug" <<<"$docs"; then
            red "    rotated lens '$slug' (steer + '$tag', no programmaticHome) has no paired PoR doc in $dir/"
            rc=1
        fi
    done <<<"$rotated"
    # Report every violation, not just the first. The earlier version returned on
    # the first mismatch, so fixing one entry revealed the next and the true
    # count was never visible in one run.
    return "$rc"
}

for entry in "${TECHNIQUE_REGISTRIES[@]}"; do
    dir="${entry%|*}"
    tag="${entry#*|}"
    check "Technique pairing clean for $dir (tag: $tag)" registry_pairing_clean "$entry"
done

# ---------------------------------------------------------------------------
# Framework-health sensor map: the doc table and the Go registry are one list
#
# Every target's name lives in two homes — the FRAMEWORK_HEALTH.md sensor map
# and a Go literal in cli/graph/audit.go — which is the double residency
# LAYERS.md forbids. Generating one from the other is not practical while the
# Observed column carries hand-written analysis, so this assertion holds them
# equal instead: a row added to the doc without a collector is documentation of
# a sensor that does not run, and a collector without a row is a reading no
# canon accounts for.
# ---------------------------------------------------------------------------

AUDIT_GO="scenarios/prompt-manager/cli/graph/audit.go"
FRAMEWORK_HEALTH="docs/agent-system/FRAMEWORK_HEALTH.md"

audit_go_targets() {
    grep -oE 'Target:[[:space:]]+"[^"]+"' "$AUDIT_GO" \
        | sed -E 's/.*"([^"]+)"/\1/' | sort -u
}

framework_health_targets() {
    # Only the sensor map table; FRAMEWORK_HEALTH.md holds other tables whose
    # first column is not a target name.
    awk '/^## Sensor map/{inmap=1; next} inmap && /^## /{exit} inmap && /^\|/{print}' "$FRAMEWORK_HEALTH" \
        | grep -v '^| *Target *|' \
        | grep -v '^|[ -]*|' \
        | sed -E 's/^\|[[:space:]]*//; s/[[:space:]]*\|.*$//' \
        | sed -E 's/^`//; s/`$//' \
        | sed -E 's/[[:space:]]+$//' \
        | grep -v '^$' | sort -u
}

sensor_map_in_sync() {
    local in_go in_doc rc=0
    in_go=$(audit_go_targets)
    in_doc=$(framework_health_targets)
    if [[ -z "$in_go" || -z "$in_doc" ]]; then
        red "    could not extract targets (go=$(wc -l <<<"$in_go") doc=$(wc -l <<<"$in_doc")); check the parsers"
        return 1
    fi
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if ! grep -qxF "$name" <<<"$in_doc"; then
            red "    audit.go collects '$name' with no row in $FRAMEWORK_HEALTH"
            rc=1
        fi
    done <<<"$in_go"
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if ! grep -qxF "$name" <<<"$in_go"; then
            red "    $FRAMEWORK_HEALTH declares '$name' with no collector in audit.go"
            rc=1
        fi
    done <<<"$in_doc"
    return "$rc"
}

check "Framework-health sensor map matches the audit collectors" sensor_map_in_sync

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo
echo "Passed: $pass"
echo "Failed: $fail"

[[ "$fail" -eq 0 ]]
