package ontology

import (
	"tech-tree-designer/internal/module"

	ontologyconnect "github.com/vrooli/vrooli/packages/proto/gen/go/tech-tree-designer/v1/ontology/ontology_v1connect"
)

var Endpoints = []module.EndpointDescriptor{
	{
		ID:          "ontology-capabilities-list",
		Path:        ontologyconnect.OntologyServiceListCapabilitiesProcedure,
		Method:      "POST",
		Summary:     "List capability ontology nodes",
		Description: "Lists top-down capability nodes, optionally filtered by parent, descendants, and kind.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "ListCapabilitiesRequest"},
		Response:    &module.Schema{Type: "ListCapabilitiesResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology capabilities"},
	},
	{
		ID:          "ontology-capability-get",
		Path:        ontologyconnect.OntologyServiceGetCapabilityProcedure,
		Method:      "POST",
		Summary:     "Get a capability",
		Description: "Returns one capability by id or slug.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "GetCapabilityRequest"},
		Response:    &module.Schema{Type: "Capability"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology capability", Args: []string{"<slug>"}},
	},
	{
		ID:          "ontology-capability-upsert",
		Path:        ontologyconnect.OntologyServiceUpsertCapabilityProcedure,
		Method:      "POST",
		Summary:     "Create or update a capability",
		Description: "Upserts a capability node in the top-down ontology tree.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "UpsertCapabilityRequest"},
		Response:    &module.Schema{Type: "Capability"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology capability-upsert"},
	},
	{
		ID:          "ontology-capability-delete",
		Path:        ontologyconnect.OntologyServiceDeleteCapabilityProcedure,
		Method:      "POST",
		Summary:     "Delete a capability",
		Description: "Deletes one capability node by id or slug.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "DeleteCapabilityRequest"},
		Response:    &module.Schema{Type: "DeleteCapabilityResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology capability-rm", Args: []string{"<slug>"}},
	},
	{
		ID:          "ontology-edge-upsert",
		Path:        ontologyconnect.OntologyServiceUpsertCapabilityEdgeProcedure,
		Method:      "POST",
		Summary:     "Create a capability edge",
		Description: "Creates a decomposition, progression, or requirement edge between capabilities.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "UpsertCapabilityEdgeRequest"},
		Response:    &module.Schema{Type: "CapabilityEdge"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology edge-add", Args: []string{"<from>", "<to>"}},
	},
	{
		ID:          "ontology-edge-delete",
		Path:        ontologyconnect.OntologyServiceDeleteCapabilityEdgeProcedure,
		Method:      "POST",
		Summary:     "Delete a capability edge",
		Description: "Deletes one capability edge.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "DeleteCapabilityEdgeRequest"},
		Response:    &module.Schema{Type: "DeleteCapabilityEdgeResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology edge-rm", Args: []string{"<from>", "<to>"}},
	},
	{
		ID:          "ontology-import-topology",
		Path:        ontologyconnect.OntologyServiceImportTopologyProcedure,
		Method:      "POST",
		Summary:     "Import ontology topology JSON",
		Description: "Idempotently imports the macro topology seed shape into capability nodes and progression edges.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "ImportTopologyRequest"},
		Response:    &module.Schema{Type: "ImportTopologyResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology import", Args: []string{"--from-file", "<path>"}},
	},
	{
		ID:          "ontology-fulfillment-link",
		Path:        ontologyconnect.OntologyServiceLinkFulfillmentProcedure,
		Method:      "POST",
		Summary:     "Link a scenario fulfillment",
		Description: "Links a capability to a live or planned scenario slug.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "LinkFulfillmentRequest"},
		Response:    &module.Schema{Type: "Fulfillment"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology fulfill", Args: []string{"<capability>", "<scenario>"}},
	},
	{
		ID:          "ontology-fulfillment-unlink",
		Path:        ontologyconnect.OntologyServiceUnlinkFulfillmentProcedure,
		Method:      "POST",
		Summary:     "Unlink a scenario fulfillment",
		Description: "Removes a capability-to-scenario fulfillment link.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "UnlinkFulfillmentRequest"},
		Response:    &module.Schema{Type: "UnlinkFulfillmentResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology unfulfill", Args: []string{"<capability>", "<scenario>"}},
	},
	{
		ID:          "ontology-fulfillments-list",
		Path:        ontologyconnect.OntologyServiceListFulfillmentsProcedure,
		Method:      "POST",
		Summary:     "List fulfillment links",
		Description: "Lists capability-to-scenario fulfillment links.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "ListFulfillmentsRequest"},
		Response:    &module.Schema{Type: "ListFulfillmentsResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology fulfillments"},
	},
	{
		ID:          "ontology-coverage",
		Path:        ontologyconnect.OntologyServiceGetCoverageProcedure,
		Method:      "POST",
		Summary:     "Get coverage analytics",
		Description: "Computes built, in-flight, gap, and unmapped coverage across ontology and implementation layers.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "GetCoverageRequest"},
		Response:    &module.Schema{Type: "CoverageSummary"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology coverage"},
	},
	{
		ID:          "ontology-focus",
		Path:        ontologyconnect.OntologyServiceListFocusProcedure,
		Method:      "POST",
		Summary:     "List focus candidates",
		Description: "Ranks ontology gaps and unmapped scenarios for portfolio prioritization.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "ListFocusRequest"},
		Response:    &module.Schema{Type: "ListFocusResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology focus"},
	},
	{
		ID:          "ontology-capability-scenarios",
		Path:        ontologyconnect.OntologyServiceGetCapabilityScenariosProcedure,
		Method:      "POST",
		Summary:     "List scenarios for a capability",
		Description: "Returns live and planned scenarios fulfilling a capability, optionally through descendants.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "GetCapabilityScenariosRequest"},
		Response:    &module.Schema{Type: "CapabilityScenarios"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology capability-scenarios", Args: []string{"<slug>"}},
	},
	{
		ID:          "ontology-scenario-capabilities",
		Path:        ontologyconnect.OntologyServiceGetScenarioCapabilitiesProcedure,
		Method:      "POST",
		Summary:     "List capabilities for a scenario",
		Description: "Returns ontology capabilities directly fulfilled by one scenario slug.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "GetScenarioCapabilitiesRequest"},
		Response:    &module.Schema{Type: "ScenarioCapabilities"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology scenario", Args: []string{"<slug>"}},
	},
	{
		ID:          "ontology-overlay-graph",
		Path:        ontologyconnect.OntologyServiceDescribeOverlayGraphProcedure,
		Method:      "POST",
		Summary:     "Describe the overlay graph",
		Description: "Projects capability nodes, ontology edges, fulfillment edges, and implementation graph nodes into one graph response.",
		Category:    "ontology",
		Request:     &module.Schema{Type: "DescribeOverlayGraphRequest"},
		Response:    &module.Schema{Type: "DescribeOverlayGraphResponse"},
		CLIMapping:  &module.CLIMapping{Command: "tech-tree-designer ontology overlay"},
	},
}
