// Actual collection, cards, query/store/services; only HTTP responses are disposable.
import { cleanup, fireEvent, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useLocation } from "react-router-dom";
import type { QueryClient } from "@tanstack/react-query";
import { createTestQueryClient, renderWithProviders } from "../../../../test-utils";
import { backlogStoreInitialState, useBacklogStore } from "../../../../stores/backlog-store";
import { useAgentActivitiesStore } from "../../../../stores";
import { useSnoozeStore } from "../../../../stores/snooze-store";
import { mapProtoBacklogItem, parseProtoResponse, backlogItemResponseSchema } from "../../../../services/proto-contracts";
import { BacklogTab } from "./BacklogTab";
import { DEFAULT_FILTERS, type BacklogFilters, type SortConfig } from "./types";
const base={kind:"fix",name:"alpha-fixture",title:"Alpha fixture",description:"Typed local defect",status:"ready",priority:2,tags:["needle"],suggested_skills:[],created:"2026-10-05T00:00:00Z",updated:"2026-10-05T00:00:00Z"};
const sources=[base,{...base,kind:"idea",name:"beta-fixture",title:"Beta fixture",description:"Different description",tags:[],status:"backlog",priority:4},{...base,name:"old-fixture",title:"Archived fixture",archived_at:"2026-10-05T00:00:00Z",priority:1}];
function mapped(){return sources.map(item=>mapProtoBacklogItem(parseProtoResponse(backlogItemResponseSchema,{item},"fixture backlog").item!));}
let calls:{method:string;path:string;body:unknown}[];let unexpected:string[];let enabled:boolean;const clients:QueryClient[]=[];
function json(value:unknown){return new Response(JSON.stringify(value),{headers:{"content-type":"application/json"}});}
function Location(){return <output data-testid="fixture-location">{useLocation().pathname+useLocation().search}</output>;}
function mount(options:{filters?:Partial<BacklogFilters>;search?:string;sort?:SortConfig;create?:boolean}={}){const client=createTestQueryClient();clients.push(client);const click=vi.fn(),clear=vi.fn(),create=vi.fn(),plan=vi.fn();const props={searchQuery:options.search??"",filters:{...DEFAULT_FILTERS.backlog,...options.filters},sort:options.sort??{field:"alphabetical" as const,direction:"asc" as const},onItemClick:click,onClearSearch:clear,...(options.create?{onCreateBacklog:create,onCreateFromPlan:plan}:{})};const view=renderWithProviders(<><Location/><BacklogTab {...props}/></>,{queryClient:client,initialEntries:["/graph"]});return{...view,props,client,click,clear,create,plan};}
function titles(){return screen.queryAllByRole("heading",{level:3}).map(node=>node.textContent);}
function writes(){return calls.filter(c=>c.method!=="GET"&&c.path!=="/backlog/next-actions");}
beforeEach(()=>{calls=[];unexpected=[];enabled=true;useBacklogStore.setState({...backlogStoreInitialState,items:mapped(),blockingMap:{},status:"success"});useAgentActivitiesStore.setState({activities:[]});useSnoozeStore.setState({entries:new Map()});window.localStorage.clear();vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const request=new Request(input,init);const path=new URL(request.url).pathname.replace(/^\/api\/v1/,"");const body=request.body?JSON.parse(await request.text()):undefined;calls.push({method:request.method,path,body});if(request.method==="POST"&&path==="/backlog/next-actions")return json({results:(body.items as string[]).map(item=>({item,action:{id:"author_plan",compact_label:"Plan",expanded_label:`Plan ${item}`,enabled,blockers:[]}}))});if(request.method==="GET"&&path==="/backlog/summary")return json({pending_questions:{items:[]}});unexpected.push(request.method+" "+path);throw new Error("Unexpected fixture request "+path);}));});
afterEach(()=>{cleanup();clients.splice(0).forEach(c=>c.clear());expect(unexpected).toEqual([]);expect(writes()).toEqual([]);useBacklogStore.setState({...backlogStoreInitialState,blockingMap:{}});useAgentActivitiesStore.setState({activities:[]});useSnoozeStore.setState({entries:new Map()});window.localStorage.clear();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe("real sidebar backlog collection workflows",()=>{
 it("hides archived owners by default and displays sorted exact live titles",()=>{mount();expect(titles()).toEqual(["Alpha fixture","Beta fixture"]);});
 it("includes archived owners only when explicitly selected",()=>{mount({filters:{showArchived:true}});expect(titles()).toEqual(["Alpha fixture","Archived fixture","Beta fixture"]);});
 it.each([{statuses:["backlog" as const]},{kinds:["idea" as const]},{priorityMin:3},{priorityMax:1}] as Partial<BacklogFilters>[])("enforces owner filter %j",filters=>{mount({filters});expect(titles()).toEqual(filters.priorityMax===1?[]:["Beta fixture"]);});
 it("combines status,kind and priority bounds rather than widening the filter",()=>{mount({filters:{statuses:["ready"],kinds:["fix"],priorityMin:2,priorityMax:2}});expect(titles()).toEqual(["Alpha fixture"]);});
 it.each(["needle","TYPED LOCAL","alpha-fixture"])("matches exact title/name/description/tag search %s",search=>{mount({search});expect(titles()).toEqual(["Alpha fixture"]);});
 it("snoozes only the exact owner locally while retaining others",()=>{useSnoozeStore.getState().snooze("backlog:fix/alpha-fixture",Date.now()+3600000);mount();expect(titles()).toEqual(["Beta fixture"]);});
 it("offers create callbacks in the real empty collection without inventing a mutation",()=>{useBacklogStore.setState({items:[]});const view=mount({create:true});expect(screen.getByText("No backlog items yet.")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Create item"}));fireEvent.click(screen.getByRole("button",{name:"Create from plan"}));expect(view.create).toHaveBeenCalledOnce();expect(view.plan).toHaveBeenCalledOnce();expect(calls.filter(c=>c.path==="/backlog/next-actions")).toEqual([]);});
 it("recovers a stale search explicitly without exposing create controls",()=>{const view=mount({search:"missing-owner",create:true});expect(screen.getByText('No matches for "missing-owner"')).toBeVisible();expect(screen.queryByRole("button",{name:"Create item"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Clear search"}));expect(view.clear).toHaveBeenCalledOnce();expect(titles()).toEqual([]);});
 it("opens exactly the clicked content owner and does not confuse action buttons with row opening",async()=>{const view=mount();fireEvent.click(screen.getByRole("heading",{name:"Alpha fixture"}));expect(view.click.mock.calls).toEqual([["backlog-item/fix/alpha-fixture"]]);fireEvent.click(await screen.findByRole("button",{name:"Plan fix/alpha-fixture"}));expect(view.click).toHaveBeenCalledOnce();await waitFor(()=>expect(screen.getByTestId("fixture-location")).toHaveTextContent("/backlog/fix/alpha-fixture"));});
 it("honors an explicitly disabled owner projection without navigating or writing",async()=>{enabled=false;const view=mount();const action=await screen.findByRole("button",{name:"Plan fix/alpha-fixture"});expect(action).toBeDisabled();fireEvent.click(action);expect(view.click).not.toHaveBeenCalled();expect(screen.getByTestId("fixture-location")).toHaveTextContent("/graph");});
 it("reads projections for the complete owner collection and retains them through a filter change",async()=>{const view=mount();await screen.findByRole("button",{name:"Plan fix/alpha-fixture"});const projections=()=>calls.filter(c=>c.path==="/backlog/next-actions");expect(projections()).toHaveLength(1);expect(projections()[0]!.body).toEqual({items:["fix/alpha-fixture","idea/beta-fixture","fix/old-fixture"]});view.rerender(<><Location/><BacklogTab {...view.props} searchQuery="Beta"/></>);expect(titles()).toEqual(["Beta fixture"]);await screen.findByRole("button",{name:"Plan idea/beta-fixture"});expect(projections()).toHaveLength(1);});
});
