import { ValueOf } from "./commonTypes.js";

export const LINKS = {
    About: "/about",
    Api: "/api",
    Awards: "/awards",
    BookmarkList: "/bookmarks",
    Calendar: "/cal",
    Chat: "/chat",
    ChatMessage: "/message",
    Comment: "/comment",
    Create: "/create",
    DataConverter: "/code",
    DataStructure: "/ds",
    ForgotPassword: "/auth/forgot-password",
    History: "/history",
    Home: "/", // Main dashboard for logged in users
    Inbox: "/in",
    Issue: "/issue",
    Login: "/auth/login",
    Meeting: "/meeting",
    MyStuff: "/my",
    Note: "/note",
    Post: "/post",
    Pro: "/pro",
    Privacy: "/privacy", // Privacy policy
    Profile: "/u",
    Project: "/project",
    Prompt: "/prompt",
    Question: "/question",
    Quiz: "/quiz",
    Reminder: "/reminder",
    Report: "/report",
    Reports: "/reports",
    ResetPassword: "/auth/password-reset",
    RoutineSingleStep: "/action",
    RoutineMultiStep: "/flow",
    Run: "/run",
    Schedule: "/event",
    Search: "/search",
    SearchVersion: "/search/version",
    Settings: "/settings",
    SettingsApi: "/settings/api",
    SettingsAuthentication: "/settings/auth",
    SettingsData: "/settings/data",
    SettingsDisplay: "/settings/display",
    SettingsFocusModes: "/settings/focus",
    SettingsNotifications: "/settings/notifications",
    SettingsPayments: "/settings/payments",
    SettingsPrivacy: "/settings/privacy",
    SettingsProfile: "/settings/profile",
    Signup: "/auth/signup",
    SmartContract: "/contract",
    Stats: "/stats", // Provides statistics for the website (no admin, so only place to see users, metrics, etc.)
    Tag: "/tag",
    Team: "/team",
    Terms: "/terms", // Terms and conditions
    User: "/u",
} as const;
export type LINKS = ValueOf<typeof LINKS>;

export const THEME = {
    Light: "light",
    Dark: "dark",
};
export type THEME = ValueOf<typeof THEME>;

export const DEFAULT_LANGUAGE = "en";

export enum CodeLanguage {
    Angular = "angular",
    Cpp = "cpp",
    Css = "css",
    Dockerfile = "dockerfile",
    Go = "go",
    Graphql = "graphql",
    Groovy = "groovy",
    Haskell = "haskell",
    Html = "html",
    Java = "java",
    Javascript = "javascript",
    Json = "json", // JSON which may or may not conform to a standard
    JsonStandard = "jsonStandard", // JSON which defines a standard for some data (could be JSON, a file, etc.)
    Nginx = "nginx",
    Nix = "nix",
    Php = "php",
    Powershell = "powershell",
    Protobuf = "protobuf",
    Puppet = "puppet",
    Python = "python",
    R = "r",
    Ruby = "ruby",
    Rust = "rust",
    Sass = "sass",
    Shell = "shell",
    Solidity = "solidity",
    Spreadsheet = "spreadsheet",
    Sql = "sql",
    Svelte = "svelte",
    Swift = "swift",
    Typescript = "typescript",
    Vb = "vb",
    Vbscript = "vbscript",
    Verilog = "verilog",
    Vhdl = "vhdl",
    Vue = "vue",
    Xml = "xml",
    Yacas = "yacas",
    Yaml = "yaml",
}
