#!/usr/bin/env bash
# Apache Airflow Resource - Default Configuration

# Service identification
export AIRFLOW_RESOURCE_NAME="apache-airflow"
export AIRFLOW_SERVICE_NAME="Apache Airflow"

# Port configuration
export AIRFLOW_WEBSERVER_PORT="${AIRFLOW_WEBSERVER_PORT:-48080}"
export AIRFLOW_FLOWER_PORT="${AIRFLOW_FLOWER_PORT:-45555}"
export AIRFLOW_REDIS_PORT="${AIRFLOW_REDIS_PORT:-46379}"
export AIRFLOW_POSTGRES_PORT="${AIRFLOW_POSTGRES_PORT:-45432}"

# Directory configuration
export AIRFLOW_HOME="${AIRFLOW_HOME:-${SCRIPT_DIR}/airflow-home}"
export AIRFLOW_DAG_DIR="${AIRFLOW_DAG_DIR:-${AIRFLOW_HOME}/dags}"
export AIRFLOW_LOG_DIR="${AIRFLOW_LOG_DIR:-${AIRFLOW_HOME}/logs}"
export AIRFLOW_PLUGIN_DIR="${AIRFLOW_PLUGIN_DIR:-${AIRFLOW_HOME}/plugins}"
export AIRFLOW_DATA_DIR="${AIRFLOW_DATA_DIR:-${AIRFLOW_HOME}/data}"

# Docker configuration
export AIRFLOW_DOCKER_IMAGE="${AIRFLOW_DOCKER_IMAGE:-apache/airflow:3.0.6}"
export AIRFLOW_DOCKER_NETWORK="${AIRFLOW_DOCKER_NETWORK:-airflow-network}"
export AIRFLOW_COMPOSE_FILE="${AIRFLOW_COMPOSE_FILE:-${SCRIPT_DIR}/docker/docker-compose.yml}"

# Database configuration
export AIRFLOW_POSTGRES_USER="${AIRFLOW_POSTGRES_USER:-airflow}"
export AIRFLOW_POSTGRES_PASSWORD="${AIRFLOW_POSTGRES_PASSWORD:-airflow}"
export AIRFLOW_POSTGRES_DB="${AIRFLOW_POSTGRES_DB:-airflow}"

# Redis configuration
export AIRFLOW_REDIS_PASSWORD="${AIRFLOW_REDIS_PASSWORD:-}"

# Executor configuration
export AIRFLOW_EXECUTOR="${AIRFLOW_EXECUTOR:-CeleryExecutor}"

# Worker configuration
export AIRFLOW_WORKER_COUNT="${AIRFLOW_WORKER_COUNT:-2}"
export AIRFLOW_WORKER_CONCURRENCY="${AIRFLOW_WORKER_CONCURRENCY:-16}"

# Performance configuration
export AIRFLOW_PARALLELISM="${AIRFLOW_PARALLELISM:-32}"
export AIRFLOW_DAG_CONCURRENCY="${AIRFLOW_DAG_CONCURRENCY:-16}"
export AIRFLOW_MAX_ACTIVE_RUNS="${AIRFLOW_MAX_ACTIVE_RUNS:-16}"

# Timeout configuration
export AIRFLOW_STARTUP_TIMEOUT="${AIRFLOW_STARTUP_TIMEOUT:-120}"
export AIRFLOW_HEALTH_CHECK_TIMEOUT="${AIRFLOW_HEALTH_CHECK_TIMEOUT:-5}"
export AIRFLOW_SHUTDOWN_TIMEOUT="${AIRFLOW_SHUTDOWN_TIMEOUT:-30}"

# Admin user configuration
export AIRFLOW_ADMIN_USER="${AIRFLOW_ADMIN_USER:-admin}"
export AIRFLOW_ADMIN_PASSWORD="${AIRFLOW_ADMIN_PASSWORD:-admin}"
export AIRFLOW_ADMIN_EMAIL="${AIRFLOW_ADMIN_EMAIL:-admin@example.com}"

# Feature flags
export AIRFLOW_ENABLE_FLOWER="${AIRFLOW_ENABLE_FLOWER:-false}"
export AIRFLOW_ENABLE_EXAMPLE_DAGS="${AIRFLOW_ENABLE_EXAMPLE_DAGS:-true}"
export AIRFLOW_ENABLE_METRICS="${AIRFLOW_ENABLE_METRICS:-false}"

# Logging configuration
export AIRFLOW_LOG_LEVEL="${AIRFLOW_LOG_LEVEL:-INFO}"
export AIRFLOW_LOG_FETCH_TIMEOUT="${AIRFLOW_LOG_FETCH_TIMEOUT:-5}"

# Health check configuration
export AIRFLOW_HEALTH_CHECK_INTERVAL="${AIRFLOW_HEALTH_CHECK_INTERVAL:-30}"
export AIRFLOW_HEALTH_CHECK_MAX_RETRIES="${AIRFLOW_HEALTH_CHECK_MAX_RETRIES:-3}"