// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $rowKey: "$rowKey",
  $schema: "$schema",
  app: {
    description: "app.description",
    eyebrow: "app.eyebrow",
    title: "app.title",
  },
  "aria-label": "aria-label",
  ascending: "ascending",
  "border-app-primary bg-app-primary text-app-primary-foreground": "border-app-primary bg-app-primary text-app-primary-foreground",
  caption: "caption",
  clsx: "clsx",
  default: "default",
  defaultValue: "defaultValue",
  desc: "desc",
  emptyMessage: "emptyMessage",
  equals: "equals",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  experience: {
    common: {
      claims: "experience.common.claims",
      debt: "experience.common.debt",
      depth: "experience.common.depth",
      page: "experience.common.page",
      scenario: "experience.common.scenario",
      status: "experience.common.status",
      tier: "experience.common.tier",
      viewEvidence: "experience.common.viewEvidence",
    },
    evidence: {
      captureLabel: "experience.evidence.captureLabel",
      captureReference: "experience.evidence.captureReference",
      description: "experience.evidence.description",
      emptyEvidence: "experience.evidence.emptyEvidence",
      emptyTree: "experience.evidence.emptyTree",
      emptyVerdicts: "experience.evidence.emptyVerdicts",
      loadError: "experience.evidence.loadError",
      loadingEvidence: "experience.evidence.loadingEvidence",
      recapture: "experience.evidence.recapture",
      refreshing: "experience.evidence.refreshing",
      staleEvidence: "experience.evidence.staleEvidence",
      title: "experience.evidence.title",
      treeLabel: "experience.evidence.treeLabel",
      verdictsLabel: "experience.evidence.verdictsLabel",
    },
    explorer: {
      claimsLabel: "experience.explorer.claimsLabel",
      defaultState: "experience.explorer.defaultState",
      description: "experience.explorer.description",
      emptyClaims: "experience.explorer.emptyClaims",
      emptyGap: "experience.explorer.emptyGap",
      emptySpec: "experience.explorer.emptySpec",
      emptyState: "experience.explorer.emptyState",
      gapsLabel: "experience.explorer.gapsLabel",
      gridLabel: "experience.explorer.gridLabel",
      loadError: "experience.explorer.loadError",
      loadingClaims: "experience.explorer.loadingClaims",
      loadingSpec: "experience.explorer.loadingSpec",
      openStudio: "experience.explorer.openStudio",
      refreshing: "experience.explorer.refreshing",
      staleData: "experience.explorer.staleData",
      staleState: "experience.explorer.staleState",
      summary: "experience.explorer.summary",
      title: "experience.explorer.title",
    },
    findings: {
      apply: "experience.findings.apply",
      applyError: "experience.findings.applyError",
      description: "experience.findings.description",
      emptyFindings: "experience.findings.emptyFindings",
      fixPreviewLabel: "experience.findings.fixPreviewLabel",
      listLabel: "experience.findings.listLabel",
      loadError: "experience.findings.loadError",
      loadingFindings: "experience.findings.loadingFindings",
      preview: "experience.findings.preview",
      previewEmpty: "experience.findings.previewEmpty",
      previewError: "experience.findings.previewError",
      providerCapabilities: "experience.findings.providerCapabilities",
      providerContract: "experience.findings.providerContract",
      providerDocumentation: "experience.findings.providerDocumentation",
      providerHistorical: "experience.findings.providerHistorical",
      providerLoading: "experience.findings.providerLoading",
      providerMaturity: "experience.findings.providerMaturity",
      providerNextAction: "experience.findings.providerNextAction",
      providerNorthStar: "experience.findings.providerNorthStar",
      providerUnavailable: "experience.findings.providerUnavailable",
      title: "experience.findings.title",
    },
    fleet: {
      depthDistribution: "experience.fleet.depthDistribution",
      depthLabel: "experience.fleet.depthLabel",
      description: "experience.fleet.description",
      emptyFleet: "experience.fleet.emptyFleet",
      filterAll: "experience.fleet.filterAll",
      filterClean: "experience.fleet.filterClean",
      filterFindings: "experience.fleet.filterFindings",
      filterStatus: "experience.fleet.filterStatus",
      loadError: "experience.fleet.loadError",
      loadingData: "experience.fleet.loadingData",
      pagesTracked: "experience.fleet.pagesTracked",
      refresh: "experience.fleet.refresh",
      sortBy: "experience.fleet.sortBy",
      specCoverage: "experience.fleet.specCoverage",
      staleData: "experience.fleet.staleData",
      tableLabel: "experience.fleet.tableLabel",
      title: "experience.fleet.title",
    },
    studio: {
      defaultClaim: "experience.studio.defaultClaim",
      defaultPage: "experience.studio.defaultPage",
      description: "experience.studio.description",
      emptyClaim: "experience.studio.emptyClaim",
      emptyPreview: "experience.studio.emptyPreview",
      emptySpec: "experience.studio.emptySpec",
      emptySuggestions: "experience.studio.emptySuggestions",
      emptyVariants: "experience.studio.emptyVariants",
      evidenceForwardVariant: "experience.studio.evidenceForwardVariant",
      formLabel: "experience.studio.formLabel",
      loadError: "experience.studio.loadError",
      loadingPreview: "experience.studio.loadingPreview",
      loadingSpec: "experience.studio.loadingSpec",
      loadingSuggestions: "experience.studio.loadingSuggestions",
      pageTitle: "experience.studio.pageTitle",
      promote: "experience.studio.promote",
      save: "experience.studio.save",
      saving: "experience.studio.saving",
      suggestionsLabel: "experience.studio.suggestionsLabel",
      title: "experience.studio.title",
      validationCopy: "experience.studio.validationCopy",
      validationLabel: "experience.studio.validationLabel",
      variantError: "experience.studio.variantError",
      variantsLabel: "experience.studio.variantsLabel",
      wireframeLabel: "experience.studio.wireframeLabel",
    },
  },
  export: "export",
  field: "field",
  header: "header",
  id: "id",
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      evidence: "layout.nav.evidence",
      explorer: "layout.nav.explorer",
      findings: "layout.nav.findings",
      fleet: "layout.nav.fleet",
      settings: "layout.nav.settings",
      studio: "layout.nav.studio",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  "lucide-react": "lucide-react",
  mode: "mode",
  module: "module",
  name: "name",
  pages: {
    settings: {
      localeHeading: "pages.settings.localeHeading",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
  },
  path: "path",
  placeholder: "placeholder",
  react: "react",
  resolvedAt: "resolvedAt",
  role: "role",
  selector: "selector",
  status: "status",
  "tailwind-merge": "tailwind-merge",
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  title: "title",
  value: "value",
  version: "version",
} as const;

export type Strings = typeof strings;
