// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
    description: "app.description",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      fleet: "layout.nav.fleet",
      explorer: "layout.nav.explorer",
      evidence: "layout.nav.evidence",
      studio: "layout.nav.studio",
      findings: "layout.nav.findings",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  experience: {
    common: {
      scenario: "experience.common.scenario",
      page: "experience.common.page",
      depth: "experience.common.depth",
      debt: "experience.common.debt",
      status: "experience.common.status",
      claims: "experience.common.claims",
      tier: "experience.common.tier",
      viewEvidence: "experience.common.viewEvidence",
    },
    fleet: {
      title: "experience.fleet.title",
      description: "experience.fleet.description",
      depthLabel: "experience.fleet.depthLabel",
      specCoverage: "experience.fleet.specCoverage",
      depthDistribution: "experience.fleet.depthDistribution",
      refresh: "experience.fleet.refresh",
      tableLabel: "experience.fleet.tableLabel",
      pagesTracked: "experience.fleet.pagesTracked",
      loadingData: "experience.fleet.loadingData",
      emptyFleet: "experience.fleet.emptyFleet",
      loadError: "experience.fleet.loadError",
      staleData: "experience.fleet.staleData",
      filterStatus: "experience.fleet.filterStatus",
      filterAll: "experience.fleet.filterAll",
      filterFindings: "experience.fleet.filterFindings",
      filterClean: "experience.fleet.filterClean",
      sortBy: "experience.fleet.sortBy",
    },
    explorer: {
      title: "experience.explorer.title",
      description: "experience.explorer.description",
      gridLabel: "experience.explorer.gridLabel",
      gapsLabel: "experience.explorer.gapsLabel",
      openStudio: "experience.explorer.openStudio",
      claimsLabel: "experience.explorer.claimsLabel",
      defaultState: "experience.explorer.defaultState",
      emptyState: "experience.explorer.emptyState",
      staleState: "experience.explorer.staleState",
      loadingSpec: "experience.explorer.loadingSpec",
      emptySpec: "experience.explorer.emptySpec",
      loadError: "experience.explorer.loadError",
      emptyGap: "experience.explorer.emptyGap",
      staleData: "experience.explorer.staleData",
      summary: "experience.explorer.summary",
      refreshing: "experience.explorer.refreshing",
      loadingClaims: "experience.explorer.loadingClaims",
      emptyClaims: "experience.explorer.emptyClaims",
    },
    evidence: {
      title: "experience.evidence.title",
      description: "experience.evidence.description",
      captureLabel: "experience.evidence.captureLabel",
      treeLabel: "experience.evidence.treeLabel",
      verdictsLabel: "experience.evidence.verdictsLabel",
      recapture: "experience.evidence.recapture",
      refreshing: "experience.evidence.refreshing",
      loadingEvidence: "experience.evidence.loadingEvidence",
      emptyEvidence: "experience.evidence.emptyEvidence",
      emptyVerdicts: "experience.evidence.emptyVerdicts",
      emptyTree: "experience.evidence.emptyTree",
      loadError: "experience.evidence.loadError",
      staleEvidence: "experience.evidence.staleEvidence",
      captureReference: "experience.evidence.captureReference",
    },
    studio: {
      title: "experience.studio.title",
      description: "experience.studio.description",
      formLabel: "experience.studio.formLabel",
      validationLabel: "experience.studio.validationLabel",
      validationCopy: "experience.studio.validationCopy",
      wireframeLabel: "experience.studio.wireframeLabel",
      variantsLabel: "experience.studio.variantsLabel",
      save: "experience.studio.save",
      saving: "experience.studio.saving",
      promote: "experience.studio.promote",
      pageTitle: "experience.studio.pageTitle",
      defaultPage: "experience.studio.defaultPage",
      defaultClaim: "experience.studio.defaultClaim",
      emptyClaim: "experience.studio.emptyClaim",
      loadingSpec: "experience.studio.loadingSpec",
      emptySpec: "experience.studio.emptySpec",
      loadError: "experience.studio.loadError",
      loadingPreview: "experience.studio.loadingPreview",
      emptyPreview: "experience.studio.emptyPreview",
      emptyVariants: "experience.studio.emptyVariants",
      variantError: "experience.studio.variantError",
      evidenceForwardVariant: "experience.studio.evidenceForwardVariant",
      suggestionsLabel: "experience.studio.suggestionsLabel",
      loadingSuggestions: "experience.studio.loadingSuggestions",
      emptySuggestions: "experience.studio.emptySuggestions",
    },
    findings: {
      title: "experience.findings.title",
      description: "experience.findings.description",
      listLabel: "experience.findings.listLabel",
      preview: "experience.findings.preview",
      apply: "experience.findings.apply",
      loadingFindings: "experience.findings.loadingFindings",
      emptyFindings: "experience.findings.emptyFindings",
      loadError: "experience.findings.loadError",
      fixPreviewLabel: "experience.findings.fixPreviewLabel",
      previewEmpty: "experience.findings.previewEmpty",
      previewError: "experience.findings.previewError",
      applyError: "experience.findings.applyError",
      providerMaturity: "experience.findings.providerMaturity",
      providerLoading: "experience.findings.providerLoading",
      providerUnavailable: "experience.findings.providerUnavailable",
      providerHistorical: "experience.findings.providerHistorical",
      providerContract: "experience.findings.providerContract",
      providerNorthStar: "experience.findings.providerNorthStar",
      providerNextAction: "experience.findings.providerNextAction",
      providerCapabilities: "experience.findings.providerCapabilities",
      providerDocumentation: "experience.findings.providerDocumentation",
    },
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
