# Workflow triggers configuration for Resume Screening Assistant
triggers:
  - id: "resume-upload-trigger"
    name: "Resume Upload Trigger"
    type: "webhook"
    config:
      path: "/webhook/resume-upload"
      method: "POST"
      authentication: false
      rateLimit:
        enabled: true
        maxRequests: 100
        windowMs: 60000
    workflow: "resume-processing-pipeline"
    enabled: true
    
  - id: "batch-processing-trigger"
    name: "Batch Processing Trigger"
    type: "schedule"
    config:
      cron: "0 */6 * * *"  # Every 6 hours
      timezone: "UTC"
    workflow: "batch-resume-processor"
    enabled: true
    
  - id: "job-matching-trigger"
    name: "Job Matching Trigger"
    type: "event"
    config:
      event: "new_job_posting"
      source: "api"
    workflow: "job-matching-pipeline"
    enabled: true
    
  - id: "report-generation-trigger"
    name: "Daily Report Generation"
    type: "schedule"
    config:
      cron: "0 9 * * *"  # Daily at 9 AM
      timezone: "UTC"
    workflow: "report-generator"
    enabled: true

workflows:
  resume-processing-pipeline:
    name: "Resume Processing Pipeline"
    description: "Main pipeline for processing individual resumes"
    platform: "n8n"
    file: "n8n/resume-processing-pipeline.json"
    timeout: 300000
    retries: 3
    
  batch-resume-processor:
    name: "Batch Resume Processor"
    description: "Process multiple resumes in batch"
    platform: "n8n"
    file: "n8n/batch-processor.json"
    timeout: 1800000
    retries: 1
    
  job-matching-pipeline:
    name: "Job Matching Pipeline"
    description: "Match candidates to job postings"
    platform: "windmill"
    file: "windmill/scripts/job_matcher.py"
    timeout: 600000
    retries: 2
    
  report-generator:
    name: "Report Generator"
    description: "Generate recruitment analytics reports"
    platform: "windmill"
    file: "windmill/scripts/report_generator.py"
    timeout: 900000
    retries: 1

activation:
  startup_delay: 5000  # 5 seconds delay after startup
  health_check_interval: 30000  # Check every 30 seconds
  failure_threshold: 3  # Disable after 3 consecutive failures
  recovery_attempts: 5  # Try to recover 5 times before giving up
  
monitoring:
  enabled: true
  metrics:
    - workflow_executions_total
    - workflow_execution_duration
    - workflow_success_rate
    - workflow_error_rate
  alerts:
    - type: "error_rate"
      threshold: 10  # Alert if error rate > 10%
      window: 3600  # Over 1 hour
    - type: "execution_time"
      threshold: 60000  # Alert if execution > 60 seconds
      workflow: "resume-processing-pipeline"