package codegen

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"flow-verifier/internal/flows/model"
)

func generatedHeader(flow model.Flow) string {
	return fmt.Sprintf("// Code generated by flow-verifier from %s; DO NOT EDIT.\n\n", flow.ContractPath)
}

func quotedList(values []string) string {
	if len(values) == 0 {
		return ""
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}

func tsQuotedList(values []string) string {
	return strings.Join(strings.Split(quotedList(values), ", "), ", ")
}

func sortedKeys(values map[string]string) []string {
	out := make([]string, 0, len(values))
	for key := range values {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

var wordBoundary = regexp.MustCompile(`[^A-Za-z0-9]+`)

func pascal(value string) string {
	parts := wordBoundary.Split(value, -1)
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		lower := strings.ToLower(part)
		out.WriteString(strings.ToUpper(lower[:1]))
		if len(lower) > 1 {
			out.WriteString(lower[1:])
		}
	}
	return out.String()
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}

// TypeScriptBase returns the "base name" used to derive runtime and
// fixture identifier conventions from a TypeScript runtime's
// StatusType (e.g. "AttachmentUploadStatus" → "AttachmentUpload").
func TypeScriptBase(statusType string) string {
	base := strings.TrimSuffix(statusType, "Status")
	if base == "" {
		return statusType
	}
	return base
}

// TypeScriptFixturesExportName is the canonical export name for the
// hand-authored fixtures.ts file. Both codegen and the lint pass use
// this helper so they cannot drift.
//
// Returns "" if the flow has no TypeScript runtime.
func TypeScriptFixturesExportName(flow model.Flow) string {
	if flow.Runtime.TypeScript == nil {
		return ""
	}
	return lowerFirst(TypeScriptBase(flow.Runtime.TypeScript.StatusType)) + "FormalFixtures"
}
