import { AdvancedInputFeatures } from "./utils.js";

export const nameInputFeatures: AdvancedInputFeatures = {
    allowFormatting: false,
    allowExpand: false,
    allowFileAttachments: false,
    allowImageAttachments: false,
    allowTextAttachments: false,
    allowTools: false,
    allowCharacterLimit: true,
    allowVoiceInput: false,
    allowSubmit: false,
    allowSettingsCustomization: false,
    allowSpellcheck: true,
    allowContextDropdown: false,
    maxChars: 128,
    minRowsCollapsed: 1,
    maxRowsCollapsed: 2,
    minRowsExpanded: undefined,
    maxRowsExpanded: undefined,
};

export const detailsInputFeatures: AdvancedInputFeatures = {
    allowFormatting: true,
    allowExpand: true,
    allowFileAttachments: false,
    allowImageAttachments: false,
    allowTextAttachments: false,
    allowTools: false,
    allowCharacterLimit: true,
    allowVoiceInput: false,
    allowSubmit: false,
    allowSettingsCustomization: false,
    allowSpellcheck: true,
    allowContextDropdown: false,
    maxChars: 8192,
    minRowsCollapsed: 1,
    maxRowsCollapsed: 2,
    minRowsExpanded: 4,
    maxRowsExpanded: 8,
};

export const summaryInputFeatures: AdvancedInputFeatures = {
    allowFormatting: false,
    allowExpand: false,
    allowFileAttachments: false,
    allowImageAttachments: false,
    allowTextAttachments: false,
    allowTools: false,
    allowCharacterLimit: true,
    allowVoiceInput: false,
    allowSubmit: false,
    allowSettingsCustomization: false,
    allowSpellcheck: true,
    allowContextDropdown: false,
    maxChars: 1024,
    minRowsCollapsed: 1,
    maxRowsCollapsed: 4,
    minRowsExpanded: 8,
    maxRowsExpanded: 16,
};
