#!/bin/bash

# PyBullet Default Configuration
# v2.0 Universal Contract

# Resource identification
export PYBULLET_RESOURCE_NAME="pybullet"
export PYBULLET_RESOURCE_VERSION="1.0.0"

# Python configuration
export PYBULLET_PYTHON_VERSION="${PYBULLET_PYTHON_VERSION:-3.8}"
export PYBULLET_VENV_NAME="${PYBULLET_VENV_NAME:-.venv}"

# Physics configuration
export PYBULLET_TIMESTEP="${PYBULLET_TIMESTEP:-0.004167}"  # 240Hz
export PYBULLET_GRAVITY_X="${PYBULLET_GRAVITY_X:-0}"
export PYBULLET_GRAVITY_Y="${PYBULLET_GRAVITY_Y:-0}"
export PYBULLET_GRAVITY_Z="${PYBULLET_GRAVITY_Z:--9.81}"
export PYBULLET_SOLVER_ITERATIONS="${PYBULLET_SOLVER_ITERATIONS:-10}"

# API server configuration
export PYBULLET_MAX_SIMULATIONS="${PYBULLET_MAX_SIMULATIONS:-10}"
export PYBULLET_API_TIMEOUT="${PYBULLET_API_TIMEOUT:-300}"
export PYBULLET_WORKERS="${PYBULLET_WORKERS:-1}"

# Rendering configuration
export PYBULLET_ENABLE_GUI="${PYBULLET_ENABLE_GUI:-false}"
export PYBULLET_RENDER_WIDTH="${PYBULLET_RENDER_WIDTH:-1024}"
export PYBULLET_RENDER_HEIGHT="${PYBULLET_RENDER_HEIGHT:-768}"
export PYBULLET_RENDER_FOV="${PYBULLET_RENDER_FOV:-60}"

# Resource limits
export PYBULLET_MAX_BODIES="${PYBULLET_MAX_BODIES:-1000}"
export PYBULLET_MAX_MEMORY_MB="${PYBULLET_MAX_MEMORY_MB:-512}"

# Logging
export PYBULLET_LOG_LEVEL="${PYBULLET_LOG_LEVEL:-INFO}"
export PYBULLET_LOG_FILE="${PYBULLET_LOG_FILE:-pybullet.log}"

# Health check
export PYBULLET_HEALTH_TIMEOUT="${PYBULLET_HEALTH_TIMEOUT:-5}"
export PYBULLET_STARTUP_TIMEOUT="${PYBULLET_STARTUP_TIMEOUT:-30}"