// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
    description: "app.description",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      workbench: "layout.nav.workbench",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      statPlaceholderLabel: "pages.dashboard.statPlaceholderLabel",
    },
    workbench: {
      title: "pages.workbench.title",
      description: "pages.workbench.description",
      catalogHeading: "pages.workbench.catalogHeading",
      catalogCaption: "pages.workbench.catalogCaption",
      styleHeading: "pages.workbench.styleHeading",
      strategyHeading: "pages.workbench.strategyHeading",
      lineageHeading: "pages.workbench.lineageHeading",
      state: "pages.workbench.state",
      emptyTitle: "pages.workbench.emptyTitle",
      emptyDescription: "pages.workbench.emptyDescription",
      reviewAction: "pages.workbench.reviewAction",
      contrastLabel: "pages.workbench.contrastLabel",
      candidateHeading: "pages.workbench.candidateHeading",
      candidateDescription: "pages.workbench.candidateDescription",
      standaloneLabel: "pages.workbench.standaloneLabel",
      contextLabel: "pages.workbench.contextLabel",
      foregroundLabel: "pages.workbench.foregroundLabel",
      candidateOneAlt: "pages.workbench.candidateOneAlt",
      candidateTwoAlt: "pages.workbench.candidateTwoAlt",
      passVerdict: "pages.workbench.passVerdict",
      failVerdict: "pages.workbench.failVerdict",
      resolvedPlan: "pages.workbench.resolvedPlan",
      copyPlan: "pages.workbench.copyPlan",
      planCopied: "pages.workbench.planCopied",
      altTextLabel: "pages.workbench.altTextLabel",
      altTextPlaceholder: "pages.workbench.altTextPlaceholder",
      releaseAction: "pages.workbench.releaseAction",
      releaseBlocked: "pages.workbench.releaseBlocked",
      loadingState: "pages.workbench.loadingState",
      errorState: "pages.workbench.errorState",
      emptyState: "pages.workbench.emptyState",
      errorRetry: "pages.workbench.errorRetry",
      contactSheetHeading: "pages.workbench.contactSheetHeading",
      contactSheetDescription: "pages.workbench.contactSheetDescription",
      placementHeading: "pages.workbench.placementHeading",
      placementDescription: "pages.workbench.placementDescription",
      forkHeading: "pages.workbench.forkHeading",
      forkDescription: "pages.workbench.forkDescription",
      forkAction: "pages.workbench.forkAction",
      packAction: "pages.workbench.packAction",
      productChrome: "pages.workbench.productChrome",
      storeChrome: "pages.workbench.storeChrome",
      desktopLabel: "pages.workbench.desktopLabel",
      mobileLabel: "pages.workbench.mobileLabel",
      fullBleedLabel: "pages.workbench.fullBleedLabel",
      splitPanelLabel: "pages.workbench.splitPanelLabel",
      axisLineage: "pages.workbench.axisLineage",
      axisSubject: "pages.workbench.axisSubject",
      axisTreatment: "pages.workbench.axisTreatment",
      forkedLabel: "pages.workbench.forkedLabel",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
    catalog: {
      title: "pages.catalog.title",
      description: "pages.catalog.description",
      specimenAlt: "pages.catalog.specimenAlt",
      specimenLoading: "pages.catalog.specimenLoading",
      specimenUnavailable: "pages.catalog.specimenUnavailable",
      metered: "pages.catalog.metered",
      free: "pages.catalog.free",
      tierProcedural: "pages.catalog.tierProcedural",
      tierLocalModel: "pages.catalog.tierLocalModel",
      tierFrontierModel: "pages.catalog.tierFrontierModel",
      untreated: "pages.catalog.untreated",
      axisRole: "pages.catalog.axisRole",
      axisSubject: "pages.catalog.axisSubject",
      axisTreatment: "pages.catalog.axisTreatment",
      axisLineage: "pages.catalog.axisLineage",
      axisPlacement: "pages.catalog.axisPlacement",
      axisAny: "pages.catalog.axisAny",
      resultCount: "pages.catalog.resultCount",
      clearFilters: "pages.catalog.clearFilters",
      loading: "pages.catalog.loading",
      error: "pages.catalog.error",
      retry: "pages.catalog.retry",
      emptyTitle: "pages.catalog.emptyTitle",
      emptyDescription: "pages.catalog.emptyDescription",
      filteredEmptyTitle: "pages.catalog.filteredEmptyTitle",
      filteredEmptyDescription: "pages.catalog.filteredEmptyDescription",
    },
    style: {
      title: "pages.style.title",
      notFound: "pages.style.notFound",
      backToCatalog: "pages.style.backToCatalog",
      chainHeading: "pages.style.chainHeading",
      chainEmpty: "pages.style.chainEmpty",
      parametersHeading: "pages.style.parametersHeading",
      promptHeading: "pages.style.promptHeading",
      generatorHeading: "pages.style.generatorHeading",
      regionsHeading: "pages.style.regionsHeading",
      regionsEmpty: "pages.style.regionsEmpty",
      qualityHeading: "pages.style.qualityHeading",
      qualityPass: "pages.style.qualityPass",
      qualityFail: "pages.style.qualityFail",
      qualityCaption: "pages.style.qualityCaption",
      qualityAbsent: "pages.style.qualityAbsent",
      qualityFloor: "pages.style.qualityFloor",
      qualityCeiling: "pages.style.qualityCeiling",
      mockupHeading: "pages.style.mockupHeading",
      mockupLanding: "pages.style.mockupLanding",
      mockupStore: "pages.style.mockupStore",
      mockupAlt: "pages.style.mockupAlt",
      regionFailing: "pages.style.regionFailing",
      copyKicker: "pages.style.copyKicker",
      copyHeadline: "pages.style.copyHeadline",
      copySubhead: "pages.style.copySubhead",
      copyCta: "pages.style.copyCta",
      surfaceLabel: "pages.style.surfaceLabel",
      seedLabel: "pages.style.seedLabel",
      renderError: "pages.style.renderError",
      remixAction: "pages.style.remixAction",
      compareHeading: "pages.style.compareHeading",
    },
    sweep: {
      title: "pages.sweep.title",
      description: "pages.sweep.description",
      seedStart: "pages.sweep.seedStart",
      count: "pages.sweep.count",
      styleLabel: "pages.sweep.styleLabel",
      select: "pages.sweep.select",
      selected: "pages.sweep.selected",
      empty: "pages.sweep.empty",
      loading: "pages.sweep.loading",
    },
    remix: {
      title: "pages.remix.title",
      description: "pages.remix.description",
      parentLabel: "pages.remix.parentLabel",
      axisLabel: "pages.remix.axisLabel",
      valueLabel: "pages.remix.valueLabel",
      newIdLabel: "pages.remix.newIdLabel",
      renderBoth: "pages.remix.renderBoth",
      save: "pages.remix.save",
      saved: "pages.remix.saved",
      saveError: "pages.remix.saveError",
      parentHeading: "pages.remix.parentHeading",
      childHeading: "pages.remix.childHeading",
      chooseStyle: "pages.remix.chooseStyle",
    },
    backdrops: {
      title: "pages.backdrops.title",
      description: "pages.backdrops.description",
      empty: "pages.backdrops.empty",
      loading: "pages.backdrops.loading",
    },
    candidates: {
      title: "pages.candidates.title",
      description: "pages.candidates.description",
      empty: "pages.candidates.empty",
      loading: "pages.candidates.loading",
    },
    placements: {
      title: "pages.placements.title",
      description: "pages.placements.description",
      empty: "pages.placements.empty",
      loading: "pages.placements.loading",
    },
    surfaces: {
      title: "pages.surfaces.title",
      description: "pages.surfaces.description",
      idHeading: "pages.surfaces.idHeading",
      kindHeading: "pages.surfaces.kindHeading",
      geometryHeading: "pages.surfaces.geometryHeading",
      placementsHeading: "pages.surfaces.placementsHeading",
      authorityHeading: "pages.surfaces.authorityHeading",
      confirmedHeading: "pages.surfaces.confirmedHeading",
      caption: "pages.surfaces.caption",
      empty: "pages.surfaces.empty",
      loading: "pages.surfaces.loading",
      error: "pages.surfaces.error",
    },
    compose: {
      title: "pages.compose.title",
      description: "pages.compose.description",
      planHeading: "pages.compose.planHeading",
      copyPlan: "pages.compose.copyPlan",
      planCopied: "pages.compose.planCopied",
      render: "pages.compose.render",
      chooseStyle: "pages.compose.chooseStyle",
      chooseSurface: "pages.compose.chooseSurface",
      styleLabel: "pages.compose.styleLabel",
      surfaceLabel: "pages.compose.surfaceLabel",
    },
    common: {
      loading: "pages.common.loading",
      error: "pages.common.error",
      retry: "pages.common.retry",
      empty: "pages.common.empty",
      seedLabel: "pages.common.seedLabel",
      provenanceHeading: "pages.common.provenanceHeading",
      renderFailed: "pages.common.renderFailed",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
