// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    description: "app.description",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      offers: "layout.nav.offers",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      priorityBoard: "pages.dashboard.priorityBoard",
      offerRecords: "pages.dashboard.offerRecords",
      firedTriggers: "pages.dashboard.firedTriggers",
      ledgerPosture: "pages.dashboard.ledgerPosture",
      runwayMonths: "pages.dashboard.runwayMonths",
      postureUnavailable: "pages.dashboard.postureUnavailable",
      postureBasis: "pages.dashboard.postureBasis",
      earningNothing: "pages.dashboard.earningNothing",
      emptyGuidance: "pages.dashboard.emptyGuidance",
      sourceUnavailable: "pages.dashboard.sourceUnavailable",
      sourceUnavailableReason: "pages.dashboard.sourceUnavailableReason",
      boardUnavailable: "pages.dashboard.boardUnavailable",
      boardOffer: "pages.dashboard.boardOffer",
      boardStatus: "pages.dashboard.boardStatus",
      boardActual: "pages.dashboard.boardActual",
      rankReason: "pages.dashboard.rankReason",
      rankReasonStatusNotSet: "pages.dashboard.rankReasonStatusNotSet",
      rankReasonIdea: "pages.dashboard.rankReasonIdea",
      rankReasonCandidate: "pages.dashboard.rankReasonCandidate",
      rankReasonTriggerMet: "pages.dashboard.rankReasonTriggerMet",
      rankReasonProposed: "pages.dashboard.rankReasonProposed",
      rankReasonActiveUnknown: "pages.dashboard.rankReasonActiveUnknown",
      rankReasonActiveEarningNothing: "pages.dashboard.rankReasonActiveEarningNothing",
      rankReasonActiveEarning: "pages.dashboard.rankReasonActiveEarning",
      rankReasonShippedUnknown: "pages.dashboard.rankReasonShippedUnknown",
      rankReasonShippedEarningNothing: "pages.dashboard.rankReasonShippedEarningNothing",
      rankReasonShippedEarning: "pages.dashboard.rankReasonShippedEarning",
      rankReasonRetired: "pages.dashboard.rankReasonRetired",
      rankReasonUnknown: "pages.dashboard.rankReasonUnknown",
      actualUnavailable: "pages.dashboard.actualUnavailable",
      blockedOffers: "pages.dashboard.blockedOffers",
      evaluationCondition: "pages.dashboard.evaluationCondition",
      evaluationNotRun: "pages.dashboard.evaluationNotRun",
      evaluationLastRun: "pages.dashboard.evaluationLastRun",
      evaluationNodesScored: "pages.dashboard.evaluationNodesScored",
      evaluationAge: "pages.dashboard.evaluationAge",
      evaluationDegraded: "pages.dashboard.evaluationDegraded",
      postureSource: "pages.dashboard.postureSource",
      postureAge: "pages.dashboard.postureAge",
      goalVerdict: "pages.dashboard.goalVerdict",
      goalMet: "pages.dashboard.goalMet",
      goalNotMet: "pages.dashboard.goalNotMet",
      defaultAliveGap: "pages.dashboard.defaultAliveGap",
      sourceAvailability: "pages.dashboard.sourceAvailability",
      rankReasonMissing: "pages.dashboard.rankReasonMissing",
      noCurrentRecords: "pages.dashboard.noCurrentRecords",
      unavailableSourcesCount: "pages.dashboard.unavailableSourcesCount",
    },
    offers: {
      title: "pages.offers.title",
      cardTitle: "pages.offers.cardTitle",
      description: "pages.offers.description",
      statusLabel: "pages.offers.statusLabel",
      offerLabel: "pages.offers.offerLabel",
      waitingOn: "pages.offers.waitingOn",
      legalTransitions: "pages.offers.legalTransitions",
      refusalReason: "pages.offers.refusalReason",
      refusalRemedy: "pages.offers.refusalRemedy",
      auditTrail: "pages.offers.auditTrail",
      promoteAction: "pages.offers.promoteAction",
      roleRequirement: "pages.offers.roleRequirement",
      membershipFinding: "pages.offers.membershipFinding",
      emptyGuidance: "pages.offers.emptyGuidance",
      createNodeTitle: "pages.offers.createNodeTitle",
      nodeKindLabel: "pages.offers.nodeKindLabel",
      nodeNameLabel: "pages.offers.nodeNameLabel",
      nodeStatusLabel: "pages.offers.nodeStatusLabel",
      nodeTriggerLabel: "pages.offers.nodeTriggerLabel",
      actualAccountLabel: "pages.offers.actualAccountLabel",
      createNodeAction: "pages.offers.createNodeAction",
      transitionTargetLabel: "pages.offers.transitionTargetLabel",
      transitionAction: "pages.offers.transitionAction",
      edgeTitle: "pages.offers.edgeTitle",
      edgeFromLabel: "pages.offers.edgeFromLabel",
      edgeToLabel: "pages.offers.edgeToLabel",
      edgeKindLabel: "pages.offers.edgeKindLabel",
      intendedPriceLabel: "pages.offers.intendedPriceLabel",
      currencyLabel: "pages.offers.currencyLabel",
      createEdgeAction: "pages.offers.createEdgeAction",
      savedNotice: "pages.offers.savedNotice",
      requestError: "pages.offers.requestError",
      candidateRequiresTrigger: "pages.offers.candidateRequiresTrigger",
      mergeTitle: "pages.offers.mergeTitle",
      mergeSurvivorLabel: "pages.offers.mergeSurvivorLabel",
      mergeDuplicateLabel: "pages.offers.mergeDuplicateLabel",
      mergePreviewAction: "pages.offers.mergePreviewAction",
      mergeApplyAction: "pages.offers.mergeApplyAction",
      mergeCancelAction: "pages.offers.mergeCancelAction",
      mergePreview: "pages.offers.mergePreview",
      mergeResult: "pages.offers.mergeResult",
      mergeDryRunNotice: "pages.offers.mergeDryRunNotice",
      findingLabel: "pages.offers.findingLabel",
      groupedViewTitle: "pages.offers.groupedViewTitle",
      groupedViewDescription: "pages.offers.groupedViewDescription",
      groupedKindCount: "pages.offers.groupedKindCount",
      groupedNodeCount: "pages.offers.groupedNodeCount",
      groupedRelationshipCount: "pages.offers.groupedRelationshipCount",
      groupedNoEdges: "pages.offers.groupedNoEdges",
      catalogViewGrouped: "pages.offers.catalogViewGrouped",
      catalogViewFlat: "pages.offers.catalogViewFlat",
      duplicateIdentityBanner: "pages.offers.duplicateIdentityBanner",
      catalogVerificationUnavailable: "pages.offers.catalogVerificationUnavailable",
      groupedEmptyGuidance: "pages.offers.groupedEmptyGuidance",
      edgeBelongsTo: "pages.offers.edgeBelongsTo",
      edgeSellsAt: "pages.offers.edgeSellsAt",
      edgeRequires: "pages.offers.edgeRequires",
      edgeFeeds: "pages.offers.edgeFeeds",
    },
    triggers: {
      title: "pages.triggers.title",
      cardTitle: "pages.triggers.cardTitle",
      description: "pages.triggers.description",
      parseReady: "pages.triggers.parseReady",
      parseError: "pages.triggers.parseError",
      parseErrorDetail: "pages.triggers.parseErrorDetail",
      dryRunAction: "pages.triggers.dryRunAction",
      dryRunVerdict: "pages.triggers.dryRunVerdict",
      factTrace: "pages.triggers.factTrace",
      missingFact: "pages.triggers.missingFact",
      factRegistry: "pages.triggers.factRegistry",
      evaluationFreshness: "pages.triggers.evaluationFreshness",
      stalledAlert: "pages.triggers.stalledAlert",
      emptyGuidance: "pages.triggers.emptyGuidance",
      nodeLabel: "pages.triggers.nodeLabel",
      factNameLabel: "pages.triggers.factNameLabel",
      operatorLabel: "pages.triggers.operatorLabel",
      thresholdLabel: "pages.triggers.thresholdLabel",
      compositionLabel: "pages.triggers.compositionLabel",
      declareAction: "pages.triggers.declareAction",
      factEntryTitle: "pages.triggers.factEntryTitle",
      factValueLabel: "pages.triggers.factValueLabel",
      observedAtLabel: "pages.triggers.observedAtLabel",
      staleAfterLabel: "pages.triggers.staleAfterLabel",
      dimensionLabel: "pages.triggers.dimensionLabel",
      addFactAction: "pages.triggers.addFactAction",
      savedNotice: "pages.triggers.savedNotice",
      requestError: "pages.triggers.requestError",
      verdictUnknown: "pages.triggers.verdictUnknown",
      verdictSatisfied: "pages.triggers.verdictSatisfied",
      verdictUnsatisfied: "pages.triggers.verdictUnsatisfied",
      factAge: "pages.triggers.factAge",
      noFacts: "pages.triggers.noFacts",
    },
    proposals: {
      title: "pages.proposals.title",
      cardTitle: "pages.proposals.cardTitle",
      description: "pages.proposals.description",
      tableCaption: "pages.proposals.tableCaption",
      proposer: "pages.proposals.proposer",
      requestedStatus: "pages.proposals.requestedStatus",
      reason: "pages.proposals.reason",
      evidence: "pages.proposals.evidence",
      age: "pages.proposals.age",
      effect: "pages.proposals.effect",
      declineHistory: "pages.proposals.declineHistory",
      noDeclines: "pages.proposals.noDeclines",
      actions: "pages.proposals.actions",
      acceptAction: "pages.proposals.acceptAction",
      declineAction: "pages.proposals.declineAction",
      declineReason: "pages.proposals.declineReason",
      declinePlaceholder: "pages.proposals.declinePlaceholder",
      declineNotice: "pages.proposals.declineNotice",
      acceptedNotice: "pages.proposals.acceptedNotice",
      operatorOnly: "pages.proposals.operatorOnly",
      roleUnavailable: "pages.proposals.roleUnavailable",
      emptyGuidance: "pages.proposals.emptyGuidance",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      ledgerConnected: "pages.settings.ledgerConnected",
      ledgerDisconnected: "pages.settings.ledgerDisconnected",
      ledgerConnectionReason: "pages.settings.ledgerConnectionReason",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  components: {
    asyncBoundary: {
      loadingContent: "components.asyncBoundary.loadingContent",
      loadingMoment: "components.asyncBoundary.loadingMoment",
    },
    chart: {
      kicker: "components.chart.kicker",
      valuesLabel: "components.chart.valuesLabel",
      caption: "components.chart.caption",
      period: "components.chart.period",
      value: "components.chart.value",
    },
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
