// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $rowKey: "$rowKey",
  $schema: "$schema",
  $text: "$text",
  "Changes saved successfully": {
    "": "Changes saved successfully.",
  },
  Collapse: "Collapse",
  "Content failed to load": {
    "": "Content failed to load.",
  },
  "Disabled states retain the same geometry and clearly communicate that the action is unavailable": {
    "": "Disabled states retain the same geometry and clearly communicate that the action is unavailable.",
  },
  M: "M",
  "Reconnect to refresh this view": {
    "": "Reconnect to refresh this view.",
  },
  "Request in progress": "Request in progress",
  Saved: "Saved",
  "Try again": "Try again",
  "Trying again…": "Trying again…",
  "Your changes are safe": {
    "": "Your changes are safe.",
  },
  app: {
    description: "app.description",
    title: "app.title",
  },
  "aria-label": "aria-label",
  ascending: "ascending",
  assertive: "assertive",
  asset: "asset",
  "border-app-primary bg-app-primary text-app-primary-foreground": "border-app-primary bg-app-primary text-app-primary-foreground",
  capability: "capability",
  caption: "caption",
  children: "children",
  clsx: "clsx",
  component: "component",
  components: {
    asyncBoundary: {
      loadingContent: "components.asyncBoundary.loadingContent",
      loadingMoment: "components.asyncBoundary.loadingMoment",
    },
    chart: {
      caption: "components.chart.caption",
      kicker: "components.chart.kicker",
      period: "components.chart.period",
      value: "components.chart.value",
      valuesLabel: "components.chart.valuesLabel",
    },
  },
  default: "default",
  defaultValue: "defaultValue",
  desc: "desc",
  description: "description",
  detail: "detail",
  dialog: "dialog",
  emptyMessage: "emptyMessage",
  en: "en",
  equals: "equals",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  example: "example",
  export: "export",
  feedback: {
    "async-boundary": {
      "loading-content": "feedback.async-boundary.loading-content",
      "this-may-take-a-moment": "feedback.async-boundary.this-may-take-a-moment",
    },
  },
  field: "field",
  fixture: "fixture",
  format: "format",
  forms: {
    "dirty-state-guard": {
      "leave-now-and-your-recent-edits-will-be-lost-sav": "forms.dirty-state-guard.leave-now-and-your-recent-edits-will-be-lost-sav",
      "saving-preserves-your-work-discarding-cannot-be-": "forms.dirty-state-guard.saving-preserves-your-work-discarding-cannot-be-",
      "you-have-unsaved-changes": "forms.dirty-state-guard.you-have-unsaved-changes",
    },
  },
  header: "header",
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    statusLabel: "health.statusLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  iconName: "iconName",
  id: "id",
  issue: "issue",
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      offers: "layout.nav.offers",
      settings: "layout.nav.settings",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  "lucide-react": "lucide-react",
  measured: "measured",
  mobile: "mobile",
  mode: "mode",
  module: "module",
  name: "name",
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  online: "online",
  pages: {
    dashboard: {
      actualUnavailable: "pages.dashboard.actualUnavailable",
      blockedOffers: "pages.dashboard.blockedOffers",
      boardActual: "pages.dashboard.boardActual",
      boardOffer: "pages.dashboard.boardOffer",
      boardStatus: "pages.dashboard.boardStatus",
      boardUnavailable: "pages.dashboard.boardUnavailable",
      defaultAliveGap: "pages.dashboard.defaultAliveGap",
      description: "pages.dashboard.description",
      earningNothing: "pages.dashboard.earningNothing",
      emptyGuidance: "pages.dashboard.emptyGuidance",
      evaluationAge: "pages.dashboard.evaluationAge",
      evaluationCondition: "pages.dashboard.evaluationCondition",
      evaluationDegraded: "pages.dashboard.evaluationDegraded",
      evaluationLastRun: "pages.dashboard.evaluationLastRun",
      evaluationNodesScored: "pages.dashboard.evaluationNodesScored",
      evaluationNotRun: "pages.dashboard.evaluationNotRun",
      firedTriggers: "pages.dashboard.firedTriggers",
      goalMet: "pages.dashboard.goalMet",
      goalNotMet: "pages.dashboard.goalNotMet",
      goalVerdict: "pages.dashboard.goalVerdict",
      ledgerPosture: "pages.dashboard.ledgerPosture",
      noCurrentRecords: "pages.dashboard.noCurrentRecords",
      offerRecords: "pages.dashboard.offerRecords",
      postureAge: "pages.dashboard.postureAge",
      postureBasis: "pages.dashboard.postureBasis",
      postureSource: "pages.dashboard.postureSource",
      postureUnavailable: "pages.dashboard.postureUnavailable",
      priorityBoard: "pages.dashboard.priorityBoard",
      rankReason: "pages.dashboard.rankReason",
      rankReasonActiveEarning: "pages.dashboard.rankReasonActiveEarning",
      rankReasonActiveEarningNothing: "pages.dashboard.rankReasonActiveEarningNothing",
      rankReasonActiveUnknown: "pages.dashboard.rankReasonActiveUnknown",
      rankReasonCandidate: "pages.dashboard.rankReasonCandidate",
      rankReasonIdea: "pages.dashboard.rankReasonIdea",
      rankReasonMissing: "pages.dashboard.rankReasonMissing",
      rankReasonProposed: "pages.dashboard.rankReasonProposed",
      rankReasonRetired: "pages.dashboard.rankReasonRetired",
      rankReasonShippedEarning: "pages.dashboard.rankReasonShippedEarning",
      rankReasonShippedEarningNothing: "pages.dashboard.rankReasonShippedEarningNothing",
      rankReasonShippedUnknown: "pages.dashboard.rankReasonShippedUnknown",
      rankReasonStatusNotSet: "pages.dashboard.rankReasonStatusNotSet",
      rankReasonTriggerMet: "pages.dashboard.rankReasonTriggerMet",
      rankReasonUnknown: "pages.dashboard.rankReasonUnknown",
      runwayMonths: "pages.dashboard.runwayMonths",
      sourceAvailability: "pages.dashboard.sourceAvailability",
      sourceUnavailable: "pages.dashboard.sourceUnavailable",
      sourceUnavailableReason: "pages.dashboard.sourceUnavailableReason",
      title: "pages.dashboard.title",
      unavailableSourcesCount: "pages.dashboard.unavailableSourcesCount",
    },
    offers: {
      actualAccountLabel: "pages.offers.actualAccountLabel",
      auditTrail: "pages.offers.auditTrail",
      candidateRequiresTrigger: "pages.offers.candidateRequiresTrigger",
      cardTitle: "pages.offers.cardTitle",
      catalogVerificationUnavailable: "pages.offers.catalogVerificationUnavailable",
      catalogViewFlat: "pages.offers.catalogViewFlat",
      catalogViewGrouped: "pages.offers.catalogViewGrouped",
      createEdgeAction: "pages.offers.createEdgeAction",
      createNodeAction: "pages.offers.createNodeAction",
      createNodeTitle: "pages.offers.createNodeTitle",
      currencyLabel: "pages.offers.currencyLabel",
      description: "pages.offers.description",
      duplicateIdentityBanner: "pages.offers.duplicateIdentityBanner",
      edgeBelongsTo: "pages.offers.edgeBelongsTo",
      edgeFeeds: "pages.offers.edgeFeeds",
      edgeFromLabel: "pages.offers.edgeFromLabel",
      edgeKindLabel: "pages.offers.edgeKindLabel",
      edgeRequires: "pages.offers.edgeRequires",
      edgeSellsAt: "pages.offers.edgeSellsAt",
      edgeTitle: "pages.offers.edgeTitle",
      edgeToLabel: "pages.offers.edgeToLabel",
      emptyGuidance: "pages.offers.emptyGuidance",
      findingLabel: "pages.offers.findingLabel",
      groupedEmptyGuidance: "pages.offers.groupedEmptyGuidance",
      groupedKindCount: "pages.offers.groupedKindCount",
      groupedNoEdges: "pages.offers.groupedNoEdges",
      groupedNodeCount: "pages.offers.groupedNodeCount",
      groupedRelationshipCount: "pages.offers.groupedRelationshipCount",
      groupedViewDescription: "pages.offers.groupedViewDescription",
      groupedViewTitle: "pages.offers.groupedViewTitle",
      intendedPriceLabel: "pages.offers.intendedPriceLabel",
      legalTransitions: "pages.offers.legalTransitions",
      membershipFinding: "pages.offers.membershipFinding",
      mergeApplyAction: "pages.offers.mergeApplyAction",
      mergeCancelAction: "pages.offers.mergeCancelAction",
      mergeDryRunNotice: "pages.offers.mergeDryRunNotice",
      mergeDuplicateLabel: "pages.offers.mergeDuplicateLabel",
      mergePreview: "pages.offers.mergePreview",
      mergePreviewAction: "pages.offers.mergePreviewAction",
      mergeResult: "pages.offers.mergeResult",
      mergeSurvivorLabel: "pages.offers.mergeSurvivorLabel",
      mergeTitle: "pages.offers.mergeTitle",
      nodeKindLabel: "pages.offers.nodeKindLabel",
      nodeNameLabel: "pages.offers.nodeNameLabel",
      nodeStatusLabel: "pages.offers.nodeStatusLabel",
      nodeTriggerLabel: "pages.offers.nodeTriggerLabel",
      offerLabel: "pages.offers.offerLabel",
      promoteAction: "pages.offers.promoteAction",
      refusalReason: "pages.offers.refusalReason",
      refusalRemedy: "pages.offers.refusalRemedy",
      requestError: "pages.offers.requestError",
      roleRequirement: "pages.offers.roleRequirement",
      savedNotice: "pages.offers.savedNotice",
      statusLabel: "pages.offers.statusLabel",
      title: "pages.offers.title",
      transitionAction: "pages.offers.transitionAction",
      transitionTargetLabel: "pages.offers.transitionTargetLabel",
      waitingOn: "pages.offers.waitingOn",
    },
    proposals: {
      acceptAction: "pages.proposals.acceptAction",
      acceptedNotice: "pages.proposals.acceptedNotice",
      actions: "pages.proposals.actions",
      age: "pages.proposals.age",
      cardTitle: "pages.proposals.cardTitle",
      declineAction: "pages.proposals.declineAction",
      declineHistory: "pages.proposals.declineHistory",
      declineNotice: "pages.proposals.declineNotice",
      declinePlaceholder: "pages.proposals.declinePlaceholder",
      declineReason: "pages.proposals.declineReason",
      description: "pages.proposals.description",
      effect: "pages.proposals.effect",
      emptyGuidance: "pages.proposals.emptyGuidance",
      evidence: "pages.proposals.evidence",
      noDeclines: "pages.proposals.noDeclines",
      operatorOnly: "pages.proposals.operatorOnly",
      proposer: "pages.proposals.proposer",
      reason: "pages.proposals.reason",
      requestedStatus: "pages.proposals.requestedStatus",
      roleUnavailable: "pages.proposals.roleUnavailable",
      tableCaption: "pages.proposals.tableCaption",
      title: "pages.proposals.title",
    },
    settings: {
      ledgerConnected: "pages.settings.ledgerConnected",
      ledgerConnectionReason: "pages.settings.ledgerConnectionReason",
      ledgerDisconnected: "pages.settings.ledgerDisconnected",
      localeHeading: "pages.settings.localeHeading",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
    triggers: {
      addFactAction: "pages.triggers.addFactAction",
      cardTitle: "pages.triggers.cardTitle",
      compositionLabel: "pages.triggers.compositionLabel",
      declareAction: "pages.triggers.declareAction",
      description: "pages.triggers.description",
      dimensionLabel: "pages.triggers.dimensionLabel",
      dryRunAction: "pages.triggers.dryRunAction",
      dryRunVerdict: "pages.triggers.dryRunVerdict",
      emptyGuidance: "pages.triggers.emptyGuidance",
      evaluationFreshness: "pages.triggers.evaluationFreshness",
      factAge: "pages.triggers.factAge",
      factEntryTitle: "pages.triggers.factEntryTitle",
      factNameLabel: "pages.triggers.factNameLabel",
      factRegistry: "pages.triggers.factRegistry",
      factTrace: "pages.triggers.factTrace",
      factValueLabel: "pages.triggers.factValueLabel",
      missingFact: "pages.triggers.missingFact",
      noFacts: "pages.triggers.noFacts",
      nodeLabel: "pages.triggers.nodeLabel",
      observedAtLabel: "pages.triggers.observedAtLabel",
      operatorLabel: "pages.triggers.operatorLabel",
      parseError: "pages.triggers.parseError",
      parseErrorDetail: "pages.triggers.parseErrorDetail",
      parseReady: "pages.triggers.parseReady",
      requestError: "pages.triggers.requestError",
      savedNotice: "pages.triggers.savedNotice",
      staleAfterLabel: "pages.triggers.staleAfterLabel",
      stalledAlert: "pages.triggers.stalledAlert",
      thresholdLabel: "pages.triggers.thresholdLabel",
      title: "pages.triggers.title",
      verdictSatisfied: "pages.triggers.verdictSatisfied",
      verdictUnknown: "pages.triggers.verdictUnknown",
      verdictUnsatisfied: "pages.triggers.verdictUnsatisfied",
    },
  },
  path: "path",
  placeholder: "placeholder",
  provenance: "provenance",
  purpose: "purpose",
  react: "react",
  "react-component-library:useEscapeKey": "react-component-library:useEscapeKey",
  reducedMotion: "reducedMotion",
  ref: "ref",
  region: "region",
  resolvedAt: "resolvedAt",
  role: "role",
  schema: "schema",
  schemaVersion: "schemaVersion",
  selector: "selector",
  size: "size",
  statement: "statement",
  status: "status",
  storyRef: "storyRef",
  "tailwind-merge": "tailwind-merge",
  testid: "testid",
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  tier: "tier",
  title: "title",
  tone: "tone",
  true: "true",
  type: "type",
  value: "value",
  variant: "variant",
  version: "version",
  visualization: {
    chart: {
      "chart-values": "visualization.chart.chart-values",
      "explore-the-trend-and-select-a-point-for-its-exa": "visualization.chart.explore-the-trend-and-select-a-point-for-its-exa",
      "performance-overview": "visualization.chart.performance-overview",
      period: "visualization.chart.period",
      value: "visualization.chart.value",
    },
  },
  "⌃": "⌃",
} as const;

export type Strings = typeof strings;
