#!/usr/bin/env bash
# Gazebo Resource Default Configuration

# Service ports
export GAZEBO_PORT="${GAZEBO_PORT:-11456}"
export GAZEBO_GRPC_PORT="${GAZEBO_GRPC_PORT:-11457}"
export GAZEBO_WS_PORT="${GAZEBO_WS_PORT:-11458}"

# Data directories
export GAZEBO_DATA_DIR="${GAZEBO_DATA_DIR:-${HOME}/.gazebo}"
export GAZEBO_LOG_DIR="${GAZEBO_LOG_DIR:-${GAZEBO_DATA_DIR}/logs}"
export GAZEBO_WORLDS_DIR="${GAZEBO_WORLDS_DIR:-${GAZEBO_DATA_DIR}/worlds}"
export GAZEBO_MODELS_DIR="${GAZEBO_MODELS_DIR:-${GAZEBO_DATA_DIR}/models}"
export GAZEBO_PLUGINS_DIR="${GAZEBO_PLUGINS_DIR:-${GAZEBO_DATA_DIR}/plugins}"

# Simulation settings
export GAZEBO_PHYSICS_ENGINE="${GAZEBO_PHYSICS_ENGINE:-dart}"
export GAZEBO_REAL_TIME_FACTOR="${GAZEBO_REAL_TIME_FACTOR:-1.0}"
export GAZEBO_MAX_STEP_SIZE="${GAZEBO_MAX_STEP_SIZE:-0.001}"
export GAZEBO_UPDATE_RATE="${GAZEBO_UPDATE_RATE:-1000}"

# Resource limits
export GAZEBO_MAX_MEMORY="${GAZEBO_MAX_MEMORY:-2G}"
export GAZEBO_MAX_CPU="${GAZEBO_MAX_CPU:-2}"
export GAZEBO_MAX_SIMULATIONS="${GAZEBO_MAX_SIMULATIONS:-5}"

# Rendering settings
export GAZEBO_HEADLESS="${GAZEBO_HEADLESS:-true}"
export GAZEBO_ENABLE_GPU="${GAZEBO_ENABLE_GPU:-false}"
export GAZEBO_RENDER_ENGINE="${GAZEBO_RENDER_ENGINE:-ogre2}"

# Network settings
export GAZEBO_ENABLE_DISTRIBUTED="${GAZEBO_ENABLE_DISTRIBUTED:-false}"
export GAZEBO_MASTER_URI="${GAZEBO_MASTER_URI:-http://localhost:${GAZEBO_PORT}}"

# Python API settings
export GAZEBO_PYTHON_VERSION="${GAZEBO_PYTHON_VERSION:-3.10}"
export GAZEBO_PYTHON_CONTEXT_SIZE="${GAZEBO_PYTHON_CONTEXT_SIZE:-256000}"

# Logging
export GAZEBO_LOG_LEVEL="${GAZEBO_LOG_LEVEL:-info}"
export GAZEBO_LOG_MAX_SIZE="${GAZEBO_LOG_MAX_SIZE:-100M}"
export GAZEBO_LOG_ROTATE="${GAZEBO_LOG_ROTATE:-7}"

# Timeouts
export GAZEBO_STARTUP_TIMEOUT="${GAZEBO_STARTUP_TIMEOUT:-60}"
export GAZEBO_SHUTDOWN_TIMEOUT="${GAZEBO_SHUTDOWN_TIMEOUT:-30}"
export GAZEBO_HEALTH_CHECK_TIMEOUT="${GAZEBO_HEALTH_CHECK_TIMEOUT:-5}"

# Integration settings
export GAZEBO_ENABLE_ROS2="${GAZEBO_ENABLE_ROS2:-false}"
export GAZEBO_ROS2_DOMAIN_ID="${GAZEBO_ROS2_DOMAIN_ID:-0}"

# Debug settings
export GAZEBO_DEBUG="${GAZEBO_DEBUG:-false}"
export GAZEBO_VERBOSE="${GAZEBO_VERBOSE:-false}"