// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      transfer: "layout.nav.transfer",
      devices: "layout.nav.devices",
      settings: "layout.nav.settings",
    },
    mainLabel: "layout.mainLabel",
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  realtime: {
    label: "realtime.label",
    connecting: "realtime.connecting",
    open: "realtime.open",
    closed: "realtime.closed",
  },
  pages: {
    devices: {
      title: "pages.devices.title",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      ownerHeading: "pages.settings.ownerHeading",
      sessionHeading: "pages.settings.sessionHeading",
      statusHeading: "pages.settings.statusHeading",
    },
  },
  join: {
    title: "join.title",
    intro: "join.intro",
    codeLabel: "join.codeLabel",
    codePlaceholder: "join.codePlaceholder",
    redeem: "join.redeem",
    deviceNameLabel: "join.deviceNameLabel",
    deviceNamePlaceholder: "join.deviceNamePlaceholder",
    requestTitle: "join.requestTitle",
    requestIntro: "join.requestIntro",
    request: "join.request",
    waitingTitle: "join.waitingTitle",
    waitingIntro: "join.waitingIntro",
    waitingOwnerAction: "join.waitingOwnerAction",
    approveThisDevice: "join.approveThisDevice",
    missingCode: "join.missingCode",
    missingName: "join.missingName",
  },
  transfer: {
    receive: {
      heading: "transfer.receive.heading",
      description: "transfer.receive.description",
      loading: "transfer.receive.loading",
      empty: "transfer.receive.empty",
      searchLabel: "transfer.receive.searchLabel",
      searchPlaceholder: "transfer.receive.searchPlaceholder",
      sortLabel: "transfer.receive.sortLabel",
      sortNewest: "transfer.receive.sortNewest",
      sortName: "transfer.receive.sortName",
      sortSize: "transfer.receive.sortSize",
      filterLabel: "transfer.receive.filterLabel",
      filterAll: "transfer.receive.filterAll",
      filterFile: "transfer.receive.filterFile",
      filterText: "transfer.receive.filterText",
      viewCards: "transfer.receive.viewCards",
      viewList: "transfer.receive.viewList",
      download: "transfer.receive.download",
      copy: "transfer.receive.copy",
      copied: "transfer.receive.copied",
      remove: "transfer.receive.remove",
      expiresLabel: "transfer.receive.expiresLabel",
      relayStored: "transfer.receive.relayStored",
      audienceAll: "transfer.receive.audienceAll",
      audienceDirect: "transfer.receive.audienceDirect",
      retentionDetail: "transfer.receive.retentionDetail",
    },
    retention: {
      live: "transfer.retention.live",
      held: "transfer.retention.held",
      pinned: "transfer.retention.pinned",
    },
    send: {
      heading: "transfer.send.heading",
      description: "transfer.send.description",
      dropHint: "transfer.send.dropHint",
      browse: "transfer.send.browse",
      fileInputLabel: "transfer.send.fileInputLabel",
      textLabel: "transfer.send.textLabel",
      textPlaceholder: "transfer.send.textPlaceholder",
      addText: "transfer.send.addText",
      stagedHeading: "transfer.send.stagedHeading",
      stagedEmpty: "transfer.send.stagedEmpty",
      retentionLabel: "transfer.send.retentionLabel",
      targetLabel: "transfer.send.targetLabel",
      targetBroadcast: "transfer.send.targetBroadcast",
      removeStaged: "transfer.send.removeStaged",
      send: "transfer.send.send",
      send_other: "transfer.send.send_other",
      sending: "transfer.send.sending",
      sent: "transfer.send.sent",
      needText: "transfer.send.needText",
    },
  },
  devices: {
    loading: "devices.loading",
    empty: "devices.empty",
    signInPrompt: "devices.signInPrompt",
    onlineLabel: "devices.onlineLabel",
    offlineLabel: "devices.offlineLabel",
    trust: {
      pending: "devices.trust.pending",
      trusted: "devices.trust.trusted",
      revoked: "devices.trust.revoked",
      unspecified: "devices.trust.unspecified",
    },
    rename: "devices.rename",
    renameLabel: "devices.renameLabel",
    renameSave: "devices.renameSave",
    revoke: "devices.revoke",
    revokeConfirm: "devices.revokeConfirm",
    approve: "devices.approve",
    issue: {
      heading: "devices.issue.heading",
      description: "devices.issue.description",
      deviceNameLabel: "devices.issue.deviceNameLabel",
      deviceNamePlaceholder: "devices.issue.deviceNamePlaceholder",
      issue: "devices.issue.issue",
      codeHeading: "devices.issue.codeHeading",
      codeHint: "devices.issue.codeHint",
      expiresLabel: "devices.issue.expiresLabel",
      qrLabel: "devices.issue.qrLabel",
    },
    pendingBanner: {
      title: "devices.pendingBanner.title",
      subtitle: "devices.pendingBanner.subtitle",
      approve: "devices.pendingBanner.approve",
      dismiss: "devices.pendingBanner.dismiss",
    },
  },
  owner: {
    intro: "owner.intro",
    signedIn: "owner.signedIn",
    signOut: "owner.signOut",
  },
  onboarding: {
    welcomeTitle: "onboarding.welcomeTitle",
    welcomeIntro: "onboarding.welcomeIntro",
    setupTitle: "onboarding.setupTitle",
    setupDescription: "onboarding.setupDescription",
    joinTitle: "onboarding.joinTitle",
    joinDescription: "onboarding.joinDescription",
    back: "onboarding.back",
  },
  login: {
    title: "login.title",
    intro: "login.intro",
    tabSignIn: "login.tabSignIn",
    tabCreate: "login.tabCreate",
    emailLabel: "login.emailLabel",
    emailPlaceholder: "login.emailPlaceholder",
    passwordLabel: "login.passwordLabel",
    passwordPlaceholder: "login.passwordPlaceholder",
    submit: "login.submit",
    submitting: "login.submitting",
    missingFields: "login.missingFields",
    invalidCredentials: "login.invalidCredentials",
    unavailable: "login.unavailable",
  },
  register: {
    usernameLabel: "register.usernameLabel",
    usernamePlaceholder: "register.usernamePlaceholder",
    submit: "register.submit",
    submitting: "register.submitting",
    emailTaken: "register.emailTaken",
    invalidInput: "register.invalidInput",
  },
  setupDevice: {
    title: "setupDevice.title",
    intro: "setupDevice.intro",
    signedInAs: "setupDevice.signedInAs",
    deviceNameLabel: "setupDevice.deviceNameLabel",
    deviceNamePlaceholder: "setupDevice.deviceNamePlaceholder",
    submit: "setupDevice.submit",
    submitting: "setupDevice.submitting",
    alreadyOwned: "setupDevice.alreadyOwned",
    signInExpired: "setupDevice.signInExpired",
    joinInstead: "setupDevice.joinInstead",
    signOut: "setupDevice.signOut",
  },
  session: {
    tokenPresent: "session.tokenPresent",
    signOut: "session.signOut",
    notPaired: "session.notPaired",
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
