import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {cleanup,fireEvent,screen,waitFor,within} from "@testing-library/react";
import {getSpatialNav} from "@vrooli/iframe-bridge/spatial";
import {BacklogDetailsPanel} from "./backlog-details-panel";
import {defaultApiClient} from "../../lib/api-client";
import {renderWithProviders,createTestQueryClient} from "../../test-utils";
import type {BacklogItem} from "../../types";
const base:BacklogItem={kind:"idea",name:"fixture-item",title:"Fixture item",description:"Owner specification",status:"backlog",priority:1,tags:[],suggestedSkills:[],created:"2026-01-01T00:00:00Z",updated:"2026-01-01T00:00:00Z"};
let goals:unknown[]=[];const clients:ReturnType<typeof createTestQueryClient>[]=[];
function mount(item:BacklogItem=base,locked=false){const edit=vi.fn(),saveNote=vi.fn(),saveDescription=vi.fn(),dep=vi.fn();const client=createTestQueryClient();clients.push(client);renderWithProviders(<BacklogDetailsPanel item={item} depRelations={{parents:[],children:[]}} spawnedItems={[]} isLocked={locked} onEditGlobs={edit} onDepStatusChange={dep} onSaveNote={saveNote} onSaveDescription={saveDescription} isSavingDescription={false}/>,{queryClient:client});return{edit,saveNote,saveDescription,dep};}
beforeEach(()=>{goals=[];vi.spyOn(defaultApiClient,"get").mockImplementation(async path=>{expect(path).toBe("/goals");return {items:goals} as never;});for(const m of ["post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,m).mockRejectedValue(new Error("Unexpected owner write"));vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("Unexpected transport")));});
afterEach(()=>{cleanup();getSpatialNav()?.dispose();try{for(const[path]of vi.mocked(defaultApiClient.get).mock.calls)expect(path).toBe("/goals");for(const m of ["post","put","patch","delete"]as const)expect(defaultApiClient[m]).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();}finally{clients.splice(0).forEach(c=>c.clear());vi.restoreAllMocks();vi.unstubAllGlobals();}});
describe("actual backlog metadata local owner controls",()=>{
 it("expands and collapses a long owner description without opening an editor",async()=>{const v=mount({...base,description:"Owner context ".repeat(15)});fireEvent.click(await screen.findByRole("button",{name:"Show more…"}));expect(screen.getByRole("button",{name:"Show less"})).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Show less"}));expect(screen.getByRole("button",{name:"Show more…"})).toBeVisible();expect(v.saveDescription).not.toHaveBeenCalled();});
 it.each(["acceptanceAllow","acceptanceDeny"]as const)("reveals all %s patterns and collapses them without editing the owner",async field=>{const v=mount({...base,[field]:["first/**","second/**","third/**","fourth/**","fifth/**"]});expect(screen.queryByText("fourth/**")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Show more… (2 more)"}));expect(screen.getByText("fourth/**")).toBeVisible();expect(screen.getByText("fifth/**")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Show less"}));expect(screen.queryByText("fourth/**")).toBeNull();expect(v.edit).not.toHaveBeenCalled();});
 it("offers the explicit empty-pattern edit callback only for an unlocked owner",()=>{const v=mount();fireEvent.click(screen.getByTestId("acceptance-globs-empty-state"));expect(v.edit).toHaveBeenCalledOnce();expect(v.saveDescription).not.toHaveBeenCalled();});
 it("keeps the empty-pattern affordance inert for a locked owner",()=>{const v=mount(base,true);expect(screen.getByTestId("acceptance-globs-empty-state")).toBeDisabled();fireEvent.click(screen.getByTestId("acceptance-globs-empty-state"));expect(v.edit).not.toHaveBeenCalled();expect(screen.queryByRole("button",{name:"Edit description"})).toBeNull();});
 it("cancels actual goal selection with no membership write",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Attach goal"}));const dialog=await screen.findByRole("dialog",{name:"Attach to goal"});fireEvent.click(within(dialog).getAllByRole("button",{name:"Close drawer"})[0]!);await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Attach to goal"})).toBeNull());});
 it("cancels exact goal detachment without changing membership or posting",async()=>{goals=[{goal:{name:"fixture-goal",title:"Fixture goal",targets:["idea/fixture-item"],status:"active",priority:1},scope:{targets:["idea/fixture-item"],closure:[],completed:[],ready:[],blocked:[],total:1}}];mount();fireEvent.click(await screen.findByRole("button",{name:"Detach from Fixture goal"}));const dialog=await screen.findByRole("dialog",{name:"Detach from goal"});fireEvent.click(within(dialog).getByRole("button",{name:"Cancel"}));await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Detach from goal"})).toBeNull());expect(screen.getByRole("button",{name:"Detach from Fixture goal"})).toBeVisible();});
});
