// Synthetic review evidence at the component callback boundary only. No provider
// verification, actual review disposition, Planner acceptance or server writes.
import { useState } from "react";
import { fireEvent, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import { renderWithProviders } from "../../test-utils";
import { defaultApiClient } from "../../lib/api-client";
import type { ReviewRound, EvidenceItem } from "../../services/review-service";
import { EvidencePanel } from "./evidence-panel";
const views:ReturnType<typeof renderWithProviders>[]=[];
let verify:ReturnType<typeof vi.fn>;let request:ReturnType<typeof vi.fn>;let expectedVerify:unknown[][];let expectedRequest:unknown[][];
function evidence(id:string,verified=false):EvidenceItem{return{id,type:"custom",title:`Fixture ${id}`,description:`Synthetic description ${id}`,verified};}
function round(number:number,overrides:Partial<ReviewRound>={}):ReviewRound{return{round:number,generated_at:"2026-10-06T00:00:00Z",execution_id:`fixture-execution-${number}`,status:"complete",classification:"ready",agent_assessment:`Assessment ${number}`,evidence:[evidence(`evidence-${number}`)],...overrides};}
function Harness({initial, gathering=false, awaiting=false}:{initial:ReviewRound[];gathering?:boolean;awaiting?:boolean}){const[rounds,setRounds]=useState(initial);return <EvidencePanel rounds={rounds} backlogKind="fix" backlogName="fixture-only" isGathering={gathering} isAwaitingManualReview={awaiting} onVerify={(number,id,checked)=>{verify(number,id,checked);setRounds(current=>current.map(r=>r.round===number?{...r,evidence:r.evidence.map(e=>e.id===id?{...e,verified:checked}:e)}:r));}} onRequestMore={request}/>;}
function mount(initial:ReviewRound[],options:{gathering?:boolean;awaiting?:boolean}={}){const view=renderWithProviders(<Harness initial={initial} {...options}/>);views.push(view);return view;}
function header(number:number){return screen.getByRole("button",{name:new RegExp(`Round ${number} `)});}
beforeEach(()=>{verify=vi.fn();request=vi.fn();expectedVerify=[];expectedRequest=[];for(const method of ["get","post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error(`Forbidden evidence ${method}`));vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("Forbidden evidence direct transport")));});
afterEach(()=>{views.splice(0).forEach(v=>v.unmount());getSpatialNav()?.dispose();try{expect(verify.mock.calls).toEqual(expectedVerify);expect(request.mock.calls).toEqual(expectedRequest);for(const method of ["get","post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();}finally{vi.restoreAllMocks();vi.unstubAllGlobals();}});
describe("evidence round history local controls",()=>{
 it("starts at the latest owner round, expands historical detail, and collapses it without offering verification",()=>{mount([round(1),round(2)]);expect(screen.getAllByTestId("evidence-agent-assessment")).toHaveLength(1);expect(screen.getByText("Fixture evidence-2")).toBeVisible();expect(screen.queryByText("Fixture evidence-1")).toBeNull();fireEvent.click(header(1));expect(screen.getByText("Fixture evidence-1")).toBeVisible();expect(screen.getAllByTestId("evidence-agent-assessment")).toHaveLength(2);fireEvent.click(header(1));expect(screen.queryByText("Fixture evidence-1")).toBeNull();expect(screen.getByText("Fixture evidence-2")).toBeVisible();});
 it("renders an actual failed owner reason and assessment notes without declaring readiness",()=>{mount([round(3,{status:"failed",classification:"needs_work",failure_reason:"Fixture owner could not qualify evidence",notes:["Fixture constraint remains"],evidence:[]})]);expect(screen.getByText("Review Failure")).toBeVisible();expect(screen.getByText("Fixture owner could not qualify evidence")).toBeVisible();expect(screen.getByText("Fixture constraint remains")).toBeVisible();expect(screen.queryByText("Ready")).toBeNull();});
 it("offers only the latest round number to the local Request More callback",()=>{mount([round(1),round(4)]);expectedRequest=[[4]];fireEvent.click(screen.getByRole("button",{name:"Request More"}));});
 it.each([{gathering:true},{awaiting:true}])("preserves an explicit current-round request intent and actual status copy while evidence is busy (%j)",options=>{mount([round(2,{status:"gathering",current_run_status:options.awaiting?"needs_review":undefined})],options);expect(screen.getByText(options.awaiting?"Awaiting manual review...":"Gathering evidence...")).toBeVisible();expect(request).not.toHaveBeenCalled();expectedRequest=[[2]];fireEvent.click(screen.getByRole("button",{name:"Request More"}));});
 it("marks all evidence in the exact expanded round then allows explicitly unreviewing the same items",()=>{mount([round(2,{evidence:[evidence("fixture-a"),evidence("fixture-b",true)]})]);const all=screen.getByTestId("evidence-mark-all-reviewed");expect(all).not.toBeChecked();expectedVerify=[[2,"fixture-a",true],[2,"fixture-b",true]];fireEvent.click(all);expect(all).toBeChecked();expect(screen.queryByText("1 unreviewed")).toBeNull();expectedVerify.push([2,"fixture-a",false],[2,"fixture-b",false]);fireEvent.click(all);expect(all).not.toBeChecked();expect(screen.getAllByText(/2 unreviewed/).length).toBeGreaterThan(0);});
 it("keeps an individual review intent bound to its exact historical round and synthetic item",()=>{mount([round(1),round(2)]);fireEvent.click(header(1));const boxes=screen.getAllByTestId("evidence-review-checkbox");expect(boxes).toHaveLength(2);expectedVerify=[[1,"evidence-1",true]];fireEvent.click(boxes[1]!);expect(boxes[1]!).toBeChecked();expect(boxes[0]!).not.toBeChecked();expectedVerify.push([1,"evidence-1",false]);fireEvent.click(boxes[1]!);expect(boxes[1]!).not.toBeChecked();});
 it("preserves an unfamiliar owner classification as an explicit label rather than promoting it to Ready",()=>{mount([round(5,{classification:"fixture-unclassified",agent_assessment:"Owner pending interpretation"})]);expect(screen.getAllByText("fixture-unclassified").length).toBeGreaterThan(0);expect(screen.queryByText("Ready")).toBeNull();expect(within(screen.getByTestId("evidence-agent-assessment")).getByText("Owner pending interpretation")).toBeVisible();});
 it("keeps empty evidence distinct from a gathering round without inventing an assessment",()=>{mount([]);expect(screen.getByText("No evidence gathered yet")).toBeVisible();expect(screen.queryByTestId("evidence-agent-assessment")).toBeNull();expect(screen.queryByRole("button",{name:"Request More"})).toBeNull();});
});
