// Real panel, recursive rows, review cards and selection store. Callback replies
// belong to a disposable local harness and confer no installed review authority.
import { useState, type ComponentProps } from "react";
import { cleanup, fireEvent, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { renderWithProviders } from "../../test-utils";
import { OperationalTargetsPanel } from "./operational-targets-panel";
import { useBacklogDetailUIStore } from "../../stores/backlog-detail-ui-store";
import type { ArchiveTarget, ArchiveRequirement, ArchiveRequirementGroup, ReviewAction } from "../../types";
const target:ArchiveTarget={id:"TARGET-A",criticality:"P0",title:"Target A",notes:"Exact target note",status:"pending",linked_requirement_ids:["REQ-A"]};
const req:ArchiveRequirement={id:"REQ-A",title:"Requirement A",description:"Exact authored requirement",status:"pending",category:"fixture",prd_ref:"fixture-prd"};
const group:ArchiveRequirementGroup={id:"MODULE-A",name:"Module A",requirements:[req,{...req,id:"REQ-B",title:"Requirement B"}],children:[{id:"MODULE-CHILD",name:"Child module",requirements:[{...req,id:"REQ-C",title:"Child requirement"}],children:[]}]};
type Props=ComponentProps<typeof OperationalTargetsPanel>;
let callbacks:{createTarget:ReturnType<typeof vi.fn>;editTarget:ReturnType<typeof vi.fn>;deleteTarget:ReturnType<typeof vi.fn>;createModule:ReturnType<typeof vi.fn>;editModule:ReturnType<typeof vi.fn>;deleteModule:ReturnType<typeof vi.fn>;createReq:ReturnType<typeof vi.fn>;editReq:ReturnType<typeof vi.fn>;deleteReq:ReturnType<typeof vi.fn>;reorderReq:ReturnType<typeof vi.fn>;review:ReturnType<typeof vi.fn>};let fetch:ReturnType<typeof vi.fn>;
function Harness({targets=[target],requirements=[group],...rest}:Partial<Props>){const[ts,setTs]=useState(targets);const[rs,setRs]=useState(requirements);const review=(id:string,type:"target"|"requirement",action:ReviewAction)=>{callbacks.review(id,type,action);if(type==="target")setTs(old=>old.map(t=>t.id===id?{...t,...action}:t));else{const update=(g:ArchiveRequirementGroup):ArchiveRequirementGroup=>({...g,requirements:g.requirements.map(r=>r.id===id?{...r,...action}:r),children:g.children.map(update)});setRs(old=>old.map(update));}};return <OperationalTargetsPanel targets={ts} requirements={rs} editable onCreateTarget={callbacks.createTarget} onEditTarget={callbacks.editTarget} onDeleteTarget={callbacks.deleteTarget} onCreateModule={callbacks.createModule} onEditModule={callbacks.editModule} onDeleteModule={callbacks.deleteModule} onCreateRequirement={callbacks.createReq} onEditRequirement={callbacks.editReq} onDeleteRequirement={callbacks.deleteReq} onReorderRequirement={callbacks.reorderReq} onReviewAction={review} {...rest}/>;}
function card(title:string){const element=screen.getByText(title).closest("div.rounded-md");expect(element).not.toBeNull();return within(element as HTMLElement);}
beforeEach(()=>{useBacklogDetailUIStore.getState().reset();callbacks={createTarget:vi.fn(),editTarget:vi.fn(),deleteTarget:vi.fn(),createModule:vi.fn(),editModule:vi.fn(),deleteModule:vi.fn(),createReq:vi.fn(),editReq:vi.fn(),deleteReq:vi.fn(),reorderReq:vi.fn(),review:vi.fn()};fetch=vi.fn(async()=>{throw new Error("Unexpected network request from local panel")});vi.stubGlobal("fetch",fetch);});
afterEach(()=>{cleanup();expect(fetch).not.toHaveBeenCalled();useBacklogDetailUIStore.getState().reset();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe("operational target and requirement local workflows",()=>{
 it("renders nothing for an empty read-only archive",()=>{const{container}=renderWithProviders(<OperationalTargetsPanel targets={[]} requirements={[]}/>);expect(container).toBeEmptyDOMElement();});
 it("offers explicit creation callbacks for an empty editable archive",()=>{renderWithProviders(<Harness targets={[]} requirements={[]}/>);fireEvent.click(screen.getByRole("button",{name:"Add Target"}));fireEvent.click(screen.getByRole("button",{name:"Add Module"}));expect(callbacks.createTarget).toHaveBeenCalledTimes(1);expect(callbacks.createModule).toHaveBeenCalledTimes(1);expect(callbacks.review).not.toHaveBeenCalled();});
 it("shows criticality groups in documented order with exact notes and linked requirements",()=>{renderWithProviders(<Harness targets={[{...target,id:"TARGET-C",criticality:"P2",title:"Target C"},{...target,id:"TARGET-B",criticality:"P1",title:"Target B"},target]} requirements={[]}/>);const titles=screen.getAllByText(/^Target [ABC]$/);expect(titles.map(e=>e.textContent)).toEqual(["Target A","Target B","Target C"]);expect(screen.getAllByText("Exact target note")).toHaveLength(3);expect(screen.getByText("P0 – Must ship")).toBeVisible();expect(screen.getByText("P1 – Should have")).toBeVisible();expect(screen.getByText("P2 – Future")).toBeVisible();});
 it("keeps an unfamiliar criticality visible in the Other group rather than silently hiding its target",()=>{renderWithProviders(<Harness targets={[{...target,id:"TARGET-FUTURE",criticality:"P3",title:"Future target"}]} requirements={[]}/>);expect(screen.getByText("Future target")).toBeVisible();expect(screen.getByText("Other")).toBeVisible();});
 it("toggles only the selected target through the actual transient store",()=>{renderWithProviders(<Harness requirements={[]}/>);const row=screen.getByRole("button",{name:/TARGET-A.*Target A/});fireEvent.click(row);expect([...useBacklogDetailUIStore.getState().selectedTargetIds]).toEqual(["TARGET-A"]);expect(within(row).getByRole("checkbox")).toBeChecked();fireEvent.click(row);expect(useBacklogDetailUIStore.getState().selectedTargetIds.size).toBe(0);expect(callbacks.review).not.toHaveBeenCalled();});
 it("selects direct requirements and expands a nested module before selecting its exact child",()=>{renderWithProviders(<Harness targets={[]}/>);fireEvent.click(screen.getByRole("button",{name:/REQ-A.*Requirement A/}));expect([...useBacklogDetailUIStore.getState().selectedRequirementIds]).toEqual(["REQ-A"]);expect(screen.queryByText("Child requirement")).toBeNull();fireEvent.click(screen.getByRole("button",{name:/Child module/}));fireEvent.click(screen.getByRole("button",{name:/REQ-C.*Child requirement/}));expect([...useBacklogDetailUIStore.getState().selectedRequirementIds]).toEqual(["REQ-A","REQ-C"]);expect(callbacks.review).not.toHaveBeenCalled();});
 it("collapses and reopens each section without losing selected identity or authoring a review",()=>{renderWithProviders(<Harness/>);fireEvent.click(screen.getByRole("button",{name:/TARGET-A.*Target A/}));fireEvent.click(screen.getByRole("button",{name:/Operational Targets/}));expect(screen.queryByText("Target A")).toBeNull();fireEvent.click(screen.getByRole("button",{name:/Requirements/}));expect(screen.queryByText("Requirement A")).toBeNull();fireEvent.click(screen.getByRole("button",{name:/Operational Targets/}));fireEvent.click(screen.getByRole("button",{name:/Requirements/}));expect(screen.getByText("Target A")).toBeVisible();expect(screen.getByText("Requirement A")).toBeVisible();expect([...useBacklogDetailUIStore.getState().selectedTargetIds]).toEqual(["TARGET-A"]);expect(callbacks.review).not.toHaveBeenCalled();});
 it("sends module authoring callbacks with only the exact selected group identity",()=>{renderWithProviders(<Harness targets={[]}/>);const adds=screen.getAllByTitle("Add Requirement");fireEvent.click(adds[0]!);fireEvent.click(screen.getAllByTitle("Edit Module")[0]!);fireEvent.click(screen.getAllByTitle("Delete Module")[0]!);expect(callbacks.createReq).toHaveBeenCalledWith("MODULE-A");expect(callbacks.editModule).toHaveBeenCalledWith("MODULE-A");expect(callbacks.deleteModule).toHaveBeenCalledWith("MODULE-A");expect(callbacks.review).not.toHaveBeenCalled();});
 it("enters actual review mode and removes ordinary create controls until exiting",()=>{renderWithProviders(<Harness/>);fireEvent.click(screen.getByRole("button",{name:"Review"}));expect(useBacklogDetailUIStore.getState().reviewMode).toBe(true);expect(card("Target A").getByRole("button",{name:"Approve"})).toBeVisible();expect(screen.queryByRole("button",{name:"Add Target"})).toBeNull();expect(screen.queryByRole("button",{name:"Add Module"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Review"}));expect(useBacklogDetailUIStore.getState().reviewMode).toBe(false);expect(screen.getByRole("button",{name:"Add Target"})).toBeVisible();expect(callbacks.review).not.toHaveBeenCalled();});
 it("routes approved and reset target review to the exact typed local callback",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<Harness requirements={[]}/>);fireEvent.click(card("Target A").getByRole("button",{name:"Approve"}));expect(callbacks.review.mock.calls).toEqual([["TARGET-A","target",{review_status:"approved"}]]);expect(card("Target A").getByText("Approved")).toBeVisible();fireEvent.click(card("Target A").getByRole("button",{name:"Reset"}));expect(callbacks.review.mock.calls[1]).toEqual(["TARGET-A","target",{review_status:"unreviewed"}]);expect(card("Target A").getByText("Unreviewed")).toBeVisible();});
 it("retains exact target flag comments and clears them on an authored reset",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<Harness requirements={[]}/>);fireEvent.click(card("Target A").getByRole("button",{name:"Flag"}));const comment=card("Target A").getByRole("textbox");fireEvent.change(comment,{target:{value:"Fixture evidence missing"}});expect(callbacks.review.mock.calls).toEqual([["TARGET-A","target",{review_status:"flagged",review_comment:""}],["TARGET-A","target",{review_status:"flagged",review_comment:"Fixture evidence missing"}]]);expect(comment).toHaveValue("Fixture evidence missing");fireEvent.click(card("Target A").getByRole("button",{name:"Reset"}));expect(card("Target A").queryByRole("textbox")).toBeNull();});
 it("reviews a direct requirement and a nested child with their exact typed identities",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<Harness targets={[]}/>);fireEvent.click(card("Requirement A").getByRole("button",{name:"Approve"}));fireEvent.click(card("Requirement B").getByRole("button",{name:"Flag"}));fireEvent.change(card("Requirement B").getByRole("textbox"),{target:{value:"Fixture rationale"}});fireEvent.click(screen.getByRole("button",{name:/Child module/}));fireEvent.click(card("Child requirement").getByRole("button",{name:"Approve"}));expect(callbacks.review.mock.calls).toEqual([["REQ-A","requirement",{review_status:"approved"}],["REQ-B","requirement",{review_status:"flagged",review_comment:""}],["REQ-B","requirement",{review_status:"flagged",review_comment:"Fixture rationale"}],["REQ-C","requirement",{review_status:"approved"}]]);});
 it("provides target edit/remove callbacks only for the exact rendered target",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<Harness requirements={[]}/>);fireEvent.click(card("Target A").getByTitle("Edit"));fireEvent.click(card("Target A").getByTitle("Remove"));expect(callbacks.editTarget).toHaveBeenCalledWith(target);expect(callbacks.deleteTarget).toHaveBeenCalledWith("TARGET-A");expect(callbacks.review).not.toHaveBeenCalled();});
 it("provides direct and nested requirement edit/remove identities with their owning module",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<Harness targets={[]}/>);fireEvent.click(card("Requirement A").getByTitle("Edit"));fireEvent.click(card("Requirement A").getByTitle("Remove"));fireEvent.click(screen.getByRole("button",{name:/Child module/}));fireEvent.click(card("Child requirement").getByTitle("Edit"));fireEvent.click(card("Child requirement").getByTitle("Remove"));expect(callbacks.editReq.mock.calls).toEqual([["MODULE-A",req],["MODULE-CHILD",group.children[0]!.requirements[0]]]);expect(callbacks.deleteReq.mock.calls).toEqual([["MODULE-A","REQ-A"],["MODULE-CHILD","REQ-C"]]);});
 it("disables review actions while saving and preserves the exact visible failure",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<Harness reviewSaving reviewError="Exact fixture review refusal"/>);for(const button of screen.getAllByRole("button",{name:/^(Approve|Flag)$/})){expect(button).toBeDisabled();fireEvent.click(button);}expect(callbacks.review).not.toHaveBeenCalled();expect(screen.getByText("Review failed: Exact fixture review refusal")).toBeVisible();expect(card("Target A").getByText("Exact fixture review refusal")).toBeVisible();});
 it("displays authoritative reviewed/flagged summaries without invoking callbacks",()=>{renderWithProviders(<Harness targets={[{...target,review_status:"flagged",review_comment:"Authoritative target comment"}]} requirements={[{...group,requirements:[{...req,review_status:"approved"}],children:[]}]}/>);expect(screen.getByText("Target A")).toBeVisible();expect(screen.getByText("Requirement A")).toBeVisible();expect(screen.getAllByText(/reviewed/).length).toBeGreaterThan(0);expect(callbacks.review).not.toHaveBeenCalled();});
 it("keeps an empty nested read-only module out of the rendered archive",()=>{renderWithProviders(<OperationalTargetsPanel targets={[]} requirements={[{id:"EMPTY",name:"Empty module",requirements:[],children:[]}]}/>);expect(screen.queryByText("Empty module")).toBeNull();});
 it("renders an empty editable module so its own add-requirement action remains reachable",()=>{renderWithProviders(<Harness targets={[]} requirements={[{id:"EMPTY",name:"Empty module",requirements:[],children:[]}]}/>);expect(screen.getByRole("button",{name:/Empty module/})).toBeVisible();fireEvent.click(screen.getByTitle("Add Requirement"));expect(callbacks.createReq).toHaveBeenCalledWith("EMPTY");});
 it("preserves optional-handler editing compatibility in review mode with exact target and reorder identities",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<Harness onReviewAction={undefined}/>);fireEvent.click(screen.getByTitle("Edit Target"));fireEvent.click(screen.getByTitle("Delete Target"));fireEvent.click(screen.getAllByTitle("Edit")[0]!);fireEvent.click(screen.getAllByTitle("Delete")[0]!);fireEvent.click(screen.getByTitle("Move Down"));fireEvent.click(screen.getByTitle("Move Up"));expect(callbacks.editTarget).toHaveBeenCalledWith(target);expect(callbacks.deleteTarget).toHaveBeenCalledWith("TARGET-A");expect(callbacks.editReq).toHaveBeenCalledWith("MODULE-A",req);expect(callbacks.deleteReq).toHaveBeenCalledWith("MODULE-A","REQ-A");expect(callbacks.reorderReq.mock.calls).toEqual([["MODULE-A","REQ-A","down"],["MODULE-A","REQ-B","up"]]);expect(callbacks.review).not.toHaveBeenCalled();});
 it("does not invent optional authoring callbacks when the supplied interface omits them",()=>{useBacklogDetailUIStore.setState({reviewMode:true});renderWithProviders(<OperationalTargetsPanel targets={[target]} requirements={[group]} editable/>);expect(screen.queryByTitle("Edit Target")).toBeNull();expect(screen.queryByTitle("Delete Target")).toBeNull();expect(screen.queryByTitle("Move Up")).toBeNull();expect(screen.queryByTitle("Move Down")).toBeNull();expect(screen.queryByTitle("Add Requirement")).toBeNull();expect(screen.queryByTitle("Edit Module")).toBeNull();expect(callbacks.review).not.toHaveBeenCalled();});

});
