import { useState } from "react";
import { cleanup, fireEvent, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { WorkshopQuestionView, ReviewQuestionView, type QuestionAnswer, type WorkshopQuestionLike } from "./question-renderers";
import type { PendingQuestion } from "../../types";
import { renderWithProviders as render } from "../../test-utils";
import { defaultApiClient } from "../../lib/api-client";
import { OTHER_KEY } from "../../lib/workshop-files";
const question:WorkshopQuestionLike={id:"fixture-decision",topic:"Owner decision",text:"Choose the owner boundary",context:"Original context",selected:"A",notes:"Original notes",options:[{key:"A",label:"Keep exact owner",rationale:"Preserve authority",recommended:true},{key:"B",label:"Defer to owner",rationale:"Retain boundary"},{key:"agent-other",label:" Other ",rationale:"Do not duplicate freeform"}]};
const review:PendingQuestion={id:"REQ-FIXTURE",source:"review",item_kind:"fix",item_name:"fixture-owner",title:"Owner requirement",description:"Original review evidence",review_type:"requirement",criticality:"P0",review_status:"unreviewed",review_comment:"Original comment"};
function Workshop({initial,disabled=false,q=question,onUpdate=vi.fn()}:{initial?:QuestionAnswer;disabled?:boolean;q?:WorkshopQuestionLike;onUpdate?:(patch:Partial<QuestionAnswer>)=>void}){const[answer,setAnswer]=useState(initial);return <WorkshopQuestionView question={q} answer={answer} disabled={disabled} actions={<button type="button">Owner action</button>} onUpdate={patch=>{onUpdate(patch);setAnswer(current=>({...current,...patch}));}}/>;}
function Review({initial,disabled=false,q=review,onUpdate=vi.fn()}:{initial?:QuestionAnswer;disabled?:boolean;q?:PendingQuestion;onUpdate?:(patch:Partial<QuestionAnswer>)=>void}){const[answer,setAnswer]=useState(initial);return <ReviewQuestionView question={q} answer={answer} disabled={disabled} onUpdate={patch=>{onUpdate(patch);setAnswer(current=>({...current,...patch}));}}/>;}
beforeEach(()=>{for(const method of ["get","post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Unexpected question network"));vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("Unexpected question fetch")));});
afterEach(()=>{cleanup();for(const method of ["get","post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe("actual workshop callback choice ownership",()=>{
 it("renders distinct owner context and options with one operator Other",()=>{render(<Workshop/>);expect(screen.getByText("Owner decision")).toBeVisible();expect(screen.getByText("Choose the owner boundary")).toBeVisible();expect(screen.getByText("Original context")).toBeVisible();expect(screen.getByText("Rec")).toBeVisible();expect(screen.getAllByRole("button",{name:/Other/})).toHaveLength(1);expect(screen.queryByText("Do not duplicate freeform")).toBeNull();expect(screen.getByPlaceholderText("Notes (optional)...")).toHaveValue("Original notes");expect(screen.getByRole("button",{name:"Owner action"})).toBeVisible();});
 it("offers exact declared choice with existing notes and no stale freeform",()=>{const update=vi.fn();render(<Workshop initial={{selected:OTHER_KEY,freeform:"Unselected material",notes:"Operator notes"}} onUpdate={update}/>);fireEvent.click(screen.getByRole("button",{name:/Defer to owner/}));expect(update.mock.calls).toEqual([[{selected:"B",freeform:undefined,notes:"Operator notes"}]]);expect(screen.queryByPlaceholderText("Describe your alternative...")).toBeNull();expect(screen.getByPlaceholderText("Notes (optional)...")).toHaveValue("Operator notes");});
 it("selects Other and retains explicit freeform without inventing an option",()=>{const update=vi.fn();render(<Workshop initial={{selected:"A",freeform:"Retained operator material",notes:"Owner notes"}} onUpdate={update}/>);fireEvent.click(screen.getByRole("button",{name:/Other/}));expect(update.mock.calls).toEqual([[{selected:OTHER_KEY,freeform:"Retained operator material",notes:"Owner notes"}]]);expect(screen.getByPlaceholderText("Describe your alternative...")).toHaveValue("Retained operator material");});
 it("offers a typed freeform patch only for the operator Other",()=>{const update=vi.fn();render(<Workshop initial={{selected:OTHER_KEY,freeform:"Old",notes:"Owner notes"}} onUpdate={update}/>);fireEvent.change(screen.getByPlaceholderText("Describe your alternative..."),{target:{value:"New operator alternative"}});expect(update.mock.calls).toEqual([[{selected:OTHER_KEY,freeform:"New operator alternative"}]]);expect(screen.getByPlaceholderText("Notes (optional)...")).toHaveValue("Owner notes");});
 it.each(["A",OTHER_KEY])("offers notes for selected %s with the appropriate freeform",selected=>{const update=vi.fn();render(<Workshop initial={{selected,freeform:"Owner alternative",notes:"Before"}} onUpdate={update}/>);fireEvent.change(screen.getByPlaceholderText("Notes (optional)..."),{target:{value:"Reviewed operator notes"}});expect(update.mock.calls).toEqual([[{selected,freeform:selected===OTHER_KEY?"Owner alternative":undefined,notes:"Reviewed operator notes"}]]);});
 it("does not treat an explicit empty answer as the server selection",()=>{render(<Workshop initial={{selected:"",notes:""}}/>);expect(screen.queryByPlaceholderText("Notes (optional)...")).toBeNull();expect(screen.queryByPlaceholderText("Describe your alternative...")).toBeNull();});
 it("disables all offered choice inputs with zero callback effects",()=>{const update=vi.fn();render(<Workshop disabled initial={{selected:OTHER_KEY,freeform:"Owner material",notes:"Owner notes"}} onUpdate={update}/>);for(const button of screen.getAllByRole("button").filter(b=>b.textContent!=="Owner action")){expect(button).toBeDisabled();fireEvent.click(button);}for(const input of screen.getAllByRole("textbox"))expect(input).toBeDisabled();expect(update).not.toHaveBeenCalled();});
 it("does not duplicate identical title and body or render whitespace context",()=>{render(<Workshop q={{id:"fixture",topic:" Same owner text ",text:"Same owner text",context:" ",options:[]}}/>);expect(screen.getAllByText("Same owner text")).toHaveLength(1);expect(screen.getAllByRole("button",{name:/Other/})).toHaveLength(1);});
 it("renders a body without inventing a title when topic is absent",()=>{render(<Workshop q={{id:"fixture",text:"Only original body"}}/>);expect(screen.getByText("Only original body")).toBeVisible();expect(screen.queryByText("Owner decision")).toBeNull();});
});
describe("actual review callback status ownership",()=>{
 it("offers approval preserving original comment without persisting acceptance",()=>{const update=vi.fn();render(<Review onUpdate={update}/>);fireEvent.click(screen.getByRole("button",{name:"Approve"}));expect(update.mock.calls).toEqual([[{reviewStatus:"approved",reviewComment:"Original comment"}]]);expect(screen.queryByPlaceholderText("Comment (optional)...")).toBeNull();expect(screen.getByText("Req")).toBeVisible();expect(screen.getByText("P0")).toBeVisible();});
 it("offers flag and edited comment retaining exact status",()=>{const update=vi.fn();render(<Review onUpdate={update}/>);fireEvent.click(screen.getByRole("button",{name:"Flag"}));expect(screen.getByPlaceholderText("Comment (optional)...")).toHaveValue("Original comment");fireEvent.change(screen.getByPlaceholderText("Comment (optional)..."),{target:{value:"Operator evidence concern"}});expect(update.mock.calls).toEqual([[{reviewStatus:"flagged",reviewComment:"Original comment"}],[{reviewStatus:"flagged",reviewComment:"Operator evidence concern"}]]);});
 it("prefers explicit local answer including empty comment over archived owner values",()=>{const update=vi.fn();render(<Review initial={{reviewStatus:"flagged",reviewComment:""}} q={{...review,review_status:"approved"}} onUpdate={update}/>);expect(screen.getByPlaceholderText("Comment (optional)...")).toHaveValue("");fireEvent.click(screen.getByRole("button",{name:"Approve"}));expect(update.mock.calls).toEqual([[{reviewStatus:"approved",reviewComment:""}]]);});
 it("disables approval, flag and comment with zero callback effects",()=>{const update=vi.fn();render(<Review disabled initial={{reviewStatus:"flagged",reviewComment:"Retained concern"}} onUpdate={update}/>);for(const button of screen.getAllByRole("button")){expect(button).toBeDisabled();fireEvent.click(button);}expect(screen.getByRole("textbox")).toBeDisabled();expect(screen.getByRole("textbox")).toHaveValue("Retained concern");expect(update).not.toHaveBeenCalled();});
 it.each(["P1","P2","future-priority",undefined])("shows supplied target criticality %s without inventing known severity",criticality=>{render(<Review q={{...review,review_type:"target",criticality,title:undefined,description:" "}}/>);expect(screen.getByText("Target")).toBeVisible();expect(screen.getByText("REQ-FIXTURE")).toBeVisible();if(criticality)expect(screen.getByText(criticality)).toBeVisible();else expect(screen.queryByText("P0")).toBeNull();expect(screen.queryByText("Owner requirement")).toBeNull();});
});
