package main

// getDefaultRules returns hardcoded rules as fallback
func getDefaultRules() map[string]RuleInfo {
	return map[string]RuleInfo{
		"lifecycle_protection": {
			ID:          "lifecycle_protection",
			Name:        "Lifecycle Protection",
			Description: "Ensure main.go files have VROOLI_LIFECYCLE_MANAGED checks",
			Category:    "api",
			Severity:    "critical",
			Enabled:     true,
			Standard:    "vrooli-lifecycle-v1",
		},
		"test_coverage": {
			ID:          "test_coverage",
			Name:        "Test File Coverage",
			Description: "Ensure all Go files have corresponding test files",
			Category:    "test",
			Severity:    "medium",
			Enabled:     true,
			Standard:    "testing-standards-v1",
		},
		"lightweight_main": {
			ID:          "lightweight_main",
			Name:        "Lightweight Main Function",
			Description: "Main functions should delegate to cmd.Execute() or similar",
			Category:    "cli",
			Severity:    "medium",
			Enabled:     true,
			Standard:    "code-structure-v1",
		},
		"hardcoded_values": {
			ID:          "hardcoded_values",
			Name:        "No Hardcoded Values",
			Description: "Avoid hardcoded ports, URLs, and credentials",
			Category:    "config",
			Severity:    "high",
			Enabled:     true,
			Standard:    "configuration-v1",
		},
		"versioned_endpoints": {
			ID:          "versioned_endpoints",
			Name:        "API Versioning",
			Description: "API endpoints should include version in path (e.g., /api/v1/)",
			Category:    "api",
			Severity:    "medium",
			Enabled:     true,
			Standard:    "api-design-v1",
		},
		"http_status_codes": {
			ID:          "http_status_codes",
			Name:        "HTTP Status Codes",
			Description: "Use proper HTTP status codes in API responses",
			Category:    "api",
			Severity:    "low",
			Enabled:     true,
			Standard:    "api-design-v1",
		},
		"content_type_headers": {
			ID:          "content_type_headers",
			Name:        "Content-Type Headers",
			Description: "API responses must set appropriate Content-Type headers",
			Category:    "api",
			Severity:    "medium",
			Enabled:     true,
			Standard:    "api-design-v1",
		},
		"env_var_naming": {
			ID:          "env_var_naming",
			Name:        "Environment Variable Naming",
			Description: "Environment variables should follow VROOLI_ prefix convention",
			Category:    "config",
			Severity:    "low",
			Enabled:     true,
			Standard:    "configuration-v1",
		},
		"structured_logging": {
			ID:          "structured_logging",
			Name:        "Structured Logging",
			Description: "Use structured logging with proper log levels",
			Category:    "cli",
			Severity:    "medium",
			Enabled:     true,
			Standard:    "logging-v1",
		},
		"resource_cleanup": {
			ID:          "resource_cleanup",
			Name:        "Resource Cleanup",
			Description: "Ensure proper cleanup of resources (connections, files, etc.)",
			Category:    "api",
			Severity:    "critical",
			Enabled:     true,
			Standard:    "resource-management-v1",
		},
		"health_check": {
			ID:          "health_check",
			Name:        "Health Check Endpoint",
			Description: "Services must implement health check endpoints",
			Category:    "api",
			Severity:    "high",
			Enabled:     true,
			Standard:    "service-reliability-v1",
		},
	}
}