import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { SettingsPage } from "./SettingsPage";
import { DEFAULT_SETTINGS } from "../services/settings-service";
import { defaultApiClient } from "../lib/api-client";
import { createTestQueryClient, renderWithProviders } from "../test-utils";
import { selectors } from "../consts/selectors";

// Actual settings owner/page/service and controlled draft; exact read-only HTTP
// boundary. All edits are local; no Save, auto-drain, filing or run is offered.
const clients: ReturnType<typeof createTestQueryClient>[] = [];
const views: { unmount(): void }[] = [];
const requests: {path: string; body: string; method: string}[] = [];
let owner = structuredClone(DEFAULT_SETTINGS);
let statusReply: () => Promise<Response>;
let theme: string | undefined, resolved: string | undefined, color = "";
const statusPath = "/vrooli.swarm_manager.v1.api.AutoFilerService/GetStatus";
const transitionPath = "/vrooli.swarm_manager.v1.api.TransitionService/ListTransitions";
function json(value: unknown) { return new Response(JSON.stringify(value), {headers:{"Content-Type":"application/json"}}); }
function input(label: string) { const el=screen.getByText(label,{selector:"label"}).parentElement?.querySelector("input");if(!el)throw new Error("Missing actual input "+label);return el; }
function change(label: string,value:string) {fireEvent.change(input(label),{target:{value}});}
function card(title:string) {const el=screen.getByRole("heading",{name:title});const parent=el.closest("[data-slot=card]")??el.parentElement?.parentElement?.parentElement;if(!parent)throw new Error("Missing actual card "+title);return within(parent as HTMLElement);}
async function mountExecution() {const client=createTestQueryClient();clients.push(client);const view=renderWithProviders(<SettingsPage/>,{queryClient:client});views.push(view);await screen.findByRole("button",{name:"Save Settings"});await userEvent.click(screen.getByRole("tab",{name:"Execution"}));await waitFor(()=>expect(requests.some(x=>x.path===statusPath)).toBe(true));return{view,client};}
function noEffects(){for(const method of ["post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(requests.every(x=>[statusPath,transitionPath].includes(x.path)&&x.body==="{}"&&x.method==="POST")).toBe(true);}
beforeEach(()=>{owner=structuredClone(DEFAULT_SETTINGS);requests.length=0;theme=document.documentElement.dataset.theme;resolved=document.documentElement.dataset.resolvedTheme;color=document.documentElement.style.colorScheme;statusReply=async()=>json({enabled:false,lastCycleTime:"",openAutoFiled:2,maxOpenAutoFiled:10});vi.spyOn(defaultApiClient,"get").mockImplementation(async path=>{if(path==="/settings"){const {deleteConfirmation:_,...settings}=owner;return{settings};}if(path==="/integrations")return{integrations:[]};if(path==="/stats")return{};if(path==="/execution/auto-drain")return{enabled:false};throw new Error("Unexpected settings read "+path);});for(const method of ["post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Unexpected settings effect"));vi.stubGlobal("fetch",vi.fn(async(value:RequestInfo|URL,init?:RequestInit)=>{const request=value instanceof Request?new Request(value,init):new Request(String(value),init);const path=new URL(request.url).pathname;const body=await request.text();requests.push({path,body,method:request.method});expect(request.method).toBe("POST");expect(body).toBe("{}");if(path===transitionPath)return json({transitions:[]});if(path===statusPath)return statusReply();throw new Error("Unexpected settings transport "+path);}));});
afterEach(()=>{try{views.splice(0).forEach(v=>v.unmount());cleanup();noEffects();}finally{clients.splice(0).forEach(c=>c.clear());vi.restoreAllMocks();vi.unstubAllGlobals();if(theme===undefined)delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=theme;if(resolved===undefined)delete document.documentElement.dataset.resolvedTheme;else document.documentElement.dataset.resolvedTheme=resolved;document.documentElement.style.colorScheme=color;}});
describe("actual execution settings local edit and reset ownership",()=>{
 it("reveals auto-fixup bounds while retaining local defaults and resets the draft",async()=>{await mountExecution();const defaults=within(screen.getByTestId(selectors.settings.executionDefaults));fireEvent.click(defaults.getByRole("button",{name:"Enabled"}));change("Max Fixup Attempts","90");expect(input("Max Fixup Attempts")).toHaveValue(5);change("Max Fixup Attempts","-5");expect(input("Max Fixup Attempts")).toHaveValue(0);fireEvent.click(defaults.getByRole("button",{name:"Reset"}));expect(screen.getByRole("button",{name:"Save Settings"})).toBeDisabled();noEffects();});
 it.each(["investigate","execute","review","reconcile"] as const)("bounds %s lane independently and restores governance without persistence",async lane=>{await mountExecution();const before={...owner.laneConcurrencyLimits};change(lane,"90");expect(input(lane)).toHaveValue(50);change(lane,"0");expect(input(lane)).toHaveValue(1);for(const sibling of ["investigate","execute","review","reconcile"] as const)if(sibling!==lane)expect(input(sibling)).toHaveValue(before[sibling]);expect(screen.getByRole("button",{name:"Save Settings"})).toBeEnabled();fireEvent.click(card("Governance").getByRole("button",{name:"Reset"}));for(const name of ["investigate","execute","review","reconcile"] as const)expect(input(name)).toHaveValue(DEFAULT_SETTINGS.laneConcurrencyLimits[name]);expect(screen.getByRole("button",{name:"Save Settings"})).toBeDisabled();noEffects();});
 it("restores all governance draft values without overwriting adjacent agent edits",async()=>{await mountExecution();change("Max Queue Depth","88");change("Circuit Breaker Threshold","9");change("Circuit Breaker Cooldown (minutes)","30");change("Cost Cap Per Run ($)","9");change("Cost Per Turn Estimate ($)","2");change("Max Turns","77");fireEvent.click(card("Governance").getByRole("button",{name:"Reset"}));expect(input("Max Queue Depth")).toHaveValue(DEFAULT_SETTINGS.maxQueueDepth);expect(input("Circuit Breaker Threshold")).toHaveValue(DEFAULT_SETTINGS.circuitBreakerThreshold);expect(input("Circuit Breaker Cooldown (minutes)")).toHaveValue(DEFAULT_SETTINGS.circuitBreakerCooldownMinutes);expect(input("Cost Cap Per Run ($)")).toHaveValue(DEFAULT_SETTINGS.executionCostCapPerRun);expect(input("Cost Per Turn Estimate ($)")).toHaveValue(DEFAULT_SETTINGS.costPerTurnEstimate);expect(input("Max Turns")).toHaveValue(77);noEffects();});
 it.each(["off","block"] as const)("changes %s fix-before-feature gate locally then resets exact owner defaults",async mode=>{await mountExecution();const gate=within(screen.getByTestId(selectors.settings.fixBeforeFeature));fireEvent.click(gate.getByRole("button",{name:mode}));expect(gate.getByRole("button",{name:mode})).toHaveClass("border-cyan-500");fireEvent.click(gate.getByRole("button",{name:"Reset"}));expect(gate.getByRole("button",{name:DEFAULT_SETTINGS.fixBeforeFeature})).toHaveClass("border-cyan-500");noEffects();});
 it("resets the complete auto-filer draft and preserves unrelated agent edits",async()=>{await mountExecution();const filer=card("Backlog Auto-Filer");fireEvent.click(filer.getByRole("button",{name:"Enabled"}));fireEvent.click(filer.getByRole("button",{name:"auto-add"}));fireEvent.click(filer.getByRole("button",{name:"importance"}));change("Max Open Auto-Filed","4");change("Velocity Window Days","12");change("Min Velocity Transitions","3");change("Interval Minutes","20");change("Goal Name","fictional-goal");change("Max Turns","77");fireEvent.click(filer.getByRole("button",{name:"Reset"}));expect(input("Max Open Auto-Filed")).toHaveValue(DEFAULT_SETTINGS.autoFiler.maxOpenAutoFiled);expect(input("Velocity Window Days")).toHaveValue(DEFAULT_SETTINGS.autoFiler.velocityWindowDays);expect(input("Min Velocity Transitions")).toHaveValue(DEFAULT_SETTINGS.autoFiler.minVelocityTransitions);expect(input("Interval Minutes")).toHaveValue(DEFAULT_SETTINGS.autoFiler.intervalMinutes);expect(input("Goal Name")).toHaveValue(DEFAULT_SETTINGS.autoFiler.goalName);expect(filer.getByRole("button",{name:DEFAULT_SETTINGS.autoFiler.mode==="auto_add"?"auto-add":"suggest"})).toHaveClass("border-cyan-500");expect(input("Max Turns")).toHaveValue(77);noEffects();});
 it("ignores a late auto-filer read after the actual Execution tab unmounts",async()=>{let resolve:(value:Response)=>void=()=>{throw new Error("Status was not started");};statusReply=()=>new Promise<Response>(r=>{resolve=r;});await mountExecution();await userEvent.click(screen.getByRole("tab",{name:"General"}));await act(async()=>resolve(json({enabled:true,lastError:"Late fictional status"})));expect(screen.queryByText("Late fictional status")).toBeNull();expect(screen.getByRole("button",{name:"Save Settings"})).toBeDisabled();noEffects();});
});
