import type { PushDeviceCreateInput } from "@vrooli/shared";

/**
 * Form data fixtures for push device-related forms
 * These represent data as it appears in form state before submission
 */

/**
 * Push device registration form data
 */
export const minimalPushDeviceCreateFormInput: Partial<PushDeviceCreateInput> = {
    name: "My Phone",
    // Note: endpoint and keys are typically generated by the Push API,
    // not entered by the user in a form
};

export const completePushDeviceCreateFormInput = {
    name: "Work Laptop",
    enableNotifications: true,
    notificationTypes: {
        comments: true,
        mentions: true,
        updates: true,
        reminders: true,
        marketing: false,
    },
};

/**
 * Push device update form data
 */
export const minimalPushDeviceUpdateFormInput = {
    name: "Updated Device Name",
};

export const completePushDeviceUpdateFormInput = {
    name: "Personal Phone",
    enableNotifications: true,
    notificationTypes: {
        comments: true,
        mentions: true,
        updates: false,
        reminders: true,
        marketing: false,
    },
};

/**
 * Push notification preferences form data
 */
export const pushNotificationPreferencesFormInput = {
    enableNotifications: true,
    notificationTypes: {
        comments: true,
        mentions: true,
        updates: true,
        reminders: true,
        marketing: false,
    },
    quietHours: {
        enabled: true,
        startTime: "22:00",
        endTime: "08:00",
        timezone: "America/New_York",
    },
    soundEnabled: true,
    vibrationEnabled: true,
};

/**
 * Device-specific notification settings
 */
export const deviceNotificationSettingsFormInputs = {
    mobile: {
        name: "Mobile Phone",
        enableNotifications: true,
        notificationTypes: {
            comments: true,
            mentions: true,
            updates: true,
            reminders: true,
            marketing: false,
        },
        soundEnabled: true,
        vibrationEnabled: true,
        badgeEnabled: true,
    },
    desktop: {
        name: "Desktop Browser",
        enableNotifications: true,
        notificationTypes: {
            comments: true,
            mentions: true,
            updates: true,
            reminders: false,
            marketing: false,
        },
        soundEnabled: true,
        vibrationEnabled: false,
        badgeEnabled: false,
    },
    tablet: {
        name: "iPad",
        enableNotifications: true,
        notificationTypes: {
            comments: false,
            mentions: true,
            updates: false,
            reminders: true,
            marketing: false,
        },
        soundEnabled: false,
        vibrationEnabled: true,
        badgeEnabled: true,
    },
};

/**
 * Push device scenarios for testing
 */
export const pushDeviceScenarioFormInputs = {
    workDevice: {
        name: "Work MacBook",
        enableNotifications: true,
        notificationTypes: {
            comments: true,
            mentions: true,
            updates: true,
            reminders: true,
            marketing: false,
        },
        quietHours: {
            enabled: true,
            startTime: "18:00",
            endTime: "09:00",
            timezone: "America/New_York",
        },
    },
    personalDevice: {
        name: "Personal iPhone",
        enableNotifications: true,
        notificationTypes: {
            comments: true,
            mentions: true,
            updates: false,
            reminders: true,
            marketing: true,
        },
        quietHours: {
            enabled: false,
        },
    },
    testDevice: {
        name: "Test Device",
        enableNotifications: false,
        notificationTypes: {
            comments: false,
            mentions: false,
            updates: false,
            reminders: false,
            marketing: false,
        },
    },
};

/**
 * Edge case device names for testing validation
 */
export const deviceNameEdgeCaseFormInputs = {
    shortName: {
        name: "A",
    },
    longName: {
        name: "This is a device name that is exactly fifty chars!", // 50 characters
    },
    specialCharacters: {
        name: "Device #1 (Home) @ 2024",
    },
    unicode: {
        name: "📱 My Phone",
    },
    whitespace: {
        name: "  Device Name  ", // Leading/trailing spaces
    },
};

/**
 * Invalid device form inputs for testing validation
 */
export const invalidPushDeviceFormInputs = {
    empty: {
        name: "",
    },
    whitespaceOnly: {
        name: "   ",
    },
    tooLong: {
        name: "This device name is way too long and exceeds the maximum allowed length of fifty characters for a device name", // > 50 characters
    },
    invalidNotificationPreferences: {
        name: "Valid Name",
        notificationTypes: "not-an-object", // Should be object
    },
    invalidQuietHours: {
        name: "Valid Name",
        quietHours: {
            enabled: true,
            startTime: "25:00", // Invalid time
            endTime: "08:00",
        },
    },
};

/**
 * Form validation states
 */
export const pushDeviceFormValidationStates = {
    pristine: {
        values: {
            name: "",
            enableNotifications: true,
            notificationTypes: {
                comments: true,
                mentions: true,
                updates: true,
                reminders: true,
                marketing: false,
            },
        },
        errors: {},
        touched: {},
        isValid: false,
        isSubmitting: false,
    },
    withErrors: {
        values: {
            name: "", // Empty name
            enableNotifications: true,
        },
        errors: {
            name: "Device name is required",
        },
        touched: {
            name: true,
        },
        isValid: false,
        isSubmitting: false,
    },
    valid: {
        values: minimalPushDeviceCreateFormInput,
        errors: {},
        touched: {
            name: true,
        },
        isValid: true,
        isSubmitting: false,
    },
    submitting: {
        values: minimalPushDeviceCreateFormInput,
        errors: {},
        touched: {
            name: true,
        },
        isValid: true,
        isSubmitting: true,
    },
};

/**
 * Helper function to create push device form initial values
 */
export const createPushDeviceFormInitialValues = (deviceData?: Partial<any>) => ({
    name: deviceData?.name || "",
    enableNotifications: deviceData?.enableNotifications ?? true,
    notificationTypes: deviceData?.notificationTypes || {
        comments: true,
        mentions: true,
        updates: true,
        reminders: true,
        marketing: false,
    },
    quietHours: deviceData?.quietHours || {
        enabled: false,
        startTime: "22:00",
        endTime: "08:00",
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    },
    soundEnabled: deviceData?.soundEnabled ?? true,
    vibrationEnabled: deviceData?.vibrationEnabled ?? true,
    badgeEnabled: deviceData?.badgeEnabled ?? true,
    ...deviceData,
});

/**
 * Helper function to transform form data to API format
 */
export const transformPushDeviceFormToApiInput = (formData: any) => {
    // Note: The actual push subscription (endpoint, keys) is handled by the Push API
    // This transforms only the user-configurable settings
    return {
        name: formData.name?.trim() || undefined,
        // Notification preferences might be stored separately
        // depending on the backend implementation
    };
};

/**
 * Mock push subscription data (typically from Push API)
 */
export const mockPushSubscription = {
    endpoint: "https://fcm.googleapis.com/fcm/send/example-endpoint",
    expirationTime: null,
    keys: {
        p256dh: "BKJYlp5Q8hJJ6RRXL8dV6wJG3l4zDWr-EXAMPLE-KEY",
        auth: "AUTH-KEY-EXAMPLE",
    },
};

/**
 * Push device list form data (for managing multiple devices)
 */
export const pushDeviceListFormData = {
    devices: [
        {
            id: "device_001",
            name: "iPhone 15 Pro",
            lastActive: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 minutes ago
            enableNotifications: true,
            isCurrentDevice: true,
        },
        {
            id: "device_002",
            name: "MacBook Pro",
            lastActive: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
            enableNotifications: true,
            isCurrentDevice: false,
        },
        {
            id: "device_003",
            name: "Old Phone",
            lastActive: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(), // 30 days ago
            enableNotifications: false,
            isCurrentDevice: false,
        },
    ],
};

/**
 * Browser/platform detection helpers for form display
 */
export const mockBrowserInfo = {
    isMobile: false,
    isDesktop: true,
    browser: "Chrome",
    version: "120.0.0",
    os: "macOS",
    supportsPush: true,
    supportsVibration: false,
    supportsBadge: true,
};

/**
 * Permission states for push notifications
 */
export const pushPermissionStates = {
    granted: "granted",
    denied: "denied",
    default: "default", // Not yet asked
};