export class BashCompletionGenerator {
    generate(commandName: string): string {
        return `#!/bin/bash
# Bash completion for ${commandName}
# This file is generated by '${commandName} completion install'

_${commandName}_completions() {
    local cur prev words cword
    _init_completion || return

    # Call the CLI with special completion flag
    local IFS=$'\\n'
    local completions
    completions=$(${commandName} --generate-completions "\${COMP_WORDS[@]}" 2>/dev/null)
    
    # Check if we got any completions
    if [[ -n "$completions" ]]; then
        local IFS=$'\\n'
        COMPREPLY=( $(compgen -W "$completions" -- "$cur") )
        
        # Handle colons in completions (for descriptions)
        local i
        for ((i=0; i<\${#COMPREPLY[@]}; i++)); do
            local completion="\${COMPREPLY[i]}"
            if [[ "$completion" == *:* ]]; then
                # Extract just the value part before the colon
                COMPREPLY[i]="\${completion%%:*}"
            fi
        done
    else
        # Fallback to filename completion
        _filedir
    fi
}

# Register the completion function
complete -F _${commandName}_completions ${commandName}
`;
    }
}
