import { describe, it, expect, beforeEach } from "vitest";
import { FishCompletionGenerator } from "./fish.js";

describe("FishCompletionGenerator", () => {
    let generator: FishCompletionGenerator;

    beforeEach(() => {
        generator = new FishCompletionGenerator();
    });

    describe("generate", () => {
        it("should generate fish completion script for given command name", () => {
            const commandName = "test-cli";
            const result = generator.generate(commandName);

            expect(result).toContain(`# Fish completion for ${commandName}`);
            expect(result).toContain(`'${commandName} completion install'`);
        });

        it("should include completion function with correct naming", () => {
            const commandName = "vrooli";
            const result = generator.generate(commandName);

            expect(result).toContain("function __vrooli_complete");
            expect(result).toContain("complete -c vrooli -f -a \"(__vrooli_complete)\"");
        });

        it("should handle command names with special characters", () => {
            const commandName = "my-special_cli.exe";
            const result = generator.generate(commandName);

            expect(result).toContain("function __my-special_cli.exe_complete");
            expect(result).toContain("complete -c my-special_cli.exe -f -a \"(__my-special_cli.exe_complete)\"");
        });

        it("should include proper fish shell constructs", () => {
            const result = generator.generate("test");

            expect(result).toContain("set -l cmd (commandline -o)");
            expect(result).toContain("set -l completions");
            expect(result).toContain("test -n \"$completions\"");
        });

        it("should include completion generation logic", () => {
            const commandName = "test";
            const result = generator.generate(commandName);

            expect(result).toContain(`${commandName} --generate-completions $cmd 2>/dev/null`);
        });

        it("should handle completion responses with descriptions", () => {
            const result = generator.generate("test");

            expect(result).toContain("string match -q \"*:*\" \"$completion\"");
            expect(result).toContain("string split \":\" \"$completion\" -m 1");
            expect(result).toContain("printf \"%s\\t%s\\n\" $parts[1] $parts[2]");
        });

        it("should handle completions without descriptions", () => {
            const result = generator.generate("test");

            expect(result).toContain("printf \"%s\\n\" \"$completion\"");
        });

        it("should include fallback to file completion", () => {
            const result = generator.generate("test");

            expect(result).toContain("__fish_complete_path");
            expect(result).toContain("else");
        });

        it("should include proper error handling", () => {
            const result = generator.generate("test");

            expect(result).toContain("2>/dev/null");
        });

        it("should generate valid fish syntax", () => {
            const result = generator.generate("test");

            // Check for proper function structure
            expect(result).toMatch(/function __[^_]+_complete[\s\S]*end/);
            expect(result).toMatch(/complete -c .+ -f -a "\(__[^_]+_complete\)"/);
        });

        it("should include proper loop structure", () => {
            const result = generator.generate("test");

            expect(result).toContain("for completion in $completions");
            expect(result).toContain("end");
        });

        it("should be deterministic", () => {
            const commandName = "consistent";
            const result1 = generator.generate(commandName);
            const result2 = generator.generate(commandName);

            expect(result1).toBe(result2);
        });

        it("should handle empty command name", () => {
            const result = generator.generate("");

            expect(result).toContain("function ___complete");
            expect(result).toContain("complete -c  -f -a \"(___complete)\"");
        });

        it("should generate multi-line script", () => {
            const result = generator.generate("test");
            const lines = result.split("\n");

            expect(lines.length).toBeGreaterThan(5);
        });

        it("should include proper commenting", () => {
            const commandName = "documented";
            const result = generator.generate(commandName);

            expect(result).toContain("# Fish completion for documented");
            expect(result).toContain("# This file is generated by");
            expect(result).toContain("# Split completion and description");
            expect(result).toContain("# Just the completion");
            expect(result).toContain("# Fallback to file completion");
            expect(result).toContain("# Register the completion function");
        });

        it("should handle fish-specific variable assignments", () => {
            const result = generator.generate("test");

            expect(result).toContain("set -l parts");
            expect(result).toContain("$parts[1]");
            expect(result).toContain("$parts[2]");
        });
    });

    describe("edge cases", () => {
        it("should handle very long command names", () => {
            const longName = "a".repeat(100);
            const result = generator.generate(longName);

            expect(result).toContain(`function __${longName}_complete`);
            expect(result).toContain(`complete -c ${longName} -f -a "(__${longName}_complete)"`);
        });

        it("should handle command names with numbers", () => {
            const result = generator.generate("cli2024");

            expect(result).toContain("function __cli2024_complete");
            expect(result).toContain("complete -c cli2024 -f -a \"(__cli2024_complete)\"");
        });

        it("should maintain script structure regardless of command name", () => {
            const names = ["a", "test-long-name", "CLI_TOOL", "tool.v2"];
            
            names.forEach(name => {
                const result = generator.generate(name);
                
                expect(result).toContain("# Fish completion for");
                expect(result).toContain("set -l cmd (commandline -o)");
                expect(result).toContain("--generate-completions");
                expect(result).toContain("__fish_complete_path");
                expect(result).toMatch(/complete -c .+ -f -a/);
            });
        });

        it("should handle conditional logic correctly", () => {
            const result = generator.generate("test");

            expect(result).toContain("if test -n \"$completions\"");
            expect(result).toContain("if string match -q \"*:*\" \"$completion\"");
        });
    });
});