// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  errorBoundary: {
    somethingWentWrong: "errorBoundary.somethingWentWrong",
    tryAgain: "errorBoundary.tryAgain",
  },
  errorBanner: {
    retry: "errorBanner.retry",
    dismiss: "errorBanner.dismiss",
  },
  enableAudioBanner: {
    title: "enableAudioBanner.title",
    description: "enableAudioBanner.description",
    enable: "enableAudioBanner.enable",
    enabling: "enableAudioBanner.enabling",
    enableTitle: "enableAudioBanner.enableTitle",
    dismiss: "enableAudioBanner.dismiss",
  },
  voiceRejection: {
    title: "voiceRejection.title",
    explanatoryDetail: "voiceRejection.explanatoryDetail",
    retryableDetail: "voiceRejection.retryableDetail",
    transcribeAnyway: "voiceRejection.transcribeAnyway",
    retry: "voiceRejection.retry",
    transcribing: "voiceRejection.transcribing",
    retryTitle: "voiceRejection.retryTitle",
    dismiss: "voiceRejection.dismiss",
    dismissAriaLabel: "voiceRejection.dismissAriaLabel",
  },
  summarizeError: {
    autoFailed: "summarizeError.autoFailed",
    failed: "summarizeError.failed",
    retry: "summarizeError.retry",
    retrying: "summarizeError.retrying",
    retryTitle: "summarizeError.retryTitle",
    dismiss: "summarizeError.dismiss",
    dismissAriaLabel: "summarizeError.dismissAriaLabel",
  },
  confirmClose: {
    title: "confirmClose.title",
    body: "confirmClose.body",
    cancel: "confirmClose.cancel",
    confirm: "confirmClose.confirm",
  },
  recoverableSessions: {
    heading: "recoverableSessions.heading",
    heading_one: "recoverableSessions.heading_one",
    agentLabel: "recoverableSessions.agentLabel",
    cwdLabel: "recoverableSessions.cwdLabel",
    agentNone: "recoverableSessions.agentNone",
    reattach: "recoverableSessions.reattach",
    reattachTitle: "recoverableSessions.reattachTitle",
    dismiss: "recoverableSessions.dismiss",
    dismissTitle: "recoverableSessions.dismissTitle",
  },
  mobileToolbar: {
    showUnsentTitle: "mobileToolbar.showUnsentTitle",
    unsentCount: "mobileToolbar.unsentCount",
    unsentOldest: "mobileToolbar.unsentOldest",
    placeholder: "mobileToolbar.placeholder",
    statusQueued: "mobileToolbar.statusQueued",
    statusSending: "mobileToolbar.statusSending",
    statusFailed: "mobileToolbar.statusFailed",
    sendTitle: "mobileToolbar.sendTitle",
    aiCommandTitle: "mobileToolbar.aiCommandTitle",
    uploadImageTitle: "mobileToolbar.uploadImageTitle",
  },
  floatingToolbar: {
    tapToRestore: "floatingToolbar.tapToRestore",
    settingsTitle: "floatingToolbar.settingsTitle",
    aiCommandTitle: "floatingToolbar.aiCommandTitle",
    launcherFirstTitle: "floatingToolbar.launcherFirstTitle",
    terminalFirstTitle: "floatingToolbar.terminalFirstTitle",
  },
  tabBar: {
    expandGroup: "tabBar.expandGroup",
    collapseGroup: "tabBar.collapseGroup",
    closeTabTitle: "tabBar.closeTabTitle",
    closeTabAria: "tabBar.closeTabAria",
  },
  sessionSidebar: {
    title: "sessionSidebar.title",
    open: "sessionSidebar.open",
    close: "sessionSidebar.close",
    sessionCount: "sessionSidebar.sessionCount",
    sessionCount_one: "sessionSidebar.sessionCount_one",
    unreadSummary: "sessionSidebar.unreadSummary",
    unreadSummary_one: "sessionSidebar.unreadSummary_one",
  },
  tabContextMenu: {
    rename: "tabContextMenu.rename",
    customizeAppearance: "tabContextMenu.customizeAppearance",
    removeFromGroup: "tabContextMenu.removeFromGroup",
    addToGroup: "tabContextMenu.addToGroup",
    newGroup: "tabContextMenu.newGroup",
    closeTab: "tabContextMenu.closeTab",
    copyDebugLog: "tabContextMenu.copyDebugLog",
  },
  terminalContextMenu: {
    copy: "terminalContextMenu.copy",
    speak: "terminalContextMenu.speak",
    paste: "terminalContextMenu.paste",
    pasting: "terminalContextMenu.pasting",
    pasted: "terminalContextMenu.pasted",
    pasteFailed: "terminalContextMenu.pasteFailed",
    useCtrlVHint: "terminalContextMenu.useCtrlVHint",
    uploadImage: "terminalContextMenu.uploadImage",
    selectAll: "terminalContextMenu.selectAll",
    clearTerminal: "terminalContextMenu.clearTerminal",
  },
  keyComboPicker: {
    triggerTitle: "keyComboPicker.triggerTitle",
    searchPlaceholder: "keyComboPicker.searchPlaceholder",
    recent: "keyComboPicker.recent",
    noResults: "keyComboPicker.noResults",
  },
  messagesSearch: {
    placeholder: "messagesSearch.placeholder",
    noMatches: "messagesSearch.noMatches",
    matchCount: "messagesSearch.matchCount",
    typeToSearch: "messagesSearch.typeToSearch",
    prevTitle: "messagesSearch.prevTitle",
    nextTitle: "messagesSearch.nextTitle",
    closeTitle: "messagesSearch.closeTitle",
  },
  integrationsPanel: {
    checking: "integrationsPanel.checking",
    loadFailed: "integrationsPanel.loadFailed",
    activeCount: "integrationsPanel.activeCount",
    noneConfigured: "integrationsPanel.noneConfigured",
  },
  terminalHeader: {
    renameTitle: "terminalHeader.renameTitle",
    showMessages: "terminalHeader.showMessages",
    showTerminal: "terminalHeader.showTerminal",
    appearanceTitle: "terminalHeader.appearanceTitle",
    closeTitle: "terminalHeader.closeTitle",
    reorderAria: "terminalHeader.reorderAria",
  },
  workspace: {
    tagline: "workspace.tagline",
    newTerminalButton: "workspace.newTerminalButton",
    creating: "workspace.creating",
    settingsTitle: "workspace.settingsTitle",
    switchToMessagesTitle: "workspace.switchToMessagesTitle",
    switchToTerminalTitle: "workspace.switchToTerminalTitle",
  },
  messagesPane: {
    copyMessageTitle: "messagesPane.copyMessageTitle",
    readFromHereTitle: "messagesPane.readFromHereTitle",
    playAudioSettingsTitle: "messagesPane.playAudioSettingsTitle",
    audioSettingsHeading: "messagesPane.audioSettingsHeading",
    dismissError: "messagesPane.dismissError",
    showMore: "messagesPane.showMore",
    showLess: "messagesPane.showLess",
    fileNotPreviewable: "messagesPane.fileNotPreviewable",
    fileOpenFailed: "messagesPane.fileOpenFailed",
    searchMessagesTitle: "messagesPane.searchMessagesTitle",
    jumpToMessageTitle: "messagesPane.jumpToMessageTitle",
    prevMatchTitle: "messagesPane.prevMatchTitle",
    prevMessageTitle: "messagesPane.prevMessageTitle",
    nextMatchTitle: "messagesPane.nextMatchTitle",
    nextMessageTitle: "messagesPane.nextMessageTitle",
    refreshTitle: "messagesPane.refreshTitle",
    noEvents: "messagesPane.noEvents",
    newMessages: "messagesPane.newMessages",
    newMessages_other: "messagesPane.newMessages_other",
    jumpToBottomAria: "messagesPane.jumpToBottomAria",
  },
  terminalLauncher: {
    newTerminal: "terminalLauncher.newTerminal",
    emptyShell: "terminalLauncher.emptyShell",
    emptyShellDescription: "terminalLauncher.emptyShellDescription",
    shortcuts: "terminalLauncher.shortcuts",
    customCommand: "terminalLauncher.customCommand",
    commandPlaceholder: "terminalLauncher.commandPlaceholder",
    launch: "terminalLauncher.launch",
    sessionOptions: "terminalLauncher.sessionOptions",
    backendLabel: "terminalLauncher.backendLabel",
    timeoutLabel: "terminalLauncher.timeoutLabel",
    persistentHint: "terminalLauncher.persistentHint",
    creating: "terminalLauncher.creating",
  },
  settings: {
    title: "settings.title",
    eyebrow: "settings.eyebrow",
    sidebarAria: "settings.sidebarAria",
    tabs: {
      sessions: {
        label: "settings.tabs.sessions.label",
        shortLabel: "settings.tabs.sessions.shortLabel",
        description: "settings.tabs.sessions.description",
      },
      workspace: {
        label: "settings.tabs.workspace.label",
        shortLabel: "settings.tabs.workspace.shortLabel",
        description: "settings.tabs.workspace.description",
      },
      voiceInput: {
        label: "settings.tabs.voiceInput.label",
        shortLabel: "settings.tabs.voiceInput.shortLabel",
        description: "settings.tabs.voiceInput.description",
      },
      voiceOutput: {
        label: "settings.tabs.voiceOutput.label",
        shortLabel: "settings.tabs.voiceOutput.shortLabel",
        description: "settings.tabs.voiceOutput.description",
      },
      shortcuts: {
        label: "settings.tabs.shortcuts.label",
        shortLabel: "settings.tabs.shortcuts.shortLabel",
        description: "settings.tabs.shortcuts.description",
      },
      newPaneDefaults: {
        label: "settings.tabs.newPaneDefaults.label",
        shortLabel: "settings.tabs.newPaneDefaults.shortLabel",
        description: "settings.tabs.newPaneDefaults.description",
      },
      integrations: {
        label: "settings.tabs.integrations.label",
        shortLabel: "settings.tabs.integrations.shortLabel",
        description: "settings.tabs.integrations.description",
      },
    },
    integrationsSection: {
      eyebrow: "settings.integrationsSection.eyebrow",
      title: "settings.integrationsSection.title",
      description: "settings.integrationsSection.description",
    },
    newPaneDefaultsSection: {
      eyebrow: "settings.newPaneDefaultsSection.eyebrow",
      title: "settings.newPaneDefaultsSection.title",
      description: "settings.newPaneDefaultsSection.description",
      plusButtonLabel: "settings.newPaneDefaultsSection.plusButtonLabel",
      plusButtonHint: "settings.newPaneDefaultsSection.plusButtonHint",
      launcher: "settings.newPaneDefaultsSection.launcher",
      emptyTerminal: "settings.newPaneDefaultsSection.emptyTerminal",
    },
    workspaceSection: {
      eyebrow: "settings.workspaceSection.eyebrow",
      title: "settings.workspaceSection.title",
      description: "settings.workspaceSection.description",
      paneLayoutLabel: "settings.workspaceSection.paneLayoutLabel",
      paneLayoutHint: "settings.workspaceSection.paneLayoutHint",
      grid: "settings.workspaceSection.grid",
      tabs: "settings.workspaceSection.tabs",
      sidebar: "settings.workspaceSection.sidebar",
      mobileToolbarLabel: "settings.workspaceSection.mobileToolbarLabel",
      mobileToolbarHint: "settings.workspaceSection.mobileToolbarHint",
      compact: "settings.workspaceSection.compact",
      expanded: "settings.workspaceSection.expanded",
      minimapLabel: "settings.workspaceSection.minimapLabel",
      minimapHint: "settings.workspaceSection.minimapHint",
      keepAwakeLabel: "settings.workspaceSection.keepAwakeLabel",
      wakeLockDefault: "settings.workspaceSection.wakeLockDefault",
      wakeLockActive: "settings.workspaceSection.wakeLockActive",
      wakeLockUnsupported: "settings.workspaceSection.wakeLockUnsupported",
      wakeLockDenied: "settings.workspaceSection.wakeLockDenied",
      wakeLockReleased: "settings.workspaceSection.wakeLockReleased",
    },
    sessionsSection: {
      eyebrow: "settings.sessionsSection.eyebrow",
      title: "settings.sessionsSection.title",
      description: "settings.sessionsSection.description",
      defaultsTitle: "settings.sessionsSection.defaultsTitle",
      defaultsHint: "settings.sessionsSection.defaultsHint",
      defaultBackendLabel: "settings.sessionsSection.defaultBackendLabel",
      defaultTimeoutLabel: "settings.sessionsSection.defaultTimeoutLabel",
      openTerminals: "settings.sessionsSection.openTerminals",
      openTerminalsHint: "settings.sessionsSection.openTerminalsHint",
      resetLayout: "settings.sessionsSection.resetLayout",
      noTerminalsOpen: "settings.sessionsSection.noTerminalsOpen",
      persistent: "settings.sessionsSection.persistent",
      noColor: "settings.sessionsSection.noColor",
      renamePane: "settings.sessionsSection.renamePane",
      moveUp: "settings.sessionsSection.moveUp",
      moveDown: "settings.sessionsSection.moveDown",
      focusPane: "settings.sessionsSection.focusPane",
      terminateSession: "settings.sessionsSection.terminateSession",
    },
    shortcutsSection: {
      eyebrow: "settings.shortcutsSection.eyebrow",
      title: "settings.shortcutsSection.title",
      description: "settings.shortcutsSection.description",
      profilesTitle: "settings.shortcutsSection.profilesTitle",
      profilesHint: "settings.shortcutsSection.profilesHint",
      newProfile: "settings.shortcutsSection.newProfile",
      loading: "settings.shortcutsSection.loading",
      empty: "settings.shortcutsSection.empty",
      saveChanges: "settings.shortcutsSection.saveChanges",
      deleteProfile: "settings.shortcutsSection.deleteProfile",
      removeShortcut: "settings.shortcutsSection.removeShortcut",
      addShortcut: "settings.shortcutsSection.addShortcut",
      labelPlaceholder: "settings.shortcutsSection.labelPlaceholder",
      commandPlaceholder: "settings.shortcutsSection.commandPlaceholder",
      newProfileName: "settings.shortcutsSection.newProfileName",
      defaultShortcutLabel: "settings.shortcutsSection.defaultShortcutLabel",
    },
    voiceOutputSection: {
      eyebrow: "settings.voiceOutputSection.eyebrow",
      title: "settings.voiceOutputSection.title",
      description: "settings.voiceOutputSection.description",
      statusLoadFailed: "settings.voiceOutputSection.statusLoadFailed",
      activeBackend: "settings.voiceOutputSection.activeBackend",
      activeBackendHint: "settings.voiceOutputSection.activeBackendHint",
      backendKokoro: "settings.voiceOutputSection.backendKokoro",
      backendBrowser: "settings.voiceOutputSection.backendBrowser",
      backendUnavailable: "settings.voiceOutputSection.backendUnavailable",
      preferenceAuto: "settings.voiceOutputSection.preferenceAuto",
      preferenceKokoro: "settings.voiceOutputSection.preferenceKokoro",
      preferenceBrowser: "settings.voiceOutputSection.preferenceBrowser",
      backendPreference: "settings.voiceOutputSection.backendPreference",
      backendPreferenceHint: "settings.voiceOutputSection.backendPreferenceHint",
      backendPreferenceAutoOption: "settings.voiceOutputSection.backendPreferenceAutoOption",
      autoSpeak: "settings.voiceOutputSection.autoSpeak",
      autoSpeakHint: "settings.voiceOutputSection.autoSpeakHint",
      startMuted: "settings.voiceOutputSection.startMuted",
      startMutedHint: "settings.voiceOutputSection.startMutedHint",
      runtimeChecks: "settings.voiceOutputSection.runtimeChecks",
      runtimeChecksRefreshing: "settings.voiceOutputSection.runtimeChecksRefreshing",
      runtimeChecksHint: "settings.voiceOutputSection.runtimeChecksHint",
      refresh: "settings.voiceOutputSection.refresh",
      testTts: "settings.voiceOutputSection.testTts",
      testTtsHint: "settings.voiceOutputSection.testTtsHint",
      testing: "settings.voiceOutputSection.testing",
      test: "settings.voiceOutputSection.test",
      testSucceeded: "settings.voiceOutputSection.testSucceeded",
      saveFailed: "settings.voiceOutputSection.saveFailed",
      playbackError: "settings.voiceOutputSection.playbackError",
      claudeHookPrefix: "settings.voiceOutputSection.claudeHookPrefix",
      registered: "settings.voiceOutputSection.registered",
      notRegistered: "settings.voiceOutputSection.notRegistered",
      hookStatusCode: "settings.voiceOutputSection.hookStatusCode",
      kokoroStatusPrefix: "settings.voiceOutputSection.kokoroStatusPrefix",
      kokoroStatusUnavailable: "settings.voiceOutputSection.kokoroStatusUnavailable",
      browserAudioPrefix: "settings.voiceOutputSection.browserAudioPrefix",
      browserAudioReady: "settings.voiceOutputSection.browserAudioReady",
      browserAudioBlocked: "settings.voiceOutputSection.browserAudioBlocked",
      lastHookRouting: "settings.voiceOutputSection.lastHookRouting",
      lastHookRoutingNone: "settings.voiceOutputSection.lastHookRoutingNone",
      lastHookAck: "settings.voiceOutputSection.lastHookAck",
      lastHookAckNone: "settings.voiceOutputSection.lastHookAckNone",
      lastTailerRouting: "settings.voiceOutputSection.lastTailerRouting",
      lastTailerRoutingNone: "settings.voiceOutputSection.lastTailerRoutingNone",
      lastTailerAck: "settings.voiceOutputSection.lastTailerAck",
      lastTailerAckNone: "settings.voiceOutputSection.lastTailerAckNone",
      lastPlayback: "settings.voiceOutputSection.lastPlayback",
      lastPlaybackNone: "settings.voiceOutputSection.lastPlaybackNone",
      playbackTimestamp: "settings.voiceOutputSection.playbackTimestamp",
      backendUnknown: "settings.voiceOutputSection.backendUnknown",
      appended: "settings.voiceOutputSection.appended",
      skipped: "settings.voiceOutputSection.skipped",
      hookSettingsPath: "settings.voiceOutputSection.hookSettingsPath",
      kokoroVoice: "settings.voiceOutputSection.kokoroVoice",
      kokoroVoiceHint: "settings.voiceOutputSection.kokoroVoiceHint",
      kokoroSpeed: "settings.voiceOutputSection.kokoroSpeed",
      kokoroSpeedHint: "settings.voiceOutputSection.kokoroSpeedHint",
      summarizationEyebrow: "settings.voiceOutputSection.summarizationEyebrow",
      summarizationTitle: "settings.voiceOutputSection.summarizationTitle",
      summarizationDescription: "settings.voiceOutputSection.summarizationDescription",
      summarizationLoadFailed: "settings.voiceOutputSection.summarizationLoadFailed",
      summarizeToggle: "settings.voiceOutputSection.summarizeToggle",
      summarizeToggleHint: "settings.voiceOutputSection.summarizeToggleHint",
      wordThreshold: "settings.voiceOutputSection.wordThreshold",
      wordThresholdHint: "settings.voiceOutputSection.wordThresholdHint",
      chars: "settings.voiceOutputSection.chars",
      summarizationLevel: "settings.voiceOutputSection.summarizationLevel",
      summarizationLevelHint: "settings.voiceOutputSection.summarizationLevelHint",
      levelLightOption: "settings.voiceOutputSection.levelLightOption",
      levelModerateOption: "settings.voiceOutputSection.levelModerateOption",
      levelHeavyOption: "settings.voiceOutputSection.levelHeavyOption",
      model: "settings.voiceOutputSection.model",
      modelHint: "settings.voiceOutputSection.modelHint",
      browserVoice: "settings.voiceOutputSection.browserVoice",
      browserVoiceHint: "settings.voiceOutputSection.browserVoiceHint",
      systemDefault: "settings.voiceOutputSection.systemDefault",
      browserRate: "settings.voiceOutputSection.browserRate",
      browserRateHint: "settings.voiceOutputSection.browserRateHint",
      browserPitch: "settings.voiceOutputSection.browserPitch",
      browserPitchHint: "settings.voiceOutputSection.browserPitchHint",
    },
  },
  appearance: {
    title: "appearance.title",
    headerColorHeading: "appearance.headerColorHeading",
    noColorTitle: "appearance.noColorTitle",
    terminalThemeHeading: "appearance.terminalThemeHeading",
    fontSizeHeading: "appearance.fontSizeHeading",
    applyToAll: "appearance.applyToAll",
  },
  audioSettings: {
    volume: "audioSettings.volume",
    muted: "audioSettings.muted",
    mute: "audioSettings.mute",
    muteAria: "audioSettings.muteAria",
    unmuteAria: "audioSettings.unmuteAria",
    muteTitle: "audioSettings.muteTitle",
    unmuteTitle: "audioSettings.unmuteTitle",
    speed: "audioSettings.speed",
  },
  playbackMode: {
    summarized: "playbackMode.summarized",
    original: "playbackMode.original",
    summarize: "playbackMode.summarize",
    light: "playbackMode.light",
    moderate: "playbackMode.moderate",
    heavy: "playbackMode.heavy",
    lightHint: "playbackMode.lightHint",
    moderateHint: "playbackMode.moderateHint",
    heavyHint: "playbackMode.heavyHint",
    summaryTitle: "playbackMode.summaryTitle",
    originalTitle: "playbackMode.originalTitle",
    summarizeTitle: "playbackMode.summarizeTitle",
  },
} as const;

export type Strings = typeof strings;
