// Package credentialuse is the BAS side of the password-manager browser
// boundary. It validates an already-authorized session policy before an action
// can reach the normal workflow executor.
package credentialuse

import (
	"errors"
	"fmt"
	"net/url"
	"strings"

	basactions "github.com/vrooli/vrooli/packages/proto/gen/go/browser-automation-studio/v1/actions"
	credentialusev1 "github.com/vrooli/vrooli/packages/proto/gen/go/browser-automation-studio/v1/credential_use"
)

var (
	ErrOriginChanged       = errors.New("credential browser origin changed; new authorization required")
	ErrDocumentChanged     = errors.New("credential browser document changed")
	ErrActionDenied        = errors.New("credential browser action is denied")
	ErrUnsupportedExposure = errors.New("credential browser exposure class is unsupported")
)

// ValidateAction rejects BAS operations that would hand a protected page's
// secret-bearing state to the ordinary agent workflow. Credential input is
// generated by the trusted executor and therefore is intentionally absent
// from this action surface.
func ValidateAction(policy *credentialusev1.BrowserSessionPolicy, action *basactions.ActionDefinition, currentOrigin, currentDocument string) error {
	if policy == nil || action == nil {
		return ErrActionDenied
	}
	if policy.GetExposureClass() == credentialusev1.BrowserExposureClass_BROWSER_EXPOSURE_CLASS_UNRESTRICTED_SESSION {
		return ErrUnsupportedExposure
	}
	if policy.GetExposureClass() != credentialusev1.BrowserExposureClass_BROWSER_EXPOSURE_CLASS_PROTECTED {
		return ErrUnsupportedExposure
	}
	origin, err := normalizeOrigin(policy.GetOrigin())
	if err != nil {
		return err
	}
	observed, err := normalizeOrigin(currentOrigin)
	if err != nil || observed != origin {
		return ErrOriginChanged
	}
	if strings.TrimSpace(currentDocument) == "" || currentDocument != policy.GetDocumentId() {
		return ErrDocumentChanged
	}
	if !operationAllowed(policy.GetAllowedOperations(), actionOperation(action)) {
		return fmt.Errorf("%w: operation %s is not approved", ErrActionDenied, actionOperation(action))
	}
	if nav := action.GetNavigate(); nav != nil {
		navigation, navErr := normalizeOrigin(nav.GetUrl())
		if navErr != nil || navigation != origin {
			return ErrOriginChanged
		}
	}
	switch action.GetType() {
	case basactions.ActionType_ACTION_TYPE_EVALUATE,
		basactions.ActionType_ACTION_TYPE_EXTRACT,
		basactions.ActionType_ACTION_TYPE_COOKIE_STORAGE:
		return fmt.Errorf("%w: protected credential sessions deny DOM evaluation, extraction, and cookies", ErrActionDenied)
	default:
		return nil
	}
}

func actionOperation(action *basactions.ActionDefinition) string {
	switch action.GetType() {
	case basactions.ActionType_ACTION_TYPE_NAVIGATE:
		return "navigate"
	case basactions.ActionType_ACTION_TYPE_CLICK:
		return "click"
	case basactions.ActionType_ACTION_TYPE_INPUT:
		return "input"
	case basactions.ActionType_ACTION_TYPE_ASSERT:
		return "assert"
	case basactions.ActionType_ACTION_TYPE_SUBFLOW:
		return "subflow"
	default:
		return strings.ToLower(strings.TrimPrefix(action.GetType().String(), "ACTION_TYPE_"))
	}
}

func operationAllowed(allowed []string, operation string) bool {
	for _, candidate := range allowed {
		if strings.EqualFold(strings.TrimSpace(candidate), operation) {
			return true
		}
	}
	return false
}

func normalizeOrigin(raw string) (string, error) {
	parsed, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" || parsed.User != nil || (parsed.Path != "" && parsed.Path != "/") || parsed.RawQuery != "" || parsed.Fragment != "" {
		return "", errors.New("credential browser origin must be an absolute http(s) origin")
	}
	return strings.ToLower(parsed.Scheme) + "://" + strings.ToLower(parsed.Host), nil
}
