import { cleanup, screen } from "@testing-library/react";
import { renderWithProviders as render } from "../../test-utils";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ErrorBoundary } from "./error-boundary";
import { defaultApiClient } from "../../lib/api-client";
function BrokenChild({error}:{error:Error}):never { throw error; }
beforeEach(()=>{vi.spyOn(console,"error").mockImplementation(()=>{});for(const method of ["get","post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Forbidden boundary transport"));vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("Forbidden boundary fetch")));});
afterEach(()=>{cleanup();try{for(const method of ["get","post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();}finally{vi.restoreAllMocks();vi.unstubAllGlobals();}});
describe("runtime boundary contains renderer failures without another request",()=>{
 it("keeps healthy children visible without reporting a crash",()=>{const onError=vi.fn();render(<ErrorBoundary onError={onError}><p>Owner healthy content</p></ErrorBoundary>);expect(screen.getByText("Owner healthy content")).toBeVisible();expect(onError).not.toHaveBeenCalled();expect(console.error).not.toHaveBeenCalled();});
 it("catches the original runtime error and emits exact structured correlation",()=>{const error=new Error("Fixture literal <script>failure</script>");const onError=vi.fn();render(<ErrorBoundary onError={onError}><BrokenChild error={error}/></ErrorBoundary>);expect(screen.getByRole("heading",{name:"Something went wrong"})).toBeVisible();expect(screen.getByRole("button",{name:"Refresh Page"})).toBeVisible();expect(onError).toHaveBeenCalledTimes(1);expect(onError).toHaveBeenCalledWith(error,expect.objectContaining({componentStack:expect.stringContaining("BrokenChild")}));const logs=vi.mocked(console.error).mock.calls.filter(row=>row[0]==="[ErrorBoundary] Runtime error caught:");expect(logs).toHaveLength(1);const report=JSON.parse(String(logs[0]![1]));expect(report).toMatchObject({name:"Error",message:"Fixture literal <script>failure</script>",componentStack:expect.stringContaining("BrokenChild"),errorId:expect.stringMatching(/^err/),timestamp:expect.any(String)});expect(Number.isNaN(Date.parse(report.timestamp))).toBe(false);expect(document.querySelector("script")).toBeNull();});
 it("uses the supplied fallback while retaining original diagnostics callback",()=>{const error=new Error("Fixture custom fallback failure");const onError=vi.fn();render(<ErrorBoundary fallback={<p>Owner recovery instructions</p>} onError={onError}><BrokenChild error={error}/></ErrorBoundary>);expect(screen.getByText("Owner recovery instructions")).toBeVisible();expect(screen.queryByRole("heading",{name:"Something went wrong"})).toBeNull();expect(onError).toHaveBeenCalledTimes(1);expect(onError.mock.calls[0]![0]).toBe(error);});
 it("contains the failure when no optional observer is installed",()=>{render(<ErrorBoundary fallback={<p>Owner contained failure</p>}><BrokenChild error={new Error("Fixture no observer")}/></ErrorBoundary>);expect(screen.getByText("Owner contained failure")).toBeVisible();expect(vi.mocked(console.error).mock.calls.some(row=>row[0]==="[ErrorBoundary] Runtime error caught:")).toBe(true);});
});
