import { useState } from "react";
import { cleanup, fireEvent, screen } from "@testing-library/react";
import { renderWithProviders as render } from "../../test-utils";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { FileTree, type TreeFile } from "./file-tree";
import { defaultApiClient } from "../../lib/api-client";
const files: TreeFile[]=[{name:"selected folder",path:"folder",type:"directory",children:[{name:"first",path:"folder/first",type:"file"},{name:"nested",path:"folder/nested",type:"directory",children:[{name:"second",path:"folder/nested/second",type:"file"}]}]},{name:"empty",path:"empty",type:"directory"},{name:"outside",path:"outside",type:"file"}];
function mount(initial:string[]=[],observer=vi.fn(),accept=true){function Owner(){const [selected,setSelected]=useState(new Set(initial));return <><output data-testid="owner-selection">{JSON.stringify([...selected].sort())}</output><FileTree files={files} selectionMode="checkbox" selectedPaths={selected} onSelectionChange={next=>{observer([...next].sort());if(accept)setSelected(next);}}/></>;}render(<Owner/>);return observer;}
function checkbox(path:string){return screen.getByTestId(`file-tree-checkbox-${path}`);}
beforeEach(()=>{for(const method of ["get","post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Forbidden selection transport"));vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("Forbidden selection fetch")));});
afterEach(()=>{cleanup();try{for(const method of ["get","post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();}finally{vi.restoreAllMocks();vi.unstubAllGlobals();}});
describe("controlled file preservation selection is exact and local",()=>{
 it("selects every nested file in one owner update while preserving unrelated selection",()=>{const observer=mount(["outside"]);fireEvent.click(checkbox("folder"));expect(observer.mock.calls).toEqual([[["folder/first","folder/nested/second","outside"]]]);expect(screen.getByTestId("owner-selection")).toHaveTextContent('["folder/first","folder/nested/second","outside"]');expect(checkbox("folder")).toHaveAttribute("aria-checked","true");expect(screen.queryByText("first")).toBeNull();});
 it("deselects all checked descendants in one owner update without clearing unrelated files",()=>{const observer=mount(["folder/first","folder/nested/second","outside"]);fireEvent.click(checkbox("folder"));expect(observer.mock.calls).toEqual([[["outside"]]]);expect(checkbox("folder")).toHaveAttribute("aria-checked","false");});
 it("completes a mixed selection through Enter without dropping the previously selected descendant",()=>{const observer=mount(["folder/first","outside"]);fireEvent.keyDown(checkbox("folder"),{key:"Enter"});expect(observer.mock.calls).toEqual([[["folder/first","folder/nested/second","outside"]]]);expect(checkbox("folder")).toHaveAttribute("aria-checked","true");});
 it("lets Space select and unselect one file through exact parent state",()=>{const observer=mount();fireEvent.keyDown(checkbox("outside"),{key:" "});expect(checkbox("outside")).toHaveAttribute("aria-checked","true");fireEvent.keyDown(checkbox("outside"),{key:" "});expect(observer.mock.calls).toEqual([[["outside"]],[[]]]);expect(checkbox("outside")).toHaveAttribute("aria-checked","false");});
 it("does not select an empty directory or react to an unrelated key",()=>{const observer=mount(["outside"]);fireEvent.click(checkbox("empty"));fireEvent.keyDown(checkbox("folder"),{key:"Escape"});expect(observer).not.toHaveBeenCalled();expect(screen.getByTestId("owner-selection")).toHaveTextContent('["outside"]');});
 it("does not pretend an owner rejected group update was committed",()=>{const observer=mount(["outside"],vi.fn(),false);fireEvent.click(checkbox("folder"));expect(observer.mock.calls).toEqual([[["folder/first","folder/nested/second","outside"]]]);expect(screen.getByTestId("owner-selection")).toHaveTextContent('["outside"]');expect(checkbox("folder")).toHaveAttribute("aria-checked","false");});
 it("keeps directory expansion separate from checkbox selection",()=>{const observer=mount();fireEvent.click(screen.getByTestId("file-tree-button-folder"));expect(screen.getByText("first")).toBeVisible();expect(observer).not.toHaveBeenCalled();fireEvent.click(checkbox("folder/first"));expect(observer.mock.calls).toEqual([[["folder/first"]]]);expect(screen.getByText("first")).toBeVisible();});
});
