import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, screen } from "@testing-library/react";
import { PageErrorBoundary } from "./page-error-boundary";
import { createTestQueryClient, renderWithProviders } from "../../test-utils";
import { defaultApiClient } from "../../lib/api-client";
// Real boundary/diagnostics and query cache; throwing child is a controlled
// render fault. Only final browser-navigation/reload affordances are observed.
let failing:boolean;let message:string;let marker:string|null;
const clients:ReturnType<typeof createTestQueryClient>[]=[];const views:{unmount():void}[]=[];
function Child(){if(failing)throw new Error(message);return <div>Recovered owner page</div>;}
function mount(fallback?:React.ReactNode){const client=createTestQueryClient();clients.push(client);client.setQueryDefaults(["unrelated-owner"],{gcTime:Infinity});client.setQueryData(["unrelated-owner"],{value:"preserved"});const view=renderWithProviders(<PageErrorBoundary pageName="Fixture owner" fallback={fallback}><Child/></PageErrorBoundary>,{queryClient:client});views.push(view);return {view,client};}
function browserLocation(location:{href:string;reload:()=>void},action:()=>void){const original=window;const fixture=Object.create(original) as Window;Object.defineProperty(fixture,"location",{value:location});vi.stubGlobal("window",fixture);try{action();}finally{vi.stubGlobal("window",original);}}
beforeEach(()=>{failing=true;message="Fixture render fault";marker=sessionStorage.getItem("vrooli:chunk-reload-at");vi.spyOn(console,"error").mockImplementation(()=>{});for(const method of ["get","post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Unexpected boundary request"));vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("Unexpected boundary fetch")));});
afterEach(()=>{try{views.splice(0).forEach(v=>v.unmount());cleanup();for(const client of clients)expect(client.getQueryData(["unrelated-owner"])).toEqual({value:"preserved"});for(const method of ["get","post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();}finally{clients.splice(0).forEach(c=>c.clear());vi.restoreAllMocks();vi.unstubAllGlobals();if(marker===null)sessionStorage.removeItem("vrooli:chunk-reload-at");else sessionStorage.setItem("vrooli:chunk-reload-at",marker);}});
describe("actual page fault recovery",()=>{
 it("presents a contained owner fault with linked diagnostic evidence and no requests",()=>{mount();expect(screen.getByRole("heading",{name:"Fixture owner encountered an error"})).toBeVisible();expect(screen.getByText(/Error ID: page_err/)).toBeVisible();const report=vi.mocked(console.error).mock.calls.find(([label])=>label==="[PageErrorBoundary] Error caught:");expect(report).toBeDefined();const payload=JSON.parse(String(report?.[1]));expect(payload).toMatchObject({page:"Fixture owner",name:"Error",message});expect(payload.componentStack).toContain("Child");expect(screen.getByText(/Error ID:/)).toHaveTextContent(payload.errorId);});
 it("recovers the original child on explicit retry while preserving unrelated cache",()=>{const {client}=mount();const owner=client.getQueryData(["unrelated-owner"]);failing=false;fireEvent.click(screen.getByRole("button",{name:"Try Again"}));expect(screen.getByText("Recovered owner page")).toBeVisible();expect(screen.queryByRole("heading",{name:"Fixture owner encountered an error"})).toBeNull();expect(client.getQueryData(["unrelated-owner"])).toBe(owner);});
 it("reports a new still-failing render after explicit retry rather than claiming recovery",()=>{mount();message="New fixture fault";fireEvent.click(screen.getByRole("button",{name:"Try Again"}));expect(screen.getByRole("heading",{name:"Fixture owner encountered an error"})).toBeVisible();expect(screen.queryByText("Recovered owner page")).toBeNull();const reports=vi.mocked(console.error).mock.calls.filter(([label])=>label==="[PageErrorBoundary] Error caught:");expect(reports).toHaveLength(2);expect(JSON.parse(String(reports[1]?.[1])).message).toBe(message);});
 it("honors a caller-supplied fallback without adding recovery effects",()=>{mount(<div>Owner-supplied fault fallback</div>);expect(screen.getByText("Owner-supplied fault fallback")).toBeVisible();expect(screen.queryByRole("button",{name:"Try Again"})).toBeNull();expect(screen.queryByRole("button",{name:"Go Home"})).toBeNull();});
 it("clears the contained fault and requests the exact graph home through browser navigation",()=>{const {client}=mount();const location={href:"https://fixture.invalid/failed-page",reload:vi.fn()};failing=false;browserLocation(location,()=>fireEvent.click(screen.getByRole("button",{name:"Go Home"})));expect(location.href).toBe("/graph");expect(location.reload).not.toHaveBeenCalled();expect(screen.getByText("Recovered owner page")).toBeVisible();expect(client.getQueryData(["unrelated-owner"])).toEqual({value:"preserved"});});
 it("retains rate-limited stale-chunk context and offers one explicit browser reload",()=>{message="Failed to fetch dynamically imported module: fixture chunk";sessionStorage.setItem("vrooli:chunk-reload-at",String(Date.now()));mount();expect(screen.getByRole("heading",{name:"A new version is available"})).toBeVisible();expect(screen.queryByRole("button",{name:"Try Again"})).toBeNull();const location={href:"https://fixture.invalid/failed-page",reload:vi.fn()};browserLocation(location,()=>fireEvent.click(screen.getByRole("button",{name:"Reload"})));expect(location.reload).toHaveBeenCalledOnce();expect(location.href).toBe("https://fixture.invalid/failed-page");});
});
