// Package memberflow defines and validates the per-member message-flow data
// layer (topics.json) that lives at:
//
//	scenarios/prompt-manager/store/teams/<team>/members/<member>/topics.json
//
// The schema declares, structurally, how a single team member produces and
// consumes work via topic-prefixed channels. It is the machine-readable
// counterpart to prose router skills and feeds the heartbeat builder's
// generated Inbox Flow section.
//
// DOC: docs/agent-system/TOPICS_SCHEMA.md
package memberflow

import (
	"errors"
	"fmt"
	"strings"
)

// DestinationKind enumerates the kinds of sinks an output entry can target.
type DestinationKind string

const (
	DestinationKnowledge     DestinationKind = "knowledge"
	DestinationPORFile       DestinationKind = "por_file"
	DestinationSkillProposal DestinationKind = "skill_proposal"
	DestinationBacklog       DestinationKind = "backlog"
)

func (k DestinationKind) Valid() bool {
	switch k {
	case DestinationKnowledge, DestinationPORFile, DestinationSkillProposal, DestinationBacklog:
		return true
	default:
		return false
	}
}

// LoopKind classifies a member's heartbeat loop by the single property
// that determines what it must declare: **where the loop keeps its memory
// between heartbeats.**
//
// The taxonomy is generated by that question rather than asserted, and it
// yields exactly one obligation. A queue loop remembers in its intake's
// unrouted set; a reactive loop remembers in the pending-artifact set it
// reviews; a generative loop has no population to cover and so has nothing
// to remember. A sweep loop is the only kind whose memory has no natural
// home — which is why a sweep, and only a sweep, must declare a coverage
// ledger (see ruleSweepWithoutLedger).
//
// DOC: docs/agent-system/TOPICS_SCHEMA.md § Loop kinds.
type LoopKind string

const (
	// LoopQueue drains a declared intake. The unrouted set is the record
	// of what remains; draining an entry is what marks it done.
	LoopQueue LoopKind = "queue"

	// LoopReactive is triggered by a peer artifact awaiting review —
	// typically pending work items. The pending/resolved split is the
	// record. Contrarian members are the canonical instance.
	LoopReactive LoopKind = "reactive"

	// LoopSweep iterates a standing population that never empties (every
	// skill, every agent, every scenario). Nothing marks a target done,
	// so without a ledger the loop re-picks the head of its priority
	// ladder forever and never reaches the tail.
	LoopSweep LoopKind = "sweep"

	// LoopGenerative produces on a cadence with no population to cover.
	// Declaring it is a positive statement ("nothing to remember"),
	// which is why the enum has no null member.
	LoopGenerative LoopKind = "generative"
)

func (k LoopKind) Valid() bool {
	switch k {
	case LoopQueue, LoopReactive, LoopSweep, LoopGenerative:
		return true
	default:
		return false
	}
}

// IntakeEntry declares one topic-prefix this member drains.
type IntakeEntry struct {
	// Prefix is a topic-prefix string. Wildcard suffix `/*` indicates a prefix
	// match; a string without `/*` matches only that exact topic.
	Prefix string `json:"prefix"`

	// Taxonomy is the id of the signal taxonomy that owns this prefix. The
	// heartbeat builder resolves it to docs/<domain>/<id>.json (the JSON
	// sidecar) to render the Inbox Flow section. Required after migration.
	// During the inbox-flow refactor transition, an empty Taxonomy surfaces
	// as a `missing_taxonomy` warning rather than a hard error.
	Taxonomy string `json:"taxonomy,omitempty"`

	// ClassifierSkill is the optional, portable judgment skill the member
	// runs on each entry to assign signal_type, evidence_strength, and
	// honesty_flags. Optional: when the prefix carries a deterministic
	// signal_type (e.g., the topic itself names the type), no classifier is
	// needed.
	ClassifierSkill string `json:"classifier_skill,omitempty"`

	// SourceTeam names the team whose member writes this prefix, when the flow
	// is cross-team. Empty / nil means same-team or external producer.
	//
	// The literal "*" (SourceTeamWildcard) means "any team's members may
	// write" — used for universal-source intakes such as bug-inbox where
	// every agent on every team may report. The validator skips
	// orphan_input for "*" entries; a paired wildcard_source_misuse warning
	// fires when external_producers is empty (the producer-side anchor
	// must be documented).
	SourceTeam *string `json:"source_team,omitempty"`
}

// SourceTeamWildcard is the literal value of IntakeEntry.SourceTeam that
// declares a universal-source intake — any team's members may write the
// prefix. See IntakeEntry.SourceTeam for semantics. The same wildcard is
// accepted on RequiredReadEntry.SourceTeam and EvidenceConsumedEntry.SourceTeam.
const SourceTeamWildcard = "*"

// RequiredReadEntry declares one topic-prefix this member must read on every
// heartbeat for required-memory context. The heartbeat builder renders these
// prefixes into the agent prompt's "Required Memory" section so the agent
// always sees current state when it ticks.
//
// Where IntakeEntry says "I drain new entries on this prefix (and may
// classify them)", RequiredReadEntry says "I need this prefix's recent
// entries in my prompt every tick — I'm not draining or routing them." A
// single member commonly carries both: an intake[] for actionable signals
// and a required_read[] for always-on context.
//
// Read relationships used to live on team.json's per-member contract
// (under a member-level field that was invisible to the validator); they
// now live here so a single load surfaces every read relationship to the
// consumer-set used by ruleOrphanOutput (see consumer_set.go).
type RequiredReadEntry struct {
	// Prefix is a topic-prefix string. Wildcard suffix `/*` indicates a
	// prefix match; a string without `/*` matches only that exact topic.
	Prefix string `json:"prefix"`

	// SourceTeam names the team whose member writes this prefix when the
	// flow is cross-team. Empty / nil means same-team or external
	// producer. Mirrors IntakeEntry.SourceTeam semantics, including the
	// "*" (SourceTeamWildcard) value for universal-source reads.
	SourceTeam *string `json:"source_team,omitempty"`

	// Comment is freeform context for human readers (e.g., "needed to cite
	// most recent campaign-draft on every publish proposal"). Optional;
	// the validator does not interpret it.
	Comment string `json:"comment,omitempty"`
}

// EvidenceConsumedEntry declares one topic-prefix this member reads as
// evidence when authoring work.
//
// Where IntakeEntry says "I drain new entries", EvidenceConsumedEntry says
// "when authoring work, I cite entries from this prefix."
type EvidenceConsumedEntry struct {
	// Prefix is a topic-prefix string. Wildcard suffix `/*` indicates a
	// prefix match; a string without `/*` matches only that exact topic.
	Prefix string `json:"prefix"`

	// SourceTeam names the team whose member writes this prefix when the
	// flow is cross-team. Empty / nil means same-team or external
	// producer. Mirrors IntakeEntry.SourceTeam semantics.
	SourceTeam *string `json:"source_team,omitempty"`
}

// OutputEntry declares one topic-prefix this member writes.
type OutputEntry struct {
	// Prefix is a topic-prefix string. Wildcard suffix `/*` indicates a prefix
	// match.
	Prefix string `json:"prefix"`

	// DestinationKind names the surface type written. Required.
	DestinationKind DestinationKind `json:"destination_kind"`

	// DestinationTeam names the team that consumes this output, when the flow
	// is cross-team. Empty / nil means same-team or non-team sink (e.g., a
	// PoR file or backlog).
	DestinationTeam *string `json:"destination_team,omitempty"`

	// DestinationPath is the markdown path under docs/ when DestinationKind ==
	// DestinationPORFile. Required for por_file destinations; ignored
	// otherwise. The dangling_por_sink validation rule (Phase 3) checks the
	// file exists.
	DestinationPath *string `json:"destination_path,omitempty"`

	// Schema names the destination front-matter schema declared on the
	// producer's taxonomy (taxonomy.schemas.<schema>). Optional but
	// encouraged for knowledge destinations: it lets the heartbeat builder
	// surface the expected front-matter shape and lets the validator catch
	// drift between topics.json and the taxonomy PoR.
	Schema string `json:"schema,omitempty"`
}

// Topics is the full per-member declaration. Marshalled to/from
// topics.json. All top-level fields are optional; an empty object {} is valid
// and means "this member has no flow declarations."
//
// Field ordering follows the consumption-side → production-side flow:
// intake/required_read/evidence_consumed describe what the member reads;
// output describes what it writes; raises_work_items and
// external_producers are policy/anchor metadata.
type Topics struct {
	// LoopKind classifies where this member's loop keeps its memory
	// between heartbeats. Declared first because it frames every field
	// below it: it is what decides whether the read/write declarations
	// that follow are sufficient. Empty surfaces as a `loop_kind_missing`
	// warning during adoption rather than a hard error, so teams can
	// declare their own members instead of inheriting a guess.
	LoopKind LoopKind `json:"loop_kind,omitempty"`

	// Population names what a sweep iterates, as relationship-graph node
	// types (`skill`, `action`, `agent`, `team`, `scenario`). Meaningful
	// only when LoopKind is sweep. Its presence is what upgrades a ledger
	// from "did I already look at this" to a measurable coverage figure —
	// visited entries over population size — so a sweep that omits it is
	// correct but unmeasurable, and reports as such rather than silently
	// counting as covered. Omit when the population is not graph-resident
	// (a time-window over recent runs, for instance).
	//
	// A list rather than a single value: one member may sweep more than one
	// population, carrying a ledger per population. `team-agent-optimizer`
	// is the live instance, sweeping teams and agents on one ladder. By
	// convention the subject in each ledger prefix names its population
	// (`team-visited/*` covers `team`), which is how coverage is attributed
	// per population rather than pooled.
	Population []string `json:"population,omitempty"`

	Intake            []IntakeEntry           `json:"intake,omitempty"`
	RequiredRead      []RequiredReadEntry     `json:"required_read,omitempty"`
	EvidenceConsumed  []EvidenceConsumedEntry `json:"evidence_consumed,omitempty"`
	Output            []OutputEntry           `json:"output,omitempty"`
	RaisesWorkItems   bool                    `json:"raises_work_items,omitempty"`
	ExternalProducers []string                `json:"external_producers,omitempty"`
}

// IsEmpty reports whether the declaration has no content. An empty Topics is a
// positive declaration ("audited; no flow") rather than ambiguous absence.
//
// LoopKind and Population are deliberately excluded: they describe the loop,
// not its topic flow. A generative member legitimately declares a loop kind and
// no flow at all, and must still render as having no topic contract.
func (t Topics) IsEmpty() bool {
	return len(t.Intake) == 0 &&
		len(t.RequiredRead) == 0 &&
		len(t.EvidenceConsumed) == 0 &&
		len(t.Output) == 0 &&
		!t.RaisesWorkItems &&
		len(t.ExternalProducers) == 0
}

// Validate checks the Topics for shape errors that can be detected without
// cross-member context. Returns the first error encountered, or nil. Callers
// that want the full set of errors should call ValidateAll instead.
//
// Shape errors include:
//   - empty intake.prefix or malformed prefix
//   - empty output.prefix or unknown destination_kind
//   - destination_kind == por_file with empty destination_path
//
// Cross-member errors (orphan_input, conflicting_drain, unknown_taxonomy,
// missing_destination_schema, prose_topic_leak, etc.) require the full
// graph and are computed by Validate (validation.go), not by this method.
func (t Topics) Validate() error {
	errs := t.ValidateAll()
	if len(errs) == 0 {
		return nil
	}
	return errs[0]
}

// ValidateAll returns all shape errors detected. Used by tests; production
// callers typically want Validate() (first-error) for fast-fail.
func (t Topics) ValidateAll() []error {
	var errs []error

	for i, e := range t.Intake {
		if err := validateIntake(e); err != nil {
			errs = append(errs, fmt.Errorf("intake[%d]: %w", i, err))
		}
	}
	for i, e := range t.RequiredRead {
		if err := validateRequiredRead(e); err != nil {
			errs = append(errs, fmt.Errorf("required_read[%d]: %w", i, err))
		}
	}
	for i, e := range t.EvidenceConsumed {
		if err := validateEvidenceConsumed(e); err != nil {
			errs = append(errs, fmt.Errorf("evidence_consumed[%d]: %w", i, err))
		}
	}
	for i, e := range t.Output {
		if err := validateOutput(e); err != nil {
			errs = append(errs, fmt.Errorf("output[%d]: %w", i, err))
		}
	}
	return errs
}

func validateIntake(e IntakeEntry) error {
	if strings.TrimSpace(e.Prefix) == "" {
		return errors.New("prefix is required")
	}
	if !validPrefix(e.Prefix) {
		return fmt.Errorf("prefix %q is malformed", e.Prefix)
	}
	return nil
}

func validateRequiredRead(e RequiredReadEntry) error {
	if strings.TrimSpace(e.Prefix) == "" {
		return errors.New("prefix is required")
	}
	if !validPrefix(e.Prefix) {
		return fmt.Errorf("prefix %q is malformed", e.Prefix)
	}
	return nil
}

func validateEvidenceConsumed(e EvidenceConsumedEntry) error {
	if strings.TrimSpace(e.Prefix) == "" {
		return errors.New("prefix is required")
	}
	if !validPrefix(e.Prefix) {
		return fmt.Errorf("prefix %q is malformed", e.Prefix)
	}
	return nil
}

func validateOutput(e OutputEntry) error {
	if strings.TrimSpace(e.Prefix) == "" {
		return errors.New("prefix is required")
	}
	if !validPrefix(e.Prefix) {
		return fmt.Errorf("prefix %q is malformed", e.Prefix)
	}
	if !e.DestinationKind.Valid() {
		return fmt.Errorf("destination_kind %q is not one of: knowledge, por_file, skill_proposal, backlog", e.DestinationKind)
	}
	if e.DestinationKind == DestinationPORFile {
		if e.DestinationPath == nil || strings.TrimSpace(*e.DestinationPath) == "" {
			return errors.New("destination_path is required when destination_kind is por_file")
		}
	}
	return nil
}

// validPrefix enforces basic shape rules:
//   - non-empty
//   - no whitespace
//   - bare "*" is disallowed (would defeat overlap detection)
//   - "/*" suffix is the only allowed wildcard
//   - inner "*" (e.g. "foo/*/bar") is disallowed
func validPrefix(p string) bool {
	if p == "" || p == "*" {
		return false
	}
	if strings.ContainsAny(p, " \t\n") {
		return false
	}
	// strip a trailing /* if present
	core := strings.TrimSuffix(p, "/*")
	// the remainder must contain no '*' at all
	if strings.Contains(core, "*") {
		return false
	}
	return true
}

// topicSegmentIsPlaceholder reports whether one path segment is a `<name>`
// placeholder standing for a single real segment.
//
// TOPICS_SCHEMA.md teaches this form by example — a reviewer declares
// `review-evidence/<work-item-id>`, a curator routes to
// `friction-report/<scope>/<date>/<slug>` — and 27 declarations across five
// teams use it. Treating `<work-item-id>` as literal text makes every one of
// them match nothing, so the member reads as having declared no prefix at all.
func topicSegmentIsPlaceholder(seg string) bool {
	return len(seg) > 2 && strings.HasPrefix(seg, "<") && strings.HasSuffix(seg, ">")
}

// topicSegmentsUnify reports whether two single segments can name the same
// real segment. A placeholder unifies with anything at its position; two
// literals must be equal.
func topicSegmentsUnify(a, b string) bool {
	return a == b || topicSegmentIsPlaceholder(a) || topicSegmentIsPlaceholder(b)
}

// Overlap reports whether two prefixes share at least one matchable topic.
//
// Semantics (matches docs/agent-system/TOPICS_SCHEMA.md):
//   - Equal prefixes always overlap.
//   - "foo/*" overlaps "foo/bar" (the wildcard is wider).
//   - "foo/bar/*" overlaps "foo/*" (the wildcard is wider).
//   - "foo/bar/*" does not overlap "foo/baz/*".
//   - Exact prefixes (no /*) overlap only with equal exact prefixes or with
//     wildcards whose stripped form is a prefix.
//   - A `<name>` segment matches any one segment, so
//     "review-evidence/<work-item-id>" overlaps "review-evidence/work-42".
//
// Comparison is segment-wise rather than by raw string prefix. For inputs
// carrying no placeholder the result is identical to plain string matching:
// a shorter prefix still only reaches a longer one through a trailing "/*".
func Overlap(a, b string) bool {
	aWild := strings.HasSuffix(a, "/*")
	bWild := strings.HasSuffix(b, "/*")
	aSegs := strings.Split(strings.TrimSuffix(a, "/*"), "/")
	bSegs := strings.Split(strings.TrimSuffix(b, "/*"), "/")

	shared := len(aSegs)
	if len(bSegs) < shared {
		shared = len(bSegs)
	}
	for i := 0; i < shared; i++ {
		if !topicSegmentsUnify(aSegs[i], bSegs[i]) {
			return false
		}
	}

	switch {
	case len(aSegs) == len(bSegs):
		return true
	case len(aSegs) < len(bSegs):
		// a is the shorter pattern; it only reaches deeper topics if it is
		// declared open-ended.
		return aWild
	default:
		return bWild
	}
}
