-- Products, subscriptions, credits, and payment operations.
CREATE TABLE IF NOT EXISTS bundle_products (id SERIAL PRIMARY KEY, bundle_key VARCHAR(100) UNIQUE NOT NULL, bundle_name VARCHAR(255) NOT NULL, stripe_product_id VARCHAR(255) UNIQUE NOT NULL, credits_per_usd BIGINT NOT NULL, display_credits_multiplier NUMERIC(12,6) DEFAULT 1.0, display_credits_label VARCHAR(50) DEFAULT 'credits', environment VARCHAR(50) DEFAULT 'production', metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_bundle_products_env ON bundle_products(environment);
CREATE TABLE IF NOT EXISTS bundle_prices (id SERIAL PRIMARY KEY, product_id INTEGER REFERENCES bundle_products(id) ON DELETE CASCADE, stripe_price_id VARCHAR(255) UNIQUE, external_product_id VARCHAR(255), plan_name VARCHAR(100) NOT NULL, plan_tier VARCHAR(50) NOT NULL CHECK (plan_tier IN ('free','solo','pro','studio','business','credits','donation')), billing_interval VARCHAR(20) NOT NULL CHECK (billing_interval IN ('month','year','one_time')), amount_cents INTEGER NOT NULL, currency VARCHAR(10) DEFAULT 'usd', intro_enabled BOOLEAN DEFAULT FALSE, intro_type VARCHAR(50), intro_amount_cents INTEGER, intro_periods INTEGER DEFAULT 0, intro_price_lookup_key VARCHAR(255), monthly_included_credits INTEGER DEFAULT 0, one_time_bonus_credits INTEGER DEFAULT 0, plan_rank INTEGER DEFAULT 0, bonus_type VARCHAR(50), kind VARCHAR(50) DEFAULT 'subscription', is_variable_amount BOOLEAN DEFAULT FALSE, display_enabled BOOLEAN DEFAULT TRUE, metadata JSONB DEFAULT '{}'::jsonb, display_weight INTEGER DEFAULT 0, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_bundle_prices_tier ON bundle_prices(plan_tier); CREATE INDEX IF NOT EXISTS idx_bundle_prices_interval ON bundle_prices(billing_interval);
CREATE TABLE IF NOT EXISTS checkout_sessions (id SERIAL PRIMARY KEY, session_id VARCHAR(255) UNIQUE NOT NULL, customer_email VARCHAR(255), price_id VARCHAR(255), subscription_id VARCHAR(255), customer_id VARCHAR(255), status VARCHAR(50) NOT NULL, session_type VARCHAR(50) DEFAULT 'subscription', amount_cents INTEGER, schedule_id VARCHAR(255), metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_checkout_sessions_session_id ON checkout_sessions(session_id); CREATE INDEX IF NOT EXISTS idx_checkout_sessions_status ON checkout_sessions(status); CREATE INDEX IF NOT EXISTS idx_checkout_sessions_type ON checkout_sessions(session_type);
CREATE TABLE IF NOT EXISTS subscriptions (id SERIAL PRIMARY KEY, subscription_id VARCHAR(255) UNIQUE NOT NULL, customer_id VARCHAR(255), customer_email VARCHAR(255), status VARCHAR(50) NOT NULL CHECK (status IN ('active','trialing','past_due','canceled','unpaid')), source VARCHAR(100) NOT NULL DEFAULT 'stripe', external_subscription_id VARCHAR(255), plan_tier VARCHAR(50), price_id VARCHAR(255), bundle_key VARCHAR(100), billing_cycle_start INTEGER DEFAULT 0, canceled_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_subscriptions_subscription_id ON subscriptions(subscription_id); CREATE INDEX IF NOT EXISTS idx_subscriptions_customer_email ON subscriptions(customer_email); CREATE INDEX IF NOT EXISTS idx_subscriptions_customer_id ON subscriptions(customer_id); CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_source_external ON subscriptions(source, external_subscription_id) WHERE external_subscription_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS subscription_schedules (id SERIAL PRIMARY KEY, schedule_id VARCHAR(255) UNIQUE NOT NULL, subscription_id VARCHAR(255), price_id VARCHAR(255) NOT NULL, billing_interval VARCHAR(20) NOT NULL CHECK (billing_interval IN ('month','year','one_time')), intro_enabled BOOLEAN DEFAULT FALSE, intro_amount_cents INTEGER, intro_periods INTEGER DEFAULT 0, normal_amount_cents INTEGER, next_billing_at TIMESTAMP, status VARCHAR(50) NOT NULL DEFAULT 'pending', metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_subscription_schedules_schedule_id ON subscription_schedules(schedule_id); CREATE INDEX IF NOT EXISTS idx_subscription_schedules_subscription_id ON subscription_schedules(subscription_id);
CREATE TABLE IF NOT EXISTS credit_wallets (id SERIAL PRIMARY KEY, customer_email VARCHAR(255) UNIQUE NOT NULL, balance_credits BIGINT DEFAULT 0, bonus_credits BIGINT DEFAULT 0, updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS credit_transactions (id SERIAL PRIMARY KEY, customer_email VARCHAR(255) NOT NULL, amount_credits BIGINT NOT NULL, transaction_type VARCHAR(50) NOT NULL, source VARCHAR(100) NOT NULL DEFAULT 'stripe', external_event_id VARCHAR(255), stripe_event_id VARCHAR(255) UNIQUE, metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMP DEFAULT NOW(), UNIQUE (source, external_event_id));
CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_transactions_stripe_event ON credit_transactions(stripe_event_id) WHERE stripe_event_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS payment_settings (id INTEGER PRIMARY KEY CHECK (id = 1), dashboard_url TEXT, anomaly_webhook_url TEXT, anomaly_webhook_enabled BOOLEAN NOT NULL DEFAULT FALSE, anomaly_rate_limits JSONB NOT NULL DEFAULT '{}'::jsonb, updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS intro_coupon_usage (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email VARCHAR(255) NOT NULL, stripe_customer_id VARCHAR(255), coupon_id VARCHAR(255) NOT NULL, plan_tier VARCHAR(50), subscription_id VARCHAR(255), used_at TIMESTAMP DEFAULT NOW(), created_at TIMESTAMP DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_intro_coupon_usage_email ON intro_coupon_usage(email);
CREATE TABLE IF NOT EXISTS payment_anomaly_log (id BIGSERIAL PRIMARY KEY, anomaly_type VARCHAR(64) NOT NULL, severity VARCHAR(16) NOT NULL DEFAULT 'warn', email VARCHAR(255), customer_id VARCHAR(255), subject_id VARCHAR(255), subject_kind VARCHAR(64), details JSONB NOT NULL DEFAULT '{}'::jsonb, dispatch_status VARCHAR(16) NOT NULL DEFAULT 'pending', dispatch_attempts INTEGER NOT NULL DEFAULT 0, dispatched_at TIMESTAMP, dispatch_error TEXT, created_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_payment_anomaly_log_type ON payment_anomaly_log(anomaly_type); CREATE INDEX IF NOT EXISTS idx_payment_anomaly_log_email ON payment_anomaly_log(email); CREATE INDEX IF NOT EXISTS idx_payment_anomaly_log_subject ON payment_anomaly_log(subject_kind, subject_id); CREATE INDEX IF NOT EXISTS idx_payment_anomaly_log_created ON payment_anomaly_log(created_at); CREATE INDEX IF NOT EXISTS idx_payment_anomaly_log_dispatch_pending ON payment_anomaly_log(created_at) WHERE dispatch_status = 'pending';
