-- Credit consumption, API keys, and user authentication.
CREATE TABLE IF NOT EXISTS subscription_tier_limits (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tier_id VARCHAR(50) NOT NULL, limit_type VARCHAR(20) NOT NULL, limit_key VARCHAR(100) NOT NULL, limit_value BIGINT NOT NULL, cost_multiplier BIGINT DEFAULT 1000000, app_bundle_key VARCHAR(100), reset_period VARCHAR(20) DEFAULT 'monthly', created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), UNIQUE(tier_id, limit_type, limit_key, app_bundle_key));
CREATE INDEX IF NOT EXISTS idx_subscription_tier_limits_tier ON subscription_tier_limits(tier_id); CREATE INDEX IF NOT EXISTS idx_subscription_tier_limits_type ON subscription_tier_limits(limit_type); CREATE INDEX IF NOT EXISTS idx_subscription_tier_limits_app ON subscription_tier_limits(app_bundle_key);
CREATE TABLE IF NOT EXISTS usage_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_identity VARCHAR(255) NOT NULL, billing_period VARCHAR(20) NOT NULL, limit_key VARCHAR(100) NOT NULL, usage_amount BIGINT NOT NULL DEFAULT 0, app_bundle_key VARCHAR(100), operation_id UUID, last_operation_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), UNIQUE(user_identity, billing_period, limit_key, app_bundle_key));
CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_records_identity_period_key_app ON usage_records(user_identity, billing_period, limit_key, app_bundle_key); CREATE INDEX IF NOT EXISTS idx_usage_records_user_period ON usage_records(user_identity, billing_period); CREATE INDEX IF NOT EXISTS idx_usage_records_limit_key ON usage_records(limit_key); CREATE INDEX IF NOT EXISTS idx_usage_records_app ON usage_records(app_bundle_key); CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_records_operation_id ON usage_records(operation_id) WHERE operation_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS api_keys (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), provider VARCHAR(50) NOT NULL UNIQUE, encrypted_key TEXT NOT NULL, key_hint VARCHAR(20), is_active BOOLEAN DEFAULT true, last_verified_at TIMESTAMP, encryption_state VARCHAR(16) NOT NULL DEFAULT 'unknown', created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_api_keys_provider ON api_keys(provider); CREATE INDEX IF NOT EXISTS idx_api_keys_active ON api_keys(is_active);
CREATE TABLE IF NOT EXISTS credit_reservations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_identity VARCHAR(255) NOT NULL, billing_period VARCHAR(20) NOT NULL, limit_key VARCHAR(100) NOT NULL, reserved_amount BIGINT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','finalized','released','expired')), created_at TIMESTAMP DEFAULT NOW(), finalized_at TIMESTAMP, expires_at TIMESTAMP NOT NULL);
CREATE INDEX IF NOT EXISTS idx_credit_reservations_user ON credit_reservations(user_identity, status); CREATE INDEX IF NOT EXISTS idx_credit_reservations_expires ON credit_reservations(expires_at) WHERE status = 'pending';
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email VARCHAR(255) UNIQUE NOT NULL, email_verified BOOLEAN DEFAULT FALSE, stripe_customer_id VARCHAR(255), has_used_intro BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), last_login_at TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email); CREATE INDEX IF NOT EXISTS idx_users_stripe_customer ON users(stripe_customer_id); CREATE INDEX IF NOT EXISTS idx_users_has_used_intro ON users(has_used_intro);
CREATE TABLE IF NOT EXISTS auth_tokens (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, token_hash VARCHAR(255) NOT NULL, token_type VARCHAR(50) NOT NULL, expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW(), ip_address INET, user_agent TEXT);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_hash ON auth_tokens(token_hash); CREATE INDEX IF NOT EXISTS idx_auth_tokens_user_expires ON auth_tokens(user_id, expires_at);
CREATE TABLE IF NOT EXISTS user_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, refresh_token_hash VARCHAR(255) NOT NULL, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP DEFAULT NOW(), last_used_at TIMESTAMP DEFAULT NOW(), ip_address INET, user_agent TEXT, device_info JSONB DEFAULT '{}', revoked BOOLEAN DEFAULT FALSE);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user ON user_sessions(user_id); CREATE INDEX IF NOT EXISTS idx_user_sessions_hash ON user_sessions(refresh_token_hash); CREATE INDEX IF NOT EXISTS idx_user_sessions_active ON user_sessions(user_id, revoked, expires_at);
