from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parent.parent
s=(ROOT/'history/dossier-0.2.md').read_text()
ins=json.loads((ROOT/'source/redesign-inserts.json').read_text())
for k,v in json.loads((ROOT/'source/contract-resolutions.json').read_text()).items():ins[k]+='\n'+v
s=s.replace('# A connected marketing workspace','# Marketing, with something to say.',1)
s=s.replace('Vrooli marketing experience and delivery plan · Review candidate 0.2','Vrooli marketing experience and delivery plan · Review candidate 0.3',1)
s=s.replace('Design and planning authorized · Product choices and exact visuals remain proposed','Whole-design revision authorized · C direction selected as a starting point · Exact specification and consequential choices remain for review',1)
s=re.sub(r'\[Full-size visual atlas \(M01–M14\)\].*?\n\n','[Full-size visual atlas and state specimens](https://drive.google.com/file/d/15UXSK90NG3YHEqL5C-lya_RahD7kitPt/view). This edition pairs purpose-specific desktop workspaces with readable phone and focused-state views. Layout overviews are supplemented by legible controls and native explanation here; original concept art and prior versions remain in the source history.\n\n',s,count=1)
s=s.replace('### What this edition adds\n\nThis edition connects strategy, source and offer truth, useful post types, production, review, account eligibility, intended publication, actual receipts and learning. It specifies the currently missing schedule-release contract, the article/method intake adapter, proportional review, real contributor participation, source-aware planner integration, failed and uncertain operations, a complete CQ history, and outcome-based implementation requirements. Old source code is distinguished from qualified behavior throughout.',
'''### What changes in this revision

The owner selected the task-specific C visual direction and asked for a deep review of the full product. This revision develops the distinct calendar, editor, review inbox and evidence notebook into one connected experience. Content remains findable in a stable home; saved revisions, editorial acceptance and release permission have explicit transitions; partial planning and publication outcomes have a responsible next action; and phone, contributor, no-art and interrupted-work paths receive actual specimens. The fifteen-chapter scope and all seventeen consequential-choice histories remain.

Start by comparing the connected journey in Chapter 1 and the revised page/state contract in Chapter 2, then inspect Create and Review together. CQ01/CQ15 still determine the native front door and ownership; CQ05/CQ07/CQ09 govern revision and review semantics; CQ12 now develops the selected C direction while exact pixels and behavior remain proposed. The current native scheduling, project/type, media and approval contracts still require the explicitly identified source work. Attractive screens do not establish those integrations.''')
# Remove four repair-only enlarged image references; new readable native specimens replace them.
s=re.sub(r'!\[Proposed specimen/detail\]\(\.\./embeds2500/M(?:01-work|04-assistance|06-release|07-outcome)-detail\.png\)\n\nEnlarged detail[^\n]*\n\n','',s)
# Preserve old figure family names, select new versions later through one canonical manifest.
s=re.sub(r'!\[Proposed specimen/detail\]\(\.\./embeds2500/(M\d+)[^)]*\)',lambda m:'[FIG:'+m.group(1)+']',s)
parts=re.split(r'(?=^## \d+ · )',s,flags=re.M)
out=[parts[0]]
openers={
 1:'Recommended: start from a real piece of work and keep the full loop visible. Review CQ02 for first-session friction and CQ16 for how much planning the system proposes. The first outcome is a durable reopened draft; the connected routes below remain proposed.',
 2:'Recommended: Content Desk owns the experience and content relationships; native domain owners keep their authority. CQ01/CQ15 are the architecture choice. Project, family, package and source-work seams below require compatible source changes.',
 3:'Recommended: preserve the existing article and its media, then admit a versioned draft without regeneration. CQ17 governs authoring/method integration. Pending media, producer and native project/type admission remain actual gaps.',
 4:'Recommended: make evidence inspectable at the sentence and freeze its selected basis in the review package. CQ03/CQ04 govern visibility and unsupported claims. Support, native verification and current permission remain different facts.',
 5:'Recommended: give each format a real editor and make assistance optional, scoped and cost-visible. CQ05/CQ17 govern revision and authoring. The richer job/cancellation controls require actual route capability before use.',
 6:'Recommended: accept a coherent content plan, then separately admit human work and publication intentions. CQ06/CQ16 govern the unified view and planning logic. Current source does not establish the complete timed-release or Planner adapter contract.',
 7:'Recommended: plan useful channels and genuine contributions, with action-scoped readiness and consent. CQ13 governs collaborator scope. The owned subreddit remains a proposal; X stays link-only.',
 8:'Recommended: distinguish edit adoption, craft assessment, human native approval and release authority. CQ08/CQ09 govern route and ceremony. Wording-only acceptance and general thread recovery require explicit native contract work.',
 9:'Recommended: learn from attributed observations and bounded questions. CQ10 governs evidence-tiered learning. Missing metrics stay unknown; native observation lineage needs the extensions below.',
 10:'Recommended: make every interruption recoverable from its affected object, preserving truthful unknown states. CQ05/CQ11 govern revisions and local safety copies. Static designs do not establish persistence or security guarantees.',
 11:'Recommended: develop the selected C direction through purpose-specific workspaces, deliberate mobile reflow and useful adaptive imagery. CQ12 records the selected starting direction and pending exact design/token decisions.',
 12:'Recommended: retain private native ownership and visible optional costs. CQ14 stays deferred as a separate commercial question; CQ15/CQ17 govern data and authoring routes. No new hosted account, price or free-inference claim follows.',
 13:'Use these connected cases to challenge the complete design and later accepted implementation. The design can be reviewed now; runtime, device, account and actual publication tests remain unexecuted obligations.',
 15:'This source record separates design production, scoped owner acceptance, native source application and implementation. Start a later full implementation commission only from accepted scope and current native readiness.'}
captions={
'M01':'M01. Proposed Today and resume states. A useful source preview accompanies the current suggestion; independent decisions and urgent uncertain outcomes have their own routes.',
'M02':'M02. Proposed content-mix comparison. The same synthetic facts support a 180-minute coordinated plan or a 90-minute reduced plan, with omitted work and affected targets explicit.',
'M10':'M10. Proposed ownership and state flow. Native owner names are source-grounded; new commands and relationships remain required design work.',
'M13':'M13. Proposed article intake and partial-admission recovery. The existing article remains the source, and missing media never implies regeneration or full success.',
'M03':'M03. Proposed claim inspection and repair. Structural evidence and unestablished performance are distinct, with exact wording and source scope visible.',
'M04':'M04. Proposed source-aware editor and optional scoped assistance. Applying a selected edit produces a saved unapproved revision; generation, acceptance and release are different actions.',
'M05':'M05. Proposed publication intentions. The calendar contains intentions, not human allocations or inferred provider schedules. The selected drawer exposes its current content basis.',
'M14':'M14. Proposed account readiness and destination selection. Identity, actor role, type/strategy activation, connection and permitted route remain separate checks.',
'M11':'M11. Proposed contributor packet and scoped response. The fictional recipient can decline, submit their own words and permit only a named use.',
'M06':'M06. Proposed editorial review of saved r2 against previous r1, with readable phone final view and explicit restore-as-new-revision detail. The new scoped decision contract is not current runtime approval.',
'M07':'M07. Proposed publication outcome reconciliation. The attempt, exact package, evidence and permitted next action remain available while the result is unknown.',
'M08':'M08. Proposed evidence notebook and observation entry. Content facts, reported/verified publication and audience feedback do not become one success score.',
'M09':'M09. Proposed interrupted-edit comparison and safe recovery. Base, server revision and local branch stay distinct until the composed result is deliberately saved.'}
for part in parts[1:]:
 n=int(re.match(r'## (\d+)',part).group(1));head,body=part.split('\n',1)
 lead=''
 if n!=11:
  match=re.search(r'\[FIG:(M\d+)\]\n\n\[[^\n]+\n\n',body)
  if match:
   ident=match.group(1);lead='[FIG:'+ident+']\n\n'+captions[ident]+'\n\n';body=body[:match.start()]+body[match.end():]
 if n in openers:lead=openers[n]+'\n\n'+lead
 if n==11:
  # Recompose this chapter rather than layering a conflicting old visual contract.
  component=body[body.index('### Components and meaningful states'):body.index('### Exact compact behavior')]
  part=head+'\n\n'+lead+ins['11']+'\n'+component+'\n[FIG:M12]\n\nM12. Proposed simple-post and interrupted-phone specimens. The native one-off admission seam remains a prerequisite to operational save.\n\n'
 elif n in (1,2,3,4,5,6,7,8,9,10,12,13,15):
  part=head+'\n\n'+lead+ins[str(n)]+'\n'+body.lstrip()
 out.append(part)
s=''.join(out)
s=s.replace('The C review concept\'s r2 is therefore explicitly a candidate revision, not an unsaved floating string.','The revised Review specimen labels r1 Previous saved wording and r2 Current saved draft. Returning to r1 is an explicit restore proposal that creates r3 under a revision guard; it never deletes r2 or silently makes an old revision current.')
s=s.replace('The primary button can say Accept content plan; requesting Planner allocation is a separately visible optional operation.','The primary button can say Accept content plan; requesting Planner allocation is a separately visible optional operation.')
s=s.replace('A publication intention identifies exact content/destination and desired time before release admission.','A publication intention identifies a draft, its selected preview basis, a proposed destination and desired time before release admission. A newer draft revision marks the basis changed and offers compare/update; no approval silently transfers. Exact release admission pins a validated PublicationPackage.')
s=s.replace('A materialized ReviewPackage freezes body, media order/version/crop, links, accessibility text, author/attribution, method/source basis and the declared review scope.','A materialized ReviewPackage freezes body, media order/version/crop, links, accessibility text, author/attribution, method/source basis and the declared review scope. This proposed relationship must be reconciled with the native human-only ApproveDraft and review/type gates; destination-free wording assessment must not be mislabeled as that existing operational approval.')
s=s.replace('An observation form asks what was observed, on which exact post/version/account, when, from what source and with which limitations.','Import publication evidence routes through Channel Manager\'s supported outcome mechanism and Content Desk\'s publish ledger, reconciling the native post/attempt identity; Learn must not create its own competing release record. Import metric observations uses the rightful owner\'s metric definition and provenance. An observation form asks what was observed, on which exact post/version/account, when, from what source and with which limitations.')
s=s.replace('Current main design-product-dossier and craft-review-artifacts definitions were read for this commission. Seven exact dossier reference resource reads failed with \'failed to read skill resource\'; no full-reference-load claim is made. The complete verified native Craft counterpart at its stated d47349d basis, project-local method and prior source/critique history supplied supported guidance. This limitation is explicit; no reference text was manufactured. Owner authorization covers this project revision, not silently updating other projects\' method adoption.',
'''The current main design-product-dossier and craft-review-artifacts definitions were read. Initial reads of all seven relative dossier resources failed. The verified owned skill source subsequently supplied the complete main method 1.2.1 and all seven references, which were read before the revised visual system was scaled. The main source SHA-256 is fad38799c867667ac293ccc0258a58f59c09cd308b79caae149395b8abb66508. The skill loader still returned a cached earlier main text; verified source access resolved this task's reading gap without claiming the loader was repaired. The complete native Craft counterpart retains its stated d47349d basis. This revision adopts dossier 1.2.1 for this authorized project work only; existing project history and other projects' pins remain unchanged.''')
s=s.replace('The design-product-dossier main method was loaded. Its relative reference resources were unavailable in this run; the current native Craft guide and the already-linked Nooch worked procedure supplied accessible craft/lifecycle detail. They are references, not a migration of Nooch’s schema, approvals or workflow. The project-local adoption for this revision is limited to reader-first design, independent source/user/visual reviews, exact artifact checking, durable source/visual pins and source-application separation. Shared future method changes do not silently upgrade this project.',
'For candidate 0.2, the dossier main method was loaded but its relative references were unavailable; the native Craft guide and linked Nooch worked procedure supplied qualified fallback detail. Candidate 0.3 recovered and consumed the complete verified dossier source as recorded above. Nooch and Planner remain actual-pixel quality references, not a migration of their schema, approvals or workflow. Future shared changes do not silently upgrade this project.')
s=s.replace('### Independent critique and correction record','### Historical candidate 0.2 critique and correction record')
s=s.replace('A PublicationPackage adds account, audience, route, allowed time window, consent and release authority.', 'A PublicationPackage adds account, audience, route, allowed time window, consent and release authority and therefore has its own immutable identity. In the connected fixture, RP2 derives from editorial package P2; the manual fixture uses MP2. Neither reuses P2’s digest for changed fields.')
s=s.replace('keyed by the actual asset identity/version and applicable policy scope','keyed by the stable asset ID under the existing cross-identity policy, with immutable asset version recorded as request provenance. A new version of the same asset cannot evade that stable-ID reservation')
s=s.replace('Keep current rejects that proposal, not the whole campaign.','For a pre-adoption edit proposal, Keep original dismisses the suggestion. For saved r2, Return to r1 opens a restore comparison and creates a new draft revision only after explicit confirmation; it never deletes r2 or changes the whole campaign.')
s=s.replace('Retry media targets the original operation/media key and current destination revision.','A safe replay uses the original media operation key and unchanged request fingerprint. If the target revision or payload changed, reconcile the original operation first, then preview a separate retry intent against the new base.')
s=s.replace('A spinning indicator includes the actual stage and a useful cancel route; it does not freeze the editor.','A running indicator names the actual stage and offers cancellation only when the selected route supports it. Otherwise it states the control limit and lets the user keep editing or leave the job view; it does not freeze the editor.')
s=s.replace('The shared language is warm ivory, cobalt primary actions and rules, near-black text, restrained red for meaningful exceptions, confident sans-serif hierarchy and readable serif prose.','The shared proposed language is warm ivory, cobalt primary actions and rules, near-black text, restrained red for meaningful exceptions, confident sans-serif hierarchy and readable serif prose. Content Desk\'s captured DESIGN.md currently binds a different operational token contract and permits no local deviation. This proposal therefore requires an explicit scoped native DESIGN/token amendment under CQ12 before implementation; the dossier does not silently override those existing tokens. Preserve the native permanent-inspector, format-shaped authoring and accessibility commitments while reconciling that amendment.')
s=s.replace('Retain the useful warm-paper, deep-ink and restrained-vermilion direction','Historically, candidate 0.2 retained the warm-paper, deep-ink and restrained-vermilion direction')
old='Reframe the earlier expressive-art default. Recommended: the restrained editorial direction with strong typography and purposeful source imagery, no-art dense work surfaces, deliberate phone reflow and optional compact density. Retain useful Cadence craft and Nooch’s action clarity without importing decorative scenery. Exact current images remain unapproved. Alternative: a more utilitarian console may be easier to align with existing tokens but risks losing the desired quality; a more atmospheric surface can crowd the work. Consequence: compare actual pixels and key states, not a mood-board score.'
new='Develop the owner-selected task-specific C / Modernist Press direction: expressive, relevant Today imagery and confident type; purpose-specific calendar, editor, review and evidence surfaces; readable mobile and no-art forms. The owner authorized this as the starting point for redesign, not every exact image, token or behavior. Candidate 0.2’s restrained vermilion recommendation is superseded as the current visual recommendation and retained historically. Alternative: align more closely to existing native design tokens at the cost of the selected expression; a larger atmospheric treatment can enrich Today but would crowd operational work. Consequence: acceptance must cover exact responsive/state specimens and any native token amendment, with adaptive art provenance and no mandatory generation.'
assert old in s;s=s.replace(old,new)
s=s.replace('The complete index below carries every CQ01–CQ16 from candidate 0.1 and adds only one new consequential choice for the external-authoring/method boundary. Each remains proposed unless explicit scoped owner evidence is recorded.','The complete index carries CQ01–CQ16 from candidate 0.1 and CQ17 from candidate 0.2. They remain reviewable at their actual scopes. CQ12 records the later owner-selected C starting direction while its exact implementation, behavior and pixels remain proposed; no broader choice is inferred.')
s=s.replace('The voice continuation authorized this design work, not any CQ answer.','The original voice continuation authorized design work; the later redesign direction is recorded at its narrower visual scope.')
s=s.replace('Earlier candidate 0.1’s exact native PDF, full-size atlas, source package and original CQ text preserve history;', 'The verified owner-only recovery baseline also preserves candidate 0.2: [53-page PDF](https://drive.google.com/file/d/1pXlEctQBoX6olsvrGPwl6rRL09uiT7f-/view), [14-board atlas](https://drive.google.com/file/d/1r71CliiJ074mdWOye7RGD0H-MlpGlSx9/view), and [reviewed source package](https://drive.google.com/file/d/1637HJzN3a54J0dLp9-_PV73hoIlC7gsw/view). Their recorded hashes distinguish them from the current same-ID outputs. Earlier candidate 0.1’s exact native PDF, full-size atlas, source package and original CQ text preserve history;')

extra={
'### Relationships that stay intelligible as work grows':'[FIG:M15]\n\nM15. A stable Content home keeps drafts, archived work and publication history findable. Same-title records remain distinguished by native identity and owning scope.\n\n',
'### Visible optional assistance and cost':'[FIG:M16]\n\nM16. Format-specific article, ordered thread and silent-demonstration canvases. The article uses an actual private source excerpt and its exported cover. Other content is synthetic; no runtime or media-release state is claimed.\n\n',
'### The job and accounting contract must match the selected route':'[FIG:M23]\n\nM23. A bounded assistance request shows selected text/context and the actual route/cost gaps. Existing dot-authored work and manual editing stay useful without a generation run.\n\n',
'### Stable preparation identity precedes Planner projection':'[FIG:M17]\n\nM17. A reduced content plan is saved while Planner time remains unreserved. Earlier publication intentions are retained at risk for date review; deferred adaptations do not become new commitments.\n\n',
'### Release has its own concise confirmation':'[FIG:M19]\n\nM19. Readable phone source inspection and an anchored change request preserve exact package context. A review comment does not silently edit or publish.\n\n',
'### Command, actor and authority mapping':'[FIG:M24]\n\nM24. Future qualified-release fixture. A synthetic human-approved package, identity and full allowed date/window are reviewed together. No actual account, approval or dispatch is asserted.\n\n',
'### Observation identity survives correction and reconciliation':'[FIG:M25]\n\nM25. Manual handoff reporting and an incomplete private observation. Copying stays separate from posting; a missing observation time stays visible and produces no audience result.\n\n',
'### Access and source privacy':'[FIG:M20]\n\nM20. No work, no matching content, loading and unknown save are distinct states with different safe actions.\n\n',
'### Responsive contracts, not shrunken boards':'[FIG:M21]\n\nM21. The same article action uses its actual exported cover, explicitly contextual vector art or a source-heading fallback. No per-visit generation or evidentiary claim is implied.\n\n',
'### Readability belongs to the delivered artifact':'[FIG:M22]\n\nM22. Proposed dark editor appearance retains the same record, source limits and optional proposal. Token contrast is checked separately; this is not an implemented accessibility test.\n\n',
'### Additional connected-design acceptance':'[FIG:M18]\n\nM18. A concrete source-to-learning state trace shows who acts and what changes. Each arrow is a proposed handoff, not evidence of an executed command.\n\n'}
for anchor,fig in extra.items():
 assert anchor in s,anchor
 s=s.replace(anchor,fig+anchor,1)
s=s.replace('Consequences:','Consequences:')
s=s.replace('Carry forward independent snapshots with derivation links and proposed updates.','Carry forward independent snapshots with derivation links and proposed updates. Recommend one owning project, at most one native campaign and one primary same-project family per draft; saved collections can display the same record without consuming another slot. These proposed cardinalities and detach/move rules require native compatibility review.')
s=s.replace('Carry forward proportionate exact preview. Recommended: light preview for ordinary personal writing;','Carry forward proportionate exact preview. Recommended: a proposed wording-only human assessment record remains distinct from native human-operator ApproveDraft and release permission, with one concise combined decision when the same human holds all roles and each scope is explicit. Use light preview for ordinary personal writing;')
s=s.replace('The source-application plan should map:','The source-application plan must also reconcile request-fingerprint idempotency, scoped editorial decisions versus native approval, immutable package/claim anchors, same-project family/cardinality and campaign slots, source-work identity/Planner projection, ordered external-item outcomes, concurrent asset reservations, complete job/cost capabilities and observation correction lineage. These named seams are required for the corresponding new controls.\n\nThe source-application plan should map:')
s=s.replace('The main source SHA-256 is fad38799c867667ac293ccc0258a58f59c09cd308b79caae149395b8abb66508.','The1.2.1 main source SHA-256 is fad38799c867667ac293ccc0258a58f59c09cd308b79caae149395b8abb66508. The later1.2.2 access-only clarification was also consumed from verified source0c3f15dfc3267a8621190c0bb61e2a2c03fa4d8bd42aadba2c76e229dc5202f6; it changes no design or delivery scope.')
s=s.replace('The1.2.1','The 1.2.1').replace('later1.2.2','later 1.2.2').replace('source0c3f','source 0c3f')
s=s.replace('Normal body/status text targets at least 4.5:1 contrast,','Design targets draw on [W3C contrast guidance](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html), [reflow guidance](https://www.w3.org/WAI/WCAG22/Understanding/reflow.html) and [enhanced target-size guidance](https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html). Normal body/status text targets at least 4.5:1 contrast,')
# Final review record is a scoped design-production receipt, not product approval.
closeout=ROOT/'source/final-review-record.txt'
if closeout.exists():
 lines=closeout.read_text().strip().splitlines()
 s=s.replace('### Historical candidate 0.2 critique and correction record','### '+lines[0]+'\n\n'+'\n\n'.join(lines[1:])+'\n\n### Historical candidate 0.2 critique and correction record',1)
# Old visual captions are replaced by current catalogue-linked annotations during final composition.
(ROOT/'source/dossier.md').write_text(s)
print(json.dumps({'bytes':len(s.encode()),'chapters':len(re.findall(r'^## \d+ · ',s,re.M)),'choices':len(re.findall(r'^### CQ\d+',s,re.M)),'figures':re.findall(r'\[FIG:(M\d+)\]',s)},indent=2))
