// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainContentLabel: "layout.mainContentLabel",
    nav: {
      overview: "layout.nav.overview",
      targets: "layout.nav.targets",
      history: "layout.nav.history",
      settings: "layout.nav.settings",
    },
    subnav: {
      label: "layout.subnav.label",
      graph: "layout.subnav.graph",
      domains: "layout.subnav.domains",
      conflicts: "layout.subnav.conflicts",
      apply: "layout.subnav.apply",
      analytics: "layout.subnav.analytics",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    overview: {
      title: "pages.overview.title",
      description: "pages.overview.description",
      recentTargetsHeading: "pages.overview.recentTargetsHeading",
      activeSnapshotsHeading: "pages.overview.activeSnapshotsHeading",
      healthHeading: "pages.overview.healthHeading",
      noActiveSnapshots: "pages.overview.noActiveSnapshots",
      loadingSnapshots: "pages.overview.loadingSnapshots",
      snapshotsError: "pages.overview.snapshotsError",
      startExtraction: "pages.overview.startExtraction",
    },
    newTarget: {
      title: "pages.newTarget.title",
      description: "pages.newTarget.description",
      scenarioPathLabel: "pages.newTarget.scenarioPathLabel",
      scenarioPathHint: "pages.newTarget.scenarioPathHint",
      submitButton: "pages.newTarget.submitButton",
      submitting: "pages.newTarget.submitting",
      successMessage: "pages.newTarget.successMessage",
      fromCacheMessage: "pages.newTarget.fromCacheMessage",
      openWorkspace: "pages.newTarget.openWorkspace",
      validationRequired: "pages.newTarget.validationRequired",
      validationInvalid: "pages.newTarget.validationInvalid",
    },
    targetWorkspace: {
      title: "pages.targetWorkspace.title",
      scenarioLabel: "pages.targetWorkspace.scenarioLabel",
    },
    conflicts: {
      title: "pages.conflicts.title",
      description: "pages.conflicts.description",
      listEmptyTitle: "pages.conflicts.listEmptyTitle",
      listEmptyDescription: "pages.conflicts.listEmptyDescription",
      loading: "pages.conflicts.loading",
      errorTitle: "pages.conflicts.errorTitle",
      detectButton: "pages.conflicts.detectButton",
      detecting: "pages.conflicts.detecting",
      validateButton: "pages.conflicts.validateButton",
      validating: "pages.conflicts.validating",
      detailNotFound: "pages.conflicts.detailNotFound",
      selectConflictPrompt: "pages.conflicts.selectConflictPrompt",
      columns: {
        id: "pages.conflicts.columns.id",
        type: "pages.conflicts.columns.type",
        severity: "pages.conflicts.columns.severity",
        domains: "pages.conflicts.columns.domains",
        status: "pages.conflicts.columns.status",
      },
      evidenceHeading: "pages.conflicts.evidenceHeading",
      noEvidence: "pages.conflicts.noEvidence",
      fixesHeading: "pages.conflicts.fixesHeading",
      noFixes: "pages.conflicts.noFixes",
      locationsHeading: "pages.conflicts.locationsHeading",
      assignedDomainLabel: "pages.conflicts.assignedDomainLabel",
      noAssignedDomain: "pages.conflicts.noAssignedDomain",
      snapshotLabel: "pages.conflicts.snapshotLabel",
      confidenceLabel: "pages.conflicts.confidenceLabel",
    },
    conflictDetail: {
      title: "pages.conflictDetail.title",
      backToList: "pages.conflictDetail.backToList",
    },
    targetGraph: {
      title: "pages.targetGraph.title",
      description: "pages.targetGraph.description",
      loading: "pages.targetGraph.loading",
      errorTitle: "pages.targetGraph.errorTitle",
      emptyTitle: "pages.targetGraph.emptyTitle",
      emptyDescription: "pages.targetGraph.emptyDescription",
      fallbackTitle: "pages.targetGraph.fallbackTitle",
      fallbackMessage: "pages.targetGraph.fallbackMessage",
      summaryNodes: "pages.targetGraph.summaryNodes",
      summaryEdges: "pages.targetGraph.summaryEdges",
    },
    targetApply: {
      title: "pages.targetApply.title",
      description: "pages.targetApply.description",
      selectDomainPrompt: "pages.targetApply.selectDomainPrompt",
      loading: "pages.targetApply.loading",
      errorTitle: "pages.targetApply.errorTitle",
      noPlan: "pages.targetApply.noPlan",
      domainHeading: "pages.targetApply.domainHeading",
      operationsHeading: "pages.targetApply.operationsHeading",
      noOperations: "pages.targetApply.noOperations",
      historyHeading: "pages.targetApply.historyHeading",
      historyEmpty: "pages.targetApply.historyEmpty",
      baselineHeading: "pages.targetApply.baselineHeading",
      baselineUnknown: "pages.targetApply.baselineUnknown",
      baselineGreen: "pages.targetApply.baselineGreen",
      baselineRed: "pages.targetApply.baselineRed",
      planButton: "pages.targetApply.planButton",
      planning: "pages.targetApply.planning",
      dryRunButton: "pages.targetApply.dryRunButton",
      applyButton: "pages.targetApply.applyButton",
      applying: "pages.targetApply.applying",
      applyUnimplementedTitle: "pages.targetApply.applyUnimplementedTitle",
      applyUnimplementedMessage: "pages.targetApply.applyUnimplementedMessage",
      forceConfirmTitle: "pages.targetApply.forceConfirmTitle",
      forceConfirmMessage: "pages.targetApply.forceConfirmMessage",
      forceNoteLabel: "pages.targetApply.forceNoteLabel",
      forceNotePlaceholder: "pages.targetApply.forceNotePlaceholder",
      forceNoteRequired: "pages.targetApply.forceNoteRequired",
      confirmButton: "pages.targetApply.confirmButton",
      cancelButton: "pages.targetApply.cancelButton",
    },
    targetDomains: {
      title: "pages.targetDomains.title",
      description: "pages.targetDomains.description",
      loading: "pages.targetDomains.loading",
      errorTitle: "pages.targetDomains.errorTitle",
      empty: "pages.targetDomains.empty",
      extractButton: "pages.targetDomains.extractButton",
      extracting: "pages.targetDomains.extracting",
      domainsHeading: "pages.targetDomains.domainsHeading",
      sharedSubstrateHeading: "pages.targetDomains.sharedSubstrateHeading",
      nonDomainsHeading: "pages.targetDomains.nonDomainsHeading",
      declarationsHeading: "pages.targetDomains.declarationsHeading",
      authorityLabel: "pages.targetDomains.authorityLabel",
      noDomains: "pages.targetDomains.noDomains",
      noSharedSubstrate: "pages.targetDomains.noSharedSubstrate",
      noNonDomains: "pages.targetDomains.noNonDomains",
      columns: {
        name: "pages.targetDomains.columns.name",
        paths: "pages.targetDomains.columns.paths",
        archetype: "pages.targetDomains.columns.archetype",
        provenance: "pages.targetDomains.columns.provenance",
      },
      convergence: {
        heading: "pages.targetDomains.convergence.heading",
        loading: "pages.targetDomains.convergence.loading",
        errorTitle: "pages.targetDomains.convergence.errorTitle",
        converged: "pages.targetDomains.convergence.converged",
        severityWarn: "pages.targetDomains.convergence.severityWarn",
        severityInfo: "pages.targetDomains.convergence.severityInfo",
      },
      boundaries: {
        heading: "pages.targetDomains.boundaries.heading",
        loading: "pages.targetDomains.boundaries.loading",
        errorTitle: "pages.targetDomains.boundaries.errorTitle",
        empty: "pages.targetDomains.boundaries.empty",
        healthScore: "pages.targetDomains.boundaries.healthScore",
        efferent: "pages.targetDomains.boundaries.efferent",
        afferent: "pages.targetDomains.boundaries.afferent",
        instability: "pages.targetDomains.boundaries.instability",
        fanOut: "pages.targetDomains.boundaries.fanOut",
        stableKernel: "pages.targetDomains.boundaries.stableKernel",
        severityWarn: "pages.targetDomains.boundaries.severityWarn",
        severityInfo: "pages.targetDomains.boundaries.severityInfo",
      },
    },
    targetAnalytics: {
      title: "pages.targetAnalytics.title",
      description: "pages.targetAnalytics.description",
      statsHeading: "pages.targetAnalytics.statsHeading",
      statsLoading: "pages.targetAnalytics.statsLoading",
      statsError: "pages.targetAnalytics.statsError",
      statsConflictsDetected: "pages.targetAnalytics.statsConflictsDetected",
      statsConflictsResolved: "pages.targetAnalytics.statsConflictsResolved",
      statsConflictsForce: "pages.targetAnalytics.statsConflictsForce",
      statsPlacementsAuto: "pages.targetAnalytics.statsPlacementsAuto",
      statsPlacementsSuggest: "pages.targetAnalytics.statsPlacementsSuggest",
      statsOverrides: "pages.targetAnalytics.statsOverrides",
      statsVerdictSuccess: "pages.targetAnalytics.statsVerdictSuccess",
      statsVerdictSuppressed: "pages.targetAnalytics.statsVerdictSuppressed",
      eventsHeading: "pages.targetAnalytics.eventsHeading",
      eventsLoading: "pages.targetAnalytics.eventsLoading",
      eventsError: "pages.targetAnalytics.eventsError",
      eventsEmpty: "pages.targetAnalytics.eventsEmpty",
      placementsHeading: "pages.targetAnalytics.placementsHeading",
      placementsLoading: "pages.targetAnalytics.placementsLoading",
      placementsError: "pages.targetAnalytics.placementsError",
      placementsEmpty: "pages.targetAnalytics.placementsEmpty",
      buildDeltasHeading: "pages.targetAnalytics.buildDeltasHeading",
      buildDeltasEmpty: "pages.targetAnalytics.buildDeltasEmpty",
      columns: {
        kind: "pages.targetAnalytics.columns.kind",
        actor: "pages.targetAnalytics.columns.actor",
        domain: "pages.targetAnalytics.columns.domain",
        conflictId: "pages.targetAnalytics.columns.conflictId",
        chunkId: "pages.targetAnalytics.columns.chunkId",
        chunkPath: "pages.targetAnalytics.columns.chunkPath",
        outcome: "pages.targetAnalytics.columns.outcome",
      },
    },
    history: {
      title: "pages.history.title",
      description: "pages.history.description",
      scenarioLabel: "pages.history.scenarioLabel",
      noScenario: "pages.history.noScenario",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      preferencesHeading: "pages.settings.preferencesHeading",
      densityLabel: "pages.settings.densityLabel",
      densityComfortable: "pages.settings.densityComfortable",
      densityDense: "pages.settings.densityDense",
      reducedMotionLabel: "pages.settings.reducedMotionLabel",
      reducedMotionHint: "pages.settings.reducedMotionHint",
      handednessLabel: "pages.settings.handednessLabel",
      handednessLeft: "pages.settings.handednessLeft",
      handednessRight: "pages.settings.handednessRight",
      defaultScenarioLabel: "pages.settings.defaultScenarioLabel",
      defaultScenarioHint: "pages.settings.defaultScenarioHint",
      defaultDomainLabel: "pages.settings.defaultDomainLabel",
      defaultDomainHint: "pages.settings.defaultDomainHint",
    },
  },
  features: {
    graph: {
      canvas: {
        ariaLabel: "features.graph.canvas.ariaLabel",
        nodeAriaLabel: "features.graph.canvas.nodeAriaLabel",
        nodeConflictPresent: "features.graph.canvas.nodeConflictPresent",
        nodeConflictAbsent: "features.graph.canvas.nodeConflictAbsent",
      },
      filterBar: {
        label: "features.graph.filterBar.label",
        allDomains: "features.graph.filterBar.allDomains",
        noDomains: "features.graph.filterBar.noDomains",
      },
      accessibleList: {
        title: "features.graph.accessibleList.title",
        description: "features.graph.accessibleList.description",
        domainLabel: "features.graph.accessibleList.domainLabel",
        noDomain: "features.graph.accessibleList.noDomain",
        conflictLabel: "features.graph.accessibleList.conflictLabel",
        noConflict: "features.graph.accessibleList.noConflict",
      },
      legend: {
        title: "features.graph.legend.title",
        noConflict: "features.graph.legend.noConflict",
        conflictPrefix: "features.graph.legend.conflictPrefix",
      },
    },
  },
  conflicts: {
    status: {
      detected: "conflicts.status.detected",
      assigned: "conflicts.status.assigned",
      split: "conflicts.status.split",
      resolved: "conflicts.status.resolved",
      validated: "conflicts.status.validated",
      committed: "conflicts.status.committed",
      force_resolved: "conflicts.status.force_resolved",
    },
    actions: {
      assign: "conflicts.actions.assign",
      split: "conflicts.actions.split",
      resolve: "conflicts.actions.resolve",
      force_resolve: "conflicts.actions.force_resolve",
      validate: "conflicts.actions.validate",
      commit: "conflicts.actions.commit",
      reopen: "conflicts.actions.reopen",
      pending: "conflicts.actions.pending",
      assignDomainPrompt: "conflicts.actions.assignDomainPrompt",
      notePlaceholder: "conflicts.actions.notePlaceholder",
      forceNoteRequired: "conflicts.actions.forceNoteRequired",
    },
    fixKind: {
      unspecified: "conflicts.fixKind.unspecified",
      move_file: "conflicts.fixKind.move_file",
      reassign_domain: "conflicts.fixKind.reassign_domain",
      break_cycle: "conflicts.fixKind.break_cycle",
      add_dependency: "conflicts.fixKind.add_dependency",
      add_transitional: "conflicts.fixKind.add_transitional",
    },
  },
  targets: {
    recent: {
      openButton: "targets.recent.openButton",
      removeAriaLabel: "targets.recent.removeAriaLabel",
      emptyTitle: "targets.recent.emptyTitle",
      emptyDescription: "targets.recent.emptyDescription",
      openedAt: "targets.recent.openedAt",
    },
    snapshots: {
      snapshotIdLabel: "targets.snapshots.snapshotIdLabel",
      scenarioLabel: "targets.snapshots.scenarioLabel",
      extractedAtLabel: "targets.snapshots.extractedAtLabel",
      openButton: "targets.snapshots.openButton",
    },
  },
  apply: {
    status: {
      baseline_captured: "apply.status.baseline_captured",
      plan_generated: "apply.status.plan_generated",
      dry_run_ok: "apply.status.dry_run_ok",
      applied: "apply.status.applied",
      committed: "apply.status.committed",
      refused_build_break: "apply.status.refused_build_break",
      force_committed: "apply.status.force_committed",
    },
    operationKind: {
      unspecified: "apply.operationKind.unspecified",
      move_file: "apply.operationKind.move_file",
      rewrite_import: "apply.operationKind.rewrite_import",
      delete_file: "apply.operationKind.delete_file",
      create_file: "apply.operationKind.create_file",
    },
  },
  analytics: {
    eventKind: {
      unspecified: "analytics.eventKind.unspecified",
      conflict_detected: "analytics.eventKind.conflict_detected",
      conflict_assigned: "analytics.eventKind.conflict_assigned",
      conflict_resolved: "analytics.eventKind.conflict_resolved",
      conflict_reopened: "analytics.eventKind.conflict_reopened",
      conflict_force_resolved: "analytics.eventKind.conflict_force_resolved",
      verdict_produced: "analytics.eventKind.verdict_produced",
      placement_auto: "analytics.eventKind.placement_auto",
      placement_suggest: "analytics.eventKind.placement_suggest",
      override_recorded: "analytics.eventKind.override_recorded",
      apply_planned: "analytics.eventKind.apply_planned",
      apply_ran: "analytics.eventKind.apply_ran",
      apply_build_green: "analytics.eventKind.apply_build_green",
      apply_build_red: "analytics.eventKind.apply_build_red",
      apply_reverted: "analytics.eventKind.apply_reverted",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
  shared: {
    empty: {
      title: "shared.empty.title",
      description: "shared.empty.description",
    },
    loading: {
      label: "shared.loading.label",
    },
    error: {
      title: "shared.error.title",
      retry: "shared.error.retry",
    },
    dataTable: {
      empty: "shared.dataTable.empty",
    },
    severity: {
      info: "shared.severity.info",
      low: "shared.severity.low",
      medium: "shared.severity.medium",
      high: "shared.severity.high",
      critical: "shared.severity.critical",
    },
    diff: {
      added: "shared.diff.added",
      removed: "shared.diff.removed",
      unchanged: "shared.diff.unchanged",
    },
    splitPane: {
      resizeHandle: "shared.splitPane.resizeHandle",
    },
    routeError: {
      title: "shared.routeError.title",
      message: "shared.routeError.message",
      retry: "shared.routeError.retry",
      home: "shared.routeError.home",
    },
  },
} as const;

export type Strings = typeof strings;
