import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import type { ComponentProps } from "react";
import type { QueryClient } from "@tanstack/react-query";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import { DecisionStreamView } from "./DecisionStreamView";
import { createTestQueryClient, renderWithProviders } from "../../test-utils";
import { defaultApiClient } from "../../lib/api-client";
import { selectors } from "../../consts/selectors";
import type { CrossItemQuestion } from "../../lib/command-post-utils";

// Real stream, decision hook, renderer and backlog service. Fixture IDs only;
// a flagged archive-review PUT is intercepted, never a Planner acceptance.
const ids = selectors.commandPost.decisionStream;
function question(id: string, name = "fixture-one"): CrossItemQuestion {
  return { parentKind: "fix", parentName: name, parentTitle: `Owner ${name}`, question: { id, source: "review", item_kind: "fix", item_name: name, review_type: "target", title: `Review ${id}`, description: `Inspect synthetic ${id}` } };
}
const clients: QueryClient[] = [];
const unmounts: Array<() => void> = [];
let allowPut = false;
function mount(questions: CrossItemQuestion[], extra: Partial<ComponentProps<typeof DecisionStreamView>> = {}) {
  const client = createTestQueryClient(); clients.push(client);
  const callbacks = { onComplete: vi.fn(), onBack: vi.fn(), onSnoozeItem: vi.fn(), onCurrentQuestionChange: vi.fn(), onOpenItem: vi.fn(), onOpenSidebar: vi.fn() };
  const view = renderWithProviders(<DecisionStreamView questions={questions} {...callbacks} {...extra} />, { queryClient: client }); unmounts.push(view.unmount); return { ...callbacks, ...view };
}
function noWrites() { for (const method of ["post", "put", "patch", "delete"] as const) expect(defaultApiClient[method]).not.toHaveBeenCalled(); }
beforeEach(() => { allowPut = false; for (const method of ["get", "post", "put", "patch", "delete"] as const) vi.spyOn(defaultApiClient, method).mockRejectedValue(new Error(`Unexpected synthetic stream ${method}`)); vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("Unexpected decision transport"))); });
afterEach(() => { unmounts.splice(0).forEach(unmount => unmount()); cleanup(); getSpatialNav()?.dispose(); try { expect(defaultApiClient.get).not.toHaveBeenCalled(); expect(fetch).not.toHaveBeenCalled(); for (const method of ["post", "patch", "delete"] as const) expect(defaultApiClient[method]).not.toHaveBeenCalled(); if (!allowPut) expect(defaultApiClient.put).not.toHaveBeenCalled(); } finally { clients.splice(0).forEach(c => c.clear()); vi.restoreAllMocks(); vi.unstubAllGlobals(); } });

describe("Decision stream actual owner workflows", () => {
  it("opens exact current parent and sidebar without saving a review", () => { const view = mount([question("fixture-q1")]); fireEvent.click(screen.getByTestId(ids.openItemLink)); fireEvent.click(screen.getByRole("button", { name: "Open sidebar" })); expect(view.onOpenItem).toHaveBeenCalledWith("fix", "fixture-one"); expect(view.onOpenSidebar).toHaveBeenCalledOnce(); noWrites(); });
  it("jumps to another parent through the real navigator and repairs current identity", async () => { const view = mount([question("fixture-q1"), question("fixture-q2", "fixture-two")]); fireEvent.click(screen.getByTestId(ids.navigatorButton)); fireEvent.click(screen.getAllByTestId(ids.navigatorRow)[1]!); expect(screen.getByText("Review fixture-q2")).toBeVisible(); expect(screen.getByTestId(ids.counter)).toHaveTextContent("2/2"); await waitFor(() => expect(view.onCurrentQuestionChange).toHaveBeenLastCalledWith("fixture-q2")); noWrites(); });
  it("snoozes a specific navigator parent without jumping or saving its questions", () => { const view = mount([question("fixture-q1"), question("fixture-q2", "fixture-two")]); fireEvent.click(screen.getByTestId(ids.navigatorButton)); const row = screen.getAllByTestId(ids.navigatorRow)[1]!; fireEvent.click(within(row).getByTitle("Snooze this item")); expect(view.onSnoozeItem).toHaveBeenCalledWith("backlog:fix/fixture-two"); expect(screen.getByText("Review fixture-q1")).toBeVisible(); expect(screen.queryByText("Review fixture-q2")).toBeNull(); noWrites(); });
  it("closes the navigator with Escape without dismissing the stream", () => { const view = mount([question("fixture-q1")]); fireEvent.click(screen.getByTestId(ids.navigatorButton)); expect(screen.getByTestId(ids.navigatorRow)).toBeVisible(); fireEvent.keyDown(document, { key: "Escape" }); expect(screen.queryByTestId(ids.navigatorRow)).toBeNull(); expect(view.onBack).not.toHaveBeenCalled(); expect(screen.getByText("Review fixture-q1")).toBeVisible(); noWrites(); });
  it("keeps embedded question navigation distinct from queue completion", async () => { const complete = vi.fn(); mount([question("fixture-q1"), question("fixture-q2")], { embedded: true, onQueueComplete: complete }); expect(screen.queryByTestId(ids.header)).toBeNull(); expect(screen.getByTestId("ds-sub-position")).toHaveTextContent("Question 1 of 2"); fireEvent.click(screen.getByRole("button", { name: "Skip question" })); expect(screen.getByText("Review fixture-q2")).toBeVisible(); expect(complete).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Previous question" })); expect(screen.getByText("Review fixture-q1")).toBeVisible(); noWrites(); });
  it("keeps exact flagged save pending before completing and disables a duplicate", async () => { allowPut = true; let release!: (value: unknown) => void; vi.mocked(defaultApiClient.put).mockImplementation(() => new Promise(resolve => { release = resolve; })); const view = mount([question("fixture-q1")]); fireEvent.click(screen.getByRole("button", { name: "Flag" })); fireEvent.change(screen.getByPlaceholderText("Comment (optional)..."), { target: { value: "Fixture evidence requires rework" } }); fireEvent.click(screen.getByTestId(ids.navNext)); await waitFor(() => expect(defaultApiClient.put).toHaveBeenCalledWith("/backlog/fix/fixture-one/archive/review", { items: [{ id: "fixture-q1", type: "target", module_id: undefined, review_status: "flagged", review_comment: "Fixture evidence requires rework" }] })); expect(screen.getByTestId(ids.navNext)).toBeDisabled(); fireEvent.click(screen.getByTestId(ids.navNext)); expect(defaultApiClient.put).toHaveBeenCalledOnce(); expect(view.onComplete).not.toHaveBeenCalled(); await act(async () => release({})); expect(await screen.findByText("Decision stream complete")).toBeVisible(); expect(screen.getByText(/Saved 1 answer/)).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "Back to Command Post" })); expect(view.onComplete).toHaveBeenCalledWith({ answeredCount: 1, skippedCount: 0, snoozedCount: 0, unlockedItems: [] }); });
  it("retains flagged draft on refusal without automatic retry or false completion", async () => { allowPut = true; vi.mocked(defaultApiClient.put).mockRejectedValue(new Error("Fixture review refused")); const view = mount([question("fixture-q1")]); fireEvent.click(screen.getByRole("button", { name: "Flag" })); fireEvent.change(screen.getByPlaceholderText("Comment (optional)..."), { target: { value: "Unaccepted fixture note" } }); fireEvent.click(screen.getByTestId(ids.navNext)); expect(await screen.findByText("Save failed — will retry on next advance")).toBeVisible(); expect(screen.getByPlaceholderText("Comment (optional)...")).toHaveValue("Unaccepted fixture note"); expect(defaultApiClient.put).toHaveBeenCalledOnce(); expect(view.onComplete).not.toHaveBeenCalled(); expect(screen.queryByText("Decision stream complete")).toBeNull(); });
  it("reports all skipped questions and closes through the explicit completion callback", async () => { const view = mount([question("fixture-q1"), question("fixture-q2")]); fireEvent.click(screen.getByTestId(ids.navSkip)); fireEvent.click(screen.getByTestId(ids.navSkip)); expect(await screen.findByText("Decision stream complete")).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "Back to Command Post" })); expect(view.onComplete).toHaveBeenCalledWith({ answeredCount: 0, skippedCount: 2, snoozedCount: 0, unlockedItems: [] }); noWrites(); });
  it("reports the single skipped question exactly once", async () => { const view = mount([question("fixture-only")]); fireEvent.click(screen.getByTestId(ids.navSkip)); expect(await screen.findByText("Decision stream complete")).toBeVisible(); expect(screen.getByText(/Skipped 1/)).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "Back to Command Post" })); expect(view.onComplete).toHaveBeenCalledOnce(); expect(view.onComplete).toHaveBeenCalledWith({ answeredCount: 0, skippedCount: 1, snoozedCount: 0, unlockedItems: [] }); noWrites(); });
  it("counts a saved flag and final skipped sibling separately", async () => { allowPut = true; vi.mocked(defaultApiClient.put).mockResolvedValue({}); const view = mount([question("fixture-q1"), question("fixture-q2")]); fireEvent.click(screen.getByRole("button", { name: "Flag" })); fireEvent.click(screen.getByTestId(ids.navNext)); await screen.findByText("Review fixture-q2"); fireEvent.click(screen.getByTestId(ids.navSkip)); expect(await screen.findByText("Decision stream complete")).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "Back to Command Post" })); expect(view.onComplete).toHaveBeenCalledWith({ answeredCount: 1, skippedCount: 1, snoozedCount: 0, unlockedItems: [] }); expect(defaultApiClient.put).toHaveBeenCalledOnce(); });
  it("delegates embedded queue completion without a second completion callback", async () => { const queueComplete = vi.fn(); const view = mount([question("fixture-q1"), question("fixture-q2")], { embedded: true, onQueueComplete: queueComplete }); fireEvent.click(screen.getByRole("button", { name: "Skip question" })); expect(queueComplete).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Flag" })); allowPut = true; vi.mocked(defaultApiClient.put).mockResolvedValue({}); fireEvent.click(screen.getByRole("button", { name: "Save answer" })); await waitFor(() => expect(queueComplete).toHaveBeenCalledOnce()); expect(view.onComplete).not.toHaveBeenCalled(); expect(defaultApiClient.put).toHaveBeenCalledOnce(); });

});
