import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import type { QueryClient } from "@tanstack/react-query";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import { ProposalDecisionStreamView, type ProposalDecisionStreamItem } from "./ProposalDecisionStreamView";
import { defaultApiClient } from "../../lib/api-client";
import { createTestQueryClient, renderWithProviders } from "../../test-utils";

// Real projection, backlog read, proposal service and generated decision client.
// No proposal is accepted/applied, archived or sent to a live server.
function proposal(id = "fixture-p1", target = true): ProposalDecisionStreamItem {
  return { sessionId: "fixture-session", sessionTitle: "Disposable owner inspection", ...(target ? { target: { type: "backlog_item" as const, ref: "fix/fixture-target", name: "Fixture target" } } : {}), proposal: { id, kind: "mutation_list", status: "ready", summary: `Inspect ${id}`, payload_json: JSON.stringify({ mutations: [{ id: `${id}-title`, op: "update_item", target: "fix/fixture-target", patch: { title: "Proposed fixture title" } }, { id: `${id}-priority`, op: "update_item", target: "fix/fixture-target", patch: { priority: 1 } }] }), created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" } };
}
const clients: QueryClient[] = [];
const unmounts: Array<() => void> = [];
const decisions: unknown[] = [];
const unexpected: string[] = [];
let readRefused = false;
let releaseRead: ((value: unknown) => void) | undefined;
let deferredRead = false;
let decisionReply: () => Promise<Response>;
function mount(proposals: ProposalDecisionStreamItem[], embedded = false) {
  const client = createTestQueryClient(); clients.push(client);
  const callbacks = { onComplete: vi.fn(), onBack: vi.fn(), onSnooze: vi.fn(), onOpenItem: vi.fn(), onItemChanged: vi.fn() };
  const view = renderWithProviders(<ProposalDecisionStreamView proposals={proposals} {...callbacks} embedded={embedded} />, { queryClient: client }); unmounts.push(view.unmount); return { ...callbacks, ...view };
}
function noWrites() { for (const method of ["post", "put", "patch", "delete"] as const) expect(defaultApiClient[method]).not.toHaveBeenCalled(); expect(decisions).toEqual([]); }
beforeEach(() => {
  readRefused = false; deferredRead = false; releaseRead = undefined; decisions.length = 0; unexpected.length = 0;
  decisionReply = async () => new Response(JSON.stringify({ code: "permission_denied", message: "Fixture owner refused rejection" }), { status: 403, headers: { "Content-Type": "application/json" } });
  vi.spyOn(defaultApiClient, "get").mockImplementation(async path => {
    if (path === "/backlog/fix/fixture-target") { if (readRefused) throw new Error("Fixture target read refused"); if (deferredRead) return new Promise(resolve => { releaseRead = resolve; }); return { item: { name: "fixture-target", kind: "fix", title: "Current canonical fixture title", created: "2026-01-01T00:00:00Z", updated: "2026-01-01T00:00:00Z", description: "Current fixture description", status: "ready", priority: 2, tags: [], suggested_skills: [] } }; }
    unexpected.push(path); throw new Error(`Unexpected proposal stream read ${path}`);
  });
  for (const method of ["post", "put", "patch", "delete"] as const) vi.spyOn(defaultApiClient, method).mockRejectedValue(new Error(`Unexpected proposal stream ${method}`));
  vi.stubGlobal("fetch", vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const request = new Request(input, init); const path = new URL(request.url).pathname; if (!path.endsWith("/vrooli.swarm_manager.v1.api.BacklogService/DecideAttempt")) { unexpected.push(path); throw new Error(`Unexpected decision transport ${path}`); } decisions.push(JSON.parse(await request.text())); return decisionReply(); }));
});
afterEach(() => { unmounts.splice(0).forEach(unmount => unmount()); cleanup(); getSpatialNav()?.dispose(); try { expect(unexpected).toEqual([]); for (const method of ["post", "put", "patch", "delete"] as const) expect(defaultApiClient[method]).not.toHaveBeenCalled(); } finally { clients.splice(0).forEach(c => c.clear()); vi.restoreAllMocks(); vi.unstubAllGlobals(); } });

describe("Proposal decision stream actual owner workflows", () => {
  it("waits for canonical target values before presenting the replacement diff", async () => { deferredRead = true; mount([proposal()]); expect((await screen.findAllByText(/current values unavailable, showing incoming only/)).length).toBeGreaterThan(0); await waitFor(() => expect(releaseRead).toBeDefined()); await act(async () => releaseRead?.({ item: { name: "fixture-target", kind: "fix", title: "Current canonical fixture title", created: "2026-01-01T00:00:00Z", updated: "2026-01-01T00:00:00Z", status: "ready", priority: 2, tags: [] } })); await waitFor(() => expect(screen.getByText((_, element) => element?.textContent === "Current canonical fixture title" && Array.from(element.children).every(child => child.textContent !== "Current canonical fixture title"))).toBeVisible()); expect(screen.getByText((_, element) => element?.textContent === "Proposed fixture title" && Array.from(element.children).every(child => child.textContent !== "Proposed fixture title"))).toBeVisible(); expect(screen.queryAllByText(/current values unavailable, showing incoming only/)).toHaveLength(0); noWrites(); });
  it("degrades a refused target read to incoming-only inspection without applying anything", async () => { readRefused = true; mount([proposal()]); expect((await screen.findAllByText(/current values unavailable, showing incoming only/)).length).toBeGreaterThan(0); await waitFor(() => expect(defaultApiClient.get).toHaveBeenCalledOnce()); expect(screen.getByText((_, element) => element?.textContent === "Proposed fixture title" && Array.from(element.children).every(child => child.textContent !== "Proposed fixture title"))).toBeVisible(); expect(screen.getByRole("button", { name: "Apply selected (2)" })).toBeVisible(); noWrites(); });
  it("changes selected mutations locally and retains the typed decision note without a write", async () => { mount([proposal()]); const checkboxes = await screen.findAllByRole("checkbox"); expect(checkboxes).toHaveLength(2); fireEvent.click(checkboxes[0]!); expect(screen.getByRole("button", { name: "Apply selected (1)" })).toBeVisible(); fireEvent.change(screen.getByPlaceholderText("Decision note (optional)"), { target: { value: "Unsubmitted fixture note" } }); expect(screen.getByPlaceholderText("Decision note (optional)")).toHaveValue("Unsubmitted fixture note"); noWrites(); });
  it("resets local selection and note when the parent replaces the current proposal", async () => { const first = proposal(); const view = mount([first]); fireEvent.click((await screen.findAllByRole("checkbox"))[0]!); fireEvent.change(screen.getByPlaceholderText("Decision note (optional)"), { target: { value: "First proposal only" } }); view.rerender(<ProposalDecisionStreamView proposals={[proposal("fixture-p2")]} onComplete={view.onComplete} onBack={view.onBack} onSnooze={view.onSnooze} />); await waitFor(() => expect(screen.getByPlaceholderText("Decision note (optional)")).toHaveValue("")); expect(screen.getByRole("button", { name: "Apply selected (2)" })).toBeVisible(); noWrites(); });
  it("opens the target callback without applying the recommendation", async () => { const view = mount([proposal()]); fireEvent.click(await screen.findByRole("button", { name: "Fixture target" })); expect(view.onOpenItem).toHaveBeenCalledOnce(); noWrites(); });
  it("cancels target archiving without resolving the proposal or refreshing its owner", async () => { const view = mount([proposal()]); fireEvent.click(await screen.findByTestId("proposal-archive-item")); const dialog = await screen.findByTestId("proposal-archive-confirm"); expect(dialog).toHaveTextContent("Fixture target will be archived"); fireEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); expect(screen.queryByTestId("proposal-archive-confirm")).toBeNull(); expect(view.onComplete).not.toHaveBeenCalled(); expect(view.onItemChanged).not.toHaveBeenCalled(); noWrites(); });
  it("snoozes only the exact proposal and keeps its sibling actionable without a decision", async () => { const view = mount([proposal("fixture-p1", false), proposal("fixture-p2", false)]); fireEvent.click(screen.getByRole("button", { name: "Snooze" })); expect(view.onSnooze).toHaveBeenCalledWith("fixture-p1"); expect(screen.getByText("Inspect fixture-p2")).toBeVisible(); expect(screen.queryByText("Inspect fixture-p1")).toBeNull(); noWrites(); });
  it("holds a rejected decision pending, then retains the same proposal/note on owner refusal", async () => { let finish!: (response: Response) => void; decisionReply = () => new Promise(resolve => { finish = resolve; }); const view = mount([proposal()]); fireEvent.change(screen.getByPlaceholderText("Decision note (optional)"), { target: { value: "Keep original owner state" } }); fireEvent.click(screen.getByRole("button", { name: "Reject proposal" })); await waitFor(() => expect(decisions).toEqual([{ subjectKind: "agent-session-proposal", subjectRef: "fixture-session/fixture-p1", roundNum: 1, decision: "drop", actor: "operator-ui", rationale: "Keep original owner state" }])); expect(screen.getByRole("button", { name: "Reject proposal" })).toBeDisabled(); fireEvent.click(screen.getByRole("button", { name: "Reject proposal" })); expect(decisions).toHaveLength(1); await act(async () => finish(new Response(JSON.stringify({ code: "permission_denied", message: "Fixture owner refused rejection" }), { status: 403, headers: { "Content-Type": "application/json" } }))); expect(await screen.findByText(/Fixture owner refused rejection/)).toBeVisible(); expect(screen.getByPlaceholderText("Decision note (optional)")).toHaveValue("Keep original owner state"); expect(screen.getByRole("button", { name: "Reject proposal" })).not.toBeDisabled(); expect(view.onComplete).not.toHaveBeenCalled(); expect(view.onItemChanged).not.toHaveBeenCalled(); expect(decisions).toHaveLength(1); });
  it("presents a keep recommendation as inspection without applying or accepting it", () => { const item = proposal("fixture-keep", false); item.proposal.kind = "no_change_recommendation"; item.proposal.payload_json = JSON.stringify({ rationale: "Fixture inspection found no required change" }); mount([item]); expect(screen.getByText("No changes recommended")).toBeVisible(); expect(screen.getByRole("button", { name: "Accept keep recommendation" })).toBeVisible(); expect(screen.queryByRole("checkbox")).toBeNull(); expect(defaultApiClient.get).not.toHaveBeenCalled(); noWrites(); });
  it("embeds a single proposal without conflicting queue controls", () => { mount([proposal("fixture-p1", false)], true); expect(screen.queryByTestId("proposal-sub-position")).toBeNull(); expect(screen.queryByRole("button", { name: "Back" })).toBeNull(); expect(screen.queryByRole("button", { name: "Snooze" })).toBeNull(); expect(screen.getByRole("button", { name: "Reject proposal" })).toBeVisible(); noWrites(); });
});
