import { useState } from "react";
import { Input } from "../components/ui/input";
import { Button } from "@vrooli/react-component-library/Button/2";
import { proseApi } from "../api/prose";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { EmptyState } from "@vrooli/react-component-library/EmptyState/1";
import { selectors } from "../consts/selectors";
import { SurfaceFrame } from "./VariationPage";

export function DocumentPage() {
  const [title, setTitle] = useState(""); const [profile, setProfile] = useState("content-desk/marketing-dev-log-profile"); const [document, setDocument] = useState<Record<string, any>>(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(false);
  const createDocument = async () => { setLoading(true); setError(undefined); try { const result = await proseApi.createDocument(title, profile); setDocument(result.document); } catch (err) { setError(err instanceof Error ? err.message : "Document creation failed"); } finally { setLoading(false); } };
  const assemble = async () => { if (!document?.id) return; setLoading(true); try { const result = await proseApi.assemble(document.id); setDocument(result.document); } catch (err) { setError(err instanceof Error ? err.message : "Assembly failed"); } finally { setLoading(false); } };
  const outline = (document?.outline ?? []) as Array<{ intent: string; summary: string; target_words: number }>;
  return <SurfaceFrame eyebrow="Composition" title="Document Workspace" description="Converge an outline and each section independently, with bounded feed-forward context." testId={selectors.pages.document} headingId="document-heading"><div className="grid gap-4 rounded-control border border-app-border p-4 md:grid-cols-[1fr_1fr_auto]"><label className="text-sm">Title<Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="A shipped subject" /></label><label className="text-sm">Profile<Input value={profile} onChange={(event) => setProfile(event.target.value)} /></label><Button disabled={loading || !title.trim()} onClick={createDocument} title={!title.trim() ? "Enter a title before creating a document" : undefined}>Create document</Button></div>{error && <p role="alert" className="rounded-control border border-app-danger p-4">{error}</p>}<div className="grid gap-4 lg:grid-cols-[18rem_1fr]"><Card><CardHeader><CardTitle>Outline rail</CardTitle><CardDescription>Generated sections and target lengths.</CardDescription></CardHeader><CardContent>{outline.length === 0 ? <p className="text-sm text-app-muted-foreground">Create a document to generate a typed outline.</p> : <ol className="flex flex-col gap-3 text-sm">{outline.map((section, index) => <li key={`${section.intent}-${index}`} className="rounded-control border border-app-border p-3"><span className="font-medium">{index + 1}. {section.intent}</span><span className="block text-xs text-app-muted-foreground">{section.target_words} words · {section.summary}</span></li>)}</ol>}</CardContent></Card><Card><CardHeader><CardTitle>Document output</CardTitle><CardDescription>Committed sections remain durable; context is bounded and resumable.</CardDescription></CardHeader><CardContent>{!document ? <EmptyState title="No document selected" description="Create a document to start the outline and section sessions." action={<a className="inline-flex min-h-11 items-center justify-center rounded-control bg-app-primary px-3 py-2 text-sm font-medium text-app-primary-foreground" href="/variation">Open variation board</a>} /> : document.assembled_text ? <><p className="whitespace-pre-wrap">{document.assembled_text}</p><Button className="mt-4" onClick={assemble} disabled={loading}>Re-assemble</Button></> : <EmptyState title="No assembled document yet" description="The outline is being composed; assemble after sections commit." action={<Button onClick={assemble} disabled={loading} title={loading ? "Assembly is running" : undefined}>Assemble</Button>} />}</CardContent></Card></div></SurfaceFrame>;
}
