import { Link } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { EmptyState } from "../components/ui/empty-state";
import { selectors } from "../consts/selectors";
import { SurfaceFrame } from "./VariationPage";

export function DocumentPage() {
  return <SurfaceFrame eyebrow="Composition" title="Document Workspace" description="Converge an outline and each section independently, with bounded feed-forward context." testId={selectors.pages.document} headingId="document-heading"><div className="grid gap-4 lg:grid-cols-[18rem_1fr]"><Card><CardHeader><CardTitle>Outline rail</CardTitle><CardDescription>Sections own their own passage session.</CardDescription></CardHeader><CardContent><ol className="flex flex-col gap-3 text-sm"><li className="rounded-control border border-app-primary bg-app-surface-muted p-3"><span className="font-medium">1. Opening</span><span className="block text-xs text-app-muted-foreground">Not started</span></li><li className="rounded-control border border-app-border p-3"><span className="font-medium">2. Evidence</span><span className="block text-xs text-app-muted-foreground">Waiting for outline</span></li><li className="rounded-control border border-app-border p-3"><span className="font-medium">3. Close</span><span className="block text-xs text-app-muted-foreground">Waiting for outline</span></li></ol></CardContent></Card><Card><CardHeader><CardTitle>Active section</CardTitle><CardDescription>Context includes the outline, prior committed sections, following intents, and the resolved profile.</CardDescription></CardHeader><CardContent><EmptyState title="No document selected" description="Create a document to begin outline variation and section-level convergence." action={<Link className="inline-flex min-h-11 items-center justify-center rounded-control bg-app-primary px-3 text-sm font-medium text-app-primary-foreground focus-visible:outline focus-visible:outline-2" to="/variation">Open variation board</Link>} /></CardContent></Card></div></SurfaceFrame>;
}
