export {
  initIframeBridgeChild,
  shimStorage,
  type BridgeChildController,
  type BridgeChildOptions,
  type BridgeCapability,
  type BridgeLogEvent,
  type BridgeLogStreamState,
  type BridgeNetworkEvent,
  type BridgeNetworkStreamState,
  type BridgeLogLevel,
  type BridgeScreenshotMode,
  type BridgeScreenshotOptions,
  type BridgeInspectRect,
  type BridgeInspectElementMeta,
  type BridgeInspectAncestorMeta,
  type BridgeInspectHoverPayload,
  type BridgeInspectResultPayload,
  type LogCaptureOptions,
  type NetworkCaptureOptions,
  type StorageShimEntry,
} from './iframeBridgeChild.js';
