export {
  initIframeBridgeChild,
  shimStorage,
  type BridgeChildController,
  type BridgeChildOptions,
  type BridgeCapability,
  type BridgeLogEvent,
  type BridgeLogStreamState,
  type BridgeNetworkEvent,
  type BridgeNetworkStreamState,
  type BridgeLogLevel,
  type BridgeScreenshotMode,
  type BridgeScreenshotOptions,
  type BridgeInspectRect,
  type BridgeInspectElementMeta,
  type BridgeInspectAncestorMeta,
  type BridgeInspectHoverPayload,
  type BridgeInspectResultPayload,
  type LogCaptureOptions,
  type NetworkCaptureOptions,
  type StorageShimEntry,
  emitShortcutIntent,
  HOST_SHORTCUT_ACTION_OPEN_GLOBAL_SWITCHER,
  type BridgeShortcutIntent,
  type BridgeShortcutOutcome,
} from './iframeBridgeChild.js';

// Spatial navigation (also available via `@vrooli/iframe-bridge/spatial`)
export {
  initSpatialNav,
  GamepadInputManager,
  SpatialNavManager,
  FOCUSABLE_SELECTOR,
  DEFAULT_SPATIAL_FOCUS_CSS,
  injectSpatialStyles,
  removeSpatialStyles,
  type SpatialNavController,
  type SpatialNavBridgeOptions,
  type GamepadAction,
  type GamepadInputOptions,
  type Direction,
  type FocusGroupMode,
  type FocusGroupOptions,
  type SpatialNavOptions,
  showActivationOverlay,
  type ActivationOverlayOptions,
  type ActivationOverlayHandle,
  type DismissReason,
} from './spatialNavBridge.js';
