/**
 * Popup Script for {{APP_NAME}} Extension
 * 
 * This script handles:
 * - Popup UI state management
 * - User authentication and settings
 * - Communication with background service worker
 * - Scenario-specific popup functionality
 * 
 * Generated by scenario-to-extension for Vrooli
 */

// ============================================
// Configuration
// ============================================

const POPUP_CONFIG = {
    SCENARIO_NAME: '{{SCENARIO_NAME}}',
    VERSION: '{{VERSION}}',
    DEBUG: {{DEBUG_MODE}},
    DEFAULT_API_ENDPOINT: '{{API_ENDPOINT}}'
};

// ============================================
// State Management
// ============================================

class PopupState {
    constructor() {
        this.isInitialized = false;
        this.isAuthenticated = false;
        this.user = null;
        this.scenarioData = {};
        this.currentTab = null;
        this.stats = {};
    }
    
    update(newState) {
        Object.assign(this, newState);
        this.render();
    }
}

const popupState = new PopupState();

// ============================================
// Background Communication
// ============================================

class BackgroundMessenger {
    static async send(type, data = {}) {
        return new Promise((resolve) => {
            chrome.runtime.sendMessage({ type, data }, (response) => {
                if (chrome.runtime.lastError) {
                    console.error('Message error:', chrome.runtime.lastError);
                    resolve({ error: chrome.runtime.lastError.message });
                } else {
                    resolve(response || { success: true });
                }
            });
        });
    }
    
    static async getState() {
        return this.send('GET_STATE');
    }
    
    static async authenticate(credentials) {
        return this.send('AUTHENTICATE', credentials);
    }
    
    static async syncData() {
        return this.send('SYNC_DATA');
    }
    
    static async executeAction(action, payload) {
        return this.send('SCENARIO_ACTION', { action, data: payload });
    }
    
    static async getCurrentPage() {
        return this.send('GET_CURRENT_PAGE');
    }
}

// ============================================
// UI Management
// ============================================

class UIManager {
    static showSection(sectionId) {
        // Hide all sections
        document.querySelectorAll('.section').forEach(section => {
            section.classList.add('hidden');
        });
        
        // Show target section
        const targetSection = document.getElementById(sectionId);
        if (targetSection) {
            targetSection.classList.remove('hidden');
        }
    }
    
    static updateStatusIndicator(status) {
        const indicator = document.getElementById('status-indicator');
        indicator.className = 'status-indicator';
        
        switch (status) {
            case 'connected':
                indicator.classList.add('status-connected');
                break;
            case 'disconnected':
                indicator.classList.add('status-disconnected');
                break;
            case 'error':
                indicator.classList.add('status-error');
                break;
        }
    }
    
    static showMessage(type, message, autoHide = true) {
        const messageEl = document.getElementById(`${type}-message`);
        const textEl = document.getElementById(`${type}-text`);
        
        if (messageEl && textEl) {
            textEl.textContent = message;
            messageEl.classList.remove('hidden');
            
            if (autoHide) {
                setTimeout(() => {
                    messageEl.classList.add('hidden');
                }, 5000);
            }
        }
    }
    
    static hideMessage(type) {
        const messageEl = document.getElementById(`${type}-message`);
        if (messageEl) {
            messageEl.classList.add('hidden');
        }
    }
    
    static setLoading(elementId, isLoading) {
        const element = document.getElementById(elementId);
        const spinner = element?.querySelector('.spinner');
        const text = element?.querySelector('span');
        
        if (element) {
            element.disabled = isLoading;
        }
        
        if (spinner) {
            spinner.classList.toggle('hidden', !isLoading);
        }
        
        if (text && isLoading) {
            text.textContent = 'Please wait...';
        }
    }
    
    static updateStats(stats) {
        Object.entries(stats).forEach(([key, value]) => {
            const statElement = document.getElementById(`stat-${key}`);
            if (statElement) {
                statElement.textContent = value;
            }
        });
    }
    
    static updateCurrentPageInfo(pageInfo) {
        const titleEl = document.getElementById('current-title');
        const urlEl = document.getElementById('current-url');
        
        if (titleEl && pageInfo.title) {
            titleEl.textContent = pageInfo.title;
        }
        
        if (urlEl && pageInfo.url) {
            urlEl.textContent = pageInfo.url;
        }
    }
}

// ============================================
// Authentication
// ============================================

class AuthManager {
    static async authenticate(formData) {
        try {
            UIManager.setLoading('login-form', true);
            UIManager.hideMessage('error');
            
            const credentials = {
                apiEndpoint: formData.get('api-endpoint'),
                {{AUTH_CREDENTIAL_MAPPING}}
            };
            
            const response = await BackgroundMessenger.authenticate(credentials);
            
            if (response.success) {
                popupState.update({
                    isAuthenticated: true,
                    user: response.user
                });
                
                UIManager.showMessage('success', 'Successfully connected to {{APP_NAME}}!');
                setTimeout(() => {
                    this.showDashboard();
                }, 1000);
                
            } else {
                UIManager.showMessage('error', response.error || 'Authentication failed');
            }
            
        } catch (error) {
            console.error('Authentication error:', error);
            UIManager.showMessage('error', 'Connection failed. Please check your settings.');
        } finally {
            UIManager.setLoading('login-form', false);
        }
    }
    
    static showAuthForm() {
        UIManager.showSection('auth-section');
        UIManager.updateStatusIndicator('disconnected');
    }
    
    static showDashboard() {
        UIManager.showSection('dashboard-section');
        UIManager.updateStatusIndicator('connected');
    }
}

// ============================================
// Dashboard Management
// ============================================

class DashboardManager {
    static async refresh() {
        try {
            // Get latest state
            const state = await BackgroundMessenger.getState();
            popupState.update(state);
            
            // Get current page info
            const pageResponse = await BackgroundMessenger.getCurrentPage();
            if (pageResponse.pageInfo) {
                UIManager.updateCurrentPageInfo(pageResponse.pageInfo);
            }
            
            // Update user info
            this.updateUserInfo(state);
            
            // Update stats
            if (state.scenarioData && state.scenarioData.stats) {
                UIManager.updateStats(state.scenarioData.stats);
            }
            
        } catch (error) {
            console.error('Dashboard refresh failed:', error);
        }
    }
    
    static updateUserInfo(state) {
        const userNameEl = document.getElementById('user-name');
        const lastSyncEl = document.getElementById('last-sync');
        
        if (userNameEl && state.user) {
            userNameEl.textContent = state.user.name || state.user.email || 'Connected User';
        }
        
        if (lastSyncEl && state.lastSync) {
            const lastSyncDate = new Date(state.lastSync);
            lastSyncEl.textContent = lastSyncDate.toLocaleTimeString();
        }
    }
}

// ============================================
// Action Handlers
// ============================================

class ActionHandlers {
    {{CUSTOM_ACTION_HANDLERS}}
    
    static async syncNow() {
        try {
            UIManager.showMessage('success', 'Syncing with scenario...');
            await BackgroundMessenger.syncData();
            await DashboardManager.refresh();
            UIManager.showMessage('success', 'Sync completed successfully!');
        } catch (error) {
            UIManager.showMessage('error', 'Sync failed: ' + error.message);
        }
    }
    
    static async openScenarioPage() {
        chrome.tabs.create({ 
            url: `${POPUP_CONFIG.DEFAULT_API_ENDPOINT}/dashboard` 
        });
        window.close();
    }
    
    static async refreshExtension() {
        chrome.runtime.reload();
    }
    
    static async openHelp() {
        chrome.tabs.create({ 
            url: `${POPUP_CONFIG.DEFAULT_API_ENDPOINT}/help/extension` 
        });
        window.close();
    }
    
    static async executeQuickAction(actionName, actionData = {}) {
        try {
            UIManager.showMessage('success', `Executing ${actionName}...`);
            
            const response = await BackgroundMessenger.executeAction(actionName, actionData);
            
            if (response.success) {
                UIManager.showMessage('success', response.message || `${actionName} completed successfully!`);
                
                // Refresh dashboard if action affects data
                if (response.refreshDashboard) {
                    await DashboardManager.refresh();
                }
            } else {
                UIManager.showMessage('error', response.error || `${actionName} failed`);
            }
            
        } catch (error) {
            console.error('Quick action failed:', error);
            UIManager.showMessage('error', `${actionName} failed: ${error.message}`);
        }
    }
}

// ============================================
// Event Handlers
// ============================================

class EventHandlers {
    static setupFormHandlers() {
        // Login form
        const loginForm = document.getElementById('login-form');
        if (loginForm) {
            loginForm.addEventListener('submit', (e) => {
                e.preventDefault();
                const formData = new FormData(loginForm);
                AuthManager.authenticate(formData);
            });
        }
    }
    
    static setupButtonHandlers() {
        // Footer buttons
        document.getElementById('refresh-btn')?.addEventListener('click', (e) => {
            e.preventDefault();
            DashboardManager.refresh();
        });
        
        document.getElementById('settings-btn')?.addEventListener('click', (e) => {
            e.preventDefault();
            ActionHandlers.openScenarioPage();
        });
        
        document.getElementById('help-btn')?.addEventListener('click', (e) => {
            e.preventDefault();
            ActionHandlers.openHelp();
        });
        
        // Action buttons (dynamically added)
        document.addEventListener('click', (e) => {
            if (e.target.matches('[data-action]')) {
                e.preventDefault();
                const action = e.target.getAttribute('data-action');
                const actionData = e.target.dataset.actionData ? 
                    JSON.parse(e.target.dataset.actionData) : {};
                ActionHandlers.executeQuickAction(action, actionData);
            }
        });
    }
    
    static setupKeyboardHandlers() {
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') {
                window.close();
            }
            
            if (e.key === 'F5' || (e.ctrlKey && e.key === 'r')) {
                e.preventDefault();
                DashboardManager.refresh();
            }
        });
    }
}

// ============================================
// Initialization
// ============================================

async function initializePopup() {
    console.log(`{{APP_NAME}} popup initializing...`);
    
    try {
        // Set up event handlers
        EventHandlers.setupFormHandlers();
        EventHandlers.setupButtonHandlers();
        EventHandlers.setupKeyboardHandlers();
        
        // Get initial state
        const state = await BackgroundMessenger.getState();
        
        if (state.error) {
            console.error('Failed to get extension state:', state.error);
            UIManager.showMessage('error', 'Failed to connect to extension background service');
            return;
        }
        
        popupState.update(state);
        
        // Show appropriate section
        if (state.isAuthenticated) {
            AuthManager.showDashboard();
            await DashboardManager.refresh();
        } else {
            AuthManager.showAuthForm();
        }
        
        // Hide loading
        UIManager.showSection(state.isAuthenticated ? 'dashboard-section' : 'auth-section');
        
        console.log(`{{APP_NAME}} popup initialized`);
        
    } catch (error) {
        console.error('Popup initialization failed:', error);
        UIManager.showMessage('error', 'Popup initialization failed');
    }
}

// ============================================
// Render Functions
// ============================================

function renderDashboard() {
    // Render scenario-specific dashboard content
    {{DASHBOARD_RENDER_LOGIC}}
}

function renderStats() {
    // Render statistics cards
    {{STATS_RENDER_LOGIC}}
}

function renderActions() {
    // Render quick action buttons
    {{ACTIONS_RENDER_LOGIC}}
}

// ============================================
// Lifecycle
// ============================================

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', initializePopup);

// Handle popup close
window.addEventListener('beforeunload', () => {
    console.log('{{APP_NAME}} popup closing');
});

console.log(`{{APP_NAME}} popup script loaded (v${POPUP_CONFIG.VERSION})`);