package machines

import (
	"vrooli-bridge/internal/module"

	machinesconnect "github.com/vrooli/vrooli/packages/proto/gen/go/vrooli-bridge/v1/machines/machines_v1connect"
)

var Endpoints = []module.EndpointDescriptor{
	{ID: "machines_create", Path: machinesconnect.MachineServiceCreateMachineProcedure, Method: "POST", Summary: "Create a durable machine", Description: "Creates operator-intent identity with validated connection locators. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"locators": "array<ConnectionLocator> (required)", "desired_profile_id": "string", "desired_profile_version": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine"}}, Errors: []module.ErrorDesc{{Status: 400, Code: "invalid_argument", Description: "Invalid or missing locator"}, {Status: 401, Code: "unauthenticated", Description: "Owner token required"}}},
	{ID: "machines_repair", Path: machinesconnect.MachineServiceRepairMachineProcedure, Method: "POST", Summary: "Repair a Machine in place", Description: "Reuses the durable Machine identity and starts a normal Bridge-managed enrollment attempt; it never creates a replacement Machine. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine", "onboarding_op_id": "string", "enrollment_attempt_id": "string"}}, Errors: []module.ErrorDesc{{Status: 401, Code: "unauthenticated", Description: "Owner token required"}, {Status: 404, Code: "not_found", Description: "Unknown machine"}, {Status: 412, Code: "failed_precondition", Description: "Repair unavailable or ambiguous identity"}}},
	{ID: "machines_merge", Path: machinesconnect.MachineServiceMergeMachinesProcedure, Method: "POST", Summary: "Merge duplicate machines", Description: "Folds locators and Node lineage into the selected target, archives the source, and writes an audit event. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"from_machine_id": "string (required)", "into_machine_id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine", "archived_machine_id": "string"}}, Errors: []module.ErrorDesc{{Status: 400, Code: "invalid_argument", Description: "Invalid source or target"}, {Status: 401, Code: "unauthenticated", Description: "Owner token required"}, {Status: 404, Code: "not_found", Description: "Unknown machine"}}},
	{ID: "machines_get", Path: machinesconnect.MachineServiceGetMachineProcedure, Method: "POST", Summary: "Get a machine", Description: "Returns durable intent and node lineage; live Node state is not copied. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine"}}, Errors: []module.ErrorDesc{{Status: 401, Code: "unauthenticated", Description: "Owner token required"}, {Status: 404, Code: "not_found", Description: "Unknown machine"}}},
	{ID: "machines_get_configuration", Path: machinesconnect.MachineServiceGetMachineConfigurationProcedure, Method: "POST", Summary: "Get machine configuration", Description: "Returns desired and applied selection documents with readiness and typed drift. Owner-gated.", Category: "configuration", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine", "desired_selection_json": "string", "applied_selection_json": "string", "drift": "array<MachineDrift>"}}},
	{ID: "machines_list", Path: machinesconnect.MachineServiceListMachinesProcedure, Method: "POST", Summary: "List machines", Description: "Lists durable Machine identities and histories. Owner-gated.", Category: "machines", Response: &module.Schema{Type: "object", Properties: map[string]string{"machines": "array<Machine>"}}, Errors: []module.ErrorDesc{{Status: 401, Code: "unauthenticated", Description: "Owner token required"}}},
	{ID: "machines_archive", Path: machinesconnect.MachineServiceArchiveMachineProcedure, Method: "POST", Summary: "Archive a machine", Description: "Applies an optimistic-version lifecycle archive without deleting history. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)", "version": "int64 (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine"}}, Errors: []module.ErrorDesc{{Status: 401, Code: "unauthenticated", Description: "Owner token required"}, {Status: 404, Code: "not_found", Description: "Unknown machine"}, {Status: 409, Code: "aborted", Description: "Version conflict"}}},
	{ID: "machines_remove", Path: machinesconnect.MachineServiceRemoveMachineProcedure, Method: "POST", Summary: "Remove a machine locally", Description: "Records local removal only; it does not claim external cleanup or erase history. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)", "version": "int64 (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine"}}, Errors: []module.ErrorDesc{{Status: 401, Code: "unauthenticated", Description: "Owner token required"}, {Status: 404, Code: "not_found", Description: "Unknown machine"}, {Status: 409, Code: "aborted", Description: "Version conflict"}}},
	{ID: "machines_get_trust", Path: machinesconnect.MachineServiceGetMachineTrustProcedure, Method: "POST", Summary: "Get Machine trust metadata", Description: "Returns public fingerprints and review state only. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"trust": "MachineTrust"}}},
	{ID: "machines_review_host_key", Path: machinesconnect.MachineServiceReviewMachineHostKeyProcedure, Method: "POST", Summary: "Approve a reviewed host key", Description: "Explicitly accepts a replacement SSH server host-key fingerprint after fail-closed detection. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)", "replacement_host_key_fingerprint": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"trust": "MachineTrust"}}},
	{ID: "machines_request_ssh_cleanup", Path: machinesconnect.MachineServiceRequestMachineSSHCleanupProcedure, Method: "POST", Summary: "Record SSH-access cleanup", Description: "Creates an explicit pending cleanup effect; it does not claim remote success. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"cleanup": "MachineCleanup"}}},
	{ID: "machines_update_cleanup", Path: machinesconnect.MachineServiceUpdateMachineCleanupProcedure, Method: "POST", Summary: "Update explicit cleanup result", Description: "Marks cleanup confirmed, not applicable, or acknowledged abandoned. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)", "status": "string (required)", "detail": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"cleanup": "MachineCleanup"}}},
	{ID: "machines_apply_policy", Path: machinesconnect.MachineServiceApplyMachinePolicyProcedure, Method: "POST", Summary: "Apply a versioned Machine policy", Description: "Resolves a built-in profile into immutable evidence and updates desired intent; suggested scopes never grant authorization. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)", "version": "int64 (required)", "profile_id": "string (required)", "profile_version": "string", "overrides": "map<string,string>", "reason": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine", "policy": "EffectivePolicy"}}},
	{ID: "machines_apply_configuration", Path: machinesconnect.MachineServiceApplyMachineConfigurationProcedure, Method: "POST", Summary: "Apply machine configuration", Description: "Applies the desired configuration document and records the result. Owner-gated.", Category: "configuration", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)", "version": "int64 (required)", "profile_id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine", "policy": "EffectivePolicy"}}},
	{ID: "machines_get_drift", Path: machinesconnect.MachineServiceGetMachineDriftProcedure, Method: "POST", Summary: "Get machine configuration drift", Description: "Returns typed differences between desired and applied machine configuration. Owner-gated.", Category: "configuration", Request: &module.Schema{Type: "object", Properties: map[string]string{"id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"drift": "array<MachineDrift>"}}},
	{ID: "machines_revoke_node", Path: machinesconnect.MachineServiceRevokeMachineNodeProcedure, Method: "POST", Summary: "Revoke a Machine's current Node", Description: "Locally revokes durable Node identity, credential, and live channel before any separate SSH cleanup. Owner-gated.", Category: "machines", Request: &module.Schema{Type: "object", Properties: map[string]string{"machine_id": "string (required)"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"machine": "Machine", "revoked_node_id": "string"}}},
}
