// Normal UI weather and camera actions; fixture hook reads renderer, clock and leases.
import{chromium}from'playwright-core';import{writeFileSync}from'node:fs';import{installFixtureHook}from'./camera-fixtures.mjs';
const root=new URL('../../evidence/living-world/',import.meta.url).pathname;const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=gl-egl']});const p=await b.newPage({viewport:{width:1400,height:900}});await installFixtureHook(p);const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/shader|WebGL|THREE/.test(m.text()))errors.push(m.text())});const check=(name,pass,detail)=>{checks.push({name,pass,detail});if(!pass)throw Error(name)};const cases=[];
try{for(const scene of ['park','office']){
await p.goto(`http://localhost:21235/world?scene=${scene}&actors=25&seed=1&diag=1&period=day&weather=clear&profile=high&workbench=1`);await p.waitForFunction(()=>window.__worldDiagnostics?.ready);await p.getByTitle('World Settings',{exact:true}).click();await p.getByText('World workbench',{exact:true}).click();await p.getByRole('button',{name:'Preview fish ripple',exact:true}).click();await p.getByRole('status').filter({hasText:'Preview ready:'}).waitFor();await p.waitForTimeout(1800);
await p.evaluate(()=>{const pending=[...window.__cameraFixtureRoots].map(r=>r.current);while(pending.length){const f=pending.pop();for(const v of[f.memoizedProps?.store,f.memoizedProps?.value])if(typeof v?.getState==='function'&&v.getState().scene?.isScene)window.__weatherRender=v;if(f.memoizedProps?.clock?.snapshot)window.__weatherClock=f.memoizedProps.clock;if(f.memoizedProps?.leases?.acquire)window.__weatherLeases=f.memoizedProps.leases;if(f.child)pending.push(f.child);if(f.sibling)pending.push(f.sibling)}});
const before=await p.evaluate(()=>({utc:window.__weatherClock.snapshot().utcMilliseconds,fish:window.__weatherRender.getState().scene.getObjectByName('ambient-fish').children.filter(r=>r.visible).map(r=>r.position.toArray())}));check(scene+' starts with frozen fish effect',before.fish.length>0);
for(const weather of ['Cloudy','Rain','Snow']){await p.getByRole('radio',{name:weather,exact:true}).click();await p.waitForFunction(()=>window.__worldDiagnostics.ambientCosts().families.every(r=>r.active===0));check(scene+' '+weather+' releases ambient leases',await p.evaluate(()=>window.__weatherLeases.count===0));await p.getByRole('radio',{name:'Clear',exact:true}).click();await p.waitForFunction(()=>window.__worldDiagnostics.ambientCosts().families.find(r=>r.family==='fish').active>0);const after=await p.evaluate(()=>({utc:window.__weatherClock.snapshot().utcMilliseconds,fish:window.__weatherRender.getState().scene.getObjectByName('ambient-fish').children.filter(r=>r.visible).map(r=>r.position.toArray())}));check(scene+' '+weather+' clear restores exact event site and time',JSON.stringify(after)===JSON.stringify(before),after)}
await p.getByRole('radio',{name:'Rain',exact:true}).click();if(!await p.getByRole('button',{name:'Preview great-fireball',exact:true}).isVisible())await p.getByText('World workbench',{exact:true}).click();await p.getByRole('button',{name:'Preview great-fireball',exact:true}).click();await p.waitForFunction(()=>window.__worldDiagnostics.ambientCosts().families.find(r=>r.family==='sky').active===1);await p.keyboard.press('Escape');
const initial=await p.evaluate(()=>window.__weatherRender.getState().camera.position.toArray());await p.mouse.move(850,420);await p.mouse.down({button:'left'});
const samples=[];for(let i=0;i<40;i++){await p.mouse.move(850+Math.sin(i*.25)*140,420+Math.sin(i*.18)*45,{steps:2});await p.waitForTimeout(200);samples.push(await p.evaluate(()=>{const d=window.__worldDiagnostics;return{costs:d.ambientCosts(),frameMsP95:d.frameMsP95,gpuMsP95:d.gpuMsP95,gpuSamples:d.gpuSamples,camera:window.__weatherRender.getState().camera.position.toArray(),weather:d.weather}}))}await p.mouse.up({button:'left'});
check(scene+' rain camera actually moves',samples.some(s=>s.camera.some((v,i)=>Math.abs(v-initial[i])>.1)));check(scene+' rain keeps ordinary wildlife suppressed',samples.every(s=>s.weather==='rain'&&s.costs.families.filter(f=>f.family!=='sky').every(f=>f.active===0)));check(scene+' explicit fireball remains visible in rain',samples.every(s=>s.costs.families.find(f=>f.family==='sky').active===1));await p.evaluate(()=>window.__worldDiagnostics.measure());const draws=await p.evaluate(()=>{const d=window.__worldDiagnostics;return{drawCalls:d.drawCalls,triangles:d.triangles,groups:d.groupCosts,gpu:d.gpu}});cases.push({scene,samples,draws});await p.screenshot({path:root+'rain-fireball-camera-'+scene+'-20260905.png'});
}check('no page or GPU errors',errors.length===0,errors)
}catch(e){checks.push({name:'completed',pass:false,detail:String(e)})}finally{writeFileSync(root+'ambient-weather-camera-browser-20260905.json',JSON.stringify({checks,errors,cases,scope:'Normal UI weather suppression/restoration at frozen event time, plus a frozen explicit fireball preview in Rain during normal pointer camera motion. Seed 1 High, 25 synthetic actors, integrated ANGLE. Does not exercise live event expiry, maximum sky capacity or physical-device qualification.'},null,2));console.log(checks);await b.close()}if(checks.some(c=>!c.pass))process.exitCode=1;
