// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    mainLabel: "layout.mainLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  delivery: {
    title: "delivery.title",
    description: "delivery.description",
    readiness: "delivery.readiness",
    targets: "delivery.targets",
    conformance: "delivery.conformance",
    chapters: "delivery.chapters",
    blockedAt: "delivery.blockedAt",
    nextAction: "delivery.nextAction",
    missingCapability: "delivery.missingCapability",
    loading: "delivery.loading",
    unavailable: "delivery.unavailable",
  },
  experience: {
    deliveryEvidence: "experience.deliveryEvidence",
    targetMatrix: "experience.targetMatrix",
    terminal: "experience.terminal",
    probed: "experience.probed",
    targetDisposition: "experience.targetDisposition",
    unsupported: "experience.unsupported",
    available: "experience.available",
    validateOnly: "experience.validateOnly",
    unavailable: "experience.unavailable",
    releaseGate: "experience.releaseGate",
    passedNonPromotable: "experience.passedNonPromotable",
    pending: "experience.pending",
    releaseReadiness: "experience.releaseReadiness",
    blockedOnMacOSBridge: "experience.blockedOnMacOSBridge",
    appleHardwareRequired: "experience.appleHardwareRequired",
    executingNode: "experience.executingNode",
    linuxHost: "experience.linuxHost",
    evidenceGrade: "experience.evidenceGrade",
    pixelGradeMirror: "experience.pixelGradeMirror",
    semantic: "experience.semantic",
    generateProject: "experience.generateProject",
    distribution: "experience.distribution",
    independentAppleChannelVerdicts: "experience.independentAppleChannelVerdicts",
    channels: "experience.channels",
    appStore: "experience.appStore",
    testFlight: "experience.testFlight",
    adHoc: "experience.adHoc",
    blockedNoMacNode: "experience.blockedNoMacNode",
    waitingOnApple: "experience.waitingOnApple",
    requiresReachableMacOSBridge: "experience.requiresReachableMacOSBridge",
    requiresAppleDeveloperEnrollment: "experience.requiresAppleDeveloperEnrollment",
    requiresChannelReview: "experience.requiresChannelReview",
    requiresEnrollmentAndSigning: "experience.requiresEnrollmentAndSigning",
    macOSBuildHost: "experience.macOSBuildHost",
    developerProgram: "experience.developerProgram",
    appleReview: "experience.appleReview",
    appStoreReview: "experience.appStoreReview",
    connectMacOSBridge: "experience.connectMacOSBridge",
    waitForAppleDecision: "experience.waitForAppleDecision",
    enrollDeveloperProgram: "experience.enrollDeveloperProgram",
    manageTestFlightTesters: "experience.manageTestFlightTesters",
    submitAppStoreReview: "experience.submitAppStoreReview",
    artifactPending: "experience.artifactPending",
    evidenceCannotGateRelease: "experience.evidenceCannotGateRelease",
    releaseReadinessHeading: "experience.releaseReadinessHeading",
    orderedAppleLadder: "experience.orderedAppleLadder",
    appleID: "experience.appleID",
    owner: "experience.owner",
    ownerAndApple: "experience.ownerAndApple",
    annualProgram: "experience.annualProgram",
    noAdditionalCost: "experience.noAdditionalCost",
    hostLease: "experience.hostLease",
    semanticMirror: "experience.semanticMirror",
    signInAppleID: "experience.signInAppleID",
    completePrecedingRung: "experience.completePrecedingRung",
    runReview: "experience.runReview",
    expectedObservedEvidence: "experience.expectedObservedEvidence",
    incomplete: "experience.incomplete",
    partial: "experience.partial",
    passed: "experience.passed",
    applicationLaunches: "experience.applicationLaunches",
    wkwebviewUnavailable: "experience.wkwebviewUnavailable",
    semanticObservation: "experience.semanticObservation",
    strategyMirrorSemantic: "experience.strategyMirrorSemantic",
    settleBound: "experience.settleBound",
    recordingUnavailable: "experience.recordingUnavailable",
    cannotGateRelease: "experience.cannotGateRelease",
    leaseLostInfrastructure: "experience.leaseLostInfrastructure",
    targetDetail: "experience.targetDetail",
    probedCapabilitySnapshot: "experience.probedCapabilitySnapshot",
    disposition: "experience.disposition",
    capabilities: "experience.capabilities",
    probedAt: "experience.probedAt",
    missingCapability: "experience.missingCapability",
    localLinuxHost: "experience.localLinuxHost",
    macOSBridge: "experience.macOSBridge",
    strategyUnsupported: "experience.strategyUnsupported",
    leaseHolderNone: "experience.leaseHolderNone",
    leaseHolderOtherConsumer: "experience.leaseHolderOtherConsumer",
    deviceIdentity: "experience.deviceIdentity",
    loggedInGuiSession: "experience.loggedInGuiSession",
    x86SimulatorRuntime: "experience.x86SimulatorRuntime",
    appleToolchain: "experience.appleToolchain",
    macOSBridgeNode: "experience.macOSBridgeNode",
    registerInspectBridge: "experience.registerInspectBridge",
    logIntoGuiSession: "experience.logIntoGuiSession",
    installSimulatorRuntime: "experience.installSimulatorRuntime",
    appStoreConnect: "experience.appStoreConnect",
    blockedOnAppleID: "experience.blockedOnAppleID",
  },
  settingsDetails: {
    signingIdentity: "settingsDetails.signingIdentity",
    unresolvedSecretReference: "settingsDetails.unresolvedSecretReference",
    defaultSigningIdentity: "settingsDetails.defaultSigningIdentity",
    defaultTransport: "settingsDetails.defaultTransport",
    localeControl: "settingsDetails.localeControl",
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
