// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  delivery: {
    blockedAt: "delivery.blockedAt",
    chapters: "delivery.chapters",
    conformance: "delivery.conformance",
    description: "delivery.description",
    loading: "delivery.loading",
    missingCapability: "delivery.missingCapability",
    nextAction: "delivery.nextAction",
    readiness: "delivery.readiness",
    targets: "delivery.targets",
    title: "delivery.title",
    unavailable: "delivery.unavailable",
  },
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  experience: {
    adHoc: "experience.adHoc",
    annualProgram: "experience.annualProgram",
    appStore: "experience.appStore",
    appStoreConnect: "experience.appStoreConnect",
    appStoreReview: "experience.appStoreReview",
    appleHardwareRequired: "experience.appleHardwareRequired",
    appleID: "experience.appleID",
    appleReview: "experience.appleReview",
    appleToolchain: "experience.appleToolchain",
    applicationLaunches: "experience.applicationLaunches",
    artifactPending: "experience.artifactPending",
    available: "experience.available",
    blockedNoMacNode: "experience.blockedNoMacNode",
    blockedOnAppleID: "experience.blockedOnAppleID",
    blockedOnMacOSBridge: "experience.blockedOnMacOSBridge",
    cannotGateRelease: "experience.cannotGateRelease",
    capabilities: "experience.capabilities",
    channels: "experience.channels",
    completePrecedingRung: "experience.completePrecedingRung",
    connectMacOSBridge: "experience.connectMacOSBridge",
    deliveryEvidence: "experience.deliveryEvidence",
    developerProgram: "experience.developerProgram",
    deviceIdentity: "experience.deviceIdentity",
    disposition: "experience.disposition",
    distribution: "experience.distribution",
    enrollDeveloperProgram: "experience.enrollDeveloperProgram",
    evidenceCannotGateRelease: "experience.evidenceCannotGateRelease",
    evidenceGrade: "experience.evidenceGrade",
    executingNode: "experience.executingNode",
    expectedObservedEvidence: "experience.expectedObservedEvidence",
    generateProject: "experience.generateProject",
    hostLease: "experience.hostLease",
    incomplete: "experience.incomplete",
    independentAppleChannelVerdicts: "experience.independentAppleChannelVerdicts",
    installSimulatorRuntime: "experience.installSimulatorRuntime",
    leaseHolderNone: "experience.leaseHolderNone",
    leaseHolderOtherConsumer: "experience.leaseHolderOtherConsumer",
    leaseLostInfrastructure: "experience.leaseLostInfrastructure",
    linuxHost: "experience.linuxHost",
    localLinuxHost: "experience.localLinuxHost",
    logIntoGuiSession: "experience.logIntoGuiSession",
    loggedInGuiSession: "experience.loggedInGuiSession",
    macOSBridge: "experience.macOSBridge",
    macOSBridgeNode: "experience.macOSBridgeNode",
    macOSBuildHost: "experience.macOSBuildHost",
    manageTestFlightTesters: "experience.manageTestFlightTesters",
    missingCapability: "experience.missingCapability",
    noAdditionalCost: "experience.noAdditionalCost",
    orderedAppleLadder: "experience.orderedAppleLadder",
    owner: "experience.owner",
    ownerAndApple: "experience.ownerAndApple",
    partial: "experience.partial",
    passed: "experience.passed",
    passedNonPromotable: "experience.passedNonPromotable",
    pending: "experience.pending",
    pixelGradeMirror: "experience.pixelGradeMirror",
    probed: "experience.probed",
    probedAt: "experience.probedAt",
    probedCapabilitySnapshot: "experience.probedCapabilitySnapshot",
    recordingUnavailable: "experience.recordingUnavailable",
    registerInspectBridge: "experience.registerInspectBridge",
    releaseGate: "experience.releaseGate",
    releaseReadiness: "experience.releaseReadiness",
    releaseReadinessHeading: "experience.releaseReadinessHeading",
    requiresAppleDeveloperEnrollment: "experience.requiresAppleDeveloperEnrollment",
    requiresChannelReview: "experience.requiresChannelReview",
    requiresEnrollmentAndSigning: "experience.requiresEnrollmentAndSigning",
    requiresReachableMacOSBridge: "experience.requiresReachableMacOSBridge",
    runReview: "experience.runReview",
    semantic: "experience.semantic",
    semanticMirror: "experience.semanticMirror",
    semanticObservation: "experience.semanticObservation",
    settleBound: "experience.settleBound",
    signInAppleID: "experience.signInAppleID",
    strategyMirrorSemantic: "experience.strategyMirrorSemantic",
    strategyUnsupported: "experience.strategyUnsupported",
    submitAppStoreReview: "experience.submitAppStoreReview",
    targetDetail: "experience.targetDetail",
    targetDisposition: "experience.targetDisposition",
    targetMatrix: "experience.targetMatrix",
    terminal: "experience.terminal",
    testFlight: "experience.testFlight",
    unavailable: "experience.unavailable",
    unsupported: "experience.unsupported",
    validateOnly: "experience.validateOnly",
    waitForAppleDecision: "experience.waitForAppleDecision",
    waitingOnApple: "experience.waitingOnApple",
    wkwebviewUnavailable: "experience.wkwebviewUnavailable",
    x86SimulatorRuntime: "experience.x86SimulatorRuntime",
  },
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    statusLabel: "health.statusLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      settings: "layout.nav.settings",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  navigation: {
    "app-shell": {
      "close-navigation": "navigation.app-shell.close-navigation",
      "mobile-navigation": "navigation.app-shell.mobile-navigation",
      "open-navigation": "navigation.app-shell.open-navigation",
      "primary-navigation": "navigation.app-shell.primary-navigation",
      "skip-to-content": "navigation.app-shell.skip-to-content",
    },
  },
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  pages: {
    dashboard: {
      description: "pages.dashboard.description",
      title: "pages.dashboard.title",
    },
    settings: {
      localeHeading: "pages.settings.localeHeading",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
  },
  settingsDetails: {
    defaultSigningIdentity: "settingsDetails.defaultSigningIdentity",
    defaultTransport: "settingsDetails.defaultTransport",
    localeControl: "settingsDetails.localeControl",
    signingIdentity: "settingsDetails.signingIdentity",
    unresolvedSecretReference: "settingsDetails.unresolvedSecretReference",
  },
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
} as const;

export type Strings = typeof strings;
