# Workflow trigger configuration for Intelligent Desktop Assistant
# This file defines how and when workflows should be activated

triggers:
  # Main application workflow
  main_workflow:
    platform: n8n
    workflow_id: "intelligent-desktop-assistant-main"
    workflow_file: "n8n/main-workflow.json"
    activation:
      auto_activate: true
      activation_delay_seconds: 5
    endpoints:
      webhook: "/webhook/intelligent-desktop-assistant-webhook"
      status: "/api/v1/workflows/intelligent-desktop-assistant-main"
    
  # Health check workflow
  health_check:
    platform: n8n
    workflow_id: "intelligent-desktop-assistant-health"
    activation:
      auto_activate: true
      activation_delay_seconds: 10
    schedule:
      enabled: true
      interval: "*/5 * * * *"  # Every 5 minutes
      timezone: "UTC"
    
  {% if "windmill" in resources.required %}
  # Windmill app deployment
  windmill_app:
    platform: windmill
    app_id: "intelligent-desktop-assistant-app"
    app_file: "ui/windmill-app.json"
    activation:
      auto_activate: {{ testing.requires_ui }}
      activation_delay_seconds: 15
    endpoints:
      app: "/app/intelligent-desktop-assistant"
      admin: "/admin/intelligent-desktop-assistant"
  {% endif %}
  
  {% if "node-red" in resources.required %}
  # Node-RED flows
  node_red_monitoring:
    platform: node-red
    flow_id: "intelligent-desktop-assistant-monitor"
    activation:
      auto_activate: true
      activation_delay_seconds: 8
    endpoints:
      dashboard: "/ui/intelligent-desktop-assistant"
      api: "/intelligent-desktop-assistant/api"
  {% endif %}

# Activation sequence - order matters for dependencies
activation_sequence:
  - name: validate_resources
    description: "Check all required resources are healthy"
    timeout_seconds: 30
    required_resources: {{ resources.required | tojson }}
    
  - name: setup_database_connections
    description: "Initialize database connections and validate schemas"
    condition: "postgres in required_resources"
    timeout_seconds: 15
    
  - name: activate_n8n_workflows
    description: "Import and activate n8n workflows"
    condition: "n8n in required_resources"
    timeout_seconds: 30
    workflows:
      - id: "intelligent-desktop-assistant-main"
        file: "n8n/main-workflow.json"
        auto_activate: true
    
  - name: deploy_windmill_apps
    description: "Deploy Windmill UI applications"
    condition: "windmill in required_resources and requires_ui"
    timeout_seconds: 45
    apps:
      - id: "intelligent-desktop-assistant-app"
        file: "ui/windmill-app.json"
        
  - name: setup_node_red_flows
    description: "Deploy Node-RED monitoring flows"
    condition: "node-red in required_resources"
    timeout_seconds: 20
    
  - name: configure_monitoring
    description: "Setup health monitoring and alerts"
    timeout_seconds: 10
    
  - name: validate_endpoints
    description: "Test all application endpoints"
    timeout_seconds: 60
    endpoints:
      - url: "/webhook/intelligent-desktop-assistant-webhook"
        method: "POST"
        expected_status: 200
      {% if "windmill" in resources.required and testing.requires_ui %}
      - url: "/app/intelligent-desktop-assistant"
        method: "GET"
        expected_status: 200
      {% endif %}

# Health monitoring configuration
monitoring:
  health_checks:
    - name: main_workflow_health
      platform: n8n
      workflow_id: "intelligent-desktop-assistant-main"
      check_interval_seconds: 300
      
    - name: database_health
      condition: "postgres in required_resources"
      type: database
      connection_string: "postgresql://postgres:postgres@localhost:5433/{{ scenario.id | replace('-', '_') }}"
      check_interval_seconds: 60
      
    - name: webhook_endpoint_health
      type: http
      url: "http://localhost:5678/webhook/intelligent-desktop-assistant-webhook"
      method: "GET"
      expected_status: 405  # Method not allowed for GET is expected
      check_interval_seconds: 120
      
    {% if "windmill" in resources.required and testing.requires_ui %}
    - name: ui_application_health
      type: http
      url: "http://localhost:5681/app/intelligent-desktop-assistant"
      method: "GET"
      expected_status: 200
      check_interval_seconds: 180
    {% endif %}

# Error handling and recovery
error_handling:
  retry_policy:
    max_attempts: 3
    retry_delay_seconds: 5
    backoff_multiplier: 2
    
  recovery_actions:
    workflow_failure:
      - action: restart_workflow
        delay_seconds: 10
      - action: notify_admin
        channels: ["log", "webhook"]
        
    resource_unavailable:
      - action: wait_for_resource
        timeout_seconds: 60
      - action: fallback_mode
        enabled: false
        
    activation_timeout:
      - action: retry_activation
        max_attempts: 2
      - action: partial_activation
        enabled: true

# Post-activation validation
validation:
  tests:
    - name: webhook_functionality
      type: integration
      description: "Test main webhook endpoint with sample data"
      request:
        url: "/webhook/intelligent-desktop-assistant-webhook"
        method: "POST"
        body: |
          {
            "test": true,
            "scenario": "intelligent-desktop-assistant",
            "timestamp": "{{ '${timestamp}' }}"
          }
      expected_response:
        status: 200
        contains: ["success", "intelligent-desktop-assistant"]
        
    - name: workflow_execution
      type: functional
      description: "Verify workflow processes requests correctly"
      timeout_seconds: {{ testing.timeout_seconds | default(60) }}
      
    {% if "postgres" in resources.required %}
    - name: database_logging
      type: integration
      description: "Verify activity logging to database"
      query: "SELECT COUNT(*) FROM {{ scenario.id | replace('-', '_') }}.activity_log WHERE timestamp > NOW() - INTERVAL '1 minute'"
      expected_result: "> 0"
    {% endif %}
    
    {% if testing.requires_ui %}
    - name: ui_accessibility
      type: functional
      description: "Verify UI application is accessible"
      url: "/app/intelligent-desktop-assistant"
      checks: ["page_loads", "no_js_errors", "responsive_design"]
    {% endif %}

# Performance expectations
performance:
  benchmarks:
    response_time:
      webhook_response_ms: {{ performance.latency.p95 | default("500") | replace("ms", "") | int }}
      workflow_execution_ms: {{ testing.timeout_seconds | default(60) | int * 1000 }}
      
    throughput:
      requests_per_minute: {{ performance.throughput.requests_per_second | default(1) | int * 60 }}
      concurrent_workflows: 3
      
    resource_usage:
      memory_limit_mb: 512
      cpu_limit_percent: 50