// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    brand: "app.brand",
  },
  nav: {
    label: "nav.label",
    openDrawer: "nav.openDrawer",
    closeDrawer: "nav.closeDrawer",
    drawerLabel: "nav.drawerLabel",
    settings: "nav.settings",
    browseAssets: "nav.browseAssets",
  },
  theme: {
    light: "theme.light",
    dark: "theme.dark",
    system: "theme.system",
  },
  route: {
    loading: "route.loading",
  },
  settings: {
    title: "settings.title",
    subtitle: "settings.subtitle",
    appearance: "settings.appearance",
    theme: "settings.theme",
    language: "settings.language",
  },
  notFound: {
    title: "notFound.title",
    description: "notFound.description",
    home: "notFound.home",
  },
  componentDetail: {
    missingId: "componentDetail.missingId",
    loading: "componentDetail.loading",
    notFound: "componentDetail.notFound",
    experience: {
      title: "componentDetail.experience.title",
      loading: "componentDetail.experience.loading",
      loadError: "componentDetail.experience.loadError",
      notConfigured: "componentDetail.experience.notConfigured",
      unavailable: "componentDetail.experience.unavailable",
      records: "componentDetail.experience.records",
      states: "componentDetail.experience.states",
      claims: "componentDetail.experience.claims",
      unproven: "componentDetail.experience.unproven",
      allStates: "componentDetail.experience.allStates",
      openCapture: "componentDetail.experience.openCapture",
      captureTimeUnavailable: "componentDetail.experience.captureTimeUnavailable",
      statesPrefix: "componentDetail.experience.statesPrefix",
      identity: "componentDetail.experience.identity",
      versionUnavailable: "componentDetail.experience.versionUnavailable",
      stale: "componentDetail.experience.stale",
    },
    progression: {
      tab: "componentDetail.progression.tab",
      title: "componentDetail.progression.title",
      description: "componentDetail.progression.description",
      loading: "componentDetail.progression.loading",
      error: "componentDetail.progression.error",
    },
  },
  catalog: {
    title: "catalog.title",
    subtitle: "catalog.subtitle",
    components: "catalog.components",
    hooks: "catalog.hooks",
    hook: "catalog.hook",
    search: "catalog.search",
    searchPlaceholder: "catalog.searchPlaceholder",
    adoptions: "catalog.adoptions",
    versionsCount: "catalog.versionsCount",
    noPreview: "catalog.noPreview",
    source: "catalog.source",
    sourceError: "catalog.sourceError",
    addManual: "catalog.addManual",
    addAssisted: "catalog.addAssisted",
    assistedDescription: "catalog.assistedDescription",
    sourceScenario: "catalog.sourceScenario",
    sourcePath: "catalog.sourcePath",
    sourcePathPlaceholder: "catalog.sourcePathPlaceholder",
    assistedError: "catalog.assistedError",
    assistedStarting: "catalog.assistedStarting",
    assistedStart: "catalog.assistedStart",
  },
  workflows: {
    active: "workflows.active",
    none: "workflows.none",
    stop: "workflows.stop",
    retry: "workflows.retry",
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  components: {
    title: "components.title",
    loading: "components.loading",
    empty: "components.empty",
    indexAction: "components.indexAction",
    searchLabel: "components.searchLabel",
    searchPlaceholder: "components.searchPlaceholder",
    tagLabel: "components.tagLabel",
    tagPlaceholder: "components.tagPlaceholder",
    tagsFilterLabel: "components.tagsFilterLabel",
    tagsFilterPlaceholder: "components.tagsFilterPlaceholder",
    categoryLabel: "components.categoryLabel",
    categoryPlaceholder: "components.categoryPlaceholder",
    styleLabel: "components.styleLabel",
    stylePlaceholder: "components.stylePlaceholder",
    affinityLabel: "components.affinityLabel",
    affinityPlaceholder: "components.affinityPlaceholder",
    summary: "components.summary",
    summary_one: "components.summary_one",
    versionLabel: "components.versionLabel",
    slotLabel: "components.slotLabel",
    designStylesLabel: "components.designStylesLabel",
    tagsLabel: "components.tagsLabel",
    noTags: "components.noTags",
    openAction: "components.openAction",
    create: {
      action: "components.create.action",
      title: "components.create.title",
      slug: "components.create.slug",
      libraryId: "components.create.libraryId",
      libraryIdPlaceholder: "components.create.libraryIdPlaceholder",
      displayName: "components.create.displayName",
      description: "components.create.description",
      tags: "components.create.tags",
      tagsPlaceholder: "components.create.tagsPlaceholder",
      version: "components.create.version",
      fileName: "components.create.fileName",
      fileNamePlaceholder: "components.create.fileNamePlaceholder",
      initialSource: "components.create.initialSource",
      initialSourcePlaceholder: "components.create.initialSourcePlaceholder",
      submit: "components.create.submit",
      creating: "components.create.creating",
      cancel: "components.create.cancel",
    },
    ingest: {
      title: "components.ingest.title",
      description: "components.ingest.description",
      scenario: "components.ingest.scenario",
      sourceFile: "components.ingest.sourceFile",
      slug: "components.ingest.slug",
      tags: "components.ingest.tags",
      submit: "components.ingest.submit",
      running: "components.ingest.running",
      success: "components.ingest.success",
      acceptBehaviorLoss: "components.ingest.acceptBehaviorLoss",
      acceptedNotice: "components.ingest.acceptedNotice",
    },
    editor: {
      title: "components.editor.title",
      loading: "components.editor.loading",
      save: "components.editor.save",
      saving: "components.editor.saving",
      close: "components.editor.close",
      info: "components.editor.info",
      noInfo: "components.editor.noInfo",
      dirty: "components.editor.dirty",
      sha: "components.editor.sha",
      subtitle: "components.editor.subtitle",
      saved: "components.editor.saved",
      previewMode: "components.editor.previewMode",
      codeMode: "components.editor.codeMode",
      files: "components.editor.files",
      reorderPane: "components.editor.reorderPane",
      paneDragInstructions: "components.editor.paneDragInstructions",
      paneDragStarted: "components.editor.paneDragStarted",
      paneDragOver: "components.editor.paneDragOver",
      paneDragEnded: "components.editor.paneDragEnded",
      paneDragCancelled: "components.editor.paneDragCancelled",
      paneDragCancelledWithPane: "components.editor.paneDragCancelledWithPane",
      previewHeading: "components.editor.previewHeading",
      previewReady: "components.editor.previewReady",
      previewFailed: "components.editor.previewFailed",
      previewTimeout: "components.editor.previewTimeout",
      previewRetry: "components.editor.previewRetry",
      comparing: "components.editor.comparing",
      showAllStories: "components.editor.showAllStories",
      storyStatus: "components.editor.storyStatus",
      focusStory: "components.editor.focusStory",
      compareStory: "components.editor.compareStory",
      storiesLabel: "components.editor.storiesLabel",
      events: "components.editor.events",
      noEvents: "components.editor.noEvents",
      clearEvents: "components.editor.clearEvents",
      tryProps: "components.editor.tryProps",
      tryPropsDescription: "components.editor.tryPropsDescription",
      indexedPropsLabel: "components.editor.indexedPropsLabel",
      propsApplied: "components.editor.propsApplied",
      applyTemporaryProps: "components.editor.applyTemporaryProps",
      applyingProps: "components.editor.applyingProps",
      resetIndexedProps: "components.editor.resetIndexedProps",
      propsObjectError: "components.editor.propsObjectError",
      propsJsonError: "components.editor.propsJsonError",
      propsRejected: "components.editor.propsRejected",
      viewingVersion: "components.editor.viewingVersion",
      libraryIdLabel: "components.editor.libraryIdLabel",
      slotLabel: "components.editor.slotLabel",
      categoryLabel: "components.editor.categoryLabel",
      tagsLabel: "components.editor.tagsLabel",
    },
    themeSwitcher: {
      appearanceLabel: "components.themeSwitcher.appearanceLabel",
      appearanceDescription: "components.themeSwitcher.appearanceDescription",
      modeLabel: "components.themeSwitcher.modeLabel",
      modeDescription: "components.themeSwitcher.modeDescription",
      mode: {
        system: "components.themeSwitcher.mode.system",
        light: "components.themeSwitcher.mode.light",
        dark: "components.themeSwitcher.mode.dark",
      },
      kitLabel: "components.themeSwitcher.kitLabel",
      kitDescription: "components.themeSwitcher.kitDescription",
      kitOptions: {
        default: "components.themeSwitcher.kitOptions.default",
        commandDisplay: "components.themeSwitcher.kitOptions.commandDisplay",
        conversionLanding: "components.themeSwitcher.kitOptions.conversionLanding",
      },
      visualLabel: "components.themeSwitcher.visualLabel",
      visualDescription: "components.themeSwitcher.visualDescription",
      loading: "components.themeSwitcher.loading",
      applied: "components.themeSwitcher.applied",
    },
    emulator: {
      viewportLabel: "components.emulator.viewportLabel",
      viewportDescription: "components.emulator.viewportDescription",
      summary: "components.emulator.summary",
      responsiveLabel: "components.emulator.responsiveLabel",
      responsiveDescription: "components.emulator.responsiveDescription",
      deviceGroups: {
        phone: "components.emulator.deviceGroups.phone",
        tablet: "components.emulator.deviceGroups.tablet",
        desktop: "components.emulator.deviceGroups.desktop",
      },
      toolbarLabel: "components.emulator.toolbarLabel",
      widthLabel: "components.emulator.widthLabel",
      heightLabel: "components.emulator.heightLabel",
      zoomLabel: "components.emulator.zoomLabel",
      zoomValue: "components.emulator.zoomValue",
      rotate: "components.emulator.rotate",
      reset: "components.emulator.reset",
      fit: "components.emulator.fit",
      visionFilterLabel: "components.emulator.visionFilterLabel",
      visionFilter: {
        normal: "components.emulator.visionFilter.normal",
        grayscale: "components.emulator.visionFilter.grayscale",
        protanopia: "components.emulator.visionFilter.protanopia",
        deuteranopia: "components.emulator.visionFilter.deuteranopia",
        tritanopia: "components.emulator.visionFilter.tritanopia",
      },
      blurLabel: "components.emulator.blurLabel",
      blurValue: "components.emulator.blurValue",
    },
    inspector: {
      title: "components.inspector.title",
      toggleStart: "components.inspector.toggleStart",
      toggleStop: "components.inspector.toggleStop",
      statusIdle: "components.inspector.statusIdle",
      statusActive: "components.inspector.statusActive",
      statusReady: "components.inspector.statusReady",
      empty: "components.inspector.empty",
      rectLabel: "components.inspector.rectLabel",
      breadcrumbLabel: "components.inspector.breadcrumbLabel",
    },
  },
  adoptions: {
    title: "adoptions.title",
    loading: "adoptions.loading",
    empty: "adoptions.empty",
    refreshAction: "adoptions.refreshAction",
    refreshing: "adoptions.refreshing",
    scenarioFilterLabel: "adoptions.scenarioFilterLabel",
    scenarioFilterPlaceholder: "adoptions.scenarioFilterPlaceholder",
    summary: "adoptions.summary",
    versionLabel: "adoptions.versionLabel",
    neverRefreshed: "adoptions.neverRefreshed",
    refreshedAt: "adoptions.refreshedAt",
    deleteAction: "adoptions.deleteAction",
    deleting: "adoptions.deleting",
    createAction: "adoptions.createAction",
    creating: "adoptions.creating",
    create: {
      title: "adoptions.create.title",
      subtitle: "adoptions.create.subtitle",
      componentIdLabel: "adoptions.create.componentIdLabel",
      componentIdPlaceholder: "adoptions.create.componentIdPlaceholder",
      scenarioLabel: "adoptions.create.scenarioLabel",
      scenarioPlaceholder: "adoptions.create.scenarioPlaceholder",
      adoptedPathLabel: "adoptions.create.adoptedPathLabel",
      adoptedPathPlaceholder: "adoptions.create.adoptedPathPlaceholder",
      adoptedVersionLabel: "adoptions.create.adoptedVersionLabel",
      adoptedVersionPlaceholder: "adoptions.create.adoptedVersionPlaceholder",
      replaceExistingLabel: "adoptions.create.replaceExistingLabel",
      replaceExistingHelp: "adoptions.create.replaceExistingHelp",
      confirmAction: "adoptions.create.confirmAction",
      confirmOverwriteAction: "adoptions.create.confirmOverwriteAction",
      cancelAction: "adoptions.create.cancelAction",
      overwriteRequired: "adoptions.create.overwriteRequired",
      validating: "adoptions.create.validating",
      styleValidating: "adoptions.create.styleValidating",
      verdictOk: "adoptions.create.verdictOk",
      verdictWarn: "adoptions.create.verdictWarn",
      verdictBlock: "adoptions.create.verdictBlock",
      styleVerdict: "adoptions.create.styleVerdict",
      styleUnknown: "adoptions.create.styleUnknown",
      ackLabel: "adoptions.create.ackLabel",
      issueMissingDep: "adoptions.create.issueMissingDep",
      issueRangeDoesNotMatch: "adoptions.create.issueRangeDoesNotMatch",
      issueIncompatibleMajor: "adoptions.create.issueIncompatibleMajor",
      issueUnparseableRange: "adoptions.create.issueUnparseableRange",
      issueUnparseableTarget: "adoptions.create.issueUnparseableTarget",
      issueUnknown: "adoptions.create.issueUnknown",
      pathSourceExplicit: "adoptions.create.pathSourceExplicit",
      pathSourceTemplateManifest: "adoptions.create.pathSourceTemplateManifest",
      pathSourceHeuristic: "adoptions.create.pathSourceHeuristic",
      pathSourceFallback: "adoptions.create.pathSourceFallback",
      pathResolving: "adoptions.create.pathResolving",
    },
    suggestions: {
      title: "adoptions.suggestions.title",
      subtitle: "adoptions.suggestions.subtitle",
      adoptAction: "adoptions.suggestions.adoptAction",
      empty: "adoptions.suggestions.empty",
    },
    status: {
      current: "adoptions.status.current",
      behind: "adoptions.status.behind",
      modified: "adoptions.status.modified",
      missing: "adoptions.status.missing",
      clean: "adoptions.status.clean",
      unknown: "adoptions.status.unknown",
      unspecified: "adoptions.status.unspecified",
    },
  },
  versions: {
    title: "versions.title",
    loading: "versions.loading",
    empty: "versions.empty",
    summary: "versions.summary",
    currentSource: "versions.currentSource",
    viewVersion: "versions.viewVersion",
    viewingVersion: "versions.viewingVersion",
    recordedAt: "versions.recordedAt",
    createdAt: "versions.createdAt",
    shaLabel: "versions.shaLabel",
    versionLabel: "versions.versionLabel",
    diff: {
      title: "versions.diff.title",
      fromLabel: "versions.diff.fromLabel",
      toLabel: "versions.diff.toLabel",
      runAction: "versions.diff.runAction",
      running: "versions.diff.running",
      empty: "versions.diff.empty",
      summary: "versions.diff.summary",
      viewerLabel: "versions.diff.viewerLabel",
      modeLabel: "versions.diff.modeLabel",
      split: "versions.diff.split",
      unified: "versions.diff.unified",
      copy: "versions.diff.copy",
      copied: "versions.diff.copied",
    },
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
