// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $schema: "$schema",
  $text: "$text",
  "Access limited": "Access limited",
  "Content failed to load": {
    "": "Content failed to load.",
  },
  "Disabled states retain the same geometry and clearly communicate that the action is unavailable": {
    "": "Disabled states retain the same geometry and clearly communicate that the action is unavailable.",
  },
  Name: "Name",
  "Reconnect to refresh this view": {
    "": "Reconnect to refresh this view.",
  },
  State: "State",
  "Try again": "Try again",
  "Trying again…": "Trying again…",
  activityState: "activityState",
  activitySurfaceId: "activitySurfaceId",
  adapter: "adapter",
  adoptions: {
    create: {
      ackLabel: "adoptions.create.ackLabel",
      adoptedPathLabel: "adoptions.create.adoptedPathLabel",
      adoptedPathPlaceholder: "adoptions.create.adoptedPathPlaceholder",
      adoptedVersionLabel: "adoptions.create.adoptedVersionLabel",
      adoptedVersionPlaceholder: "adoptions.create.adoptedVersionPlaceholder",
      cancelAction: "adoptions.create.cancelAction",
      componentIdLabel: "adoptions.create.componentIdLabel",
      componentIdPlaceholder: "adoptions.create.componentIdPlaceholder",
      confirmAction: "adoptions.create.confirmAction",
      confirmOverwriteAction: "adoptions.create.confirmOverwriteAction",
      issueIncompatibleMajor: "adoptions.create.issueIncompatibleMajor",
      issueMissingDep: "adoptions.create.issueMissingDep",
      issueRangeDoesNotMatch: "adoptions.create.issueRangeDoesNotMatch",
      issueUnknown: "adoptions.create.issueUnknown",
      issueUnparseableRange: "adoptions.create.issueUnparseableRange",
      issueUnparseableTarget: "adoptions.create.issueUnparseableTarget",
      overwriteRequired: "adoptions.create.overwriteRequired",
      pathResolving: "adoptions.create.pathResolving",
      pathSourceExplicit: "adoptions.create.pathSourceExplicit",
      pathSourceFallback: "adoptions.create.pathSourceFallback",
      pathSourceHeuristic: "adoptions.create.pathSourceHeuristic",
      pathSourceTemplateManifest: "adoptions.create.pathSourceTemplateManifest",
      replaceExistingHelp: "adoptions.create.replaceExistingHelp",
      replaceExistingLabel: "adoptions.create.replaceExistingLabel",
      scenarioLabel: "adoptions.create.scenarioLabel",
      scenarioPlaceholder: "adoptions.create.scenarioPlaceholder",
      styleUnknown: "adoptions.create.styleUnknown",
      styleValidating: "adoptions.create.styleValidating",
      styleVerdict: "adoptions.create.styleVerdict",
      subtitle: "adoptions.create.subtitle",
      title: "adoptions.create.title",
      validating: "adoptions.create.validating",
      verdictBlock: "adoptions.create.verdictBlock",
      verdictOk: "adoptions.create.verdictOk",
      verdictWarn: "adoptions.create.verdictWarn",
    },
    createAction: "adoptions.createAction",
    creating: "adoptions.creating",
    deleteAction: "adoptions.deleteAction",
    deleting: "adoptions.deleting",
    empty: "adoptions.empty",
    loading: "adoptions.loading",
    neverRefreshed: "adoptions.neverRefreshed",
    refreshAction: "adoptions.refreshAction",
    refreshedAt: "adoptions.refreshedAt",
    refreshing: "adoptions.refreshing",
    scenarioFilterLabel: "adoptions.scenarioFilterLabel",
    scenarioFilterPlaceholder: "adoptions.scenarioFilterPlaceholder",
    status: {
      behind: "adoptions.status.behind",
      clean: "adoptions.status.clean",
      current: "adoptions.status.current",
      missing: "adoptions.status.missing",
      modified: "adoptions.status.modified",
      unknown: "adoptions.status.unknown",
      unspecified: "adoptions.status.unspecified",
    },
    suggestions: {
      adoptAction: "adoptions.suggestions.adoptAction",
      empty: "adoptions.suggestions.empty",
      subtitle: "adoptions.suggestions.subtitle",
      title: "adoptions.suggestions.title",
    },
    summary: "adoptions.summary",
    title: "adoptions.title",
    versionLabel: "adoptions.versionLabel",
  },
  alert: "alert",
  app: {
    brand: "app.brand",
    title: "app.title",
  },
  "aria-label": "aria-label",
  assertive: "assertive",
  asset: "asset",
  axis: "axis",
  background: "background",
  "bg-app-primary/60": "bg-app-primary/60",
  "border-app-info bg-app-info/20 text-app-info": "border-app-info bg-app-info/20 text-app-info",
  "border-app-warning bg-app-warning/10 text-app-warning": "border-app-warning bg-app-warning/10 text-app-warning",
  capability: "capability",
  catalog: {
    addAssisted: "catalog.addAssisted",
    addManual: "catalog.addManual",
    adoptions: "catalog.adoptions",
    assistedDescription: "catalog.assistedDescription",
    assistedError: "catalog.assistedError",
    assistedStart: "catalog.assistedStart",
    assistedStarting: "catalog.assistedStarting",
    components: "catalog.components",
    hook: "catalog.hook",
    hooks: "catalog.hooks",
    noPreview: "catalog.noPreview",
    search: "catalog.search",
    searchPlaceholder: "catalog.searchPlaceholder",
    source: "catalog.source",
    sourceError: "catalog.sourceError",
    sourcePath: "catalog.sourcePath",
    sourcePathPlaceholder: "catalog.sourcePathPlaceholder",
    sourceScenario: "catalog.sourceScenario",
    subtitle: "catalog.subtitle",
    title: "catalog.title",
    versionsCount: "catalog.versionsCount",
  },
  closeLabel: "closeLabel",
  clsx: "clsx",
  componentDetail: {
    experience: {
      allStates: "componentDetail.experience.allStates",
      captureTimeUnavailable: "componentDetail.experience.captureTimeUnavailable",
      claims: "componentDetail.experience.claims",
      identity: "componentDetail.experience.identity",
      loadError: "componentDetail.experience.loadError",
      loading: "componentDetail.experience.loading",
      notConfigured: "componentDetail.experience.notConfigured",
      openCapture: "componentDetail.experience.openCapture",
      records: "componentDetail.experience.records",
      stale: "componentDetail.experience.stale",
      states: "componentDetail.experience.states",
      statesPrefix: "componentDetail.experience.statesPrefix",
      title: "componentDetail.experience.title",
      unavailable: "componentDetail.experience.unavailable",
      unproven: "componentDetail.experience.unproven",
      versionUnavailable: "componentDetail.experience.versionUnavailable",
    },
    loading: "componentDetail.loading",
    missingId: "componentDetail.missingId",
    notFound: "componentDetail.notFound",
    progression: {
      description: "componentDetail.progression.description",
      error: "componentDetail.progression.error",
      loading: "componentDetail.progression.loading",
      tab: "componentDetail.progression.tab",
      title: "componentDetail.progression.title",
    },
  },
  componentId: "componentId",
  components: {
    affinityLabel: "components.affinityLabel",
    affinityPlaceholder: "components.affinityPlaceholder",
    categoryLabel: "components.categoryLabel",
    categoryPlaceholder: "components.categoryPlaceholder",
    create: {
      action: "components.create.action",
      cancel: "components.create.cancel",
      creating: "components.create.creating",
      description: "components.create.description",
      displayName: "components.create.displayName",
      fileName: "components.create.fileName",
      fileNamePlaceholder: "components.create.fileNamePlaceholder",
      initialSource: "components.create.initialSource",
      initialSourcePlaceholder: "components.create.initialSourcePlaceholder",
      libraryId: "components.create.libraryId",
      libraryIdPlaceholder: "components.create.libraryIdPlaceholder",
      slug: "components.create.slug",
      submit: "components.create.submit",
      tags: "components.create.tags",
      tagsPlaceholder: "components.create.tagsPlaceholder",
      title: "components.create.title",
      version: "components.create.version",
    },
    designStylesLabel: "components.designStylesLabel",
    editor: {
      applyTemporaryProps: "components.editor.applyTemporaryProps",
      applyingProps: "components.editor.applyingProps",
      categoryLabel: "components.editor.categoryLabel",
      clearEvents: "components.editor.clearEvents",
      close: "components.editor.close",
      codeMode: "components.editor.codeMode",
      compareStory: "components.editor.compareStory",
      comparing: "components.editor.comparing",
      dirty: "components.editor.dirty",
      events: "components.editor.events",
      files: "components.editor.files",
      focusStory: "components.editor.focusStory",
      indexedPropsLabel: "components.editor.indexedPropsLabel",
      info: "components.editor.info",
      libraryIdLabel: "components.editor.libraryIdLabel",
      loading: "components.editor.loading",
      noEvents: "components.editor.noEvents",
      noInfo: "components.editor.noInfo",
      paneDragCancelled: "components.editor.paneDragCancelled",
      paneDragCancelledWithPane: "components.editor.paneDragCancelledWithPane",
      paneDragEnded: "components.editor.paneDragEnded",
      paneDragInstructions: "components.editor.paneDragInstructions",
      paneDragOver: "components.editor.paneDragOver",
      paneDragStarted: "components.editor.paneDragStarted",
      previewDiagnostics: "components.editor.previewDiagnostics",
      previewDiagnosticsCopied: "components.editor.previewDiagnosticsCopied",
      previewDiagnosticsCopy: "components.editor.previewDiagnosticsCopy",
      previewDiagnosticsDescription: "components.editor.previewDiagnosticsDescription",
      previewFailed: "components.editor.previewFailed",
      previewHeading: "components.editor.previewHeading",
      previewMode: "components.editor.previewMode",
      previewReady: "components.editor.previewReady",
      previewRetry: "components.editor.previewRetry",
      previewTimeout: "components.editor.previewTimeout",
      propsApplied: "components.editor.propsApplied",
      propsJsonError: "components.editor.propsJsonError",
      propsObjectError: "components.editor.propsObjectError",
      propsRejected: "components.editor.propsRejected",
      reorderPane: "components.editor.reorderPane",
      resetIndexedProps: "components.editor.resetIndexedProps",
      save: "components.editor.save",
      saved: "components.editor.saved",
      saving: "components.editor.saving",
      sha: "components.editor.sha",
      showAllStories: "components.editor.showAllStories",
      slotLabel: "components.editor.slotLabel",
      storiesLabel: "components.editor.storiesLabel",
      storyStatus: "components.editor.storyStatus",
      subtitle: "components.editor.subtitle",
      tagsLabel: "components.editor.tagsLabel",
      title: "components.editor.title",
      tryProps: "components.editor.tryProps",
      tryPropsDescription: "components.editor.tryPropsDescription",
      viewingVersion: "components.editor.viewingVersion",
    },
    empty: "components.empty",
    emulator: {
      blurLabel: "components.emulator.blurLabel",
      blurValue: "components.emulator.blurValue",
      deviceGroups: {
        desktop: "components.emulator.deviceGroups.desktop",
        phone: "components.emulator.deviceGroups.phone",
        tablet: "components.emulator.deviceGroups.tablet",
      },
      fit: "components.emulator.fit",
      heightLabel: "components.emulator.heightLabel",
      reset: "components.emulator.reset",
      responsiveDescription: "components.emulator.responsiveDescription",
      responsiveLabel: "components.emulator.responsiveLabel",
      rotate: "components.emulator.rotate",
      summary: "components.emulator.summary",
      toolbarLabel: "components.emulator.toolbarLabel",
      viewportDescription: "components.emulator.viewportDescription",
      viewportLabel: "components.emulator.viewportLabel",
      visionFilter: {
        deuteranopia: "components.emulator.visionFilter.deuteranopia",
        grayscale: "components.emulator.visionFilter.grayscale",
        normal: "components.emulator.visionFilter.normal",
        protanopia: "components.emulator.visionFilter.protanopia",
        tritanopia: "components.emulator.visionFilter.tritanopia",
      },
      visionFilterLabel: "components.emulator.visionFilterLabel",
      widthLabel: "components.emulator.widthLabel",
      zoomLabel: "components.emulator.zoomLabel",
      zoomValue: "components.emulator.zoomValue",
    },
    indexAction: "components.indexAction",
    ingest: {
      acceptBehaviorLoss: "components.ingest.acceptBehaviorLoss",
      acceptedNotice: "components.ingest.acceptedNotice",
      description: "components.ingest.description",
      running: "components.ingest.running",
      scenario: "components.ingest.scenario",
      slug: "components.ingest.slug",
      sourceFile: "components.ingest.sourceFile",
      submit: "components.ingest.submit",
      success: "components.ingest.success",
      tags: "components.ingest.tags",
      title: "components.ingest.title",
    },
    inspector: {
      breadcrumbLabel: "components.inspector.breadcrumbLabel",
      empty: "components.inspector.empty",
      rectLabel: "components.inspector.rectLabel",
      statusActive: "components.inspector.statusActive",
      statusIdle: "components.inspector.statusIdle",
      statusReady: "components.inspector.statusReady",
      title: "components.inspector.title",
      toggleStart: "components.inspector.toggleStart",
      toggleStop: "components.inspector.toggleStop",
    },
    loading: "components.loading",
    noTags: "components.noTags",
    openAction: "components.openAction",
    searchLabel: "components.searchLabel",
    searchPlaceholder: "components.searchPlaceholder",
    slotLabel: "components.slotLabel",
    styleLabel: "components.styleLabel",
    stylePlaceholder: "components.stylePlaceholder",
    summary: "components.summary",
    summary_one: "components.summary_one",
    tagLabel: "components.tagLabel",
    tagPlaceholder: "components.tagPlaceholder",
    tagsFilterLabel: "components.tagsFilterLabel",
    tagsFilterPlaceholder: "components.tagsFilterPlaceholder",
    tagsLabel: "components.tagsLabel",
    themeSwitcher: {
      appearanceDescription: "components.themeSwitcher.appearanceDescription",
      appearanceLabel: "components.themeSwitcher.appearanceLabel",
      applied: "components.themeSwitcher.applied",
      kitDescription: "components.themeSwitcher.kitDescription",
      kitLabel: "components.themeSwitcher.kitLabel",
      kitOptions: {
        commandDisplay: "components.themeSwitcher.kitOptions.commandDisplay",
        conversionLanding: "components.themeSwitcher.kitOptions.conversionLanding",
        default: "components.themeSwitcher.kitOptions.default",
      },
      loading: "components.themeSwitcher.loading",
      mode: {
        dark: "components.themeSwitcher.mode.dark",
        light: "components.themeSwitcher.mode.light",
        system: "components.themeSwitcher.mode.system",
      },
      modeDescription: "components.themeSwitcher.modeDescription",
      modeLabel: "components.themeSwitcher.modeLabel",
      visualDescription: "components.themeSwitcher.visualDescription",
      visualLabel: "components.themeSwitcher.visualLabel",
    },
    title: "components.title",
    versionLabel: "components.versionLabel",
  },
  default: "default",
  defaultValue: "defaultValue",
  density: "density",
  desc: "desc",
  description: "description",
  detail: "detail",
  dialog: "dialog",
  drawer: "drawer",
  error: "error",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  escaped: "escaped",
  example: "example",
  "exit-passive": "exit-passive",
  expect: "expect",
  export: "export",
  fixture: "fixture",
  format: "format",
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    statusLabel: "health.statusLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  id: "id",
  idle: "idle",
  inspectorState: "inspectorState",
  inspectorSurfaceId: "inspectorSurfaceId",
  key: "key",
  kind: "kind",
  label: "label",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  "lucide-react": "lucide-react",
  metric: "metric",
  mode: "mode",
  module: "module",
  name: "name",
  nav: {
    browseAssets: "nav.browseAssets",
    closeDrawer: "nav.closeDrawer",
    drawerLabel: "nav.drawerLabel",
    label: "nav.label",
    openDrawer: "nav.openDrawer",
    settings: "nav.settings",
  },
  notFound: {
    description: "notFound.description",
    home: "notFound.home",
    title: "notFound.title",
  },
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  online: "online",
  path: "path",
  "permission-denied": "permission-denied",
  placeholder: "placeholder",
  provenance: "provenance",
  purpose: "purpose",
  react: "react",
  "react-component-library:useEscapeKey": "react-component-library:useEscapeKey",
  region: "region",
  regionId: "regionId",
  regionState: "regionState",
  require: "require",
  role: "role",
  route: {
    loading: "route.loading",
  },
  schema: "schema",
  schemaVersion: "schemaVersion",
  selector: "selector",
  settings: {
    appearance: "settings.appearance",
    language: "settings.language",
    subtitle: "settings.subtitle",
    theme: "settings.theme",
    title: "settings.title",
  },
  shape: "shape",
  size: "size",
  state: "state",
  statement: "statement",
  statusMessage: "statusMessage",
  story: "story",
  storyRef: "storyRef",
  style: "style",
  subject: "subject",
  surfaceId: "surfaceId",
  "tailwind-merge": "tailwind-merge",
  testid: "testid",
  text: "text",
  theme: {
    dark: "theme.dark",
    light: "theme.light",
    system: "theme.system",
  },
  tier: "tier",
  title: "title",
  tone: "tone",
  true: "true",
  type: "type",
  uncontrolled: "uncontrolled",
  value: "value",
  "var(--radius-pill)": "var(--radius-pill)",
  "var(--space-3xs)": "var(--space-3xs)",
  variant: "variant",
  version: "version",
  versions: {
    createdAt: "versions.createdAt",
    currentSource: "versions.currentSource",
    diff: {
      copied: "versions.diff.copied",
      copy: "versions.diff.copy",
      empty: "versions.diff.empty",
      fromLabel: "versions.diff.fromLabel",
      modeLabel: "versions.diff.modeLabel",
      runAction: "versions.diff.runAction",
      running: "versions.diff.running",
      split: "versions.diff.split",
      summary: "versions.diff.summary",
      title: "versions.diff.title",
      toLabel: "versions.diff.toLabel",
      unified: "versions.diff.unified",
      viewerLabel: "versions.diff.viewerLabel",
    },
    empty: "versions.empty",
    loading: "versions.loading",
    recordedAt: "versions.recordedAt",
    shaLabel: "versions.shaLabel",
    summary: "versions.summary",
    title: "versions.title",
    versionLabel: "versions.versionLabel",
    viewVersion: "versions.viewVersion",
    viewingVersion: "versions.viewingVersion",
  },
  voiceInput: "voiceInput",
  workflows: {
    active: "workflows.active",
    none: "workflows.none",
    retry: "workflows.retry",
    stop: "workflows.stop",
  },
  "↑": "↑",
} as const;

export type Strings = typeof strings;
