#!/usr/bin/env bash
# GridLAB-D Resource - Default Configuration

# Service Configuration
export GRIDLABD_PORT="${GRIDLABD_PORT:-9511}"
export GRIDLABD_HOST="${GRIDLABD_HOST:-0.0.0.0}"
export GRIDLABD_API_ENABLED="${GRIDLABD_API_ENABLED:-true}"

# Directory Configuration
export GRIDLABD_DATA_DIR="${GRIDLABD_DATA_DIR:-${HOME}/.vrooli/gridlabd/data}"
export GRIDLABD_LOG_DIR="${GRIDLABD_LOG_DIR:-${HOME}/.vrooli/gridlabd/logs}"
export GRIDLABD_CONFIG_DIR="${GRIDLABD_CONFIG_DIR:-${HOME}/.vrooli/gridlabd/config}"
export GRIDLABD_MODELS_DIR="${GRIDLABD_MODELS_DIR:-${GRIDLABD_DATA_DIR}/models}"
export GRIDLABD_RESULTS_DIR="${GRIDLABD_RESULTS_DIR:-${GRIDLABD_DATA_DIR}/results}"

# Logging Configuration
export GRIDLABD_LOG_LEVEL="${GRIDLABD_LOG_LEVEL:-INFO}"
export GRIDLABD_LOG_FILE="${GRIDLABD_LOG_FILE:-${GRIDLABD_LOG_DIR}/gridlabd.log}"
export GRIDLABD_API_LOG_FILE="${GRIDLABD_API_LOG_FILE:-${GRIDLABD_LOG_DIR}/api.log}"

# Performance Configuration
export GRIDLABD_MAX_THREADS="${GRIDLABD_MAX_THREADS:-4}"
export GRIDLABD_MEMORY_LIMIT="${GRIDLABD_MEMORY_LIMIT:-2048}"  # MB
export GRIDLABD_MAX_CONCURRENT_SIMS="${GRIDLABD_MAX_CONCURRENT_SIMS:-5}"
export GRIDLABD_SIMULATION_TIMEOUT="${GRIDLABD_SIMULATION_TIMEOUT:-3600}"  # seconds

# Solver Configuration
export GRIDLABD_SOLVER="${GRIDLABD_SOLVER:-NR}"  # Newton-Raphson
export GRIDLABD_CONVERGENCE_LIMIT="${GRIDLABD_CONVERGENCE_LIMIT:-0.0001}"
export GRIDLABD_MAX_ITERATIONS="${GRIDLABD_MAX_ITERATIONS:-100}"

# API Configuration
export GRIDLABD_API_TIMEOUT="${GRIDLABD_API_TIMEOUT:-300}"
export GRIDLABD_API_MAX_UPLOAD_SIZE="${GRIDLABD_API_MAX_UPLOAD_SIZE:-100}"  # MB
export GRIDLABD_API_CORS_ENABLED="${GRIDLABD_API_CORS_ENABLED:-true}"

# Installation Configuration
export GRIDLABD_VERSION="${GRIDLABD_VERSION:-5.3}"
export GRIDLABD_INSTALL_DIR="${GRIDLABD_INSTALL_DIR:-/usr/local/gridlabd}"
export GRIDLABD_BINARY="${GRIDLABD_BINARY:-gridlabd}"

# Health Check Configuration
export GRIDLABD_HEALTH_CHECK_INTERVAL="${GRIDLABD_HEALTH_CHECK_INTERVAL:-30}"
export GRIDLABD_HEALTH_CHECK_TIMEOUT="${GRIDLABD_HEALTH_CHECK_TIMEOUT:-5}"

# Python Environment
export GRIDLABD_PYTHON="${GRIDLABD_PYTHON:-python3}"
export GRIDLABD_VENV_DIR="${GRIDLABD_VENV_DIR:-${HOME}/.vrooli/gridlabd/venv}"

# Feature Flags
export GRIDLABD_ENABLE_MYSQL="${GRIDLABD_ENABLE_MYSQL:-false}"
export GRIDLABD_ENABLE_MATLAB="${GRIDLABD_ENABLE_MATLAB:-false}"
export GRIDLABD_ENABLE_VISUALIZATION="${GRIDLABD_ENABLE_VISUALIZATION:-true}"

# Create required directories
mkdir -p "${GRIDLABD_DATA_DIR}"
mkdir -p "${GRIDLABD_LOG_DIR}"
mkdir -p "${GRIDLABD_CONFIG_DIR}"
mkdir -p "${GRIDLABD_MODELS_DIR}"
mkdir -p "${GRIDLABD_RESULTS_DIR}"