import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { fetchV2HostRequirements } from "../../lib/api";
import type { HostRequirement } from "../../types";

function Requirements({ title, items, onToggle, onConfig }: { title: string; items: HostRequirement[]; onToggle: (name: string, value: boolean) => void; onConfig?: (name: string, config: Record<string, unknown>) => void }) {
  const groupTestId = title.toLowerCase() === "tools" ? "host-tools" : "host-safeguards";
  return <section className="mt-6" data-testid={groupTestId} role="group"><h2 className="text-lg font-medium">{title}</h2>{title === "Safeguards" && <p data-testid="change-summary" role="note" className="mt-2 text-xs text-muted">Each safeguard row describes the host change it declares before consent.</p>}<div className="mt-3 space-y-2">{items.length === 0 ? <p className="text-sm text-muted">No declared {title.toLowerCase()}.</p> : items.map((item) => { const selected = item.status === "required" || item.status === "opted_in"; return <div key={item.name} className="rounded-lg border border-muted bg-surface-muted p-3"><label className="flex gap-3"><input type="checkbox" data-testid="requirement-entry" className="min-h-11 min-w-11" checked={selected} disabled={item.required} onChange={(event) => onToggle(item.name, event.target.checked)} /><span><span className="font-medium">{item.name}</span>{item.required && <span className="ml-2 text-xs text-primary-soft">required</span>}{item.risk && <span className="ml-2 text-xs text-warning" data-testid="risk-indicator" role="note">risk: {item.risk}</span>}<span className="block text-xs text-muted">{item.reason || item.description}</span><span className="mt-1 block text-xs text-muted" data-testid="privilege-indicator" role="note">Privilege: {item.privilege || "not declared"} · Bundling: {item.bundling || "not declared"}{item.platforms?.length ? ` · Platforms: ${item.platforms.join(", ")}` : ""}</span></span></label>{onConfig && item.config_schema?.properties && <ConfigFields item={item} onChange={(config) => onConfig(item.name, config)} />}</div>; })}</div></section>;
}
function ConfigFields({ item, onChange }: { item: HostRequirement; onChange: (config: Record<string, unknown>) => void }) {
  const schema = item.config_schema as { properties?: Record<string, { type?: string; title?: string; description?: string; enum?: unknown[]; default?: unknown }> };
  const [values, setValues] = useState<Record<string, unknown>>(item.config ?? {});
  return <fieldset data-testid={`config-${item.name}`} className="mt-3 space-y-2 border-t border-border-muted pt-3"><legend className="text-sm font-medium">Configuration</legend>{Object.entries(schema.properties ?? {}).map(([key, property]) => { const value = values[key] ?? property.default ?? ""; const update = (next: unknown) => { const config = { ...values, [key]: next }; setValues(config); onChange(config); }; if (property.enum?.length) return <label key={key} className="block text-sm">{property.title || key}<select aria-label={property.title || key} className="mt-1 min-h-11 w-full rounded-md border border-muted bg-surface px-3" value={String(value)} onChange={(event) => update(event.target.value)}>{property.enum.map((option) => <option key={String(option)} value={String(option)}>{String(option)}</option>)}</select></label>; if (property.type === "boolean") return <label key={key} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" aria-label={property.title || key} checked={Boolean(value)} onChange={(event) => update(event.target.checked)} />{property.title || key}</label>; return <label key={key} className="block text-sm">{property.title || key}<input aria-label={property.title || key} type={property.type === "number" || property.type === "integer" ? "number" : "text"} className="mt-1 min-h-11 w-full rounded-md border border-muted bg-surface px-3" value={String(value)} onChange={(event) => update(property.type === "number" || property.type === "integer" ? Number(event.target.value) : event.target.value)} />{property.description && <span className="mt-1 block text-xs text-muted">{property.description}</span>}</label>; })}</fieldset>;
}
export function StepHostRequirements({ onTool, onSafeguard, onHostConfig }: { onTool: (name: string, value: boolean) => void; onSafeguard: (name: string, value: boolean) => void; onHostConfig?: (kind: "host_tools" | "host_safeguards", name: string, config: Record<string, unknown>) => void }) {
  const { data, isLoading, error } = useQuery({ queryKey: ["v2-host-requirements"], queryFn: fetchV2HostRequirements });
  return <div data-testid="step-host-requirements"><h1 className="text-xl font-semibold sm:text-2xl">Host tools and safeguards</h1><p className="mt-2 text-sm text-muted">Requirements are derived from selected manifests. Required tools stay selected; safeguards show their host-change risk before opt-in.</p>{isLoading && <p role="status" className="mt-6">Loading host requirements…</p>}{error && <p role="alert" className="mt-6 text-danger">Unable to derive host requirements.</p>}<Requirements title="Tools" items={data?.tools ?? []} onToggle={onTool} onConfig={onHostConfig ? (name, config) => onHostConfig("host_tools", name, config) : undefined} /><Requirements title="Safeguards" items={data?.safeguards ?? []} onToggle={onSafeguard} onConfig={onHostConfig ? (name, config) => onHostConfig("host_safeguards", name, config) : undefined} /></div>;
}
