# Browser Automation Studio requirement registry (draft)
# Status values: pending | in_progress | complete | not_applicable
# Validation status: not_implemented | planned | implemented | failing

meta:
  scenario: browser-automation-studio
  version: 0.1.4
  generated: 2025-11-10
  owners:
    - platform: browser-automation-studio
      contact: execution-team@vrooli.dev
  notes: |
    This initial skeleton captures the top-level PRD requirements that must
    be linked to automated validation. Update `status` and `validation.status`
    as implementation progresses.

requirements:
  - id: BAS-FUNC-001
    category: foundation
    prd_ref: "Functional Requirements > Must Have > Visual workflow builder"
    title: Persist visual workflows with nodes/edges and folder hierarchy
    description: |
      Users can create, update, and load React Flow-based workflows with
      organized folders. Graph definitions must include nodes, edges, and
      metadata required for execution planning.
    status: in_progress
    criticality: P0
    validation:
      - type: test
        ref: api/browserless/compiler_test.go
        status: implemented
        notes: Validates compile ordering, cycle detection, and unsupported node handling.
      - type: test
        ref: test/phases/test-unit.sh
        status: not_implemented
        notes: Add unit coverage for `database.Workflow` persistence & compiler validation.
      - type: automation
        ref: workflows/ui-validation/structure-check.json
        status: not_implemented
        notes: Planned Browserless automation to verify workflow CRUD via API.
      - type: automation
        ref: automation/projects/demo-sanity.yaml
        status: implemented
        notes: Validates the demo project and workflow seed so the UI always has an executable journey.

  - id: BAS-FUNC-002
    category: execution
    prd_ref: "Functional Requirements > Must Have > Real-time screenshot display"
    title: Stream execution telemetry (screenshots, progress, logs) while runs are active
    description: |
      The executor must deliver per-step telemetry (progress, console, network,
      screenshots, heartbeats) to all subscribed clients via WebSocket within 500 ms of capture.
    status: in_progress
    criticality: P0
    validation:
      - type: test
        ref: api/browserless/client_test.go
        status: implemented
        notes: Exercises telemetry persistence, heartbeat emission, retry/backoff attempt metadata, assert artifact storage, and per-step highlight metadata; extend with WebSocket contract tests.
      - type: test
        ref: api/browserless/runtime/session_test.go
        status: not_implemented
        notes: Session manager unit tests emitting mock telemetry.
      - type: test
        ref: ui/tests/executionEventProcessor.heartbeat.test.mjs
        status: implemented
        notes: Node-based unit test ensuring heartbeat events update progress and heartbeat metadata in the UI store; extend with UI heartbeat state rendering snapshot.
      - type: test
        ref: ui/tests/executionEventProcessor.assertion.test.mjs
        status: implemented
        notes: Confirms assertion payloads generate readable success/failure logs in the execution stream processor.
      - type: automation
        ref: automation/executions/telemetry-smoke.yaml
        status: implemented
        notes: Shell automation provisions a deterministic data-URL workflow, executes it, and asserts timeline frames include screenshots, highlight metadata, console logs, network events, and successful assertion payloads before validating replay export packages.
      - type: manual
        ref: ui/src/components/ExecutionViewer.tsx
        status: implemented
        notes: Execution viewer flags heartbeat states (awaiting/delayed/stalled) with contextual messaging.
      - type: manual
        ref: cli/browser-automation-studio
        status: implemented
        notes: CLI execution watch emits heartbeat lag/stall warnings and recovery notices.
      - type: automation
        ref: automation/executions/heartbeat-stall.yaml
        status: implemented
        notes: Shell harness that relaunches the scenario with heartbeats disabled, executes a 20s wait workflow, and asserts the CLI reports a stalled heartbeat.

  - id: BAS-FUNC-003
    category: replay
    prd_ref: "Functional Requirements > Should Have > Replay & marketing renderer"
    title: Persist normalized execution artifacts for replay & video rendering
    description: |
      Execution runs produce a timeline of artifacts (screenshots, cursor trails,
      DOM snippets) stored in Postgres + MinIO with deterministic keys. The UI and
      CLI can reconstruct replays from these artifacts.
    status: in_progress
    criticality: P1
    validation:
      - type: test
        ref: api/database/repository_test.go
        status: in_progress
        notes: Covers execution_steps/execution_artifacts persistence; add replay schema contract tests as renderer hardens.
      - type: test
        ref: api/browserless/client_test.go
        status: implemented
        notes: Verifies timeline_frame artifact creation, cursor trail metadata propagation, highlight/mask metadata, DOM snapshot persistence, and retry history fields without live Browserless.
      - type: test
        ref: api/services/exporter_test.go
        status: implemented
        notes: Ensures replay export packages include frame/asset metadata, transition hints, DOM snapshot HTML, and resiliency fields for downstream renderers.
      - type: test
        ref: api/services/timeline_test.go
        status: implemented
        notes: Ensures execution timeline aggregation surfaces screenshot/highlight metadata, DOM snapshot previews, and artifact references for replay consumers.
      - type: automation
        ref: automation/replay/render-check.yaml
        status: implemented
        notes: End-to-end renderer automation that validates `execution render` output bundle.
      - type: manual
        ref: cli/browser-automation-studio execution render
        status: implemented
        notes: Generates stylised HTML replay packages from export metadata for operator review.

  - id: BAS-FUNC-004
    category: ai-integration
    prd_ref: "Functional Requirements > Must Have > AI workflow generation"
    title: AI-generated workflows validated against the execution plan
    description: |
      Prompts handled by the AI generator must round-trip through the compiler
      and execute at least one smoke test workflow without manual edits.
    status: pending
    criticality: P0
    validation:
      - type: test
        ref: api/services/workflow_service_ai_test.go
        status: not_implemented
        notes: Add deterministic tests for AI prompt normalization + compiler validation.
      - type: automation
        ref: automation/ai/generated-smoke.yaml
        status: planned
        notes: Browserless automation executing AI-generated workflow end-to-end.

reporting:
  script: scripts/requirements/report.js
  entrypoint: node scripts/requirements/report.js
  outputs:
    - format: json
      description: Machine-readable coverage report for CI dashboards
    - format: markdown
      description: README badge/table generation
  cli_options:
    --scenario: browser-automation-studio
    --format: json|markdown
    --include-pending: boolean
  aggregates:
    - metric: coverage_ratio
      formula: implemented validations / required validations
    - metric: criticality_gap
      formula: count of requirements with status != complete and criticality in [P0, P1]
