// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
    description: "app.description",
    versionTag: "app.versionTag",
  },
  shell: {
    openMenu: "shell.openMenu",
    openSettings: "shell.openSettings",
    closeSettings: "shell.closeSettings",
    primaryNav: "shell.primaryNav",
    mainContent: "shell.mainContent",
    settingsTitle: "shell.settingsTitle",
  },
  status: {
    checking: "status.checking",
    offline: "status.offline",
    live: "status.live",
    healthy: "status.healthy",
    degraded: "status.degraded",
    issue: "status.issue",
    enabled: "status.enabled",
    off: "status.off",
    ok: "status.ok",
    error: "status.error",
    fallback: "status.fallback",
  },
  common: {
    retry: "common.retry",
    loading: "common.loading",
    default: "common.default",
    dash: "common.dash",
    lastHour: "common.lastHour",
    last24h: "common.last24h",
    millisSuffix: "common.millisSuffix",
    creditsSuffix: "common.creditsSuffix",
  },
  nav: {
    overview: "nav.overview",
    diagnostics: "nav.diagnostics",
    configure: "nav.configure",
    voices: "nav.voices",
    usage: "nav.usage",
    docs: "nav.docs",
  },
  overview: {
    openDiagnostics: "overview.openDiagnostics",
    summaryApi: "overview.summaryApi",
    summaryRecent: "overview.summaryRecent",
    summaryProviderTiers: "overview.summaryProviderTiers",
    precedenceHint: "overview.precedenceHint",
    recentTitle: "overview.recentTitle",
    recentDescription: "overview.recentDescription",
    noOperations: "overview.noOperations",
  },
  config: {
    title: "config.title",
    description: "config.description",
    providerRoutingTitle: "config.providerRoutingTitle",
    providerRoutingDescription: "config.providerRoutingDescription",
    capabilityHeader: "config.capabilityHeader",
    byokHeader: "config.byokHeader",
    vrooliHeader: "config.vrooliHeader",
    localHeader: "config.localHeader",
    byokCredsTitle: "config.byokCredsTitle",
    byokCredsDescription: "config.byokCredsDescription",
    byokEmpty: "config.byokEmpty",
    providerColHeader: "config.providerColHeader",
    fingerprintHeader: "config.fingerprintHeader",
    createdHeader: "config.createdHeader",
    envTitle: "config.envTitle",
    envDescription: "config.envDescription",
    envFollowUp: "config.envFollowUp",
    toggleByok: "config.toggleByok",
    toggleVrooli: "config.toggleVrooli",
    toggleLocal: "config.toggleLocal",
    deleteAction: "config.deleteAction",
    providerFieldLabel: "config.providerFieldLabel",
    providerPlaceholder: "config.providerPlaceholder",
    capabilityFieldLabel: "config.capabilityFieldLabel",
    apiKeyFieldLabel: "config.apiKeyFieldLabel",
    apiKeyPlaceholder: "config.apiKeyPlaceholder",
    addCredential: "config.addCredential",
    capabilityStt: "config.capabilityStt",
    capabilityTts: "config.capabilityTts",
    capabilitySummarize: "config.capabilitySummarize",
  },
  voices: {
    title: "voices.title",
    description: "voices.description",
    matrixTitle: "voices.matrixTitle",
    canonicalHeader: "voices.canonicalHeader",
    localHealthTitle: "voices.localHealthTitle",
    localHealthDescription: "voices.localHealthDescription",
    localHealthFollowUp: "voices.localHealthFollowUp",
  },
  diagnostics: {
    title: "diagnostics.title",
    description: "diagnostics.description",
    tablistLabel: "diagnostics.tablistLabel",
    tabTranscribe: "diagnostics.tabTranscribe",
    tabSynthesize: "diagnostics.tabSynthesize",
    tabSummarize: "diagnostics.tabSummarize",
    tabTranscode: "diagnostics.tabTranscode",
    transcribeTitle: "diagnostics.transcribeTitle",
    transcribeDescription: "diagnostics.transcribeDescription",
    audioFileLabel: "diagnostics.audioFileLabel",
    transcribeAction: "diagnostics.transcribeAction",
    resultLabel: "diagnostics.resultLabel",
    summarizeTitle: "diagnostics.summarizeTitle",
    summarizeDescription: "diagnostics.summarizeDescription",
    summarizeInputLabel: "diagnostics.summarizeInputLabel",
    summarizeInputPlaceholder: "diagnostics.summarizeInputPlaceholder",
    levelLabel: "diagnostics.levelLabel",
    levelLight: "diagnostics.levelLight",
    levelModerate: "diagnostics.levelModerate",
    levelHeavy: "diagnostics.levelHeavy",
    summarizeAction: "diagnostics.summarizeAction",
    synthesizeTitle: "diagnostics.synthesizeTitle",
    synthesizeDescription: "diagnostics.synthesizeDescription",
    synthesizeAction: "diagnostics.synthesizeAction",
    synthesizeTextPlaceholder: "diagnostics.synthesizeTextPlaceholder",
    synthesizeVoiceLabel: "diagnostics.synthesizeVoiceLabel",
    transcodeTitle: "diagnostics.transcodeTitle",
    transcodeDescription: "diagnostics.transcodeDescription",
    transcodeAction: "diagnostics.transcodeAction",
    transcodeOutputFormatLabel: "diagnostics.transcodeOutputFormatLabel",
    transcodeFailed: "diagnostics.transcodeFailed",
    transcodeDownload: "diagnostics.transcodeDownload",
    formatWav: "diagnostics.formatWav",
    formatMp3: "diagnostics.formatMp3",
    formatFlac: "diagnostics.formatFlac",
    formatOgg: "diagnostics.formatOgg",
    traceTitle: "diagnostics.traceTitle",
    traceDescription: "diagnostics.traceDescription",
    traceEmpty: "diagnostics.traceEmpty",
    tablistTranscribeMode: "diagnostics.tablistTranscribeMode",
    tabLiveMic: "diagnostics.tabLiveMic",
    tabOneshot: "diagnostics.tabOneshot",
    tabFile: "diagnostics.tabFile",
    liveStop: "diagnostics.liveStop",
    liveStart: "diagnostics.liveStart",
    partialLabel: "diagnostics.partialLabel",
    finalLabel: "diagnostics.finalLabel",
    oneshotStopUpload: "diagnostics.oneshotStopUpload",
    oneshotUploading: "diagnostics.oneshotUploading",
    oneshotRecord: "diagnostics.oneshotRecord",
    oneshotHint: "diagnostics.oneshotHint",
    liveStartFailed: "diagnostics.liveStartFailed",
    micPermissionDenied: "diagnostics.micPermissionDenied",
    suite: {
      title: "diagnostics.suite.title",
      description: "diagnostics.suite.description",
      runAction: "diagnostics.suite.runAction",
      runningAction: "diagnostics.suite.runningAction",
      rerunAction: "diagnostics.suite.rerunAction",
      lastRunNever: "diagnostics.suite.lastRunNever",
      lastRunLabel: "diagnostics.suite.lastRunLabel",
      lastRunJustNow: "diagnostics.suite.lastRunJustNow",
      overallNever: "diagnostics.suite.overallNever",
      overallPass: "diagnostics.suite.overallPass",
      overallPartial: "diagnostics.suite.overallPartial",
      overallFail: "diagnostics.suite.overallFail",
      overallUnknown: "diagnostics.suite.overallUnknown",
      tileLabelSTT: "diagnostics.suite.tileLabelSTT",
      tileLabelTTS: "diagnostics.suite.tileLabelTTS",
      tileLabelSummarize: "diagnostics.suite.tileLabelSummarize",
      tileLabelTranscode: "diagnostics.suite.tileLabelTranscode",
      tileNever: "diagnostics.suite.tileNever",
      tileOK: "diagnostics.suite.tileOK",
      tileFail: "diagnostics.suite.tileFail",
      tileTier: "diagnostics.suite.tileTier",
      tileProvider: "diagnostics.suite.tileProvider",
      tileModel: "diagnostics.suite.tileModel",
      tileLatency: "diagnostics.suite.tileLatency",
      tileLatencyMs: "diagnostics.suite.tileLatencyMs",
      tileNoProvider: "diagnostics.suite.tileNoProvider",
      errorCodeProviderUnavailable: "diagnostics.suite.errorCodeProviderUnavailable",
      errorCodeNotConfigured: "diagnostics.suite.errorCodeNotConfigured",
      errorCodeDeadlineExceeded: "diagnostics.suite.errorCodeDeadlineExceeded",
      errorCodeInsufficientCredits: "diagnostics.suite.errorCodeInsufficientCredits",
      errorCodeInternal: "diagnostics.suite.errorCodeInternal",
      logToggleOpen: "diagnostics.suite.logToggleOpen",
      logToggleClose: "diagnostics.suite.logToggleClose",
      logEmpty: "diagnostics.suite.logEmpty",
      logEntry: "diagnostics.suite.logEntry",
      logStatusOK: "diagnostics.suite.logStatusOK",
      logStatusFail: "diagnostics.suite.logStatusFail",
      runFailed: "diagnostics.suite.runFailed",
      traceFilterTitle: "diagnostics.suite.traceFilterTitle",
      traceFilterAll: "diagnostics.suite.traceFilterAll",
      traceFilterSTT: "diagnostics.suite.traceFilterSTT",
      traceFilterTTS: "diagnostics.suite.traceFilterTTS",
      traceFilterSummarize: "diagnostics.suite.traceFilterSummarize",
      traceFilterTranscode: "diagnostics.suite.traceFilterTranscode",
    },
  },
  usage: {
    title: "usage.title",
    description: "usage.description",
    operations: "usage.operations",
    creditsCharged: "usage.creditsCharged",
    errors: "usage.errors",
    distributionTitle: "usage.distributionTitle",
    distributionDescription: "usage.distributionDescription",
    noUsage: "usage.noUsage",
    recentTitle: "usage.recentTitle",
    recentEmpty: "usage.recentEmpty",
    colTime: "usage.colTime",
    colCapability: "usage.colCapability",
    colOperation: "usage.colOperation",
    colProvider: "usage.colProvider",
    colModel: "usage.colModel",
    colLatency: "usage.colLatency",
    colCredits: "usage.colCredits",
    colStatus: "usage.colStatus",
  },
  docs: {
    title: "docs.title",
    description: "docs.description",
    groupPRD: "docs.groupPRD",
    groupConcepts: "docs.groupConcepts",
    groupReference: "docs.groupReference",
    groupInternal: "docs.groupInternal",
    backToList: "docs.backToList",
    loading: "docs.loading",
    notFoundTitle: "docs.notFoundTitle",
    notFoundDescription: "docs.notFoundDescription",
    viewSource: "docs.viewSource",
  },
  notFound: {
    title: "notFound.title",
    description: "notFound.description",
    backToOverview: "notFound.backToOverview",
  },
  settings: {
    themeLabel: "settings.themeLabel",
    themeLight: "settings.themeLight",
    themeDark: "settings.themeDark",
    themeSystem: "settings.themeSystem",
    fontScaleLabel: "settings.fontScaleLabel",
    fontScaleCompact: "settings.fontScaleCompact",
    fontScaleComfortable: "settings.fontScaleComfortable",
    fontScaleLarge: "settings.fontScaleLarge",
    motionLabel: "settings.motionLabel",
    reducedMotion: "settings.reducedMotion",
  },
  apiError: {
    unimplementedTitle: "apiError.unimplementedTitle",
    loadFailedTitle: "apiError.loadFailedTitle",
    unimplementedDescription: "apiError.unimplementedDescription",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
