// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
    description: "app.description",
    versionTag: "app.versionTag",
  },
  shell: {
    openMenu: "shell.openMenu",
    openSettings: "shell.openSettings",
    closeSettings: "shell.closeSettings",
    primaryNav: "shell.primaryNav",
    mainContent: "shell.mainContent",
    settingsTitle: "shell.settingsTitle",
  },
  status: {
    checking: "status.checking",
    offline: "status.offline",
    live: "status.live",
    healthy: "status.healthy",
    degraded: "status.degraded",
    issue: "status.issue",
    enabled: "status.enabled",
    off: "status.off",
    probePending: "status.probePending",
    ok: "status.ok",
    error: "status.error",
    fallback: "status.fallback",
  },
  common: {
    retry: "common.retry",
    loading: "common.loading",
    default: "common.default",
    dash: "common.dash",
    lastHour: "common.lastHour",
    last24h: "common.last24h",
    millisSuffix: "common.millisSuffix",
    creditsSuffix: "common.creditsSuffix",
  },
  nav: {
    overview: "nav.overview",
    diagnostics: "nav.diagnostics",
    configure: "nav.configure",
    voices: "nav.voices",
    usage: "nav.usage",
    docs: "nav.docs",
  },
  overview: {
    openDiagnostics: "overview.openDiagnostics",
    summaryApi: "overview.summaryApi",
    summaryRecent: "overview.summaryRecent",
    summaryProviderTiers: "overview.summaryProviderTiers",
    precedenceHint: "overview.precedenceHint",
    recentTitle: "overview.recentTitle",
    recentDescription: "overview.recentDescription",
    noOperations: "overview.noOperations",
  },
  config: {
    title: "config.title",
    description: "config.description",
    providerRoutingTitle: "config.providerRoutingTitle",
    providerRoutingDescription: "config.providerRoutingDescription",
    capabilityHeader: "config.capabilityHeader",
    byokHeader: "config.byokHeader",
    vrooliHeader: "config.vrooliHeader",
    localHeader: "config.localHeader",
    byokCredsTitle: "config.byokCredsTitle",
    byokCredsDescription: "config.byokCredsDescription",
    byokEmpty: "config.byokEmpty",
    providerColHeader: "config.providerColHeader",
    fingerprintHeader: "config.fingerprintHeader",
    createdHeader: "config.createdHeader",
    envTitle: "config.envTitle",
    envDescription: "config.envDescription",
    envFollowUp: "config.envFollowUp",
  },
  voices: {
    title: "voices.title",
    description: "voices.description",
    matrixTitle: "voices.matrixTitle",
    canonicalHeader: "voices.canonicalHeader",
    localHealthTitle: "voices.localHealthTitle",
    localHealthDescription: "voices.localHealthDescription",
    localHealthFollowUp: "voices.localHealthFollowUp",
  },
  diagnostics: {
    title: "diagnostics.title",
    description: "diagnostics.description",
    tablistLabel: "diagnostics.tablistLabel",
    tabTranscribe: "diagnostics.tabTranscribe",
    tabSynthesize: "diagnostics.tabSynthesize",
    tabSummarize: "diagnostics.tabSummarize",
    tabTranscode: "diagnostics.tabTranscode",
    transcribeTitle: "diagnostics.transcribeTitle",
    transcribeDescription: "diagnostics.transcribeDescription",
    audioFileLabel: "diagnostics.audioFileLabel",
    transcribeAction: "diagnostics.transcribeAction",
    resultLabel: "diagnostics.resultLabel",
    summarizeTitle: "diagnostics.summarizeTitle",
    summarizeDescription: "diagnostics.summarizeDescription",
    summarizeInputLabel: "diagnostics.summarizeInputLabel",
    summarizeInputPlaceholder: "diagnostics.summarizeInputPlaceholder",
    levelLabel: "diagnostics.levelLabel",
    levelLight: "diagnostics.levelLight",
    levelModerate: "diagnostics.levelModerate",
    levelHeavy: "diagnostics.levelHeavy",
    summarizeAction: "diagnostics.summarizeAction",
    synthesizeTitle: "diagnostics.synthesizeTitle",
    synthesizeDescription: "diagnostics.synthesizeDescription",
    synthesizeFollowUp: "diagnostics.synthesizeFollowUp",
    transcodeTitle: "diagnostics.transcodeTitle",
    transcodeDescription: "diagnostics.transcodeDescription",
    transcodeFollowUp: "diagnostics.transcodeFollowUp",
    traceTitle: "diagnostics.traceTitle",
    traceDescription: "diagnostics.traceDescription",
    traceEmpty: "diagnostics.traceEmpty",
  },
  usage: {
    title: "usage.title",
    description: "usage.description",
    operations: "usage.operations",
    creditsCharged: "usage.creditsCharged",
    errors: "usage.errors",
    distributionTitle: "usage.distributionTitle",
    distributionDescription: "usage.distributionDescription",
    noUsage: "usage.noUsage",
    recentTitle: "usage.recentTitle",
    recentEmpty: "usage.recentEmpty",
    colTime: "usage.colTime",
    colCapability: "usage.colCapability",
    colOperation: "usage.colOperation",
    colProvider: "usage.colProvider",
    colModel: "usage.colModel",
    colLatency: "usage.colLatency",
    colCredits: "usage.colCredits",
    colStatus: "usage.colStatus",
  },
  docs: {
    title: "docs.title",
    description: "docs.description",
    groupPRD: "docs.groupPRD",
    groupConcepts: "docs.groupConcepts",
    groupReference: "docs.groupReference",
    groupInternal: "docs.groupInternal",
  },
  notFound: {
    title: "notFound.title",
    description: "notFound.description",
    backToOverview: "notFound.backToOverview",
  },
  settings: {
    themeLabel: "settings.themeLabel",
    themeLight: "settings.themeLight",
    themeDark: "settings.themeDark",
    themeSystem: "settings.themeSystem",
    fontScaleLabel: "settings.fontScaleLabel",
    fontScaleCompact: "settings.fontScaleCompact",
    fontScaleComfortable: "settings.fontScaleComfortable",
    fontScaleLarge: "settings.fontScaleLarge",
    motionLabel: "settings.motionLabel",
    reducedMotion: "settings.reducedMotion",
  },
  apiError: {
    unimplementedTitle: "apiError.unimplementedTitle",
    loadFailedTitle: "apiError.loadFailedTitle",
    unimplementedDescription: "apiError.unimplementedDescription",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
