package graph

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vrooli/cli-core/cliutil"
	"prompt-manager/cli/internal/appctx"
)

type operatingMap struct {
	Teams  []operatingMapTeam  `json:"teams"`
	Topics []operatingMapTopic `json:"topics"`
	Edges  []operatingMapEdge  `json:"edges"`
}
type operatingMapTeam struct {
	ID          string `json:"id"`
	Label       string `json:"label"`
	GoalLinkage string `json:"goal_linkage"`
	Valid       bool   `json:"valid"`
}
type operatingMapTopic struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}
type operatingMapEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
}

func cmdMap(ctx appctx.Context, args []string) error {
	fs := flag.NewFlagSet("map", flag.ContinueOnError)
	jsonOut := fs.Bool("json", false, "Output JSON")
	write := fs.Bool("write", false, "Write docs/agent-system/MAP.md")
	if err := cliutil.ParseInterspersed(fs, args); err != nil {
		return err
	}
	var result operatingMap
	if err := ctx.Get("/operating-models/map", &result); err != nil {
		return fmt.Errorf("fetch operating map: %w", err)
	}
	if *jsonOut {
		return json.NewEncoder(os.Stdout).Encode(result)
	}
	rendered := renderOperatingMap(result)
	if *write {
		return os.WriteFile(filepath.Join("docs", "agent-system", "MAP.md"), []byte(rendered), 0o644)
	}
	fmt.Print(rendered)
	return nil
}

func renderOperatingMap(m operatingMap) string {
	var b strings.Builder
	b.WriteString("# Agent System Map\n\n> Generated by `prompt-manager graph map --write`; do not hand-edit.\n\n```mermaid\nflowchart LR\n")
	for _, t := range m.Teams {
		b.WriteString(fmt.Sprintf("  T_%s[%s]\n", strings.ReplaceAll(t.ID, "-", "_"), t.Label))
	}
	for _, topic := range m.Topics {
		b.WriteString(fmt.Sprintf("  X_%x[(%s)]\n", topic.ID, topic.Label))
	}
	for _, e := range m.Edges {
		b.WriteString(fmt.Sprintf("  %s --> %s\n", mapID(e.From), mapID(e.To)))
	}
	b.WriteString("```\n\n## Teams\n\n| Team | Goal linkage | Contract validation |\n|---|---|---|\n")
	for _, t := range m.Teams {
		status := "valid"
		if !t.Valid {
			status = "invalid"
		}
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", t.Label, t.GoalLinkage, status))
	}
	return b.String()
}
func mapID(value string) string {
	if strings.Contains(value, "/") || strings.Contains(value, "*") {
		return fmt.Sprintf("X_%x", value)
	}
	return "T_" + strings.ReplaceAll(value, "-", "_")
}
