// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $rowKey: "$rowKey",
  $schema: "$schema",
  $text: "$text",
  "Changes saved successfully": {
    "": "Changes saved successfully.",
  },
  "Disabled states retain the same geometry and clearly communicate that the action is unavailable": {
    "": "Disabled states retain the same geometry and clearly communicate that the action is unavailable.",
  },
  "Request in progress": "Request in progress",
  Saved: "Saved",
  app: {
    title: "app.title",
  },
  "aria-label": "aria-label",
  ascending: "ascending",
  asset: "asset",
  "border-app-primary bg-app-primary text-app-primary-foreground": "border-app-primary bg-app-primary text-app-primary-foreground",
  capability: "capability",
  caption: "caption",
  children: "children",
  clsx: "clsx",
  component: "component",
  default: "default",
  defaultValue: "defaultValue",
  desc: "desc",
  description: "description",
  detail: "detail",
  dialog: "dialog",
  emptyMessage: "emptyMessage",
  equals: "equals",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  example: "example",
  export: "export",
  field: "field",
  fixture: "fixture",
  format: "format",
  header: "header",
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  iconName: "iconName",
  id: "id",
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      evidence: "layout.nav.evidence",
      flows: "layout.nav.flows",
      settings: "layout.nav.settings",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  "lucide-react": "lucide-react",
  mode: "mode",
  module: "module",
  name: "name",
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  pages: {
    auth: {
      configured: "pages.auth.configured",
      lastOutcome: "pages.auth.lastOutcome",
      none: "pages.auth.none",
      provider: "pages.auth.provider",
      reference: "pages.auth.reference",
      title: "pages.auth.title",
      unconfigured: "pages.auth.unconfigured",
    },
    dashboard: {
      acquireLease: "pages.dashboard.acquireLease",
      addDevice: "pages.dashboard.addDevice",
      cancel: "pages.dashboard.cancel",
      description: "pages.dashboard.description",
      devicesAvailable: "pages.dashboard.devicesAvailable",
      discoverDevices: "pages.dashboard.discoverDevices",
      fleetSnapshot: "pages.dashboard.fleetSnapshot",
      killImmediately: "pages.dashboard.killImmediately",
      killSession: "pages.dashboard.killSession",
      knownDevice: "pages.dashboard.knownDevice",
      lanDiscovery: "pages.dashboard.lanDiscovery",
      leaseExpires: "pages.dashboard.leaseExpires",
      leaseFailed: "pages.dashboard.leaseFailed",
      liveLeases: "pages.dashboard.liveLeases",
      liveSessionControls: "pages.dashboard.liveSessionControls",
      localTransport: "pages.dashboard.localTransport",
      modelUnavailable: "pages.dashboard.modelUnavailable",
      no: "pages.dashboard.no",
      noDevices: "pages.dashboard.noDevices",
      noLiveSessions: "pages.dashboard.noLiveSessions",
      notInInventory: "pages.dashboard.notInInventory",
      onboardingFailed: "pages.dashboard.onboardingFailed",
      onboardingProbeComplete: "pages.dashboard.onboardingProbeComplete",
      onboardingReport: "pages.dashboard.onboardingReport",
      osUnavailable: "pages.dashboard.osUnavailable",
      pair: "pages.dashboard.pair",
      pairDevice: "pages.dashboard.pairDevice",
      pairTransport: "pages.dashboard.pairTransport",
      pairingStarted: "pages.dashboard.pairingStarted",
      pairingStarting: "pages.dashboard.pairingStarting",
      probePassed: "pages.dashboard.probePassed",
      promotable: "pages.dashboard.promotable",
      reprobe: "pages.dashboard.reprobe",
      status: "pages.dashboard.status",
      strategyMatrix: "pages.dashboard.strategyMatrix",
      tiers: "pages.dashboard.tiers",
      title: "pages.dashboard.title",
      txtMetadata: "pages.dashboard.txtMetadata",
      unavailablePrerequisites: "pages.dashboard.unavailablePrerequisites",
      unknown: "pages.dashboard.unknown",
      unnamedDevice: "pages.dashboard.unnamedDevice",
      yes: "pages.dashboard.yes",
    },
    evidence: {
      actor: "pages.evidence.actor",
      created: "pages.evidence.created",
      description: "pages.evidence.description",
      device: "pages.evidence.device",
      noVerbs: "pages.evidence.noVerbs",
      outcome: "pages.evidence.outcome",
      recentVerbs: "pages.evidence.recentVerbs",
      title: "pages.evidence.title",
      verb: "pages.evidence.verb",
    },
    flows: {
      acquireAndRun: "pages.flows.acquireAndRun",
      blockedBeforeExecution: "pages.flows.blockedBeforeExecution",
      bytes: "pages.flows.bytes",
      capabilityGapReport: "pages.flows.capabilityGapReport",
      chapterSummary: "pages.flows.chapterSummary",
      checksumUnavailable: "pages.flows.checksumUnavailable",
      degradedEvidence: "pages.flows.degradedEvidence",
      description: "pages.flows.description",
      device: "pages.flows.device",
      deviceOption: "pages.flows.deviceOption",
      dispositionReasonUnavailable: "pages.flows.dispositionReasonUnavailable",
      flowDefinition: "pages.flows.flowDefinition",
      flowFailed: "pages.flows.flowFailed",
      invalidFlow: "pages.flows.invalidFlow",
      json: "pages.flows.json",
      killActiveSession: "pages.flows.killActiveSession",
      killAvailable: "pages.flows.killAvailable",
      liveSession: "pages.flows.liveSession",
      noRun: "pages.flows.noRun",
      noValidation: "pages.flows.noValidation",
      redactionVerified: "pages.flows.redactionVerified",
      resolutionSummary: "pages.flows.resolutionSummary",
      retainedEvidence: "pages.flows.retainedEvidence",
      retainedEvidenceAlt: "pages.flows.retainedEvidenceAlt",
      runReview: "pages.flows.runReview",
      runnable: "pages.flows.runnable",
      running: "pages.flows.running",
      sessionKillFailed: "pages.flows.sessionKillFailed",
      strategy: "pages.flows.strategy",
      strategyOption: "pages.flows.strategyOption",
      title: "pages.flows.title",
      validate: "pages.flows.validate",
    },
    settings: {
      localeHeading: "pages.settings.localeHeading",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
  },
  path: "path",
  placeholder: "placeholder",
  provenance: "provenance",
  purpose: "purpose",
  react: "react",
  "react-component-library:useEscapeKey": "react-component-library:useEscapeKey",
  ref: "ref",
  region: "region",
  resolvedAt: "resolvedAt",
  role: "role",
  schema: "schema",
  schemaVersion: "schemaVersion",
  selector: "selector",
  size: "size",
  statement: "statement",
  status: "status",
  storyRef: "storyRef",
  "tailwind-merge": "tailwind-merge",
  testid: "testid",
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  tier: "tier",
  title: "title",
  tone: "tone",
  true: "true",
  type: "type",
  value: "value",
  variant: "variant",
  version: "version",
} as const;

export type Strings = typeof strings;
