site_name: Vrooli Docs
site_description: >-
  Learn all about Vrooli, how it works, and how to use its API for your own projects.
  Vrooli is a decentralized, collaborative automation platform designed to minimize
  the time between the inception of an idea and its development into a
  fully-functional product.
site_url: https://docs.vrooli.com
site_author: Vrooli
nav:
  - About:
      - Overview: about/overview.md
      - Background: about/background.md
      - Resources: about/resources.md
  - Valyxa:
      - Overview: valyxa/overview.md
  - API Reference:
      - Overview: api_reference/overview.md
      - Getting Access: api_reference/getting_access.md
      - Authorization: api_reference/authorization.md
  - Setup:
      - Overview: setup/overview.md
      - Project Structure: setup/project_structure.md
      - Getting Started:
          - Overview: setup/getting_started/overview.md
          - Prerequisites: setup/getting_started/prerequisites.md
          - Remote Server Setup: setup/getting_started/remote_setup.md
          - Repository Setup: setup/getting_started/repo_setup.md
          - Messenger Setup: setup/messenger_setup.md
          - S3 Setup: setup/s3_setup.md
          - Working With Docker: setup/getting_started/working_with_docker.md
  - Testing:
      - Overview: testing/overview.md
      - Logs: testing/logs.md
      - Profiling: testing/profiling.md
      - Routine Complexity: testing/routine_complexity.md
  - Deployment:
      - Overview: deployment/overview.md
      - Single Server: deployment/single_server.md
      - Multiple Servers: deployment/multiple_servers.md
  - Guides:
      - Overview: guides/overview.md
      - Linting: guides/linting.md
      - Logo: guides/logo.md
      - Fonts: guides/fonts.md
      - UX Performance: guides/ui_performance.md
      - PWA and TWA: guides/pwa_and_twa.md
      - Income Streams: guides/income_streams.md
      - Database Design: design/database_design.md
      - Migrate: guides/migrate.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
plugins:
  - search
  - social
  - offline
  - macros
extra:
  repo_code: "https://github.com/Vrooli/Vrooli/tree/master"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Vrooli/Vrooli
      name: Source Code
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VrooliOfficial
      name: Follow us on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VyrDFzbmmF
      name: Join our Discord
    - icon: fontawesome/solid/envelope
      link: mailto:official@vrooli.com
      name: Email us
repo_name: Vrooli
repo_url: https://github.com/Vrooli/Vrooli
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js
