// Component contract only: synthetic capture replies and local routes; never
// publishes a real record. Real form/widgets/providers, all external offers forbidden.
import { act, fireEvent, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { Route, Routes, useLocation } from "react-router-dom";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import { renderWithProviders } from "../../test-utils";
import { defaultApiClient } from "../../lib/api-client";
import type { RecordCaptureInput, RecordCaptureResult, RecordItem } from "../../types";
import { RecordCaptureForm } from "./RecordCaptureForm";
const views: ReturnType<typeof renderWithProviders>[]=[];
let submit: ReturnType<typeof vi.fn>; let expected: RecordCaptureInput[];
function record(overrides:Partial<RecordItem>={}):RecordItem {return{id:"fixture-private-record",kind:"fix",scenario:"fixture-owner",trigger:"Owner trigger",approach:"Owner approach",ruledOut:["Owner alternative"],filesChanged:[],outcome:"partial",stub:false,draft:true,createdAt:"2026-10-06T00:00:00Z",...overrides};}
function result(disposition:"draft"|"published"="draft"):RecordCaptureResult {return{disposition,record:record({draft:disposition==="draft"}),accepted:{kind:"fix"},needs:disposition==="draft"?["trigger"]:[],invalid:[],warnings:disposition==="draft"?["Fixture remains private"]:[],nextAction:[]};}
const payload:RecordCaptureInput={kind:"fix",scenario:"fixture-owner",trigger:"Fixture trigger",approach:"Fixture approach",evidence:"Fixture evidence",ruledOut:["Alternative one","Alternative two"],outcome:"partial"};
function Location(){const l=useLocation();return <output data-testid="capture-contract-location">{l.pathname}{l.search}</output>;}
function mount(value?:RecordItem){const view=renderWithProviders(<><Routes><Route path="/capture" element={<RecordCaptureForm record={value} onSubmit={submit}/>}/><Route path="/records/:id" element={<h1>Local record destination</h1>}/></Routes><Location/></>,{initialEntries:["/capture"]});views.push(view);return view;}
function change(name:string,value:string){fireEvent.change(screen.getByTestId(`record-capture-${name}`),{target:{value}});}
function fill(){change("kind","fix");change("outcome","partial");change("scenario","  fixture-owner  ");change("trigger"," Fixture trigger ");change("approach"," Fixture approach ");change("evidence"," Fixture evidence ");change("ruled-out"," Alternative one \n\n Alternative two \n ");}
function click(){fireEvent.click(screen.getByTestId("record-capture-submit"));}
beforeEach(()=>{expected=[];submit=vi.fn().mockResolvedValue(result());for(const method of ["get","post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error(`Forbidden record ${method}`));vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("Forbidden direct record transport")));});
afterEach(()=>{views.splice(0).forEach(v=>v.unmount());getSpatialNav()?.dispose();try{expect(submit.mock.calls).toEqual(expected.map(p=>[p]));for(const method of ["get","post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();}finally{vi.restoreAllMocks();vi.unstubAllGlobals();}});
describe("record capture progressive owner contract",()=>{
 it("keeps unsent intake local, including multiline alternatives, before explicit submission",()=>{mount();fill();expect(screen.getByTestId("record-capture-scenario")).toHaveValue("  fixture-owner  ");expect(screen.getByTestId("record-capture-ruled-out")).toHaveValue(" Alternative one \n\n Alternative two \n ");expect(screen.queryByTestId("record-capture-disposition")).toBeNull();});
 it("submits all trimmed fields and normalized alternatives exactly once and presents exact owner repair guidance",async()=>{const reply=result();reply.invalid=[{field:"outcome",value:"partial",message:"Fixture owner requires a complete disposition"}];reply.needs=["evidence","outcome"];submit.mockResolvedValue(reply);mount();fill();expected=[payload];click();await waitFor(()=>expect(screen.getByTestId("record-capture-disposition")).toHaveTextContent("Private draft saved"));expect(screen.getByText("Fixture owner requires a complete disposition")).toBeVisible();expect(screen.getByTestId("record-capture-disposition")).toHaveTextContent("evidence, outcome");expect(screen.getByTestId("record-capture-disposition")).toHaveTextContent("Fixture remains private");expect(screen.getByTestId("record-capture-open")).toHaveAttribute("href","/records/fixture-private-record");});
 it("permits deliberately incomplete intake rather than inventing client-required fields",async()=>{mount();expected=[{kind:"",scenario:"",trigger:"",approach:"",evidence:undefined,ruledOut:[],outcome:""}];click();await waitFor(()=>expect(screen.getByTestId("record-capture-disposition")).toHaveTextContent("Private draft saved"));expect(screen.getByTestId("record-capture-scenario")).toHaveValue("");});
 it("omits whitespace-only evidence while preserving a deliberate duplicate alternative as entered",async()=>{mount();fill();change("evidence"," \n ");change("ruled-out"," same \n same ");expected=[{...payload,evidence:undefined,ruledOut:["same","same"]}];click();await waitFor(()=>expect(submit).toHaveBeenCalledTimes(1));});
 it("uses protected draft raw fields and fallback metadata while retaining canonical alternatives",()=>{const draft=record({capture:{raw:{kind:"chore",scenario:"raw-owner",trigger:"raw trigger",approach:"raw approach",evidence:"raw evidence",outcome:"abandoned"}}});mount(draft);expect(screen.getByTestId("record-capture-kind")).toHaveValue("chore");expect(screen.getByTestId("record-capture-scenario")).toHaveValue("raw-owner");expect(screen.getByTestId("record-capture-outcome")).toHaveValue("abandoned");expect(screen.getByTestId("record-capture-ruled-out")).toHaveValue("Owner alternative");expect(screen.getByTestId("record-capture-disposition")).toHaveTextContent("Draft saved privately; it is not searchable or published.");expect(screen.getByTestId("record-capture-submit")).toHaveTextContent("Save repair");});
 it("holds one pending callback and keeps its exact original input while the submit control is disabled",async()=>{let release!:(r:RecordCaptureResult)=>void;submit.mockImplementation(()=>new Promise<RecordCaptureResult>(r=>{release=r;}));mount();fill();expected=[payload];click();expect(screen.getByTestId("record-capture-submit")).toBeDisabled();expect(screen.getByTestId("record-capture-submit")).toHaveTextContent("Saving…");click();expect(submit).toHaveBeenCalledTimes(1);await act(async()=>release(result()));expect(screen.getByTestId("record-capture-submit")).not.toBeDisabled();});
 it("retains the complete draft after refusal and retries only on a second explicit submit",async()=>{submit.mockRejectedValueOnce(new Error("Fixture capture refused")).mockResolvedValueOnce(result("published"));mount();fill();expected=[payload];click();expect(await screen.findByText("Fixture capture refused")).toBeVisible();expect(screen.getByTestId("record-capture-trigger")).toHaveValue(" Fixture trigger ");expect(screen.queryByTestId("record-capture-disposition")).toBeNull();expect(submit).toHaveBeenCalledTimes(1);expected=[payload,payload];click();await waitFor(()=>expect(screen.getByTestId("record-capture-disposition")).toHaveTextContent("Published"));expect(screen.queryByText("Fixture capture refused")).toBeNull();});
 it("shows a non-Error refusal without treating it as a publication",async()=>{submit.mockRejectedValue("Fixture typed refusal");mount();fill();expected=[payload];click();expect(await screen.findByText("Fixture typed refusal")).toBeVisible();expect(screen.queryByTestId("record-capture-disposition")).toBeNull();expect(screen.getByTestId("record-capture-submit")).not.toBeDisabled();});
 it("navigates only on the explicit synthetic published-record link",async()=>{submit.mockResolvedValue(result("published"));mount();fill();expected=[payload];click();await waitFor(()=>expect(screen.getByTestId("record-capture-disposition")).toHaveTextContent("Published"));expect(screen.getByTestId("capture-contract-location")).toHaveTextContent("/capture");fireEvent.click(screen.getByRole("link",{name:"Open published record"}));await screen.findByRole("heading",{name:"Local record destination"});expect(screen.getByTestId("capture-contract-location")).toHaveTextContent("/records/fixture-private-record");});
});
