-- Resource Improver Database Schema
-- Tables for tracking resource improvements, compliance, and health monitoring

-- Resource reports (issues found in resources)
CREATE TABLE IF NOT EXISTS resource_reports (
    id SERIAL PRIMARY KEY,
    resource_name VARCHAR(255) NOT NULL,
    issue_type VARCHAR(100) NOT NULL, -- v2-compliance, health-check, cli-enhancement, documentation
    description TEXT NOT NULL,
    context JSONB,
    severity VARCHAR(50) DEFAULT 'medium', -- critical, high, medium, low
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Improvement suggestions generated by AI analysis
CREATE TABLE IF NOT EXISTS improvement_suggestions (
    id SERIAL PRIMARY KEY,
    resource_report_id INTEGER REFERENCES resource_reports(id) ON DELETE CASCADE,
    suggestions JSONB NOT NULL, -- Array of suggestion strings
    confidence DECIMAL(3,2) DEFAULT 0.70, -- 0.00 to 1.00
    priority VARCHAR(50) DEFAULT 'medium', -- critical, high, medium, low
    estimated_time VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Resource metrics and compliance scores
CREATE TABLE IF NOT EXISTS resource_metrics (
    id SERIAL PRIMARY KEY,
    resource_name VARCHAR(255) NOT NULL UNIQUE,
    v2_compliance_score DECIMAL(5,2) DEFAULT 0.00, -- 0.00 to 100.00
    health_reliability DECIMAL(5,2) DEFAULT 0.00, -- 0.00 to 100.00
    cli_coverage DECIMAL(5,2) DEFAULT 0.00, -- 0.00 to 100.00
    doc_completeness DECIMAL(5,2) DEFAULT 0.00, -- 0.00 to 100.00
    status VARCHAR(50) DEFAULT 'unknown', -- excellent, good, needs-improvement, poor
    recommendations JSONB, -- Array of recommendation strings
    last_analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Queue items for improvement tasks
CREATE TABLE IF NOT EXISTS improvement_queue (
    id VARCHAR(255) PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type VARCHAR(100) NOT NULL, -- v2-compliance, health-check, cli-enhancement, documentation, fix
    target VARCHAR(255) NOT NULL, -- resource name
    priority VARCHAR(50) DEFAULT 'medium', -- critical, high, medium, low
    estimates JSONB, -- Priority scoring estimates
    status VARCHAR(50) DEFAULT 'pending', -- pending, in-progress, completed, failed
    created_by VARCHAR(100) DEFAULT 'system',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attempt_count INTEGER DEFAULT 0,
    last_attempt TIMESTAMP,
    failure_reasons JSONB -- Array of failure reason strings
);

-- Improvement results and outcomes
CREATE TABLE IF NOT EXISTS improvement_results (
    id SERIAL PRIMARY KEY,
    queue_item_id VARCHAR(255) REFERENCES improvement_queue(id) ON DELETE CASCADE,
    success BOOLEAN DEFAULT FALSE,
    changes JSONB, -- Array of files/changes made
    test_results JSONB, -- Array of test results
    metrics JSONB, -- Various metrics about the improvement
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    failure_reason TEXT
);

-- Validation results for improvements
CREATE TABLE IF NOT EXISTS validation_results (
    id SERIAL PRIMARY KEY,
    improvement_result_id INTEGER REFERENCES improvement_results(id) ON DELETE CASCADE,
    passed BOOLEAN DEFAULT FALSE,
    gates JSONB NOT NULL, -- Array of validation gate objects
    summary TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Available resources for improvement (discovered resources)
CREATE TABLE IF NOT EXISTS available_resources (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    description TEXT,
    path VARCHAR(500),
    current_compliance_score DECIMAL(5,2) DEFAULT 0.00,
    current_health_score DECIMAL(5,2) DEFAULT 0.00,
    improvement_friendly BOOLEAN DEFAULT TRUE,
    complexity_level VARCHAR(50) DEFAULT 'medium', -- simple, medium, complex
    last_improvement_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Memory storage for improvement patterns (local fallback for Qdrant)
CREATE TABLE IF NOT EXISTS improvement_memory (
    id SERIAL PRIMARY KEY,
    queue_item_id VARCHAR(255),
    resource_name VARCHAR(255),
    improvement_type VARCHAR(100),
    success BOOLEAN,
    changes TEXT,
    test_results TEXT,
    patterns JSONB, -- Extracted patterns for future use
    stored_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for better performance
CREATE INDEX IF NOT EXISTS idx_resource_reports_resource_name ON resource_reports(resource_name);
CREATE INDEX IF NOT EXISTS idx_resource_reports_severity ON resource_reports(severity);
CREATE INDEX IF NOT EXISTS idx_resource_reports_created_at ON resource_reports(created_at);

CREATE INDEX IF NOT EXISTS idx_resource_metrics_resource_name ON resource_metrics(resource_name);
CREATE INDEX IF NOT EXISTS idx_resource_metrics_v2_compliance ON resource_metrics(v2_compliance_score);
CREATE INDEX IF NOT EXISTS idx_resource_metrics_health_reliability ON resource_metrics(health_reliability);

CREATE INDEX IF NOT EXISTS idx_improvement_queue_status ON improvement_queue(status);
CREATE INDEX IF NOT EXISTS idx_improvement_queue_priority ON improvement_queue(priority);
CREATE INDEX IF NOT EXISTS idx_improvement_queue_target ON improvement_queue(target);
CREATE INDEX IF NOT EXISTS idx_improvement_queue_created_at ON improvement_queue(created_at);

CREATE INDEX IF NOT EXISTS idx_improvement_results_success ON improvement_results(success);
CREATE INDEX IF NOT EXISTS idx_improvement_results_completed_at ON improvement_results(completed_at);

CREATE INDEX IF NOT EXISTS idx_available_resources_name ON available_resources(name);
CREATE INDEX IF NOT EXISTS idx_available_resources_compliance ON available_resources(current_compliance_score);

CREATE INDEX IF NOT EXISTS idx_improvement_memory_resource_name ON improvement_memory(resource_name);
CREATE INDEX IF NOT EXISTS idx_improvement_memory_improvement_type ON improvement_memory(improvement_type);
CREATE INDEX IF NOT EXISTS idx_improvement_memory_success ON improvement_memory(success);

-- Update triggers to maintain updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_resource_reports_updated_at BEFORE UPDATE ON resource_reports FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_resource_metrics_updated_at BEFORE UPDATE ON resource_metrics FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_improvement_queue_updated_at BEFORE UPDATE ON improvement_queue FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_available_resources_updated_at BEFORE UPDATE ON available_resources FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();