// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $schema: "$schema",
  $text: "$text",
  "Access limited": "Access limited",
  "Changes saved successfully": {
    "": "Changes saved successfully.",
  },
  Collapse: "Collapse",
  "Content failed to load": {
    "": "Content failed to load.",
  },
  "Disabled states retain the same geometry and clearly communicate that the action is unavailable": {
    "": "Disabled states retain the same geometry and clearly communicate that the action is unavailable.",
  },
  M: "M",
  "Reconnect to refresh this view": {
    "": "Reconnect to refresh this view.",
  },
  "Request in progress": "Request in progress",
  Saved: "Saved",
  "Try again": "Try again",
  "Trying again…": "Trying again…",
  app: {
    description: "app.description",
    title: "app.title",
  },
  assertive: "assertive",
  asset: "asset",
  axis: "axis",
  background: "background",
  capability: "capability",
  children: "children",
  component: "component",
  componentId: "componentId",
  components: {
    asyncBoundary: {
      loadingContent: "components.asyncBoundary.loadingContent",
      loadingMoment: "components.asyncBoundary.loadingMoment",
    },
    chart: {
      caption: "components.chart.caption",
      kicker: "components.chart.kicker",
      period: "components.chart.period",
      value: "components.chart.value",
      valuesLabel: "components.chart.valuesLabel",
    },
  },
  "data-display": {
    "data-table": {
      "access-is-limited": "data-display.data-table.access-is-limited",
      all: "data-display.data-table.all",
      "data-table-content": "data-display.data-table.data-table-content",
      dense: "data-display.data-table.dense",
      next: "data-display.data-table.next",
      previous: "data-display.data-table.previous",
      roomy: "data-display.data-table.roomy",
      "row-density": "data-display.data-table.row-density",
    },
  },
  default: "default",
  desc: "desc",
  description: "description",
  detail: "detail",
  dialog: "dialog",
  en: "en",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  example: "example",
  export: "export",
  feedback: {
    "async-boundary": {
      "loading-content": "feedback.async-boundary.loading-content",
      "this-may-take-a-moment": "feedback.async-boundary.this-may-take-a-moment",
    },
  },
  fixture: "fixture",
  format: "format",
  forms: {
    "dirty-state-guard": {
      "leave-now-and-your-recent-edits-will-be-lost-sav": "forms.dirty-state-guard.leave-now-and-your-recent-edits-will-be-lost-sav",
      "saving-preserves-your-work-discarding-cannot-be-": "forms.dirty-state-guard.saving-preserves-your-work-discarding-cannot-be-",
      "you-have-unsaved-changes": "forms.dirty-state-guard.you-have-unsaved-changes",
    },
  },
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    statusLabel: "health.statusLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  iconName: "iconName",
  id: "id",
  issue: "issue",
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      journal: "layout.nav.journal",
      settings: "layout.nav.settings",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  "lucide-react": "lucide-react",
  measured: "measured",
  mode: "mode",
  module: "module",
  name: "name",
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  online: "online",
  pages: {
    accounts: {
      acceptedKinds: "pages.accounts.acceptedKinds",
      accountKindLabel: "pages.accounts.accountKindLabel",
      accountLabel: "pages.accounts.accountLabel",
      accountNameLabel: "pages.accounts.accountNameLabel",
      archiveBookAction: "pages.accounts.archiveBookAction",
      archivedBookNotice: "pages.accounts.archivedBookNotice",
      balanceBasis: "pages.accounts.balanceBasis",
      balanceGap: "pages.accounts.balanceGap",
      balanceLabel: "pages.accounts.balanceLabel",
      balanceUnavailable: "pages.accounts.balanceUnavailable",
      basisLabel: "pages.accounts.basisLabel",
      bookNameLabel: "pages.accounts.bookNameLabel",
      cardTitle: "pages.accounts.cardTitle",
      createAccountAction: "pages.accounts.createAccountAction",
      createAccountTitle: "pages.accounts.createAccountTitle",
      createBookAction: "pages.accounts.createBookAction",
      createBookTitle: "pages.accounts.createBookTitle",
      currencyLabel: "pages.accounts.currencyLabel",
      description: "pages.accounts.description",
      emptyGuidance: "pages.accounts.emptyGuidance",
      fromAccountLabel: "pages.accounts.fromAccountLabel",
      kindLabel: "pages.accounts.kindLabel",
      requestError: "pages.accounts.requestError",
      savedNotice: "pages.accounts.savedNotice",
      selectBook: "pages.accounts.selectBook",
      title: "pages.accounts.title",
      toAccountLabel: "pages.accounts.toAccountLabel",
      transferAction: "pages.accounts.transferAction",
      transferAmountLabel: "pages.accounts.transferAmountLabel",
      transferDescriptionLabel: "pages.accounts.transferDescriptionLabel",
      transferPair: "pages.accounts.transferPair",
      transferTitle: "pages.accounts.transferTitle",
      validationError: "pages.accounts.validationError",
    },
    adapters: {
      absentUntilSupplied: "pages.adapters.absentUntilSupplied",
      adapterIdLabel: "pages.adapters.adapterIdLabel",
      adapterKindLabel: "pages.adapters.adapterKindLabel",
      adapterNameLabel: "pages.adapters.adapterNameLabel",
      aggregatorKind: "pages.adapters.aggregatorKind",
      applyReviewedImport: "pages.adapters.applyReviewedImport",
      availabilityReason: "pages.adapters.availabilityReason",
      available: "pages.adapters.available",
      cardTitle: "pages.adapters.cardTitle",
      credentialGap: "pages.adapters.credentialGap",
      derivedRateRefusal: "pages.adapters.derivedRateRefusal",
      description: "pages.adapters.description",
      emptyGuidance: "pages.adapters.emptyGuidance",
      failureReason: "pages.adapters.failureReason",
      field: "pages.adapters.field",
      fileKind: "pages.adapters.fileKind",
      fileLabel: "pages.adapters.fileLabel",
      importTitle: "pages.adapters.importTitle",
      lastSuccess: "pages.adapters.lastSuccess",
      lastSuccessAge: "pages.adapters.lastSuccessAge",
      manualAdapter: "pages.adapters.manualAdapter",
      missingImpact: "pages.adapters.missingImpact",
      neverRun: "pages.adapters.neverRun",
      observed: "pages.adapters.observed",
      operatorInputDescription: "pages.adapters.operatorInputDescription",
      operatorInputStatusCaption: "pages.adapters.operatorInputStatusCaption",
      operatorInputTitle: "pages.adapters.operatorInputTitle",
      previewImport: "pages.adapters.previewImport",
      reason: "pages.adapters.reason",
      registerAction: "pages.adapters.registerAction",
      registerTitle: "pages.adapters.registerTitle",
      reportTitle: "pages.adapters.reportTitle",
      requestError: "pages.adapters.requestError",
      runAction: "pages.adapters.runAction",
      savedNotice: "pages.adapters.savedNotice",
      status: "pages.adapters.status",
      title: "pages.adapters.title",
      unavailable: "pages.adapters.unavailable",
      written: "pages.adapters.written",
    },
    dashboard: {
      availabilityAge: "pages.dashboard.availabilityAge",
      changeDescription: "pages.dashboard.changeDescription",
      changeTitle: "pages.dashboard.changeTitle",
      changeUnavailable: "pages.dashboard.changeUnavailable",
      complete: "pages.dashboard.complete",
      completenessLabel: "pages.dashboard.completenessLabel",
      declareGoalTitle: "pages.dashboard.declareGoalTitle",
      description: "pages.dashboard.description",
      emptyGuidance: "pages.dashboard.emptyGuidance",
      goalComparatorLabel: "pages.dashboard.goalComparatorLabel",
      goalCreateAction: "pages.dashboard.goalCreateAction",
      goalMetricLabel: "pages.dashboard.goalMetricLabel",
      goalName: "pages.dashboard.goalName",
      goalNameLabel: "pages.dashboard.goalNameLabel",
      goalPeriod: "pages.dashboard.goalPeriod",
      goalPeriodUnitLabel: "pages.dashboard.goalPeriodUnitLabel",
      goalProgress: "pages.dashboard.goalProgress",
      goalSustainPeriodsLabel: "pages.dashboard.goalSustainPeriodsLabel",
      goalThreshold: "pages.dashboard.goalThreshold",
      goalThresholdLabel: "pages.dashboard.goalThresholdLabel",
      goalVerdictMet: "pages.dashboard.goalVerdictMet",
      goalVerdictUnmet: "pages.dashboard.goalVerdictUnmet",
      goalsDescription: "pages.dashboard.goalsDescription",
      goalsTitle: "pages.dashboard.goalsTitle",
      missingAdapter: "pages.dashboard.missingAdapter",
      notConfigured: "pages.dashboard.notConfigured",
      partial: "pages.dashboard.partial",
      positionUnavailable: "pages.dashboard.positionUnavailable",
      requestError: "pages.dashboard.requestError",
      runwayBasis: "pages.dashboard.runwayBasis",
      runwayLabel: "pages.dashboard.runwayLabel",
      runwayMonths: "pages.dashboard.runwayMonths",
      runwayUndefined: "pages.dashboard.runwayUndefined",
      savedNotice: "pages.dashboard.savedNotice",
      sourceUnavailable: "pages.dashboard.sourceUnavailable",
      title: "pages.dashboard.title",
      trendBasisAuthoritative: "pages.dashboard.trendBasisAuthoritative",
      trendBasisDerived: "pages.dashboard.trendBasisDerived",
      trendBasisMixed: "pages.dashboard.trendBasisMixed",
      trendBasisOperator: "pages.dashboard.trendBasisOperator",
      trendDescription: "pages.dashboard.trendDescription",
      trendEmpty: "pages.dashboard.trendEmpty",
      trendGap: "pages.dashboard.trendGap",
      trendGapLabel: "pages.dashboard.trendGapLabel",
      trendInflow: "pages.dashboard.trendInflow",
      trendNet: "pages.dashboard.trendNet",
      trendNoPostings: "pages.dashboard.trendNoPostings",
      trendOutflow: "pages.dashboard.trendOutflow",
      trendPeriod: "pages.dashboard.trendPeriod",
      trendSourceBasis: "pages.dashboard.trendSourceBasis",
      trendStale: "pages.dashboard.trendStale",
      trendTableCaption: "pages.dashboard.trendTableCaption",
      trendTitle: "pages.dashboard.trendTitle",
      trendUnavailable: "pages.dashboard.trendUnavailable",
      trendWindowDays: "pages.dashboard.trendWindowDays",
      trendWindowLabel: "pages.dashboard.trendWindowLabel",
      validationError: "pages.dashboard.validationError",
    },
    journal: {
      accountLabel: "pages.journal.accountLabel",
      amountLabel: "pages.journal.amountLabel",
      auditTrail: "pages.journal.auditTrail",
      basisLabel: "pages.journal.basisLabel",
      cancel: "pages.journal.cancel",
      cardTitle: "pages.journal.cardTitle",
      confirmReversal: "pages.journal.confirmReversal",
      currencyLabel: "pages.journal.currencyLabel",
      dateLabel: "pages.journal.dateLabel",
      description: "pages.journal.description",
      descriptionLabel: "pages.journal.descriptionLabel",
      duplicateNotice: "pages.journal.duplicateNotice",
      emptyGuidance: "pages.journal.emptyGuidance",
      eventBasis: "pages.journal.eventBasis",
      eventSource: "pages.journal.eventSource",
      externalIdLabel: "pages.journal.externalIdLabel",
      linkedReversal: "pages.journal.linkedReversal",
      manualEntry: "pages.journal.manualEntry",
      noAudit: "pages.journal.noAudit",
      postingAccount: "pages.journal.postingAccount",
      postingBasis: "pages.journal.postingBasis",
      postingCurrency: "pages.journal.postingCurrency",
      postingDate: "pages.journal.postingDate",
      requestError: "pages.journal.requestError",
      reversalDialogDescription: "pages.journal.reversalDialogDescription",
      reversalDialogTitle: "pages.journal.reversalDialogTitle",
      reversalLink: "pages.journal.reversalLink",
      reversalReason: "pages.journal.reversalReason",
      reversalReasonLabel: "pages.journal.reversalReasonLabel",
      reverseAction: "pages.journal.reverseAction",
      savedNotice: "pages.journal.savedNotice",
      signedAmountLabel: "pages.journal.signedAmountLabel",
      sourceLabel: "pages.journal.sourceLabel",
      submitEntry: "pages.journal.submitEntry",
      title: "pages.journal.title",
      validationError: "pages.journal.validationError",
    },
    settings: {
      archiveGoal: "pages.settings.archiveGoal",
      currencyDisplay: "pages.settings.currencyDisplay",
      defaultBook: "pages.settings.defaultBook",
      goalBuffer: "pages.settings.goalBuffer",
      goalDescription: "pages.settings.goalDescription",
      goalSummary: "pages.settings.goalSummary",
      goalSustainWindow: "pages.settings.goalSustainWindow",
      goalThreshold: "pages.settings.goalThreshold",
      goalsEmpty: "pages.settings.goalsEmpty",
      goalsHeading: "pages.settings.goalsHeading",
      localeHeading: "pages.settings.localeHeading",
      moveGoal: "pages.settings.moveGoal",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
    statements: {
      applyPeriod: "pages.statements.applyPeriod",
      assets: "pages.statements.assets",
      availability: "pages.statements.availability",
      cardTitle: "pages.statements.cardTitle",
      categoryBreakdown: "pages.statements.categoryBreakdown",
      closingCash: "pages.statements.closingCash",
      coverageNote: "pages.statements.coverageNote",
      description: "pages.statements.description",
      emptyGuidance: "pages.statements.emptyGuidance",
      expense: "pages.statements.expense",
      exportAction: "pages.statements.exportAction",
      exportError: "pages.statements.exportError",
      exported: "pages.statements.exported",
      fromLabel: "pages.statements.fromLabel",
      inflow: "pages.statements.inflow",
      liabilities: "pages.statements.liabilities",
      notTaxAdvice: "pages.statements.notTaxAdvice",
      openingCash: "pages.statements.openingCash",
      outflow: "pages.statements.outflow",
      periodSelector: "pages.statements.periodSelector",
      revenue: "pages.statements.revenue",
      title: "pages.statements.title",
      toLabel: "pages.statements.toLabel",
      uncategorisedCount: "pages.statements.uncategorisedCount",
      uncategorisedNotReported: "pages.statements.uncategorisedNotReported",
    },
  },
  path: "path",
  provenance: "provenance",
  purpose: "purpose",
  react: "react",
  "react-component-library:useEscapeKey": "react-component-library:useEscapeKey",
  ref: "ref",
  region: "region",
  resolvedAt: "resolvedAt",
  role: "role",
  schema: "schema",
  schemaVersion: "schemaVersion",
  selector: "selector",
  size: "size",
  state: "state",
  statement: "statement",
  status: "status",
  storyRef: "storyRef",
  testid: "testid",
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  tier: "tier",
  title: "title",
  tone: "tone",
  true: "true",
  type: "type",
  value: "value",
  variant: "variant",
  version: "version",
  visualization: {
    "cartesian-charts": {
      title: "visualization.cartesian-charts.title",
    },
    chart: {
      "chart-values": "visualization.chart.chart-values",
      "explore-the-trend-and-select-a-point-for-its-exa": "visualization.chart.explore-the-trend-and-select-a-point-for-its-exa",
      "performance-overview": "visualization.chart.performance-overview",
      period: "visualization.chart.period",
      value: "visualization.chart.value",
    },
  },
  "↑": "↑",
  "⌃": "⌃",
} as const;

export type Strings = typeof strings;
