// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    description: "app.description",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      journal: "layout.nav.journal",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      runwayLabel: "pages.dashboard.runwayLabel",
      runwayMonths: "pages.dashboard.runwayMonths",
      runwayUndefined: "pages.dashboard.runwayUndefined",
      runwayBasis: "pages.dashboard.runwayBasis",
      completenessLabel: "pages.dashboard.completenessLabel",
      partial: "pages.dashboard.partial",
      complete: "pages.dashboard.complete",
      notConfigured: "pages.dashboard.notConfigured",
      missingAdapter: "pages.dashboard.missingAdapter",
      positionUnavailable: "pages.dashboard.positionUnavailable",
      sourceUnavailable: "pages.dashboard.sourceUnavailable",
      emptyGuidance: "pages.dashboard.emptyGuidance",
      goalsTitle: "pages.dashboard.goalsTitle",
      goalsDescription: "pages.dashboard.goalsDescription",
      changeTitle: "pages.dashboard.changeTitle",
      changeDescription: "pages.dashboard.changeDescription",
      changeUnavailable: "pages.dashboard.changeUnavailable",
      goalName: "pages.dashboard.goalName",
      goalThreshold: "pages.dashboard.goalThreshold",
      goalProgress: "pages.dashboard.goalProgress",
      goalVerdictMet: "pages.dashboard.goalVerdictMet",
      goalVerdictUnmet: "pages.dashboard.goalVerdictUnmet",
      goalPeriod: "pages.dashboard.goalPeriod",
      declareGoalTitle: "pages.dashboard.declareGoalTitle",
      goalNameLabel: "pages.dashboard.goalNameLabel",
      goalMetricLabel: "pages.dashboard.goalMetricLabel",
      goalComparatorLabel: "pages.dashboard.goalComparatorLabel",
      goalThresholdLabel: "pages.dashboard.goalThresholdLabel",
      goalSustainPeriodsLabel: "pages.dashboard.goalSustainPeriodsLabel",
      goalPeriodUnitLabel: "pages.dashboard.goalPeriodUnitLabel",
      goalCreateAction: "pages.dashboard.goalCreateAction",
      savedNotice: "pages.dashboard.savedNotice",
      validationError: "pages.dashboard.validationError",
      requestError: "pages.dashboard.requestError",
      availabilityAge: "pages.dashboard.availabilityAge",
      trendTitle: "pages.dashboard.trendTitle",
      trendDescription: "pages.dashboard.trendDescription",
      trendWindowLabel: "pages.dashboard.trendWindowLabel",
      trendWindowDays: "pages.dashboard.trendWindowDays",
      trendInflow: "pages.dashboard.trendInflow",
      trendOutflow: "pages.dashboard.trendOutflow",
      trendNet: "pages.dashboard.trendNet",
      trendSourceBasis: "pages.dashboard.trendSourceBasis",
      trendBasisMixed: "pages.dashboard.trendBasisMixed",
      trendEmpty: "pages.dashboard.trendEmpty",
      trendGap: "pages.dashboard.trendGap",
      trendGapLabel: "pages.dashboard.trendGapLabel",
      trendTableCaption: "pages.dashboard.trendTableCaption",
      trendPeriod: "pages.dashboard.trendPeriod",
      trendUnavailable: "pages.dashboard.trendUnavailable",
      trendNoPostings: "pages.dashboard.trendNoPostings",
      trendStale: "pages.dashboard.trendStale",
      trendBasisOperator: "pages.dashboard.trendBasisOperator",
      trendBasisAuthoritative: "pages.dashboard.trendBasisAuthoritative",
      trendBasisDerived: "pages.dashboard.trendBasisDerived",
    },
    journal: {
      title: "pages.journal.title",
      cardTitle: "pages.journal.cardTitle",
      description: "pages.journal.description",
      eventBasis: "pages.journal.eventBasis",
      eventSource: "pages.journal.eventSource",
      reversalLink: "pages.journal.reversalLink",
      reversalReason: "pages.journal.reversalReason",
      auditTrail: "pages.journal.auditTrail",
      manualEntry: "pages.journal.manualEntry",
      dateLabel: "pages.journal.dateLabel",
      accountLabel: "pages.journal.accountLabel",
      signedAmountLabel: "pages.journal.signedAmountLabel",
      currencyLabel: "pages.journal.currencyLabel",
      basisLabel: "pages.journal.basisLabel",
      sourceLabel: "pages.journal.sourceLabel",
      descriptionLabel: "pages.journal.descriptionLabel",
      amountLabel: "pages.journal.amountLabel",
      externalIdLabel: "pages.journal.externalIdLabel",
      submitEntry: "pages.journal.submitEntry",
      duplicateNotice: "pages.journal.duplicateNotice",
      savedNotice: "pages.journal.savedNotice",
      validationError: "pages.journal.validationError",
      requestError: "pages.journal.requestError",
      reverseAction: "pages.journal.reverseAction",
      reversalDialogTitle: "pages.journal.reversalDialogTitle",
      reversalDialogDescription: "pages.journal.reversalDialogDescription",
      reversalReasonLabel: "pages.journal.reversalReasonLabel",
      confirmReversal: "pages.journal.confirmReversal",
      cancel: "pages.journal.cancel",
      postingDate: "pages.journal.postingDate",
      postingAccount: "pages.journal.postingAccount",
      postingCurrency: "pages.journal.postingCurrency",
      postingBasis: "pages.journal.postingBasis",
      linkedReversal: "pages.journal.linkedReversal",
      noAudit: "pages.journal.noAudit",
      emptyGuidance: "pages.journal.emptyGuidance",
    },
    accounts: {
      title: "pages.accounts.title",
      cardTitle: "pages.accounts.cardTitle",
      description: "pages.accounts.description",
      balanceBasis: "pages.accounts.balanceBasis",
      balanceGap: "pages.accounts.balanceGap",
      transferPair: "pages.accounts.transferPair",
      accountLabel: "pages.accounts.accountLabel",
      kindLabel: "pages.accounts.kindLabel",
      balanceLabel: "pages.accounts.balanceLabel",
      basisLabel: "pages.accounts.basisLabel",
      createBookTitle: "pages.accounts.createBookTitle",
      bookNameLabel: "pages.accounts.bookNameLabel",
      currencyLabel: "pages.accounts.currencyLabel",
      createBookAction: "pages.accounts.createBookAction",
      createAccountTitle: "pages.accounts.createAccountTitle",
      accountNameLabel: "pages.accounts.accountNameLabel",
      accountKindLabel: "pages.accounts.accountKindLabel",
      selectBook: "pages.accounts.selectBook",
      createAccountAction: "pages.accounts.createAccountAction",
      transferTitle: "pages.accounts.transferTitle",
      fromAccountLabel: "pages.accounts.fromAccountLabel",
      toAccountLabel: "pages.accounts.toAccountLabel",
      transferAmountLabel: "pages.accounts.transferAmountLabel",
      transferDescriptionLabel: "pages.accounts.transferDescriptionLabel",
      transferAction: "pages.accounts.transferAction",
      savedNotice: "pages.accounts.savedNotice",
      validationError: "pages.accounts.validationError",
      requestError: "pages.accounts.requestError",
      balanceUnavailable: "pages.accounts.balanceUnavailable",
      emptyGuidance: "pages.accounts.emptyGuidance",
      archiveBookAction: "pages.accounts.archiveBookAction",
      archivedBookNotice: "pages.accounts.archivedBookNotice",
      acceptedKinds: "pages.accounts.acceptedKinds",
    },
    adapters: {
      title: "pages.adapters.title",
      cardTitle: "pages.adapters.cardTitle",
      description: "pages.adapters.description",
      manualAdapter: "pages.adapters.manualAdapter",
      available: "pages.adapters.available",
      neverRun: "pages.adapters.neverRun",
      unavailable: "pages.adapters.unavailable",
      failureReason: "pages.adapters.failureReason",
      lastSuccessAge: "pages.adapters.lastSuccessAge",
      missingImpact: "pages.adapters.missingImpact",
      credentialGap: "pages.adapters.credentialGap",
      emptyGuidance: "pages.adapters.emptyGuidance",
      registerTitle: "pages.adapters.registerTitle",
      adapterIdLabel: "pages.adapters.adapterIdLabel",
      adapterNameLabel: "pages.adapters.adapterNameLabel",
      adapterKindLabel: "pages.adapters.adapterKindLabel",
      registerAction: "pages.adapters.registerAction",
      runAction: "pages.adapters.runAction",
      importTitle: "pages.adapters.importTitle",
      fileLabel: "pages.adapters.fileLabel",
      savedNotice: "pages.adapters.savedNotice",
      requestError: "pages.adapters.requestError",
      lastSuccess: "pages.adapters.lastSuccess",
      availabilityReason: "pages.adapters.availabilityReason",
      fileKind: "pages.adapters.fileKind",
      aggregatorKind: "pages.adapters.aggregatorKind",
      operatorInputTitle: "pages.adapters.operatorInputTitle",
      operatorInputDescription: "pages.adapters.operatorInputDescription",
      operatorInputStatusCaption: "pages.adapters.operatorInputStatusCaption",
      field: "pages.adapters.field",
      status: "pages.adapters.status",
      observed: "pages.adapters.observed",
      reason: "pages.adapters.reason",
      absentUntilSupplied: "pages.adapters.absentUntilSupplied",
      derivedRateRefusal: "pages.adapters.derivedRateRefusal",
      previewImport: "pages.adapters.previewImport",
      applyReviewedImport: "pages.adapters.applyReviewedImport",
      reportTitle: "pages.adapters.reportTitle",
      written: "pages.adapters.written",
    },
    statements: {
      title: "pages.statements.title",
      cardTitle: "pages.statements.cardTitle",
      description: "pages.statements.description",
      periodSelector: "pages.statements.periodSelector",
      fromLabel: "pages.statements.fromLabel",
      toLabel: "pages.statements.toLabel",
      applyPeriod: "pages.statements.applyPeriod",
      coverageNote: "pages.statements.coverageNote",
      categoryBreakdown: "pages.statements.categoryBreakdown",
      uncategorisedCount: "pages.statements.uncategorisedCount",
      uncategorisedNotReported: "pages.statements.uncategorisedNotReported",
      notTaxAdvice: "pages.statements.notTaxAdvice",
      exportAction: "pages.statements.exportAction",
      exported: "pages.statements.exported",
      exportError: "pages.statements.exportError",
      openingCash: "pages.statements.openingCash",
      inflow: "pages.statements.inflow",
      outflow: "pages.statements.outflow",
      closingCash: "pages.statements.closingCash",
      revenue: "pages.statements.revenue",
      expense: "pages.statements.expense",
      assets: "pages.statements.assets",
      liabilities: "pages.statements.liabilities",
      availability: "pages.statements.availability",
      emptyGuidance: "pages.statements.emptyGuidance",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      goalsHeading: "pages.settings.goalsHeading",
      goalDescription: "pages.settings.goalDescription",
      goalThreshold: "pages.settings.goalThreshold",
      goalSustainWindow: "pages.settings.goalSustainWindow",
      goalBuffer: "pages.settings.goalBuffer",
      goalSummary: "pages.settings.goalSummary",
      goalsEmpty: "pages.settings.goalsEmpty",
      defaultBook: "pages.settings.defaultBook",
      currencyDisplay: "pages.settings.currencyDisplay",
      archiveGoal: "pages.settings.archiveGoal",
      moveGoal: "pages.settings.moveGoal",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  components: {
    asyncBoundary: {
      loadingContent: "components.asyncBoundary.loadingContent",
      loadingMoment: "components.asyncBoundary.loadingMoment",
    },
    chart: {
      kicker: "components.chart.kicker",
      valuesLabel: "components.chart.valuesLabel",
      caption: "components.chart.caption",
      period: "components.chart.period",
      value: "components.chart.value",
    },
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
