import { act, cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import { useLocation } from "react-router-dom";
import type { QueryClient } from "@tanstack/react-query";
import { createTestQueryClient, renderWithProviders } from "../../../test-utils";
import { backlogStoreInitialState, useBacklogStore } from "../../../stores/backlog-store";
import { FocusActionsSection } from "./FocusActionsSection";
import type { BacklogGraphNodeData, CaptureGraphNodeData, ExecutionGraphNodeData, GraphNodeData } from "../types";
const backlog:BacklogGraphNodeData={label:"Fixture backlog",entityType:"backlog",rawType:"BacklogItem",kind:"fix",name:"fixture-backlog",title:"Fixture backlog",status:"ready",priority:2};
function execution(status:ExecutionGraphNodeData["status"]):ExecutionGraphNodeData{return{label:"Fixture execution",entityType:"execution",rawType:"ExecutionRecord",executionId:"fixture-execution",backlogKind:"fix",backlogName:"fixture-backlog",status,mode:"manual"};}
function capture(status:CaptureGraphNodeData["status"]):CaptureGraphNodeData{return{label:"Fixture capture",entityType:"capture",rawType:"Capture",id:"fixture-capture",text:"Fixture capture",status};}
let action:string;let enabled:boolean;let calls:{method:string;path:string;body:unknown}[];let unexpected:string[];let replies:Map<string,()=>Response|Promise<Response>>;const clients:QueryClient[]=[];
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
function Location(){const l=useLocation();return <output data-testid="fixture-location">{l.pathname+l.search}</output>;}
function mount(data:GraphNodeData=backlog,nodeId="backlog-item/fix/fixture-backlog"){const client=createTestQueryClient();clients.push(client);return{client,...renderWithProviders(<><Location/><FocusActionsSection nodeData={data} nodeId={nodeId}/></>,{queryClient:client,initialEntries:["/graph"]})};}
function effects(){return calls.filter(c=>c.method!=="GET"&&!c.path.endsWith("/ListTransitions"));}
beforeEach(()=>{action="author_plan";enabled=true;calls=[];unexpected=[];useBacklogStore.setState({...backlogStoreInitialState,blockingMap:{}});replies=new Map([["GET /backlog/fix/fixture-backlog/next-action",()=>json({action:{id:action,compact_label:"Fixture action",expanded_label:"Fixture action",enabled,blockers:[]}})],["GET /backlog/summary",()=>json({pending_questions:{items:[]}})],["GET /backlog",()=>json({items:[],blocking:{}})],["GET /execution/strategies",()=>json({items:[{id:"sliced",workflow_key:"fixture",display_name:"Fixture slices",description:"Fixture only",when_to_use:"Fixture only",cost_band:"fixture",cost_estimate:0}]})],["GET /execution-options",()=>json({options:[]})]]);vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const request=new Request(input,init);const path=new URL(request.url).pathname.replace(/^\/api\/v1/,"");const body=request.body?JSON.parse(await request.text()):undefined;calls.push({method:request.method,path,body});if(path.endsWith("/ListTransitions"))return json({transitions:[{key:"capture.classify",label:"Classify",subject:"capture",kind:"TRANSITION_KIND_WORKFLOW"}]});const key=request.method+" "+path;if(!replies.has(key)){unexpected.push(key);throw new Error("Unexpected fixture request "+key);}return replies.get(key)!();}));});
afterEach(()=>{cleanup();getSpatialNav()?.dispose();clients.splice(0).forEach(c=>c.clear());useBacklogStore.setState({...backlogStoreInitialState,blockingMap:{}});vi.unstubAllGlobals();vi.restoreAllMocks();expect(unexpected).toEqual([]);});
describe("real graph focus owner network workflows",()=>{
 it.each(["author_plan","accept_plan","repair_plan","review","resolve_dependencies","view_execution"])("navigates exact backlog owner for declared %s without issuing a mutation",async next=>{action=next;mount();fireEvent.click(await screen.findByTestId("focus-cta-button"));await waitFor(()=>expect(screen.getByTestId("fixture-location")).toHaveTextContent("/backlog/fix/fixture-backlog"));expect(effects()).toEqual([]);});
 it("honors an explicitly disabled server projection without navigation or effects",async()=>{enabled=false;mount();const cta=await screen.findByTestId("focus-cta-button");expect(cta).toBeDisabled();fireEvent.click(cta);expect(screen.getByTestId("fixture-location")).toHaveTextContent("/graph");expect(effects()).toEqual([]);});
 it("does not invent an action when authoritative projection declares none",async()=>{action="none";mount();await waitFor(()=>expect(calls.some(c=>c.path.endsWith("/next-action"))).toBe(true));expect(screen.queryByTestId("focus-cta-button")).toBeNull();expect(effects()).toEqual([]);});
 it("previews only the exact backlog owner unconfirmed and cancels the real sheet",async()=>{action="run";replies.set("POST /backlog/fix/fixture-backlog/queue",()=>json({item:{kind:"fix",name:"fixture-backlog",title:"Fixture backlog",status:"ready",priority:2,created:"2026-10-05T00:00:00Z",updated:"2026-10-05T00:00:00Z"},dryRun:true,queued:false,blockingReasons:[]}));mount();fireEvent.click(await screen.findByTestId("focus-cta-button"));const sheet=await screen.findByTestId("run-sheet");await waitFor(()=>expect(effects()).toHaveLength(1));expect(effects()[0]).toMatchObject({method:"POST",path:"/backlog/fix/fixture-backlog/queue",body:{confirm:false}});fireEvent.click(within(sheet).getByRole("button",{name:"Cancel"}));await waitFor(()=>expect(screen.queryByTestId("run-sheet")).toBeNull());expect(effects()).toHaveLength(1);});
 it("retries the projected backlog owner through its dedicated adapter rather than treating a backlog ID as an execution ID",async()=>{action="retry";replies.set("POST /backlog/fix/fixture-backlog/retry",()=>json({}));mount();fireEvent.click(await screen.findByTestId("focus-cta-button"));await waitFor(()=>expect(effects()).toEqual([{method:"POST",path:"/backlog/fix/fixture-backlog/retry",body:{}}]));await waitFor(()=>expect(calls.some(c=>c.path==="/backlog")).toBe(true));});
 it("holds one exact archive pending then refreshes canonical backlog only after owner completion",async()=>{action="archive";let finish!:(value:Response)=>void;replies.set("PATCH /backlog/fix/fixture-backlog/archive-item",()=>new Promise(r=>{finish=r;}));mount();fireEvent.click(await screen.findByTestId("focus-cta-button"));await waitFor(()=>expect(effects()).toHaveLength(1));await waitFor(()=>expect(screen.getByTestId("focus-cta-button")).toBeDisabled());fireEvent.click(screen.getByTestId("focus-cta-button"));expect(effects()).toEqual([{method:"PATCH",path:"/backlog/fix/fixture-backlog/archive-item",body:{}}]);expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);await act(async()=>finish(json({})));await waitFor(()=>expect(calls.some(c=>c.path==="/backlog")).toBe(true));expect(effects()).toHaveLength(1);});
 it("keeps archive refusal visible without refreshing, retrying or switching target",async()=>{action="archive";replies.set("PATCH /backlog/fix/fixture-backlog/archive-item",()=>json({message:"Fixture archive refused"},422));mount();fireEvent.click(await screen.findByTestId("focus-cta-button"));expect(await screen.findByText("Fixture archive refused")).toBeVisible();expect(effects()).toHaveLength(1);expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);});
 it("opens exact execution review without writing or inventing a different owner",async()=>{mount(execution("needs_review"));fireEvent.click(screen.getByTestId("focus-review-button"));await waitFor(()=>expect(screen.getByTestId("fixture-location")).toHaveTextContent("/executions/fixture-execution"));expect(effects()).toEqual([]);});
 it.each(["completed","needs_fixup"] as const)("runs checks for %s on one exact fixture execution",async status=>{replies.set("POST /execution/fixture-execution/trigger-review",()=>json({}));const {client}=mount(execution(status));client.setQueryDefaults(["execution","fixture-execution"],{gcTime:Infinity});client.setQueryData(["execution","fixture-execution"],{fixture:"current"});fireEvent.click(screen.getByTestId("focus-run-checks-button"));await waitFor(()=>expect(calls.some(c=>c.path==="/backlog")).toBe(true));expect(effects()).toEqual([{method:"POST",path:"/execution/fixture-execution/trigger-review",body:{}}]);expect(client.getQueryState(["execution","fixture-execution"])?.isInvalidated).toBe(true);});
 it("retains exact execution retry pending with no duplicate, then invalidates only after completion",async()=>{let finish!:(value:Response)=>void;replies.set("POST /execution/fixture-execution/retry",()=>new Promise(r=>{finish=r;}));mount(execution("failed"));fireEvent.click(screen.getByTestId("focus-retry-button"));await waitFor(()=>expect(effects()).toHaveLength(1));expect(screen.getByTestId("focus-retry-button")).toBeDisabled();fireEvent.click(screen.getByTestId("focus-retry-button"));expect(effects()).toHaveLength(1);expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);await act(async()=>finish(json({})));await waitFor(()=>expect(calls.some(c=>c.path==="/backlog")).toBe(true));expect(effects()).toEqual([{method:"POST",path:"/execution/fixture-execution/retry",body:{}}]);});
 it("displays refused execution retry without alternate effects or canonical refresh",async()=>{replies.set("POST /execution/fixture-execution/retry",()=>json({message:"Fixture retry refused"},422));mount(execution("failed"));fireEvent.click(screen.getByTestId("focus-retry-button"));expect(await screen.findByText("Fixture retry refused")).toBeVisible();expect(effects()).toHaveLength(1);expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);});
 it.each(["running","canceled"] as const)("keeps execution %s without an invented action",status=>{mount(execution(status));expect(screen.queryByTestId("focus-review-button")).toBeNull();expect(screen.queryByTestId("focus-run-checks-button")).toBeNull();expect(screen.queryByTestId("focus-retry-button")).toBeNull();expect(effects()).toEqual([]);});
 it("uses declared capture subject and pending guard at the real Connect boundary",async()=>{let finish!:(value:Response)=>void;const path="/vrooli.swarm_manager.v1.api.TransitionService/StartTransition";replies.set("POST "+path,()=>new Promise(r=>{finish=r;}));mount(capture("classifying"));fireEvent.click(await screen.findByTestId("focus-classify-button"));await waitFor(()=>expect(effects()).toHaveLength(1));expect(screen.getByTestId("focus-classify-button")).toBeDisabled();fireEvent.click(screen.getByTestId("focus-classify-button"));expect(effects()).toHaveLength(1);expect(effects()[0]?.body).toEqual({transitionKey:"capture.classify",subjectRef:{subject:"capture",value:"fixture-capture"}});await act(async()=>finish(json({executionId:"fixture-classification"})));await waitFor(()=>expect(screen.getByTestId("focus-classify-button")).not.toBeDisabled());expect(effects()).toHaveLength(1);});
 it("shows Capture owner refusal without a legacy fallback or synthetic success",async()=>{replies.set("POST /vrooli.swarm_manager.v1.api.TransitionService/StartTransition",()=>json({code:"permission_denied",message:"Fixture capture refused"},403));mount(capture("classifying"));fireEvent.click(await screen.findByTestId("focus-classify-button"));expect(await screen.findByText(/Fixture capture refused/)).toBeVisible();expect(effects()).toHaveLength(1);expect(effects()[0]?.body).toEqual({transitionKey:"capture.classify",subjectRef:{subject:"capture",value:"fixture-capture"}});});
 it.each(["classified","failed"] as const)("does not invent a classification action for capture %s",status=>{mount(capture(status));expect(screen.queryByTestId("focus-classify-button")).toBeNull();expect(effects()).toEqual([]);});
});

describe("backlog retry exact projected owner", () => {
 it("holds the dedicated backlog retry pending without duplicate or premature canonical refresh",async()=>{
  action="retry";let finish!:(value:Response)=>void;replies.set("POST /backlog/fix/fixture-backlog/retry",()=>new Promise(resolve=>{finish=resolve;}));
  mount();fireEvent.click(await screen.findByTestId("focus-cta-button"));await waitFor(()=>expect(effects()).toHaveLength(1));await waitFor(()=>expect(screen.getByTestId("focus-cta-button")).toBeDisabled());
  fireEvent.click(screen.getByTestId("focus-cta-button"));expect(effects()).toEqual([{method:"POST",path:"/backlog/fix/fixture-backlog/retry",body:{}}]);expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);
  await act(async()=>finish(json({new_execution_id:"fixture-new-execution",parent_execution_id:"fixture-parent",status:"queued"})));await waitFor(()=>expect(calls.some(c=>c.path==="/backlog")).toBe(true));expect(await screen.findByText("Retry started")).toBeVisible();expect(effects()).toHaveLength(1);
 });
 it("reports backlog retry refusal without refreshing, changing owner or using execution follow-up",async()=>{
  action="retry";replies.set("POST /backlog/fix/fixture-backlog/retry",()=>json({message:"Projected backlog owner refused"},403));const{client}=mount();await screen.findByTestId("focus-cta-button");const before=client.getQueryData(["backlog","fix","fixture-backlog","next-action"]);
  fireEvent.click(screen.getByTestId("focus-cta-button"));expect(await screen.findByText("You don't have permission to access this resource.")).toBeVisible();
  expect(effects()).toEqual([{method:"POST",path:"/backlog/fix/fixture-backlog/retry",body:{}}]);expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);expect(client.getQueryData(["backlog","fix","fixture-backlog","next-action"])).toBe(before);expect(screen.queryByText("Retry started")).toBeNull();
 });
 it("refuses a disabled retry projection even when a graph ID suggests another execution",async()=>{
  action="retry";enabled=false;mount(backlog,"execution/other-owner");const cta=await screen.findByTestId("focus-cta-button");expect(cta).toBeDisabled();fireEvent.click(cta);expect(effects()).toEqual([]);expect(calls.filter(c=>c.path==="/backlog")).toEqual([]);
 });
 it.each(["not-a-node-id","execution/other-owner"])("uses the authoritative backlog kind/name when incidental graph ID is %s",async nodeId=>{
  action="retry";replies.set("POST /backlog/fix/fixture-backlog/retry",()=>json({new_execution_id:"fixture-new-execution",parent_execution_id:"fixture-parent",status:"queued"}));mount(backlog,nodeId);fireEvent.click(await screen.findByTestId("focus-cta-button"));
  await waitFor(()=>expect(calls.some(c=>c.path==="/backlog")).toBe(true));expect(effects()).toEqual([{method:"POST",path:"/backlog/fix/fixture-backlog/retry",body:{}}]);
 });
});
