import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, screen, waitFor, within } from "@testing-library/react";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import { SettingsDrawer } from "./SettingsDrawer";
import { useGraphDataStore, cloneGraphDataInitialState, resetGraphRequestState } from "../stores/graph-data-store";
import { useGraphSettingsStore, cloneGraphSettingsInitialState } from "../stores/graph-settings-store";
import { useGraphUIStore, cloneGraphUIInitialState } from "../stores/graph-ui-store";
import { makeBacklogNode } from "../test-helpers";
import { createTestQueryClient, renderWithProviders } from "../../../test-utils";
import { defaultApiClient } from "../../../lib/api-client";
import { DEFAULT_SETTINGS } from "../../../services/settings-service";
// Real panel, controls, embedded Settings/Prompts pages, stores and adapters.
// Only exact owner reads are fixtures. UI persistence is disposable localStorage.
const clients:ReturnType<typeof createTestQueryClient>[]=[];const views:{unmount():void}[]=[];
const requests:{path:string;body:string;method:string}[]=[];const unexpected:string[]=[];
let graphRefused=false;let graphReply:()=>Promise<unknown>;let close:ReturnType<typeof vi.fn>;
const savedStorage:Record<string,string>={};let theme:string|undefined,resolved:string|undefined,color="";
function reset(){resetGraphRequestState();const initial=cloneGraphDataInitialState();const nodes=[makeBacklogNode("backlog-item/fix/fixture",{status:"backlog"})];useGraphDataStore.setState({...initial,lens:"topology",nodes,graphsByLens:{...initial.graphsByLens,topology:{...initial.graphsByLens.topology,nodes}}});useGraphSettingsStore.setState(cloneGraphSettingsInitialState());useGraphUIStore.setState(cloneGraphUIInitialState());}
function settings(){return useGraphSettingsStore.getState().settingsByLens.topology;}
function statusGroup(){const section=screen.getByText("Statuses").closest("section");if(!section)throw new Error("Missing status section");const header=within(section).getByRole("button",{name:/Backlog \(1\)/});const group=header.parentElement?.parentElement;if(!group)throw new Error("Missing actual status group");return within(group);}
async function mount(){const client=createTestQueryClient();clients.push(client);close=vi.fn();const view=renderWithProviders(<SettingsDrawer isOpen onClose={close}/>,{queryClient:client});views.push(view);await screen.findByText("Statuses");await waitFor(()=>expect(screen.getByRole("button",{name:"Save Settings",hidden:true})).toBeInTheDocument());return view;}
function noEffects(){for(const method of ["post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();expect(unexpected).toEqual([]);expect(requests.every(x=>x.path==="/vrooli.swarm_manager.v1.api.TransitionService/ListTransitions"&&x.method==="POST"&&x.body==="{}")).toBe(true);}
beforeEach(()=>{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key!==null)savedStorage[key]=localStorage.getItem(key)!;}localStorage.clear();theme=document.documentElement.dataset.theme;resolved=document.documentElement.dataset.resolvedTheme;color=document.documentElement.style.colorScheme;reset();requests.length=0;unexpected.length=0;graphRefused=false;graphReply=async()=>({nodes:[],edges:[],meta:{lens:"topology",node_count:0,edge_count:0,generated_at:"2026-10-06T00:00:00Z"}});vi.spyOn(defaultApiClient,"get").mockImplementation(async path=>{if(path==="/settings"){const{deleteConfirmation:_,...value}=DEFAULT_SETTINGS;return{settings:value};}if(path==="/integrations")return{integrations:[]};if(path==="/stats")return{};if(path==="/prompts/catalog"||path==="/prompts/skills")return{items:[]};if(path==="/graph?lens=topology"){if(graphRefused)throw new Error("Fixture graph owner refused");return graphReply();}unexpected.push(path);throw new Error("Unexpected drawer read "+path);});for(const method of ["post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Unexpected drawer effect"));vi.stubGlobal("fetch",vi.fn(async(value:RequestInfo|URL,init?:RequestInit)=>{const req=value instanceof Request?new Request(value,init):new Request(String(value),init);const path=new URL(req.url).pathname,body=await req.text();requests.push({path,body,method:req.method});expect(path).toBe("/vrooli.swarm_manager.v1.api.TransitionService/ListTransitions");expect(req.method).toBe("POST");expect(body).toBe("{}");return new Response(JSON.stringify({transitions:[]}),{headers:{"Content-Type":"application/json"}});}));});
afterEach(()=>{try{views.splice(0).forEach(v=>v.unmount());cleanup();getSpatialNav()?.dispose();noEffects();}finally{clients.splice(0).forEach(c=>c.clear());reset();vi.restoreAllMocks();vi.unstubAllGlobals();localStorage.clear();for(const[key,value]of Object.entries(savedStorage)){localStorage.setItem(key,value);delete savedStorage[key];}if(theme===undefined)delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=theme;if(resolved===undefined)delete document.documentElement.dataset.resolvedTheme;else document.documentElement.dataset.resolvedTheme=resolved;document.documentElement.style.colorScheme=color;}});
describe("actual graph drawer owner controls",()=>{
 it("hides and restores one status without changing owner nodes or other lenses",async()=>{await mount();const nodes=useGraphDataStore.getState().nodes;const other=structuredClone(useGraphSettingsStore.getState().settingsByLens.focus);const group=statusGroup();fireEvent.click(group.getByRole("button",{name:"backlog"}));expect(settings().statusFilters.backlog?.backlog).toBe(false);fireEvent.click(group.getByRole("button",{name:"backlog"}));expect(settings().statusFilters.backlog?.backlog).toBeUndefined();expect(useGraphDataStore.getState().nodes).toBe(nodes);expect(useGraphSettingsStore.getState().settingsByLens.focus).toEqual(other);});
 it("hides and restores the whole backlog status group without hiding entities",async()=>{await mount();const group=statusGroup();fireEvent.click(group.getByRole("button",{name:"Hide all"}));expect(settings().statusFilters.backlog).toBeDefined();expect(Object.values(settings().statusFilters.backlog!).every(x=>x===false)).toBe(true);expect(settings().entityFilters.backlog).toBe(true);fireEvent.click(group.getByRole("button",{name:"Show all"}));expect(settings().statusFilters.backlog??{}).toEqual({});});
 it("clears all custom status filters through the actual Reset action",async()=>{await mount();fireEvent.click(statusGroup().getByRole("button",{name:"backlog"}));const section=screen.getByText("Statuses").closest("section")!;fireEvent.click(within(section).getByRole("button",{name:"Reset"}));expect(settings().statusFilters).toEqual({});});
 it("collapses and reopens status disclosure without changing visibility",async()=>{await mount();const group=statusGroup();const header=group.getByRole("button",{name:/Backlog \(1\)/});const before=structuredClone(settings());fireEvent.click(header);expect(header).toHaveAttribute("aria-expanded","false");expect(group.queryByRole("button",{name:"backlog"})).toBeNull();fireEvent.click(header);expect(header).toHaveAttribute("aria-expanded","true");expect(group.getByRole("button",{name:"backlog"})).toBeVisible();expect(settings()).toEqual(before);});
 it("resets only the current lens and requests a fit without reloading owner data",async()=>{await mount();fireEvent.click(screen.getByRole("button",{name:"Backlog"}));fireEvent.click(screen.getByRole("button",{name:"Show Nav Controls"}));const other=structuredClone(useGraphSettingsStore.getState().settingsByLens.focus);const nonce=useGraphUIStore.getState().fitViewNonce;fireEvent.click(screen.getByRole("button",{name:"Reset Lens"}));expect(settings()).toEqual(cloneGraphSettingsInitialState().settingsByLens.topology);expect(useGraphSettingsStore.getState().settingsByLens.focus).toEqual(other);expect(useGraphUIStore.getState().fitViewNonce).toBe(nonce+1);expect(vi.mocked(defaultApiClient.get).mock.calls.filter(([p])=>p.startsWith("/graph"))).toHaveLength(0);});
 it("uses real embedded Settings and Prompts tabs without leaving or offering a write",async()=>{await mount();fireEvent.click(screen.getByRole("button",{name:"Settings"}));expect(screen.getByRole("button",{name:"Save Settings"})).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Prompts"}));expect(await screen.findByRole("tab",{name:"Prompt Catalog"})).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Graph"}));expect(screen.getByText("Statuses")).toBeVisible();noEffects();});
 it("shows pending graph read then commits only its exact owner projection",async()=>{let resolve:(value:unknown)=>void=()=>{throw new Error("No graph read");};graphReply=()=>new Promise(r=>{resolve=r;});await mount();fireEvent.click(screen.getByRole("button",{name:"Reload Graph"}));expect(await screen.findByText("Refreshing graph…")).toBeVisible();expect(useGraphDataStore.getState().nodes).toHaveLength(1);resolve({nodes:[],edges:[],meta:{lens:"topology",node_count:0,edge_count:0,generated_at:"2026-10-06T00:00:00Z"}});await waitFor(()=>expect(useGraphDataStore.getState().loading).toBe(false));expect(useGraphDataStore.getState().nodes).toEqual([]);expect(vi.mocked(defaultApiClient.get).mock.calls.filter(([p])=>p.startsWith("/graph"))).toHaveLength(1);});
 it("retains the canonical graph after refused refresh and offers no alternate effect",async()=>{graphRefused=true;await mount();const nodes=useGraphDataStore.getState().nodes;fireEvent.click(screen.getByRole("button",{name:"Reload Graph"}));expect(await screen.findByText("Fixture graph owner refused")).toBeVisible();expect(useGraphDataStore.getState().nodes).toBe(nodes);expect(vi.mocked(defaultApiClient.get).mock.calls.filter(([p])=>p.startsWith("/graph"))).toHaveLength(1);noEffects();});
});
