// Actual Connect client and generated reader. Only the declared GetRelated POST
// is permitted; none of these projections confer run identity or admission.
import { cleanup, fireEvent, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import type { QueryClient } from "@tanstack/react-query";
import { useLocation } from "react-router-dom";
import { createTestQueryClient, renderWithProviders } from "../../test-utils";
import { API_BASE, defaultApiClient } from "../../lib/api-client";
import { RelatedTab } from "./RelatedTab";
import type { RelatedTarget } from "../../services/related-service";
const backlog={backlog:{kind:"idea",name:"fixture-source"}};
let expectedReads:unknown[]; let observedReads:unknown[]; let refuse:boolean; let invalid:boolean; let unexpected:string[];
let groups:unknown[];const clients:QueryClient[]=[];const views:ReturnType<typeof renderWithProviders>[]=[];
function Location(){return <output data-testid="current-owner-url">{useLocation().search}</output>;}
function mount(target:RelatedTarget={kind:"backlog",backlogKind:"idea",name:"fixture-source"},entry="/backlog/idea/fixture-source?tab=related&keep=1",enabled=true){const queryClient=createTestQueryClient();clients.push(queryClient);const view=renderWithProviders(<><Location/><RelatedTab target={target} enabled={enabled}/></>,{queryClient,initialEntries:[entry]});views.push(view);return view;}
beforeEach(()=>{window.localStorage.clear();expectedReads=[];observedReads=[];unexpected=[];refuse=false;invalid=false;groups=[{name:"linked",entities:[],degraded:false}];for(const method of ["get","post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Forbidden related alternate transport"));vi.stubGlobal("fetch",vi.fn(async (url:RequestInfo|URL,options?:RequestInit)=>{if(String(url)!==`${API_BASE}/vrooli.swarm_manager.v1.api.RelatedService/GetRelated`||options?.method!=="POST"){unexpected.push(`${options?.method} ${String(url)}`);throw new Error("Forbidden related route");}const wire=options.body;let text:string;if(typeof wire==="string")text=wire;else if(ArrayBuffer.isView(wire))text=new TextDecoder().decode(new Uint8Array(wire.buffer,wire.byteOffset,wire.byteLength));else throw new Error("Unsupported Connect fixture body");const body=JSON.parse(text);observedReads.push(body);if(refuse)return new Response(JSON.stringify({code:"unavailable",message:"Fixture owner refused related read"}),{status:503,headers:{"Content-Type":"application/json"}});return new Response(invalid?"not-json":JSON.stringify({groups}),{status:200,headers:{"Content-Type":"application/json"}});}));});
afterEach(()=>{views.splice(0).forEach(view=>view.unmount());cleanup();clients.splice(0).forEach(client=>client.clear());getSpatialNav()?.dispose();try{expect(observedReads).toEqual(expectedReads);expect(unexpected).toEqual([]);for(const method of ["get","post","put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();}finally{window.localStorage.clear();vi.restoreAllMocks();vi.unstubAllGlobals();}});
describe("related work owner reads, URL filters and local disclosures",()=>{
 it("retains exact historical entity links and visible reasons through the real reader",async()=>{groups=[{name:"linked",entities:[{entity_kind:"backlog",key:"idea/related-item",title:"Original related item",status:"completed",archived:true,reasons:["first reason","second reason","retained hidden reason"],score_percent:73},{entity_kind:"goal",key:"related-goal",title:"Original related goal",status:"active",reasons:[]},{entity_kind:"record",key:"related-record",title:"Original related record",reasons:[]}]}];expectedReads=[backlog];mount();expect(await screen.findByRole("link",{name:"Original related item"})).toHaveAttribute("href","/backlog/idea/related-item");expect(screen.getByRole("link",{name:"Original related goal"})).toHaveAttribute("href","/goals/related-goal");expect(screen.getByRole("link",{name:"Original related record"})).toHaveAttribute("href","/records/related-record");expect(screen.getByText("Archived")).toBeVisible();expect(screen.getByText("73% similar")).toBeVisible();expect(screen.getByTestId("related-reasons-overflow")).toHaveTextContent("+1");expect(screen.getByTestId("related-reasons-overflow")).toHaveAttribute("title","retained hidden reason");});
 it("uses key fallback and keeps absent optional badges absent on a goal target",async()=>{groups=[{name:"similar",entities:[{entity_kind:"goal",key:"untitled-goal",reasons:[],score_percent:0}],degraded:true}];expectedReads=[{goal:{name:"fixture-goal"}}];mount({kind:"goal",name:"fixture-goal"});expect(await screen.findByRole("link",{name:"untitled-goal"})).toHaveAttribute("href","/goals/untitled-goal");expect(screen.queryByText("Archived")).toBeNull();expect(screen.queryByText("0% similar")).toBeNull();expect(screen.queryByTestId("related-reasons-overflow")).toBeNull();expect(screen.getByText("Similarity unavailable")).toBeVisible();});
 it("treats an invalid historical URL value as the canonical include setting",async()=>{expectedReads=[backlog];mount(undefined,"/backlog/idea/fixture-source?tab=related&historical=unknown&keep=1");expect(await screen.findByTestId("related-filter-historical")).toHaveAttribute("aria-pressed","true");expect(screen.getByTestId("current-owner-url")).toHaveTextContent("keep=1");});
 it("changes historical reads only after explicit local filter clicks and preserves other URL state",async()=>{expectedReads=[backlog];mount();const button=await screen.findByTestId("related-filter-historical");expectedReads.push({...backlog,excludeHistorical:true});fireEvent.click(button);await waitFor(()=>expect(observedReads).toHaveLength(2));await waitFor(()=>expect(screen.getByTestId("related-filter-historical")).toHaveAttribute("aria-pressed","false"));expect(screen.getByTestId("current-owner-url")).toHaveTextContent("historical=exclude");expect(screen.getByTestId("current-owner-url")).toHaveTextContent("keep=1");expectedReads.push(backlog);fireEvent.click(await screen.findByTestId("related-filter-historical"));await waitFor(()=>expect(screen.getByTestId("related-filter-historical")).toHaveAttribute("aria-pressed","true"));await waitFor(()=>expect(observedReads).toHaveLength(3));});
 it("uses exact selected entity sets for each read without inventing an all-off route",async()=>{expectedReads=[backlog];mount();await screen.findByTestId("related-filter-goal");expectedReads.push({...backlog,entityKinds:["backlog"]});fireEvent.click(screen.getByTestId("related-filter-backlog"));await waitFor(()=>expect(observedReads).toHaveLength(2));await waitFor(()=>expect(screen.getByTestId("related-filter-backlog")).toHaveAttribute("aria-pressed","true"));expectedReads.push({...backlog,entityKinds:["backlog","goal"]});fireEvent.click(screen.getByTestId("related-filter-goal"));await waitFor(()=>expect(observedReads).toHaveLength(3));await waitFor(()=>expect(screen.getByTestId("related-filter-goal")).toHaveAttribute("aria-pressed","true"));expectedReads.push({...backlog,entityKinds:["goal"]});fireEvent.click(screen.getByTestId("related-filter-backlog"));await waitFor(()=>expect(observedReads).toHaveLength(4));await waitFor(()=>expect(screen.getByTestId("related-filter-backlog")).toHaveAttribute("aria-pressed","false"));expectedReads.push(backlog);fireEvent.click(screen.getByTestId("related-filter-goal"));await waitFor(()=>expect(screen.getByTestId("related-filter-goal")).toHaveAttribute("aria-pressed","false"));await waitFor(()=>expect(observedReads).toHaveLength(5));expect(screen.getByTestId("current-owner-url")).toHaveTextContent("keep=1");});
 it("retains read refusal without offering an alternate owner read or mutation",async()=>{refuse=true;expectedReads=[backlog];mount();expect(await screen.findByText("Related work is not available yet")).toBeVisible();expect(screen.queryByRole("button",{name:/try again/i})).toBeNull();expect(observedReads).toHaveLength(1);});
 it("contains malformed wire data without alternate discovery or mutation",async()=>{invalid=true;expectedReads=[backlog];mount();expect(await screen.findByText("Related work is not available yet")).toBeVisible();expect(observedReads).toHaveLength(1);});
 it("keeps disabled discovery free of read or mutation offers",async()=>{mount(undefined,undefined,false);await Promise.resolve();expect(observedReads).toEqual([]);});
 it("collapses and reopens the current owner group locally without another request",async()=>{expectedReads=[backlog];mount();const toggle=await screen.findByRole("button",{name:/linked.*0/i});expect(screen.getByText("No related work.")).toBeVisible();fireEvent.click(toggle);expect(screen.queryByText("No related work.")).toBeNull();fireEvent.click(toggle);expect(screen.getByText("No related work.")).toBeVisible();expect(observedReads).toHaveLength(1);});
});
