// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    brand: "app.brand",
    brandInitials: "app.brandInitials",
    eyebrow: "app.eyebrow",
    title: "app.title",
  },
  common: {
    code: {
      copied: "common.code.copied",
      copy: "common.code.copy",
      copyShort: "common.code.copyShort",
    },
  },
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  health: {
    pill: {
      error: "health.pill.error",
      loading: "health.pill.loading",
      ok: "health.pill.ok",
    },
  },
  inspector: {
    close: "inspector.close",
  },
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    closeDrawer: "layout.closeDrawer",
    drawerLabel: "layout.drawerLabel",
    main: "layout.main",
    mobileHeaderLabel: "layout.mobileHeaderLabel",
    nav: {
      captures: "layout.nav.captures",
      dashboard: "layout.nav.dashboard",
      inventory: "layout.nav.inventory",
      reindex: "layout.nav.reindex",
      search: "layout.nav.search",
      settings: "layout.nav.settings",
      validation: "layout.nav.validation",
    },
    openDrawer: "layout.openDrawer",
    sidebarLabel: "layout.sidebarLabel",
    skipToContent: "layout.skipToContent",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  navigation: {
    "app-shell": {
      "close-navigation": "navigation.app-shell.close-navigation",
      "mobile-navigation": "navigation.app-shell.mobile-navigation",
      "open-navigation": "navigation.app-shell.open-navigation",
      "primary-navigation": "navigation.app-shell.primary-navigation",
      "skip-to-content": "navigation.app-shell.skip-to-content",
    },
  },
  pages: {
    captures: {
      chrome: {
        captured: "pages.captures.chrome.captured",
        declared: "pages.captures.chrome.declared",
        safeArea: "pages.captures.chrome.safeArea",
        statusBar: "pages.captures.chrome.statusBar",
      },
      description: "pages.captures.description",
      empty: "pages.captures.empty",
      filters: {
        allScenarios: "pages.captures.filters.allScenarios",
        scenario: "pages.captures.filters.scenario",
      },
      status: {
        clean: "pages.captures.status.clean",
        findings: "pages.captures.status.findings",
      },
      title: "pages.captures.title",
      violations: {
        edge: "pages.captures.violations.edge",
        empty: "pages.captures.violations.empty",
      },
    },
    dashboard: {
      activity: {
        empty: "pages.dashboard.activity.empty",
        errorsLabel: "pages.dashboard.activity.errorsLabel",
        heading: "pages.dashboard.activity.heading",
        kindReindex: "pages.dashboard.activity.kindReindex",
        kindValidation: "pages.dashboard.activity.kindValidation",
        openJob: "pages.dashboard.activity.openJob",
        openValidation: "pages.dashboard.activity.openValidation",
        validationFailed: "pages.dashboard.activity.validationFailed",
        validationPassed: "pages.dashboard.activity.validationPassed",
        warningsLabel: "pages.dashboard.activity.warningsLabel",
      },
      apiStatus: {
        dependencies: "pages.dashboard.apiStatus.dependencies",
        error: "pages.dashboard.apiStatus.error",
        heading: "pages.dashboard.apiStatus.heading",
        indexedSurfaces: "pages.dashboard.apiStatus.indexedSurfaces",
        latency: "pages.dashboard.apiStatus.latency",
        loading: "pages.dashboard.apiStatus.loading",
        noDependencies: "pages.dashboard.apiStatus.noDependencies",
        notReady: "pages.dashboard.apiStatus.notReady",
        readiness: "pages.dashboard.apiStatus.readiness",
        ready: "pages.dashboard.apiStatus.ready",
        service: "pages.dashboard.apiStatus.service",
        uptime: "pages.dashboard.apiStatus.uptime",
        uptimeSeconds: "pages.dashboard.apiStatus.uptimeSeconds",
        version: "pages.dashboard.apiStatus.version",
      },
      description: "pages.dashboard.description",
      quickActions: {
        heading: "pages.dashboard.quickActions.heading",
        inventory: "pages.dashboard.quickActions.inventory",
        reindex: "pages.dashboard.quickActions.reindex",
        search: "pages.dashboard.quickActions.search",
        validate: "pages.dashboard.quickActions.validate",
      },
      stats: {
        openIssues: "pages.dashboard.stats.openIssues",
        scenariosValidated: "pages.dashboard.stats.scenariosValidated",
        surfacesIndexed: "pages.dashboard.stats.surfacesIndexed",
      },
      title: "pages.dashboard.title",
    },
    inventory: {
      columns: {
        displayName: "pages.inventory.columns.displayName",
        filePath: "pages.inventory.columns.filePath",
        kind: "pages.inventory.columns.kind",
        slot: "pages.inventory.columns.slot",
      },
      description: "pages.inventory.description",
      detail: {
        back: "pages.inventory.detail.back",
        description: "pages.inventory.detail.description",
        error: "pages.inventory.detail.error",
        filePath: "pages.inventory.detail.filePath",
        kind: "pages.inventory.detail.kind",
        loading: "pages.inventory.detail.loading",
        notFound: {
          description: "pages.inventory.detail.notFound.description",
          title: "pages.inventory.detail.notFound.title",
        },
        provenance: {
          adoptionId: "pages.inventory.detail.provenance.adoptionId",
          empty: "pages.inventory.detail.provenance.empty",
          heading: "pages.inventory.detail.provenance.heading",
          library: "pages.inventory.detail.provenance.library",
          libraryVersion: "pages.inventory.detail.provenance.libraryVersion",
        },
        scenario: "pages.inventory.detail.scenario",
        slot: "pages.inventory.detail.slot",
        title: "pages.inventory.detail.title",
        widgets: {
          empty: "pages.inventory.detail.widgets.empty",
          heading: "pages.inventory.detail.widgets.heading",
          propsSchema: "pages.inventory.detail.widgets.propsSchema",
        },
      },
      empty: {
        description: "pages.inventory.empty.description",
        title: "pages.inventory.empty.title",
      },
      error: "pages.inventory.error",
      filters: {
        heading: "pages.inventory.filters.heading",
      },
      form: {
        heading: "pages.inventory.form.heading",
        scenarioHelp: "pages.inventory.form.scenarioHelp",
        scenarioLabel: "pages.inventory.form.scenarioLabel",
        scenarioPlaceholder: "pages.inventory.form.scenarioPlaceholder",
        submit: "pages.inventory.form.submit",
        submitting: "pages.inventory.form.submitting",
      },
      loading: "pages.inventory.loading",
      noResultsForFilter: "pages.inventory.noResultsForFilter",
      noSurfaces: {
        description: "pages.inventory.noSurfaces.description",
        title: "pages.inventory.noSurfaces.title",
      },
      summary: "pages.inventory.summary",
      title: "pages.inventory.title",
    },
    notFound: {
      back: "pages.notFound.back",
      description: "pages.notFound.description",
      title: "pages.notFound.title",
    },
    reindex: {
      confirm: {
        accept: "pages.reindex.confirm.accept",
        backdrop: "pages.reindex.confirm.backdrop",
        cancel: "pages.reindex.confirm.cancel",
        close: "pages.reindex.confirm.close",
        description: "pages.reindex.confirm.description",
        title: "pages.reindex.confirm.title",
      },
      description: "pages.reindex.description",
      error: "pages.reindex.error",
      form: {
        dryRunHelp: "pages.reindex.form.dryRunHelp",
        dryRunLabel: "pages.reindex.form.dryRunLabel",
        heading: "pages.reindex.form.heading",
        scenarioHelp: "pages.reindex.form.scenarioHelp",
        scenarioLabel: "pages.reindex.form.scenarioLabel",
        scenarioPlaceholder: "pages.reindex.form.scenarioPlaceholder",
        submit: "pages.reindex.form.submit",
        submitting: "pages.reindex.form.submitting",
      },
      job: {
        back: "pages.reindex.job.back",
        cancel: "pages.reindex.job.cancel",
        cancelling: "pages.reindex.job.cancelling",
        error: "pages.reindex.job.error",
        loadError: "pages.reindex.job.loadError",
        loading: "pages.reindex.job.loading",
        meta: {
          dryRun: "pages.reindex.job.meta.dryRun",
          processed: "pages.reindex.job.meta.processed",
          scenario: "pages.reindex.job.meta.scenario",
          state: "pages.reindex.job.meta.state",
          total: "pages.reindex.job.meta.total",
          triggeredAt: "pages.reindex.job.meta.triggeredAt",
        },
        notFound: {
          description: "pages.reindex.job.notFound.description",
          title: "pages.reindex.job.notFound.title",
        },
        progress: "pages.reindex.job.progress",
        title: "pages.reindex.job.title",
      },
      jobs: {
        allScenarios: "pages.reindex.jobs.allScenarios",
        clearTerminal: "pages.reindex.jobs.clearTerminal",
        columns: {
          dryRun: "pages.reindex.jobs.columns.dryRun",
          progress: "pages.reindex.jobs.columns.progress",
        },
        emptyDescription: "pages.reindex.jobs.emptyDescription",
        emptyTitle: "pages.reindex.jobs.emptyTitle",
        heading: "pages.reindex.jobs.heading",
        open: "pages.reindex.jobs.open",
      },
      state: {
        cancelled: "pages.reindex.state.cancelled",
        failed: "pages.reindex.state.failed",
        queued: "pages.reindex.state.queued",
        running: "pages.reindex.state.running",
        succeeded: "pages.reindex.state.succeeded",
        unknown: "pages.reindex.state.unknown",
      },
      title: "pages.reindex.title",
    },
    search: {
      description: "pages.search.description",
      empty: {
        description: "pages.search.empty.description",
        title: "pages.search.empty.title",
      },
      error: "pages.search.error",
      filters: {
        heading: "pages.search.filters.heading",
      },
      input: {
        clear: "pages.search.input.clear",
        label: "pages.search.input.label",
      },
      kind: {
        all: "pages.search.kind.all",
        component: "pages.search.kind.component",
        feature: "pages.search.kind.feature",
        hook: "pages.search.kind.hook",
        layout: "pages.search.kind.layout",
        other: "pages.search.kind.other",
        page: "pages.search.kind.page",
        unspecified: "pages.search.kind.unspecified",
      },
      loading: "pages.search.loading",
      noResults: {
        description: "pages.search.noResults.description",
        title: "pages.search.noResults.title",
      },
      noResultsForFilter: "pages.search.noResultsForFilter",
      placeholder: "pages.search.placeholder",
      provenance: {
        adoptedModified: "pages.search.provenance.adoptedModified",
        adoptedUnmodified: "pages.search.provenance.adoptedUnmodified",
        custom: "pages.search.provenance.custom",
        unknown: "pages.search.provenance.unknown",
        unspecified: "pages.search.provenance.unspecified",
      },
      results: {
        listLabel: "pages.search.results.listLabel",
        openInInventory: "pages.search.results.openInInventory",
        path: "pages.search.results.path",
        score: "pages.search.results.score",
        summary: "pages.search.results.summary",
      },
      shortQuery: "pages.search.shortQuery",
      title: "pages.search.title",
    },
    settings: {
      localeHeading: "pages.settings.localeHeading",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
    validation: {
      back: "pages.validation.back",
      description: "pages.validation.description",
      error: "pages.validation.error",
      filters: {
        all: "pages.validation.filters.all",
        error: "pages.validation.filters.error",
        heading: "pages.validation.filters.heading",
        info: "pages.validation.filters.info",
        warning: "pages.validation.filters.warning",
      },
      findings: {
        code: "pages.validation.findings.code",
        empty: "pages.validation.findings.empty",
        heading: "pages.validation.findings.heading",
        location: "pages.validation.findings.location",
        noneForFilter: "pages.validation.findings.noneForFilter",
        suggestion: "pages.validation.findings.suggestion",
      },
      form: {
        heading: "pages.validation.form.heading",
        scenarioHelp: "pages.validation.form.scenarioHelp",
        scenarioLabel: "pages.validation.form.scenarioLabel",
        scenarioPlaceholder: "pages.validation.form.scenarioPlaceholder",
        submit: "pages.validation.form.submit",
        submitting: "pages.validation.form.submitting",
      },
      loading: "pages.validation.loading",
      presentation: {
        codeRollup: "pages.validation.presentation.codeRollup",
        contract: "pages.validation.presentation.contract",
        docs: "pages.validation.presentation.docs",
        heading: "pages.validation.presentation.heading",
        maximum: "pages.validation.presentation.maximum",
        next: "pages.validation.presentation.next",
        northStar: "pages.validation.presentation.northStar",
        unlock: "pages.validation.presentation.unlock",
      },
      recent: {
        clear: "pages.validation.recent.clear",
        columns: {
          errors: "pages.validation.recent.columns.errors",
          ranAt: "pages.validation.recent.columns.ranAt",
          scenario: "pages.validation.recent.columns.scenario",
          status: "pages.validation.recent.columns.status",
          warnings: "pages.validation.recent.columns.warnings",
        },
        empty: "pages.validation.recent.empty",
        heading: "pages.validation.recent.heading",
        open: "pages.validation.recent.open",
      },
      revalidate: "pages.validation.revalidate",
      status: {
        failed: "pages.validation.status.failed",
        passed: "pages.validation.status.passed",
      },
      summary: {
        errors: "pages.validation.summary.errors",
        heading: "pages.validation.summary.heading",
        infos: "pages.validation.summary.infos",
        ranAt: "pages.validation.summary.ranAt",
        warnings: "pages.validation.summary.warnings",
      },
      title: "pages.validation.title",
    },
  },
  route: {
    loading: "route.loading",
  },
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    dark: "theme.dark",
    light: "theme.light",
    switcherLabel: "theme.switcherLabel",
    system: "theme.system",
  },
} as const;

export type Strings = typeof strings;
