// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      runs: "layout.nav.runs",
      settings: "layout.nav.settings",
      sessions: "layout.nav.sessions",
      rollouts: "layout.nav.rollouts",
      trust: "layout.nav.trust",
      setup: "layout.nav.setup",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
    runs: {
      title: "pages.runs.title",
      description: "pages.runs.description",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  fleet: {
    title: "fleet.title",
    description: "fleet.description",
    loading: "fleet.loading",
    empty: "fleet.empty",
    onlineLabel: "fleet.onlineLabel",
    offlineLabel: "fleet.offlineLabel",
    neverSeen: "fleet.neverSeen",
    revoke: "fleet.revoke",
    revokeConfirm: "fleet.revokeConfirm",
    osLabel: "fleet.osLabel",
    archLabel: "fleet.archLabel",
    versionLabel: "fleet.versionLabel",
    healthLabel: "fleet.healthLabel",
    unknownValue: "fleet.unknownValue",
    readiness: {
      registry: "fleet.readiness.registry",
      heartbeat: "fleet.readiness.heartbeat",
      channel: "fleet.readiness.channel",
      protocol: "fleet.readiness.protocol",
      dispatch: "fleet.readiness.dispatch",
      present: "fleet.readiness.present",
      missing: "fleet.readiness.missing",
      fresh: "fleet.readiness.fresh",
      stale: "fleet.readiness.stale",
      held: "fleet.readiness.held",
      absent: "fleet.readiness.absent",
      compatible: "fleet.readiness.compatible",
      updateRequired: "fleet.readiness.updateRequired",
      ready: "fleet.readiness.ready",
      blocked: "fleet.readiness.blocked",
    },
    machines: {
      heading: "fleet.machines.heading",
      description: "fleet.machines.description",
      loading: "fleet.machines.loading",
      empty: "fleet.machines.empty",
      state: "fleet.machines.state",
      details: "fleet.machines.details",
      detailHeading: "fleet.machines.detailHeading",
      closeDetails: "fleet.machines.closeDetails",
      attempts: "fleet.machines.attempts",
      currentNode: "fleet.machines.currentNode",
      noCurrentNode: "fleet.machines.noCurrentNode",
      auditEvents: "fleet.machines.auditEvents",
      cleanupStatus: "fleet.machines.cleanupStatus",
      noCleanup: "fleet.machines.noCleanup",
      ready: "fleet.machines.ready",
      notReady: "fleet.machines.notReady",
      hostTrust: "fleet.machines.hostTrust",
      hostFingerprint: "fleet.machines.hostFingerprint",
      clientFingerprint: "fleet.machines.clientFingerprint",
      replacementHostKey: "fleet.machines.replacementHostKey",
      reviewHostKey: "fleet.machines.reviewHostKey",
      policy: "fleet.machines.policy",
      policyReason: "fleet.machines.policyReason",
      confirmRemoval: "fleet.machines.confirmRemoval",
      applyPolicy: "fleet.machines.applyPolicy",
      archive: "fleet.machines.archive",
      revokeNode: "fleet.machines.revokeNode",
      cleanup: "fleet.machines.cleanup",
      cleanupPlanRemove: "fleet.machines.cleanupPlanRemove",
      cleanupPlanKeep: "fleet.machines.cleanupPlanKeep",
      cleanupPlanCannotAttribute: "fleet.machines.cleanupPlanCannotAttribute",
      cleanupPlanEmpty: "fleet.machines.cleanupPlanEmpty",
      remove: "fleet.machines.remove",
      removeConfirm: "fleet.machines.removeConfirm",
    },
    bridgeReadinessHeading: "fleet.bridgeReadinessHeading",
    bridgeReadinessReady: "fleet.bridgeReadinessReady",
    bridgeReadinessCandidateBlocked: "fleet.bridgeReadinessCandidateBlocked",
    bridgeReadinessNotReady: "fleet.bridgeReadinessNotReady",
    bridgeReadinessEndpoint: "fleet.bridgeReadinessEndpoint",
    bridgeReadinessMode: "fleet.bridgeReadinessMode",
    bridgeReadinessFirewall: "fleet.bridgeReadinessFirewall",
    bridgeReadinessRemediation: "fleet.bridgeReadinessRemediation",
    bridgeReadinessVerify: "fleet.bridgeReadinessVerify",
    bridgeReadinessPreview: "fleet.bridgeReadinessPreview",
    bridgeReadinessAllow: "fleet.bridgeReadinessAllow",
    bridgeReadinessAllowConfirm: "fleet.bridgeReadinessAllowConfirm",
    bridgeReadinessRevoke: "fleet.bridgeReadinessRevoke",
    bridgeReadinessRevokeConfirm: "fleet.bridgeReadinessRevokeConfirm",
    bridgeReadinessActionResult: "fleet.bridgeReadinessActionResult",
    bridgeReadinessBrokerUnavailable: "fleet.bridgeReadinessBrokerUnavailable",
    jobsHeading: "fleet.jobsHeading",
    jobsIdle: "fleet.jobsIdle",
    jobsBusy: "fleet.jobsBusy",
    status: {
      unspecified: "fleet.status.unspecified",
      offline: "fleet.status.offline",
      online: "fleet.status.online",
      needsUpdate: "fleet.status.needsUpdate",
      revoked: "fleet.status.revoked",
    },
    pairing: {
      heading: "fleet.pairing.heading",
      description: "fleet.pairing.description",
      nameLabel: "fleet.pairing.nameLabel",
      namePlaceholder: "fleet.pairing.namePlaceholder",
      submit: "fleet.pairing.submit",
      submitting: "fleet.pairing.submitting",
      codeHeading: "fleet.pairing.codeHeading",
      codeHelp: "fleet.pairing.codeHelp",
      publicKeyLabel: "fleet.pairing.publicKeyLabel",
      expiresLabel: "fleet.pairing.expiresLabel",
      copy: "fleet.pairing.copy",
      disclosureLabel: "fleet.pairing.disclosureLabel",
      disclosureNote: "fleet.pairing.disclosureNote",
    },
    onboard: {
      heading: "fleet.onboard.heading",
      description: "fleet.onboard.description",
      hostLabel: "fleet.onboard.hostLabel",
      hostPlaceholder: "fleet.onboard.hostPlaceholder",
      userLabel: "fleet.onboard.userLabel",
      userPlaceholder: "fleet.onboard.userPlaceholder",
      portLabel: "fleet.onboard.portLabel",
      portPlaceholder: "fleet.onboard.portPlaceholder",
      nameLabel: "fleet.onboard.nameLabel",
      namePlaceholder: "fleet.onboard.namePlaceholder",
      passwordLabel: "fleet.onboard.passwordLabel",
      passwordShow: "fleet.onboard.passwordShow",
      passwordHide: "fleet.onboard.passwordHide",
      controlPlaneUrlLabel: "fleet.onboard.controlPlaneUrlLabel",
      controlPlaneUrlPlaceholder: "fleet.onboard.controlPlaneUrlPlaceholder",
      controlPlaneUrlHelp: "fleet.onboard.controlPlaneUrlHelp",
      reachabilityModeLabel: "fleet.onboard.reachabilityModeLabel",
      reachabilityModeHelp: "fleet.onboard.reachabilityModeHelp",
      endpointEvidence: "fleet.onboard.endpointEvidence",
      reachabilityLan: "fleet.onboard.reachabilityLan",
      reachabilityTunnel: "fleet.onboard.reachabilityTunnel",
      reachabilityManual: "fleet.onboard.reachabilityManual",
      capabilitiesLabel: "fleet.onboard.capabilitiesLabel",
      capabilitiesPlaceholder: "fleet.onboard.capabilitiesPlaceholder",
      capabilitiesHelp: "fleet.onboard.capabilitiesHelp",
      revisionLabel: "fleet.onboard.revisionLabel",
      revisionHelp: "fleet.onboard.revisionHelp",
      provisionSudoLabel: "fleet.onboard.provisionSudoLabel",
      provisionSudoHelp: "fleet.onboard.provisionSudoHelp",
      advancedHeading: "fleet.onboard.advancedHeading",
      advancedHelp: "fleet.onboard.advancedHelp",
      setupEnvironmentLabel: "fleet.onboard.setupEnvironmentLabel",
      setupEnvironmentPlaceholder: "fleet.onboard.setupEnvironmentPlaceholder",
      setupEnvironmentHelp: "fleet.onboard.setupEnvironmentHelp",
      setupResourcesLabel: "fleet.onboard.setupResourcesLabel",
      setupResourcesPlaceholder: "fleet.onboard.setupResourcesPlaceholder",
      setupResourcesHelp: "fleet.onboard.setupResourcesHelp",
      setupScenariosLabel: "fleet.onboard.setupScenariosLabel",
      setupScenariosPlaceholder: "fleet.onboard.setupScenariosPlaceholder",
      setupScenariosHelp: "fleet.onboard.setupScenariosHelp",
      includeOptionalLabel: "fleet.onboard.includeOptionalLabel",
      includeOptionalHelp: "fleet.onboard.includeOptionalHelp",
      sourceModeLabel: "fleet.onboard.sourceModeLabel",
      sourceModeHelp: "fleet.onboard.sourceModeHelp",
      sourceModeWarning: "fleet.onboard.sourceModeWarning",
      sourceSummaryWorkingTree: "fleet.onboard.sourceSummaryWorkingTree",
      sourceSummaryPinned: "fleet.onboard.sourceSummaryPinned",
      submit: "fleet.onboard.submit",
      submitting: "fleet.onboard.submitting",
      progressHeading: "fleet.onboard.progressHeading",
      waiting: "fleet.onboard.waiting",
      successHeading: "fleet.onboard.successHeading",
      successBody: "fleet.onboard.successBody",
      viewNode: "fleet.onboard.viewNode",
      failureHeading: "fleet.onboard.failureHeading",
      retryHint: "fleet.onboard.retryHint",
      retryUnavailable: "fleet.onboard.retryUnavailable",
      failureOutputHeading: "fleet.onboard.failureOutputHeading",
      viewLogs: "fleet.onboard.viewLogs",
      hideLogs: "fleet.onboard.hideLogs",
      loadingLogs: "fleet.onboard.loadingLogs",
      noLogs: "fleet.onboard.noLogs",
      savedFailuresHeading: "fleet.onboard.savedFailuresHeading",
      savedFailureDetail: "fleet.onboard.savedFailureDetail",
      retrySaved: "fleet.onboard.retrySaved",
      removeSaved: "fleet.onboard.removeSaved",
      state: {
        unspecified: "fleet.onboard.state.unspecified",
        pending: "fleet.onboard.state.pending",
        sshSetup: "fleet.onboard.state.sshSetup",
        pushingScript: "fleet.onboard.state.pushingScript",
        bootstrapping: "fleet.onboard.state.bootstrapping",
        verifying: "fleet.onboard.state.verifying",
        succeeded: "fleet.onboard.state.succeeded",
        failed: "fleet.onboard.state.failed",
        cancelled: "fleet.onboard.state.cancelled",
      },
      stepStatus: {
        unspecified: "fleet.onboard.stepStatus.unspecified",
        started: "fleet.onboard.stepStatus.started",
        ok: "fleet.onboard.stepStatus.ok",
        skipped: "fleet.onboard.stepStatus.skipped",
        failed: "fleet.onboard.stepStatus.failed",
      },
      failure: {
        ssh_setup_failed: "fleet.onboard.failure.ssh_setup_failed",
        script_push_failed: "fleet.onboard.failure.script_push_failed",
        pairing_issue_failed: "fleet.onboard.failure.pairing_issue_failed",
        bootstrap_usage_error: "fleet.onboard.failure.bootstrap_usage_error",
        unsupported_platform: "fleet.onboard.failure.unsupported_platform",
        pairing_failed: "fleet.onboard.failure.pairing_failed",
        bootstrap_failed: "fleet.onboard.failure.bootstrap_failed",
        verify_online_failed: "fleet.onboard.failure.verify_online_failed",
        interrupted_by_restart: "fleet.onboard.failure.interrupted_by_restart",
        internal_error: "fleet.onboard.failure.internal_error",
        generic: "fleet.onboard.failure.generic",
      },
      addNode: "fleet.onboard.addNode",
      stepConnect: "fleet.onboard.stepConnect",
      stepUnlock: "fleet.onboard.stepUnlock",
      stepReview: "fleet.onboard.stepReview",
      stepIndicator: "fleet.onboard.stepIndicator",
      next: "fleet.onboard.next",
      back: "fleet.onboard.back",
      connectIntro: "fleet.onboard.connectIntro",
      macHint: "fleet.onboard.macHint",
      moreLabel: "fleet.onboard.moreLabel",
      unlockIntro: "fleet.onboard.unlockIntro",
      passwordOptionalNote: "fleet.onboard.passwordOptionalNote",
      reviewSummary: "fleet.onboard.reviewSummary",
    },
    emptyHeading: "fleet.emptyHeading",
    management: {
      details: "fleet.management.details",
      heading: "fleet.management.heading",
      overview: "fleet.management.overview",
      endpoint: "fleet.management.endpoint",
      scopes: "fleet.management.scopes",
      save: "fleet.management.save",
      saving: "fleet.management.saving",
      revokeHeading: "fleet.management.revokeHeading",
      revokeDescription: "fleet.management.revokeDescription",
      revoke: "fleet.management.revoke",
      removeHeading: "fleet.management.removeHeading",
      removeDescription: "fleet.management.removeDescription",
      removeAction: "fleet.management.removeAction",
      removeBlocked: "fleet.management.removeBlocked",
      removeConfirm: "fleet.management.removeConfirm",
      close: "fleet.management.close",
    },
  },
  runs: {
    title: "runs.title",
    description: "runs.description",
    loading: "runs.loading",
    empty: "runs.empty",
    nodeLabel: "runs.nodeLabel",
    jobLabel: "runs.jobLabel",
    startedLabel: "runs.startedLabel",
    durationLabel: "runs.durationLabel",
    exitLabel: "runs.exitLabel",
    progressLabel: "runs.progressLabel",
    etaLabel: "runs.etaLabel",
    etaPending: "runs.etaPending",
    view: "runs.view",
    close: "runs.close",
    cancel: "runs.cancel",
    cancelling: "runs.cancelling",
    cancelConfirm: "runs.cancelConfirm",
    outputHeading: "runs.outputHeading",
    outputEmpty: "runs.outputEmpty",
    artifactsHeading: "runs.artifactsHeading",
    artifactsEmpty: "runs.artifactsEmpty",
    download: "runs.download",
    status: {
      unspecified: "runs.status.unspecified",
      queued: "runs.status.queued",
      running: "runs.status.running",
      passed: "runs.status.passed",
      failed: "runs.status.failed",
      aborted: "runs.status.aborted",
    },
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
  session: {
    screenTitle: "session.screenTitle",
    screenIntro: "session.screenIntro",
    signedInAs: "session.signedInAs",
    signedIn: "session.signedIn",
    signOut: "session.signOut",
    accountHeading: "session.accountHeading",
    firstTimeNote: "session.firstTimeNote",
    login: {
      title: "session.login.title",
      intro: "session.login.intro",
      tabSignIn: "session.login.tabSignIn",
      tabCreate: "session.login.tabCreate",
      emailLabel: "session.login.emailLabel",
      emailPlaceholder: "session.login.emailPlaceholder",
      passwordLabel: "session.login.passwordLabel",
      passwordPlaceholder: "session.login.passwordPlaceholder",
      usernameLabel: "session.login.usernameLabel",
      usernamePlaceholder: "session.login.usernamePlaceholder",
      submit: "session.login.submit",
      submitting: "session.login.submitting",
      missingFields: "session.login.missingFields",
      invalidCredentials: "session.login.invalidCredentials",
      unavailable: "session.login.unavailable",
    },
    register: {
      submit: "session.register.submit",
      submitting: "session.register.submitting",
      emailTaken: "session.register.emailTaken",
      invalidInput: "session.register.invalidInput",
    },
  },
} as const;

export type Strings = typeof strings;
