// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      runs: "layout.nav.runs",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
    runs: {
      title: "pages.runs.title",
      description: "pages.runs.description",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  fleet: {
    title: "fleet.title",
    description: "fleet.description",
    loading: "fleet.loading",
    empty: "fleet.empty",
    onlineLabel: "fleet.onlineLabel",
    offlineLabel: "fleet.offlineLabel",
    neverSeen: "fleet.neverSeen",
    revoke: "fleet.revoke",
    revokeConfirm: "fleet.revokeConfirm",
    osLabel: "fleet.osLabel",
    archLabel: "fleet.archLabel",
    versionLabel: "fleet.versionLabel",
    healthLabel: "fleet.healthLabel",
    unknownValue: "fleet.unknownValue",
    jobsHeading: "fleet.jobsHeading",
    jobsIdle: "fleet.jobsIdle",
    jobsBusy: "fleet.jobsBusy",
    status: {
      unspecified: "fleet.status.unspecified",
      offline: "fleet.status.offline",
      online: "fleet.status.online",
      needsUpdate: "fleet.status.needsUpdate",
      revoked: "fleet.status.revoked",
    },
    pairing: {
      heading: "fleet.pairing.heading",
      description: "fleet.pairing.description",
      nameLabel: "fleet.pairing.nameLabel",
      namePlaceholder: "fleet.pairing.namePlaceholder",
      submit: "fleet.pairing.submit",
      submitting: "fleet.pairing.submitting",
      codeHeading: "fleet.pairing.codeHeading",
      codeHelp: "fleet.pairing.codeHelp",
      publicKeyLabel: "fleet.pairing.publicKeyLabel",
      expiresLabel: "fleet.pairing.expiresLabel",
      copy: "fleet.pairing.copy",
    },
    onboard: {
      heading: "fleet.onboard.heading",
      description: "fleet.onboard.description",
      hostLabel: "fleet.onboard.hostLabel",
      hostPlaceholder: "fleet.onboard.hostPlaceholder",
      userLabel: "fleet.onboard.userLabel",
      userPlaceholder: "fleet.onboard.userPlaceholder",
      portLabel: "fleet.onboard.portLabel",
      portPlaceholder: "fleet.onboard.portPlaceholder",
      nameLabel: "fleet.onboard.nameLabel",
      namePlaceholder: "fleet.onboard.namePlaceholder",
      passwordLabel: "fleet.onboard.passwordLabel",
      passwordHelp: "fleet.onboard.passwordHelp",
      capabilitiesLabel: "fleet.onboard.capabilitiesLabel",
      capabilitiesPlaceholder: "fleet.onboard.capabilitiesPlaceholder",
      capabilitiesHelp: "fleet.onboard.capabilitiesHelp",
      revisionLabel: "fleet.onboard.revisionLabel",
      revisionHelp: "fleet.onboard.revisionHelp",
      submit: "fleet.onboard.submit",
      submitting: "fleet.onboard.submitting",
      progressHeading: "fleet.onboard.progressHeading",
      waiting: "fleet.onboard.waiting",
      successHeading: "fleet.onboard.successHeading",
      successBody: "fleet.onboard.successBody",
      viewNode: "fleet.onboard.viewNode",
      failureHeading: "fleet.onboard.failureHeading",
      retryHint: "fleet.onboard.retryHint",
      state: {
        unspecified: "fleet.onboard.state.unspecified",
        pending: "fleet.onboard.state.pending",
        sshSetup: "fleet.onboard.state.sshSetup",
        pushingScript: "fleet.onboard.state.pushingScript",
        bootstrapping: "fleet.onboard.state.bootstrapping",
        verifying: "fleet.onboard.state.verifying",
        succeeded: "fleet.onboard.state.succeeded",
        failed: "fleet.onboard.state.failed",
        cancelled: "fleet.onboard.state.cancelled",
      },
      stepStatus: {
        unspecified: "fleet.onboard.stepStatus.unspecified",
        started: "fleet.onboard.stepStatus.started",
        ok: "fleet.onboard.stepStatus.ok",
        skipped: "fleet.onboard.stepStatus.skipped",
        failed: "fleet.onboard.stepStatus.failed",
      },
      failure: {
        ssh_setup_failed: "fleet.onboard.failure.ssh_setup_failed",
        script_push_failed: "fleet.onboard.failure.script_push_failed",
        pairing_issue_failed: "fleet.onboard.failure.pairing_issue_failed",
        bootstrap_usage_error: "fleet.onboard.failure.bootstrap_usage_error",
        unsupported_platform: "fleet.onboard.failure.unsupported_platform",
        pairing_failed: "fleet.onboard.failure.pairing_failed",
        bootstrap_failed: "fleet.onboard.failure.bootstrap_failed",
        verify_online_failed: "fleet.onboard.failure.verify_online_failed",
        interrupted_by_restart: "fleet.onboard.failure.interrupted_by_restart",
        internal_error: "fleet.onboard.failure.internal_error",
        generic: "fleet.onboard.failure.generic",
      },
    },
  },
  runs: {
    title: "runs.title",
    description: "runs.description",
    loading: "runs.loading",
    empty: "runs.empty",
    nodeLabel: "runs.nodeLabel",
    jobLabel: "runs.jobLabel",
    startedLabel: "runs.startedLabel",
    durationLabel: "runs.durationLabel",
    exitLabel: "runs.exitLabel",
    progressLabel: "runs.progressLabel",
    etaLabel: "runs.etaLabel",
    etaPending: "runs.etaPending",
    view: "runs.view",
    close: "runs.close",
    cancel: "runs.cancel",
    cancelling: "runs.cancelling",
    cancelConfirm: "runs.cancelConfirm",
    outputHeading: "runs.outputHeading",
    outputEmpty: "runs.outputEmpty",
    artifactsHeading: "runs.artifactsHeading",
    artifactsEmpty: "runs.artifactsEmpty",
    download: "runs.download",
    status: {
      unspecified: "runs.status.unspecified",
      queued: "runs.status.queued",
      running: "runs.status.running",
      passed: "runs.status.passed",
      failed: "runs.status.failed",
      aborted: "runs.status.aborted",
    },
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
