// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $schema: "$schema",
  "Changes saved successfully": {
    "": "Changes saved successfully.",
  },
  "Disabled states retain the same geometry and clearly communicate that the action is unavailable": {
    "": "Disabled states retain the same geometry and clearly communicate that the action is unavailable.",
  },
  "Request in progress": "Request in progress",
  Saved: "Saved",
  app: {
    title: "app.title",
  },
  asset: "asset",
  children: "children",
  default: "default",
  detail: "detail",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  export: "export",
  fleet: {
    archLabel: "fleet.archLabel",
    bridgeReadinessActionResult: "fleet.bridgeReadinessActionResult",
    bridgeReadinessAllow: "fleet.bridgeReadinessAllow",
    bridgeReadinessAllowConfirm: "fleet.bridgeReadinessAllowConfirm",
    bridgeReadinessBrokerUnavailable: "fleet.bridgeReadinessBrokerUnavailable",
    bridgeReadinessCandidateBlocked: "fleet.bridgeReadinessCandidateBlocked",
    bridgeReadinessEndpoint: "fleet.bridgeReadinessEndpoint",
    bridgeReadinessFirewall: "fleet.bridgeReadinessFirewall",
    bridgeReadinessHeading: "fleet.bridgeReadinessHeading",
    bridgeReadinessMode: "fleet.bridgeReadinessMode",
    bridgeReadinessNotReady: "fleet.bridgeReadinessNotReady",
    bridgeReadinessPreview: "fleet.bridgeReadinessPreview",
    bridgeReadinessReady: "fleet.bridgeReadinessReady",
    bridgeReadinessRemediation: "fleet.bridgeReadinessRemediation",
    bridgeReadinessRevoke: "fleet.bridgeReadinessRevoke",
    bridgeReadinessRevokeConfirm: "fleet.bridgeReadinessRevokeConfirm",
    bridgeReadinessVerify: "fleet.bridgeReadinessVerify",
    description: "fleet.description",
    empty: "fleet.empty",
    emptyHeading: "fleet.emptyHeading",
    healthLabel: "fleet.healthLabel",
    jobsBusy: "fleet.jobsBusy",
    jobsHeading: "fleet.jobsHeading",
    jobsIdle: "fleet.jobsIdle",
    loading: "fleet.loading",
    machines: {
      applyPolicy: "fleet.machines.applyPolicy",
      archive: "fleet.machines.archive",
      attempts: "fleet.machines.attempts",
      auditEvents: "fleet.machines.auditEvents",
      cleanup: "fleet.machines.cleanup",
      cleanupPlanCannotAttribute: "fleet.machines.cleanupPlanCannotAttribute",
      cleanupPlanEmpty: "fleet.machines.cleanupPlanEmpty",
      cleanupPlanKeep: "fleet.machines.cleanupPlanKeep",
      cleanupPlanRemove: "fleet.machines.cleanupPlanRemove",
      cleanupStatus: "fleet.machines.cleanupStatus",
      clientFingerprint: "fleet.machines.clientFingerprint",
      closeDetails: "fleet.machines.closeDetails",
      confirmRemoval: "fleet.machines.confirmRemoval",
      currentNode: "fleet.machines.currentNode",
      description: "fleet.machines.description",
      detailHeading: "fleet.machines.detailHeading",
      details: "fleet.machines.details",
      empty: "fleet.machines.empty",
      heading: "fleet.machines.heading",
      hostFingerprint: "fleet.machines.hostFingerprint",
      hostTrust: "fleet.machines.hostTrust",
      loading: "fleet.machines.loading",
      noCleanup: "fleet.machines.noCleanup",
      noCurrentNode: "fleet.machines.noCurrentNode",
      notReady: "fleet.machines.notReady",
      policy: "fleet.machines.policy",
      policyReason: "fleet.machines.policyReason",
      ready: "fleet.machines.ready",
      remove: "fleet.machines.remove",
      removeConfirm: "fleet.machines.removeConfirm",
      replacementHostKey: "fleet.machines.replacementHostKey",
      reviewHostKey: "fleet.machines.reviewHostKey",
      revokeNode: "fleet.machines.revokeNode",
      state: "fleet.machines.state",
    },
    management: {
      close: "fleet.management.close",
      details: "fleet.management.details",
      endpoint: "fleet.management.endpoint",
      heading: "fleet.management.heading",
      overview: "fleet.management.overview",
      removeAction: "fleet.management.removeAction",
      removeBlocked: "fleet.management.removeBlocked",
      removeConfirm: "fleet.management.removeConfirm",
      removeDescription: "fleet.management.removeDescription",
      removeHeading: "fleet.management.removeHeading",
      revoke: "fleet.management.revoke",
      revokeDescription: "fleet.management.revokeDescription",
      revokeHeading: "fleet.management.revokeHeading",
      save: "fleet.management.save",
      saving: "fleet.management.saving",
      scopes: "fleet.management.scopes",
    },
    neverSeen: "fleet.neverSeen",
    offlineLabel: "fleet.offlineLabel",
    onboard: {
      addNode: "fleet.onboard.addNode",
      advancedHeading: "fleet.onboard.advancedHeading",
      advancedHelp: "fleet.onboard.advancedHelp",
      back: "fleet.onboard.back",
      capabilitiesHelp: "fleet.onboard.capabilitiesHelp",
      capabilitiesLabel: "fleet.onboard.capabilitiesLabel",
      capabilitiesPlaceholder: "fleet.onboard.capabilitiesPlaceholder",
      connectIntro: "fleet.onboard.connectIntro",
      controlPlaneUrlHelp: "fleet.onboard.controlPlaneUrlHelp",
      controlPlaneUrlLabel: "fleet.onboard.controlPlaneUrlLabel",
      controlPlaneUrlPlaceholder: "fleet.onboard.controlPlaneUrlPlaceholder",
      description: "fleet.onboard.description",
      endpointEvidence: "fleet.onboard.endpointEvidence",
      failure: {
        bootstrap_failed: "fleet.onboard.failure.bootstrap_failed",
        bootstrap_usage_error: "fleet.onboard.failure.bootstrap_usage_error",
        generic: "fleet.onboard.failure.generic",
        internal_error: "fleet.onboard.failure.internal_error",
        interrupted_by_restart: "fleet.onboard.failure.interrupted_by_restart",
        pairing_failed: "fleet.onboard.failure.pairing_failed",
        pairing_issue_failed: "fleet.onboard.failure.pairing_issue_failed",
        script_push_failed: "fleet.onboard.failure.script_push_failed",
        ssh_setup_failed: "fleet.onboard.failure.ssh_setup_failed",
        unsupported_platform: "fleet.onboard.failure.unsupported_platform",
        verify_online_failed: "fleet.onboard.failure.verify_online_failed",
      },
      failureHeading: "fleet.onboard.failureHeading",
      failureOutputHeading: "fleet.onboard.failureOutputHeading",
      heading: "fleet.onboard.heading",
      hideLogs: "fleet.onboard.hideLogs",
      hostLabel: "fleet.onboard.hostLabel",
      hostPlaceholder: "fleet.onboard.hostPlaceholder",
      includeOptionalHelp: "fleet.onboard.includeOptionalHelp",
      includeOptionalLabel: "fleet.onboard.includeOptionalLabel",
      loadingLogs: "fleet.onboard.loadingLogs",
      macHint: "fleet.onboard.macHint",
      moreLabel: "fleet.onboard.moreLabel",
      nameLabel: "fleet.onboard.nameLabel",
      namePlaceholder: "fleet.onboard.namePlaceholder",
      next: "fleet.onboard.next",
      noLogs: "fleet.onboard.noLogs",
      passwordHide: "fleet.onboard.passwordHide",
      passwordLabel: "fleet.onboard.passwordLabel",
      passwordOptionalNote: "fleet.onboard.passwordOptionalNote",
      passwordShow: "fleet.onboard.passwordShow",
      portLabel: "fleet.onboard.portLabel",
      portPlaceholder: "fleet.onboard.portPlaceholder",
      progressHeading: "fleet.onboard.progressHeading",
      provisionSudoHelp: "fleet.onboard.provisionSudoHelp",
      provisionSudoLabel: "fleet.onboard.provisionSudoLabel",
      reachabilityLan: "fleet.onboard.reachabilityLan",
      reachabilityManual: "fleet.onboard.reachabilityManual",
      reachabilityModeHelp: "fleet.onboard.reachabilityModeHelp",
      reachabilityModeLabel: "fleet.onboard.reachabilityModeLabel",
      reachabilityTunnel: "fleet.onboard.reachabilityTunnel",
      removeSaved: "fleet.onboard.removeSaved",
      retryHint: "fleet.onboard.retryHint",
      retrySaved: "fleet.onboard.retrySaved",
      retryUnavailable: "fleet.onboard.retryUnavailable",
      reviewSummary: "fleet.onboard.reviewSummary",
      revisionHelp: "fleet.onboard.revisionHelp",
      revisionLabel: "fleet.onboard.revisionLabel",
      savedFailureDetail: "fleet.onboard.savedFailureDetail",
      savedFailuresHeading: "fleet.onboard.savedFailuresHeading",
      setupPresetHelp: "fleet.onboard.setupPresetHelp",
      setupPresetLabel: "fleet.onboard.setupPresetLabel",
      setupPresetPlaceholder: "fleet.onboard.setupPresetPlaceholder",
      setupResourcesHelp: "fleet.onboard.setupResourcesHelp",
      setupResourcesLabel: "fleet.onboard.setupResourcesLabel",
      setupResourcesPlaceholder: "fleet.onboard.setupResourcesPlaceholder",
      setupScenariosHelp: "fleet.onboard.setupScenariosHelp",
      setupScenariosLabel: "fleet.onboard.setupScenariosLabel",
      setupScenariosPlaceholder: "fleet.onboard.setupScenariosPlaceholder",
      sourceModeHelp: "fleet.onboard.sourceModeHelp",
      sourceModeLabel: "fleet.onboard.sourceModeLabel",
      sourceModeWarning: "fleet.onboard.sourceModeWarning",
      sourceSummaryPinned: "fleet.onboard.sourceSummaryPinned",
      sourceSummaryWorkingTree: "fleet.onboard.sourceSummaryWorkingTree",
      state: {
        bootstrapping: "fleet.onboard.state.bootstrapping",
        cancelled: "fleet.onboard.state.cancelled",
        failed: "fleet.onboard.state.failed",
        paired: "fleet.onboard.state.paired",
        pending: "fleet.onboard.state.pending",
        pushingScript: "fleet.onboard.state.pushingScript",
        sshSetup: "fleet.onboard.state.sshSetup",
        succeeded: "fleet.onboard.state.succeeded",
        unspecified: "fleet.onboard.state.unspecified",
        verifying: "fleet.onboard.state.verifying",
      },
      stepConnect: "fleet.onboard.stepConnect",
      stepIndicator: "fleet.onboard.stepIndicator",
      stepReview: "fleet.onboard.stepReview",
      stepStatus: {
        failed: "fleet.onboard.stepStatus.failed",
        ok: "fleet.onboard.stepStatus.ok",
        skipped: "fleet.onboard.stepStatus.skipped",
        started: "fleet.onboard.stepStatus.started",
        unspecified: "fleet.onboard.stepStatus.unspecified",
      },
      stepUnlock: "fleet.onboard.stepUnlock",
      submit: "fleet.onboard.submit",
      submitting: "fleet.onboard.submitting",
      successBody: "fleet.onboard.successBody",
      successHeading: "fleet.onboard.successHeading",
      unlockIntro: "fleet.onboard.unlockIntro",
      userLabel: "fleet.onboard.userLabel",
      userPlaceholder: "fleet.onboard.userPlaceholder",
      viewLogs: "fleet.onboard.viewLogs",
      viewNode: "fleet.onboard.viewNode",
      waiting: "fleet.onboard.waiting",
    },
    onlineLabel: "fleet.onlineLabel",
    osLabel: "fleet.osLabel",
    pairing: {
      approvalError: "fleet.pairing.approvalError",
      approve: "fleet.pairing.approve",
      approving: "fleet.pairing.approving",
      codeHeading: "fleet.pairing.codeHeading",
      codeHelp: "fleet.pairing.codeHelp",
      confirmationHelp: "fleet.pairing.confirmationHelp",
      confirmationWords: "fleet.pairing.confirmationWords",
      copy: "fleet.pairing.copy",
      description: "fleet.pairing.description",
      disclosureLabel: "fleet.pairing.disclosureLabel",
      disclosureNote: "fleet.pairing.disclosureNote",
      expiresLabel: "fleet.pairing.expiresLabel",
      heading: "fleet.pairing.heading",
      nameLabel: "fleet.pairing.nameLabel",
      namePlaceholder: "fleet.pairing.namePlaceholder",
      noRequests: "fleet.pairing.noRequests",
      permissionFull: "fleet.pairing.permissionFull",
      permissionLabel: "fleet.pairing.permissionLabel",
      permissionOperate: "fleet.pairing.permissionOperate",
      permissionReadOnly: "fleet.pairing.permissionReadOnly",
      permissionScopes: "fleet.pairing.permissionScopes",
      permissionWithholds: "fleet.pairing.permissionWithholds",
      publicKeyLabel: "fleet.pairing.publicKeyLabel",
      reject: "fleet.pairing.reject",
      rejecting: "fleet.pairing.rejecting",
      requestName: "fleet.pairing.requestName",
      requestPlatform: "fleet.pairing.requestPlatform",
      requestsDescription: "fleet.pairing.requestsDescription",
      requestsHeading: "fleet.pairing.requestsHeading",
      submit: "fleet.pairing.submit",
      submitting: "fleet.pairing.submitting",
      wordsMatch: "fleet.pairing.wordsMatch",
    },
    readiness: {
      absent: "fleet.readiness.absent",
      blocked: "fleet.readiness.blocked",
      channel: "fleet.readiness.channel",
      compatible: "fleet.readiness.compatible",
      dispatch: "fleet.readiness.dispatch",
      fresh: "fleet.readiness.fresh",
      heartbeat: "fleet.readiness.heartbeat",
      held: "fleet.readiness.held",
      missing: "fleet.readiness.missing",
      present: "fleet.readiness.present",
      protocol: "fleet.readiness.protocol",
      ready: "fleet.readiness.ready",
      registry: "fleet.readiness.registry",
      stale: "fleet.readiness.stale",
      updateRequired: "fleet.readiness.updateRequired",
    },
    revoke: "fleet.revoke",
    revokeConfirm: "fleet.revokeConfirm",
    status: {
      needsUpdate: "fleet.status.needsUpdate",
      offline: "fleet.status.offline",
      online: "fleet.status.online",
      revoked: "fleet.status.revoked",
      unspecified: "fleet.status.unspecified",
    },
    title: "fleet.title",
    unknownValue: "fleet.unknownValue",
    versionLabel: "fleet.versionLabel",
  },
  format: "format",
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    statusLabel: "health.statusLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  iconName: "iconName",
  id: "id",
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      rollouts: "layout.nav.rollouts",
      runs: "layout.nav.runs",
      sessions: "layout.nav.sessions",
      settings: "layout.nav.settings",
      setup: "layout.nav.setup",
      trust: "layout.nav.trust",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  mode: "mode",
  module: "module",
  name: "name",
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  pages: {
    dashboard: {
      description: "pages.dashboard.description",
      title: "pages.dashboard.title",
    },
    runs: {
      description: "pages.runs.description",
      title: "pages.runs.title",
    },
    settings: {
      localeHeading: "pages.settings.localeHeading",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
  },
  path: "path",
  react: "react",
  resolvedAt: "resolvedAt",
  role: "role",
  runs: {
    artifactsEmpty: "runs.artifactsEmpty",
    artifactsHeading: "runs.artifactsHeading",
    cancel: "runs.cancel",
    cancelConfirm: "runs.cancelConfirm",
    cancelling: "runs.cancelling",
    close: "runs.close",
    description: "runs.description",
    download: "runs.download",
    durationLabel: "runs.durationLabel",
    empty: "runs.empty",
    etaLabel: "runs.etaLabel",
    etaPending: "runs.etaPending",
    exitLabel: "runs.exitLabel",
    jobLabel: "runs.jobLabel",
    loading: "runs.loading",
    nodeLabel: "runs.nodeLabel",
    outputEmpty: "runs.outputEmpty",
    outputHeading: "runs.outputHeading",
    progressLabel: "runs.progressLabel",
    startedLabel: "runs.startedLabel",
    status: {
      aborted: "runs.status.aborted",
      failed: "runs.status.failed",
      passed: "runs.status.passed",
      queued: "runs.status.queued",
      running: "runs.status.running",
      unspecified: "runs.status.unspecified",
    },
    title: "runs.title",
    view: "runs.view",
  },
  selector: "selector",
  session: {
    accountHeading: "session.accountHeading",
    firstTimeNote: "session.firstTimeNote",
    login: {
      emailLabel: "session.login.emailLabel",
      emailPlaceholder: "session.login.emailPlaceholder",
      intro: "session.login.intro",
      invalidCredentials: "session.login.invalidCredentials",
      missingFields: "session.login.missingFields",
      passwordLabel: "session.login.passwordLabel",
      passwordPlaceholder: "session.login.passwordPlaceholder",
      submit: "session.login.submit",
      submitting: "session.login.submitting",
      tabCreate: "session.login.tabCreate",
      tabSignIn: "session.login.tabSignIn",
      title: "session.login.title",
      unavailable: "session.login.unavailable",
      usernameLabel: "session.login.usernameLabel",
      usernamePlaceholder: "session.login.usernamePlaceholder",
    },
    register: {
      emailTaken: "session.register.emailTaken",
      invalidInput: "session.register.invalidInput",
      submit: "session.register.submit",
      submitting: "session.register.submitting",
    },
    screenIntro: "session.screenIntro",
    screenTitle: "session.screenTitle",
    signOut: "session.signOut",
    signedIn: "session.signedIn",
    signedInAs: "session.signedInAs",
  },
  size: "size",
  status: "status",
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  title: "title",
  value: "value",
  variant: "variant",
  version: "version",
} as const;

export type Strings = typeof strings;
