package main

import (
	"fmt"
	"net/http"
	"strings"
	
	"financial-calculators-hub/lib"
	"github.com/jung-kurt/gofpdf"
)

// formatMoney formats a float as currency with comma separators
func formatMoney(amount float64) string {
	formatted := fmt.Sprintf("%.2f", amount)
	parts := strings.Split(formatted, ".")
	intPart := parts[0]
	decPart := ""
	if len(parts) > 1 {
		decPart = parts[1]
	}
	
	// Add comma separators
	var result []rune
	for i, r := range intPart {
		if i > 0 && (len(intPart)-i)%3 == 0 {
			result = append(result, ',')
		}
		result = append(result, r)
	}
	
	return "$" + string(result) + "." + decPart
}

func exportFIREPDF(w http.ResponseWriter, input lib.FIREInput, result lib.FIREResult) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	
	// Title
	pdf.SetFont("Arial", "B", 20)
	pdf.Cell(0, 10, "FIRE Calculation Report")
	pdf.Ln(15)
	
	// Input section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Input Parameters")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(60, 8, "Current Age:")
	pdf.Cell(0, 8, fmt.Sprintf("%.0f years", input.CurrentAge))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Current Savings:")
	pdf.Cell(0, 8, fmt.Sprintf("$%.2f", input.CurrentSavings))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Annual Income:")
	pdf.Cell(0, 8, formatMoney(input.AnnualIncome))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Annual Expenses:")
	pdf.Cell(0, 8, formatMoney(input.AnnualExpenses))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Savings Rate:")
	pdf.Cell(0, 8, fmt.Sprintf("%.1f%%", input.SavingsRate))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Expected Return:")
	pdf.Cell(0, 8, fmt.Sprintf("%.1f%%", input.ExpectedReturn))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Withdrawal Rate:")
	pdf.Cell(0, 8, fmt.Sprintf("%.1f%%", input.TargetWithdrawalRate))
	pdf.Ln(15)
	
	// Results section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Calculation Results")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 100, 0)
	pdf.Cell(60, 8, "Retirement Age:")
	pdf.Cell(0, 8, fmt.Sprintf("%.1f years", result.RetirementAge))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Years to Retirement:")
	pdf.Cell(0, 8, fmt.Sprintf("%.1f years", result.YearsToRetirement))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Target Nest Egg:")
	pdf.Cell(0, 8, formatMoney(result.TargetNestEgg))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Monthly Savings Required:")
	pdf.Cell(0, 8, formatMoney(result.MonthlySavingsReq))
	pdf.Ln(15)
	
	// Projected nest egg section
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Projected Nest Egg by Age")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 11)
	count := 0
	for age, amount := range result.ProjectedByAge {
		if count >= 10 {
			break // Limit to first 10 entries for space
		}
		pdf.Cell(40, 7, fmt.Sprintf("Age %d:", age))
		pdf.Cell(0, 7, formatMoney(amount))
		pdf.Ln(7)
		count++
	}
	
	// Footer
	pdf.SetY(-30)
	pdf.SetFont("Arial", "I", 10)
	pdf.SetTextColor(128, 128, 128)
	pdf.Cell(0, 10, "Generated by Financial Calculators Hub")
	
	// Output PDF
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", "attachment; filename=fire-calculation.pdf")
	pdf.Output(w)
}

func exportCompoundInterestPDF(w http.ResponseWriter, input lib.CompoundInterestInput, result lib.CompoundInterestResult) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	
	// Title
	pdf.SetFont("Arial", "B", 20)
	pdf.Cell(0, 10, "Compound Interest Report")
	pdf.Ln(15)
	
	// Input section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Input Parameters")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(60, 8, "Principal Amount:")
	pdf.Cell(0, 8, formatMoney(input.Principal))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Annual Rate:")
	pdf.Cell(0, 8, fmt.Sprintf("%.2f%%", input.AnnualRate))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Investment Period:")
	pdf.Cell(0, 8, fmt.Sprintf("%.0f years", input.Years))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Monthly Contribution:")
	pdf.Cell(0, 8, formatMoney(input.MonthlyContribution))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Compound Frequency:")
	pdf.Cell(0, 8, input.CompoundFrequency)
	pdf.Ln(15)
	
	// Results section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Final Results")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 100, 0)
	pdf.Cell(60, 8, "Final Amount:")
	pdf.Cell(0, 8, formatMoney(result.FinalAmount))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Total Contributions:")
	pdf.Cell(0, 8, formatMoney(result.TotalContributions))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Total Interest Earned:")
	pdf.Cell(0, 8, formatMoney(result.TotalInterest))
	pdf.Ln(15)
	
	// Year by year breakdown (limited)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Year-by-Year Growth")
	pdf.Ln(10)
	
	// Table header
	pdf.SetFont("Arial", "B", 11)
	pdf.Cell(20, 7, "Year")
	pdf.Cell(45, 7, "Balance")
	pdf.Cell(45, 7, "Contribution")
	pdf.Cell(45, 7, "Interest")
	pdf.Ln(7)
	
	pdf.SetFont("Arial", "", 10)
	for i, year := range result.YearByYear {
		if i >= 10 && i < len(result.YearByYear)-1 {
			continue // Skip middle years if more than 10
		}
		pdf.Cell(20, 6, fmt.Sprintf("%d", year.Year))
		pdf.Cell(45, 6, formatMoney(year.Balance))
		pdf.Cell(45, 6, formatMoney(year.Contribution))
		pdf.Cell(45, 6, formatMoney(year.Interest))
		pdf.Ln(6)
	}
	
	// Footer
	pdf.SetY(-30)
	pdf.SetFont("Arial", "I", 10)
	pdf.SetTextColor(128, 128, 128)
	pdf.Cell(0, 10, "Generated by Financial Calculators Hub")
	
	// Output PDF
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", "attachment; filename=compound-interest.pdf")
	pdf.Output(w)
}

func exportMortgagePDF(w http.ResponseWriter, input lib.MortgageInput, result lib.MortgageResult) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	
	// Title
	pdf.SetFont("Arial", "B", 20)
	pdf.Cell(0, 10, "Mortgage Amortization Report")
	pdf.Ln(15)
	
	// Input section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Loan Parameters")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(60, 8, "Loan Amount:")
	pdf.Cell(0, 8, formatMoney(input.LoanAmount))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Annual Interest Rate:")
	pdf.Cell(0, 8, fmt.Sprintf("%.2f%%", input.AnnualRate))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Loan Term:")
	pdf.Cell(0, 8, fmt.Sprintf("%.0f years", input.Years))
	pdf.Ln(8)
	
	if input.DownPayment > 0 {
		pdf.Cell(60, 8, "Down Payment:")
		pdf.Cell(0, 8, formatMoney(input.DownPayment))
		pdf.Ln(8)
	}
	
	if input.ExtraMonthlyPayment > 0 {
		pdf.Cell(60, 8, "Extra Monthly Payment:")
		pdf.Cell(0, 8, formatMoney(input.ExtraMonthlyPayment))
		pdf.Ln(8)
	}
	pdf.Ln(10)
	
	// Results section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Payment Summary")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 100, 0)
	pdf.Cell(60, 8, "Monthly Payment:")
	pdf.Cell(0, 8, formatMoney(result.MonthlyPayment))
	pdf.Ln(8)
	
	pdf.SetTextColor(200, 0, 0)
	pdf.Cell(60, 8, "Total Interest Paid:")
	pdf.Cell(0, 8, formatMoney(result.TotalInterest))
	pdf.Ln(8)
	
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(60, 8, "Total Amount Paid:")
	pdf.Cell(0, 8, formatMoney(result.TotalPaid))
	pdf.Ln(8)
	
	pdf.Cell(60, 8, "Payoff Date:")
	pdf.Cell(0, 8, result.PayoffDate)
	pdf.Ln(15)
	
	// Amortization schedule (first year only for space)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "First Year Amortization Schedule")
	pdf.Ln(10)
	
	// Table header
	pdf.SetFont("Arial", "B", 10)
	pdf.Cell(20, 6, "Month")
	pdf.Cell(35, 6, "Payment")
	pdf.Cell(35, 6, "Principal")
	pdf.Cell(35, 6, "Interest")
	pdf.Cell(45, 6, "Balance")
	pdf.Ln(6)
	
	pdf.SetFont("Arial", "", 9)
	for i, payment := range result.AmortizationSchedule {
		if i >= 12 {
			break // Only show first year
		}
		pdf.Cell(20, 5, fmt.Sprintf("%d", payment.Month))
		pdf.Cell(35, 5, formatMoney(payment.Payment))
		pdf.Cell(35, 5, formatMoney(payment.Principal))
		pdf.Cell(35, 5, formatMoney(payment.Interest))
		pdf.Cell(45, 5, formatMoney(payment.RemainingBalance))
		pdf.Ln(5)
	}
	
	// Footer
	pdf.SetY(-30)
	pdf.SetFont("Arial", "I", 10)
	pdf.SetTextColor(128, 128, 128)
	pdf.Cell(0, 10, "Generated by Financial Calculators Hub")
	
	// Output PDF
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", "attachment; filename=mortgage-amortization.pdf")
	pdf.Output(w)
}