// This file is generated by icon spritesheet generator

export const iconNames = [
  "YouTube",
  "X",
  "Reddit",
  "LinkedIn",
  "Instagram",
  "Google",
  "GitHub",
  "Facebook",
  "Docker",
  "Discord",
  "DefaultSocial",
] as const

export type IconName = typeof iconNames[number]
