// This file is generated by icon spritesheet generator

export const iconNames = [
  "WrapText",
  "WholeWord",
  "Underline",
  "Strikethrough",
  "Regex",
  "Quote",
  "ListNumber",
  "ListCheck",
  "ListBullet",
  "List",
  "Italic",
  "Header6",
  "Header5",
  "Header4",
  "Header3",
  "Header2",
  "Header1",
  "Header",
  "CaseSensitive",
  "Bold",
] as const;

export type IconName = typeof iconNames[number]
