run:
  timeout: 5m

linters:
  enable:
    - funlen
    - cyclop
    - gocognit

linters-settings:
  funlen:
    lines: 180
    statements: 80
  cyclop:
    max-complexity: 26
  gocognit:
    min-complexity: 41
