package operatingmode

func holisticLoopDefinition() Definition {
	return buildInitiativeMode(initiativeModeSpec{
		Mode:        ModeHolisticLoop,
		Label:       "Holistic Loop",
		Description: "Investigate → plan → execute → review cycles across the whole initiative. Use when scope is exploratory and the plan must be revised as you learn.",
		BestFor: []string{
			"Coupled work where items can't be validated in isolation",
			"The right plan can only be authored after cross-item investigation",
			"Item shape will shift as the work reveals what items actually are",
			"Replanning is expected — the first plan will be wrong about something material",
		},
		NotFor: []string{
			"Items are independent and stable — use item-level for parallelism",
			"A stable plan already exists and just needs to be drained — use phased-plan-drain",
			"Work is small enough to fit in a single backlog item",
		},
		Tradeoffs: []string{
			"One plan, not N plans — lower replanning cost than item-level for coupled work",
			"Higher per-run cost than item-level",
			"Loses parallelism — only one round runs at a time",
			"Initiative-level acceptance review instead of per-item review",
		},
		WhenInDoubtPickInstead: ModeItemLevel,
		RunStrategy:            RunStrategyOperatorGatedLoop,
		ArtifactRoot:           "modes/holistic-loop",
		PromptCatalogPrefix:    "swarm-manager-holistic-loop",
		DefaultProfileKey:      ProfileDeepWork,
		StartPhase:             "investigate",
		Terminal:               []Phase{"reconcile"},
		Transitions: map[Phase][]Phase{
			"investigate": {"plan"},
			"plan":        {"execute"},
			"execute":     {"review", "investigate"},
			"review":      {"reconcile"},
		},
		TransitionRules: map[Phase][]TransitionRule{
			"execute": {
				{
					When: TransitionCondition{
						Kind:       TransitionConditionPayloadBool,
						PayloadKey: payloadReplanNeeded,
						BoolValue:  true,
					},
					Next: []Phase{"investigate"},
				},
				{
					When: TransitionCondition{Kind: TransitionConditionAlways},
					Next: []Phase{"review"},
				},
			},
		},
		Phases: []initiativePhaseSpec{
			{
				Phase:           "investigate",
				Kind:            PhaseKindInvestigate,
				Purpose:         "holistic_loop_investigate",
				PromptTitle:     "Holistic Loop Investigate",
				PromptTrigger:   "Operator starts holistic-loop investigate phase",
				PromptPurpose:   "Investigate initiative-wide code, backlog, and system state and produce holistic findings.",
				ProfileKey:      ProfileDeepWork,
				OutputArtifacts: []ArtifactDefinition{requiredOutputArtifact("modes/holistic-loop/findings.md", "text/markdown")},
			},
			{
				Phase:           "plan",
				Kind:            PhaseKindInvestigate,
				Purpose:         "holistic_loop_plan",
				PromptTitle:     "Holistic Loop Plan",
				PromptTrigger:   "Operator starts holistic-loop plan phase",
				PromptPurpose:   "Produce or update the initiative-wide implementation plan and readiness assessment.",
				ProfileKey:      ProfileDeepWork,
				OutputArtifacts: []ArtifactDefinition{requiredOutputArtifact("modes/holistic-loop/initiative-plan.md", "text/markdown")},
			},
			{
				Phase:         "execute",
				Kind:          PhaseKindExecute,
				Purpose:       "holistic_loop_execute",
				PromptTitle:   "Holistic Loop Execute",
				PromptTrigger: "Operator starts holistic-loop execute phase",
				PromptPurpose: "Execute against the initiative-wide plan and report whether replanning is needed.",
				ProfileKey:    ProfileDeepWork,
				WritesRepo:    true,
				Metrics:       PhaseMetricsSpec{CountsReplanSample: true},
			},
			{
				Phase:            "review",
				Kind:             PhaseKindReview,
				Purpose:          "holistic_loop_review",
				PromptTitle:      "Holistic Loop Acceptance Review",
				PromptTrigger:    "Operator starts holistic-loop review phase",
				PromptPurpose:    "Evaluate holistic-loop results against acceptance criteria and produce an acceptance verdict.",
				ProfileKey:       ProfileAnalysis,
				RequiresVerdict:  true,
				RequiresCriteria: true,
				Metrics:          PhaseMetricsSpec{CountsAcceptanceSample: true},
			},
			{
				Phase:               "reconcile",
				Kind:                PhaseKindReconcile,
				AutoStartAfter:      []Phase{"review"},
				Purpose:             "holistic_loop_reconcile",
				PromptSuffix:        "reconcile",
				PromptTitle:         "Holistic Loop Backlog Reconcile",
				PromptTrigger:       "Round refresher auto-starts holistic-loop reconcile after review completes",
				PromptPurpose:       "Read prior round artifacts and propose backlog mutations that align the initiative with the work just completed.",
				ProfileKey:          ProfileAnalysis,
				RequiresBacklogSync: true,
			},
		},
	})
}
