import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { StatusBadge } from "../components/ui/status-badge";
import { getRampJson } from "../api/ramp";
import { strings } from "../consts/strings";
import { useTranslation } from "../i18n";
import { ReadinessSurface } from "../features/delivery/ExperienceSurfaces";
type Rung = { id?: string; title?: string; state?: string; owner?: string; next_action?: string; obligation?: string };
export function ReadinessPage() { const { t } = useTranslation(); const [rungs, setRungs] = useState<Rung[]>([]); const [error, setError] = useState(""); useEffect(() => { void getRampJson<{ rungs?: Rung[] }>("/android/readiness").then((value) => setRungs(value.rungs || [])).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : t(strings.errors.unknown))); }, [t]); return <div className="flex flex-col gap-6"><section className="flex flex-col gap-4" aria-labelledby="readiness-heading"><div><h2 id="readiness-heading" className="text-2xl font-semibold">{t(strings.pages.readiness.title)}</h2><p className="text-app-muted-foreground">{t(strings.pages.readiness.description)}</p></div>{error && <p role="alert" className="text-red-600">{error}</p>}<div className="grid gap-4 lg:grid-cols-2">{rungs.map((rung) => <Card key={rung.id}><CardHeader><CardTitle className="flex justify-between gap-3"><span>{rung.title || rung.id}</span><StatusBadge tone={rung.state === "ready" ? "success" : "warning"}>{rung.state || t(strings.pages.readiness.unknown)}</StatusBadge></CardTitle></CardHeader><CardContent className="space-y-1 text-sm"><p>{t(strings.pages.readiness.owner)} {rung.owner}</p><p>{t(strings.pages.readiness.next)} {rung.next_action}</p>{rung.obligation && <p className="text-app-muted-foreground">{t(strings.pages.readiness.obligation)} {rung.obligation}</p>}</CardContent></Card>)}</div></section><ReadinessSurface /></div>; }
