package studio

import (
	"experience-manager/internal/module"

	contractconnect "github.com/vrooli/vrooli/packages/proto/gen/go/experience-manager/v1/contract/contract_v1connect"
)

func sessionSchema() *module.Schema {
	return &module.Schema{Type: "object", Properties: map[string]string{"session_id": "string"}}
}

var Endpoints = []module.EndpointDescriptor{
	{ID: "studio_start_authoring_session", Path: contractconnect.StudioSessionServiceStartAuthoringSessionProcedure, Method: "POST", Summary: "Start an experience spec authoring session", Description: "Creates a persisted authoring session for form-shaped experience/ edits.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "path": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"session": "AuthoringSession"}}},
	{ID: "studio_submit_page", Path: contractconnect.StudioSessionServiceSubmitPageProcedure, Method: "POST", Summary: "Submit a page form into an authoring session", Description: "Stores a typed PageForm draft for preview/apply.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"session_id": "string", "page": "PageForm"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"session": "AuthoringSession", "page": "PageDraft"}}},
	{ID: "studio_preview_session", Path: contractconnect.StudioSessionServicePreviewSessionProcedure, Method: "POST", Summary: "Preview authoring session diffs", Description: "Computes file diffs and parser validation for the session without touching the target tree.", Category: "studio", Request: sessionSchema(), Response: &module.Schema{Type: "object", Properties: map[string]string{"diffs": "array<FileDiff>", "validation": "ValidateScenarioResponse"}}},
	{ID: "studio_apply_session", Path: contractconnect.StudioSessionServiceApplySessionProcedure, Method: "POST", Summary: "Apply an authoring session", Description: "Writes previewed experience/ files only after the parser reports zero error findings.", Category: "studio", Request: sessionSchema(), Response: &module.Schema{Type: "object", Properties: map[string]string{"diffs": "array<FileDiff>", "validation": "ValidateScenarioResponse"}}},
	{ID: "studio_discard_session", Path: contractconnect.StudioSessionServiceDiscardSessionProcedure, Method: "POST", Summary: "Discard an authoring session", Description: "Deletes the persisted authoring session and its page drafts.", Category: "studio", Request: sessionSchema(), Response: &module.Schema{Type: "object", Properties: map[string]string{"discarded": "boolean"}}},
	{ID: "studio_list_spec", Path: contractconnect.StudioSessionServiceListSpecProcedure, Method: "POST", Summary: "List experience spec documents", Description: "Lists pages, journeys, and components from a scenario's parsed experience index.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "path": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"pages": "array<SpecDocument>", "journeys": "array<SpecDocument>", "components": "array<SpecDocument>"}}},
	{ID: "studio_show_spec", Path: contractconnect.StudioSessionServiceShowSpecProcedure, Method: "POST", Summary: "Show a page spec", Description: "Returns one page document as JSON.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "page": "string", "path": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"json": "string"}}},
	{ID: "studio_list_evidence", Path: contractconnect.StudioSessionServiceListEvidenceProcedure, Method: "POST", Summary: "List reconciliation evidence", Description: "Returns persisted per-claim reconciliation evidence rows for a page.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "page": "string", "claim": "string", "path": "string", "limit": "int"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"evidence": "array<ReconciliationEvidence>"}}},
	{ID: "studio_suggest_bindings", Path: contractconnect.StudioSessionServiceSuggestBindingsProcedure, Method: "POST", Summary: "Suggest page bindings", Description: "Suggests testid/role bindings from existing spec bindings and latest reconciliation evidence.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "page": "string", "path": "string", "limit": "int"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"suggestions": "array<BindingSuggestion>"}}},
	{ID: "studio_render_spec", Path: contractconnect.StudioSessionServiceRenderSpecProcedure, Method: "POST", Summary: "Render a deterministic page wireframe", Description: "Renders one page spec to stable HTML for workshop review. Image mode degrades to wireframe-only when image-tools is unavailable.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "page": "string", "path": "string", "mode": "string"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"html": "string", "artifact_path": "string", "degraded_reason": "string"}}},
	{ID: "studio_compare_variants", Path: contractconnect.StudioSessionServiceCompareVariantsProcedure, Method: "POST", Summary: "Compare rendered page variants", Description: "Renders supplied page-form variants side by side as deterministic workshop HTML.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "page": "string", "path": "string", "mode": "string", "variants": "array<SpecVariant>"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"html": "string", "artifact_path": "string", "variants": "array<RenderedVariant>"}}},
	{ID: "studio_promote_variant", Path: contractconnect.StudioSessionServicePromoteVariantProcedure, Method: "POST", Summary: "Promote a page variant into the spec", Description: "Writes the selected variant through parser-clean apply semantics and returns diffs plus validation.", Category: "studio", Request: &module.Schema{Type: "object", Properties: map[string]string{"scenario": "string", "page": "string", "path": "string", "variant": "SpecVariant"}}, Response: &module.Schema{Type: "object", Properties: map[string]string{"variant": "RenderedVariant", "diffs": "array<FileDiff>", "validation": "ValidateScenarioResponse"}}},
}
