// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      settings: "layout.nav.settings",
      substrate: "layout.nav.substrate",
      coverage: "layout.nav.coverage",
      condition: "layout.nav.condition",
      focus: "layout.nav.focus",
      designLanguage: "layout.nav.designLanguage",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      eyebrow: "pages.dashboard.eyebrow",
      reading: "pages.dashboard.reading",
      sourceUnavailable: "pages.dashboard.sourceUnavailable",
      headlineLabel: "pages.dashboard.headlineLabel",
      statMissingCells: "pages.dashboard.statMissingCells",
      statTrustedReadings: "pages.dashboard.statTrustedReadings",
      statRankedFindings: "pages.dashboard.statRankedFindings",
      statWeakestConfidence: "pages.dashboard.statWeakestConfidence",
      confidenceHeading: "pages.dashboard.confidenceHeading",
      confidenceNote: "pages.dashboard.confidenceNote",
      findingsHeading: "pages.dashboard.findingsHeading",
      findingsNote: "pages.dashboard.findingsNote",
      findingsEmptyTitle: "pages.dashboard.findingsEmptyTitle",
      findingsEmptyBody: "pages.dashboard.findingsEmptyBody",
      findingsUnavailableTitle: "pages.dashboard.findingsUnavailableTitle",
      findingsUnavailableBody: "pages.dashboard.findingsUnavailableBody",
      sourcesHeading: "pages.dashboard.sourcesHeading",
      sourcesNote: "pages.dashboard.sourcesNote",
      sourcesEmptyTitle: "pages.dashboard.sourcesEmptyTitle",
      sourcesEmptyBody: "pages.dashboard.sourcesEmptyBody",
      instrumentHeading: "pages.dashboard.instrumentHeading",
      instrumentNote: "pages.dashboard.instrumentNote",
    },
    settings: {
      title: "pages.settings.title",
      localeHeading: "pages.settings.localeHeading",
    },
    designLanguage: {
      title: "pages.designLanguage.title",
      description: "pages.designLanguage.description",
      plateHeading: "pages.designLanguage.plateHeading",
      plateNote: "pages.designLanguage.plateNote",
      lampHeading: "pages.designLanguage.lampHeading",
      lampNote: "pages.designLanguage.lampNote",
      ringHeading: "pages.designLanguage.ringHeading",
      ringNote: "pages.designLanguage.ringNote",
      statHeading: "pages.designLanguage.statHeading",
      statNote: "pages.designLanguage.statNote",
      gridHeading: "pages.designLanguage.gridHeading",
      gridNote: "pages.designLanguage.gridNote",
      blindHeading: "pages.designLanguage.blindHeading",
      blindNote: "pages.designLanguage.blindNote",
      fixtureCaption: "pages.designLanguage.fixtureCaption",
      kitId: "pages.designLanguage.kitId",
      statRungsCovered: "pages.designLanguage.statRungsCovered",
      statCellsBlind: "pages.designLanguage.statCellsBlind",
      statDevices: "pages.designLanguage.statDevices",
      statNotComputable: "pages.designLanguage.statNotComputable",
      blindNotEnumerated: "pages.designLanguage.blindNotEnumerated",
      blindNoPredictive: "pages.designLanguage.blindNoPredictive",
      blindNoEvidence: "pages.designLanguage.blindNoEvidence",
      blindAgeDays: "pages.designLanguage.blindAgeDays",
      blindOpened: "pages.designLanguage.blindOpened",
    },
    substrate: {
      eyebrow: "pages.substrate.eyebrow",
      title: "pages.substrate.title",
      description: "pages.substrate.description",
      reading: "pages.substrate.reading",
      sourceUnavailable: "pages.substrate.sourceUnavailable",
      unavailableTitle: "pages.substrate.unavailableTitle",
      unavailableBody: "pages.substrate.unavailableBody",
      noDevicesTitle: "pages.substrate.noDevicesTitle",
      noDevicesBody: "pages.substrate.noDevicesBody",
      headlineLabel: "pages.substrate.headlineLabel",
      statLadderCoverage: "pages.substrate.statLadderCoverage",
      statRungsCovered: "pages.substrate.statRungsCovered",
      statUnseenDevices: "pages.substrate.statUnseenDevices",
      statDevices: "pages.substrate.statDevices",
      statDenominator: "pages.substrate.statDenominator",
      constellationHeading: "pages.substrate.constellationHeading",
      constellationNote: "pages.substrate.constellationNote",
      classesSuffix: "pages.substrate.classesSuffix",
      matrixHeading: "pages.substrate.matrixHeading",
      matrixNote: "pages.substrate.matrixNote",
      matrixCaption: "pages.substrate.matrixCaption",
      deviceColumn: "pages.substrate.deviceColumn",
      drilldownSection: "pages.substrate.drilldownSection",
      drilldownHeading: "pages.substrate.drilldownHeading",
      ladderHeading: "pages.substrate.ladderHeading",
      fieldIdentity: "pages.substrate.fieldIdentity",
      fieldVendor: "pages.substrate.fieldVendor",
      fieldDriver: "pages.substrate.fieldDriver",
      fieldParent: "pages.substrate.fieldParent",
      fieldNodes: "pages.substrate.fieldNodes",
      fieldProvenance: "pages.substrate.fieldProvenance",
      fieldDiscoveredBy: "pages.substrate.fieldDiscoveredBy",
      fieldEnrichedBy: "pages.substrate.fieldEnrichedBy",
      reasonHeading: "pages.substrate.reasonHeading",
      remediationHeading: "pages.substrate.remediationHeading",
      noRemediation: "pages.substrate.noRemediation",
      blindForDays: "pages.substrate.blindForDays",
      portabilityHeading: "pages.substrate.portabilityHeading",
      portabilityNote: "pages.substrate.portabilityNote",
      portabilityCaption: "pages.substrate.portabilityCaption",
      capabilityColumn: "pages.substrate.capabilityColumn",
      constellationTitle: "pages.substrate.constellationTitle",
      hubClasses: "pages.substrate.hubClasses",
      nodeSummary: "pages.substrate.nodeSummary",
      nothingDeclaredShort: "pages.substrate.nothingDeclaredShort",
      nothingDeclaredLabel: "pages.substrate.nothingDeclaredLabel",
    },
    coverage: {
      eyebrow: "pages.coverage.eyebrow",
      title: "pages.coverage.title",
      description: "pages.coverage.description",
      reading: "pages.coverage.reading",
      sourceUnavailable: "pages.coverage.sourceUnavailable",
      unavailableTitle: "pages.coverage.unavailableTitle",
      unavailableBody: "pages.coverage.unavailableBody",
      chromeHeading: "pages.coverage.chromeHeading",
      chromeNote: "pages.coverage.chromeNote",
      chromeAllRead: "pages.coverage.chromeAllRead",
      headlineLabel: "pages.coverage.headlineLabel",
      statSpacesRead: "pages.coverage.statSpacesRead",
      statCellsMissing: "pages.coverage.statCellsMissing",
      statDatedGaps: "pages.coverage.statDatedGaps",
      statWeakestConfidence: "pages.coverage.statWeakestConfidence",
      gridHeading: "pages.coverage.gridHeading",
      gridNote: "pages.coverage.gridNote",
      projectionUnavailable: "pages.coverage.projectionUnavailable",
      countNow: "pages.coverage.countNow",
      countInReach: "pages.coverage.countInReach",
      countMissing: "pages.coverage.countMissing",
      confidenceHeading: "pages.coverage.confidenceHeading",
      confidenceNote: "pages.coverage.confidenceNote",
      confidenceCaption: "pages.coverage.confidenceCaption",
      colSpace: "pages.coverage.colSpace",
      colRatio: "pages.coverage.colRatio",
      colConfidence: "pages.coverage.colConfidence",
      colRationale: "pages.coverage.colRationale",
      noRationale: "pages.coverage.noRationale",
      openLoopHeading: "pages.coverage.openLoopHeading",
      openLoopNote: "pages.coverage.openLoopNote",
      openLoopCaption: "pages.coverage.openLoopCaption",
      openLoopEmptyTitle: "pages.coverage.openLoopEmptyTitle",
      openLoopEmptyBody: "pages.coverage.openLoopEmptyBody",
      openLoopUnavailable: "pages.coverage.openLoopUnavailable",
      readingGaps: "pages.coverage.readingGaps",
      colState: "pages.coverage.colState",
      colCell: "pages.coverage.colCell",
      colQuestion: "pages.coverage.colQuestion",
      colOpened: "pages.coverage.colOpened",
      colAge: "pages.coverage.colAge",
      undated: "pages.coverage.undated",
      ageDays: "pages.coverage.ageDays",
      integrityHeading: "pages.coverage.integrityHeading",
      integrityNote: "pages.coverage.integrityNote",
      integrityEmptyTitle: "pages.coverage.integrityEmptyTitle",
      integrityEmptyBody: "pages.coverage.integrityEmptyBody",
      integrityUnavailable: "pages.coverage.integrityUnavailable",
    },
    condition: {
      eyebrow: "pages.condition.eyebrow",
      title: "pages.condition.title",
      description: "pages.condition.description",
      reading: "pages.condition.reading",
      sourceUnavailable: "pages.condition.sourceUnavailable",
      unavailableTitle: "pages.condition.unavailableTitle",
      unavailableBody: "pages.condition.unavailableBody",
      trustHeading: "pages.condition.trustHeading",
      trustNote: "pages.condition.trustNote",
      readingsHeading: "pages.condition.readingsHeading",
      readingsNote: "pages.condition.readingsNote",
      readingsCaption: "pages.condition.readingsCaption",
      colCell: "pages.condition.colCell",
      colValue: "pages.condition.colValue",
      colSource: "pages.condition.colSource",
      colTrust: "pages.condition.colTrust",
      colBand: "pages.condition.colBand",
      valueUnavailable: "pages.condition.valueUnavailable",
      untrustedNotBanded: "pages.condition.untrustedNotBanded",
      emptyTitle: "pages.condition.emptyTitle",
      emptyBody: "pages.condition.emptyBody",
      sourcesHeading: "pages.condition.sourcesHeading",
      sourcesNote: "pages.condition.sourcesNote",
      sourceReadable: "pages.condition.sourceReadable",
      sourceUnreadable: "pages.condition.sourceUnreadable",
      noReason: "pages.condition.noReason",
      noSourceReportTitle: "pages.condition.noSourceReportTitle",
      noSourceReportBody: "pages.condition.noSourceReportBody",
      historyHeading: "pages.condition.historyHeading",
      historyEmptyTitle: "pages.condition.historyEmptyTitle",
      historyEmptyBody: "pages.condition.historyEmptyBody",
    },
    focus: {
      eyebrow: "pages.focus.eyebrow",
      title: "pages.focus.title",
      description: "pages.focus.description",
      reading: "pages.focus.reading",
      sourceUnavailable: "pages.focus.sourceUnavailable",
      rationaleHeading: "pages.focus.rationaleHeading",
      rationaleBody: "pages.focus.rationaleBody",
      rankedHeading: "pages.focus.rankedHeading",
      rankedNote: "pages.focus.rankedNote",
      unavailableTitle: "pages.focus.unavailableTitle",
      unavailableBody: "pages.focus.unavailableBody",
      nothingReadTitle: "pages.focus.nothingReadTitle",
      nothingReadBody: "pages.focus.nothingReadBody",
      emptyTitle: "pages.focus.emptyTitle",
      emptyBody: "pages.focus.emptyBody",
      rankLabel: "pages.focus.rankLabel",
      unranked: "pages.focus.unranked",
      sourcesHeading: "pages.focus.sourcesHeading",
      sourcesNote: "pages.focus.sourcesNote",
      sourceFindings: "pages.focus.sourceFindings",
      sourceUnreadable: "pages.focus.sourceUnreadable",
      noReason: "pages.focus.noReason",
      sourcesEmptyTitle: "pages.focus.sourcesEmptyTitle",
      sourcesEmptyBody: "pages.focus.sourcesEmptyBody",
      efficacyHeading: "pages.focus.efficacyHeading",
      efficacyEmptyTitle: "pages.focus.efficacyEmptyTitle",
      efficacyEmptyBody: "pages.focus.efficacyEmptyBody",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
  instrument: {
    notAvailable: "instrument.notAvailable",
    blindFor: "instrument.blindFor",
    trustDistributionLabel: "instrument.trustDistributionLabel",
    noVerdicts: "instrument.noVerdicts",
    checkedOf: "instrument.checkedOf",
    ratioLabel: "instrument.ratioLabel",
    ratioUncomputedLabel: "instrument.ratioUncomputedLabel",
    trust: {
      valid: "instrument.trust.valid",
      ghost: "instrument.trust.ghost",
      saturated: "instrument.trust.saturated",
      shelved: "instrument.trust.shelved",
      unitMismatch: "instrument.trust.unitMismatch",
      unavailable: "instrument.trust.unavailable",
      untrusted: "instrument.trust.untrusted",
    },
    band: {
      inBand: "instrument.band.inBand",
      outOfBand: "instrument.band.outOfBand",
      pendingSustain: "instrument.band.pendingSustain",
      needsBaseline: "instrument.band.needsBaseline",
      notEvaluated: "instrument.band.notEvaluated",
      notGradeable: "instrument.band.notGradeable",
    },
    confidence: {
      authoritative: "instrument.confidence.authoritative",
      partial: "instrument.confidence.partial",
      sketch: "instrument.confidence.sketch",
    },
  },
} as const;

export type Strings = typeof strings;
