// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $rowKey: "$rowKey",
  $schema: "$schema",
  $text: "$text",
  "Changes saved successfully": {
    "": "Changes saved successfully.",
  },
  "Disabled states retain the same geometry and clearly communicate that the action is unavailable": {
    "": "Disabled states retain the same geometry and clearly communicate that the action is unavailable.",
  },
  "Request in progress": "Request in progress",
  Saved: "Saved",
  app: {
    eyebrow: "app.eyebrow",
    title: "app.title",
  },
  "aria-label": "aria-label",
  ascending: "ascending",
  asset: "asset",
  "border-app-primary bg-app-primary text-app-primary-foreground": "border-app-primary bg-app-primary text-app-primary-foreground",
  capability: "capability",
  caption: "caption",
  children: "children",
  clsx: "clsx",
  component: "component",
  default: "default",
  defaultValue: "defaultValue",
  desc: "desc",
  description: "description",
  detail: "detail",
  dialog: "dialog",
  emptyMessage: "emptyMessage",
  equals: "equals",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  example: "example",
  export: "export",
  field: "field",
  fixture: "fixture",
  format: "format",
  header: "header",
  health: {
    description: "health.description",
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  iconName: "iconName",
  id: "id",
  instrument: {
    band: {
      inBand: "instrument.band.inBand",
      needsBaseline: "instrument.band.needsBaseline",
      notEvaluated: "instrument.band.notEvaluated",
      notGradeable: "instrument.band.notGradeable",
      outOfBand: "instrument.band.outOfBand",
      pendingSustain: "instrument.band.pendingSustain",
    },
    blindFor: "instrument.blindFor",
    checkedOf: "instrument.checkedOf",
    confidence: {
      authoritative: "instrument.confidence.authoritative",
      partial: "instrument.confidence.partial",
      sketch: "instrument.confidence.sketch",
    },
    noVerdicts: "instrument.noVerdicts",
    notAvailable: "instrument.notAvailable",
    ratioLabel: "instrument.ratioLabel",
    ratioUncomputedLabel: "instrument.ratioUncomputedLabel",
    trust: {
      ghost: "instrument.trust.ghost",
      saturated: "instrument.trust.saturated",
      shelved: "instrument.trust.shelved",
      unavailable: "instrument.trust.unavailable",
      unitMismatch: "instrument.trust.unitMismatch",
      untrusted: "instrument.trust.untrusted",
      valid: "instrument.trust.valid",
    },
    trustDistributionLabel: "instrument.trustDistributionLabel",
  },
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      condition: "layout.nav.condition",
      coverage: "layout.nav.coverage",
      dashboard: "layout.nav.dashboard",
      designLanguage: "layout.nav.designLanguage",
      focus: "layout.nav.focus",
      settings: "layout.nav.settings",
      substrate: "layout.nav.substrate",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  "lucide-react": "lucide-react",
  mode: "mode",
  module: "module",
  name: "name",
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  pages: {
    condition: {
      colBand: "pages.condition.colBand",
      colCell: "pages.condition.colCell",
      colSource: "pages.condition.colSource",
      colTrust: "pages.condition.colTrust",
      colValue: "pages.condition.colValue",
      description: "pages.condition.description",
      emptyBody: "pages.condition.emptyBody",
      emptyTitle: "pages.condition.emptyTitle",
      eyebrow: "pages.condition.eyebrow",
      historyEmptyBody: "pages.condition.historyEmptyBody",
      historyEmptyTitle: "pages.condition.historyEmptyTitle",
      historyHeading: "pages.condition.historyHeading",
      noReason: "pages.condition.noReason",
      noSourceReportBody: "pages.condition.noSourceReportBody",
      noSourceReportTitle: "pages.condition.noSourceReportTitle",
      reading: "pages.condition.reading",
      readingsCaption: "pages.condition.readingsCaption",
      readingsHeading: "pages.condition.readingsHeading",
      readingsNote: "pages.condition.readingsNote",
      sourceReadable: "pages.condition.sourceReadable",
      sourceUnavailable: "pages.condition.sourceUnavailable",
      sourceUnreadable: "pages.condition.sourceUnreadable",
      sourcesHeading: "pages.condition.sourcesHeading",
      sourcesNote: "pages.condition.sourcesNote",
      title: "pages.condition.title",
      trustHeading: "pages.condition.trustHeading",
      trustNote: "pages.condition.trustNote",
      unavailableBody: "pages.condition.unavailableBody",
      unavailableTitle: "pages.condition.unavailableTitle",
      untrustedNotBanded: "pages.condition.untrustedNotBanded",
      valueUnavailable: "pages.condition.valueUnavailable",
    },
    coverage: {
      ageDays: "pages.coverage.ageDays",
      chromeAllRead: "pages.coverage.chromeAllRead",
      chromeHeading: "pages.coverage.chromeHeading",
      chromeNote: "pages.coverage.chromeNote",
      colAge: "pages.coverage.colAge",
      colCell: "pages.coverage.colCell",
      colConfidence: "pages.coverage.colConfidence",
      colOpened: "pages.coverage.colOpened",
      colQuestion: "pages.coverage.colQuestion",
      colRatio: "pages.coverage.colRatio",
      colRationale: "pages.coverage.colRationale",
      colSpace: "pages.coverage.colSpace",
      colState: "pages.coverage.colState",
      confidenceCaption: "pages.coverage.confidenceCaption",
      confidenceHeading: "pages.coverage.confidenceHeading",
      confidenceNote: "pages.coverage.confidenceNote",
      countInReach: "pages.coverage.countInReach",
      countMissing: "pages.coverage.countMissing",
      countNow: "pages.coverage.countNow",
      description: "pages.coverage.description",
      eyebrow: "pages.coverage.eyebrow",
      gridHeading: "pages.coverage.gridHeading",
      gridNote: "pages.coverage.gridNote",
      headlineLabel: "pages.coverage.headlineLabel",
      integrityEmptyBody: "pages.coverage.integrityEmptyBody",
      integrityEmptyTitle: "pages.coverage.integrityEmptyTitle",
      integrityHeading: "pages.coverage.integrityHeading",
      integrityNote: "pages.coverage.integrityNote",
      integrityUnavailable: "pages.coverage.integrityUnavailable",
      noRationale: "pages.coverage.noRationale",
      noSpacesBody: "pages.coverage.noSpacesBody",
      noSpacesTitle: "pages.coverage.noSpacesTitle",
      openLoopCaption: "pages.coverage.openLoopCaption",
      openLoopEmptyBody: "pages.coverage.openLoopEmptyBody",
      openLoopEmptyTitle: "pages.coverage.openLoopEmptyTitle",
      openLoopHeading: "pages.coverage.openLoopHeading",
      openLoopNote: "pages.coverage.openLoopNote",
      openLoopUnavailable: "pages.coverage.openLoopUnavailable",
      projectionUnavailable: "pages.coverage.projectionUnavailable",
      reading: "pages.coverage.reading",
      readingGaps: "pages.coverage.readingGaps",
      sourceUnavailable: "pages.coverage.sourceUnavailable",
      statCellsMissing: "pages.coverage.statCellsMissing",
      statDatedGaps: "pages.coverage.statDatedGaps",
      statSpacesRead: "pages.coverage.statSpacesRead",
      statWeakestConfidence: "pages.coverage.statWeakestConfidence",
      title: "pages.coverage.title",
      unavailableBody: "pages.coverage.unavailableBody",
      unavailableTitle: "pages.coverage.unavailableTitle",
      undated: "pages.coverage.undated",
    },
    dashboard: {
      confidenceHeading: "pages.dashboard.confidenceHeading",
      confidenceNote: "pages.dashboard.confidenceNote",
      description: "pages.dashboard.description",
      eyebrow: "pages.dashboard.eyebrow",
      findingsEmptyBody: "pages.dashboard.findingsEmptyBody",
      findingsEmptyTitle: "pages.dashboard.findingsEmptyTitle",
      findingsHeading: "pages.dashboard.findingsHeading",
      findingsNote: "pages.dashboard.findingsNote",
      findingsUnavailableBody: "pages.dashboard.findingsUnavailableBody",
      findingsUnavailableTitle: "pages.dashboard.findingsUnavailableTitle",
      headlineLabel: "pages.dashboard.headlineLabel",
      instrumentHeading: "pages.dashboard.instrumentHeading",
      instrumentNote: "pages.dashboard.instrumentNote",
      reading: "pages.dashboard.reading",
      sourceUnavailable: "pages.dashboard.sourceUnavailable",
      sourcesEmptyBody: "pages.dashboard.sourcesEmptyBody",
      sourcesEmptyTitle: "pages.dashboard.sourcesEmptyTitle",
      sourcesHeading: "pages.dashboard.sourcesHeading",
      sourcesNote: "pages.dashboard.sourcesNote",
      statMissingCells: "pages.dashboard.statMissingCells",
      statRankedFindings: "pages.dashboard.statRankedFindings",
      statTrustedReadings: "pages.dashboard.statTrustedReadings",
      statWeakestConfidence: "pages.dashboard.statWeakestConfidence",
      title: "pages.dashboard.title",
    },
    designLanguage: {
      blindAgeDays: "pages.designLanguage.blindAgeDays",
      blindHeading: "pages.designLanguage.blindHeading",
      blindNoEvidence: "pages.designLanguage.blindNoEvidence",
      blindNoPredictive: "pages.designLanguage.blindNoPredictive",
      blindNotEnumerated: "pages.designLanguage.blindNotEnumerated",
      blindNote: "pages.designLanguage.blindNote",
      blindOpened: "pages.designLanguage.blindOpened",
      description: "pages.designLanguage.description",
      fixtureCaption: "pages.designLanguage.fixtureCaption",
      gridHeading: "pages.designLanguage.gridHeading",
      gridNote: "pages.designLanguage.gridNote",
      kitId: "pages.designLanguage.kitId",
      lampHeading: "pages.designLanguage.lampHeading",
      lampNote: "pages.designLanguage.lampNote",
      plateHeading: "pages.designLanguage.plateHeading",
      plateNote: "pages.designLanguage.plateNote",
      ringHeading: "pages.designLanguage.ringHeading",
      ringNote: "pages.designLanguage.ringNote",
      statCellsBlind: "pages.designLanguage.statCellsBlind",
      statDevices: "pages.designLanguage.statDevices",
      statHeading: "pages.designLanguage.statHeading",
      statNotComputable: "pages.designLanguage.statNotComputable",
      statNote: "pages.designLanguage.statNote",
      statRungsCovered: "pages.designLanguage.statRungsCovered",
      title: "pages.designLanguage.title",
    },
    focus: {
      description: "pages.focus.description",
      efficacyEmptyBody: "pages.focus.efficacyEmptyBody",
      efficacyEmptyTitle: "pages.focus.efficacyEmptyTitle",
      efficacyHeading: "pages.focus.efficacyHeading",
      emptyBody: "pages.focus.emptyBody",
      emptyTitle: "pages.focus.emptyTitle",
      eyebrow: "pages.focus.eyebrow",
      noReason: "pages.focus.noReason",
      nothingReadBody: "pages.focus.nothingReadBody",
      nothingReadTitle: "pages.focus.nothingReadTitle",
      rankLabel: "pages.focus.rankLabel",
      rankedHeading: "pages.focus.rankedHeading",
      rankedNote: "pages.focus.rankedNote",
      rationaleBody: "pages.focus.rationaleBody",
      rationaleHeading: "pages.focus.rationaleHeading",
      reading: "pages.focus.reading",
      sourceFindings: "pages.focus.sourceFindings",
      sourceUnavailable: "pages.focus.sourceUnavailable",
      sourceUnreadable: "pages.focus.sourceUnreadable",
      sourcesEmptyBody: "pages.focus.sourcesEmptyBody",
      sourcesEmptyTitle: "pages.focus.sourcesEmptyTitle",
      sourcesHeading: "pages.focus.sourcesHeading",
      sourcesNote: "pages.focus.sourcesNote",
      title: "pages.focus.title",
      unavailableBody: "pages.focus.unavailableBody",
      unavailableTitle: "pages.focus.unavailableTitle",
      unranked: "pages.focus.unranked",
    },
    settings: {
      localeHeading: "pages.settings.localeHeading",
      title: "pages.settings.title",
    },
    substrate: {
      blindForDays: "pages.substrate.blindForDays",
      blockedByRung: "pages.substrate.blockedByRung",
      capabilityColumn: "pages.substrate.capabilityColumn",
      checkPlatformRow: "pages.substrate.checkPlatformRow",
      checkPlatformsHeading: "pages.substrate.checkPlatformsHeading",
      checkPlatformsNote: "pages.substrate.checkPlatformsNote",
      classesSuffix: "pages.substrate.classesSuffix",
      constellationHeading: "pages.substrate.constellationHeading",
      constellationNote: "pages.substrate.constellationNote",
      constellationTitle: "pages.substrate.constellationTitle",
      denominatorUnread: "pages.substrate.denominatorUnread",
      description: "pages.substrate.description",
      deviceColumn: "pages.substrate.deviceColumn",
      drilldownBlindDevices: "pages.substrate.drilldownBlindDevices",
      drilldownDevices: "pages.substrate.drilldownDevices",
      drilldownHeading: "pages.substrate.drilldownHeading",
      drilldownSection: "pages.substrate.drilldownSection",
      eyebrow: "pages.substrate.eyebrow",
      headlineLabel: "pages.substrate.headlineLabel",
      hubClasses: "pages.substrate.hubClasses",
      ladderHeading: "pages.substrate.ladderHeading",
      matrixCaption: "pages.substrate.matrixCaption",
      matrixHeading: "pages.substrate.matrixHeading",
      matrixNote: "pages.substrate.matrixNote",
      mechanismHeading: "pages.substrate.mechanismHeading",
      noDevicesBody: "pages.substrate.noDevicesBody",
      noDevicesTitle: "pages.substrate.noDevicesTitle",
      noRemediation: "pages.substrate.noRemediation",
      nodeSummary: "pages.substrate.nodeSummary",
      notRead: "pages.substrate.notRead",
      nothingDeclaredLabel: "pages.substrate.nothingDeclaredLabel",
      nothingDeclaredShort: "pages.substrate.nothingDeclaredShort",
      portabilityCaption: "pages.substrate.portabilityCaption",
      portabilityHeading: "pages.substrate.portabilityHeading",
      portabilityNote: "pages.substrate.portabilityNote",
      provisional: "pages.substrate.provisional",
      reading: "pages.substrate.reading",
      reasonHeading: "pages.substrate.reasonHeading",
      remediationHeading: "pages.substrate.remediationHeading",
      resourceAcquisitionColumn: "pages.substrate.resourceAcquisitionColumn",
      resourceClaimsCaption: "pages.substrate.resourceClaimsCaption",
      resourceClaimsHeading: "pages.substrate.resourceClaimsHeading",
      resourceClaimsNote: "pages.substrate.resourceClaimsNote",
      resourceDriverColumn: "pages.substrate.resourceDriverColumn",
      resourceNameColumn: "pages.substrate.resourceNameColumn",
      resourcePlatformColumn: "pages.substrate.resourcePlatformColumn",
      skipBudgetHeading: "pages.substrate.skipBudgetHeading",
      skipBudgetNote: "pages.substrate.skipBudgetNote",
      skipBudgetOver: "pages.substrate.skipBudgetOver",
      skipBudgetSummary: "pages.substrate.skipBudgetSummary",
      skipBudgetUnavailable: "pages.substrate.skipBudgetUnavailable",
      skipBudgetWithin: "pages.substrate.skipBudgetWithin",
      sourceUnavailable: "pages.substrate.sourceUnavailable",
      statDenominator: "pages.substrate.statDenominator",
      statDevices: "pages.substrate.statDevices",
      statLadderCoverage: "pages.substrate.statLadderCoverage",
      statRungsCovered: "pages.substrate.statRungsCovered",
      statUngraded: "pages.substrate.statUngraded",
      statUnseenDevices: "pages.substrate.statUnseenDevices",
      title: "pages.substrate.title",
      unavailableBody: "pages.substrate.unavailableBody",
      unavailableTitle: "pages.substrate.unavailableTitle",
      ungraded: "pages.substrate.ungraded",
    },
  },
  path: "path",
  placeholder: "placeholder",
  provenance: "provenance",
  purpose: "purpose",
  react: "react",
  "react-component-library:useEscapeKey": "react-component-library:useEscapeKey",
  ref: "ref",
  region: "region",
  resolvedAt: "resolvedAt",
  role: "role",
  schema: "schema",
  schemaVersion: "schemaVersion",
  selector: "selector",
  size: "size",
  statement: "statement",
  status: "status",
  storyRef: "storyRef",
  "tailwind-merge": "tailwind-merge",
  testid: "testid",
  tier: "tier",
  title: "title",
  tone: "tone",
  true: "true",
  type: "type",
  value: "value",
  variant: "variant",
  version: "version",
} as const;

export type Strings = typeof strings;
