/**
 * Schema barrel export.
 *
 * All Zod schemas and their inferred types are exported from this module.
 * Import from here to get both runtime validation and TypeScript types.
 *
 * @example
 * import { SkillSchema, type Skill } from '@/lib/schemas'
 */

// Safe parsing utilities
export {
  safeParse,
  parseOrThrow,
  parseOrNull,
  parseArrayFiltered,
  ValidationError,
  type ParseResult,
} from './safeParse'

// Common schemas
export {
  FolderTypeSchema,
  HexColorSchema,
  KebabCaseIdSchema,
  TimestampSchema,
  type FolderType,
} from './common.schema'

// Skill schemas
export {
  SkillSchema,
  SkillArraySchema,
  CreateSkillRequestSchema,
  UpdateSkillRequestSchema,
  TagSchema,
  TagArraySchema,
  SkillTestRequestSchema,
  SkillTestResultSchema,
  SkillTestResultArraySchema,
  UsageResponseSchema,
  RatingResponseSchema,
  HealthResponseSchema,
  SyncResponseSchema,
  DisplayFormatSchema,
  DisplayResponseSchema,
  type Skill,
  type CreateSkillRequest,
  type UpdateSkillRequest,
  type Tag,
  type SkillTestRequest,
  type SkillTestResult,
  type UsageResponse,
  type RatingResponse,
  type HealthResponse,
  type SyncResponse,
  type DisplayFormat,
  type DisplayResponse,
  SkillXRefsResponseSchema,
  ReferenceSchema,
  ReferenceSourceSchema,
  type SkillXRefsResponse,
  type Reference,
  type ReferenceSource,
} from './skill.schema'

// Action schemas
export {
  ActionStatusSchema,
  ActionOwnerSchema,
  ActionCommandSchema,
  ActionInputTypeSchema,
  ActionOutputTypeSchema,
  ActionInputSchema,
  ActionOutputSchema,
  ActionPermissionsSchema,
  ActionExampleSchema,
  ActionExecutionSchema,
  ActionValidationSchema,
  ActionSchema,
  ActionArraySchema,
  CreateActionRequestSchema,
  UpdateActionRequestSchema,
  CommandCertaintySchema,
  CommandEffectSchema,
  CommandResolutionSchema,
  ActionValidationCheckSchema,
  ActionValidationResponseSchema,
  ActionMutationResponseSchema,
  ActionRunRequestSchema,
  ActionRunStatusSchema,
  ActionRunResponseSchema,
  type ActionStatus,
  type ActionOwner,
  type ActionCommand,
  type ActionInputType,
  type ActionOutputType,
  type ActionInput,
  type ActionOutput,
  type ActionPermissions,
  type ActionExample,
  type ActionExecution,
  type ActionValidation,
  type Action,
  type CreateActionRequest,
  type UpdateActionRequest,
  type CommandCertainty,
  type CommandEffect,
  type CommandResolution,
  type ActionValidationCheck,
  type ActionValidationResponse,
  type ActionMutationResponse,
  type ActionRunRequest,
  type ActionRunStatus,
  type ActionRunResponse,
} from './action.schema'

// Agent schemas
export {
  AgentStatusSchema,
  AgentAppearanceSchema,
  AgentCapabilitySchema,
  AgentCapabilitiesSchema,
  ConnectorTypeSchema,
  AgentConnectorSchema,
  AgentHeartbeatSchema,
  AgentSchema,
  AgentArraySchema,
  CreateAgentRequestSchema,
  UpdateAgentRequestSchema,
  SoulRequestSchema,
  SoulResponseSchema,
  AgentFileEntrySchema,
  AgentFileListResponseSchema,
  AgentFileContentResponseSchema,
  AgentFileWriteRequestSchema,
  AgentFileCreateRequestSchema,
  AgentFileRenameRequestSchema,
  PromptPreviewResponseSchema,
  PromptSectionSchema,
  StructuredPromptPreviewResponseSchema,
  TeamPromptMatrixEntrySchema,
  TeamPromptMatrixResponseSchema,
  AgentTeamMembershipSchema,
  AgentTeamsResponseSchema,
  DEFAULT_AGENT_COLORS,
  type AgentStatus,
  type AgentAppearance,
  type AgentCapability,
  type AgentCapabilities,
  type ConnectorType,
  type AgentConnector,
  type AgentHeartbeat,
  type Agent,
  type CreateAgentRequest,
  type UpdateAgentRequest,
  type SoulRequest,
  type SoulResponse,
  type AgentFileEntry,
  type AgentFileListResponse,
  type AgentFileContentResponse,
  type AgentFileWriteRequest,
  type AgentFileCreateRequest,
  type AgentFileRenameRequest,
  type PromptPreviewResponse,
  type PromptSection,
  type StructuredPromptPreviewResponse,
  type TeamPromptMatrixEntry,
  type TeamPromptMatrixResponse,
  type AgentTeamMembership,
  type AgentTeamsResponse,
} from './agent.schema'

// Search schemas
export {
  AISearchResultSchema,
  AISearchOutputSchema,
  SearchMethodSchema,
  SkillSearchResultSchema,
  SkillSearchResponseSchema,
  AISearchResponseSchema,
  AISearchRequestSchema,
  AISearchStatusSchema,
  AIReindexStatusSchema,
  ContentMatchRangeSchema,
  ContentSearchMatchSchema,
  ContentSearchResponseSchema,
  LinkPreviewDataSchema,
  type AISearchResult,
  type AISearchOutput,
  type SearchMethod,
  type SkillSearchResult,
  type SkillSearchResponse,
  type AISearchResponse,
  type AISearchRequest,
  type AISearchStatus,
  type AIReindexStatus,
  type ContentMatchRange,
  type ContentSearchMatch,
  type ContentSearchResponse,
  AIActionSearchResultSchema,
  AIActionSearchResponseSchema,
  AIActionSearchRequestSchema,
  type AIActionSearchResult,
  type AIActionSearchResponse,
  type AIActionSearchRequest,
  AIAgentSearchResultSchema,
  AIAgentSearchResponseSchema,
  AIAgentSearchRequestSchema,
  type AIAgentSearchResult,
  type AIAgentSearchResponse,
  type AIAgentSearchRequest,
  AITeamSearchResultSchema,
  AITeamSearchResponseSchema,
  AITeamSearchRequestSchema,
  type AITeamSearchResult,
  type AITeamSearchResponse,
  type AITeamSearchRequest,
  AgentContentSearchMatchSchema,
  AgentContentSearchResponseSchema,
  type AgentContentSearchMatch,
  type AgentContentSearchResponse,
  TeamContentSearchMatchSchema,
  TeamContentSearchResponseSchema,
  type TeamContentSearchMatch,
  type TeamContentSearchResponse,
  type LinkPreviewData,
  DiscoverSourceSchema,
  DiscoverTypeSchema,
  BudgetStatusSchema,
  DiscoverResultSchema,
  DiscoverResponseSchema,
  type DiscoverSource,
  type DiscoverType,
  type BudgetStatus,
  type DiscoverResult,
  type DiscoverResponse,
  BudgetConfigSchema,
  type BudgetConfig,
  DiscoverFilterConfigSchema,
  type DiscoverFilterConfig,
} from './search.schema'

// Team schemas
export {
  RuntimeModeSchema,
  CoordinationPatternSchema,
  ReportingModeSchema,
  MessagingModeSchema,
  QueuePolicySchema,
  CoordinationCapabilitiesSchema,
  RuntimeSchema,
  CoordinationSchema,
  ExecutionSchema,
  TeamMemberStatusSchema,
  TeamRoleSchema,
  TeamMemberSchema,
  TeamSchema,
  TeamArraySchema,
  TeamDetailsSchema,
  CreateTeamRequestSchema,
  UpdateTeamRequestSchema,
  AddMemberRequestSchema,
  UpdateMemberRequestSchema,
  SetRolesRequestSchema,
  TeamSharedFileEntrySchema,
  TeamSharedFileListResponseSchema,
  TeamSharedFileContentResponseSchema,
  TeamSharedFileWriteRequestSchema,
  TeamSharedFileCreateRequestSchema,
  TeamSharedFileRenameRequestSchema,
  AvailableCCTeamSchema,
  ImportCCRequestSchema,
  ExportCCResponseSchema,
  ExclusiveMemberSchema,
  ExclusiveMembersResponseSchema,
  buildIndependentCoordination,
  buildPeerCoordination,
  buildLeaderLedCoordination,
  buildBoundedParallelExecution,
  buildSerializedExecution,
  buildDefaultCreateTeamRequest,
  type RuntimeMode,
  type CoordinationPattern,
  type ReportingMode,
  type MessagingMode,
  type QueuePolicy,
  type CoordinationCapabilities,
  type Runtime,
  type Coordination,
  type Execution,
  type TeamMemberStatus,
  type TeamRole,
  type TeamMember,
  type Team,
  type TeamDetails,
  type CreateTeamRequest,
  type UpdateTeamRequest,
  type AddMemberRequest,
  type UpdateMemberRequest,
  type SetRolesRequest,
  type TeamSharedFileEntry,
  type TeamSharedFileListResponse,
  type TeamSharedFileContentResponse,
  type TeamSharedFileWriteRequest,
  type TeamSharedFileCreateRequest,
  type TeamSharedFileRenameRequest,
  type AvailableCCTeam,
  type ImportCCRequest,
  type ExportCCResponse,
  type ExclusiveMember,
  type ExclusiveMembersResponse,
} from './team.schema'

// Template schemas
export {
  AgentFileTemplateSchema,
  AgentFileTemplateListResponseSchema,
  type AgentFileTemplate,
  type AgentFileTemplateListResponse,
} from './template.schema'

// Topic schemas
export {
  TopicSchema,
  TopicArraySchema,
  CreateTopicRequestSchema,
  UpdateTopicRequestSchema,
  AccumulatedSkillsResponseSchema,
  TopicMatchRequestSchema,
  TopicMatchResultSchema,
  TopicMatchResponseSchema,
  type Topic,
  type CreateTopicRequest,
  type UpdateTopicRequest,
  type AccumulatedSkillsResponse,
  type TopicMatchRequest,
  type TopicMatchResult,
  type TopicMatchResponse,
} from './topic.schema'

// Version schemas
export {
  SkillVersionSchema,
  VersionsResponseSchema,
  RevertResponseSchema,
  type SkillVersion,
  type VersionsResponse,
  type RevertResponse,
} from './version.schema'

// Variant schemas
export {
  VariantSchema,
  VariantArraySchema,
  CreateVariantRequestSchema,
  type Variant,
  type CreateVariantRequest,
} from './variant.schema'

// Experiment schemas
export {
  ExperimentArmSchema,
  ExperimentArmInputSchema,
  ExperimentSchema,
  ExperimentArraySchema,
  CreateExperimentRequestSchema,
  ConcludeExperimentRequestSchema,
  type ExperimentArm,
  type ExperimentArmInput,
  type Experiment,
  type CreateExperimentRequest,
  type ConcludeExperimentRequest,
} from './experiment.schema'

// Graph schemas
export {
  NodeTypeSchema,
  EdgeKindSchema,
  HealthFactorSchema,
  HealthMessageSchema,
  HealthScoreSchema,
  EntityHealthWeightsSchema,
  CLIHealthConfigSchema,
  GraphHealthConfigSchema,
  GraphNodeSchema,
  GraphEdgeSchema,
  GraphDataSchema,
  GraphIndexSchema,
  NodeDetailSchema,
  PopularityEntrySchema,
  CircularRefSchema,
  GraphResponseSchema,
  NodeDetailResponseSchema,
  RegenerateResponseSchema,
  NodeListResponseSchema,
  PopularityResponseSchema,
  CircularRefResponseSchema,
  GraphHealthResponseSchema,
  NodeHealthResponseSchema,
  GraphHealthConfigResponseSchema,
  OperatingMapSchema,
  type NodeType,
  type EdgeKind,
  type HealthFactor,
  type HealthMessage,
  type HealthScore,
  type EntityHealthWeights,
  type CLIHealthConfig,
  type GraphHealthConfig,
  type OperatingMap,
  type GraphNode,
  type GraphEdge,
  type GraphData,
  type GraphIndex,
  type NodeDetail,
  type PopularityEntry,
  type CircularRef,
  type GraphResponse,
  type NodeDetailResponse,
  type RegenerateResponse,
  type NodeListResponse,
  type PopularityResponse,
  type CircularRefResponse,
  type GraphHealthResponse,
  type NodeHealthResponse,
  type GraphHealthConfigResponse,
} from './graph.schema'
