// Re-export everything from each module for backward compatibility
// This allows existing imports from "../lib/api" to continue working

// Client (error handling)
export { ApiError, throwIfNotOk, buildUrl } from "./client";
export type { RecoveryAction, ApiErrorResponse } from "./client";

// Types (all type definitions)
export type {
  DocsDocument,
  DocsSection,
  DocsNavigation,
  DocsManifest,
  DocsContentResponse,
  HealthResponse,
  TemplateInfo,
  DesktopConfig,
  BundleValidationError,
  BundleValidationWarning,
  BundleMissingBinary,
  BundleMissingAsset,
  BundleInvalidChecksum,
  BundleValidationResult,
  BundlePreflightRequest,
  BundlePreflightSecret,
  BundlePreflightReady,
  BundlePreflightTelemetry,
  BundlePreflightRuntime,
  BundlePreflightServiceFingerprint,
  BundlePreflightLogTail,
  BundlePreflightCheck,
  BundlePreflightResponse,
  BundlePreflightStep,
  BundleManifestResponse,
  PlatformBuildResult,
  BuildStatus,
  SmokeTestStatus,
  ProbeResponse,
  ProxyHintsResponse,
  DesktopRecord,
  DesktopRecordResponse,
  TestArtifactSummary,
  TestArtifactCleanupResult,
  WineInstallMethod,
  WineCheckResponse,
  WineInstallStatus,
  TelemetryUploadRequest,
  ScenarioPortResponse,
  SigningConfig,
  WindowsSigningConfig,
  MacOSSigningConfig,
  LinuxSigningConfig,
  SigningConfigResponse,
  SigningValidationError,
  ValidationWarning,
  PlatformValidation,
  SigningValidationResult,
  PlatformStatus,
  SigningReadinessResponse,
  ToolDetectionResult,
  DiscoveredCertificate,
  GenerateKeyResponse,
} from "./types";

// Pipeline types and functions
export type {
  PipelineConfig,
  PipelineStageResult,
  PipelineStatus,
  PipelineRunResponse,
  PipelineResumeResponse,
  BundleStageDetails,
  GenerateStageDetails,
  BuildPlatformResult,
  BuildStageDetails,
  SmokeTestStageDetails,
  DistributionPlatformUpload,
  DistributionTargetStatus,
  DistributionStageDetails,
  StageDetails,
  VerboseStageResult,
  VerbosePipelineStatus,
  GetPipelineStatusOptions,
} from "./pipeline";
export {
  runPipeline,
  getPipelineStatus,
  resumePipeline,
  cancelPipeline,
  listPipelines,
  runPreflightPipeline,
  extractPreflightResult,
} from "./pipeline";

// Scenario state types and functions
export type {
  PlatformSelection,
  FormState,
  InputFingerprint,
  StageState,
  CompressedLog,
  BuildArtifact,
  ScenarioState,
  StateChange,
  StageStatus,
  ValidationStatus,
  LoadStateResponse,
  SaveStateResponse,
  CheckStalenessResponse,
  GetLogsResponse,
  LoadStateOptions,
  SaveStateOptions,
} from "./scenarios";
export {
  fetchScenarioState,
  saveScenarioState,
  deleteScenarioState,
  checkStateStaleness,
  getScenarioLogs,
  invalidateScenarioStage,
  fetchScenarioDesktopStatus,
  fetchTemplates,
} from "./scenarios";

// Signing functions
export {
  fetchSigningConfig,
  saveSigningConfig,
  updatePlatformSigningConfig,
  deleteSigningConfig,
  deletePlatformSigningConfig,
  validateSigningConfig,
  checkSigningReadiness,
  fetchSigningPrerequisites,
  discoverCertificates,
  generateLinuxSigningKey,
} from "./signing";

// Distribution types and functions
export type {
  DistributionRetryConfig,
  DistributionTarget,
  DistributionConfig,
  DistributionConfigResponse,
  DistributionTargetResponse,
  DistributionTargetsResponse,
  DistributionTargetValidation,
  DistributionValidationResult,
  DistributionTestResult,
  DistributeRequest,
  CheckCredentialsRequest,
  TargetCredentialStatus,
  CheckCredentialsResponse,
  DistributeResponse,
  UploadStatus,
  TargetDistribution,
  DistributionStatus,
} from "./distribution";
export {
  fetchDistributionConfig,
  fetchDistributionConfigPath,
  fetchDistributionTargets,
  fetchDistributionTarget,
  createDistributionTarget,
  updateDistributionTarget,
  deleteDistributionTarget,
  testDistributionTarget,
  validateDistributionTargets,
  startDistribution,
  fetchDistributionStatus,
  cancelDistribution,
  checkDistributionCredentials,
} from "./distribution";

// Task functions
export {
  getAgentManagerStatus,
  createTask,
  listTasks,
  getTask,
  stopTask,
} from "./tasks";

// Misc functions
export {
  getIconPreviewUrl,
  fetchHealth,
  fetchDocsManifest,
  fetchDocContent,
  fetchDesktopRecords,
  moveDesktopRecord,
  getDownloadUrl,
  deleteDesktopBuild,
  fetchTestArtifacts,
  cleanupTestArtifacts,
  probeEndpoints,
  fetchProxyHints,
  fetchBundleManifest,
  checkWineStatus,
  startWineInstall,
  fetchWineInstallStatus,
  fetchTelemetryInsights,
  uploadTelemetry,
  deleteTelemetry,
  fetchTelemetrySummary,
  fetchTelemetryTail,
  getTelemetryDownloadUrl,
  fetchScenarioPort,
} from "./misc";
