#!/usr/bin/env bash
# Generate dynamic resource URLs configuration for AI Model Orchestra Controller
# This script creates resource-urls.json using the port registry system

set -euo pipefail

# Get the directory of this script
APP_ROOT="${APP_ROOT:-$(builtin cd "${BASH_SOURCE[0]%/*}/../../../.." && builtin pwd)}"
SCRIPT_DIR="${APP_ROOT}/scenarios/ai-model-orchestra-controller/initialization/scripts"
CONFIG_DIR="$SCRIPT_DIR/../configuration"
RESOURCE_URLS_FILE="$CONFIG_DIR/resource-urls.json"

# Source the port registry to get RESOURCE_PORTS
PROJECT_ROOT="$APP_ROOT"
PORT_REGISTRY="$PROJECT_ROOT/scripts/resources/port_registry.sh"

if [[ ! -f "$PORT_REGISTRY" ]]; then
    echo "ERROR: Port registry not found at $PORT_REGISTRY" >&2
    exit 1
fi

# Source the port registry
# shellcheck disable=SC1090
source "$PORT_REGISTRY"

# Create the resource URLs configuration
cat > "$RESOURCE_URLS_FILE" << EOF
{
  "version": "1.0.0",
  "generated_at": "$(date -Iseconds)",
  "note": "Auto-generated by create-resource-urls.sh - do not edit manually",
  "resources": {
    "ai": {
      "ollama": {
        "url": "http://localhost:${RESOURCE_PORTS[ollama]}",
        "port": ${RESOURCE_PORTS[ollama]},
        "host": "localhost",
        "api_base": "http://localhost:${RESOURCE_PORTS[ollama]}/api"
      }
    },
    "automation": {
      "node_red": {
        "url": "http://localhost:${RESOURCE_PORTS[node-red]}",
        "port": ${RESOURCE_PORTS[node-red]},
        "host": "localhost",
        "api_base": "http://localhost:${RESOURCE_PORTS[node-red]}/api"
      },
      "n8n": {
        "url": "http://localhost:${RESOURCE_PORTS[n8n]}",
        "port": ${RESOURCE_PORTS[n8n]},
        "host": "localhost",
        "api_base": "http://localhost:${RESOURCE_PORTS[n8n]}/api"
      },
      "windmill": {
        "url": "http://localhost:${RESOURCE_PORTS[windmill]}",
        "port": ${RESOURCE_PORTS[windmill]},
        "host": "localhost",
        "api_base": "http://localhost:${RESOURCE_PORTS[windmill]}/api"
      }
    },
    "storage": {
      "postgres": {
        "url": "postgres://postgres:postgres@localhost:${RESOURCE_PORTS[postgres]}/orchestrator?sslmode=disable",
        "port": ${RESOURCE_PORTS[postgres]},
        "host": "localhost",
        "database": "orchestrator",
        "username": "postgres",
        "maxConnections": 25
      },
      "redis": {
        "url": "redis://localhost:${RESOURCE_PORTS[redis]}",
        "port": ${RESOURCE_PORTS[redis]},
        "host": "localhost"
      },
      "qdrant": {
        "url": "http://localhost:${RESOURCE_PORTS[qdrant]}",
        "port": ${RESOURCE_PORTS[qdrant]},
        "host": "localhost",
        "api_base": "http://localhost:${RESOURCE_PORTS[qdrant]}"
      }
    },
    "docker": {
      "api": {
        "socketPath": "/var/run/docker.sock"
      }
    }
  },
  "port_registry_info": {
    "source": "$PORT_REGISTRY",
    "note": "Ports are managed centrally via port registry to avoid conflicts"
  }
}
EOF

echo "✅ Generated resource URLs configuration: $RESOURCE_URLS_FILE"
echo "📊 Using ports:"
echo "  Ollama: ${RESOURCE_PORTS[ollama]}"
echo "  Node-RED: ${RESOURCE_PORTS[node-red]}"
echo "  PostgreSQL: ${RESOURCE_PORTS[postgres]}"
echo "  Redis: ${RESOURCE_PORTS[redis]}"
echo "  Qdrant: ${RESOURCE_PORTS[qdrant]}"