import { AlertTriangle, Check, CornerDownLeft, X } from "lucide-react";
import { useState } from "react";
import { Button } from "../../ui/button";
import { defaultApiClient } from "../../../lib/api-client";
import { API_ENDPOINTS } from "../../../lib/api-endpoints";
import type { ReviewRound } from "../../../services/review-service";

export function ReviewDecisionCard({ kind, name, round, onDecided, onSendBack }: { kind: string; name: string; round: ReviewRound | undefined; onDecided: () => void; onSendBack?: () => void }) {
  const [pending, setPending] = useState<"accept" | "followup" | "fail" | null>(null);
  const [error, setError] = useState<string | null>(null);
  if (!round || round.status === "pending" || round.status === "gathering") return <section className="rounded-xl border border-amber-400/20 bg-amber-400/[0.06] p-4"><p className="text-sm font-medium text-amber-100">Review is gathering evidence</p><p className="mt-1 text-xs text-slate-300">The result will appear here when the review is ready for your decision.</p></section>;
  const decide = async (decision: "accept" | "followup" | "fail") => { setPending(decision); setError(null); try { const rationale = round.agent_assessment ?? "Review decision from Activity"; await defaultApiClient.post(API_ENDPOINTS.reviewDecide(kind, name), { decision, rationale, ...(decision === "followup" ? { follow_up: { steering: rationale, disposition: "replan" } } : {}) }); onDecided(); if (decision === "followup") onSendBack?.(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save this review decision."); } finally { setPending(null); } };
  const verdict = round.classification === "not_assessable" ? "Inconclusive" : round.classification?.replace(/-/g, " ") || "Review ready";
  const evidenceCount = round.evidence?.length ?? 0;
  return <section className="rounded-xl border border-violet-400/25 bg-violet-400/[0.06] p-4" aria-label="Review decision">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-violet-200" /><h2 className="text-sm font-semibold text-white">Review decision required</h2><span className="rounded-full border border-violet-300/25 bg-violet-300/10 px-2 py-0.5 text-[11px] capitalize text-violet-100">{verdict}</span></div><p className="mt-2 max-w-3xl text-sm text-slate-200">{round.agent_assessment || "Review evidence is ready for your judgment."}</p><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-400"><span>{evidenceCount} evidence item{evidenceCount === 1 ? "" : "s"} · Review round {round.round}</span>{round.execution_id ? <a className="text-cyan-200 underline-offset-2 hover:underline" href={`/executions/${round.execution_id}?tab=changes`}>View changed files</a> : null}</div>{round.disposition ? <div className="mt-3 inline-flex max-w-3xl items-start gap-2 rounded-md border border-sky-300/20 bg-sky-300/[0.06] px-2.5 py-2 text-xs text-sky-100"><span className="shrink-0 font-medium">Advisory: {round.disposition.kind.replace(/_/g, " ")}</span><span className="text-sky-100/80">{round.disposition.rationale}{round.disposition.confidence ? ` · ${round.disposition.confidence} confidence` : ""}</span></div> : null}{round.evidence.length > 0 ? <div className="mt-3 flex flex-wrap gap-1.5">{round.evidence.slice(0, 6).map((evidence) => <span key={evidence.id} className={`rounded-full border px-2 py-0.5 text-[11px] ${evidence.verified ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-100" : "border-slate-600 bg-slate-900 text-slate-300"}`}>{evidence.title}</span>)}</div> : null}</div></div>
    <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" disabled={pending !== null} onClick={() => void decide("accept")}><Check className="mr-1.5 h-3.5 w-3.5" />{pending === "accept" ? "Accepting…" : "Accept"}</Button><Button size="sm" variant="outline" disabled={pending !== null} onClick={() => void decide("followup")}><CornerDownLeft className="mr-1.5 h-3.5 w-3.5" />{pending === "followup" ? "Sending back…" : "Send back"}</Button><Button size="sm" variant="destructive" disabled={pending !== null} onClick={() => void decide("fail")}><X className="mr-1.5 h-3.5 w-3.5" />{pending === "fail" ? "Failing…" : "Fail"}</Button></div>{error ? <p className="mt-3 text-xs text-rose-200">{error}</p> : null}
  </section>;
}
