import { Activity, BarChart3, Binoculars, ClipboardList, GitBranch, HeartPulse, Play, Search, Settings2, Upload, X } from "lucide-react";

export type NavSection = "dashboard" | "profiles" | "tasks" | "runs" | "workflows" | "watches" | "stats" | "health" | "investigations" | "findings" | "import";
type Item = { id: NavSection; label: string; icon: typeof Activity };
const groups: Array<{ label: string; id: string; items: Item[] }> = [
  { id: "work", label: "Work", items: [{ id: "dashboard", label: "Dashboard", icon: Activity }, { id: "tasks", label: "Tasks", icon: ClipboardList }, { id: "runs", label: "Runs", icon: Play }, { id: "workflows", label: "Flows", icon: GitBranch }, { id: "watches", label: "Watches", icon: Binoculars }] },
  { id: "insight", label: "Insight", items: [{ id: "investigations", label: "Investigations", icon: Search }, { id: "findings", label: "Findings", icon: ClipboardList }, { id: "stats", label: "Stats", icon: BarChart3 }] },
  { id: "system", label: "System", items: [{ id: "profiles", label: "Profiles", icon: Settings2 }, { id: "health", label: "Health", icon: HeartPulse }, { id: "import", label: "Import", icon: Upload }] },
];

export function SideNav({ activeSection, onSectionChange, onSettingsClick, mobileOpen, onMobileOpenChange }: { activeSection: NavSection; onSectionChange: (section: NavSection) => void; onSettingsClick: () => void; mobileOpen: boolean; onMobileOpenChange: (open: boolean) => void }) {
  const choose = (section: NavSection) => { onSectionChange(section); onMobileOpenChange(false); };
  const content = (mobile: boolean) => <nav aria-label={mobile ? "Mobile primary navigation" : "Primary navigation"} className="space-y-5">{groups.map((group) => <section key={group.id} data-testid={`sidenav-${group.id}`} className="space-y-1"><h2 className="px-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">{group.label}</h2>{group.items.map((item) => { const Icon = item.icon; const active = activeSection === item.id; return <button key={item.id} type="button" onClick={() => choose(item.id)} aria-label={mobile ? `mobile ${item.id}` : undefined} aria-current={active ? "page" : undefined} data-testid={`${mobile ? "mobile-nav" : "sidenav"}-${item.id}`} className={`flex min-h-11 w-full items-center gap-2 rounded-md px-2 py-2 text-sm ${active ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="h-4 w-4" /><span>{item.label}</span></button>})}</section>)}<button type="button" aria-label={mobile ? "Mobile navigation settings" : "Side navigation settings"} onClick={() => { onSettingsClick(); onMobileOpenChange(false); }} className="flex min-h-11 w-full items-center gap-2 rounded-md px-2 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground"><Settings2 className="h-4 w-4" />Settings</button></nav>;
  return <><aside className="hidden h-full w-56 shrink-0 overflow-y-auto border-r border-border bg-background p-3 md:block">{content(false)}</aside>{mobileOpen && <div className="fixed inset-0 z-50 md:hidden" role="dialog" aria-modal="true" aria-label="Navigation menu"><button type="button" aria-label="Close navigation menu" className="absolute inset-0 cursor-default bg-black/50 backdrop-blur-sm" onClick={() => onMobileOpenChange(false)} /><aside className="relative h-full w-[min(19rem,88vw)] overflow-y-auto bg-background p-3 shadow-2xl motion-safe:animate-in motion-safe:slide-in-from-left motion-safe:duration-200"><div className="mb-4 flex items-center justify-between border-b border-border pb-3"><span className="font-semibold">Agent Manager</span><button type="button" aria-label="Close navigation menu" onClick={() => onMobileOpenChange(false)} className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><X className="h-5 w-5" /></button></div>{content(true)}</aside></div>}</>;
}
