// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    tagline: "app.tagline",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainContentLabel: "layout.mainContentLabel",
    nav: {
      home: "layout.nav.home",
      workspace: "layout.nav.workspace",
      library: "layout.nav.library",
      activity: "layout.nav.activity",
      models: "layout.nav.models",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  settings: {
    fontScale: {
      label: "settings.fontScale.label",
      small: "settings.fontScale.small",
      default: "settings.fontScale.default",
      large: "settings.fontScale.large",
      xlarge: "settings.fontScale.xlarge",
    },
    reducedMotion: {
      label: "settings.reducedMotion.label",
      description: "settings.reducedMotion.description",
      system: "settings.reducedMotion.system",
      always: "settings.reducedMotion.always",
      never: "settings.reducedMotion.never",
    },
    textDirection: {
      label: "settings.textDirection.label",
      auto: "settings.textDirection.auto",
      ltr: "settings.textDirection.ltr",
      rtl: "settings.textDirection.rtl",
    },
    handedness: {
      label: "settings.handedness.label",
      description: "settings.handedness.description",
      left: "settings.handedness.left",
      right: "settings.handedness.right",
    },
  },
  pages: {
    home: {
      title: "pages.home.title",
    },
    library: {
      title: "pages.library.title",
    },
    activity: {
      title: "pages.activity.title",
    },
    models: {
      title: "pages.models.title",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      displayHeading: "pages.settings.displayHeading",
    },
    workspace: {
      title: "pages.workspace.title",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  jobs: {
    title: "jobs.title",
    loading: "jobs.loading",
    empty: "jobs.empty",
    stateLabel: "jobs.stateLabel",
    progressLabel: "jobs.progressLabel",
    errorLabel: "jobs.errorLabel",
    liveBadge: "jobs.liveBadge",
    cancel: "jobs.cancel",
    lane: {
      unspecified: "jobs.lane.unspecified",
      gpu: "jobs.lane.gpu",
      cpu: "jobs.lane.cpu",
    },
    state: {
      unspecified: "jobs.state.unspecified",
      queued: "jobs.state.queued",
      running: "jobs.state.running",
      succeeded: "jobs.state.succeeded",
      failed: "jobs.state.failed",
      canceled: "jobs.state.canceled",
    },
  },
  home: {
    greeting: "home.greeting",
    entry: {
      title: "home.entry.title",
      hint: "home.entry.hint",
      choose: "home.entry.choose",
      camera: "home.entry.camera",
      sample: "home.entry.sample",
      dropActive: "home.entry.dropActive",
      fileLabel: "home.entry.fileLabel",
    },
    group: {
      quickEdits: "home.group.quickEdits",
      enhance: "home.group.enhance",
      create: "home.group.create",
      analyze: "home.group.analyze",
    },
    needsModel: "home.needsModel",
    analyzeTile: "home.analyzeTile",
    recent: {
      heading: "home.recent.heading",
      viewAll: "home.recent.viewAll",
      empty: "home.recent.empty",
      alt: "home.recent.alt",
    },
    firstRun: "home.firstRun",
    samples: {
      heading: "home.samples.heading",
      product: "home.samples.product",
      portrait: "home.samples.portrait",
      blurry: "home.samples.blurry",
      receipt: "home.samples.receipt",
    },
  },
  library: {
    description: "library.description",
    loading: "library.loading",
    empty: "library.empty",
    searchLabel: "library.searchLabel",
    searchPlaceholder: "library.searchPlaceholder",
    noMatches: "library.noMatches",
    count: "library.count",
    count_one: "library.count_one",
    selected: "library.selected",
    selectAll: "library.selectAll",
    clearSelection: "library.clearSelection",
    downloadSelected: "library.downloadSelected",
    open: "library.open",
    thumbnailAlt: "library.thumbnailAlt",
    tryWorkspace: "library.tryWorkspace",
  },
  looks: {
    title: "looks.title",
    description: "looks.description",
    loading: "looks.loading",
    error: "looks.error",
    empty: "looks.empty",
    preview: "looks.preview",
    refresh: "looks.refresh",
    rendering: "looks.rendering",
    noPreview: "looks.noPreview",
    deferred: "looks.deferred",
    builtinBadge: "looks.builtinBadge",
    customBadge: "looks.customBadge",
    thumbnailAlt: "looks.thumbnailAlt",
    kind: {
      style: "looks.kind.style",
      film: "looks.kind.film",
      camera: "looks.kind.camera",
      enhance: "looks.kind.enhance",
      custom: "looks.kind.custom",
      unspecified: "looks.kind.unspecified",
    },
  },
  activity: {
    description: "activity.description",
    thumbnailAlt: "activity.thumbnailAlt",
    openOutput: "activity.openOutput",
  },
  models: {
    title: "models.title",
    loading: "models.loading",
    empty: "models.empty",
    tierLabel: "models.tierLabel",
    backendLabel: "models.backendLabel",
    operationsLabel: "models.operationsLabel",
    sizeLabel: "models.sizeLabel",
    sizeValue: "models.sizeValue",
    hardwareLabel: "models.hardwareLabel",
    hardware: {
      gpuRequired: "models.hardware.gpuRequired",
      cpuOk: "models.hardware.cpuOk",
      vram: "models.hardware.vram",
      ram: "models.hardware.ram",
      speedNote: "models.hardware.speedNote",
    },
    licenseLabel: "models.licenseLabel",
    commercialLabel: "models.commercialLabel",
    commercial: {
      unspecified: "models.commercial.unspecified",
      yes: "models.commercial.yes",
      no: "models.commercial.no",
      conditional: "models.commercial.conditional",
    },
    commercialNotesLabel: "models.commercialNotesLabel",
    nsfwBadge: "models.nsfwBadge",
    customBadge: "models.customBadge",
    defaultForBadge: "models.defaultForBadge",
    defaultForLabel: "models.defaultForLabel",
    downloadSizeLabel: "models.downloadSizeLabel",
    diskSizeLabel: "models.diskSizeLabel",
    installState: {
      installed: "models.installState.installed",
      notInstalled: "models.installState.notInstalled",
    },
    install: "models.install",
    installing: "models.installing",
    installStarted: "models.installStarted",
    alreadyInstalled: "models.alreadyInstalled",
    remove: "models.remove",
    removing: "models.removing",
    enabledLabel: "models.enabledLabel",
    disabledLabel: "models.disabledLabel",
    enable: "models.enable",
    disable: "models.disable",
    blocklist: {
      title: "models.blocklist.title",
      loading: "models.blocklist.loading",
      empty: "models.blocklist.empty",
      licenseLabel: "models.blocklist.licenseLabel",
      reasonLabel: "models.blocklist.reasonLabel",
      operationsLabel: "models.blocklist.operationsLabel",
      onnxWarning: "models.blocklist.onnxWarning",
    },
    addCustom: {
      title: "models.addCustom.title",
      idLabel: "models.addCustom.idLabel",
      operationsLabel: "models.addCustom.operationsLabel",
      backendLabel: "models.addCustom.backendLabel",
      localPathLabel: "models.addCustom.localPathLabel",
      downloadUrlLabel: "models.addCustom.downloadUrlLabel",
      submit: "models.addCustom.submit",
      submitting: "models.addCustom.submitting",
      success: "models.addCustom.success",
    },
    defaults: {
      title: "models.defaults.title",
      loading: "models.defaults.loading",
      empty: "models.defaults.empty",
      modelLabel: "models.defaults.modelLabel",
      sourceLabel: "models.defaults.sourceLabel",
      source: {
        seed: "models.defaults.source.seed",
        override: "models.defaults.source.override",
      },
      useDefault: "models.defaults.useDefault",
      clear: "models.defaults.clear",
      none: "models.defaults.none",
    },
  },
  workspace: {
    loading: "workspace.loading",
    error: "workspace.error",
    uploadLabel: "workspace.uploadLabel",
    overlayLabel: "workspace.overlayLabel",
    run: "workspace.run",
    running: "workspace.running",
    empty: "workspace.empty",
    originalLabel: "workspace.originalLabel",
    resultLabel: "workspace.resultLabel",
    resultMeta: "workspace.resultMeta",
    metadataLabel: "workspace.metadataLabel",
    canvas: {
      empty: "workspace.canvas.empty",
      zoomIn: "workspace.canvas.zoomIn",
      zoomOut: "workspace.canvas.zoomOut",
      zoomFit: "workspace.canvas.zoomFit",
      zoomActual: "workspace.canvas.zoomActual",
      zoomLevel: "workspace.canvas.zoomLevel",
      compareToggle: "workspace.canvas.compareToggle",
      replace: "workspace.canvas.replace",
    },
    actions: {
      undo: "workspace.actions.undo",
      redo: "workspace.actions.redo",
      reset: "workspace.actions.reset",
      download: "workspace.actions.download",
    },
    history: {
      title: "workspace.history.title",
      empty: "workspace.history.empty",
      source: "workspace.history.source",
      step: "workspace.history.step",
    },
    mode: {
      edit: "workspace.mode.edit",
      enhance: "workspace.mode.enhance",
      create: "workspace.mode.create",
      analyze: "workspace.mode.analyze",
      switcherLabel: "workspace.mode.switcherLabel",
    },
    analyzeOp: {
      probe: {
        label: "workspace.analyzeOp.probe.label",
        desc: "workspace.analyzeOp.probe.desc",
      },
      ocr: {
        label: "workspace.analyzeOp.ocr.label",
        desc: "workspace.analyzeOp.ocr.desc",
      },
      nsfw_classify: {
        label: "workspace.analyzeOp.nsfw_classify.label",
        desc: "workspace.analyzeOp.nsfw_classify.desc",
      },
    },
    analyze: {
      intro: "workspace.analyze.intro",
      loading: "workspace.analyze.loading",
      error: "workspace.analyze.error",
      needsImage: "workspace.analyze.needsImage",
      modelNote: "workspace.analyze.modelNote",
      run: "workspace.analyze.run",
      running: "workspace.analyze.running",
      retry: "workspace.analyze.retry",
      failed: "workspace.analyze.failed",
      probe: {
        dimensions: "workspace.analyze.probe.dimensions",
        format: "workspace.analyze.probe.format",
        colorModel: "workspace.analyze.probe.colorModel",
        alpha: "workspace.analyze.probe.alpha",
        frames: "workspace.analyze.probe.frames",
        megapixels: "workspace.analyze.probe.megapixels",
        size: "workspace.analyze.probe.size",
        exif: "workspace.analyze.probe.exif",
        gps: "workspace.analyze.probe.gps",
        orientation: "workspace.analyze.probe.orientation",
        palette: "workspace.analyze.probe.palette",
        yes: "workspace.analyze.probe.yes",
        no: "workspace.analyze.probe.no",
      },
      ocr: {
        copy: "workspace.analyze.ocr.copy",
        copied: "workspace.analyze.ocr.copied",
        empty: "workspace.analyze.ocr.empty",
        language: "workspace.analyze.ocr.language",
        blocks: "workspace.analyze.ocr.blocks",
      },
      nsfw: {
        flagged: "workspace.analyze.nsfw.flagged",
        safe: "workspace.analyze.nsfw.safe",
        score: "workspace.analyze.nsfw.score",
        threshold: "workspace.analyze.nsfw.threshold",
      },
    },
    aiOp: {
      background_removal: {
        label: "workspace.aiOp.background_removal.label",
        desc: "workspace.aiOp.background_removal.desc",
      },
      upscale: {
        label: "workspace.aiOp.upscale.label",
        desc: "workspace.aiOp.upscale.desc",
      },
      denoise: {
        label: "workspace.aiOp.denoise.label",
        desc: "workspace.aiOp.denoise.desc",
      },
      naturalize: {
        label: "workspace.aiOp.naturalize.label",
        desc: "workspace.aiOp.naturalize.desc",
      },
    },
    enhance: {
      intro: "workspace.enhance.intro",
      loading: "workspace.enhance.loading",
      error: "workspace.enhance.error",
      needsImage: "workspace.enhance.needsImage",
      scaleLabel: "workspace.enhance.scaleLabel",
      targetResolution: "workspace.enhance.targetResolution",
      memoryWarning: "workspace.enhance.memoryWarning",
      run: "workspace.enhance.run",
      running: "workspace.enhance.running",
      progress: "workspace.enhance.progress",
      cancel: "workspace.enhance.cancel",
      retry: "workspace.enhance.retry",
      succeeded: "workspace.enhance.succeeded",
      failed: "workspace.enhance.failed",
      warningsLabel: "workspace.enhance.warningsLabel",
      tier: {
        localGpu: "workspace.enhance.tier.localGpu",
        localCpu: "workspace.enhance.tier.localCpu",
        byokCloud: "workspace.enhance.tier.byokCloud",
      },
      install: {
        title: "workspace.enhance.install.title",
        cpu: "workspace.enhance.install.cpu",
        gpu: "workspace.enhance.install.gpu",
        size: "workspace.enhance.install.size",
        run: "workspace.enhance.install.run",
        installing: "workspace.enhance.install.installing",
      },
      naturalize: {
        realismLabel: "workspace.enhance.naturalize.realismLabel",
        realismHint: "workspace.enhance.naturalize.realismHint",
        subtle: "workspace.enhance.naturalize.subtle",
        strong: "workspace.enhance.naturalize.strong",
        faceAware: "workspace.enhance.naturalize.faceAware",
        suggestTitle: "workspace.enhance.naturalize.suggestTitle",
        suggest: "workspace.enhance.naturalize.suggest",
      },
    },
    createOp: {
      text_to_image: {
        label: "workspace.createOp.text_to_image.label",
        desc: "workspace.createOp.text_to_image.desc",
      },
      image_to_image: {
        label: "workspace.createOp.image_to_image.label",
        desc: "workspace.createOp.image_to_image.desc",
      },
      edit_instruct: {
        label: "workspace.createOp.edit_instruct.label",
        desc: "workspace.createOp.edit_instruct.desc",
      },
      inpaint: {
        label: "workspace.createOp.inpaint.label",
        desc: "workspace.createOp.inpaint.desc",
      },
      object_removal: {
        label: "workspace.createOp.object_removal.label",
        desc: "workspace.createOp.object_removal.desc",
      },
    },
    create: {
      intro: "workspace.create.intro",
      loading: "workspace.create.loading",
      error: "workspace.create.error",
      promptLabel: "workspace.create.promptLabel",
      promptPlaceholder: "workspace.create.promptPlaceholder",
      negativeLabel: "workspace.create.negativeLabel",
      negativePlaceholder: "workspace.create.negativePlaceholder",
      sizeLabel: "workspace.create.sizeLabel",
      size: {
        square: "workspace.create.size.square",
        portrait: "workspace.create.size.portrait",
        landscape: "workspace.create.size.landscape",
      },
      seedLabel: "workspace.create.seedLabel",
      seedRandom: "workspace.create.seedRandom",
      seedLock: "workspace.create.seedLock",
      seedRandomize: "workspace.create.seedRandomize",
      variationsLabel: "workspace.create.variationsLabel",
      modelLabel: "workspace.create.modelLabel",
      modelPlaceholder: "workspace.create.modelPlaceholder",
      byokLabel: "workspace.create.byokLabel",
      advanced: "workspace.create.advanced",
      usesCurrent: "workspace.create.usesCurrent",
      needsImage: "workspace.create.needsImage",
      needsMask: "workspace.create.needsMask",
      run: "workspace.create.run",
      running: "workspace.create.running",
      produced: "workspace.create.produced",
      progress: "workspace.create.progress",
      cancel: "workspace.create.cancel",
      retry: "workspace.create.retry",
      succeeded: "workspace.create.succeeded",
      failed: "workspace.create.failed",
      warningsLabel: "workspace.create.warningsLabel",
      result: {
        heading: "workspace.create.result.heading",
        slot: "workspace.create.result.slot",
        pending: "workspace.create.result.pending",
        sendToCanvas: "workspace.create.result.sendToCanvas",
        sendToEnhance: "workspace.create.result.sendToEnhance",
        download: "workspace.create.result.download",
      },
    },
    mask: {
      title: "workspace.mask.title",
      hint: "workspace.mask.hint",
      brushSize: "workspace.mask.brushSize",
      clear: "workspace.mask.clear",
      uploadLabel: "workspace.mask.uploadLabel",
      painted: "workspace.mask.painted",
      uploaded: "workspace.mask.uploaded",
      empty: "workspace.mask.empty",
    },
    operationLabelGroup: "workspace.operationLabelGroup",
    op: {
      resize: {
        label: "workspace.op.resize.label",
        desc: "workspace.op.resize.desc",
      },
      crop: {
        label: "workspace.op.crop.label",
        desc: "workspace.op.crop.desc",
      },
      rotate: {
        label: "workspace.op.rotate.label",
        desc: "workspace.op.rotate.desc",
      },
      flip: {
        label: "workspace.op.flip.label",
        desc: "workspace.op.flip.desc",
      },
      deskew: {
        label: "workspace.op.deskew.label",
        desc: "workspace.op.deskew.desc",
      },
      thumbnail: {
        label: "workspace.op.thumbnail.label",
        desc: "workspace.op.thumbnail.desc",
      },
      canvas: {
        label: "workspace.op.canvas.label",
        desc: "workspace.op.canvas.desc",
      },
      adjust: {
        label: "workspace.op.adjust.label",
        desc: "workspace.op.adjust.desc",
      },
      filter: {
        label: "workspace.op.filter.label",
        desc: "workspace.op.filter.desc",
      },
      convert: {
        label: "workspace.op.convert.label",
        desc: "workspace.op.convert.desc",
      },
      compress: {
        label: "workspace.op.compress.label",
        desc: "workspace.op.compress.desc",
      },
      overlay: {
        label: "workspace.op.overlay.label",
        desc: "workspace.op.overlay.desc",
      },
      metadata: {
        label: "workspace.op.metadata.label",
        desc: "workspace.op.metadata.desc",
      },
    },
    fitOption: {
      fit: "workspace.fitOption.fit",
      fill: "workspace.fitOption.fill",
      stretch: "workspace.fitOption.stretch",
    },
    axisOption: {
      horizontal: "workspace.axisOption.horizontal",
      vertical: "workspace.axisOption.vertical",
    },
    filterOption: {
      grayscale: "workspace.filterOption.grayscale",
      sepia: "workspace.filterOption.sepia",
      invert: "workspace.filterOption.invert",
      blur: "workspace.filterOption.blur",
      sharpen: "workspace.filterOption.sharpen",
    },
    position: {
      name: {
        topLeft: "workspace.position.name.topLeft",
        top: "workspace.position.name.top",
        topRight: "workspace.position.name.topRight",
        left: "workspace.position.name.left",
        center: "workspace.position.name.center",
        right: "workspace.position.name.right",
        bottomLeft: "workspace.position.name.bottomLeft",
        bottom: "workspace.position.name.bottom",
        bottomRight: "workspace.position.name.bottomRight",
      },
    },
    crop: {
      aspect: {
        label: "workspace.crop.aspect.label",
        free: "workspace.crop.aspect.free",
        square: "workspace.crop.aspect.square",
        standard: "workspace.crop.aspect.standard",
        wide: "workspace.crop.aspect.wide",
        original: "workspace.crop.aspect.original",
      },
      advanced: "workspace.crop.advanced",
      hint: "workspace.crop.hint",
      boxLabel: "workspace.crop.boxLabel",
    },
    control: {
      reset: "workspace.control.reset",
    },
    color: {
      alpha: "workspace.color.alpha",
      clear: "workspace.color.clear",
    },
    target: {
      kb: "workspace.target.kb",
      mb: "workspace.target.mb",
      noLimit: "workspace.target.noLimit",
    },
    compare: {
      before: "workspace.compare.before",
      after: "workspace.compare.after",
      slider: "workspace.compare.slider",
    },
    field: {
      width: "workspace.field.width",
      height: "workspace.field.height",
      fit: "workspace.field.fit",
      gravity: "workspace.field.gravity",
      x: "workspace.field.x",
      y: "workspace.field.y",
      angle: "workspace.field.angle",
      background: "workspace.field.background",
      axis: "workspace.field.axis",
      brightness: "workspace.field.brightness",
      contrast: "workspace.field.contrast",
      gamma: "workspace.field.gamma",
      saturation: "workspace.field.saturation",
      hue: "workspace.field.hue",
      filter: "workspace.field.filter",
      amount: "workspace.field.amount",
      format: "workspace.field.format",
      quality: "workspace.field.quality",
      lossless: "workspace.field.lossless",
      targetBytes: "workspace.field.targetBytes",
      text: "workspace.field.text",
      position: "workspace.field.position",
      opacity: "workspace.field.opacity",
      color: "workspace.field.color",
      fontSize: "workspace.field.fontSize",
      stripAll: "workspace.field.stripAll",
      stripGps: "workspace.field.stripGps",
      autoOrient: "workspace.field.autoOrient",
    },
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
