// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      workspace: "layout.nav.workspace",
      jobs: "layout.nav.jobs",
      models: "layout.nav.models",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      statPlaceholderLabel: "pages.dashboard.statPlaceholderLabel",
    },
    jobs: {
      title: "pages.jobs.title",
    },
    models: {
      title: "pages.models.title",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
    workspace: {
      title: "pages.workspace.title",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  jobs: {
    title: "jobs.title",
    loading: "jobs.loading",
    empty: "jobs.empty",
    operationLabel: "jobs.operationLabel",
    laneLabel: "jobs.laneLabel",
    stateLabel: "jobs.stateLabel",
    progressLabel: "jobs.progressLabel",
    messageLabel: "jobs.messageLabel",
    resultLabel: "jobs.resultLabel",
    errorLabel: "jobs.errorLabel",
    liveBadge: "jobs.liveBadge",
    cancel: "jobs.cancel",
    lane: {
      unspecified: "jobs.lane.unspecified",
      gpu: "jobs.lane.gpu",
      cpu: "jobs.lane.cpu",
    },
    state: {
      unspecified: "jobs.state.unspecified",
      queued: "jobs.state.queued",
      running: "jobs.state.running",
      succeeded: "jobs.state.succeeded",
      failed: "jobs.state.failed",
      canceled: "jobs.state.canceled",
    },
  },
  models: {
    title: "models.title",
    loading: "models.loading",
    empty: "models.empty",
    tierLabel: "models.tierLabel",
    backendLabel: "models.backendLabel",
    operationsLabel: "models.operationsLabel",
    sizeLabel: "models.sizeLabel",
    sizeValue: "models.sizeValue",
    hardwareLabel: "models.hardwareLabel",
    hardware: {
      gpuRequired: "models.hardware.gpuRequired",
      cpuOk: "models.hardware.cpuOk",
      vram: "models.hardware.vram",
      ram: "models.hardware.ram",
    },
    licenseLabel: "models.licenseLabel",
    commercialLabel: "models.commercialLabel",
    commercial: {
      unspecified: "models.commercial.unspecified",
      yes: "models.commercial.yes",
      no: "models.commercial.no",
      conditional: "models.commercial.conditional",
    },
    nsfwBadge: "models.nsfwBadge",
    customBadge: "models.customBadge",
    installState: {
      installed: "models.installState.installed",
      notInstalled: "models.installState.notInstalled",
    },
    install: "models.install",
    installing: "models.installing",
    installStarted: "models.installStarted",
    alreadyInstalled: "models.alreadyInstalled",
    remove: "models.remove",
    removing: "models.removing",
    enabledLabel: "models.enabledLabel",
    disabledLabel: "models.disabledLabel",
    enable: "models.enable",
    disable: "models.disable",
    blocklist: {
      title: "models.blocklist.title",
      loading: "models.blocklist.loading",
      empty: "models.blocklist.empty",
      licenseLabel: "models.blocklist.licenseLabel",
      reasonLabel: "models.blocklist.reasonLabel",
      operationsLabel: "models.blocklist.operationsLabel",
      onnxWarning: "models.blocklist.onnxWarning",
    },
    addCustom: {
      title: "models.addCustom.title",
      idLabel: "models.addCustom.idLabel",
      operationsLabel: "models.addCustom.operationsLabel",
      backendLabel: "models.addCustom.backendLabel",
      localPathLabel: "models.addCustom.localPathLabel",
      downloadUrlLabel: "models.addCustom.downloadUrlLabel",
      submit: "models.addCustom.submit",
      submitting: "models.addCustom.submitting",
      success: "models.addCustom.success",
    },
    defaults: {
      title: "models.defaults.title",
      loading: "models.defaults.loading",
      empty: "models.defaults.empty",
      modelLabel: "models.defaults.modelLabel",
      sourceLabel: "models.defaults.sourceLabel",
      source: {
        seed: "models.defaults.source.seed",
        override: "models.defaults.source.override",
      },
      useDefault: "models.defaults.useDefault",
      clear: "models.defaults.clear",
      none: "models.defaults.none",
    },
  },
  workspace: {
    loading: "workspace.loading",
    error: "workspace.error",
    uploadLabel: "workspace.uploadLabel",
    operationLabel: "workspace.operationLabel",
    overlayLabel: "workspace.overlayLabel",
    run: "workspace.run",
    running: "workspace.running",
    empty: "workspace.empty",
    originalLabel: "workspace.originalLabel",
    resultLabel: "workspace.resultLabel",
    resultMeta: "workspace.resultMeta",
    metadataLabel: "workspace.metadataLabel",
    canvas: {
      empty: "workspace.canvas.empty",
      zoomIn: "workspace.canvas.zoomIn",
      zoomOut: "workspace.canvas.zoomOut",
      zoomFit: "workspace.canvas.zoomFit",
      zoomActual: "workspace.canvas.zoomActual",
      zoomLevel: "workspace.canvas.zoomLevel",
      compareToggle: "workspace.canvas.compareToggle",
      replace: "workspace.canvas.replace",
    },
    actions: {
      undo: "workspace.actions.undo",
      redo: "workspace.actions.redo",
      reset: "workspace.actions.reset",
      download: "workspace.actions.download",
    },
    history: {
      title: "workspace.history.title",
      empty: "workspace.history.empty",
      source: "workspace.history.source",
      step: "workspace.history.step",
    },
    mode: {
      edit: "workspace.mode.edit",
      enhance: "workspace.mode.enhance",
      create: "workspace.mode.create",
      analyze: "workspace.mode.analyze",
      switcherLabel: "workspace.mode.switcherLabel",
      comingSoon: "workspace.mode.comingSoon",
    },
    compare: {
      before: "workspace.compare.before",
      after: "workspace.compare.after",
      slider: "workspace.compare.slider",
    },
    field: {
      width: "workspace.field.width",
      height: "workspace.field.height",
      fit: "workspace.field.fit",
      gravity: "workspace.field.gravity",
      x: "workspace.field.x",
      y: "workspace.field.y",
      angle: "workspace.field.angle",
      background: "workspace.field.background",
      axis: "workspace.field.axis",
      brightness: "workspace.field.brightness",
      contrast: "workspace.field.contrast",
      gamma: "workspace.field.gamma",
      saturation: "workspace.field.saturation",
      hue: "workspace.field.hue",
      filter: "workspace.field.filter",
      amount: "workspace.field.amount",
      format: "workspace.field.format",
      quality: "workspace.field.quality",
      lossless: "workspace.field.lossless",
      targetBytes: "workspace.field.targetBytes",
      text: "workspace.field.text",
      position: "workspace.field.position",
      opacity: "workspace.field.opacity",
      color: "workspace.field.color",
      fontSize: "workspace.field.fontSize",
      stripAll: "workspace.field.stripAll",
      stripGps: "workspace.field.stripGps",
      autoOrient: "workspace.field.autoOrient",
    },
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
