import { useMemo, useState } from "react";
import { AlertCircle, ChevronDown, ChevronRight, FileEdit, Minus, Plus, ShieldAlert } from "lucide-react";
import { useBlame, useProvenance } from "../lib/hooks";
import type { BlameEvidence, ProvenanceFile, ProvenanceRunGroup, ProvenanceStanding } from "../lib/api";

interface AIProvenanceTabProps { repoId?: string | null; }

const STANDING_LABELS: Record<string, string> = { exact_content: "Exact content", commit_file: "Commit match", run_file: "Run overlap", work_reference: "Work reference", private: "Private", unavailable: "Unavailable", unknown: "Unknown" };

function changeTypeIcon(changeType: string) { switch (changeType) { case "added": return <Plus className="h-3 w-3 text-green-400" />; case "deleted": return <Minus className="h-3 w-3 text-red-400" />; default: return <FileEdit className="h-3 w-3 text-yellow-400" />; } }
function formatTimestamp(ts?: string): string { if (!ts) return "time unavailable"; const date = new Date(ts); return Number.isNaN(date.getTime()) ? ts : date.toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }); }
function truncateId(id: string, len = 10): string { return id.length > len ? `${id.slice(0, len)}…` : id; }
function standingTone(standing?: ProvenanceStanding): string { if (standing === "exact_content") return "border-emerald-700/60 bg-emerald-950/40 text-emerald-300"; if (standing === "commit_file") return "border-cyan-700/60 bg-cyan-950/40 text-cyan-300"; if (standing === "run_file" || standing === "work_reference") return "border-amber-700/60 bg-amber-950/40 text-amber-300"; if (standing === "private" || standing === "unavailable") return "border-red-700/60 bg-red-950/40 text-red-300"; return "border-slate-600 bg-slate-900/60 text-slate-300"; }
function StandingBadge({ standing }: { standing?: ProvenanceStanding }) { const value = standing || "unknown"; return <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${standingTone(value)}`}>{STANDING_LABELS[value] || value}</span>; }

function EvidenceCard({ evidence }: { evidence: BlameEvidence }) {
  const refs = evidence.workReferences ?? [];
  return <div className="rounded border border-slate-800 bg-slate-950/40 p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-slate-200">Linked evidence</span>{evidence.commitState && <span className="text-slate-500">state:{evidence.commitState}</span>}{evidence.runOutcome && <span className="text-slate-500">outcome:{evidence.runOutcome}</span>}{evidence.visibility === "private" && <ShieldAlert className="h-3.5 w-3.5 text-red-400" aria-label="Private evidence" />}</div><div className="mt-2 grid gap-1 text-slate-400 sm:grid-cols-2">{evidence.runId && <span>run <code className="text-slate-300">{truncateId(evidence.runId)}</code></span>}{evidence.sandboxId && <span>sandbox <code className="text-slate-300">{truncateId(evidence.sandboxId)}</code></span>}{evidence.commitId && <span>commit <code className="text-slate-300">{truncateId(evidence.commitId)}</code></span>}{evidence.committedAt && <span>committed {formatTimestamp(evidence.committedAt)}</span>}</div>{refs.length > 0 && <div className="mt-2 border-t border-slate-800 pt-2 text-slate-400"><span className="text-slate-500">work references:</span>{" "}{refs.map((ref) => <code key={`${ref.kind}:${ref.id}`} className="mr-2 text-cyan-300">{ref.kind}:{truncateId(ref.id)}</code>)}</div>}{(evidence.unavailable?.length ?? 0) > 0 && <div className="mt-2 text-amber-300">Unavailable: {evidence.unavailable?.join(", ")}</div>}</div>;
}

function FileDetail({ path, repoId }: { path: string; repoId?: string | null }) {
  const query = useBlame(path, repoId); const file = query.data?.files[0];
  if (query.isLoading) return <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4 text-xs text-slate-500">Loading native blame and linked evidence…</div>;
  if (query.error) return <div className="rounded-lg border border-red-900/60 bg-red-950/20 p-4 text-xs text-red-300">Evidence unavailable for this file.</div>;
  if (!file) return <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4 text-xs text-slate-500">No blame result returned.</div>;
  return <section className="rounded-lg border border-slate-700 bg-slate-900/50 p-4" aria-label={`Evidence detail for ${path}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-medium text-slate-100">{path}</h3><p className="mt-1 text-[11px] text-slate-500">revision: {query.data?.revision || "unknown"} · {file.status}</p></div><StandingBadge standing={file.standing} /></div>{file.downgradeReasons?.map((reason) => <p key={reason} className="mt-3 text-xs text-amber-300">Why this is not exact: {reason}</p>)}{file.reason && <p className="mt-3 text-xs text-slate-400">{file.reason}</p>}<div className="mt-4 grid gap-2">{file.evidence.length > 0 ? file.evidence.map((evidence, index) => <EvidenceCard key={`${evidence.runId ?? "evidence"}-${index}`} evidence={evidence} />) : <p className="text-xs text-slate-500">No linked evidence was available; authorship remains unknown.</p>}</div>{query.data?.truncated && <p className="mt-3 text-xs text-amber-300">Line output was bounded. This view is not a complete file receipt.</p>}{query.data?.warnings.map((warning) => <p key={warning} className="mt-2 text-xs text-amber-300">{warning}</p>)}</section>;
}

function RunGroupCard({ group, selectedPath, onSelect }: { group: ProvenanceRunGroup; selectedPath?: string; onSelect: (path: string) => void }) {
  const [expanded, setExpanded] = useState(true);
  return <div className="overflow-hidden rounded-lg border border-slate-700"><button type="button" onClick={() => setExpanded(!expanded)} className="flex w-full items-center gap-3 bg-slate-800/50 px-4 py-3 text-left transition-colors hover:bg-slate-800">{expanded ? <ChevronDown className="h-4 w-4 shrink-0 text-slate-400" /> : <ChevronRight className="h-4 w-4 shrink-0 text-slate-400" />}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium text-slate-200">{group.sandboxOwner || "Unknown owner"}</span>{group.runId && <code className="text-xs text-slate-500">run:{truncateId(group.runId)}</code>}</div><div className="mt-0.5 text-xs text-slate-500">{group.files.length} file{group.files.length !== 1 ? "s" : ""} · last applied {formatTimestamp(group.latestAppliedAt)}</div></div></button>{expanded && <div className="divide-y divide-slate-800">{group.files.map((file: ProvenanceFile) => { const path = file.relativePath || file.filePath; return <button key={file.filePath} type="button" onClick={() => onSelect(path)} className={`flex w-full items-center gap-2 px-4 py-2 text-left text-xs ${selectedPath === path ? "bg-blue-950/50" : "hover:bg-slate-900/70"}`}>{changeTypeIcon(file.changeType)}<span className="flex-1 truncate font-mono text-slate-300">{path}</span>{file.visibility === "private" && <ShieldAlert className="h-3.5 w-3.5 text-red-400" aria-label="Private evidence" />}<span className="shrink-0 text-slate-600">{formatTimestamp(file.appliedAt)}</span></button>; })}</div>}</div>;
}

export function AIProvenanceTab({ repoId }: AIProvenanceTabProps) {
  const provenanceQuery = useProvenance(repoId); const groups = provenanceQuery.data?.runGroups ?? [];
  const firstPath = useMemo(() => groups[0]?.files[0] ? (groups[0].files[0].relativePath || groups[0].files[0].filePath) : undefined, [groups]);
  const [selectedPath, setSelectedPath] = useState<string>(); const activePath = selectedPath || firstPath;
  if (provenanceQuery.isLoading) return <div className="space-y-3"><div className="h-20 animate-pulse rounded-lg bg-slate-800" /><div className="h-20 animate-pulse rounded-lg bg-slate-800" /></div>;
  if (provenanceQuery.error) return <div className="flex items-center gap-2 text-sm text-red-400"><AlertCircle className="h-4 w-4" />Failed to load provenance data</div>;
  if (!provenanceQuery.data?.available) return <div className="text-sm text-slate-500">{provenanceQuery.data?.warning || "Workspace Sandbox is not available"}</div>;
  if (groups.length === 0) return <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4 text-sm text-slate-500">No historical or pending AI-authored changes were found.</div>;
  return <div className="space-y-4"><div className="rounded-lg border border-blue-900/50 bg-blue-950/20 p-3 text-xs text-blue-200">Provenance Explorer · historical and pending evidence · path overlap never proves authorship.</div><div className="grid gap-4 xl:grid-cols-[minmax(18rem,0.8fr)_minmax(24rem,1.2fr)]"><div className="space-y-3">{groups.map((group) => <RunGroupCard key={group.runId || group.sandboxId} group={group} selectedPath={activePath} onSelect={setSelectedPath} />)}</div>{activePath ? <FileDetail path={activePath} repoId={repoId} /> : <div className="rounded-lg border border-slate-800 p-4 text-sm text-slate-500">Select a file to inspect evidence.</div>}</div></div>;
}
