import { useState, type ComponentProps } from "react";
import { act, cleanup, fireEvent, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useLocation } from "react-router-dom";
import { getSpatialNav } from "@vrooli/iframe-bridge/spatial";
import { SessionConversation } from "./SessionConversation";
import { createTestQueryClient, renderWithProviders } from "../../test-utils";
import { defaultApiClient } from "../../lib/api-client";
import { useBacklogStore, useExecutionStore } from "../../stores";
import { parseProtoResponse } from "../../services/proto-contracts";
import { getAgentSessionResponseSchema, mapProtoAgentSession } from "../../services/proto/agent-session-contracts";
import type { SessionContextOption } from "./context/session-context-refs";
import type { QueryClient } from "@tanstack/react-query";
const context:SessionContextOption={type:"backlog_item",ref:"fix/fixture-owner",title:"Fixture owner",nodeId:"backlog-item/fix/fixture-owner",summary:"Original operator-owned context"};
const sibling:SessionContextOption={type:"goal",ref:"fixture-goal",title:"Fixture goal",nodeId:"goal/fixture-goal"};
type Props=ComponentProps<typeof SessionConversation>;
const send=vi.fn(),changes=vi.fn(),jobs=vi.fn(),retry=vi.fn(),edit=vi.fn(),contexts=vi.fn(),densities=vi.fn(),attach=vi.fn(),remove=vi.fn();
let allowedPost:unknown[][];let unexpected:string[];let external:()=>Response|Promise<Response>;const clients:QueryClient[]=[];const views:{unmount:()=>void}[]=[];
function Location(){const l=useLocation();return <output data-testid="fixture-location">{l.pathname+l.search}</output>;}
function Harness({options={}}:{options?:Partial<Props>}){const{draft:initialDraft,pendingContext:initialPending,density:initialDensity,starterJobId:initialJob,...rest}=options;const[draft,setDraft]=useState(initialDraft??"");const[job,setJob]=useState(initialJob);const[pending,setPending]=useState(initialPending??[]);const[density,setDensity]=useState(initialDensity??"comfortable");return <><Location/><SessionConversation messages={[]} draft={draft} onDraftChange={v=>{changes(v);setDraft(v);}} onSend={send} isMutating={false} isWaitingForAgent={false} sessionKind="workflow_authoring" sessionStatus="waiting_for_user" sessionId="fixture-session" attachments={[]} pendingAttachments={[]} onAttachFiles={attach} onRemovePendingAttachment={remove} pendingContext={pending} onPendingContextChange={v=>{contexts(v);setPending(v);}} density={density} onDensityChange={v=>{densities(v);setDensity(v);}} onRetryPendingMessage={retry} onEditPendingMessage={edit} {...rest} starterJobId={job} onStarterJobChange={(id,opener)=>{jobs(id,opener);setJob(id);}}/></>;}
function mount(options:Partial<Props>={}){const client=createTestQueryClient();clients.push(client);const view=renderWithProviders(<Harness options={options}/>,{queryClient:client,initialEntries:["/sessions/fixture-session"]});views.push(view);return{client,...view};}
function session(raw:Record<string,unknown>){const enriched={...raw,messages:Array.isArray(raw.messages)?raw.messages.map((m:Record<string,unknown>)=>({created_at:"2026-10-05T00:00:00Z",...m,...(Array.isArray(m.context)?{context:m.context.map((c:Record<string,unknown>)=>({selected_at:"2026-10-05T00:00:00Z",...c}))}:{})})):[],attachments:Array.isArray(raw.attachments)?raw.attachments.map(v=>({created_at:"2026-10-05T00:00:00Z",...v})):[]};const parsed=parseProtoResponse(getAgentSessionResponseSchema,{session:{skill_id:"fixture-skill",created_at:"2026-10-05T00:00:00Z",updated_at:"2026-10-05T00:00:00Z",id:"fixture-session",title:"Fixture",kind:"workflow_authoring",status:"waiting_for_user",...enriched}},"fixture session");if(!parsed.session)throw new Error("Missing fixture session");return mapProtoAgentSession(parsed.session);}
beforeEach(()=>{allowedPost=[];unexpected=[];external=()=>new Response(JSON.stringify({url:"https://fixture.invalid/agent-manager/"}),{headers:{"content-type":"application/json"}});for(const fn of [send,changes,jobs,retry,edit,contexts,densities,attach,remove])fn.mockReset();useBacklogStore.getState().reset();useExecutionStore.getState().reset();vi.spyOn(defaultApiClient,"get").mockImplementation(async path=>{if(path.startsWith("/backlog"))return{items:[],blocking:{}};if(path.startsWith("/execution"))return{items:[]};if(path==="/settings")return{settings:{}};unexpected.push("GET "+path);throw new Error("Unexpected fixture GET "+path);});for(const method of ["post","put","patch","delete"] as const)vi.spyOn(defaultApiClient,method).mockRejectedValue(new Error("Unexpected fixture "+method));vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const request=new Request(input,init);const path=new URL(request.url).pathname;if(request.method==="GET"&&path==="/embedded/agent-manager/external-url")return external();const readReplies:Record<string,unknown>={"/vrooli.swarm_manager.v1.audio_runtime.AudioRuntimeService/ListVoices":{voices:[]},"/vrooli.swarm_manager.v1.audio_admin.AudioAdminService/GetStreamConfig":{config:{}},"/vrooli.swarm_manager.v1.audio_admin.AudioAdminService/GetWakeWordConfig":{config:{}}};if(request.method==="POST"&&path in readReplies){expect(JSON.parse(await request.text())).toEqual({});return new Response(JSON.stringify(readReplies[path]),{headers:{"content-type":"application/json"}});}unexpected.push(request.method+" "+new URL(request.url).pathname);throw new Error("Unexpected fixture fetch");}));});
afterEach(()=>{views.splice(0).forEach(v=>v.unmount());cleanup();getSpatialNav()?.dispose();clients.splice(0).forEach(c=>c.clear());useBacklogStore.getState().reset();useExecutionStore.getState().reset();expect(unexpected).toEqual([]);expect(vi.mocked(defaultApiClient.post).mock.calls).toEqual(allowedPost);for(const method of ["put","patch","delete"] as const)expect(defaultApiClient[method]).not.toHaveBeenCalled();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe("actual conversation composer and recovery callback ownership",()=>{
 it("keeps empty continuation unsendable and offers one explicit nonempty message callback",()=>{mount();const submit=screen.getByRole("button",{name:"Send"});expect(submit).toBeDisabled();fireEvent.click(submit);expect(send).not.toHaveBeenCalled();fireEvent.change(screen.getByRole("textbox",{name:"Continue this session..."}),{target:{value:"Owner message"}});expect(submit).not.toBeDisabled();fireEvent.click(submit);expect(send).toHaveBeenCalledOnce();expect(changes).toHaveBeenCalledWith("Owner message");});
 it("disables composer and preview during parent mutation with zero send or preview effects",()=>{mount({draft:"Pending owner message",isMutating:true});expect(screen.getByRole("textbox")).toBeDisabled();for(const name of ["Send","Preview prompt"]){const b=screen.getByRole("button",{name});expect(b).toBeDisabled();fireEvent.click(b);}expect(send).not.toHaveBeenCalled();});
 it.each(["comfortable","compact"] as const)("offers only the chosen %s density callback",density=>{mount();fireEvent.click(screen.getByTestId("agent-session-density-"+density));expect(densities.mock.calls).toEqual([[density]]);expect(screen.getByTestId("agent-session-density-"+density)).toHaveAttribute("aria-pressed","true");expect(send).not.toHaveBeenCalled();});
 it("retains sorted canonical messages and the unaccepted optimistic message at the tail",()=>{const owner=session({messages:[{id:"later",role:"assistant",content:"Later canonical message",created_at:"2026-10-05T02:00:00Z"},{id:"earlier",role:"user",content:"Earlier canonical message",created_at:"2026-10-05T01:00:00Z"}]});mount({messages:owner.messages,pendingMessage:{id:"local",role:"user",content:"Unaccepted pending message",delivery:"sending",createdAt:"2026-10-05T00:00:00Z"}});const earlier=screen.getByText("Earlier canonical message"),later=screen.getByText("Later canonical message"),pending=screen.getByText("Unaccepted pending message");expect(earlier.compareDocumentPosition(later)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(later.compareDocumentPosition(pending)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.queryByTestId("agent-session-message-retry")).toBeNull();expect(retry).not.toHaveBeenCalled();});
 it("offers retry and edit only for a failed local message, without issuing its own send",()=>{mount({pendingMessage:{id:"failed",role:"user",content:"Unaccepted failed message",delivery:"failed"}});fireEvent.click(screen.getByTestId("agent-session-message-retry"));fireEvent.click(screen.getByTestId("agent-session-message-edit"));expect(retry).toHaveBeenCalledOnce();expect(edit).toHaveBeenCalledOnce();expect(send).not.toHaveBeenCalled();});
 it("removes only matching pending context and retains the other owner",()=>{mount({pendingContext:[context,sibling]});fireEvent.click(screen.getByRole("button",{name:"Remove Fixture owner"}));expect(contexts.mock.calls).toEqual([[[sibling]]]);expect(screen.queryByRole("button",{name:"Remove Fixture owner"})).toBeNull();expect(screen.getByRole("button",{name:"Remove Fixture goal"})).toBeVisible();expect(send).not.toHaveBeenCalled();});
 it("discloses pending context text and navigates exact detail on explicit intent",()=>{mount({pendingContext:[context]});fireEvent.click(screen.getByRole("button",{name:"Item Fixture owner"}));expect(screen.getByText("Original operator-owned context")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Open details"}));expect(screen.getByTestId("fixture-location")).toHaveTextContent("/backlog/fix/fixture-owner");expect(send).not.toHaveBeenCalled();});
 it("renders only message-attributed attachments and context, preserving canonical exact routes",()=>{const owner=session({messages:[{id:"confirmed",role:"assistant",content:"Canonical attributed message",attachment_ids:["included","missing"],context:[{type:"goal",ref:"fixture-goal",title:"Canonical goal",node_id:"goal/fixture-goal"}]}],attachments:[{id:"included",filename:"Included owner image",content_type:"image/png"},{id:"unrelated",filename:"Unrelated owner image",content_type:"image/png"}]});mount({messages:owner.messages,attachments:owner.attachments});expect(screen.getByAltText("Included owner image")).toHaveAttribute("src","/agent-sessions/fixture-session/attachments/included");expect(screen.queryByAltText("Unrelated owner image")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"goal Canonical goal"}));fireEvent.click(screen.getByRole("button",{name:"Open details"}));expect(screen.getByTestId("fixture-location")).toHaveTextContent("/goals/fixture-goal");});
 it("resolves exact provided profile/run links without navigating or attaching a run",async()=>{mount({profileKey:"fixture profile",runId:"fixture/run"});expect(await screen.findByRole("link",{name:"Open profile fixture profile in a new tab"})).toHaveAttribute("href","https://fixture.invalid/agent-manager/profiles?profileKey=fixture%20profile");expect(screen.getByRole("link",{name:"Open run fixture/run in a new tab"})).toHaveAttribute("href","https://fixture.invalid/agent-manager/runs/fixture%2Frun");expect(send).not.toHaveBeenCalled();});
 it("keeps unresolved embedded ownership as metadata without guessing a link",async()=>{external=()=>new Response(JSON.stringify({}),{headers:{"content-type":"application/json"}});mount({profileKey:"fixture profile",runId:"fixture-run"});await waitFor(()=>expect(fetch).toHaveBeenCalled());expect(screen.getByTestId("agent-session-conversation-profile").tagName).toBe("SPAN");expect(screen.getByTestId("agent-session-conversation-run").tagName).toBe("SPAN");expect(screen.queryByRole("link")).toBeNull();});
});
describe("actual starter job selection without session dispatch",()=>{
 it("seeds an empty operator composer, then clears the selected job on a second click",()=>{mount({sessionStatus:"draft"});const card=screen.getByRole("button",{name:/Describe a way of working/});fireEvent.click(card);expect(jobs.mock.calls).toEqual([["workflow-author-method","Here is how I work:"]]);expect(screen.getByRole("textbox")).toHaveValue("Here is how I work:\n\n");expect(screen.getByRole("button",{name:"Send"})).not.toBeDisabled();fireEvent.click(card);expect(jobs.mock.calls.at(-1)).toEqual([undefined,undefined]);expect(screen.getByRole("textbox")).toHaveValue("");expect(send).not.toHaveBeenCalled();});
 it("changes selected job while preserving explicit operator text",()=>{mount({sessionStatus:"draft",draft:"My explicit owner text"});fireEvent.click(screen.getByRole("button",{name:/Something about working with agents/}));expect(jobs.mock.calls).toEqual([["workflow-author-friction","Here is what is bothering me:"]]);expect(screen.getByRole("textbox")).toHaveValue("My explicit owner text");expect(changes).not.toHaveBeenCalled();expect(send).not.toHaveBeenCalled();});
});
describe("actual server-owned prompt preview adapter",()=>{
 it.each([true,false])("retains exact %s initial/continuation prompt bytes with exact offered context/job",async initial=>{const prompt="Fixture owner prompt\n<script>literal</script>";allowedPost=[["/agent-sessions/fixture-session/prompt-preview",{message:"Owner draft",attachment_ids:[],context_refs:[{type:"backlog_item",ref:context.ref}],starter_job_id:"workflow-author-method"}]];vi.mocked(defaultApiClient.post).mockResolvedValue({prompt,initial});mount({draft:"Owner draft",pendingContext:[context],starterJobId:"workflow-author-method"});fireEvent.click(screen.getByRole("button",{name:"Preview prompt"}));expect(await screen.findByTestId("session-prompt-preview-text")).toHaveTextContent("Fixture owner prompt");expect(screen.getByTestId("session-prompt-preview-text").textContent).toBe(prompt);expect(screen.getByTestId("session-prompt-preview-text").querySelector("script")).toBeNull();expect(screen.getByText(initial?/The full initial prompt/:/The continuation prompt/)).toBeVisible();expect(send).not.toHaveBeenCalled();});
 it("retains a visible upstream preview refusal without fallback or automatic retry",async()=>{allowedPost=[["/agent-sessions/fixture-session/prompt-preview",{message:"Owner draft",attachment_ids:[],context_refs:[]}]];vi.mocked(defaultApiClient.post).mockRejectedValue(new Error("Exact preview owner refused"));mount({draft:"Owner draft"});fireEvent.click(screen.getByRole("button",{name:"Preview prompt"}));expect(await screen.findByText("Exact preview owner refused")).toBeVisible();expect(screen.queryByTestId("session-prompt-preview-text")).toBeNull();expect(defaultApiClient.post).toHaveBeenCalledOnce();expect(send).not.toHaveBeenCalled();});
 it("shows owner preview pending without displaying invented prompt content",async()=>{let finish!:(value:unknown)=>void;allowedPost=[["/agent-sessions/fixture-session/prompt-preview",{message:"Owner draft",attachment_ids:[],context_refs:[]}]];vi.mocked(defaultApiClient.post).mockImplementation(()=>new Promise(r=>{finish=r;}));mount({draft:"Owner draft"});fireEvent.click(screen.getByRole("button",{name:"Preview prompt"}));expect(await screen.findByText("Assembling…")).toBeVisible();expect(screen.queryByTestId("session-prompt-preview-text")).toBeNull();await act(async()=>finish({prompt:"Canonical finished prompt",initial:false}));expect(await screen.findByTestId("session-prompt-preview-text")).toHaveTextContent("Canonical finished prompt");expect(defaultApiClient.post).toHaveBeenCalledOnce();});
});
