import { cleanup, fireEvent, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { renderWithProviders } from "../../test-utils";
import { parseProtoResponse } from "../../services/proto-contracts";
import { listAgentSessionEventsResponseSchema, mapProtoAgentSessionRunEvent } from "../../services/proto/agent-session-contracts";
import { SessionEventTimeline } from "./SessionEventTimeline";
function event(fields:Record<string,unknown>={}){return mapProtoAgentSessionRunEvent(parseProtoResponse(listAgentSessionEventsResponseSchema,{events:[{id:"fixture-event",run_id:"fixture-run",sequence:"9",event_type:"message",...fields}]},"fixture events").events[0]!);}
beforeEach(()=>{vi.stubGlobal("fetch",vi.fn(()=>{throw new Error("Timeline is read-only display");}));});
afterEach(()=>{cleanup();const transport=fetch;vi.unstubAllGlobals();vi.restoreAllMocks();expect(transport).not.toHaveBeenCalled();});
describe("actual typed session event timeline display",()=>{
 it("shows an empty completed read and refreshes only on explicit intent",()=>{const refresh=vi.fn();renderWithProviders(<SessionEventTimeline events={[]} isLoading={false} error={null} onRefresh={refresh}/>);expect(screen.getByText("No run events yet.")).toBeVisible();expect(screen.getByText("Events will appear after the run starts.")).toBeVisible();expect(refresh).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Refresh"}));expect(refresh).toHaveBeenCalledOnce();});
 it("disables refresh during the owner read while retaining its exact error and existing rows",()=>{const refresh=vi.fn();renderWithProviders(<SessionEventTimeline events={[event({content:"Previously read content"})]} isLoading error="Owner event read refused" onRefresh={refresh}/>);expect(screen.getByRole("alert")).toHaveTextContent("Owner event read refused");expect(screen.getByText("Previously read content")).toBeVisible();expect(screen.getByRole("button",{name:"Refresh"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"Refresh"}));expect(refresh).not.toHaveBeenCalled();});
 it("distinguishes an empty pending read from an empty terminal read",()=>{renderWithProviders(<SessionEventTimeline events={[]} isLoading error={null} onRefresh={vi.fn()}/>);expect(screen.getByText("Loading run events...")).toBeVisible();expect(screen.queryByText("Events will appear after the run starts.")).toBeNull();});
 it.each([{event_type:"tool_call",tool_name:"fixture-tool",label:"Tool call: fixture-tool"},{event_type:"tool_result",tool_name:"fixture-tool",label:"Tool result: fixture-tool"},{event_type:"tool_call",label:"Tool call"},{event_type:"tool_result",label:"Tool result"},{event_type:"message",role:"assistant",label:"Message: assistant"},{event_type:"message",label:"Message"},{event_type:"status",label:"Status"},{event_type:"error",label:"Error"},{event_type:"log",label:"log"},{event_type:"compaction",label:"Compaction"},{event_type:"message_deleted",label:"message deleted"},{event_type:"not-a-declared-event",label:"unknown"}])("renders declared or normalized event identity $label without inventing attribution",fields=>{const {label,...raw}=fields;renderWithProviders(<SessionEventTimeline events={[event(raw)]} isLoading={false} error={null} onRefresh={vi.fn()}/>);expect(screen.getByText(label)).toBeVisible();expect(screen.getByText("#9")).toBeVisible();expect(screen.getByText("1 run events")).toBeVisible();});
 it.each([{content:"Owner content",error:"Ignored error",progress_message:"Ignored progress",text:"Owner content"},{error:"Owner error",progress_message:"Ignored progress",text:"Owner error"},{progress_message:"Owner progress",status:"ignored",text:"Owner progress"},{previous_status:"pending",status:"running",text:"pending -> running"},{status:"complete",text:"complete"},{summary:"Owner summary",output:"Ignored output",text:"Owner summary"},{output:"Owner output",text:"Owner output"}])("retains exact meaningful event summary $text",fields=>{const {text,...raw}=fields;renderWithProviders(<SessionEventTimeline events={[event(raw)]} isLoading={false} error={null} onRefresh={vi.fn()}/>);expect(screen.getByText(text)).toBeVisible();expect(screen.queryByText(/^Ignored/)).toBeNull();});
 it("discloses exact input payload safely as text before raw fallback and preserves supplied order",()=>{renderWithProviders(<SessionEventTimeline events={[event({input:'<script>fixture</script>',raw_json:'{ "ignored": true }',content:"Input event"}),event({id:"",sequence:"10",event_type:"log",raw_json:'{ "fixture": true }',content:"Raw event"})]} isLoading={false} error={null} onRefresh={vi.fn()} variant="plain"/>);const rows=screen.getAllByRole("listitem");expect(rows).toHaveLength(2);expect(within(rows[0]!).getByText("Input event")).toBeVisible();expect(within(rows[1]!).getByText("Raw event")).toBeVisible();expect(rows[0]!.querySelector("pre")).toHaveTextContent('<script>fixture</script>');expect(rows[0]!.querySelector("script")).toBeNull();expect(rows[1]!.querySelector("pre")).toHaveTextContent('{ "fixture": true }');expect(screen.getAllByText("Payload")).toHaveLength(2);});
 it("omits absent summary and payload rather than fabricating run evidence",()=>{renderWithProviders(<SessionEventTimeline events={[event({event_type:"lifecycle",created_at:"2026-10-05T00:00:00Z"})]} isLoading={false} error={null} onRefresh={vi.fn()}/>);expect(screen.getByText("lifecycle")).toBeVisible();expect(screen.queryByText("Payload")).toBeNull();expect(screen.getAllByRole("listitem")).toHaveLength(1);});
 it("replaces stale display only when authoritative event props change",()=>{const refresh=vi.fn();const view=renderWithProviders(<SessionEventTimeline events={[event({content:"Original content"})]} isLoading={false} error={null} onRefresh={refresh}/>);view.rerender(<SessionEventTimeline events={[event({sequence:"11",content:"Canonical replacement"})]} isLoading={false} error={null} onRefresh={refresh}/>);expect(screen.queryByText("Original content")).toBeNull();expect(screen.getByText("Canonical replacement")).toBeVisible();expect(screen.getByText("#11")).toBeVisible();expect(refresh).not.toHaveBeenCalled();});
});
