#!/bin/bash

# ElectionGuard Default Configuration
# Environment variables and default values

# Service configuration
export ELECTIONGUARD_PORT="${ELECTIONGUARD_PORT:-18250}"
export ELECTIONGUARD_HOST="${ELECTIONGUARD_HOST:-0.0.0.0}"
export ELECTIONGUARD_LOG_LEVEL="${ELECTIONGUARD_LOG_LEVEL:-info}"

# Integration settings
export ELECTIONGUARD_VAULT_ENABLED="${ELECTIONGUARD_VAULT_ENABLED:-true}"
export ELECTIONGUARD_VAULT_URL="${ELECTIONGUARD_VAULT_URL:-http://localhost:8200}"
export ELECTIONGUARD_VAULT_PATH="${ELECTIONGUARD_VAULT_PATH:-/electionguard}"

# Database settings (optional)
export ELECTIONGUARD_DB_ENABLED="${ELECTIONGUARD_DB_ENABLED:-false}"
export ELECTIONGUARD_DB_TYPE="${ELECTIONGUARD_DB_TYPE:-postgres}"
export ELECTIONGUARD_DB_HOST="${ELECTIONGUARD_DB_HOST:-localhost}"
export ELECTIONGUARD_DB_PORT="${ELECTIONGUARD_DB_PORT:-5432}"
export ELECTIONGUARD_DB_NAME="${ELECTIONGUARD_DB_NAME:-electionguard}"

# QuestDB settings (optional)
export ELECTIONGUARD_QUESTDB_ENABLED="${ELECTIONGUARD_QUESTDB_ENABLED:-false}"
export ELECTIONGUARD_QUESTDB_HOST="${ELECTIONGUARD_QUESTDB_HOST:-localhost}"
export ELECTIONGUARD_QUESTDB_PORT="${ELECTIONGUARD_QUESTDB_PORT:-9000}"

# Workflow automation (optional)
export ELECTIONGUARD_N8N_ENABLED="${ELECTIONGUARD_N8N_ENABLED:-false}"
export ELECTIONGUARD_N8N_WEBHOOK="${ELECTIONGUARD_N8N_WEBHOOK:-}"
export ELECTIONGUARD_WINDMILL_ENABLED="${ELECTIONGUARD_WINDMILL_ENABLED:-false}"
export ELECTIONGUARD_WINDMILL_URL="${ELECTIONGUARD_WINDMILL_URL:-}"

# Election defaults
export ELECTIONGUARD_DEFAULT_GUARDIANS="${ELECTIONGUARD_DEFAULT_GUARDIANS:-5}"
export ELECTIONGUARD_DEFAULT_THRESHOLD="${ELECTIONGUARD_DEFAULT_THRESHOLD:-3}"
export ELECTIONGUARD_KEY_SIZE="${ELECTIONGUARD_KEY_SIZE:-4096}"

# Performance settings
export ELECTIONGUARD_WORKERS="${ELECTIONGUARD_WORKERS:-4}"
export ELECTIONGUARD_MAX_BATCH_SIZE="${ELECTIONGUARD_MAX_BATCH_SIZE:-100}"
export ELECTIONGUARD_CACHE_ENABLED="${ELECTIONGUARD_CACHE_ENABLED:-true}"

# Security settings
export ELECTIONGUARD_REQUIRE_AUTH="${ELECTIONGUARD_REQUIRE_AUTH:-false}"
export ELECTIONGUARD_API_TOKEN="${ELECTIONGUARD_API_TOKEN:-}"
export ELECTIONGUARD_CORS_ENABLED="${ELECTIONGUARD_CORS_ENABLED:-true}"
export ELECTIONGUARD_CORS_ORIGINS="${ELECTIONGUARD_CORS_ORIGINS:-*}"

# Data paths (RESOURCE_DIR is set by cli.sh)
RESOURCE_DIR="${RESOURCE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
export ELECTIONGUARD_DATA_DIR="${ELECTIONGUARD_DATA_DIR:-${RESOURCE_DIR}/data}"
export ELECTIONGUARD_LOG_DIR="${ELECTIONGUARD_LOG_DIR:-${RESOURCE_DIR}/logs}"