# Automation Triggers Configuration for Scenario Generator V1
# Defines event-driven automation and workflow triggers

triggers:
  # Scenario Generation Request Trigger
  scenario_generation_request:
    type: webhook
    endpoint: "/api/generate"
    method: POST
    target: main-workflow
    description: "Triggers complete scenario generation pipeline when new request received"
    validation:
      required_fields:
        - scenario_name
        - description
      optional_fields:
        - complexity
        - category
        - business_value
        - planning_iterations
        - implementation_iterations
        - validation_iterations
    retry_policy:
      max_attempts: 3
      backoff_multiplier: 2
      initial_delay: 5000

  # N8N Direct Generation Trigger  
  n8n_generation_trigger:
    type: webhook
    endpoint: "/webhook/generate-scenario"
    method: POST
    target: scenario-generator-orchestrator
    description: "Direct N8N workflow trigger for scenario generation"
    validation:
      required_fields:
        - scenario_name
        - description
    timeout: 300000

  # React UI Integration Triggers
  ui_form_trigger:
    type: webhook
    endpoint: "/webhook/generate-scenario"
    target: n8n_generation_trigger
    description: "React UI form submission triggers generation"
    
  template_trigger:
    type: webhook
    endpoint: "/webhook/use-template"
    target: scenario_generation_request
    description: "Template-based generation trigger"

  # File System Triggers
  plan_completion_trigger:
    type: file_watcher
    watch_path: "/tmp/scenario-plans/"
    file_pattern: "*-plan-complete.json"
    target: implementation-workflow
    description: "Triggers implementation when planning phase completes"
    cleanup: true

  implementation_completion_trigger:
    type: file_watcher
    watch_path: "/tmp/scenario-implementations/"  
    file_pattern: "*-impl-complete.json"
    target: validation-workflow
    description: "Triggers validation when implementation phase completes"
    cleanup: true

  # Database Event Triggers
  scenario_status_change:
    type: database_trigger
    table: scenarios
    event: UPDATE
    condition: "status IN ('completed', 'failed')"
    target: notification-workflow
    description: "Sends notifications when scenario generation completes or fails"

  template_usage_trigger:
    type: database_trigger
    table: scenario_templates
    event: INSERT
    target: analytics-update-workflow
    description: "Updates analytics when new templates are used"

  # Scheduled Triggers
  cleanup_temp_files:
    type: cron
    schedule: "0 2 * * *" # Daily at 2 AM
    target: cleanup-workflow
    description: "Daily cleanup of temporary generation files"

  analytics_refresh:
    type: cron
    schedule: "0 */6 * * *" # Every 6 hours
    target: analytics-refresh-workflow
    description: "Refresh generation analytics and performance metrics"

  health_check:
    type: cron
    schedule: "*/15 * * * *" # Every 15 minutes
    target: health-check-workflow
    description: "Monitor system health and resource availability"

# Error Handling Configuration
error_handling:
  default_retry_attempts: 2
  escalation_workflow: error-escalation-workflow
  notification_channels:
    - email: admin@vrooli.com
    - webhook: http://localhost:5681/api/notifications
    - log: /var/log/scenario-generator/errors.log

# Rate Limiting
rate_limits:
  scenario_generation_request:
    requests_per_minute: 10
    requests_per_hour: 100
    burst_size: 5
    
  n8n_generation_trigger:
    requests_per_minute: 5
    requests_per_hour: 50
    burst_size: 2

# Monitoring and Metrics
monitoring:
  enable_metrics: true
  metrics_endpoint: "/api/metrics"
  tracking:
    - trigger_activations
    - success_rates
    - execution_times
    - error_rates
    - resource_usage
  
  alerts:
    failure_rate_threshold: 20 # percent
    response_time_threshold: 60000 # milliseconds
    notification_target: error-escalation-workflow