import { beforeEach, describe, expect, it, vi } from "vitest";
import { screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { renderWithProviders } from "../../test-utils";
const generatePlan = vi.hoisted(() => vi.fn());
const listRecipes = vi.hoisted(() => vi.fn());
const applyPlan = vi.hoisted(() => vi.fn());
const previewSwap = vi.hoisted(() => vi.fn());
vi.mock("../../api/planning", () => ({ generatePlan, applyPlan, previewSwap }));
vi.mock("../../api/recipes", () => ({ listRecipes }));
vi.mock("../../api/workspace", () => ({ ensureWorkspace: vi.fn().mockResolvedValue({ id: "w1" }) }));
import { WeekPage } from "./WeekPage";
describe("WeekPage", () => { beforeEach(() => { vi.clearAllMocks(); listRecipes.mockResolvedValue([]); }); it("renders seven explicit dinner rows and supports navigation", async () => { const user = userEvent.setup(); generatePlan.mockResolvedValue({ occurrences: [], unresolved: [], currentRevision: 0n }); renderWithProviders(<WeekPage />); await waitFor(() => expect(screen.getAllByText(/Open dinner slot/)).toHaveLength(7)); await user.click(screen.getByRole("button", { name: "Next week" })); expect(generatePlan).toHaveBeenCalledTimes(2); }); it("supports explicit lock and skip controls", async () => { const user = userEvent.setup(); const date = new Date().toISOString().slice(0, 10); generatePlan.mockResolvedValue({ occurrences: [{ date, recipeId: "a", recipeName: "A", locked: false, reason: "Known fit" }], unresolved: [], currentRevision: 1n }); applyPlan.mockResolvedValue({ revision: 2n }); renderWithProviders(<WeekPage />); await waitFor(() => expect(screen.getByRole("button", { name: "Lock" })).toBeInTheDocument()); await user.click(screen.getByRole("button", { name: "Lock" })); expect(screen.getByRole("button", { name: "Unlock" })).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Skip" })); expect(screen.getByText("Skipped / open")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Save week" })); expect(applyPlan).toHaveBeenCalled(); }); it("previews and applies a scoped swap", async () => { const user = userEvent.setup(); const date = new Date().toISOString().slice(0, 10); generatePlan.mockResolvedValue({ occurrences: [{ date, recipeId: "a", recipeName: "A", locked: false, reason: "Known fit" }], unresolved: [], currentRevision: 1n }); listRecipes.mockResolvedValue([{ id: "b", name: "B" }]); previewSwap.mockResolvedValue({ revision: 1n, preview: { draft: { occurrences: [{ date, recipeId: "b", recipeName: "B", locked: false, reason: "swapped" }], unresolved: [], inputReferences: [], runId: "seed-0", seed: 0, currentRevision: 1n }, changes: [{ date, beforeName: "A", afterName: "B" }] }, affectedDates: [date] }); applyPlan.mockResolvedValue({ revision: 2n }); renderWithProviders(<WeekPage />); await waitFor(() => expect(screen.getByRole("heading", { name: "Your dinner week" })).toBeInTheDocument()); await user.click(screen.getByRole("button", { name: "Swap meal" })); await user.selectOptions(screen.getByLabelText("Replacement meal"), "b"); await user.click(screen.getByRole("button", { name: "Preview swap" })); await waitFor(() => expect(screen.getByText(/A → B/)).toBeInTheDocument()); await user.click(screen.getByRole("button", { name: "Apply swap" })); await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument()); expect(applyPlan).toHaveBeenCalled(); }); });

describe("Week swap dialog keyboard behavior", () => { beforeEach(() => { vi.clearAllMocks(); listRecipes.mockResolvedValue([{ id: "b", name: "B" }]); }); it("focuses the dialog and restores the trigger on Escape", async () => { const user = userEvent.setup(); const date = new Date().toISOString().slice(0, 10); generatePlan.mockResolvedValue({ occurrences: [{ date, recipeId: "a", recipeName: "A", locked: false, reason: "Known fit" }], unresolved: [], currentRevision: 1n }); renderWithProviders(<WeekPage />); await waitFor(() => expect(screen.getByRole("button", { name: "Swap meal" })).toBeInTheDocument()); const trigger = screen.getByRole("button", { name: "Swap meal" }); await user.click(trigger); expect(screen.getByLabelText("Replacement meal")).toHaveFocus(); await user.keyboard("{Escape}"); expect(screen.queryByRole("dialog")).not.toBeInTheDocument(); expect(trigger).toHaveFocus(); }); });
