// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      agents: "layout.nav.agents",
      channels: "layout.nav.channels",
      contacts: "layout.nav.contacts",
      conversations: "layout.nav.conversations",
      dashboard: "layout.nav.dashboard",
      settings: "layout.nav.settings",
    },
    sidebarLabel: "layout.sidebarLabel",
    navShort: {
      dashboard: "layout.navShort.dashboard",
      conversations: "layout.navShort.conversations",
    },
  },
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  console: {
    mainContent: "console.mainContent",
    common: {
      back: "console.common.back",
      cancel: "console.common.cancel",
      close: "console.common.close",
    },
    shell: {
      apiConnected: "console.shell.apiConnected",
      apiUnreachable: "console.shell.apiUnreachable",
    },
    attention: {
      pendingCount: "console.attention.pendingCount",
      pendingCount_one: "console.attention.pendingCount_one",
    },
    region: {
      loading: "console.region.loading",
      errorTitle: "console.region.errorTitle",
      retry: "console.region.retry",
    },
    tiers: {
      stranger: "console.tiers.stranger",
      known: "console.tiers.known",
      trusted: "console.tiers.trusted",
      owner: "console.tiers.owner",
      effect: {
        stranger: "console.tiers.effect.stranger",
        known: "console.tiers.effect.known",
        trusted: "console.tiers.effect.trusted",
        owner: "console.tiers.effect.owner",
      },
    },
    budget: {
      turnsThisHour: "console.budget.turnsThisHour",
      remaining: "console.budget.remaining",
      unlimited: "console.budget.unlimited",
      spend: "console.budget.spend",
      noSpendCap: "console.budget.noSpendCap",
      exhausted: "console.budget.exhausted",
      nearLimit: "console.budget.nearLimit",
    },
    capabilityGate: {
      title: "console.capabilityGate.title",
      withheld: "console.capabilityGate.withheld",
      unblock: "console.capabilityGate.unblock",
      expiresIn: "console.capabilityGate.expiresIn",
      grantOnce: "console.capabilityGate.grantOnce",
      notNow: "console.capabilityGate.notNow",
      ownerOnly: "console.capabilityGate.ownerOnly",
      status: {
        granted: "console.capabilityGate.status.granted",
        denied: "console.capabilityGate.status.denied",
        expired: "console.capabilityGate.status.expired",
      },
    },
    overview: {
      refresh: "console.overview.refresh",
      updated: "console.overview.updated",
      waitingOnYou: "console.overview.waitingOnYou",
      allClear: "console.overview.allClear",
      allClearDetail: "console.overview.allClearDetail",
      openThread: "console.overview.openThread",
      channelHealth: "console.overview.channelHealth",
      manageChannels: "console.overview.manageChannels",
      channelCounts: "console.overview.channelCounts",
      budgetPressure: "console.overview.budgetPressure",
      noBudgetPressure: "console.overview.noBudgetPressure",
      noBudgetPressureDetail: "console.overview.noBudgetPressureDetail",
      recentRefusals: "console.overview.recentRefusals",
      noRefusals: "console.overview.noRefusals",
      noRefusalsDetail: "console.overview.noRefusalsDetail",
      stats: {
        liveChannels: "console.overview.stats.liveChannels",
        ofTotal: "console.overview.stats.ofTotal",
        threads: "console.overview.stats.threads",
        agents: "console.overview.stats.agents",
        contacts: "console.overview.stats.contacts",
      },
    },
    conversations: {
      title: "console.conversations.title",
      description: "console.conversations.description",
      threads: "console.conversations.threads",
      search: "console.conversations.search",
      filterByChannel: "console.conversations.filterByChannel",
      allChannels: "console.conversations.allChannels",
      noMatches: "console.conversations.noMatches",
      noMessagesYet: "console.conversations.noMessagesYet",
      attachmentOnly: "console.conversations.attachmentOnly",
      groupRoom: "console.conversations.groupRoom",
      gateWaiting: "console.conversations.gateWaiting",
      emptyTitle: "console.conversations.emptyTitle",
      emptyDescription: "console.conversations.emptyDescription",
      startCta: "console.conversations.startCta",
      startTitle: "console.conversations.startTitle",
      startDescription: "console.conversations.startDescription",
      startConfirm: "console.conversations.startConfirm",
      pickThread: "console.conversations.pickThread",
      you: "console.conversations.you",
      agentMarker: "console.conversations.agentMarker",
      sending: "console.conversations.sending",
      message: "console.conversations.message",
      writePlaceholder: "console.conversations.writePlaceholder",
      send: "console.conversations.send",
      sendLabel: "console.conversations.sendLabel",
      attachFile: "console.conversations.attachFile",
      removeAttachment: "console.conversations.removeAttachment",
      sendFailed: "console.conversations.sendFailed",
      enterHint: "console.conversations.enterHint",
      connecting: "console.conversations.connecting",
      repliesLiveOn: "console.conversations.repliesLiveOn",
      speaksWhenAddressed: "console.conversations.speaksWhenAddressed",
      roster: "console.conversations.roster",
      roomCeiling: "console.conversations.roomCeiling",
      agentPermitted: "console.conversations.agentPermitted",
      agentRefusing: "console.conversations.agentRefusing",
      agentSilenced: "console.conversations.agentSilenced",
      strangerCeiling: "console.conversations.strangerCeiling",
      reviewContacts: "console.conversations.reviewContacts",
      sayHello: "console.conversations.sayHello",
      threadNotFound: "console.conversations.threadNotFound",
      threadNotFoundDetail: "console.conversations.threadNotFoundDetail",
    },
    agents: {
      title: "console.agents.title",
      description: "console.agents.description",
      newAgent: "console.agents.newAgent",
      emptyTitle: "console.agents.emptyTitle",
      empty: "console.agents.empty",
      createFirst: "console.agents.createFirst",
      live: "console.agents.live",
      paused: "console.agents.paused",
      unbound: "console.agents.unbound",
      brokenReference: "console.agents.brokenReference",
      reachableAt: "console.agents.reachableAt",
      notReachable: "console.agents.notReachable",
      reachesTerminal: "console.agents.reachesTerminal",
      defaultGrantShort: "console.agents.defaultGrantShort",
      activity24h: "console.agents.activity24h",
      sourceUnavailable: "console.agents.sourceUnavailable",
      sourceUnavailableShort: "console.agents.sourceUnavailableShort",
      draftDescription: "console.agents.draftDescription",
      descriptionLabel: "console.agents.descriptionLabel",
      descriptionPlaceholder: "console.agents.descriptionPlaceholder",
      draftHint: "console.agents.draftHint",
      prepareDraft: "console.agents.prepareDraft",
      reviewHeading: "console.agents.reviewHeading",
      reviewPlaceholder: "console.agents.reviewPlaceholder",
      displayName: "console.agents.displayName",
      proposedGrant: "console.agents.proposedGrant",
      defaultGrant: "console.agents.defaultGrant",
      confirmWrite: "console.agents.confirmWrite",
      notWritable: "console.agents.notWritable",
    },
    agentDetail: {
      editInPromptManager: "console.agentDetail.editInPromptManager",
      profileOwnedElsewhere: "console.agentDetail.profileOwnedElsewhere",
      whatItMayDo: "console.agentDetail.whatItMayDo",
      scopeGranted: "console.agentDetail.scopeGranted",
      programBinding: "console.agentDetail.programBinding",
      defaultGrant: "console.agentDetail.defaultGrant",
      descriptorGrant: "console.agentDetail.descriptorGrant",
      ownerOnlyNote: "console.agentDetail.ownerOnlyNote",
      attachToChannel: "console.agentDetail.attachToChannel",
      notReachableDetail: "console.agentDetail.notReachableDetail",
      budgets: "console.agentDetail.budgets",
      noThreads: "console.agentDetail.noThreads",
      recentActivity: "console.agentDetail.recentActivity",
      noActivity: "console.agentDetail.noActivity",
      activityKind: {
        turn: "console.agentDetail.activityKind.turn",
        refusal: "console.agentDetail.activityKind.refusal",
        suppressed: "console.agentDetail.activityKind.suppressed",
        gate: "console.agentDetail.activityKind.gate",
      },
      notFound: "console.agentDetail.notFound",
      notFoundDetail: "console.agentDetail.notFoundDetail",
    },
    channels: {
      title: "console.channels.title",
      description: "console.channels.description",
      emptyTitle: "console.channels.emptyTitle",
      emptyDetail: "console.channels.emptyDetail",
      availability: {
        available: "console.channels.availability.available",
        unavailable: "console.channels.availability.unavailable",
        unimplemented: "console.channels.availability.unimplemented",
        unknown: "console.channels.availability.unknown",
      },
      friction: {
        none: "console.channels.friction.none",
        low: "console.channels.friction.low",
        medium: "console.channels.friction.medium",
        high: "console.channels.friction.high",
      },
      setupEffort: "console.channels.setupEffort",
      supports: {
        images: "console.channels.supports.images",
        files: "console.channels.supports.files",
        groups: "console.channels.supports.groups",
        threads: "console.channels.supports.threads",
      },
      textLimit: "console.channels.textLimit",
      cost: {
        byok: "console.channels.cost.byok",
        metered: "console.channels.cost.metered",
      },
      toEnable: "console.channels.toEnable",
      satisfyRequirement: "console.channels.satisfyRequirement",
      showAll: "console.channels.showAll",
      attachAgent: "console.channels.attachAgent",
      attachTo: "console.channels.attachTo",
      attachFormLabel: "console.channels.attachFormLabel",
      bindingDescription: "console.channels.bindingDescription",
      agent: "console.channels.agent",
      address: "console.channels.address",
      addressPlaceholder: "console.channels.addressPlaceholder",
      addressHint: "console.channels.addressHint",
      threadKey: "console.channels.threadKey",
      threadKeyHint: "console.channels.threadKeyHint",
      confirmAttachment: "console.channels.confirmAttachment",
      attached: "console.channels.attached",
      goToConversations: "console.channels.goToConversations",
      descriptorLoaded: "console.channels.descriptorLoaded",
    },
    contacts: {
      title: "console.contacts.title",
      description: "console.contacts.description",
      emptyTitle: "console.contacts.emptyTitle",
      empty: "console.contacts.empty",
      search: "console.contacts.search",
      noMatches: "console.contacts.noMatches",
      pickContact: "console.contacts.pickContact",
      lastSeen: "console.contacts.lastSeen",
      firstSeen: "console.contacts.firstSeen",
      messages: "console.contacts.messages",
      rooms: "console.contacts.rooms",
      roomCount: "console.contacts.roomCount",
      people: "console.contacts.people",
      trustTier: "console.contacts.trustTier",
      changeTier: "console.contacts.changeTier",
      ceilingWarning: "console.contacts.ceilingWarning",
      ownerWarning: "console.contacts.ownerWarning",
      tierChanged: "console.contacts.tierChanged",
      roomsTitle: "console.contacts.roomsTitle",
      noRooms: "console.contacts.noRooms",
    },
    session: {
      title: "console.session.title",
      description: "console.session.description",
      email: "console.session.email",
      password: "console.session.password",
      signIn: "console.session.signIn",
      signOut: "console.session.signOut",
      badCredentials: "console.session.badCredentials",
    },
    call: {
      title: "console.call.title",
      description: "console.call.description",
      unavailableTitle: "console.call.unavailableTitle",
      unavailableDetail: "console.call.unavailableDetail",
      backToThread: "console.call.backToThread",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
    },
    settings: {
      title: "pages.settings.title",
      description: "pages.settings.description",
      themeHeading: "pages.settings.themeHeading",
      themeDescription: "pages.settings.themeDescription",
      localeHeading: "pages.settings.localeHeading",
      localeDescription: "pages.settings.localeDescription",
      descriptorHeading: "pages.settings.descriptorHeading",
      descriptorStatus: "pages.settings.descriptorStatus",
      trustHeading: "pages.settings.trustHeading",
      trustDescription: "pages.settings.trustDescription",
      trustRule1: "pages.settings.trustRule1",
      trustRule2: "pages.settings.trustRule2",
      trustRule3: "pages.settings.trustRule3",
      meteringHeading: "pages.settings.meteringHeading",
      meteringDescription: "pages.settings.meteringDescription",
      byokNote: "pages.settings.byokNote",
      aboutHeading: "pages.settings.aboutHeading",
    },
  },
} as const;

export type Strings = typeof strings;
