// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $schema: "$schema",
  app: {
    title: "app.title",
  },
  asset: "asset",
  capability: "capability",
  console: {
    agents: {
      confirmWrite: "console.agents.confirmWrite",
      confirmed: "console.agents.confirmed",
      defaultGrant: "console.agents.defaultGrant",
      description: "console.agents.description",
      descriptionLabel: "console.agents.descriptionLabel",
      descriptionPlaceholder: "console.agents.descriptionPlaceholder",
      draftDescription: "console.agents.draftDescription",
      draftHeading: "console.agents.draftHeading",
      prepareDraft: "console.agents.prepareDraft",
      reviewHeading: "console.agents.reviewHeading",
      title: "console.agents.title",
    },
    capabilityGate: {
      expires: "console.capabilityGate.expires",
      grantOnce: "console.capabilityGate.grantOnce",
      notNow: "console.capabilityGate.notNow",
      ownerOnly: "console.capabilityGate.ownerOnly",
      title: "console.capabilityGate.title",
      unblock: "console.capabilityGate.unblock",
      withheld: "console.capabilityGate.withheld",
    },
    channels: {
      address: "console.channels.address",
      addressPlaceholder: "console.channels.addressPlaceholder",
      agentId: "console.channels.agentId",
      attachAgent: "console.channels.attachAgent",
      attachFormLabel: "console.channels.attachFormLabel",
      attached: "console.channels.attached",
      attaching: "console.channels.attaching",
      bindingDescription: "console.channels.bindingDescription",
      cancel: "console.channels.cancel",
      confirmAttachment: "console.channels.confirmAttachment",
      connectRequirement: "console.channels.connectRequirement",
      description: "console.channels.description",
      descriptorLoaded: "console.channels.descriptorLoaded",
      setupFriction: "console.channels.setupFriction",
      threadKey: "console.channels.threadKey",
      title: "console.channels.title",
    },
    contacts: {
      description: "console.contacts.description",
      empty: "console.contacts.empty",
      title: "console.contacts.title",
    },
    conversations: {
      agent: "console.conversations.agent",
      attachFile: "console.conversations.attachFile",
      attachment: "console.conversations.attachment",
      connected: "console.conversations.connected",
      description: "console.conversations.description",
      disconnectError: "console.conversations.disconnectError",
      empty: "console.conversations.empty",
      message: "console.conversations.message",
      offline: "console.conversations.offline",
      send: "console.conversations.send",
      thread: "console.conversations.thread",
      title: "console.conversations.title",
      unreadableError: "console.conversations.unreadableError",
      writePlaceholder: "console.conversations.writePlaceholder",
      you: "console.conversations.you",
    },
    mainContent: "console.mainContent",
    surface: {
      agent: "console.surface.agent",
      agentDescription: "console.surface.agentDescription",
      call: "console.surface.call",
      callDescription: "console.surface.callDescription",
      channel: "console.surface.channel",
      channelDescription: "console.surface.channelDescription",
      contact: "console.surface.contact",
      contactDescription: "console.surface.contactDescription",
      nothingConfigured: "console.surface.nothingConfigured",
      welcome: "console.surface.welcome",
      welcomeDescription: "console.surface.welcomeDescription",
    },
  },
  default: "default",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  export: "export",
  fixture: "fixture",
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  id: "id",
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      agents: "layout.nav.agents",
      channels: "layout.nav.channels",
      contacts: "layout.nav.contacts",
      conversations: "layout.nav.conversations",
      dashboard: "layout.nav.dashboard",
      settings: "layout.nav.settings",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  mode: "mode",
  module: "module",
  name: "name",
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  pages: {
    dashboard: {
      description: "pages.dashboard.description",
      statPlaceholderLabel: "pages.dashboard.statPlaceholderLabel",
      title: "pages.dashboard.title",
    },
    settings: {
      blastRadius: "pages.settings.blastRadius",
      byokLabel: "pages.settings.byokLabel",
      byokNote: "pages.settings.byokNote",
      descriptorHeading: "pages.settings.descriptorHeading",
      descriptorStatus: "pages.settings.descriptorStatus",
      localeHeading: "pages.settings.localeHeading",
      meteringHeading: "pages.settings.meteringHeading",
      quietHoursDescription: "pages.settings.quietHoursDescription",
      quietHoursHeading: "pages.settings.quietHoursHeading",
      save: "pages.settings.save",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
  },
  path: "path",
  react: "react",
  region: "region",
  resolvedAt: "resolvedAt",
  role: "role",
  selector: "selector",
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  title: "title",
  true: "true",
  value: "value",
  version: "version",
} as const;

export type Strings = typeof strings;
