/**
 * Domain types for Swarm Manager
 *
 * This module contains the core domain types that represent the business concepts.
 * These types are shared across the UI and should match the API contract.
 *
 * DOC: docs/concepts/ARCHITECTURE.md#domain-concepts
 * DOC: docs/internal/SEAMS.md#module-boundaries
 * DOC: docs/internal/INTENT.md#module-responsibilities
 */

// ============================================================================
// Backlog Domain
// ============================================================================

/**
 * Valid lifecycle states for a backlog item
 */
export type BacklogStatus =
  | "backlog"
  | "researching"
  | "ready"
  | "queued"
  | "in_progress"
  | "completed"
  | "archived";

/**
 * Main backlog categories.
 */
export type BacklogKind = "idea" | "research" | "fix" | "execute";

/**
 * Optional target kind for research items.
 */
export type BacklogResearchTarget = "idea" | "fix" | "execute" | "unspecified";

/**
 * A backlog item represents a unit of work for the swarm.
 */
export interface BacklogItem {
  /** Unique identifier (folder name) */
  name: string;
  /** Human-readable title */
  title: string;
  /** Detailed description of the item */
  description: string;
  /** Current lifecycle state */
  status: BacklogStatus;
  /** Priority level (1 = highest) */
  priority: number;
  /** Categorization tags */
  tags: string[];
  /** ISO timestamp of creation */
  created: string;
  /** ISO timestamp of last update */
  updated: string;
  /** Backlog category */
  kind: BacklogKind;
  /** Research target (research items only) */
  researchTarget?: BacklogResearchTarget;
}

/**
 * Form values for creating or editing a backlog item.
 */
export interface BacklogFormValues {
  name: string;
  title: string;
  description: string;
  status: BacklogStatus;
  priority: number;
  tags: string[];
  kind: BacklogKind;
  researchTarget?: BacklogResearchTarget;
}

/**
 * File type in the backlog file tree
 */
export type BacklogFileType = "file" | "directory";

/**
 * Represents a file or directory within a backlog folder.
 */
export interface BacklogFile {
  /** File or directory name */
  name: string;
  /** Relative path from the backlog root */
  path: string;
  /** Whether this is a file or directory */
  type: BacklogFileType;
  /** File size in bytes (only for files) */
  size?: number;
  /** Child files (only for directories) */
  children?: BacklogFile[];
}

/**
 * Supported agent workflows for idea refinement (idea backlog items).
 */
export type IdeaAgentMode = "clarify" | "suggest" | "enhance";

/**
 * A clarifying question generated by an agent.
 */
export interface IdeaClarificationQuestion {
  id: string;
  question: string;
  answer?: string;
}

/**
 * Decision states for agent suggestions.
 */
export type IdeaSuggestionDecision = "pending" | "accepted" | "rejected";

/**
 * A suggestion generated by an agent.
 */
export interface IdeaSuggestion {
  id: string;
  suggestion: string;
  details?: string;
  status?: IdeaSuggestionDecision;
}

/**
 * JSON file shape for stored clarifying questions.
 */
export interface IdeaAgentQuestionsFile {
  questions: IdeaClarificationQuestion[];
  generatedAt?: string;
  updatedAt?: string;
}

/**
 * JSON file shape for stored suggestions.
 */
export interface IdeaAgentSuggestionsFile {
  suggestions: IdeaSuggestion[];
  generatedAt?: string;
  updatedAt?: string;
}

// ============================================================================
// Scenarios Domain
// ============================================================================

/**
 * Valid runtime states for a scenario
 */
export type ScenarioStatus = "running" | "stopped" | "error" | "unknown";

/**
 * A scenario represents a deployed application in the Vrooli ecosystem.
 * [REQ:REQ-P0-007] Includes metadata for greenfield toggle and recommendations
 */
export interface Scenario {
  /** Unique identifier (folder name) */
  name: string;
  /** Human-readable name from service.json */
  displayName: string;
  /** Scenario description */
  description: string;
  /** Current runtime state */
  status: ScenarioStatus;
  /** Priority level for development focus */
  priority: number;
  /** Completeness score (0-100) if available */
  completenessScore?: number;
  /** Whether this is a new scenario without existing code */
  isGreenfield: boolean;
  /** Categorization tags */
  tags: string[];
  /** Whether recommendations engine is enabled for this scenario */
  recommendationsEnabled: boolean;
}

/**
 * Request to update scenario metadata
 * [REQ:REQ-P0-007] Update metadata for greenfield and recommendations
 */
export interface UpdateScenarioMetadataRequest {
  /** Set to toggle greenfield status */
  isGreenfield?: boolean;
  /** Set to enable/disable recommendations */
  recommendationsEnabled?: boolean;
}

/**
 * File type in the scenario file tree
 */
export type ScenarioFileType = "file" | "directory";

/**
 * Represents a file or directory within a scenario folder.
 */
export interface ScenarioFile {
  /** File or directory name */
  name: string;
  /** Relative path from the scenario root */
  path: string;
  /** Whether this is a file or directory */
  type: ScenarioFileType;
  /** File size in bytes (only for files) */
  size?: number;
  /** Child files (only for directories) */
  children?: ScenarioFile[];
}

/**
 * Available presets for file preservation during archive
 */
export type PreserveFilesPreset = "documentation" | "requirements" | "planning" | "all-planning";

/**
 * Request to specify which files to preserve when archiving
 */
export interface PreserveFilesRequest {
  /** Explicit paths to preserve (supports glob patterns like "docs/**") */
  paths?: string[];
  /** Preset name: "documentation", "requirements", "planning", "all-planning" */
  preset?: PreserveFilesPreset;
}

/**
 * Request body for DELETE /api/v1/scenarios/{name}
 */
export interface DeleteScenarioRequest {
  /** Optional file preservation settings when archiving */
  preserveFiles?: PreserveFilesRequest;
}

/**
 * Response from scenario deletion
 * [REQ:REQ-P0-008] Deletion confirmation with archive status
 */
export interface DeleteScenarioResponse {
  /** Name of the deleted scenario */
  name: string;
  /** Whether the scenario was archived to backlog (idea) */
  archived: boolean;
  /** Human-readable message describing the result */
  message: string;
  /** Name of the backlog idea created (if archived) */
  backlogIdeaName?: string;
  /** List of files that were preserved */
  preservedFiles?: string[];
}

// ============================================================================
// Recommendations Domain
// ============================================================================

/**
 * Valid states for a recommendation
 */
export type RecommendationStatus = "pending" | "approved" | "rejected";

/**
 * A recommendation is a system-generated suggestion for improvement.
 */
export interface Recommendation {
  /** Unique identifier */
  id: string;
  /** Target scenario name */
  scenarioName: string;
  /** Type of improvement */
  type: "test" | "feature" | "refactor" | "docs";
  /** Description of the recommendation */
  description: string;
  /** Current state */
  status: RecommendationStatus;
  /** Priority level (1 = highest) */
  priority: number;
  /** ISO timestamp of creation */
  created: string;
  /** Optional agent-manager task id when started */
  taskId?: string;
  /** Optional agent-manager run id when started */
  runId?: string;
  /** ISO timestamp when started */
  startedAt?: string;
  /** Source of start action */
  startedBy?: string;
  /** Whether auto-approved (YOLO) */
  autoApproved?: boolean;
}

// ============================================================================
// Agent Manager Domain
// ============================================================================

export interface AgentManagerStatus {
  enabled: boolean;
  available: boolean;
  url?: string;
  profileId?: string;
}

// ============================================================================
// Settings Domain
// ============================================================================

/**
 * Recommendation engine operating mode
 */
export type RecommendationMode = "off" | "suggestions" | "yolo";

/**
 * Recommendation data sources configuration
 */
export interface RecommendationSources {
  problems: boolean;
  completeness: boolean;
  tests: boolean;
  coverage: boolean;
  customFocus: boolean;
  scenarioNotes: boolean;
}

/**
 * Recommendation auto-sync configuration
 */
export interface RecommendationAutoSync {
  enabled: boolean;
  interval: string;
  lastRefresh?: string;
  nextRefresh?: string;
  refreshScope?: string;
}

/**
 * User preferences and configuration
 */
export interface Settings {
  /** UI theme preference */
  theme: "dark" | "light" | "system";
  /** Recommendation engine mode */
  recommendationMode: RecommendationMode;
  /** Optional custom focus for recommendations */
  customFocus?: string;
  /** Whether insights engine is enabled */
  insightsEnabled: boolean;
  /** Auto-analyze on scenario changes */
  insightsAutoAnalyze: boolean;
  /** Recommendation data sources */
  recommendationSources: RecommendationSources;
  /** Auto-sync for recommendation refresh */
  recommendationAutoSync: RecommendationAutoSync;
}

/**
 * Research agent spawn response
 */
export interface ResearchResponse {
  taskId: string;
  runId: string;
  baseUrl: string;
  created: string;
}
