import { useEffect, useState, type FormEvent } from "react";
import { getShoppingPreview, setShoppingChecked, type ShoppingLine } from "../../api/planning";
import { ensureWorkspace } from "../../api/workspace";
import { listInventoryEvents, recordInventoryEvent, type InventoryEvent } from "../../api/inventory";
import { exportGroceriesCSV } from "../../api/portability";

export function GroceriesPage() {
  const [lines, setLines] = useState<ShoppingLine[]>([]);
  const [workspaceId, setWorkspaceId] = useState("");
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [error, setError] = useState("");
  const [events, setEvents] = useState<InventoryEvent[]>([]);
  const [planRevision, setPlanRevision] = useState<bigint>(-1n);
  const [exporting, setExporting] = useState(false);
  const [itemId, setItemId] = useState("");
  const [amount, setAmount] = useState("");
  const [unit, setUnit] = useState("g");
  useEffect(() => { let mounted = true; void ensureWorkspace().then(async (workspace) => { if (mounted) setWorkspaceId(workspace.id); const [shopping, inventory] = await Promise.all([getShoppingPreview({ workspaceId: workspace.id, expectedRevision: -1n }), listInventoryEvents(workspace.id).catch(() => [])]); if (mounted) { setLines(shopping.lines); setPlanRevision(shopping.revision); setEvents(inventory); setState("ready"); } }).catch((err: unknown) => { if (mounted) { setError(err instanceof Error ? err.message : "Unable to load the shopping preview."); setState("error"); } }); return () => { mounted = false; }; }, []);
  async function toggle(line: ShoppingLine) { const checked = await setShoppingChecked({ workspaceId, lineKey: line.key, checked: !line.checked }).catch(() => line.checked); setLines((current) => current.map((item) => item.key === line.key ? { ...item, checked } : item)); }
  async function recordPurchase(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!itemId || !amount) return; const created = await recordInventoryEvent({ workspaceId, id: `purchase-${Date.now()}`, kind: "purchase", itemId, amount, unit }); setEvents((current) => [created, ...current]); setItemId(""); setAmount(""); }
  async function downloadCSV() { setExporting(true); try { const result = await exportGroceriesCSV({ workspaceId, expectedRevision: planRevision }); const blob = new Blob([result.content], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.filename; anchor.click(); URL.revokeObjectURL(url); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to export groceries."); } finally { setExporting(false); } }
  return <section aria-labelledby="groceries-heading" className="flex flex-col gap-6"><header><p className="text-sm font-medium uppercase tracking-wide text-cyan-700">Plan / Groceries</p><h1 id="groceries-heading" className="text-3xl font-semibold text-slate-900">Shopping preview</h1><p className="mt-2 text-slate-600">Derived from the selected plan. Unknown quantities, package counts, and prices stay unknown until entered.</p></header>{state === "loading" && <p role="status" className="rounded border bg-white p-5 text-slate-600">Loading shopping preview…</p>}{state === "error" && <p role="alert" className="rounded border border-red-200 bg-red-50 p-5 text-red-800">{error}</p>}{state === "ready" && <button type="button" onClick={() => void downloadCSV()} disabled={exporting}>{exporting ? "Exporting…" : "Download grocery CSV"}</button>}{state === "ready" && lines.length === 0 && <div className="rounded border border-dashed bg-white p-6"><h2 className="font-semibold">No ingredient evidence yet</h2><p className="mt-2 text-slate-600">Add ingredient inputs to a planned recipe to derive shopping lines.</p></div>}{state === "ready" && lines.length > 0 && <ul aria-label="Shopping lines" className="divide-y rounded-lg border bg-white">{lines.map((line) => <li key={line.key} className="flex flex-wrap items-start gap-3 p-4"><input type="checkbox" aria-label={`Check ${line.label}`} checked={line.checked} onChange={() => void toggle(line)} /><div className="min-w-0 flex-1"><p className={line.checked ? "text-slate-500 line-through" : "font-medium text-slate-900"}>{line.label}</p><p className="mt-1 text-sm text-slate-600">Need: {line.need} · Stock: {line.stock} · Missing: {line.missing} · Packages: {line.packageCount} · Price: {line.price}</p><p className="mt-1 text-xs text-slate-500">Checklist state only; this does not change inventory, spend, or consumption.</p></div></li>)}</ul>}{state === "ready" && <div className="rounded-lg border bg-white p-5"><h2 className="font-semibold">Record purchased stock</h2><p className="mt-1 text-sm text-slate-600">This records an inventory event; checking a line alone never changes stock.</p><form onSubmit={(event) => void recordPurchase(event)} className="mt-4 flex flex-wrap gap-3"><label>Item <input aria-label="Inventory item" value={itemId} onChange={(event) => setItemId(event.target.value)} /></label><label>Amount <input aria-label="Inventory amount" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Unit <input aria-label="Inventory unit" value={unit} onChange={(event) => setUnit(event.target.value)} /></label><button type="submit" disabled={!itemId || !amount}>Record purchase</button></form><p className="mt-3 text-sm text-slate-600">Recorded events: {events.length}</p></div>}</section>;
}
