// ============================================================================
// API barrel file — re-exports all types and functions from split modules
// for backward compatibility.
// ============================================================================

// Internals (not re-exported — consumers use domain modules)
// But we re-export buildApiUrl since some consumers may use it

// Core repo & branch types
export type {
  HealthResponse,
  RepoRecord,
  RepoListResponse,
  RepoActiveResponse,
  RepoOpenRequest,
  RepoCloneRequest,
  RepoActiveRequest,
  RepoMutationResponse,
  RepoRemoveResponse,
  RepoBranchStatus,
  RepoFilesStatus,
  RepoFileStats,
  RepoStatusSummary,
  BranchInfo,
  RepoBranchesResponse,
  BranchWarning,
  CreateBranchRequest,
  BranchCreateResponse,
  SwitchBranchRequest,
  BranchSwitchResponse,
  PublishBranchRequest,
  BranchPublishResponse,
  RepoStatus,
  RepoHistoryResponse,
  RepoHistoryEntry,
  CommitCheckRun,
  CommitCheckKind,
  CommitCheckStatus,
  DiffHunk,
  DiffStats,
} from "./api-types-repo";

// Operation types (diff, stage, commit, file, search)
export type {
  ViewMode,
  FileViewMode,
  LineChange,
  AnnotatedLine,
  DiffResponse,
  StageRequest,
  StageResponse,
  UnstageRequest,
  UnstageResponse,
  CommitRequest,
  CommitResponse,
  PrecommitConfig,
  PrecommitRunRequest,
  PrecommitRunResponse,
  PrecommitRunResult,
  DiscardRequest,
  DiscardResponse,
  IgnoreRequest,
  IgnoreResponse,
  GroupingRulesConfig,
  GroupingRuleAPI,
  GitignoreHealthResponse,
  GitignoreSuggestion,
  GitignoreMoveRequest,
  GitignoreMoveResponse,
  PushRequest,
  PushResponse,
  PullRequest,
  PullResponse,
  UpstreamActionType,
  UpstreamActionRequest,
  UpstreamActionResponse,
  SyncStatusResponse,
  ApprovedChangeFile,
  ApprovedChangesResponse,
  ApprovedChangesPreviewRequest,
  ProvenanceFile,
  ProvenanceRunGroup,
  ProvenanceResponse,
  FileStatus,
  FileInfo,
  FileTreeResponse,
  DirEntry,
  DirListResponse,
  RelationType,
  RelatedFile,
  RelatedFilesResponse,
  ContentSearchRequest,
  ContentSearchMatch,
  ContentSearchResponse,
  DeletePathRequest,
  DeletePathResponse,
  SaveFileContentRequest,
  SaveFileContentResponse,
  SaveFileContentConflictResponse,
} from "./api-types-operations";
export { FileContentConflictError } from "./api-types-operations";

// Core API functions
export {
  fetchHealth,
  fetchRepoStatus,
  fetchRepoHistory,
  fetchDiff,
  stageFiles,
  unstageFiles,
  createCommit,
  fetchPrecommitConfig,
  savePrecommitConfig,
  runPrecommit,
  discardFiles,
  ignoreFile,
  pushToRemote,
  pullFromRemote,
  runUpstreamAction,
  fetchSyncStatus,
  fetchApprovedChanges,
  fetchApprovedChangesPreview,
  fetchProvenance,
  fetchBranches,
  createBranch,
  switchBranch,
  publishBranch,
  fetchFiles,
  fetchRelatedFiles,
  searchContent,
  fetchDirectoryContents,
  deletePath,
  saveFileContent,
} from "./api-core";

// Settings: capabilities, credentials, SSH, repos, grouping, gitignore
export type {
  DependencyKind,
  CapabilityStatus,
  CapabilityState,
  CapabilitiesResponse,
  CredentialType,
  Credential,
  CredentialsListResponse,
  CredentialSaveRequest,
  CredentialSaveResponse,
  CredentialDeleteResponse,
  CredentialTestRequest,
  CredentialTestResponse,
  RemoteURLUpdateRequest,
  RemoteURLUpdateResponse,
  SSHKeyType,
  SSHKeyInfo,
  SSHListKeysResponse,
  SSHGenerateKeyRequest,
  SSHGenerateKeyResponse,
  SSHGetPublicKeyRequest,
  SSHGetPublicKeyResponse,
  SSHTestConnectionRequest,
  SSHTestConnectionResponse,
  SSHDeleteKeyRequest,
  SSHDeleteKeyResponse,
} from "./api-settings";
export {
  fetchCapabilities,
  fetchGroupingRules,
  saveGroupingRules,
  fetchGitignoreHealth,
  moveGitignoreEntry,
  fetchCredentials,
  saveCredential,
  deleteCredential,
  testCredential,
  updateRemoteURL,
  fetchRepos,
  fetchActiveRepo,
  openRepo,
  cloneRepo,
  setActiveRepo,
  removeRepo,
  fetchSSHKeys,
  generateSSHKey,
  getSSHPublicKey,
  testSSHConnection,
  deleteSSHKey,
} from "./api-settings";

// Visual & workflow captures
export type {
  CaptureTrigger,
  CaptureStatus,
  SnapshotRole,
  CaptureMode,
  CaptureTheme,
  CapturePreset,
  SnapshotStalenessInfo,
  SnapshotFile,
  SnapshotSetMeta,
  SnapshotSetDetail,
  VisualCaptureListResponse,
  CaptureStorageStats,
  ExecutionMode,
  WorkflowExecutionResult,
  WorkflowCaptureResult,
  WorkflowCaptureListResponse,
  WorkflowCaptureDetailResponse,
} from "./api-visual";
export {
  SIZE_PRESETS,
  DEFAULT_PRESETS,
  presetSuffix,
  presetLabel,
  presetKey,
  getCapturePresets,
  setCapturePresets,
  triggerVisualCapture,
  fetchVisualCaptures,
  fetchVisualCaptureDetail,
  fetchCaptureStorageStats,
  deleteVisualCapture,
  clearAllCaptureStorage,
  buildCaptureScreenshotUrl,
  fetchScreenshotPath,
  buildCaptureVideoUrl,
  triggerWorkflowCapture,
  fetchWorkflowCaptures,
  fetchWorkflowCaptureDetail,
  buildWorkflowVideoUrl,
} from "./api-visual";

// Test execution & tidiness
export type {
  TestExecutionRequest,
  TestExecutionResult,
  TestPhaseResult,
  TestPhaseSummary,
  TestObservation,
  TestExecutionListResponse,
  TidinessBreakdown,
  TidinessMetricsSummary,
  TidinessScoreResponse,
  TidinessIssue,
  TidinessStalenessInfo,
  TidinessLightScanRequest,
  TidinessFileMetric,
  TidinessLongFile,
  TidinessLightScanResult,
  TidinessScenarioFileInfo,
  TidinessScenarioDetail,
} from "./api-testing";
export {
  triggerTestExecution,
  fetchTestExecutions,
  fetchTestExecution,
  fetchTidinessScore,
  fetchTidinessIssues,
  fetchTidinessStaleness,
  triggerTidinessLightScan,
  fetchTidinessScenarioDetail,
} from "./api-testing";

// Auditor
export type {
  AuditorViolation,
  AuditorCheckResult,
  AuditorViolationSummary,
  AuditorJobStatus,
  AuditorCheckJobResponse,
  AuditorRule,
  AuditorRulesListResponse,
  AuditorFixRequest,
  AuditorFixChange,
  AuditorFixResult,
  AuditorFixResponse,
} from "./api-auditor";
export {
  startAuditorCheck,
  pollAuditorJob,
  fetchAuditorRules,
  applyAuditorFix,
  fetchAuditorViolations,
} from "./api-auditor";

// Agent manager
export type {
  AgentRunStatus,
  AgentProfile,
  AgentProfileListResponse,
  AgentRunRequest,
  AgentRunCreateResponse,
  AgentRunSummary,
  AgentRunActions,
  AgentRun,
  AgentRunListResponse,
  AgentEventType,
  AgentRunEvent,
  AgentRunEventsResponse,
  AgentRunDiffFile,
  AgentRunDiffResponse,
  AgentContinueRequest,
  AttachmentUploadResponse,
  AgentContinueResponse,
  AgentApproveRequest,
  AgentApproveResponse,
  AgentRejectRequest,
  AgentRejectResponse,
  AgentStopResponse,
  AgentContextKind,
  AgentContextItem,
} from "./api-agent";
export {
  RUN_STATUS,
  ACTIVE_STATUSES,
  TERMINAL_STATUSES,
  uploadAgentAttachment,
  fetchAgentProfiles,
  createAgentRun,
  fetchAgentRuns,
  fetchAgentRun,
  fetchAgentRunEvents,
  fetchAgentRunDiff,
  continueAgentRun,
  approveAgentRun,
  rejectAgentRun,
  stopAgentRun,
} from "./api-agent";

// Scenarios & review
export type {
  ScenarioInfo,
  ScenarioEnvelopeData,
  Readiness,
  ReviewCheckStatus,
  CodeQualityDimension,
  TestsDimension,
  StandardsDimension,
  VisualDimension,
  ProvenanceDimension,
  ReviewDimensions,
  ReviewSummaryResponse,
  ReviewJobStatus,
} from "./api-scenarios";
export {
  fetchScenarios,
  fetchScenarioEnvelope,
  fetchReviewSummary,
  triggerReviewRun,
  fetchReviewJobStatus,
} from "./api-scenarios";
