// ============================================================================
// Hooks barrel file — re-exports all hooks from split modules
// for backward compatibility.
// ============================================================================

export { queryKeys, useRepoSelection } from "./hooks-query-keys";

export {
  useHealth,
  useRepoStatus,
  useRepoHistory,
  useDiff,
  useDiffStats,
  useStageFiles,
  useUnstageFiles,
  useSyncStatus,
  useCommit,
  usePrecommitConfig,
  useSavePrecommitConfig,
  useRunPrecommit,
  useStreamPrecommit,
  useDiscardFiles,
  useIgnoreFile,
  usePush,
  useSaveFileContent,
  usePull,
  useApprovedChanges,
  useApprovedChangesPreview,
  useProvenance,
  useBranches,
  useCreateBranch,
  useSwitchBranch,
  usePublishBranch,
  useFileSearch,
  useRelatedFiles,
  useDirectoryContents,
  useDeletePath,
  useContentSearch,
} from "./hooks-core";

export {
  useCapabilities,
  useCredentials,
  useSaveCredential,
  useDeleteCredential,
  useTestCredential,
  useUpdateRemoteURL,
  useRepos,
  useActiveRepo,
  useOpenRepo,
  useCloneRepo,
  useSetActiveRepo,
  useRemoveRepo,
  useSSHKeys,
  useGenerateSSHKey,
  useGetSSHPublicKey,
  useTestSSHConnection,
  useDeleteSSHKey,
  useGroupingRules,
  useSaveGroupingRules,
  useGitignoreHealth,
  useGitignoreMove,
} from "./hooks-settings";

export {
  useVisualCaptures,
  useVisualCaptureDetail,
  useTriggerVisualCapture,
  useCaptureStorageStats,
  useDeleteVisualCapture,
  useClearAllCaptureStorage,
  useTestExecutions,
  useTestExecution,
  useTriggerTestExecution,
  useTidinessScore,
  useTidinessIssues,
  useTidinessStaleness,
  useTriggerTidinessScan,
  useTidinessScenarioDetail,
} from "./hooks-visual";
export type { TidinessIssuesOptions } from "./hooks-visual";

export {
  useScenarios,
  useScenarioEnvelope,
  useAgentProfiles,
  useAgentRuns,
  useAgentRun,
  useAgentRunEvents,
  useAgentRunDiff,
  useCreateAgentRun,
  useContinueAgentRun,
  useApproveAgentRun,
  useRejectAgentRun,
  useStopAgentRun,
  useAuditorRules,
  useStartAuditorCheck,
  useAuditorJobStatus,
  useApplyAuditorFix,
  useAuditorViolations,
  useReviewSummary,
  useTriggerReviewRun,
  useReviewJobStatus,
} from "./hooks-agent";
