// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    nav: {
      overview: "layout.nav.overview",
      targets: "layout.nav.targets",
      destinations: "layout.nav.destinations",
      plans: "layout.nav.plans",
      runs: "layout.nav.runs",
      restores: "layout.nav.restores",
      settings: "layout.nav.settings",
    },
    mainLabel: "layout.mainLabel",
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  common: {
    retry: "common.retry",
    loadError: "common.loadError",
    cancel: "common.cancel",
    close: "common.close",
    save: "common.save",
    saving: "common.saving",
    create: "common.create",
    never: "common.never",
  },
  status: {
    run: {
      unknown: "status.run.unknown",
      pending: "status.run.pending",
      capturing: "status.run.capturing",
      snapshotting: "status.run.snapshotting",
      completed: "status.run.completed",
      partialFailed: "status.run.partialFailed",
      failed: "status.run.failed",
    },
    outcome: {
      unknown: "status.outcome.unknown",
      succeeded: "status.outcome.succeeded",
      failed: "status.outcome.failed",
      blocked: "status.outcome.blocked",
    },
    restore: {
      unknown: "status.restore.unknown",
      requested: "status.restore.requested",
      restoring: "status.restore.restoring",
      verifying: "status.restore.verifying",
      verified: "status.restore.verified",
      restored: "status.restore.restored",
      failed: "status.restore.failed",
    },
    usage: {
      unknown: "status.usage.unknown",
      within: "status.usage.within",
      near: "status.usage.near",
      over: "status.usage.over",
    },
    capPolicy: {
      unknown: "status.capPolicy.unknown",
      alertBlock: "status.capPolicy.alertBlock",
      alertOnly: "status.capPolicy.alertOnly",
    },
    backend: {
      unknown: "status.backend.unknown",
      filesystem: "status.backend.filesystem",
      s3: "status.backend.s3",
    },
    sourceKind: {
      unknown: "status.sourceKind.unknown",
      filesystem: "status.sourceKind.filesystem",
      sqlite: "status.sourceKind.sqlite",
      postgres: "status.sourceKind.postgres",
      redis: "status.sourceKind.redis",
      qdrant: "status.sourceKind.qdrant",
      objectStorage: "status.sourceKind.objectStorage",
    },
    verified: {
      verified: "status.verified.verified",
      stale: "status.verified.stale",
      unverified: "status.verified.unverified",
    },
    trigger: {
      unknown: "status.trigger.unknown",
      scheduler: "status.trigger.scheduler",
      manual: "status.trigger.manual",
    },
    driveClass: {
      unknown: "status.driveClass.unknown",
      removable: "status.driveClass.removable",
      fixed: "status.driveClass.fixed",
      network: "status.driveClass.network",
    },
  },
  posture: {
    title: "posture.title",
    loading: "posture.loading",
    error: "posture.error",
    allClear: "posture.allClear",
    attention: "posture.attention",
    attention_one: "posture.attention_one",
    overdue: "posture.overdue",
    unverified: "posture.unverified",
    readinessLabel: "posture.readinessLabel",
    serviceLabel: "posture.serviceLabel",
  },
  overview: {
    title: "overview.title",
    subtitle: "overview.subtitle",
    storageHeading: "overview.storageHeading",
    storageEmpty: "overview.storageEmpty",
    coverageHeading: "overview.coverageHeading",
    coverageEmpty: "overview.coverageEmpty",
    lastBackupLabel: "overview.lastBackupLabel",
    verifiedLabel: "overview.verifiedLabel",
    ownerFallback: "overview.ownerFallback",
    setupTitle: "overview.setupTitle",
    setupBody: "overview.setupBody",
    setupCtaDestinations: "overview.setupCtaDestinations",
    setupCtaPlans: "overview.setupCtaPlans",
    usageOfCap: "overview.usageOfCap",
    usageUncapped: "overview.usageUncapped",
  },
  discovery: {
    title: "discovery.title",
    subtitle: "discovery.subtitle",
    onboardingTitle: "discovery.onboardingTitle",
    onboardingBody: "discovery.onboardingBody",
    targetsHeading: "discovery.targetsHeading",
    destinationsHeading: "discovery.destinationsHeading",
    targetsEmpty: "discovery.targetsEmpty",
    destinationsEmpty: "discovery.destinationsEmpty",
    enable: "discovery.enable",
    enabling: "discovery.enabling",
    review: "discovery.review",
    reviewTitle: "discovery.reviewTitle",
    createReviewed: "discovery.createReviewed",
    analyzingDestination: "discovery.analyzingDestination",
    readinessUnavailable: "discovery.readinessUnavailable",
    recommendedLocation: "discovery.recommendedLocation",
    readinessChecks: "discovery.readinessChecks",
    readinessPass: "discovery.readinessPass",
    readinessWarning: "discovery.readinessWarning",
    readinessFail: "discovery.readinessFail",
    readinessUnknown: "discovery.readinessUnknown",
    dismiss: "discovery.dismiss",
    unsafe: "discovery.unsafe",
    sensitive: "discovery.sensitive",
    approxSize: "discovery.approxSize",
    freeOfTotal: "discovery.freeOfTotal",
  },
  coverage: {
    title: "coverage.title",
    incompleteTitle: "coverage.incompleteTitle",
    incompleteBody: "coverage.incompleteBody",
    complete: "coverage.complete",
    registerRecommended: "coverage.registerRecommended",
    registering: "coverage.registering",
    sensitiveTitle: "coverage.sensitiveTitle",
    sensitiveBody: "coverage.sensitiveBody",
    registerSensitive: "coverage.registerSensitive",
    summary: "coverage.summary",
    incompleteRejected: "coverage.incompleteRejected",
    proceedIncomplete: "coverage.proceedIncomplete",
  },
  targets: {
    subtitle: "targets.subtitle",
    register: "targets.register",
    empty: "targets.empty",
    emptyHint: "targets.emptyHint",
    owner: "targets.owner",
    ownerHint: "targets.ownerHint",
    name: "targets.name",
    nameHint: "targets.nameHint",
    kind: "targets.kind",
    locator: "targets.locator",
    locatorHint: "targets.locatorHint",
    ownerRequired: "targets.ownerRequired",
    nameRequired: "targets.nameRequired",
    locatorRequired: "targets.locatorRequired",
    deregister: "targets.deregister",
    deregisterTitle: "targets.deregisterTitle",
    deregisterBody: "targets.deregisterBody",
    registerError: "targets.registerError",
    detailsTitle: "targets.detailsTitle",
    restoreHistory: "targets.restoreHistory",
    noRestores: "targets.noRestores",
  },
  destinations: {
    subtitle: "destinations.subtitle",
    create: "destinations.create",
    empty: "destinations.empty",
    emptyHint: "destinations.emptyHint",
    name: "destinations.name",
    nameHint: "destinations.nameHint",
    backend: "destinations.backend",
    location: "destinations.location",
    locationHint: "destinations.locationHint",
    cap: "destinations.cap",
    capHint: "destinations.capHint",
    policy: "destinations.policy",
    encryption: "destinations.encryption",
    secretRef: "destinations.secretRef",
    nameRequired: "destinations.nameRequired",
    locationRequired: "destinations.locationRequired",
    createTitle: "destinations.createTitle",
    editTitle: "destinations.editTitle",
    editLockedHint: "destinations.editLockedHint",
    delete: "destinations.delete",
    deleteTitle: "destinations.deleteTitle",
    deleteBody: "destinations.deleteBody",
    deleteRepo: "destinations.deleteRepo",
    deleteRepoHint: "destinations.deleteRepoHint",
    createError: "destinations.createError",
    updateError: "destinations.updateError",
    nameInvalid: "destinations.nameInvalid",
    repositoryPath: "destinations.repositoryPath",
    repositoryPathPreview: "destinations.repositoryPathPreview",
  },
  plans: {
    subtitle: "plans.subtitle",
    create: "plans.create",
    empty: "plans.empty",
    emptyHint: "plans.emptyHint",
    name: "plans.name",
    schedule: "plans.schedule",
    scheduleHint: "plans.scheduleHint",
    keepLatest: "plans.keepLatest",
    keepLatestHint: "plans.keepLatestHint",
    enabled: "plans.enabled",
    targets: "plans.targets",
    destinations: "plans.destinations",
    nameRequired: "plans.nameRequired",
    needTarget: "plans.needTarget",
    needDestination: "plans.needDestination",
    noTargets: "plans.noTargets",
    noDestinations: "plans.noDestinations",
    summary: "plans.summary",
    runNow: "plans.runNow",
    noRuns: "plans.noRuns",
    delete: "plans.delete",
    deleteTitle: "plans.deleteTitle",
    deleteBody: "plans.deleteBody",
    createTitle: "plans.createTitle",
    editTitle: "plans.editTitle",
    createError: "plans.createError",
    updateError: "plans.updateError",
  },
  runs: {
    subtitle: "runs.subtitle",
    empty: "runs.empty",
    emptyHint: "runs.emptyHint",
    outcomesHeading: "runs.outcomesHeading",
  },
  restores: {
    subtitle: "restores.subtitle",
    empty: "restores.empty",
    emptyHint: "restores.emptyHint",
    start: "restores.start",
    modeRestore: "restores.modeRestore",
    modeVerify: "restores.modeVerify",
    chooseSnapshot: "restores.chooseSnapshot",
    chooseSnapshotHint: "restores.chooseSnapshotHint",
    noSnapshots: "restores.noSnapshots",
    browse: "restores.browse",
    verify: "restores.verify",
    verifyHint: "restores.verifyHint",
    restore: "restores.restore",
    location: "restores.location",
    locationHint: "restores.locationHint",
    locationRequired: "restores.locationRequired",
    restoreConfirmBody: "restores.restoreConfirmBody",
    verifyError: "restores.verifyError",
    restoreError: "restores.restoreError",
  },
  snapshot: {
    empty: "snapshot.empty",
    up: "snapshot.up",
  },
  pages: {
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
