import type { LucideIcon } from 'lucide-react';
import {
  Globe,
  MousePointer,
  MousePointer2,
  Hand,
  Crosshair,
  EyeOff,
  PanelsTopLeft,
  LayoutPanelTop,
  ScrollText,
  Smartphone,
  Touchpad,
  ListFilter,
  UploadCloud,
  Keyboard,
  Command,
  KeySquare,
  Database,
  Variable,
  Recycle,
  TerminalSquare,
  CheckCircle,
  Clock,
  Camera,
  GitBranch,
  RefreshCcw,
  Play,
  Cookie,
  HardDriveUpload,
  HardDriveDownload,
  Trash2,
  Network,
  Compass,
  Pointer,
  ShieldCheck,
  Server,
} from 'lucide-react';

export interface WorkflowNodeDefinition {
  type: string;
  label: string;
  description: string;
  icon: LucideIcon;
  color: string;
  keywords?: string[];
}

export interface NodeCategory {
  id: string;
  label: string;
  icon: LucideIcon;
  description: string;
  defaultExpanded: boolean;
  nodes: string[];
}

export const WORKFLOW_NODE_DEFINITIONS: Record<string, WorkflowNodeDefinition> = {
  navigate: {
    type: 'navigate',
    label: 'Navigate',
    description: 'Navigate to URL or scenario',
    icon: Globe,
    color: 'text-blue-400',
    keywords: ['url', 'scenario', 'open page', 'load'],
  },
  click: {
    type: 'click',
    label: 'Click',
    description: 'Click an element',
    icon: MousePointer,
    color: 'text-green-400',
    keywords: ['button', 'tap', 'interaction'],
  },
  hover: {
    type: 'hover',
    label: 'Hover',
    description: 'Move cursor without clicking',
    icon: MousePointer2,
    color: 'text-cyan-300',
    keywords: ['tooltip', 'dropdown', 'pointer'],
  },
  dragDrop: {
    type: 'dragDrop',
    label: 'Drag & Drop',
    description: 'Reorder cards or move files',
    icon: Hand,
    color: 'text-pink-300',
    keywords: ['kanban', 'drag', 'drop', 'reorder'],
  },
  focus: {
    type: 'focus',
    label: 'Focus',
    description: 'Focus fields before typing',
    icon: Crosshair,
    color: 'text-emerald-300',
    keywords: ['input', 'field', 'form'],
  },
  blur: {
    type: 'blur',
    label: 'Blur',
    description: 'Trigger blur/onChange handlers',
    icon: EyeOff,
    color: 'text-amber-300',
    keywords: ['validation', 'form'],
  },
  tabSwitch: {
    type: 'tabSwitch',
    label: 'Tab Switch',
    description: 'Switch between tabs or popups',
    icon: PanelsTopLeft,
    color: 'text-violet-300',
    keywords: ['window', 'popup', 'oauth'],
  },
  frameSwitch: {
    type: 'frameSwitch',
    label: 'Frame Switch',
    description: 'Enter/exit iframe contexts',
    icon: LayoutPanelTop,
    color: 'text-lime-300',
    keywords: ['iframe', 'frame', 'embedded'],
  },
  scroll: {
    type: 'scroll',
    label: 'Scroll',
    description: 'Scroll page, elements, or until visible',
    icon: ScrollText,
    color: 'text-amber-300',
    keywords: ['scroll', 'lazy load', 'viewport'],
  },
  rotate: {
    type: 'rotate',
    label: 'Rotate',
    description: 'Flip viewport orientation mid-run',
    icon: Smartphone,
    color: 'text-sky-300',
    keywords: ['mobile', 'landscape', 'portrait'],
  },
  gesture: {
    type: 'gesture',
    label: 'Gesture',
    description: 'Swipe, pinch, tap, or long-press',
    icon: Touchpad,
    color: 'text-rose-300',
    keywords: ['mobile', 'touch', 'pinch'],
  },
  select: {
    type: 'select',
    label: 'Select',
    description: 'Choose option(s) in dropdowns',
    icon: ListFilter,
    color: 'text-teal-300',
    keywords: ['dropdown', 'option', 'form'],
  },
  uploadFile: {
    type: 'uploadFile',
    label: 'Upload File',
    description: 'Attach files to inputs',
    icon: UploadCloud,
    color: 'text-pink-300',
    keywords: ['file', 'attachment'],
  },
  type: {
    type: 'type',
    label: 'Type',
    description: 'Type text in input',
    icon: Keyboard,
    color: 'text-yellow-400',
    keywords: ['text', 'input', 'form'],
  },
  shortcut: {
    type: 'shortcut',
    label: 'Shortcut',
    description: 'Trigger keyboard shortcut(s)',
    icon: Command,
    color: 'text-indigo-400',
    keywords: ['keyboard', 'accelerator'],
  },
  keyboard: {
    type: 'keyboard',
    label: 'Keyboard',
    description: 'Dispatch keydown/keyup events',
    icon: KeySquare,
    color: 'text-lime-300',
    keywords: ['keypress', 'keydown', 'keyup'],
  },
  setVariable: {
    type: 'setVariable',
    label: 'Set Variable',
    description: 'Store values for reuse',
    icon: Variable,
    color: 'text-emerald-300',
    keywords: ['variable', 'state', 'store'],
  },
  useVariable: {
    type: 'useVariable',
    label: 'Use Variable',
    description: 'Transform or require variables',
    icon: Recycle,
    color: 'text-sky-300',
    keywords: ['variable', 'interpolate', 'assert'],
  },
  evaluate: {
    type: 'evaluate',
    label: 'Script',
    description: 'Run custom JavaScript',
    icon: TerminalSquare,
    color: 'text-teal-400',
    keywords: ['script', 'js', 'evaluate'],
  },
  screenshot: {
    type: 'screenshot',
    label: 'Screenshot',
    description: 'Capture screenshot',
    icon: Camera,
    color: 'text-purple-400',
    keywords: ['capture', 'image', 'report'],
  },
  wait: {
    type: 'wait',
    label: 'Wait',
    description: 'Wait for condition',
    icon: Clock,
    color: 'text-gray-400',
    keywords: ['delay', 'pause', 'condition'],
  },
  extract: {
    type: 'extract',
    label: 'Extract',
    description: 'Extract data',
    icon: Database,
    color: 'text-pink-400',
    keywords: ['data', 'text', 'attribute'],
  },
  assert: {
    type: 'assert',
    label: 'Assert',
    description: 'Verify page conditions',
    icon: CheckCircle,
    color: 'text-orange-400',
    keywords: ['validate', 'expect', 'test'],
  },
  conditional: {
    type: 'conditional',
    label: 'Conditional',
    description: 'Branch workflow on true/false',
    icon: GitBranch,
    color: 'text-rose-300',
    keywords: ['if', 'condition', 'branch'],
  },
  loop: {
    type: 'loop',
    label: 'Loop',
    description: 'Repeat a body with datasets or conditions',
    icon: RefreshCcw,
    color: 'text-blue-300',
    keywords: ['repeat', 'for each', 'iteration'],
  },
  workflowCall: {
    type: 'workflowCall',
    label: 'Call Workflow',
    description: 'Execute another workflow',
    icon: Play,
    color: 'text-violet-400',
    keywords: ['subflow', 'reusable', 'replay'],
  },
  setCookie: {
    type: 'setCookie',
    label: 'Set Cookie',
    description: 'Create or update browser cookies',
    icon: Cookie,
    color: 'text-amber-300',
    keywords: ['cookie', 'session', 'auth'],
  },
  getCookie: {
    type: 'getCookie',
    label: 'Get Cookie',
    description: 'Read cookies into variables',
    icon: Cookie,
    color: 'text-lime-300',
    keywords: ['cookie', 'read', 'state'],
  },
  clearCookie: {
    type: 'clearCookie',
    label: 'Clear Cookie',
    description: 'Delete individual cookies or flush all',
    icon: Cookie,
    color: 'text-rose-300',
    keywords: ['cookie', 'delete'],
  },
  setStorage: {
    type: 'setStorage',
    label: 'Set Storage',
    description: 'Write to local/session storage',
    icon: HardDriveUpload,
    color: 'text-purple-300',
    keywords: ['storage', 'localStorage', 'sessionStorage'],
  },
  getStorage: {
    type: 'getStorage',
    label: 'Get Storage',
    description: 'Read local/session storage values',
    icon: HardDriveDownload,
    color: 'text-sky-300',
    keywords: ['storage', 'read'],
  },
  clearStorage: {
    type: 'clearStorage',
    label: 'Clear Storage',
    description: 'Remove keys or wipe storage',
    icon: Trash2,
    color: 'text-red-300',
    keywords: ['storage', 'delete', 'reset'],
  },
  networkMock: {
    type: 'networkMock',
    label: 'Network Mock',
    description: 'Intercept, stub, or delay HTTP calls',
    icon: Network,
    color: 'text-fuchsia-300',
    keywords: ['api', 'mock', 'intercept'],
  },
};

export const NODE_CATEGORIES: NodeCategory[] = [
  {
    id: 'navigation',
    label: 'Navigation & Context',
    icon: Compass,
    description: 'Open pages, switch contexts, and control viewports',
    defaultExpanded: true,
    nodes: ['navigate', 'scroll', 'tabSwitch', 'frameSwitch', 'rotate', 'gesture'],
  },
  {
    id: 'pointer',
    label: 'Pointer & Gestures',
    icon: Pointer,
    description: 'Click, hover, drag, and manage pointer focus states',
    defaultExpanded: true,
    nodes: ['click', 'hover', 'dragDrop', 'focus', 'blur'],
  },
  {
    id: 'forms',
    label: 'Forms & Input',
    icon: Keyboard,
    description: 'Type, select, upload, and trigger keyboard events',
    defaultExpanded: false,
    nodes: ['type', 'select', 'uploadFile', 'shortcut', 'keyboard'],
  },
  {
    id: 'data',
    label: 'Data & Variables',
    icon: Database,
    description: 'Extract, transform, and reuse values across steps',
    defaultExpanded: false,
    nodes: ['extract', 'setVariable', 'useVariable', 'evaluate'],
  },
  {
    id: 'validation',
    label: 'Assertions & Observability',
    icon: ShieldCheck,
    description: 'Validate outcomes and capture artifacts',
    defaultExpanded: false,
    nodes: ['assert', 'wait', 'screenshot'],
  },
  {
    id: 'workflow',
    label: 'Workflow Logic',
    icon: GitBranch,
    description: 'Branch, loop, and reuse existing workflows',
    defaultExpanded: false,
    nodes: ['conditional', 'loop', 'workflowCall'],
  },
  {
    id: 'storage-network',
    label: 'Storage & Network',
    icon: Server,
    description: 'Manage cookies, storage, and network interception',
    defaultExpanded: false,
    nodes: ['setCookie', 'getCookie', 'clearCookie', 'setStorage', 'getStorage', 'clearStorage', 'networkMock'],
  },
];

export const ALL_NODE_TYPES = Object.keys(WORKFLOW_NODE_DEFINITIONS);
