run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofumpt
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-dirs:
    - mocks
    - testutil
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - gocyclo
    - path: mocks/
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
