package heartbeat

import (
	"context"
	"sync"
	"testing"
	"time"

	"prompt-manager/internal/store"
)

type stubConfigStore struct {
	config *store.HeartbeatConfig
	err    error
}

func (s *stubConfigStore) GetHeartbeatConfig(ctx context.Context, teamID, agentID string) (*store.HeartbeatConfig, error) {
	return s.config, s.err
}

type captureExecutor struct {
	calls []executionCall
}

type executionCall struct {
	teamID     string
	agentID    string
	profileKey string
}

func (c *captureExecutor) Execute(ctx context.Context, teamID, agentID, profileKey string) (*ExecutionResult, error) {
	c.calls = append(c.calls, executionCall{
		teamID:     teamID,
		agentID:    agentID,
		profileKey: profileKey,
	})
	return &ExecutionResult{
		TeamID:  teamID,
		AgentID: agentID,
		Status:  store.HeartbeatStatusRunning,
	}, nil
}

func TestSchedulerUsesConfigProfileKey(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:     "team-1",
			AgentID:    "agent-1",
			Enabled:    true,
			Schedule:   "0 * * * *",
			ProfileKey: "custom-profile",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 1 {
		t.Fatalf("expected executor to be called once, got %d", len(exec.calls))
	}
	if exec.calls[0].profileKey != "custom-profile" {
		t.Fatalf("expected profileKey to be custom-profile, got %s", exec.calls[0].profileKey)
	}
}

func TestSchedulerUsesDefaultProfileWhenEmpty(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  true,
			Schedule: "0 * * * *",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 1 {
		t.Fatalf("expected executor to be called once, got %d", len(exec.calls))
	}
	// When config.ProfileKey is empty, the scheduler passes an empty string
	// so that Execute() can resolve the default based on the team's runtime mode.
	if exec.calls[0].profileKey != "" {
		t.Fatalf("expected empty profileKey (for Execute to resolve), got %q", exec.calls[0].profileKey)
	}
}

func TestSchedulerSkipsWhenConfigMissing(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{config: nil}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 0 {
		t.Fatalf("expected executor not to be called, got %d calls", len(exec.calls))
	}
}

func TestSchedulerScheduleStandard5FieldCron(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	// Standard 5-field cron expressions generated by the UI must be accepted.
	cases := []struct {
		name     string
		schedule string
	}{
		{"daily at 10:45", "45 10 * * *"},
		{"every hour", "0 * * * *"},
		{"every 6 hours", "0 */6 * * *"},
		{"weekdays at 9am", "0 9 * * 1,2,3,4,5"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if err := scheduler.Schedule("team-1", "agent-1", tc.schedule); err != nil {
				t.Fatalf("Schedule(%q) should succeed for standard 5-field cron, got: %v", tc.schedule, err)
			}
			if next := scheduler.GetNextRun("team-1", "agent-1"); next == nil {
				t.Fatalf("GetNextRun should return a time after scheduling %q", tc.schedule)
			}
			scheduler.Unschedule("team-1", "agent-1")
		})
	}
}

func TestSchedulerGetNextRunsReturnsMultipleFutureTimes(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	if err := scheduler.Schedule("team-1", "agent-1", "0 9 * * *"); err != nil {
		t.Fatalf("Schedule failed: %v", err)
	}

	runs := scheduler.GetNextRuns("team-1", "agent-1", 5)
	if len(runs) != 5 {
		t.Fatalf("expected 5 runs, got %d", len(runs))
	}

	// Each run must be strictly after the previous one.
	for i := 1; i < len(runs); i++ {
		if !runs[i].After(runs[i-1]) {
			t.Fatalf("run[%d] (%s) is not after run[%d] (%s)", i, runs[i], i-1, runs[i-1])
		}
	}

	scheduler.Unschedule("team-1", "agent-1")

	// Should return nil for unscheduled heartbeat.
	if runs := scheduler.GetNextRuns("team-1", "agent-1", 5); runs != nil {
		t.Fatalf("expected nil for unscheduled heartbeat, got %d runs", len(runs))
	}
}

func TestSchedulerRejectsInvalidCron(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	if err := scheduler.Schedule("team-1", "agent-1", "not a cron"); err == nil {
		t.Fatal("Schedule should reject invalid cron expression")
	}
}

func TestSchedulerSkipsWhenConfigDisabled(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  false,
			Schedule: "0 * * * *",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, nil)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != 0 {
		t.Fatalf("expected executor not to be called, got %d calls", len(exec.calls))
	}
}

func TestSchedulerRoutesToTeamExecStore(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:     "team-1",
			AgentID:    "agent-1",
			Enabled:    true,
			Schedule:   "0 * * * *",
			ProfileKey: "custom-profile",
		},
	}
	teamExecStore := NewTeamExecutionStore(nil, exec, t.TempDir(), nil)
	scheduler := NewScheduler(exec, nil, configStore, teamExecStore)

	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	// Verify the team execution store received the enqueue (executor is called via goroutine)
	status := teamExecStore.Status("team-1")
	if status.State != "active" {
		t.Fatalf("expected team state 'active', got %q", status.State)
	}
	if len(status.RunningAgentIDs) != 1 || status.RunningAgentIDs[0] != "agent-1" {
		t.Fatalf("expected running [agent-1], got %v", status.RunningAgentIDs)
	}
}

func TestSchedulerHandlesMemberAlreadyQueued(t *testing.T) {
	exec := &captureExecutor{}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  true,
			Schedule: "0 * * * *",
		},
	}
	teamExecStore := NewTeamExecutionStore(nil, exec, t.TempDir(), nil)
	scheduler := NewScheduler(exec, nil, configStore, teamExecStore)

	// First call should succeed
	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	// Second call should be skipped (already running) without panic
	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	// Should still have exactly one running
	status := teamExecStore.Status("team-1")
	if status.State != "active" {
		t.Fatalf("expected team state 'active', got %q", status.State)
	}
}

// TestSchedulerSkipsTickWhenRecoveredObligationIsUncertain verifies the fence
// survives a restart: a dispatch whose run identity was never bound is retained
// as an uncertain obligation, and the next scheduled tick for that member is
// refused instead of admitting a duplicate heartbeat.
func TestSchedulerSkipsTickWhenRecoveredObligationIsUncertain(t *testing.T) {
	dir := t.TempDir()
	exec := &captureExecutor{}

	// Seed a running entry with no bound RunID, as after a lost start response.
	writeQueueFile(t, dir, "team-1", persistedTeamQueue{
		TeamID:            "team-1",
		QueuePolicy:       "serialized",
		MaxConcurrentRuns: 1,
		Running: []queuedExecution{
			{AgentID: "agent-1", ProfileKey: "p", RunID: ""},
		},
	})

	teamExecStore := NewTeamExecutionStore(nil, exec, dir, newMockAgentClient())
	teamExecStore.Recover(context.Background())

	if got := teamExecStore.Status("team-1"); len(got.UncertainAgentIDs) != 1 {
		t.Fatalf("expected one uncertain obligation after recovery, got %+v", got)
	}

	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  true,
			Schedule: "0 * * * *",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, teamExecStore)

	before := len(exec.calls)
	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != before {
		t.Fatalf("expected uncertain obligation to refuse the tick, executor called %d time(s)", len(exec.calls)-before)
	}
	if got := teamExecStore.Status("team-1"); len(got.RunningAgentIDs) != 1 {
		t.Fatalf("expected obligation retained after refused tick, got %+v", got)
	}
}

// TestSchedulerSkipsTickWhenRecoveredObligationIsPaused verifies that a
// quota-paused (parked) owner run is retained nonterminal ownership: the next
// scheduled tick is refused so a pause is never mistaken for a missing run.
func TestSchedulerSkipsTickWhenRecoveredObligationIsPaused(t *testing.T) {
	dir := t.TempDir()
	exec := &captureExecutor{}

	writeQueueFile(t, dir, "team-1", persistedTeamQueue{
		TeamID:            "team-1",
		QueuePolicy:       "serialized",
		MaxConcurrentRuns: 1,
		Running: []queuedExecution{
			{AgentID: "agent-1", ProfileKey: "p", RunID: "run-parked"},
		},
	})

	client := newMockAgentClient().
		WithGetRunResponse("run-parked", &Run{ID: "run-parked", Status: "RUN_STATUS_PARKED"})
	teamExecStore := NewTeamExecutionStore(nil, exec, dir, client)
	teamExecStore.Recover(context.Background())

	if got := teamExecStore.Status("team-1"); len(got.PausedAgentIDs) != 1 {
		t.Fatalf("expected one paused obligation after recovery, got %+v", got)
	}

	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  true,
			Schedule: "0 * * * *",
		},
	}
	scheduler := NewScheduler(exec, nil, configStore, teamExecStore)

	before := len(exec.calls)
	scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")

	if len(exec.calls) != before {
		t.Fatalf("expected paused obligation to refuse the tick, executor called %d time(s)", len(exec.calls)-before)
	}
	if got := teamExecStore.Status("team-1"); len(got.PausedAgentIDs) != 1 || len(got.RunningAgentIDs) != 1 {
		t.Fatalf("expected paused obligation retained after refused tick, got %+v", got)
	}
}

// blockingExecutor holds each Execute call until released and records how many
// calls were admitted.
type blockingExecutor struct {
	mu      sync.Mutex
	calls   int
	release chan struct{}
}

func (b *blockingExecutor) Execute(_ context.Context, teamID, agentID, _ string) (*ExecutionResult, error) {
	b.mu.Lock()
	b.calls++
	b.mu.Unlock()
	<-b.release
	return &ExecutionResult{TeamID: teamID, AgentID: agentID, Status: store.HeartbeatStatusRunning}, nil
}

// TestSchedulerConcurrentDuplicateTicksAdmitOne verifies the duplicate-trigger
// fence under concurrency: simultaneous scheduled ticks for one member admit
// exactly one execution and refuse the rest, with no catch-up queue.
func TestSchedulerConcurrentDuplicateTicksAdmitOne(t *testing.T) {
	exec := &blockingExecutor{release: make(chan struct{})}
	configStore := &stubConfigStore{
		config: &store.HeartbeatConfig{
			TeamID:   "team-1",
			AgentID:  "agent-1",
			Enabled:  true,
			Schedule: "0 * * * *",
		},
	}
	teamExecStore := NewTeamExecutionStore(nil, exec, t.TempDir(), nil)
	scheduler := NewScheduler(exec, nil, configStore, teamExecStore)

	const ticks = 8
	var wg sync.WaitGroup
	wg.Add(ticks)
	for i := 0; i < ticks; i++ {
		go func() {
			defer wg.Done()
			scheduler.executeHeartbeat(context.Background(), "team-1", "agent-1")
		}()
	}
	wg.Wait()

	waitFor(t, 5*time.Second, func() bool {
		exec.mu.Lock()
		defer exec.mu.Unlock()
		return exec.calls == 1
	}, "exactly one admitted execution")

	exec.mu.Lock()
	got := exec.calls
	exec.mu.Unlock()
	if got != 1 {
		t.Fatalf("expected exactly one admitted execution, got %d", got)
	}
	if status := teamExecStore.Status("team-1"); len(status.Queue) != 0 {
		t.Fatalf("expected no catch-up queue, got %+v", status.Queue)
	}
	close(exec.release)
}
