#!/usr/bin/env bash
# Cloudflare AI Gateway Configuration Defaults

# Service configuration
export CLOUDFLARE_AI_GATEWAY_NAME="cloudflare-ai-gateway"
export CLOUDFLARE_AI_GATEWAY_DISPLAY_NAME="Cloudflare AI Gateway"
export CLOUDFLARE_AI_GATEWAY_CATEGORY="ai"
export CLOUDFLARE_AI_GATEWAY_DESCRIPTION="Resilient AI traffic proxy with caching, rate limiting, and analytics"

# Gateway configuration
export CLOUDFLARE_AI_GATEWAY_DATA_DIR="${CLOUDFLARE_AI_GATEWAY_DATA_DIR:-${var_DATA_DIR}/resources/cloudflare-ai-gateway}"
export CLOUDFLARE_AI_GATEWAY_CONFIG_DIR="${CLOUDFLARE_AI_GATEWAY_DATA_DIR}/configs"
export CLOUDFLARE_AI_GATEWAY_LOGS_DIR="${CLOUDFLARE_AI_GATEWAY_DATA_DIR}/logs"

# API configuration
export CLOUDFLARE_AI_GATEWAY_API_BASE="https://api.cloudflare.com/client/v4"
export CLOUDFLARE_AI_GATEWAY_DEFAULT_NAME="${CLOUDFLARE_AI_GATEWAY_DEFAULT_NAME:-vrooli-ai-gateway}"
export CLOUDFLARE_AI_GATEWAY_DEFAULT_SLUG="${CLOUDFLARE_AI_GATEWAY_DEFAULT_SLUG:-vrooli}"

# Rate limiting defaults
export CLOUDFLARE_AI_GATEWAY_DEFAULT_RATE_LIMIT="${CLOUDFLARE_AI_GATEWAY_DEFAULT_RATE_LIMIT:-1000}"
export CLOUDFLARE_AI_GATEWAY_DEFAULT_CACHE_TTL="${CLOUDFLARE_AI_GATEWAY_DEFAULT_CACHE_TTL:-3600}"

# Export config function
cloudflare_ai_gateway::export_config() {
    export CLOUDFLARE_AI_GATEWAY_NAME CLOUDFLARE_AI_GATEWAY_DISPLAY_NAME 
    export CLOUDFLARE_AI_GATEWAY_CATEGORY CLOUDFLARE_AI_GATEWAY_DESCRIPTION
    export CLOUDFLARE_AI_GATEWAY_DATA_DIR CLOUDFLARE_AI_GATEWAY_CONFIG_DIR CLOUDFLARE_AI_GATEWAY_LOGS_DIR
    export CLOUDFLARE_AI_GATEWAY_API_BASE CLOUDFLARE_AI_GATEWAY_DEFAULT_NAME CLOUDFLARE_AI_GATEWAY_DEFAULT_SLUG
    export CLOUDFLARE_AI_GATEWAY_DEFAULT_RATE_LIMIT CLOUDFLARE_AI_GATEWAY_DEFAULT_CACHE_TTL
}