#!/usr/bin/env bash
################################################################################
# Resource Wrapper for Agent Management
# 
# Maintains backward compatibility with existing resource-specific CLI while
# using the unified agent management system internally
################################################################################

# Source common utilities
APP_ROOT="${APP_ROOT:-$(builtin cd "$(dirname "${BASH_SOURCE[0]}")/../../../" && builtin pwd)}"
source "${APP_ROOT}/scripts/lib/utils/log.sh"

#######################################
# Create resource-specific agent management wrapper
# Arguments:
#   $1 - Resource name
# Returns:
#   0 on success, 1 on error
#######################################
resource_wrapper::create() {
    local resource="$1"
    
    if [[ -z "$resource" ]]; then
        log::error "resource_wrapper::create: Resource name required"
        return 1
    fi
    
    local wrapper_file="${APP_ROOT}/resources/${resource}/lib/agents.sh"
    local config_file="${APP_ROOT}/resources/${resource}/config/agents.conf"
    
    # Check if config exists
    if [[ ! -f "$config_file" ]]; then
        log::error "Configuration file not found: $config_file"
        log::error "Create it first with proper resource settings"
        return 1
    fi
    
    # Create the wrapper
    cat > "$wrapper_file" << EOF
#!/usr/bin/env bash
################################################################################
# Agent Management for $resource (GENERATED WRAPPER)
# 
# This file is generated by the unified agent management system.
# It provides backward compatibility while using the plugin architecture.
# 
# REPLACES: 800+ lines of duplicate code
# WITH: This lightweight wrapper calling agent-manager.sh
################################################################################

# Source common utilities
APP_ROOT="\${APP_ROOT:-\$(builtin cd "\${BASH_SOURCE[0]%/*}/../../.." && builtin pwd)}"

# Load resource configuration
source "\${APP_ROOT}/resources/$resource/config/agents.conf"

# Source the unified manager (which provides agent_manager::* functions)
source "\${APP_ROOT}/scripts/resources/agents/agent-manager.sh"

#######################################
# Backward compatibility functions - THESE ARE ACTUALLY USED!
# Resource CLI scripts ($resource/cli.sh) call these directly
#######################################

agents::init_registry() { agent_manager::init_registry; }
agents::generate_id() { agent_manager::generate_id; }
agents::register() { agent_manager::register "\$@"; }
agents::unregister() { agent_manager::unregister "\$@"; }
agents::heartbeat() { agent_manager::heartbeat "\$@"; }
agents::is_pid_running() { agent_manager::is_pid_running "\$@"; }
agents::cleanup() { agent_manager::cleanup; }
agents::list() { agent_manager::list "\$@"; }
agents::stop() { agent_manager::stop "\$@"; }
agents::info() { agent_manager::info "\$@"; }
agents::logs() { agent_manager::logs "\$@"; }

#######################################
# CLI interface function
#######################################
${resource}::agents::command() {
    # This delegates to the main function in agent-manager.sh
    "\${APP_ROOT}/scripts/resources/agents/agent-manager.sh" --config="$resource" "\$@"
}

# Export all functions for backward compatibility
export -f agents::init_registry
export -f agents::generate_id
export -f agents::register
export -f agents::unregister
export -f agents::heartbeat
export -f agents::is_pid_running
export -f agents::cleanup
export -f agents::list
export -f agents::stop
export -f agents::info
export -f agents::logs
export -f ${resource}::agents::command
EOF
    
    chmod +x "$wrapper_file"
    log::info "Created wrapper for $resource: $wrapper_file"
    return 0
}

#######################################
# Generate wrappers for all configured resources
# Returns:
#   0 on success
#######################################
resource_wrapper::generate_all() {
    local resources_dir="${APP_ROOT}/resources"
    local count=0
    local failed=0
    
    log::info "Generating agent management wrappers..."
    
    for config_file in "$resources_dir"/*/config/agents.conf; do
        if [[ -f "$config_file" ]]; then
            local resource
            resource=$(basename "$(dirname "$(dirname "$config_file")")")
            
            if resource_wrapper::create "$resource"; then
                ((count++))
            else
                ((failed++))
                log::warn "Failed to create wrapper for: $resource"
            fi
        fi
    done
    
    log::info "Generated $count wrappers, $failed failed"
    return 0
}

# If run directly, generate all wrappers
if [[ "\${BASH_SOURCE[0]}" == "\${0}" ]]; then
    resource_wrapper::generate_all "\$@"
fi