// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
    eyebrow: "app.eyebrow",
  },
  goldens: {
    title: "goldens.title",
    subtitle: "goldens.subtitle",
    empty: "goldens.empty",
    emptyDescription: "goldens.emptyDescription",
    registerHeading: "goldens.registerHeading",
    registerOpen: "goldens.registerOpen",
    slugLabel: "goldens.slugLabel",
    templateLabel: "goldens.templateLabel",
    versionLabel: "goldens.versionLabel",
    pathLabel: "goldens.pathLabel",
    registerSubmit: "goldens.registerSubmit",
    registering: "goldens.registering",
    rowLabel: "goldens.rowLabel",
    regenerate: "goldens.regenerate",
    regenerating: "goldens.regenerating",
    delete: "goldens.delete",
    deleting: "goldens.deleting",
    close: "goldens.close",
    confirmDelete: "goldens.confirmDelete",
    confirmRegenerate: "goldens.confirmRegenerate",
    regenerateSuccess: "goldens.regenerateSuccess",
    lastRegeneratedLabel: "goldens.lastRegeneratedLabel",
    verdictSummaryPending: "goldens.verdictSummaryPending",
    skillsGridCaption: "goldens.skillsGridCaption",
    toolsGridCaption: "goldens.toolsGridCaption",
    backToIndex: "goldens.backToIndex",
    verdictSummaryCounts: "goldens.verdictSummaryCounts",
    noSkillVerdicts: "goldens.noSkillVerdicts",
    noToolVerdicts: "goldens.noToolVerdicts",
    tupleDetailTitle: "goldens.tupleDetailTitle",
    tupleBack: "goldens.tupleBack",
    tupleRunSummary: "goldens.tupleRunSummary",
    tupleNoRuns: "goldens.tupleNoRuns",
    tupleDurationLabel: "goldens.tupleDurationLabel",
    tupleTokensLabel: "goldens.tupleTokensLabel",
    tupleCostLabel: "goldens.tupleCostLabel",
    tupleAgentRunLabel: "goldens.tupleAgentRunLabel",
    tupleTabDiff: "goldens.tupleTabDiff",
    tupleTabManifest: "goldens.tupleTabManifest",
    tupleTabHistory: "goldens.tupleTabHistory",
    tupleDiffPlaceholder: "goldens.tupleDiffPlaceholder",
    tupleNoDiff: "goldens.tupleNoDiff",
    tupleManifestEmpty: "goldens.tupleManifestEmpty",
    tupleHistoryEmpty: "goldens.tupleHistoryEmpty",
  },
  skills: {
    title: "skills.title",
    subtitle: "skills.subtitle",
    empty: "skills.empty",
    emptyDescription: "skills.emptyDescription",
    rowLabel: "skills.rowLabel",
    detailHeading: "skills.detailHeading",
    contentHashLabel: "skills.contentHashLabel",
    backToIndex: "skills.backToIndex",
  },
  manifests: {
    title: "manifests.title",
    subtitle: "manifests.subtitle",
    empty: "manifests.empty",
    emptyDescription: "manifests.emptyDescription",
    rowLabel: "manifests.rowLabel",
    editorHeading: "manifests.editorHeading",
    allowedPathsLabel: "manifests.allowedPathsLabel",
    wildcardAllowedLabel: "manifests.wildcardAllowedLabel",
    convergenceTargetLabel: "manifests.convergenceTargetLabel",
    convergenceNone: "manifests.convergenceNone",
    convergenceEmptyDiff: "manifests.convergenceEmptyDiff",
    contentRulesLabel: "manifests.contentRulesLabel",
    saveButton: "manifests.saveButton",
    saving: "manifests.saving",
    saveSuccess: "manifests.saveSuccess",
    clearStaleButton: "manifests.clearStaleButton",
    clearingStale: "manifests.clearingStale",
    clearStaleSuccess: "manifests.clearStaleSuccess",
    backToIndex: "manifests.backToIndex",
    pinningLabel: "manifests.pinningLabel",
  },
  nav: {
    menuToggle: "nav.menuToggle",
    convergenceLabel: "nav.convergenceLabel",
    convergencePlaceholder: "nav.convergencePlaceholder",
    convergenceCounts: "nav.convergenceCounts",
    staleLabel: "nav.staleLabel",
    stalePlaceholder: "nav.stalePlaceholder",
    healthLabel: "nav.healthLabel",
    logo: "nav.logo",
    goldensLabel: "nav.goldensLabel",
    skillsLabel: "nav.skillsLabel",
    manifestsLabel: "nav.manifestsLabel",
    settingsLabel: "nav.settingsLabel",
  },
  settings: {
    title: "settings.title",
    subtitle: "settings.subtitle",
    themeHeading: "settings.themeHeading",
    themeDarkLabel: "settings.themeDarkLabel",
    themeLightLabel: "settings.themeLightLabel",
    localeHeading: "settings.localeHeading",
    densityHeading: "settings.densityHeading",
    densityComfortableLabel: "settings.densityComfortableLabel",
    densityCompactLabel: "settings.densityCompactLabel",
    sidebarHeading: "settings.sidebarHeading",
    sidebarCollapsed: "settings.sidebarCollapsed",
    catalogSyncHeading: "settings.catalogSyncHeading",
    catalogSyncDescription: "settings.catalogSyncDescription",
    catalogSyncButton: "settings.catalogSyncButton",
    catalogSyncing: "settings.catalogSyncing",
    catalogSyncSummary: "settings.catalogSyncSummary",
    catalogSyncNeverRun: "settings.catalogSyncNeverRun",
    watcherHeading: "settings.watcherHeading",
    watcherDescription: "settings.watcherDescription",
    watcherStaleSummary: "settings.watcherStaleSummary",
    watcherEmpty: "settings.watcherEmpty",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
