package validation_run

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	golden "development-toolchain-validator/internal/golden"
	manifest "development-toolchain-validator/internal/manifest"

	"github.com/google/uuid"
)

const generatedGoldenMarker = ".dtv-generated-golden"

// GoldenMaterializerFromRepo adapts a golden.Repository and generator runner
// into GoldenMaterializer.
type GoldenMaterializerFromRepo struct {
	Repo    golden.Repository
	Runner  golden.RegeneratorRunner
	BaseDir string
	Retain  bool
}

func (g GoldenMaterializerFromRepo) Materialize(ctx context.Context, goldenSlug string) (MaterializedGolden, error) {
	gld, err := g.Repo.Get(ctx, goldenSlug)
	if err != nil {
		var nf golden.ErrGoldenNotFound
		if errors.As(err, &nf) {
			return MaterializedGolden{}, ErrInvalidRun{Field: "golden_slug", Reason: "no such golden"}
		}
		return MaterializedGolden{}, err
	}
	if g.Runner == nil {
		return MaterializedGolden{}, fmt.Errorf("golden materializer: generator runner not configured")
	}
	base := strings.TrimSpace(g.BaseDir)
	if base == "" {
		base = filepath.Join(os.TempDir(), "vrooli-dtv-generated-goldens")
	}
	if err := os.MkdirAll(base, 0o755); err != nil {
		return MaterializedGolden{}, fmt.Errorf("prepare generated golden base: %w", err)
	}
	dest := filepath.Join(base, gld.Slug+"-"+uuid.NewString())
	out, err := g.Runner.Regenerate(ctx, golden.RegenerateRunnerInput{
		Slug:            gld.Slug,
		TemplateID:      gld.TemplateID,
		TemplateVersion: gld.TemplateVersionPinned,
		Path:            dest,
	})
	if err != nil {
		_ = os.RemoveAll(dest)
		_ = g.markMaterialized(ctx, gld, dest, golden.MaterializationStatusFailed)
		return MaterializedGolden{}, err
	}
	if version := strings.TrimSpace(out.TemplateVersion); version != "" {
		gld.TemplateVersionPinned = version
	}
	if err := os.WriteFile(filepath.Join(dest, generatedGoldenMarker), []byte("generated by development-toolchain-validator\n"), 0o644); err != nil {
		_ = os.RemoveAll(dest)
		_ = g.markMaterialized(ctx, gld, dest, golden.MaterializationStatusFailed)
		return MaterializedGolden{}, fmt.Errorf("write generated golden marker: %w", err)
	}
	if err := g.markMaterialized(ctx, gld, dest, golden.MaterializationStatusReady); err != nil {
		_ = os.RemoveAll(dest)
		return MaterializedGolden{}, err
	}
	logicalRoot := strings.TrimSpace(gld.LogicalRoot)
	if logicalRoot == "" {
		logicalRoot = gld.Path
	}
	cleanup := func() error { return cleanupGeneratedGolden(dest) }
	if g.Retain {
		cleanup = func() error { return nil }
	}
	return MaterializedGolden{
		GoldenSlug:   gld.Slug,
		PhysicalPath: dest,
		LogicalRoot:  logicalRoot,
		Cleanup:      cleanup,
	}, nil
}

func (g GoldenMaterializerFromRepo) markMaterialized(ctx context.Context, gld golden.Golden, path, status string) error {
	gld.LastMaterializedPath = path
	gld.LastMaterializedStatus = status
	_, err := g.Repo.Update(ctx, gld)
	return err
}

func cleanupGeneratedGolden(path string) error {
	if strings.TrimSpace(path) == "" {
		return nil
	}
	marker := filepath.Join(path, generatedGoldenMarker)
	if _, err := os.Stat(marker); err != nil {
		return fmt.Errorf("refusing to clean unmarked generated golden %q: %w", path, err)
	}
	return os.RemoveAll(path)
}

var _ GoldenMaterializer = GoldenMaterializerFromRepo{}

// ManifestSourceFromRepo adapts a manifest.Repository into ManifestSource.
type ManifestSourceFromRepo struct {
	Repo manifest.Repository
}

func (m ManifestSourceFromRepo) GetManifest(ctx context.Context, skillID, goldenSlug string) (manifest.Manifest, error) {
	return m.Repo.Get(ctx, skillID, goldenSlug)
}

var _ ManifestSource = ManifestSourceFromRepo{}
