# Vrooli Resource Interface Validation - CI/CD Integration Examples
# Copy and adapt these examples for your preferred CI/CD platform

# ==================================================
# GitHub Actions Example
# File: .github/workflows/resource-validation.yml
# ==================================================

name: Resource Interface Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'scripts/resources/**/manage.sh'
      - 'scripts/resources/contracts/**'
      - 'scripts/resources/tests/framework/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/resources/**/manage.sh'
      - 'scripts/resources/contracts/**'
      - 'scripts/resources/tests/framework/**'

jobs:
  validate-resource-interfaces:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Layer 1 validation should complete quickly
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup validation environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc  # Required for JUnit duration calculations
        
    - name: Run Layer 1 Syntax Validation (Quick)
      run: |
        cd scripts/resources
        ./tools/validate-interfaces.sh --level quick --format junit --parallel > validation-results.xml
        
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Resource Interface Validation
        path: scripts/resources/validation-results.xml
        reporter: java-junit
        
    - name: Upload validation report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: resource-validation-report
        path: scripts/resources/validation-results.xml
        retention-days: 30

  validate-specific-resources:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get changed resources
      id: changed-resources
      run: |
        # Find changed manage.sh files
        changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'manage\.sh$' || true)
        if [ -n "$changed_files" ]; then
          # Extract resource names from paths
          resources=$(echo "$changed_files" | xargs -I {} dirname {} | xargs -I {} basename {} | sort -u | tr '\n' ' ')
          echo "resources=$resources" >> $GITHUB_OUTPUT
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Validate changed resources
      if: steps.changed-resources.outputs.changed == 'true'
      run: |
        cd scripts/resources
        for resource in ${{ steps.changed-resources.outputs.resources }}; do
          echo "Validating resource: $resource"
          ./tools/validate-interfaces.sh --resource "$resource" --level quick --verbose
        done

# ==================================================
# GitLab CI Example  
# File: .gitlab-ci.yml (resource validation section)
# ==================================================

stages:
  - validate

resource-interface-validation:
  stage: validate
  image: ubuntu:22.04
  timeout: 5m
  
  before_script:
    - apt-get update && apt-get install -y bc git
    
  script:
    - cd scripts/resources
    - ./tools/validate-interfaces.sh --level quick --format junit --parallel > validation-results.xml
    
  artifacts:
    when: always
    reports:
      junit: scripts/resources/validation-results.xml
    paths:
      - scripts/resources/validation-results.xml
    expire_in: 30 days
    
  rules:
    - changes:
        - scripts/resources/**/manage.sh
        - scripts/resources/contracts/**/*
        - scripts/resources/tests/framework/**/*

resource-validation-mr:
  stage: validate
  image: ubuntu:22.04
  timeout: 3m
  
  script:
    - cd scripts/resources
    - |
      # Find changed resources in merge request
      changed_resources=$(git diff --name-only $CI_MERGE_REQUEST_TARGET_BRANCH_SHA...HEAD | grep 'manage\.sh$' | xargs -I {} dirname {} | xargs -I {} basename {} | sort -u || true)
      if [ -n "$changed_resources" ]; then
        for resource in $changed_resources; do
          echo "Validating changed resource: $resource"
          ./tools/validate-interfaces.sh --resource "$resource" --level quick --verbose
        done
      else
        echo "No resource changes detected"
      fi
      
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# ==================================================
# Jenkins Pipeline Example
# File: Jenkinsfile (resource validation stage)
# ==================================================

pipeline {
    agent any
    
    stages {
        stage('Resource Interface Validation') {
            when {
                anyOf {
                    changeset 'scripts/resources/**/manage.sh'
                    changeset 'scripts/resources/contracts/**'
                    changeset 'scripts/resources/tests/framework/**'
                }
            }
            
            steps {
                script {
                    // Quick validation for all resources
                    sh '''
                        cd scripts/resources
                        ./tools/validate-interfaces.sh --level quick --format junit --parallel > validation-results.xml
                    '''
                }
            }
            
            post {
                always {
                    // Publish JUnit test results
                    publishTestResults testResultsPattern: 'scripts/resources/validation-results.xml'
                    
                    // Archive validation report
                    archiveArtifacts artifacts: 'scripts/resources/validation-results.xml', 
                                   fingerprint: true, 
                                   allowEmptyArchive: false
                }
                
                failure {
                    emailext(
                        subject: "Resource Validation Failed - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                        body: "Resource interface validation failed. Check the build logs for details.",
                        to: "${env.CHANGE_AUTHOR_EMAIL}"
                    )
                }
            }
        }
        
        stage('Validate Changed Resources') {
            when {
                changeRequest()
            }
            
            steps {
                script {
                    // Get list of changed manage.sh files
                    def changedResources = sh(
                        script: """
                            git diff --name-only origin/${env.CHANGE_TARGET}...HEAD | 
                            grep 'manage\\.sh\$' | 
                            xargs -I {} dirname {} | 
                            xargs -I {} basename {} | 
                            sort -u || true
                        """,
                        returnStdout: true
                    ).trim()
                    
                    if (changedResources) {
                        changedResources.split('\n').each { resource ->
                            sh """
                                cd scripts/resources
                                echo "Validating changed resource: ${resource}"
                                ./tools/validate-interfaces.sh --resource "${resource}" --level quick --verbose
                            """
                        }
                    } else {
                        echo "No resource changes detected in this PR"
                    }
                }
            }
        }
    }
}

# ==================================================
# Azure DevOps Pipeline Example
# File: azure-pipelines.yml (resource validation section)
# ==================================================

trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - scripts/resources/**/manage.sh
    - scripts/resources/contracts/**
    - scripts/resources/tests/framework/**

pr:
  branches:
    include:
    - main
  paths:
    include:
    - scripts/resources/**/manage.sh
    - scripts/resources/contracts/**
    - scripts/resources/tests/framework/**

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ValidateResourceInterfaces
  displayName: 'Resource Interface Validation'
  timeoutInMinutes: 5
  
  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y bc
    displayName: 'Install dependencies'
    
  - bash: |
      cd scripts/resources
      ./tools/validate-interfaces.sh --level quick --format junit --parallel > validation-results.xml
    displayName: 'Run Layer 1 validation'
    
  - task: PublishTestResults@2
    displayName: 'Publish validation results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'scripts/resources/validation-results.xml'
      testRunTitle: 'Resource Interface Validation'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Archive validation report'
    condition: always()
    inputs:
      pathToPublish: 'scripts/resources/validation-results.xml'
      artifactName: 'resource-validation-report'

- job: ValidateChangedResources
  displayName: 'Validate Changed Resources (PR only)'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  
  steps:
  - bash: |
      # Find changed manage.sh files in PR
      changed_files=$(git diff --name-only origin/$(System.PullRequest.TargetBranch)...HEAD | grep 'manage\.sh$' || true)
      if [ -n "$changed_files" ]; then
        resources=$(echo "$changed_files" | xargs -I {} dirname {} | xargs -I {} basename {} | sort -u)
        cd scripts/resources
        for resource in $resources; do
          echo "Validating changed resource: $resource"
          ./tools/validate-interfaces.sh --resource "$resource" --level quick --verbose
        done
      else
        echo "No resource changes detected in this PR"
      fi
    displayName: 'Validate changed resources'

# ==================================================
# Docker-based Validation (for any CI/CD)
# ==================================================

# Dockerfile for validation container
# File: scripts/resources/docker/Dockerfile.validation

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    bash \
    bc \
    git \
    grep \
    findutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# Copy validation framework
COPY scripts/resources/contracts/ ./contracts/
COPY scripts/resources/tests/framework/ ./tests/framework/
COPY scripts/resources/tools/ ./tools/

# Make validation script executable
RUN chmod +x ./tools/validate-interfaces.sh

# Default command runs validation
CMD ["./tools/validate-interfaces.sh", "--level", "quick", "--format", "junit", "--parallel"]

# Usage in any CI/CD:
# docker build -f scripts/resources/docker/Dockerfile.validation -t resource-validator .
# docker run --rm -v $(pwd)/scripts/resources:/workspace/resources resource-validator

# ==================================================
# Pre-commit Hook Integration
# ==================================================

# Add to .pre-commit-hooks.yaml:
repos:
- repo: local
  hooks:
  - id: resource-validation
    name: Resource Interface Validation
    entry: scripts/resources/tools/validate-interfaces.sh
    args: [--level, quick, --format, text]
    language: script
    files: 'scripts/resources/.*/manage\.sh$'
    pass_filenames: false
    
# ==================================================
# Makefile Integration
# ==================================================

# Add to Makefile:
.PHONY: validate-resources validate-resources-quick validate-resources-full

validate-resources: validate-resources-quick

validate-resources-quick:
	@echo "Running Layer 1 resource interface validation..."
	@cd scripts/resources && ./tools/validate-interfaces.sh --level quick --parallel

validate-resources-full:
	@echo "Running full resource interface validation..."
	@cd scripts/resources && ./tools/validate-interfaces.sh --level full --parallel

validate-resources-junit:
	@echo "Running resource validation with JUnit output..."
	@cd scripts/resources && ./tools/validate-interfaces.sh --level quick --format junit --parallel > validation-results.xml

# ==================================================
# npm/yarn Integration (for Node.js projects)
# ==================================================

# Add to package.json:
{
  "scripts": {
    "validate:resources": "cd scripts/resources && ./tools/validate-interfaces.sh --level quick --parallel",
    "validate:resources:junit": "cd scripts/resources && ./tools/validate-interfaces.sh --level quick --format junit --parallel > validation-results.xml",
    "validate:resources:verbose": "cd scripts/resources && ./tools/validate-interfaces.sh --level quick --verbose --parallel"
  }
}

# ==================================================
# Integration Notes
# ==================================================

# Performance Expectations:
# - Layer 1 validation: < 2 seconds for 20+ resources
# - Parallel execution: ~70% faster than sequential
# - Memory usage: < 50MB during validation
# - Network: No external dependencies required

# Exit Codes:
# 0 - All resources pass validation
# 1 - One or more resources fail validation
# 2 - Validation framework error (missing dependencies, etc.)

# Output Formats:
# - text: Human-readable, colored output
# - json: Machine-readable JSON with detailed results
# - junit: XML format for CI/CD test result integration
# - csv: Tabular format for spreadsheet analysis

# Caching:
# - Validation results are cached based on file content hash
# - Cache hits provide ~90% speed improvement
# - Cache automatically expires after 1 hour
# - Use --no-cache to force fresh validation

# Parallel Execution:
# - Use --parallel flag for fastest validation
# - Automatically detects optimal concurrency level
# - Safe for CI/CD environments
# - Falls back to sequential if issues detected