// Package adoptions is the domain-scoped home for the adoption registry
// — soft links from a library component (by id) to a concrete copy of
// its source under a target scenario's tree. Cross-domain references
// (to components.id) are stored as IDs only, no SQL constraint.
//
// Layering:
//
//	HTTP → handler → Service (drift compute) → Repository (sqlite)
//	                       ↑                          ↑
//	                       FakeService (handler tests) FakeRepository (service tests)
//	                                                    Real sqlite (repository tests)
//
// types.go owns the domain entity + typed sentinels. repository.go
// owns persistence. service.go owns the Refresh policy (current /
// behind / modified / unknown). The scenarios-tree resolver and the
// components-content reader are seams the service depends on; tests
// inject fakes.
package adoptions

import (
	"fmt"
	"time"
)

// Status is the drift state computed by Refresh. Stored as the lower-
// case wire string for sqlite portability — the proto enum is mapped
// at the transport edge.
type Status string

const (
	StatusEmpty    Status = ""
	StatusCurrent  Status = "current"
	StatusBehind   Status = "behind"
	StatusModified Status = "modified"
	StatusUnknown  Status = "unknown"
)

// Valid returns true when s is one of the wire-recognised values.
func (s Status) Valid() bool {
	switch s {
	case StatusEmpty, StatusCurrent, StatusBehind, StatusModified, StatusUnknown:
		return true
	}
	return false
}

// Adoption is the internal domain shape for an adoption record. The
// wire/proto type lives at the transport edge; this struct is the only
// shape internal callers depend on.
type Adoption struct {
	ID             string
	ComponentID    string
	LibraryID      string
	Scenario       string
	AdoptedPath    string
	AdoptedVersion string
	// AdoptedSnapshotSHA256 is the sha256 of the adopted file content
	// at create time. Refresh compares the current adopted bytes to
	// this snapshot to distinguish behind (clean adopted copy, library
	// has moved on) from modified (caller edited the adopted file
	// locally).
	AdoptedSnapshotSHA256 string
	Status                Status
	StatusDetail   string
	CreatedAt      time.Time
	RefreshedAt    time.Time
	// DriftBacklogRef is the swarm-manager backlog item ("<kind>/<name>")
	// filed by Refresh when this adoption first transitioned to
	// behind/modified. Cleared back to "" when status returns to current
	// so a future drift files a fresh item.
	DriftBacklogRef string
}

// CreateInput is the explicit DTO the service hands to the repository
// on create. Distinct from Adoption because ID and CreatedAt are
// generated by the repository.
type CreateInput struct {
	ComponentID           string
	LibraryID             string
	Scenario              string
	AdoptedPath           string
	AdoptedVersion        string
	AdoptedSnapshotSHA256 string
}

// RefreshUpdate carries the per-row update Refresh writes back to the
// repository after computing drift. Repository merges these fields
// onto the existing row without touching CreatedAt / ComponentID /
// Scenario / AdoptedPath / AdoptedVersion.
type RefreshUpdate struct {
	ID           string
	Status       Status
	StatusDetail string
	RefreshedAt  time.Time
	// DriftBacklogRef is set when Refresh successfully filed a backlog
	// item via swarm-manager. Empty string means "leave the existing
	// value untouched"; the explicit empty-clear path uses
	// ClearDriftBacklogRef below so the repository can tell the
	// difference between "no opinion" and "clear it".
	DriftBacklogRef       string
	ClearDriftBacklogRef  bool
}

// ListQuery filters a List call. All fields optional.
type ListQuery struct {
	ComponentID string
	Scenario    string
	Limit       int
}

// ErrAdoptionNotFound is the typed sentinel handlers translate to a
// 404 via errors.As.
type ErrAdoptionNotFound struct {
	ID string
}

func (e ErrAdoptionNotFound) Error() string {
	return fmt.Sprintf("adoption %q not found", e.ID)
}

// ErrInvalidAdoption is returned by the service when the caller's
// input does not satisfy the create contract. Field names the
// offending field; Reason is a human-safe explanation.
type ErrInvalidAdoption struct {
	Field  string
	Reason string
}

func (e ErrInvalidAdoption) Error() string {
	return fmt.Sprintf("invalid adoption: %s: %s", e.Field, e.Reason)
}
