// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    navigationLabel: "layout.navigationLabel",
    mobileNavigationLabel: "layout.mobileNavigationLabel",
    skipToContent: "layout.skipToContent",
    openNavigation: "layout.openNavigation",
    closeNavigation: "layout.closeNavigation",
    nav: {
      dashboard: "layout.nav.dashboard",
      plan: "layout.nav.plan",
      goals: "layout.nav.goals",
      focus: "layout.nav.focus",
      review: "layout.nav.review",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      placeholderTitle: "pages.dashboard.placeholderTitle",
      placeholderDescription: "pages.dashboard.placeholderDescription",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
      description: "pages.settings.description",
      preferences: "pages.settings.preferences",
      themeHint: "pages.settings.themeHint",
      localeHint: "pages.settings.localeHint",
      storyKicker: "pages.settings.storyKicker",
      storyTitle: "pages.settings.storyTitle",
      storyIntro: "pages.settings.storyIntro",
      storyIncludedTitle: "pages.settings.storyIncludedTitle",
      storyIncluded: "pages.settings.storyIncluded",
      storyPrivateTitle: "pages.settings.storyPrivateTitle",
      storyPrivate: "pages.settings.storyPrivate",
      storyFutureTitle: "pages.settings.storyFutureTitle",
      storyFuture: "pages.settings.storyFuture",
      storyNote: "pages.settings.storyNote",
      sceneryHeading: "pages.settings.sceneryHeading",
      sceneryHint: "pages.settings.sceneryHint",
      artFree: "pages.settings.artFree",
      reducedScenery: "pages.settings.reducedScenery",
      subduedNight: "pages.settings.subduedNight",
      planningHeading: "pages.settings.planningHeading",
      planningHint: "pages.settings.planningHint",
      planningUnavailable: "pages.settings.planningUnavailable",
      planningLoading: "pages.settings.planningLoading",
      timezone: "pages.settings.timezone",
      weekStart: "pages.settings.weekStart",
      monday: "pages.settings.monday",
      sunday: "pages.settings.sunday",
      dailyCapacity: "pages.settings.dailyCapacity",
      reserve: "pages.settings.reserve",
      focusSession: "pages.settings.focusSession",
      savePlanning: "pages.settings.savePlanning",
      planningSaveError: "pages.settings.planningSaveError",
      planningSaved: "pages.settings.planningSaved",
      availabilityHeading: "pages.settings.availabilityHeading",
      availabilityHint: "pages.settings.availabilityHint",
      availabilityLoading: "pages.settings.availabilityLoading",
      weekday1: "pages.settings.weekday1",
      weekday2: "pages.settings.weekday2",
      weekday3: "pages.settings.weekday3",
      weekday4: "pages.settings.weekday4",
      weekday5: "pages.settings.weekday5",
      weekday6: "pages.settings.weekday6",
      weekday7: "pages.settings.weekday7",
      protectedTime: "pages.settings.protectedTime",
      protectedReason: "pages.settings.protectedReason",
      saveAvailability: "pages.settings.saveAvailability",
      availabilitySaveError: "pages.settings.availabilitySaveError",
      availabilitySaved: "pages.settings.availabilitySaved",
      integrationsHeading: "pages.settings.integrationsHeading",
      integrationsHint: "pages.settings.integrationsHint",
      integrationsLoading: "pages.settings.integrationsLoading",
      integrationsEmpty: "pages.settings.integrationsEmpty",
      fixtureConnection: "pages.settings.fixtureConnection",
      fixtureConnectionHelp: "pages.settings.fixtureConnectionHelp",
      syncConnection: "pages.settings.syncConnection",
      disconnectConnection: "pages.settings.disconnectConnection",
      connectionReadOnly: "pages.settings.connectionReadOnly",
      connectionEvents: "pages.settings.connectionEvents",
      connectionBusy: "pages.settings.connectionBusy",
      connectionFixture: "pages.settings.connectionFixture",
      connectionSynced: "pages.settings.connectionSynced",
      connectionCreated: "pages.settings.connectionCreated",
      connectionDisconnected: "pages.settings.connectionDisconnected",
      connectionError: "pages.settings.connectionError",
      integrationBoundary: "pages.settings.integrationBoundary",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
    description: "health.description",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
