# Deployment orchestration for scenario-to-app conversion
# This file defines HOW to deploy a scenario as a running application
apiVersion: vrooli.com/v1
kind: ScenarioApp
metadata:
  name: "resume-screening-assistant"
  version: "1.0.0"
  labels:
    category: "ai-recruitment"
    complexity: "intermediate"

# Deployment orchestration - the critical missing piece
deployment:
  # Step-by-step app initialization sequence
  startup_sequence:
    - name: validate_resources
      description: "Check that all required resources are healthy"
      action: check_health
      resources: ["unstructured-io", "ollama", "qdrant"]
      timeout_seconds: 30
      
    - name: initialize_vector_collection
      description: "Create Qdrant collection for candidate profiles"
      action: create_collection
      target_url: "{{ qdrant.baseUrl }}"
      collection_name: "candidate_profiles"
      vector_size: 384
      distance: "Cosine"
      
    - name: deploy_workflows
      description: "Import workflows into automation platforms"
      action: import_workflows
      targets:
        n8n: 
          condition: "n8n in resources.optional"
          files: "initialization/workflows/n8n/*.json"
          base_url: "{{ n8n.baseUrl }}"
        windmill:
          condition: "windmill in resources.optional" 
          files: "initialization/workflows/windmill/scripts/*"
          base_url: "{{ windmill.baseUrl }}"
        
    - name: apply_configuration
      description: "Load runtime configuration and feature flags"
      action: load_config
      files:
        - "initialization/configuration/app-config.json"
        - "initialization/configuration/resource-urls.json"
        - "initialization/configuration/feature-flags.json"
        
    - name: seed_candidate_templates
      description: "Initialize templates for candidate assessment"
      action: seed_vectors
      source: "initialization/vectors/assessment-templates.json"
      target_url: "{{ qdrant.baseUrl }}"
      collection: "assessment_templates"
      
    - name: configure_storage
      description: "Set up object storage for resumes and reports"
      action: configure_storage
      condition: "minio in resources.optional"
      source: "initialization/storage/minio-config.json"
      target_url: "{{ minio.baseUrl }}"
      
    - name: deploy_ui
      description: "Create professional recruitment interface"
      action: create_app
      condition: "windmill in resources.optional and requires_ui"
      source: "initialization/ui/windmill-app.json"
      target_url: "{{ windmill.baseUrl }}"
      
    - name: activate_triggers
      description: "Enable resume processing workflows"
      action: enable_workflows
      config: "initialization/workflows/triggers.yaml"
      delay_seconds: 5  # Allow services to fully initialize

# Health monitoring configuration
health_checks:
  - name: app_health
    endpoint: "/api/health"
    interval: 30s
    timeout: 5s
    
  - name: resume_processor_health
    endpoint: "/api/resume-processor/status"
    interval: 60s
    timeout: 10s
    
  - name: candidate_db_health
    endpoint: "{{ qdrant.baseUrl }}/collections/candidate_profiles"
    interval: 30s
    timeout: 5s

# Application URLs after deployment
urls:
  # Main application interface
  app: "http://localhost:3000/resume-screening-assistant"
  
  # Administrative interface
  admin: "http://localhost:3000/admin/resume-screening-assistant"
  
  # API endpoints
  api: "http://localhost:3000/api/resume-screening-assistant"
  
  # Health check endpoint
  health: "http://localhost:3000/api/resume-screening-assistant/health"
  
  # Resume upload endpoint
  upload: "http://localhost:3000/api/resume-screening-assistant/upload"
  
  # Candidate search interface
  search: "http://localhost:3000/api/resume-screening-assistant/search"

# Resource configuration generation
resource_config:
  # Generate .vrooli/service.json with only required resources
  enabled_only: true
  
  # Resource-specific settings
  unstructured_io:
    strategy: "fast"
    output_format: "application/json"
    extract_metadata: true
    
  ollama:
    models:
      - "llama3.2:3b"  # Lightweight model for candidate assessment
    max_context: 4096
    
  qdrant:
    collections:
      - name: "candidate_profiles"
        size: 384
        distance: "Cosine"
      - name: "assessment_templates"
        size: 384
        distance: "Cosine"
      - name: "job_requirements"
        size: 384
        distance: "Cosine"
    
  minio:
    buckets:
      - "resume-screening-assistant-uploads"
      - "resume-screening-assistant-reports"
      - "resume-screening-assistant-backups"

# Cleanup procedures for scenario testing
cleanup:
  # Vector database cleanup
  qdrant:
    - action: delete_collections
      collections:
        - "candidate_profiles"
        - "assessment_templates"
        - "job_requirements"
      
  # Workflow cleanup  
  n8n:
    - action: delete_workflows
      filter: "tags:resume-screening-assistant"
      
  windmill:
    - action: delete_workspace
      name: "resume-screening-assistant"
      
  # Storage cleanup
  minio:
    - action: delete_buckets
      buckets: 
        - "resume-screening-assistant-uploads"
        - "resume-screening-assistant-reports"
        - "resume-screening-assistant-backups"

# Validation rules
validation:
  # Pre-deployment checks
  pre_deploy:
    - check: resource_availability
      resources: ["unstructured-io", "ollama", "qdrant"]
      
    - check: port_availability
      ports: [3000, 8000, 11434, 6333]  # App, unstructured, ollama, qdrant
      
    - check: disk_space
      minimum: "2GB"  # For model storage and resume processing
      
    - check: ollama_models
      required_models: ["llama3.2:3b"]
      
  # Post-deployment checks  
  post_deploy:
    - check: health_endpoints
      timeout: 60s
      
    - check: vector_collections
      collections: ["candidate_profiles", "assessment_templates"]
      
    - check: resume_processing
      test_file: "test-data/sample-resume.pdf"
      expected_fields: ["name", "email", "skills", "experience"]

# Performance monitoring
monitoring:
  # Key metrics to track
  metrics:
    - name: resume_processing_time
      endpoint: "/api/resume-screening-assistant/process"
      target_p95: "5000ms"  # 5 seconds for full resume processing
      
    - name: candidate_matching_time
      endpoint: "/api/resume-screening-assistant/match"
      target_p95: "1000ms"  # 1 second for matching
      
    - name: throughput
      endpoint: "/api/resume-screening-assistant"
      target_rps: 10  # 10 resumes per second
      
    - name: error_rate
      endpoint: "/api/resume-screening-assistant"
      target_error_rate: "1%"

# Business metrics
business_metrics:
  # Track business value delivery
  kpis:
    - name: resumes_processed
      type: counter
      description: "Total resumes processed"
      
    - name: candidates_matched
      type: counter
      description: "Successful candidate matches"
      
    - name: average_assessment_score
      type: gauge
      description: "Average candidate quality score"
      
    - name: time_to_shortlist
      type: histogram
      description: "Time to generate candidate shortlist"

# Development mode settings
development:
  # Enable hot reloading
  hot_reload: true
  
  # Enhanced logging
  log_level: "debug"
  
  # Skip certain validations
  skip_validations: ["disk_space", "performance"]
  
  # Shorter timeouts for faster iteration
  timeouts:
    startup: 30s
    health_check: 5s
    resume_processing: 10s
  
  # Use smaller test model for development
  test_model: "tinyllama:1b"