package quality_test

import (
	"context"
	"testing"
	"time"

	apidb "github.com/vrooli/api-core/database"

	"knowledge-observatory/internal/dbtest"
	"knowledge-observatory/internal/quality"
)

func newRepo(t *testing.T) *quality.SQLite {
	t.Helper()
	return quality.NewSQLite(dbtest.New(t, apidb.SchemaProviderFunc(quality.Schema)))
}

func ptr(v float64) *float64 { return &v }

// TestMetricRoundTripCoversEveryColumn writes every writable column and reads
// each one back. A silently lossy type translation (REAL truncation, a dropped
// timestamp) fails here rather than in production.
func TestMetricRoundTripCoversEveryColumn(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	measured := time.Date(2026, 5, 6, 7, 8, 9, 0, time.UTC)
	in := quality.Metric{
		CollectionName: "vrooli_knowledge",
		Coherence:      ptr(0.25),
		Freshness:      ptr(0.5),
		Redundancy:     ptr(0.75),
		Coverage:       ptr(1),
		TotalEntries:   4321,
		MeasuredAt:     measured,
	}
	id, err := repo.InsertMetric(ctx, in)
	if err != nil {
		t.Fatalf("insert: %v", err)
	}
	if id == "" {
		t.Fatal("insert returned an empty id")
	}

	got, ok, err := repo.LatestMetric(ctx, "vrooli_knowledge")
	if err != nil || !ok {
		t.Fatalf("latest: ok=%v err=%v", ok, err)
	}

	if got.ID != id {
		t.Errorf("id = %q, want %q", got.ID, id)
	}
	if got.CollectionName != in.CollectionName {
		t.Errorf("collection_name = %q, want %q", got.CollectionName, in.CollectionName)
	}
	for _, c := range []struct {
		name      string
		got, want *float64
	}{
		{"coherence_score", got.Coherence, in.Coherence},
		{"freshness_score", got.Freshness, in.Freshness},
		{"redundancy_score", got.Redundancy, in.Redundancy},
		{"coverage_score", got.Coverage, in.Coverage},
	} {
		if c.got == nil || *c.got != *c.want {
			t.Errorf("%s = %v, want %v", c.name, c.got, *c.want)
		}
	}
	if got.TotalEntries != in.TotalEntries {
		t.Errorf("total_entries = %d, want %d", got.TotalEntries, in.TotalEntries)
	}
	// avg_quality is generated by the database, not written by the caller.
	if got.AvgQuality == nil || *got.AvgQuality != 0.625 {
		t.Errorf("avg_quality = %v, want 0.625 (the generated column)", got.AvgQuality)
	}
	if !got.MeasuredAt.UTC().Equal(measured) {
		t.Errorf("measured_at = %v, want %v", got.MeasuredAt.UTC(), measured)
	}
	if got.CreatedAt.IsZero() || got.UpdatedAt.IsZero() {
		t.Errorf("created_at/updated_at not defaulted: %v / %v", got.CreatedAt, got.UpdatedAt)
	}
}

// TestNullScoresSurviveTheCheckConstraint proves the CHECK constraints were
// translated with an explicit IS NULL arm. Postgres treats `NULL >= 0` as
// unknown and admits the row; a naive SQLite translation would too, but the
// explicit form documents the intent and this test locks it in.
func TestNullScoresSurviveTheCheckConstraint(t *testing.T) {
	repo := newRepo(t)
	if _, err := repo.InsertMetric(context.Background(), quality.Metric{
		CollectionName: "sparse",
		TotalEntries:   1,
	}); err != nil {
		t.Fatalf("insert with null scores: %v", err)
	}
}

func TestOutOfRangeScoreIsRejected(t *testing.T) {
	repo := newRepo(t)
	if _, err := repo.InsertMetric(context.Background(), quality.Metric{
		CollectionName: "bad",
		Coherence:      ptr(1.5),
	}); err == nil {
		t.Fatal("expected the CHECK constraint to reject a score above 1")
	}
}

func TestCollectionStatRoundTripCoversEveryColumn(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	in := quality.CollectionStat{
		CollectionName:    "vrooli_knowledge",
		TotalEntries:      120,
		TotalSearches:     34,
		AvgSearchScore:    ptr(0.82),
		MostSearchedTerms: `["alpha","beta"]`,
		GrowthRate:        ptr(12.5),
	}
	if err := repo.UpsertCollectionStat(ctx, in); err != nil {
		t.Fatalf("upsert: %v", err)
	}

	got, ok, err := repo.GetCollectionStat(ctx, "vrooli_knowledge")
	if err != nil || !ok {
		t.Fatalf("get: ok=%v err=%v", ok, err)
	}
	if got.TotalEntries != in.TotalEntries || got.TotalSearches != in.TotalSearches {
		t.Errorf("counts = %d/%d, want %d/%d",
			got.TotalEntries, got.TotalSearches, in.TotalEntries, in.TotalSearches)
	}
	if got.AvgSearchScore == nil || *got.AvgSearchScore != 0.82 {
		t.Errorf("avg_search_score = %v, want 0.82", got.AvgSearchScore)
	}
	if got.MostSearchedTerms != in.MostSearchedTerms {
		t.Errorf("most_searched_terms = %q, want %q", got.MostSearchedTerms, in.MostSearchedTerms)
	}
	// growth_rate was DECIMAL(5,2) on Postgres; REAL must not truncate it.
	if got.GrowthRate == nil || *got.GrowthRate != 12.5 {
		t.Errorf("growth_rate = %v, want 12.5", got.GrowthRate)
	}
	if got.LastUpdated.IsZero() || got.CreatedAt.IsZero() {
		t.Errorf("timestamps not defaulted: %v / %v", got.LastUpdated, got.CreatedAt)
	}

	// Second upsert must update in place, not duplicate.
	in.TotalEntries = 121
	if err := repo.UpsertCollectionStat(ctx, in); err != nil {
		t.Fatalf("second upsert: %v", err)
	}
	got, _, err = repo.GetCollectionStat(ctx, "vrooli_knowledge")
	if err != nil {
		t.Fatalf("get after upsert: %v", err)
	}
	if got.TotalEntries != 121 {
		t.Errorf("total_entries = %d, want 121 after upsert", got.TotalEntries)
	}
}

// TestDashboardViewReplacesTheLateralJoin proves the correlated-subquery view is
// equivalent to the Postgres LEFT JOIN LATERAL it replaced: one row per
// collection, carrying that collection's most recent sample.
func TestDashboardViewReplacesTheLateralJoin(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	if err := repo.UpsertCollectionStat(ctx, quality.CollectionStat{
		CollectionName: "alpha", TotalEntries: 10, TotalSearches: 2,
	}); err != nil {
		t.Fatal(err)
	}
	// A collection with stats but no samples must still appear (LEFT JOIN).
	if err := repo.UpsertCollectionStat(ctx, quality.CollectionStat{
		CollectionName: "beta", TotalEntries: 5,
	}); err != nil {
		t.Fatal(err)
	}

	older := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	newer := time.Date(2026, 2, 2, 0, 0, 0, 0, time.UTC)
	for _, m := range []quality.Metric{
		{CollectionName: "alpha", Coherence: ptr(0.1), Freshness: ptr(0.1), Redundancy: ptr(0.1), Coverage: ptr(0.1), MeasuredAt: older},
		{CollectionName: "alpha", Coherence: ptr(0.9), Freshness: ptr(0.9), Redundancy: ptr(0.9), Coverage: ptr(0.9), MeasuredAt: newer},
	} {
		if _, err := repo.InsertMetric(ctx, m); err != nil {
			t.Fatal(err)
		}
	}

	rows, err := repo.Dashboard(ctx)
	if err != nil {
		t.Fatalf("dashboard: %v", err)
	}
	if len(rows) != 2 {
		t.Fatalf("dashboard returned %d rows, want one per collection", len(rows))
	}
	if rows[0].CollectionName != "alpha" {
		t.Fatalf("rows[0] = %q, want alpha", rows[0].CollectionName)
	}
	if rows[0].AvgQuality == nil || *rows[0].AvgQuality != 0.9 {
		t.Errorf("alpha avg_quality = %v, want the newest sample's 0.9", rows[0].AvgQuality)
	}
	if rows[0].MeasuredAt == nil || !rows[0].MeasuredAt.Equal(newer) {
		t.Errorf("alpha measured_at = %v, want %v", rows[0].MeasuredAt, newer)
	}
	if rows[1].CollectionName != "beta" || rows[1].AvgQuality != nil {
		t.Errorf("beta should appear with no sample, got %+v", rows[1])
	}
}

// TestDownsampleKeepsOneRowPerCollectionPerDay is the retention control the
// operator approved: full resolution recently, one row per collection per day
// before the cutoff.
func TestDownsampleKeepsOneRowPerCollectionPerDay(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	day := time.Date(2026, 3, 10, 0, 0, 0, 0, time.UTC)
	// Three samples on one old day for each of two collections, plus one recent.
	for _, collection := range []string{"alpha", "beta"} {
		for h := 0; h < 3; h++ {
			if _, err := repo.InsertMetric(ctx, quality.Metric{
				CollectionName: collection,
				Coherence:      ptr(float64(h) / 10),
				MeasuredAt:     day.Add(time.Duration(h) * time.Hour),
			}); err != nil {
				t.Fatal(err)
			}
		}
	}
	recent := time.Date(2026, 7, 1, 0, 0, 0, 0, time.UTC)
	for h := 0; h < 4; h++ {
		if _, err := repo.InsertMetric(ctx, quality.Metric{
			CollectionName: "alpha",
			MeasuredAt:     recent.Add(time.Duration(h) * time.Hour),
		}); err != nil {
			t.Fatal(err)
		}
	}

	cutoff := time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC)
	deleted, err := repo.DownsampleMetricsOlderThan(ctx, cutoff)
	if err != nil {
		t.Fatalf("downsample: %v", err)
	}
	if deleted != 4 {
		t.Errorf("deleted %d rows, want 4 (2 collections x 2 redundant samples)", deleted)
	}

	total, err := repo.CountMetrics(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if total != 6 {
		t.Errorf("kept %d rows, want 6 (1 per old collection-day + 4 recent)", total)
	}

	// The survivor of each old day must be that day's newest sample.
	got, ok, err := repo.LatestMetric(ctx, "beta")
	if err != nil || !ok {
		t.Fatalf("latest beta: ok=%v err=%v", ok, err)
	}
	if !got.MeasuredAt.UTC().Equal(day.Add(2 * time.Hour)) {
		t.Errorf("beta survivor measured_at = %v, want the day's newest %v",
			got.MeasuredAt.UTC(), day.Add(2*time.Hour))
	}

	// Re-running must be a no-op; the operation has to be safe to schedule.
	deleted, err = repo.DownsampleMetricsOlderThan(ctx, cutoff)
	if err != nil {
		t.Fatalf("second downsample: %v", err)
	}
	if deleted != 0 {
		t.Errorf("second downsample deleted %d rows, want 0", deleted)
	}
}

func TestPruneMetricsOlderThan(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	for _, at := range []time.Time{
		time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC),
		time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC),
	} {
		if _, err := repo.InsertMetric(ctx, quality.Metric{CollectionName: "a", MeasuredAt: at}); err != nil {
			t.Fatal(err)
		}
	}

	deleted, err := repo.PruneMetricsOlderThan(ctx, time.Date(2026, 3, 1, 0, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatalf("prune: %v", err)
	}
	if deleted != 1 {
		t.Errorf("deleted %d, want 1", deleted)
	}
	total, _ := repo.CountMetrics(ctx)
	if total != 1 {
		t.Errorf("remaining %d, want 1", total)
	}
}

// TestInsertMetricIsIdempotentOnExplicitID matters for the Phase 11 migration,
// which supplies the Postgres UUID as the SQLite id so a re-run cannot
// duplicate rows.
func TestInsertMetricIsIdempotentOnExplicitID(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	m := quality.Metric{ID: "fixed-id", CollectionName: "a", MeasuredAt: time.Now().UTC()}
	for i := 0; i < 2; i++ {
		if _, err := repo.InsertMetric(ctx, m); err != nil {
			t.Fatalf("insert %d: %v", i, err)
		}
	}
	total, _ := repo.CountMetrics(ctx)
	if total != 1 {
		t.Errorf("count = %d, want 1 — a re-run must not duplicate", total)
	}
}
