package releases

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"deployment-manager/profiles"
	"deployment-manager/shared"

	"github.com/gorilla/mux"
)

// newReleaseID returns a hex-encoded 16-byte random string. Collisions are
// astronomically unlikely; we avoid a UUID dep just for this.
func newReleaseID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return fmt.Sprintf("rel-%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b[:])
}

// Orchestrator is the seam the handler uses to drive a release through the
// full DM pipeline after allocating a release_id. Keeping this as an interface
// avoids an import cycle between releases <-> deployments.
type Orchestrator interface {
	RunDeploy(ctx context.Context, req DeployRequest) (*DeployResult, error)
}

// DeployRequest is the orchestrator-facing request generated by a release
// start. It mirrors the fields that POST /deploy-desktop consumes, plus the
// fresh release_id and channel that DM now owns.
type DeployRequest struct {
	ProfileID      string
	ReleaseID      string
	Channel        string
	Platforms      []string
	GitCommitHash  string
	ReleaseVersion string
	ReleaseNotes   string
}

// DeployResult is the minimal response surface the release handler needs
// back from the orchestrator.
type DeployResult struct {
	Status            string
	Steps             []Step
	ReleaseID         string
	PublishedVersions []PublishedVersionRef
	VerifyEvidence    []VerificationItem
}

// Step is a single orchestration step summary.
type Step struct {
	Name    string `json:"name"`
	Status  string `json:"status"`
	Message string `json:"message,omitempty"`
	Error   string `json:"error,omitempty"`
}

// PublishedVersionRef is a compact reference to a published-version row.
type PublishedVersionRef struct {
	Platform      string `json:"platform"`
	Version       string `json:"version"`
	GitCommitHash string `json:"git_commit_hash,omitempty"`
	ArtifactID    int64  `json:"artifact_id,omitempty"`
}

// LPBSVerifier is the verify-endpoint seam used by re-verify requests.
type LPBSVerifier interface {
	Verify(ctx context.Context, req *VerifyCall) (*VerifyOutcome, error)
}

// VerifyCall is the input to LPBSVerifier.Verify.
type VerifyCall struct {
	AppKey          string
	Channel         string
	Platform        string
	ExpectedVersion string
	Deep            bool
}

// VerifyOutcome mirrors the LPBS verify response for one platform.
type VerifyOutcome struct {
	AppKey          string `json:"app_key"`
	Channel         string `json:"channel"`
	Platform        string `json:"platform"`
	ExpectedVersion string `json:"expected_version"`
	ObservedVersion string `json:"observed_version,omitempty"`
	SHA512Match     bool   `json:"sha512_match"`
	Match           bool   `json:"match"`
	Error           string `json:"error,omitempty"`
}

// Handler serves the release-lifecycle HTTP routes.
type Handler struct {
	repo       Repository
	lpbsConfig profiles.LPBSReleaseConfigRepository
	verifier   LPBSVerifier
	orch       Orchestrator
	log        func(string, map[string]interface{})
	readiness  func(context.Context, string) (*ReadinessApproval, error)
	promoted   func(context.Context, string, time.Time) error
}

type ReadinessApproval struct {
	Key             string
	Scenario        string
	ProfileID       string
	CandidateCommit string
	ArtifactDigest  string
	Targets         []string
	Channel         string
	PolicyVersion   int
	Status          string
	ApprovedAt      *time.Time
}

// WithReadinessLookup enables the exact candidate/artifact/target/channel
// promotion gate. It is optional only for isolated compatibility tests.
func (h *Handler) WithReadinessLookup(lookup func(context.Context, string) (*ReadinessApproval, error)) *Handler {
	h.readiness = lookup
	return h
}

// WithReadinessPromoter records the terminal lifecycle transition only after
// the release repository confirms publication.
func (h *Handler) WithReadinessPromoter(promote func(context.Context, string, time.Time) error) *Handler {
	h.promoted = promote
	return h
}

// NewHandler wires a new releases handler. The verifier and orchestrator may
// be nil; the handler degrades gracefully for the affected endpoints.
func NewHandler(repo Repository, lpbsConfig profiles.LPBSReleaseConfigRepository, verifier LPBSVerifier, orch Orchestrator, log func(string, map[string]interface{})) *Handler {
	if log == nil {
		log = func(string, map[string]interface{}) {}
	}
	return &Handler{repo: repo, lpbsConfig: lpbsConfig, verifier: verifier, orch: orch, log: log}
}

// ListByProfile handles GET /api/v1/profiles/{id}/releases.
func (h *Handler) ListByProfile(w http.ResponseWriter, r *http.Request) {
	profileID := mux.Vars(r)["id"]
	limit := 50
	if raw := r.URL.Query().Get("limit"); raw != "" {
		if n, err := strconv.Atoi(raw); err == nil && n > 0 && n <= 500 {
			limit = n
		}
	}
	rows, err := h.repo.ListByProfile(r.Context(), profileID, limit)
	if err != nil {
		shared.JSONError(w, fmt.Sprintf("list releases: %v", err), http.StatusInternalServerError)
		return
	}
	shared.JSONOK(w, map[string]interface{}{"releases": rows})
}

// Get handles GET /api/v1/releases/{release_id}.
func (h *Handler) Get(w http.ResponseWriter, r *http.Request) {
	id := mux.Vars(r)["release_id"]
	rel, err := h.repo.Get(r.Context(), id)
	if err != nil {
		shared.JSONError(w, fmt.Sprintf("get release: %v", err), http.StatusNotFound)
		return
	}
	shared.JSONOK(w, rel)
}

// Verify handles POST /api/v1/releases/{release_id}/verify. Re-runs the
// verify call for every platform row and persists the outcome on the release.
func (h *Handler) Verify(w http.ResponseWriter, r *http.Request) {
	if h.verifier == nil {
		shared.JSONError(w, "lpbs verify client not configured", http.StatusServiceUnavailable)
		return
	}
	id := mux.Vars(r)["release_id"]
	rel, err := h.repo.Get(r.Context(), id)
	if err != nil || rel == nil {
		shared.JSONError(w, fmt.Sprintf("release not found: %v", err), http.StatusNotFound)
		return
	}
	cfg, err := h.lpbsConfig.Get(r.Context(), rel.ProfileID)
	if err != nil || cfg == nil || cfg.LPBSAppKey == "" {
		shared.JSONError(w, "lpbs release config missing app_key for profile", http.StatusPreconditionFailed)
		return
	}

	var evidence []VerificationItem
	allMatch := true
	for _, p := range rel.Platforms {
		out, verr := h.verifier.Verify(r.Context(), &VerifyCall{
			AppKey:          cfg.LPBSAppKey,
			Channel:         rel.Channel,
			Platform:        p.Platform,
			ExpectedVersion: rel.ReleaseVersion,
			Deep:            r.URL.Query().Get("deep") == "true",
		})
		item := VerificationItem{
			Platform:        p.Platform,
			Channel:         rel.Channel,
			ExpectedVersion: rel.ReleaseVersion,
			CheckedAt:       time.Now().UTC(),
		}
		if verr != nil {
			item.Error = verr.Error()
			allMatch = false
		} else if out != nil {
			item.ObservedVersion = out.ObservedVersion
			item.Match = out.Match
			item.SHA512Match = out.SHA512Match
			if !out.Match {
				allMatch = false
			}
			if out.Error != "" {
				item.Error = out.Error
			}
		}
		evidence = append(evidence, item)
	}
	if err := h.repo.SetVerificationEvidence(r.Context(), rel.ID, evidence); err != nil {
		shared.JSONError(w, fmt.Sprintf("persist evidence: %v", err), http.StatusInternalServerError)
		return
	}

	status := StatusVerifyFailed
	if allMatch {
		status = StatusPublished
	}
	_ = h.repo.UpdateStatus(r.Context(), rel.ID, status)

	rel.Status = status
	rel.VerificationEvidence = evidence
	shared.JSONOK(w, rel)
}

// Start handles POST /api/v1/profiles/{id}/releases/start. Allocates a
// release_id under the profile-scoped advisory lock, inserts the record,
// then drives the underlying orchestrator to completion. Returns 409 if a
// release is already in flight for the profile.
func (h *Handler) Start(w http.ResponseWriter, r *http.Request) {
	profileID := mux.Vars(r)["id"]
	if h.orch == nil {
		shared.JSONError(w, "orchestrator not configured", http.StatusServiceUnavailable)
		return
	}
	var body StartRequest
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		shared.JSONError(w, fmt.Sprintf("invalid JSON: %v", err), http.StatusBadRequest)
		return
	}
	if body.GitCommitHash == "" {
		shared.JSONError(w, "git_commit_hash is required", http.StatusBadRequest)
		return
	}
	if body.ReleaseVersion == "" {
		shared.JSONError(w, "release_version is required", http.StatusBadRequest)
		return
	}

	cfg, _ := h.lpbsConfig.Get(r.Context(), profileID)
	channel := body.Channel
	if channel == "" {
		if cfg != nil && cfg.DefaultChannel != "" {
			channel = cfg.DefaultChannel
		} else {
			channel = "stable"
		}
	}

	// Acquire the profile-scoped advisory lock. A second caller sees 409.
	acquired, release, err := h.repo.AcquireProfileLock(r.Context(), profileID)
	if err != nil {
		shared.JSONError(w, fmt.Sprintf("acquire profile lock: %v", err), http.StatusInternalServerError)
		return
	}
	if !acquired {
		shared.JSONErrorCode(w, http.StatusConflict, map[string]interface{}{
			"error":      "release_in_flight",
			"profile_id": profileID,
			"message":    "a release is already in progress for this profile",
		})
		return
	}
	defer release()

	platforms := body.Platforms
	if len(platforms) == 0 {
		platforms = []string{"linux-x64", "darwin-arm64", "win-x64"}
	}
	if h.readiness != nil {
		if body.ArtifactDigest == "" || body.ReadinessReviewKey == "" {
			shared.JSONError(w, "artifact_digest and readiness_review_key are required", http.StatusPreconditionFailed)
			return
		}
		review, reviewErr := h.readiness(r.Context(), body.ReadinessReviewKey)
		if reviewErr != nil || review == nil {
			shared.JSONError(w, "approved readiness review was not found", http.StatusPreconditionFailed)
			return
		}
		if review.Key != body.ReadinessReviewKey || review.ProfileID != profileID || review.CandidateCommit != body.GitCommitHash || review.ArtifactDigest != body.ArtifactDigest || review.Channel != channel || !sameStringSet(review.Targets, platforms) || review.Status != "approved" || review.ApprovedAt == nil {
			shared.JSONError(w, "release identity does not have an exact approved readiness review", http.StatusPreconditionFailed)
			return
		}
	}

	releaseID := newReleaseID()
	rel := &Release{
		ID:                 releaseID,
		ProfileID:          profileID,
		GitCommitHash:      body.GitCommitHash,
		ArtifactDigest:     body.ArtifactDigest,
		ReadinessReviewKey: body.ReadinessReviewKey,
		ReleaseVersion:     body.ReleaseVersion,
		Channel:            channel,
		Status:             StatusPending,
		ReleaseNotes:       body.ReleaseNotes,
		ReleasedBy:         body.ReleasedBy,
	}
	for _, p := range platforms {
		rel.Platforms = append(rel.Platforms, ReleasePlatform{Platform: p, Status: PlatformStatusPending})
	}
	if err := h.repo.Insert(r.Context(), rel); err != nil {
		shared.JSONError(w, fmt.Sprintf("insert release: %v", err), http.StatusInternalServerError)
		return
	}

	result, derr := h.orch.RunDeploy(r.Context(), DeployRequest{
		ProfileID:      profileID,
		ReleaseID:      releaseID,
		Channel:        channel,
		Platforms:      platforms,
		GitCommitHash:  body.GitCommitHash,
		ReleaseVersion: body.ReleaseVersion,
		ReleaseNotes:   body.ReleaseNotes,
	})
	if derr != nil {
		_ = h.repo.UpdateStatus(context.WithoutCancel(r.Context()), releaseID, StatusFailed)
		shared.JSONError(w, fmt.Sprintf("orchestrator failed: %v", derr), http.StatusInternalServerError)
		return
	}

	// Re-read and return the final release record so the caller sees
	// verification evidence, platform rows, and the terminal status.
	final, _ := h.repo.Get(r.Context(), releaseID)
	if final == nil {
		shared.JSONOK(w, map[string]interface{}{
			"release_id": releaseID,
			"status":     result.Status,
			"steps":      result.Steps,
		})
		return
	}
	if final.Status == StatusPublished && h.promoted != nil {
		if err := h.promoted(context.WithoutCancel(r.Context()), body.ReadinessReviewKey, time.Now().UTC()); err != nil {
			shared.JSONError(w, fmt.Sprintf("record readiness promotion: %v", err), http.StatusInternalServerError)
			return
		}
	}
	shared.JSONOK(w, map[string]interface{}{
		"release": final,
		"steps":   result.Steps,
	})
}

func sameStringSet(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	counts := make(map[string]int, len(left))
	for _, value := range left {
		counts[value]++
	}
	for _, value := range right {
		if counts[value] == 0 {
			return false
		}
		counts[value]--
	}
	return true
}
