export const SuppFields = {
    Api: ["you"],
    ApiKey: [],
    ApiKeyExternal: [],
    ApiVersion: ["you"],
    Award: ["title", "description"],
    Bookmark: [],
    BookmarkList: [],
    Chat: ["you"],
    ChatInvite: ["you"],
    ChatMessage: ["you"],
    ChatParticipant: [],
    Code: ["you", "translatedName"],
    CodeVersion: ["you"],
    Comment: ["you"],
    Email: [],
    Issue: ["you"],
    Label: ["you"],
    Meeting: ["you"],
    MeetingInvite: ["you"],
    Member: ["you"],
    MemberInvite: ["you"],
    Node: [],
    NodeEnd: [],
    NodeLink: [],
    NodeLinkWhen: [],
    NodeLoop: [],
    NodeLoopWhile: [],
    NodeRoutineList: [],
    NodeRoutineListItem: [],
    Note: ["you"],
    NoteVersion: ["you"],
    Notification: [],
    NotificationSubscription: [],
    Payment: [],
    Phone: [],
    Premium: [],
    Project: ["you", "translatedName"],
    ProjectVersion: ["you"],
    ProjectVersionDirectory: [],
    PullRequest: ["you"],
    PushDevice: [],
    Reaction: [],
    ReactionSummary: [],
    Reminder: [],
    ReminderItem: [],
    ReminderList: [],
    Report: ["you"],
    ReportResponse: ["you"],
    Resource: [],
    ResourceList: [],
    Role: [],
    Routine: ["you", "translatedName"],
    RoutineVersion: ["you"],
    RoutineVersionInput: [],
    RoutineVersionOutput: [],
    RunProject: ["lastStep", "you"],
    RunProjectStep: [],
    RunRoutine: ["lastStep", "you"],
    RunRoutineIO: [],
    RunRoutineStep: [],
    Schedule: [],
    ScheduleException: [],
    ScheduleRecurrence: [],
    Session: [],
    Standard: ["you", "translatedName"],
    StandardVersion: ["you"],
    StatsApi: [],
    StatsCode: [],
    StatsProject: [],
    StatsRoutine: [],
    StatsSite: [],
    StatsStandard: [],
    StatsTeam: [],
    StatsUser: [],
    Tag: ["you"],
    Team: ["you", "translatedName"],
    Transfer: [],
    User: ["you"],
    View: [],
    Wallet: [],
} as const;
