export const SuppFields = {
    ApiKey: [],
    ApiKeyExternal: [],
    Award: ["title", "description"],
    Bookmark: [],
    BookmarkList: [],
    Chat: ["you"],
    ChatInvite: ["you"],
    ChatMessage: ["you"],
    ChatParticipant: [],
    Comment: ["you"],
    Email: [],
    Issue: ["you"],
    Meeting: ["you"],
    MeetingInvite: ["you"],
    Member: ["you"],
    MemberInvite: ["you"],
    Notification: [],
    NotificationSubscription: [],
    Payment: [],
    Phone: [],
    PullRequest: ["you"],
    PushDevice: [],
    Reaction: [],
    ReactionSummary: [],
    Reminder: [],
    ReminderItem: [],
    ReminderList: [],
    Report: ["you"],
    ReportResponse: ["you"],
    Resource: [],
    ResourceVersion: ["you"],
    ResourceVersionRelation: [],
    Role: [],
    Run: ["lastStep", "you"],
    RunIO: [],
    RunStep: [],
    Schedule: [],
    ScheduleException: [],
    ScheduleRecurrence: [],
    StatsResource: [],
    StatsSite: [],
    StatsTeam: [],
    StatsUser: [],
    Tag: ["you"],
    Team: ["you", "translatedName"],
    Transfer: [],
    User: ["you"],
    View: [],
    Wallet: [],
} as const;
