import { cleanup, fireEvent, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useEffect } from "react";
import { Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { renderWithProviders, createTestQueryClient } from "../../../test-utils";
import type { QueryClient } from "@tanstack/react-query";
import { useOperationsStore } from "../../../stores/operations-store";
import { createPlanDataInitialState, resetPlanRequestState, usePlanDataStore } from "../stores/plan-data-store";
import { usePlanUrlState } from "./usePlanUrlState";
const observed=vi.fn();let unexpected:string[]=[];const clients:QueryClient[]=[];
function Probe(){const l=useLocation();useEffect(()=>observed({pathname:l.pathname,search:l.search,key:l.key}),[l]);return <output data-testid="url">{l.pathname+l.search}</output>;}
function Consumer(){const state=usePlanUrlState();const navigate=useNavigate();return <><output data-testid="state">{state.goal}|{state.filters.q}|{state.viewMode}|{String(state.showSnoozed)}</output><button onClick={()=>state.setFilters({q:"changed owner"})}>Change filter</button><button onClick={()=>state.setGoal("other-goal")}>Change goal</button><button onClick={()=>state.setShowSnoozed(true)}>Show snoozed</button><button onClick={()=>navigate("/plan?goal=url-owner&q=from-url&keep=fixture")}>Open URL owner</button><button onClick={()=>navigate(-1)}>Back</button><button onClick={()=>navigate(1)}>Forward</button><button onClick={()=>navigate("/graph?focus=backlog-item%2Ffix%2Fmissing&select=backlog-item%2Ffix%2Fmissing")}>Open graph</button></>;}
function mount(path="/plan?keep=fixture"){const queryClient=createTestQueryClient();clients.push(queryClient);return renderWithProviders(<><Routes><Route path="/plan" element={<Consumer/>}/><Route path="*" element={<div>Destination</div>}/></Routes><Probe/></>,{queryClient,initialEntries:[path]});}
beforeEach(()=>{observed.mockClear();unexpected=[];resetPlanRequestState();useOperationsStore.getState().reset();usePlanDataStore.setState({...createPlanDataInitialState()});vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const req=new Request(input,init);if(req.method!=="GET"||new URL(req.url).pathname!=="/api/v1/plan"){unexpected.push(req.method+" "+req.url);throw new Error("Unexpected URL state request");}return new Response(JSON.stringify({}),{headers:{"content-type":"application/json"}});}));});
afterEach(()=>{cleanup();clients.splice(0).forEach(c=>c.clear());resetPlanRequestState();useOperationsStore.getState().reset();usePlanDataStore.setState({...createPlanDataInitialState()});vi.unstubAllGlobals();expect(unexpected).toEqual([]);});
describe("real Plan URL navigation synchronization",()=>{
 it("does not replace a canonical unchanged location merely to mirror existing stores",async()=>{mount();await waitFor(()=>expect(screen.getByTestId("state")).toHaveTextContent("||by-milestone|false"));expect(observed.mock.calls.map(([l])=>l.key)).toEqual(["default"]);expect(screen.getByTestId("url")).toHaveTextContent("/plan?keep=fixture");});
 it("writes only explicitly changed filter while preserving unrelated query fields",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Change filter"}));await waitFor(()=>expect(new URL(screen.getByTestId("url").textContent!,"http://fixture.invalid").searchParams.get("q")).toBe("changed owner"));const url=new URL(screen.getByTestId("url").textContent!,"http://fixture.invalid");expect(url.pathname).toBe("/plan");expect(url.searchParams.get("keep")).toBe("fixture");expect(useOperationsStore.getState().filters.q).toBe("changed owner");});
 it("preserves exact goal and snooze changes with the same owner URL",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Change goal"}));await waitFor(()=>expect(screen.getByTestId("url")).toHaveTextContent("goal=other-goal"));fireEvent.click(screen.getByRole("button",{name:"Show snoozed"}));await waitFor(()=>expect(screen.getByTestId("url")).toHaveTextContent("show_snoozed=1"));expect(screen.getByTestId("url")).toHaveTextContent("keep=fixture");expect(usePlanDataStore.getState().goal).toBe("other-goal");});
 it("adopts a changed URL owner's filters instead of overwriting them with stale stores",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Open URL owner"}));await waitFor(()=>expect(screen.getByTestId("state")).toHaveTextContent("url-owner|from-url|by-milestone|false"));expect(screen.getByTestId("url")).toHaveTextContent("goal=url-owner&q=from-url&keep=fixture");expect(usePlanDataStore.getState().goal).toBe("url-owner");expect(useOperationsStore.getState().filters.q).toBe("from-url");});
 it("keeps an explicit graph destination and both exact subject references",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Open graph"}));await screen.findByText("Destination");const url=new URL(screen.getByTestId("url").textContent!,"http://fixture.invalid");expect(url.pathname).toBe("/graph");expect(url.searchParams.get("focus")).toBe("backlog-item/fix/missing");expect(url.searchParams.get("select")).toBe("backlog-item/fix/missing");});
 it("preserves browser back and forward across an exact URL-owned goal and filter",async()=>{mount();fireEvent.click(screen.getByRole("button",{name:"Open URL owner"}));await waitFor(()=>expect(screen.getByTestId("state")).toHaveTextContent("url-owner|from-url|by-milestone|false"));fireEvent.click(screen.getByRole("button",{name:"Back"}));await waitFor(()=>expect(screen.getByTestId("state")).toHaveTextContent("||by-milestone|false"));expect(screen.getByTestId("url")).toHaveTextContent("/plan?keep=fixture");fireEvent.click(screen.getByRole("button",{name:"Forward"}));await waitFor(()=>expect(screen.getByTestId("state")).toHaveTextContent("url-owner|from-url|by-milestone|false"));expect(screen.getByTestId("url")).toHaveTextContent("goal=url-owner&q=from-url&keep=fixture");});

});
