import { librarySelectors } from "./selectors.library";
export { librarySelectors };
/** Application selector definitions. Shared behavior lives in @vrooli/ui-selectors.
 * Run selector:manifest after editing these maps; UI builds regenerate the manifest.
 */
import { LOCALE_CODES } from "../i18n/locales";

import { createSelectorRegistry, defineDynamicSelector, type LiteralSelectorTree, type DynamicSelectorTree } from "@vrooli/ui-selectors";
export { createSelectorRegistry, defineDynamicSelector } from "@vrooli/ui-selectors";

const literalSelectors = {
  app: {
    title: "app-title",
    eyebrow: "app-eyebrow",
    description: "app-description",
  },
  health: {
    card: "health-card",
    statusBadge: "health-status-badge",
    loading: "health-loading",
    error: "health-error",
    statusValue: "health-status-value",
    serviceValue: "health-service-value",
    timestampValue: "health-timestamp-value",
    refreshButton: "health-refresh-button",
    refreshCount: "health-refresh-count",
  },
  notifications: {
    summary: "notifications-summary",
  },
  // Shared query-state primitive (loading / error / empty) — reused by every surface.
  queryState: {
    loading: "query-state-loading",
    error: "query-state-error",
    empty: "query-state-empty",
  },
  overview: {
    page: "overview-page",
    readinessCard: "overview-readiness-card",
    readinessStatus: "overview-readiness-status",
    modeBadge: "overview-mode-badge",
    missingFields: "overview-missing-fields",
    tunnelCard: "overview-tunnel-card",
    tunnelStatus: "overview-tunnel-status",
    tunnelScore: "overview-tunnel-score",
    exposureCard: "overview-exposure-card",
    coreCount: "overview-core-count",
    leasedCount: "overview-leased-count",
    recoveryCard: "overview-recovery-card",
    recoveryStatus: "overview-recovery-status",
    circuitWarning: "overview-circuit-warning",
    modeCallout: "overview-mode-callout",
    driftCard: "overview-drift-card",
    driftManaged: "overview-drift-managed",
    driftExternal: "overview-drift-external",
    driftUnmanaged: "overview-drift-unmanaged",
    constellation: "overview-exposure-constellation",
    constellationError: "overview-constellation-error",
    constellationRetry: "overview-constellation-retry",
    mobileTopology: "overview-mobile-topology",
    mobileRoute: "overview-mobile-route",
    mobileTopologyError: "overview-mobile-topology-error",
    finding: "overview-actionable-finding",
  },
  drift: {
    panel: "drift-panel",
    summary: "drift-summary",
    modeHint: "drift-mode-hint",
    refreshButton: "drift-refresh-button",
    table: "drift-table",
    row: "drift-row",
    hostname: "drift-hostname",
    target: "drift-target",
    stateBadge: "drift-state-badge",
    sourceBadge: "drift-source-badge",
    actionError: "drift-action-error",
    confirmDialog: "drift-confirm-dialog",
    confirmButton: "drift-confirm-button",
    cancelButton: "drift-cancel-button",
  },
  routes: {
    panel: "routes-panel",
    addForm: "routes-add-form",
    subdomainInput: "routes-subdomain-input",
    targetInput: "routes-target-input",
    domainInput: "routes-domain-input",
    publicExposureSelect: "routes-public-exposure-select",
    addButton: "routes-add-button",
    addError: "routes-add-error",
    table: "routes-table",
    row: "routes-row",
    sourceBadge: "routes-source-badge",
    publicExposureBadge: "routes-public-exposure-badge",
    publicExposureError: "routes-public-exposure-error",
    url: "routes-url",
    deleteButton: "routes-delete-button",
    deleteError: "routes-delete-error",
  },
  access: {
    panel: "access-panel",
    summary: "access-summary",
    globalBadge: "access-global-badge",
    configuredBadge: "access-configured-badge",
    note: "access-note",
    refreshButton: "access-refresh-button",
    planCreate: "access-plan-create",
    planRemove: "access-plan-remove",
    table: "access-table",
    row: "access-row",
    hostName: "access-host-name",
    overrideBadge: "access-override-badge",
    bypassBadge: "access-bypass-badge",
    managedBadge: "access-managed-badge",
    appId: "access-app-id",
  },
  exposure: {
    panel: "exposure-panel",
    summary: "exposure-summary",
    coreCount: "exposure-core-count",
    leasedCount: "exposure-leased-count",
    unhealthyCount: "exposure-unhealthy-count",
    searchInput: "exposure-search-input",
    tierFilter: "exposure-tier-filter",
    reconcileButton: "exposure-reconcile-button",
    reconcileResult: "exposure-reconcile-result",
    table: "exposure-table",
    row: "exposure-row",
    tierBadge: "exposure-tier-badge",
    healthBadge: "exposure-health-badge",
    url: "exposure-url",
    leaseExpiry: "exposure-lease-expiry",
    exposeForm: "exposure-expose-form",
    exposeInput: "exposure-expose-input",
    exposeButton: "exposure-expose-button",
    exposeError: "exposure-expose-error",
    extendButton: "exposure-extend-button",
    revokeButton: "exposure-revoke-button",
    actionError: "exposure-action-error",
    refreshButton: "exposure-refresh-button",
    reviewDialog: "exposure-review-dialog",
    durationSelect: "exposure-duration-select",
    customDurationInput: "exposure-custom-duration-input",
    confirmExposeButton: "exposure-confirm-expose-button",
    cancelExposeButton: "exposure-cancel-expose-button",
    healthFilter: "exposure-health-filter",
    leaseFilter: "exposure-lease-filter",
    policyFilter: "exposure-policy-filter",
    readinessFilter: "exposure-readiness-filter",
    detailDialog: "exposure-detail-dialog",
    detailCloseButton: "exposure-detail-close-button",
    detailProbeButton: "exposure-detail-probe-button",
    detailCopyButton: "exposure-detail-copy-button",
    detailExtendButton: "exposure-detail-extend-button",
    detailRevokeButton: "exposure-detail-revoke-button",
    policyAcknowledgement: "exposure-policy-acknowledgement",
    revokeConfirmButton: "exposure-revoke-confirm-button",
    expiredPanel: "exposure-expired-panel",
    reExposeButton: "exposure-re-expose-button",
    verifyResultButton: "exposure-verify-result-button",
  },
  recovery: {
    statePanel: "recovery-state-panel",
    summary: "recovery-summary",
    statusValue: "recovery-status-value",
    circuitValue: "recovery-circuit-value",
    nextAction: "recovery-next-action",
    policyNote: "recovery-policy-note",
    timeline: "recovery-timeline",
    timelineRow: "recovery-timeline-row",
    eventDetails: "recovery-event-details",
    recoverButton: "recovery-recover-button",
    forceToggle: "recovery-force-toggle",
    forceWarning: "recovery-force-warning",
    confirmDialog: "recovery-confirm-dialog",
    confirmButton: "recovery-confirm-button",
    cancelButton: "recovery-cancel-button",
    actionError: "recovery-action-error",
    refreshButton: "recovery-refresh-button",
  },
  metrics: {
    panel: "metrics-panel",
    summary: "metrics-summary",
    table: "metrics-table",
    row: "metrics-row",
    latest: "metrics-latest",
    scrapeButton: "metrics-scrape-button",
    scrapeActionFeedback: "metrics-scrape-action-feedback",
    probesActionFeedback: "metrics-probes-action-feedback",
    probesPanel: "metrics-probes-panel",
    probesTable: "metrics-probes-table",
    probesRow: "metrics-probes-row",
    runProbesButton: "metrics-run-probes-button",
    classifiedCount: "metrics-classified-count",
    classification: "metrics-classification",
    classCount: "metrics-class-count",
    limitation: "metrics-limitation",
  },
  audit: {
    panel: "audit-panel",
    summary: "audit-summary",
    table: "audit-table",
    row: "audit-row",
    statusBadge: "audit-status-badge",
    violationCount: "audit-violation-count",
    statusFilter: "audit-status-filter",
    remediation: "audit-remediation",
    runButton: "audit-run-button",
  },
  locale: {
    switcher: "locale-switcher",
  },
  layout: {
    shell: "layout-shell",
    topBar: "layout-top-bar",
    sidebar: "layout-sidebar",
    bottomNav: "layout-bottom-nav",
    main: "layout-main",
  },
  theme: {
    switcher: "theme-switcher",
    select: "theme-select",
  },
  pages: {
    overview: "page-overview",
    exposure: "page-exposure",
    recovery: "page-recovery",
    metrics: "page-metrics",
    audit: "page-audit",
    drift: "page-drift",
    settings: "page-settings",
  },
  settingsPage: {
    configPanel: "settings-config-panel",
    currentMode: "settings-current-mode",
    remoteAvailable: "settings-remote-available",
    credentialSource: "settings-credential-source",
    syncReady: "settings-sync-ready",
    missingFields: "settings-missing-fields",
    credentialsForm: "settings-credentials-form",
    accountIdInput: "settings-account-id-input",
    tunnelIdInput: "settings-tunnel-id-input",
    apiTokenInput: "settings-api-token-input",
    credentialsSaveButton: "settings-credentials-save-button",
    credentialsClearButton: "settings-credentials-clear-button",
    credentialPolicy: "settings-credential-policy",
    credentialNextAction: "settings-credential-next-action",
    credentialShadowWarning: "settings-credential-shadow-warning",
    credentialFields: "settings-credential-fields",
    credentialVerification: "settings-credential-verification",
    credentialVerificationButton: "settings-credential-verification-button",
    credentialVerificationResult: "settings-credential-verification-result",
    credentialVerificationCheck: "settings-credential-verification-check",
    localModeButton: "settings-local-mode-button",
    remoteModeButton: "settings-remote-mode-button",
    syncDryRunButton: "settings-sync-dry-run-button",
    syncApplyButton: "settings-sync-apply-button",
    syncResult: "settings-sync-result",
    actionError: "settings-action-error",
    switchModeNote: "settings-switch-mode-note",
    reconcileNowButton: "settings-reconcile-now-button",
    reconcileResult: "settings-reconcile-result",
    reviewDriftLink: "settings-review-drift-link",
    publicExposurePanel: "settings-public-exposure-panel",
    publicExposureState: "settings-public-exposure-state",
    publicExposureToggle: "settings-public-exposure-toggle",
    publicExposureStatusLink: "settings-public-exposure-status-link",
  },
  errorBoundary: {
    root: "error-boundary-root",
    retryButton: "error-boundary-retry",
  },
} satisfies LiteralSelectorTree;

// Per-locale toggle test IDs are emitted by `locale.toggle({ code })` below.
// We deliberately do NOT also declare static `toggleEn` / `toggleJa` literals —
// the dynamic form is the single source of truth, and duplicating it here would
// drift the moment a new locale is added to LOCALE_CODES.
//
// `code` is constrained to `LOCALE_CODES` so `selectors.locale.toggle({ code: "fr" })`
// is a TypeScript error when "fr" isn't a supported locale. The runtime enum
// validation in `normalizeParams` provides the same guarantee at call time.
const dynamicSelectorDefinitions = {
  locale: {
    toggle: defineDynamicSelector({
      description: "Locale toggle button by language code",
      testIdPattern: "locale-toggle-${code}",
      params: { code: { type: "enum", values: LOCALE_CODES } },
    }),
  },
  layout: {
    sidebarLink: defineDynamicSelector({
      description: "Sidebar navigation link by canonical nav key",
      testIdPattern: "layout-sidebar-link-${key}",
      params: {
        key: {
          type: "enum",
          values: [
            "overview",
            "exposure",
            "recovery",
            "metrics",
            "audit",
            "drift",
            "settings",
          ] as const,
        },
      },
    }),
    bottomNavLink: defineDynamicSelector({
      description: "Bottom-nav link by canonical nav key",
      testIdPattern: "layout-bottom-nav-link-${key}",
      params: {
        key: {
          type: "enum",
          values: [
            "overview",
            "exposure",
            "recovery",
            "metrics",
            "audit",
            "drift",
            "settings",
          ] as const,
        },
      },
    }),
  },
  settingsPage: {
    themeOption: defineDynamicSelector({
      description: "Theme choice radio button on the settings page",
      testIdPattern: "page-settings-theme-${choice}",
      params: { choice: { type: "enum", values: ["light", "dark", "system"] as const } },
    }),
    localeOption: defineDynamicSelector({
      description: "Locale choice radio button on the settings page",
      testIdPattern: "page-settings-locale-${code}",
      params: { code: { type: "enum", values: LOCALE_CODES } },
    }),
  },
  routes: {
    publicExposureRowSelect: defineDynamicSelector({
      description: "Per-route public-exposure override select, by route id",
      testIdPattern: "routes-public-exposure-row-select-${id}",
      params: { id: { type: "string" } },
    }),
  },
  drift: {
    adoptButton: defineDynamicSelector({
      description: "Adopt action button for a drift row, by hostname",
      testIdPattern: "drift-adopt-${hostname}",
      params: { hostname: { type: "string" } },
    }),
    ignoreButton: defineDynamicSelector({
      description: "Ignore action button for a drift row, by hostname",
      testIdPattern: "drift-ignore-${hostname}",
      params: { hostname: { type: "string" } },
    }),
    pruneButton: defineDynamicSelector({
      description: "Prune action button for a drift row, by hostname",
      testIdPattern: "drift-prune-${hostname}",
      params: { hostname: { type: "string" } },
    }),
  },
} satisfies DynamicSelectorTree;

const registry = createSelectorRegistry(literalSelectors, dynamicSelectorDefinitions, librarySelectors);

export const selectors = registry.selectors;
export type Selectors = typeof selectors;
export const selectorsManifest = registry.manifest;
