// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    navGroup: {
      operations: "layout.navGroup.operations",
      diagnostics: "layout.navGroup.diagnostics",
      governance: "layout.navGroup.governance",
      settings: "layout.navGroup.settings",
    },
    nav: {
      overview: "layout.nav.overview",
      exposure: "layout.nav.exposure",
      recovery: "layout.nav.recovery",
      metrics: "layout.nav.metrics",
      audit: "layout.nav.audit",
      drift: "layout.nav.drift",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  common: {
    loading: "common.loading",
    empty: "common.empty",
    refresh: "common.refresh",
    never: "common.never",
    notAvailable: "common.notAvailable",
  },
  pages: {
    overview: {
      title: "pages.overview.title",
      description: "pages.overview.description",
    },
    exposure: {
      title: "pages.exposure.title",
      description: "pages.exposure.description",
    },
    recovery: {
      title: "pages.recovery.title",
      description: "pages.recovery.description",
    },
    metrics: {
      title: "pages.metrics.title",
      description: "pages.metrics.description",
    },
    audit: {
      title: "pages.audit.title",
      description: "pages.audit.description",
    },
    drift: {
      title: "pages.drift.title",
      description: "pages.drift.description",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  overview: {
    readinessHeading: "overview.readinessHeading",
    readinessReady: "overview.readinessReady",
    readinessSetupRequired: "overview.readinessSetupRequired",
    readinessFallback: "overview.readinessFallback",
    configure: "overview.configure",
    tunnelHeading: "overview.tunnelHeading",
    scoreLabel: "overview.scoreLabel",
    exposureHeading: "overview.exposureHeading",
    coreLabel: "overview.coreLabel",
    leasedLabel: "overview.leasedLabel",
    recoveryHeading: "overview.recoveryHeading",
    circuitOpenWarning: "overview.circuitOpenWarning",
    viewExposure: "overview.viewExposure",
    viewRecovery: "overview.viewRecovery",
    modeLocal: "overview.modeLocal",
    modeLocalKeysConfigured: "overview.modeLocalKeysConfigured",
    modeRemote: "overview.modeRemote",
    driftHeading: "overview.driftHeading",
    driftManaged: "overview.driftManaged",
    driftExternal: "overview.driftExternal",
    driftUnmanaged: "overview.driftUnmanaged",
    viewDrift: "overview.viewDrift",
    urlStateLive: "overview.urlStateLive",
    urlStateDesired: "overview.urlStateDesired",
  },
  config: {
    setupHeading: "config.setupHeading",
    setupDescription: "config.setupDescription",
    loading: "config.loading",
    error: "config.error",
    mode: {
      local: "config.mode.local",
      remote: "config.mode.remote",
      unspecified: "config.mode.unspecified",
    },
    currentMode: "config.currentMode",
    remoteAvailability: "config.remoteAvailability",
    credentialSource: "config.credentialSource",
    credentialRef: "config.credentialRef",
    syncReadiness: "config.syncReadiness",
    tunnelId: "config.tunnelId",
    accountId: "config.accountId",
    localConfigPath: "config.localConfigPath",
    metricsEndpoint: "config.metricsEndpoint",
    available: "config.available",
    unavailable: "config.unavailable",
    ready: "config.ready",
    setupRequired: "config.setupRequired",
    none: "config.none",
    notSet: "config.notSet",
    missingFields: "config.missingFields",
    credentialsHeading: "config.credentialsHeading",
    credentialsDescription: "config.credentialsDescription",
    credentialPolicyTitle: "config.credentialPolicyTitle",
    credentialPolicyBody: "config.credentialPolicyBody",
    cloudflareTokenHelp: "config.cloudflareTokenHelp",
    apiTokenHelp: "config.apiTokenHelp",
    nextActionMissing: "config.nextActionMissing",
    nextActionUnavailable: "config.nextActionUnavailable",
    nextActionReady: "config.nextActionReady",
    nextActionRemote: "config.nextActionRemote",
    credentialReadOnlyWarning: "config.credentialReadOnlyWarning",
    apiToken: "config.apiToken",
    saveCredentials: "config.saveCredentials",
    clearCredentials: "config.clearCredentials",
    credentialSaved: "config.credentialSaved",
    credentialCleared: "config.credentialCleared",
    credentialFields: "config.credentialFields",
    credentialFieldStatus: "config.credentialFieldStatus",
    credentialPresent: "config.credentialPresent",
    credentialMissing: "config.credentialMissing",
    credentialWritable: "config.credentialWritable",
    credentialReadOnly: "config.credentialReadOnly",
    useLocalMode: "config.useLocalMode",
    useRemoteMode: "config.useRemoteMode",
    syncDryRun: "config.syncDryRun",
    syncApply: "config.syncApply",
    syncSetupRequired: "config.syncSetupRequired",
    syncNoChanges: "config.syncNoChanges",
    syncChanged: "config.syncChanged",
    switchModeNote: "config.switchModeNote",
    reconcileHeading: "config.reconcileHeading",
    reconcileNow: "config.reconcileNow",
    reconcileResult: "config.reconcileResult",
    reviewDrift: "config.reviewDrift",
    publicExposureHeading: "config.publicExposureHeading",
    publicExposureBody: "config.publicExposureBody",
    publicExposureOn: "config.publicExposureOn",
    publicExposureOff: "config.publicExposureOff",
    publicExposureEnable: "config.publicExposureEnable",
    publicExposureDisable: "config.publicExposureDisable",
    publicExposureViewStatus: "config.publicExposureViewStatus",
  },
  exposure: {
    heading: "exposure.heading",
    loading: "exposure.loading",
    error: "exposure.error",
    empty: "exposure.empty",
    filteredEmpty: "exposure.filteredEmpty",
    summary: "exposure.summary",
    unhealthySummary: "exposure.unhealthySummary",
    unhealthySummary_one: "exposure.unhealthySummary_one",
    unhealthySummary_zero: "exposure.unhealthySummary_zero",
    searchLabel: "exposure.searchLabel",
    searchPlaceholder: "exposure.searchPlaceholder",
    tierFilterLabel: "exposure.tierFilterLabel",
    tierFilterAll: "exposure.tierFilterAll",
    tierFilterCore: "exposure.tierFilterCore",
    tierFilterLeased: "exposure.tierFilterLeased",
    reconcileButton: "exposure.reconcileButton",
    reconcileResult: "exposure.reconcileResult",
    colScenario: "exposure.colScenario",
    colTier: "exposure.colTier",
    colHealth: "exposure.colHealth",
    colUrl: "exposure.colUrl",
    colPort: "exposure.colPort",
    colLease: "exposure.colLease",
    colActions: "exposure.colActions",
    tier: {
      core: "exposure.tier.core",
      leased: "exposure.tier.leased",
      unknown: "exposure.tier.unknown",
    },
    leaseActive: "exposure.leaseActive",
    leaseNone: "exposure.leaseNone",
    durationHour: "exposure.durationHour",
    durationDay: "exposure.durationDay",
    durationWeek: "exposure.durationWeek",
    healthUnknown: "exposure.healthUnknown",
    exposeHeading: "exposure.exposeHeading",
    exposePlaceholder: "exposure.exposePlaceholder",
    exposeButton: "exposure.exposeButton",
    extendButton: "exposure.extendButton",
    revokeButton: "exposure.revokeButton",
    actionError: "exposure.actionError",
  },
  recovery: {
    stateHeading: "recovery.stateHeading",
    summaryHeading: "recovery.summaryHeading",
    summaryHealthy: "recovery.summaryHealthy",
    summaryFailure: "recovery.summaryFailure",
    summaryCircuitOpen: "recovery.summaryCircuitOpen",
    summaryRecovering: "recovery.summaryRecovering",
    nextActionHealthy: "recovery.nextActionHealthy",
    nextActionFailure: "recovery.nextActionFailure",
    nextActionCircuitOpen: "recovery.nextActionCircuitOpen",
    nextActionRecovering: "recovery.nextActionRecovering",
    policyNote: "recovery.policyNote",
    loading: "recovery.loading",
    error: "recovery.error",
    statusLabel: "recovery.statusLabel",
    consecFailuresLabel: "recovery.consecFailuresLabel",
    backoffLabel: "recovery.backoffLabel",
    failedRecoveriesLabel: "recovery.failedRecoveriesLabel",
    lastCheckLabel: "recovery.lastCheckLabel",
    lastRecoveryLabel: "recovery.lastRecoveryLabel",
    nextRetryLabel: "recovery.nextRetryLabel",
    circuitOpenLabel: "recovery.circuitOpenLabel",
    circuitOpen: "recovery.circuitOpen",
    circuitClosed: "recovery.circuitClosed",
    status: {
      idle: "recovery.status.idle",
      monitoring: "recovery.status.monitoring",
      recovering: "recovery.status.recovering",
      circuitOpen: "recovery.status.circuitOpen",
      unknown: "recovery.status.unknown",
    },
    timelineHeading: "recovery.timelineHeading",
    timelineEmpty: "recovery.timelineEmpty",
    timelineError: "recovery.timelineError",
    colTrigger: "recovery.colTrigger",
    colAction: "recovery.colAction",
    colOutcome: "recovery.colOutcome",
    colAttempt: "recovery.colAttempt",
    colDetails: "recovery.colDetails",
    colWhen: "recovery.colWhen",
    outcome: {
      success: "recovery.outcome.success",
      failure: "recovery.outcome.failure",
      skipped: "recovery.outcome.skipped",
      unknown: "recovery.outcome.unknown",
    },
    recoverButton: "recovery.recoverButton",
    recoverForce: "recovery.recoverForce",
    forceWarning: "recovery.forceWarning",
    recoverConfirmTitle: "recovery.recoverConfirmTitle",
    recoverConfirmBody: "recovery.recoverConfirmBody",
    recoverConfirm: "recovery.recoverConfirm",
    recoverCancel: "recovery.recoverCancel",
    recoverError: "recovery.recoverError",
  },
  metrics: {
    heading: "metrics.heading",
    loading: "metrics.loading",
    error: "metrics.error",
    empty: "metrics.empty",
    scrapeButton: "metrics.scrapeButton",
    latestHaConnections: "metrics.latestHaConnections",
    latestRequestErrors: "metrics.latestRequestErrors",
    latestRtt: "metrics.latestRtt",
    latestScrape: "metrics.latestScrape",
    colTime: "metrics.colTime",
    colHaConnections: "metrics.colHaConnections",
    colActiveStreams: "metrics.colActiveStreams",
    colRequestErrors: "metrics.colRequestErrors",
    colRtt: "metrics.colRtt",
    probesHeading: "metrics.probesHeading",
    probesEmpty: "metrics.probesEmpty",
    probesError: "metrics.probesError",
    runProbesButton: "metrics.runProbesButton",
    classifiedRoutes: "metrics.classifiedRoutes",
    routesNeedingAttention: "metrics.routesNeedingAttention",
    latestProbe: "metrics.latestProbe",
    classificationScope: "metrics.classificationScope",
    colRoute: "metrics.colRoute",
    colKind: "metrics.colKind",
    colStatus: "metrics.colStatus",
    colLatency: "metrics.colLatency",
    kind: {
      internal: "metrics.kind.internal",
      external: "metrics.kind.external",
      unknown: "metrics.kind.unknown",
    },
    probeStatus: {
      up: "metrics.probeStatus.up",
      down: "metrics.probeStatus.down",
      timeout: "metrics.probeStatus.timeout",
      error: "metrics.probeStatus.error",
      unknown: "metrics.probeStatus.unknown",
    },
    classificationHeading: "metrics.classificationHeading",
    class: {
      healthy: "metrics.class.healthy",
      tunnelDown: "metrics.class.tunnelDown",
      scenarioDown: "metrics.class.scenarioDown",
      cloudflareOutage: "metrics.class.cloudflareOutage",
      dnsFailure: "metrics.class.dnsFailure",
      configDrift: "metrics.class.configDrift",
      unknown: "metrics.class.unknown",
    },
  },
  audit: {
    heading: "audit.heading",
    loading: "audit.loading",
    error: "audit.error",
    empty: "audit.empty",
    runButton: "audit.runButton",
    totalRoutes: "audit.totalRoutes",
    compliantRoutes: "audit.compliantRoutes",
    routesToFix: "audit.routesToFix",
    filterLabel: "audit.filterLabel",
    filterEmpty: "audit.filterEmpty",
    violations: "audit.violations",
    violations_zero: "audit.violations_zero",
    violations_one: "audit.violations_one",
    colScenario: "audit.colScenario",
    colSubdomain: "audit.colSubdomain",
    colExpected: "audit.colExpected",
    colActual: "audit.colActual",
    colStatus: "audit.colStatus",
    colDetail: "audit.colDetail",
    colRemediation: "audit.colRemediation",
    filter: {
      all: "audit.filter.all",
      violations: "audit.filter.violations",
      compliant: "audit.filter.compliant",
      mismatch: "audit.filter.mismatch",
      missingScenario: "audit.filter.missingScenario",
      missingPort: "audit.filter.missingPort",
    },
    status: {
      compliant: "audit.status.compliant",
      mismatch: "audit.status.mismatch",
      missingScenario: "audit.status.missingScenario",
      missingPort: "audit.status.missingPort",
      unknown: "audit.status.unknown",
    },
    remediation: {
      compliant: "audit.remediation.compliant",
      mismatch: "audit.remediation.mismatch",
      missingScenario: "audit.remediation.missingScenario",
      missingPort: "audit.remediation.missingPort",
      unknown: "audit.remediation.unknown",
    },
  },
  drift: {
    heading: "drift.heading",
    summary: "drift.summary",
    loading: "drift.loading",
    error: "drift.error",
    empty: "drift.empty",
    modeHint: "drift.modeHint",
    colHostname: "drift.colHostname",
    colTarget: "drift.colTarget",
    colState: "drift.colState",
    colSource: "drift.colSource",
    colActions: "drift.colActions",
    adoptButton: "drift.adoptButton",
    ignoreButton: "drift.ignoreButton",
    pruneButton: "drift.pruneButton",
    actionError: "drift.actionError",
    pruneConfirmTitle: "drift.pruneConfirmTitle",
    pruneConfirmBody: "drift.pruneConfirmBody",
    pruneConfirm: "drift.pruneConfirm",
    pruneCancel: "drift.pruneCancel",
    state: {
      managed: "drift.state.managed",
      missing: "drift.state.missing",
      externalOk: "drift.state.externalOk",
      orphaned: "drift.state.orphaned",
      ignored: "drift.state.ignored",
      unmanaged: "drift.state.unmanaged",
      unknown: "drift.state.unknown",
    },
    source: {
      scenario: "drift.source.scenario",
      external: "drift.source.external",
      unknown: "drift.source.unknown",
    },
  },
  routes: {
    externalHeading: "routes.externalHeading",
    externalDescription: "routes.externalDescription",
    loading: "routes.loading",
    error: "routes.error",
    empty: "routes.empty",
    subdomainLabel: "routes.subdomainLabel",
    subdomainPlaceholder: "routes.subdomainPlaceholder",
    targetLabel: "routes.targetLabel",
    targetPlaceholder: "routes.targetPlaceholder",
    domainLabel: "routes.domainLabel",
    domainPlaceholder: "routes.domainPlaceholder",
    addButton: "routes.addButton",
    deleteButton: "routes.deleteButton",
    addError: "routes.addError",
    deleteError: "routes.deleteError",
    colSubdomain: "routes.colSubdomain",
    colTarget: "routes.colTarget",
    colSource: "routes.colSource",
    colPublicExposure: "routes.colPublicExposure",
    colUrl: "routes.colUrl",
    colActions: "routes.colActions",
    source: {
      scenario: "routes.source.scenario",
      external: "routes.source.external",
      unknown: "routes.source.unknown",
    },
    publicExposure: {
      label: "routes.publicExposure.label",
      rowLabel: "routes.publicExposure.rowLabel",
      help: "routes.publicExposure.help",
      error: "routes.publicExposure.error",
      option: {
        inherit: "routes.publicExposure.option.inherit",
        enabled: "routes.publicExposure.option.enabled",
        disabled: "routes.publicExposure.option.disabled",
      },
    },
  },
  access: {
    heading: "access.heading",
    description: "access.description",
    note: "access.note",
    loading: "access.loading",
    error: "access.error",
    empty: "access.empty",
    globalEnabled: "access.globalEnabled",
    globalDisabled: "access.globalDisabled",
    configured: "access.configured",
    notConfigured: "access.notConfigured",
    planCreateHeading: "access.planCreateHeading",
    planRemoveHeading: "access.planRemoveHeading",
    planNone: "access.planNone",
    colHost: "access.colHost",
    colOverride: "access.colOverride",
    colEffective: "access.colEffective",
    colManaged: "access.colManaged",
    colAppId: "access.colAppId",
    override: {
      inherit: "access.override.inherit",
      enabled: "access.override.enabled",
      disabled: "access.override.disabled",
    },
    bypassOn: "access.bypassOn",
    bypassOff: "access.bypassOff",
    managedYes: "access.managedYes",
    managedNo: "access.managedNo",
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
