// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      overview: "layout.nav.overview",
      exposure: "layout.nav.exposure",
      recovery: "layout.nav.recovery",
      metrics: "layout.nav.metrics",
      audit: "layout.nav.audit",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  common: {
    loading: "common.loading",
    empty: "common.empty",
    refresh: "common.refresh",
    never: "common.never",
  },
  pages: {
    overview: {
      title: "pages.overview.title",
      description: "pages.overview.description",
    },
    exposure: {
      title: "pages.exposure.title",
      description: "pages.exposure.description",
    },
    recovery: {
      title: "pages.recovery.title",
      description: "pages.recovery.description",
    },
    metrics: {
      title: "pages.metrics.title",
      description: "pages.metrics.description",
    },
    audit: {
      title: "pages.audit.title",
      description: "pages.audit.description",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  overview: {
    tunnelHeading: "overview.tunnelHeading",
    scoreLabel: "overview.scoreLabel",
    exposureHeading: "overview.exposureHeading",
    coreLabel: "overview.coreLabel",
    leasedLabel: "overview.leasedLabel",
    recoveryHeading: "overview.recoveryHeading",
    circuitOpenWarning: "overview.circuitOpenWarning",
    viewExposure: "overview.viewExposure",
    viewRecovery: "overview.viewRecovery",
  },
  exposure: {
    heading: "exposure.heading",
    loading: "exposure.loading",
    error: "exposure.error",
    empty: "exposure.empty",
    colScenario: "exposure.colScenario",
    colTier: "exposure.colTier",
    colUrl: "exposure.colUrl",
    colPort: "exposure.colPort",
    colLease: "exposure.colLease",
    colActions: "exposure.colActions",
    tier: {
      core: "exposure.tier.core",
      leased: "exposure.tier.leased",
      unknown: "exposure.tier.unknown",
    },
    leaseActive: "exposure.leaseActive",
    leaseNone: "exposure.leaseNone",
    exposeHeading: "exposure.exposeHeading",
    exposePlaceholder: "exposure.exposePlaceholder",
    exposeButton: "exposure.exposeButton",
    extendButton: "exposure.extendButton",
    revokeButton: "exposure.revokeButton",
    actionError: "exposure.actionError",
  },
  recovery: {
    stateHeading: "recovery.stateHeading",
    loading: "recovery.loading",
    error: "recovery.error",
    statusLabel: "recovery.statusLabel",
    consecFailuresLabel: "recovery.consecFailuresLabel",
    backoffLabel: "recovery.backoffLabel",
    failedRecoveriesLabel: "recovery.failedRecoveriesLabel",
    lastCheckLabel: "recovery.lastCheckLabel",
    lastRecoveryLabel: "recovery.lastRecoveryLabel",
    nextRetryLabel: "recovery.nextRetryLabel",
    circuitOpenLabel: "recovery.circuitOpenLabel",
    circuitOpen: "recovery.circuitOpen",
    circuitClosed: "recovery.circuitClosed",
    status: {
      idle: "recovery.status.idle",
      monitoring: "recovery.status.monitoring",
      recovering: "recovery.status.recovering",
      circuitOpen: "recovery.status.circuitOpen",
      unknown: "recovery.status.unknown",
    },
    timelineHeading: "recovery.timelineHeading",
    timelineEmpty: "recovery.timelineEmpty",
    timelineError: "recovery.timelineError",
    colTrigger: "recovery.colTrigger",
    colAction: "recovery.colAction",
    colOutcome: "recovery.colOutcome",
    colAttempt: "recovery.colAttempt",
    colWhen: "recovery.colWhen",
    outcome: {
      success: "recovery.outcome.success",
      failure: "recovery.outcome.failure",
      skipped: "recovery.outcome.skipped",
      unknown: "recovery.outcome.unknown",
    },
    recoverButton: "recovery.recoverButton",
    recoverForce: "recovery.recoverForce",
    recoverConfirmTitle: "recovery.recoverConfirmTitle",
    recoverConfirmBody: "recovery.recoverConfirmBody",
    recoverConfirm: "recovery.recoverConfirm",
    recoverCancel: "recovery.recoverCancel",
    recoverError: "recovery.recoverError",
  },
  metrics: {
    heading: "metrics.heading",
    loading: "metrics.loading",
    error: "metrics.error",
    empty: "metrics.empty",
    scrapeButton: "metrics.scrapeButton",
    colTime: "metrics.colTime",
    colHaConnections: "metrics.colHaConnections",
    colActiveStreams: "metrics.colActiveStreams",
    colRequestErrors: "metrics.colRequestErrors",
    colRtt: "metrics.colRtt",
    probesHeading: "metrics.probesHeading",
    probesEmpty: "metrics.probesEmpty",
    probesError: "metrics.probesError",
    runProbesButton: "metrics.runProbesButton",
    colRoute: "metrics.colRoute",
    colKind: "metrics.colKind",
    colStatus: "metrics.colStatus",
    colLatency: "metrics.colLatency",
    kind: {
      internal: "metrics.kind.internal",
      external: "metrics.kind.external",
      unknown: "metrics.kind.unknown",
    },
    probeStatus: {
      up: "metrics.probeStatus.up",
      down: "metrics.probeStatus.down",
      timeout: "metrics.probeStatus.timeout",
      error: "metrics.probeStatus.error",
      unknown: "metrics.probeStatus.unknown",
    },
    classificationHeading: "metrics.classificationHeading",
    class: {
      healthy: "metrics.class.healthy",
      tunnelDown: "metrics.class.tunnelDown",
      scenarioDown: "metrics.class.scenarioDown",
      cloudflareOutage: "metrics.class.cloudflareOutage",
      dnsFailure: "metrics.class.dnsFailure",
      configDrift: "metrics.class.configDrift",
      unknown: "metrics.class.unknown",
    },
  },
  audit: {
    heading: "audit.heading",
    loading: "audit.loading",
    error: "audit.error",
    empty: "audit.empty",
    runButton: "audit.runButton",
    violations: "audit.violations",
    violations_zero: "audit.violations_zero",
    violations_one: "audit.violations_one",
    colScenario: "audit.colScenario",
    colSubdomain: "audit.colSubdomain",
    colExpected: "audit.colExpected",
    colActual: "audit.colActual",
    colStatus: "audit.colStatus",
    colDetail: "audit.colDetail",
    status: {
      compliant: "audit.status.compliant",
      mismatch: "audit.status.mismatch",
      missingScenario: "audit.status.missingScenario",
      missingPort: "audit.status.missingPort",
      unknown: "audit.status.unknown",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
