#!/usr/bin/env bash
# OpenRocket Default Configuration

# Service configuration
export OPENROCKET_PORT="${OPENROCKET_PORT:-9513}"
export OPENROCKET_HOST="${OPENROCKET_HOST:-0.0.0.0}"

# Data directories
export OPENROCKET_DATA_DIR="${OPENROCKET_DATA_DIR:-${HOME}/.openrocket}"
export OPENROCKET_MODELS_DIR="${OPENROCKET_MODELS_DIR:-${OPENROCKET_DATA_DIR}/models}"
export OPENROCKET_DESIGNS_DIR="${OPENROCKET_DESIGNS_DIR:-${OPENROCKET_DATA_DIR}/designs}"
export OPENROCKET_SIMS_DIR="${OPENROCKET_SIMS_DIR:-${OPENROCKET_DATA_DIR}/simulations}"
export OPENROCKET_LOG_DIR="${OPENROCKET_LOG_DIR:-${OPENROCKET_DATA_DIR}/logs}"

# Container settings
export OPENROCKET_CONTAINER_NAME="${OPENROCKET_CONTAINER_NAME:-openrocket-server}"
export OPENROCKET_IMAGE="${OPENROCKET_IMAGE:-openrocket/openrocket:latest}"

# Simulation defaults
export OPENROCKET_MAX_ALTITUDE="${OPENROCKET_MAX_ALTITUDE:-10000}"  # meters
export OPENROCKET_TIME_STEP="${OPENROCKET_TIME_STEP:-0.01}"  # seconds
export OPENROCKET_WIND_SPEED="${OPENROCKET_WIND_SPEED:-5}"  # m/s

# Integration settings
export OPENROCKET_ENABLE_MINIO="${OPENROCKET_ENABLE_MINIO:-true}"
export OPENROCKET_ENABLE_POSTGRES="${OPENROCKET_ENABLE_POSTGRES:-true}"
export OPENROCKET_ENABLE_QUESTDB="${OPENROCKET_ENABLE_QUESTDB:-false}"

# Performance settings
export OPENROCKET_MAX_CONCURRENT_SIMS="${OPENROCKET_MAX_CONCURRENT_SIMS:-4}"
export OPENROCKET_MEMORY_LIMIT="${OPENROCKET_MEMORY_LIMIT:-2G}"
export OPENROCKET_CPU_LIMIT="${OPENROCKET_CPU_LIMIT:-2}"