import { afterEach, describe, expect, it, vi } from "vitest";
import type { IApiClient } from "../lib/api-client";
import { createPromptService } from "./prompt-service";
// Injected transports only: previews are non-dispatch fixture projections.
let clients: { api: IApiClient; reads: unknown[][]; posts: unknown[][] }[]=[];
function fixture(data: unknown, reads: unknown[][], posts: unknown[][]=[], error?: Error) { const api: IApiClient = { get: error ? vi.fn().mockRejectedValue(error) : vi.fn().mockResolvedValue(data), post: error ? vi.fn().mockRejectedValue(error) : vi.fn().mockResolvedValue(data), put: vi.fn(), patch: vi.fn(), delete: vi.fn() }; clients.push({api,reads,posts}); return {api,service:createPromptService(api)}; }
afterEach(() => { for (const {api,reads,posts} of clients.splice(0)) { expect(vi.mocked(api.get).mock.calls).toEqual(reads); expect(vi.mocked(api.post).mock.calls).toEqual(posts); for (const method of ["put","patch","delete"] as const) expect(api[method]).not.toHaveBeenCalled(); } });
describe("prompt display projections preserve scope and historical evidence",()=>{
 it.each([undefined,false,true])("sends exact preview scope %j and literal variables without publishing",async scope=>{ const data={skill_id:"fixture-skill",with_scope:scope??true,variables:{target:"fixture/<literal>"},prompt:"Literal <script>"}; const f=fixture(data,[],[["/prompts/preview",{skill_id:"fixture-skill",variables:{target:"fixture/<literal>"},with_scope:scope??true}]]); expect(await f.service.preview("fixture-skill",{target:"fixture/<literal>"},scope)).toEqual(data); });
 it("retains preview refusal without execution fallback",async()=>{ const error=new Error("Fixture refused preview");const f=fixture(undefined,[],[["/prompts/preview",{skill_id:"fixture-skill",variables:{},with_scope:false}]],error);await expect(f.service.preview("fixture-skill",{},false)).rejects.toBe(error); });
 it.each([false,true])("preserves the historical trace synthetic annotation %j",async synthetic=>{const trace={purpose:"fixture-display",prompt:"Original exact text",used_fallback:false,synthetic,captured_at:"historic",prompt_revision:"fixture-revision",experiment_id:"historical-experiment",variant_id:"historical-variant"};const f=fixture({trace},[["/execution/historical-execution/prompt-trace"]]);expect(await f.service.getExecutionPromptTrace("historical-execution")).toEqual(trace);});
 it("refuses a missing historical trace without rebuilding it",async()=>{const f=fixture({},[["/execution/historical-execution/prompt-trace"]]);await expect(f.service.getExecutionPromptTrace("historical-execution")).rejects.toThrow("Prompt trace not found");});
 it.each([{variants:[]},{variants:[{variantId:"original-variant",totalRuns:2,readyCount:1,needsWorkCount:1,fixupRate:0.5,avgDurationSecs:2}]}])("reads retained experiment outcomes %j without running another experiment",async ({variants})=>{ const data={experimentId:"historical-experiment",variants,totalOutcomes:variants.length?2:0,analyzedAt:"historic"};const f=fixture(data,[["/prompts/experiments/historical-experiment/results"]]);expect(await f.service.getExperimentResults("historical-experiment")).toEqual(data); });
 it("retains experiment transport refusal with no rerun",async()=>{const error=new Error("Fixture results refused");const f=fixture(undefined,[["/prompts/experiments/historical-experiment/results"]],[],error);await expect(f.service.getExperimentResults("historical-experiment")).rejects.toBe(error);});
});
