import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";

import { getComponentTestReport, listComponentTestReports, runComponentTest, type ComponentTestReport } from "../../api/componentTests";
import { Button } from "../../components/ui/button";
import { EmptyState } from "../../components/ui/empty-state";
import { StatusBadge } from "../../components/ui/status-badge";

function tone(verdict: string): "success" | "danger" | "warning" | "neutral" { return verdict === "passed" ? "success" : verdict === "failed" ? "danger" : verdict === "blocked" ? "warning" : "neutral"; }
function Report({ report }: { report: ComponentTestReport }) { return <article data-testid="component-test-report" className="rounded-control border border-app-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-mono text-xs">{report.id}</p><StatusBadge tone={tone(report.verdict)}>{report.verdict}</StatusBadge></div><ul className="mt-3 space-y-2 text-xs">{report.results.map((result, index) => <li key={`${result.stage}-${result.assetLibraryId}-${index}`} className="border-l-2 border-app-border pl-2"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{result.stage}</span><StatusBadge tone={tone(result.verdict)}>{result.verdict}</StatusBadge><span className="font-mono text-app-muted-foreground">{result.assetLibraryId}@{result.version}</span></div>{result.message && <p className="mt-1 text-app-muted-foreground">{result.message}</p>}{result.remediation && <p className="mt-1 text-app-warning">Next: {result.remediation}</p>}</li>)}</ul>{(report.artifacts?.length ?? 0) > 0 && <section className="mt-3 text-xs" aria-label="Report artifacts"><h4 className="font-medium">Artifacts</h4><ul className="mt-1 space-y-1">{report.artifacts?.map((artifact) => <li key={artifact.reference} className="font-mono text-app-muted-foreground">{artifact.kind} · {artifact.reference}</li>)}</ul></section>}</article>; }

export function ComponentTestPanel({ componentId, version }: { componentId: string; version: string }) {
  const [search] = useSearchParams();
  const reportID = search.get("testReport") || "";
  const queryClient = useQueryClient();
  const reports = useQuery({ queryKey: ["component-tests", componentId], queryFn: () => listComponentTestReports({ componentId }), enabled: Boolean(componentId) });
  const selected = useQuery({ queryKey: ["component-test-report", reportID], queryFn: () => getComponentTestReport(reportID), enabled: Boolean(reportID) });
  const run = useMutation({ mutationFn: () => runComponentTest({ componentId, version, includeClosure: true }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["component-tests", componentId] }) });
  const latest = run.data ?? selected.data ?? reports.data?.[0];
  return <section data-testid="component-test-panel" className="space-y-3 text-sm text-app-foreground" aria-label="Component tests"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-medium">Component tests</h3><p className="text-xs text-app-muted-foreground">Runs the declared {version || "unselected"} version and its pinned dependency closure.</p></div><Button size="sm" onClick={() => run.mutate()} disabled={run.isPending || !version}>{run.isPending ? "Running…" : "Run tests"}</Button></div>{run.isError && <p role="alert" className="rounded-control border border-app-danger p-2 text-xs text-app-danger">{run.error instanceof Error ? run.error.message : "The component test could not be started."}</p>}{selected.isError && <p role="alert" className="rounded-control border border-app-warning p-2 text-xs text-app-warning">The requested report is unavailable.</p>}{reports.isLoading ? <p className="text-xs text-app-muted-foreground">Loading test history…</p> : latest ? <Report report={latest} /> : <EmptyState className="p-2 text-xs" title="No component test history" description="Run the declared contract to create durable evidence." />}{reports.data && reports.data.length > 1 && <details><summary className="cursor-pointer text-xs text-app-primary">{reports.data.length - 1} earlier run(s)</summary><div className="mt-2 space-y-2">{reports.data.slice(1).map((report) => <a key={report.id} href={`?tab=tests&testReport=${encodeURIComponent(report.id)}`} className="block rounded-control focus:outline-none focus:ring-2 focus:ring-app-primary" aria-label={`Open component test report ${report.id}`}><Report report={report} /></a>)}</div></details>}</section>;
}
