export * from './AboutPage';
export * from './admin';
export * from './FormPage';
export * from './HomePage';
export * from './NotFoundPage';
export * from './Page';
export * from './PrivacyPolicyPage';
export * from './styles';
export * from './TermsPage';