run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofumpt
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gofumpt:
    module-path: github.com/vrooli/browser-automation-studio

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0
