// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      matrix: "layout.nav.matrix",
      fleet: "layout.nav.fleet",
      wizard: "layout.nav.wizard",
      findings: "layout.nav.findings",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      statPlaceholderLabel: "pages.dashboard.statPlaceholderLabel",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
  common: {
    scenarioLabel: "common.scenarioLabel",
    scenarioPlaceholder: "common.scenarioPlaceholder",
    load: "common.load",
    recentLabel: "common.recentLabel",
    clearRecent: "common.clearRecent",
    chooseScenario: "common.chooseScenario",
    close: "common.close",
  },
  matrix: {
    title: "matrix.title",
    description: "matrix.description",
    loading: "matrix.loading",
    error: "matrix.error",
    empty: "matrix.empty",
    degraded: "matrix.degraded",
    registry: {
      modules: "matrix.registry.modules",
      requirements: "matrix.registry.requirements",
      targets: "matrix.registry.targets",
      starter: "matrix.registry.starter",
    },
    orphanTarget: "matrix.orphanTarget",
    orphanRequirement: "matrix.orphanRequirement",
    unproven: "matrix.unproven",
    checked: "matrix.checked",
    unchecked: "matrix.unchecked",
    evidence: {
      live: "matrix.evidence.live",
      stale: "matrix.evidence.stale",
      manual: "matrix.evidence.manual",
      none: "matrix.evidence.none",
      syncedAt: "matrix.evidence.syncedAt",
      expired: "matrix.evidence.expired",
      expires: "matrix.evidence.expires",
      attestedBy: "matrix.evidence.attestedBy",
    },
    drawer: {
      title: "matrix.drawer.title",
      validations: "matrix.drawer.validations",
      refExists: "matrix.drawer.refExists",
      refMissing: "matrix.drawer.refMissing",
      noValidations: "matrix.drawer.noValidations",
      evidenceHeading: "matrix.drawer.evidenceHeading",
      attestHeading: "matrix.drawer.attestHeading",
      attestBy: "matrix.drawer.attestBy",
      attestByPlaceholder: "matrix.drawer.attestByPlaceholder",
      attestNotes: "matrix.drawer.attestNotes",
      attestNotesPlaceholder: "matrix.drawer.attestNotesPlaceholder",
      attestSubmit: "matrix.drawer.attestSubmit",
      attestSuccess: "matrix.drawer.attestSuccess",
    },
  },
  fleet: {
    title: "fleet.title",
    description: "fleet.description",
    loading: "fleet.loading",
    error: "fleet.error",
    empty: "fleet.empty",
    refresh: "fleet.refresh",
    asOf: "fleet.asOf",
    filterPlaceholder: "fleet.filterPlaceholder",
    filter: {
      starter: "fleet.filter.starter",
      laggard: "fleet.filter.laggard",
      unproven: "fleet.filter.unproven",
    },
    tile: {
      scanned: "fleet.tile.scanned",
      passing: "fleet.tile.passing",
      starter: "fleet.tile.starter",
      laggard: "fleet.tile.laggard",
    },
    column: {
      scenario: "fleet.column.scenario",
      status: "fleet.column.status",
      errors: "fleet.column.errors",
      warnings: "fleet.column.warnings",
      autofix: "fleet.column.autofix",
      orphans: "fleet.column.orphans",
      unproven: "fleet.column.unproven",
      template: "fleet.column.template",
      debt: "fleet.column.debt",
    },
    passed: "fleet.passed",
    failed: "fleet.failed",
    errorsHeading: "fleet.errorsHeading",
    errorsHeading_one: "fleet.errorsHeading_one",
    noMatches: "fleet.noMatches",
  },
  wizard: {
    title: "wizard.title",
    description: "wizard.description",
    loading: "wizard.loading",
    error: "wizard.error",
    reset: "wizard.reset",
    progress: "wizard.progress",
    required: "wizard.required",
    optional: "wizard.optional",
    listAdd: "wizard.listAdd",
    listRemove: "wizard.listRemove",
    otTitlePlaceholder: "wizard.otTitlePlaceholder",
    otDescPlaceholder: "wizard.otDescPlaceholder",
    submit: "wizard.submit",
    saving: "wizard.saving",
    complete: "wizard.complete",
    sectionPreviewHeading: "wizard.sectionPreviewHeading",
    sectionPreviewEmpty: "wizard.sectionPreviewEmpty",
    previewButton: "wizard.previewButton",
    previewLoading: "wizard.previewLoading",
    previewHeading: "wizard.previewHeading",
    previewBlocking: "wizard.previewBlocking",
    apply: "wizard.apply",
    applying: "wizard.applying",
    applied: "wizard.applied",
    applied_one: "wizard.applied_one",
    residual: "wizard.residual",
    hintsHeading: "wizard.hintsHeading",
    hintScore: "wizard.hintScore",
  },
  findings: {
    title: "findings.title",
    description: "findings.description",
    loading: "findings.loading",
    error: "findings.error",
    empty: "findings.empty",
    verdict: "findings.verdict",
    degraded: "findings.degraded",
    remediationHeading: "findings.remediationHeading",
    docLink: "findings.docLink",
    location: "findings.location",
    autofix: "findings.autofix",
    previewFix: "findings.previewFix",
    previewLoading: "findings.previewLoading",
    applyFix: "findings.applyFix",
    applying: "findings.applying",
    fixEmpty: "findings.fixEmpty",
    fixApplied: "findings.fixApplied",
    fixApplied_one: "findings.fixApplied_one",
    noFixable: "findings.noFixable",
  },
  diff: {
    added: "diff.added",
    removed: "diff.removed",
    newFile: "diff.newFile",
    empty: "diff.empty",
  },
} as const;

export type Strings = typeof strings;
