name: Development VPS Deployment

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: |
          # Set version with timestamp
          VERSION=$(cat package.json | jq -r .version)-dev-$(date +%Y%m%d%H%M%S)
          # Run build script
          ./scripts/build.sh -v $VERSION -t y
          echo "BUILD_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

      - name: Deploy to Development VPS
        env:
          DEV_VPS_HOST: ${{ secrets.DEV_VPS_HOST }}
          DEV_VPS_USER: ${{ secrets.DEV_VPS_USER }}
          DEPLOY_PATH: "/root/Vrooli"
        run: |
          # Add VPS host to known_hosts
          ssh-keyscan -H $DEV_VPS_HOST >> ~/.ssh/known_hosts

          # Create temp directory for build artifacts
          BUILD_DIR="/var/tmp/${{ env.BUILD_VERSION }}"
          ssh $DEV_VPS_USER@$DEV_VPS_HOST "mkdir -p $BUILD_DIR"

          # Copy build artifacts to VPS
          scp /var/tmp/${{ env.BUILD_VERSION }}/build.tar.gz $DEV_VPS_USER@$DEV_VPS_HOST:$BUILD_DIR/
          scp /var/tmp/${{ env.BUILD_VERSION }}/production-docker-images.tar.gz $DEV_VPS_USER@$DEV_VPS_HOST:$BUILD_DIR/
          scp /var/tmp/${{ env.BUILD_VERSION }}/.env-dev $DEV_VPS_USER@$DEV_VPS_HOST:$BUILD_DIR/

          # Update git repo on server and deploy
          ssh $DEV_VPS_USER@$DEV_VPS_HOST "cd $DEPLOY_PATH && \
            git fetch && \
            git pull origin development && \
            cp $BUILD_DIR/.env-dev .env-dev && \
            ./scripts/develop.sh -v ${{ env.BUILD_VERSION }} -c -y"

          # Verify API health check after deployment
          sleep 30
          curl -s -f -o /dev/null ${{ secrets.DEV_API_URL }}/healthcheck || { echo "Deployment verification failed"; exit 1; }

  notify:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Notify on success
        if: ${{ needs.deploy.result == 'success' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"text":"✅ Successfully deployed version ${{ env.BUILD_VERSION }} to development VPS"}' \
            ${{ secrets.NOTIFICATION_WEBHOOK_URL }} || echo "Deployment to development VPS completed successfully"

      - name: Notify on failure
        if: ${{ needs.deploy.result != 'success' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"text":"❌ Failed to deploy version ${{ env.BUILD_VERSION }} to development VPS"}' \
            ${{ secrets.NOTIFICATION_WEBHOOK_URL }} || echo "Deployment to development VPS failed"
