// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      tokens: "layout.nav.tokens",
      holders: "layout.nav.holders",
      earning: "layout.nav.earning",
      grants: "layout.nav.grants",
      catalog: "layout.nav.catalog",
      approvals: "layout.nav.approvals",
      journal: "layout.nav.journal",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
  },
  common: {
    status: "common.status",
    actions: "common.actions",
    amount: "common.amount",
    active: "common.active",
    inactive: "common.inactive",
    retired: "common.retired",
    retire: "common.retire",
    pending: "common.pending",
    name: "common.name",
    identifier: "common.identifier",
    description: "common.description",
    loading: "common.loading",
    requestError: "common.requestError",
    search: "common.search",
  },
  dashboard: {
    current: "dashboard.current",
    tokenTypes: "dashboard.tokenTypes",
    holders: "dashboard.holders",
    rewards: "dashboard.rewards",
    pendingApprovals: "dashboard.pendingApprovals",
  },
  mints: {
    title: "mints.title",
    description: "mints.description",
    createTitle: "mints.createTitle",
    create: "mints.create",
    identity: "mints.identity",
    symbol: "mints.symbol",
    color: "mints.color",
    minterSubject: "mints.minterSubject",
    supplyPolicy: "mints.supplyPolicy",
    unbounded: "mints.unbounded",
    capped: "mints.capped",
    fixed: "mints.fixed",
    capAmount: "mints.capAmount",
    supply: "mints.supply",
    mintAmount: "mints.mintAmount",
    mint: "mints.mint",
    tableCaption: "mints.tableCaption",
    empty: "mints.empty",
  },
  holders: {
    title: "holders.title",
    description: "holders.description",
    addTitle: "holders.addTitle",
    add: "holders.add",
    authenticatorSubject: "holders.authenticatorSubject",
    tableCaption: "holders.tableCaption",
    empty: "holders.empty",
  },
  holderView: {
    appTitle: "holderView.appTitle",
    appDescription: "holderView.appDescription",
    mainLabel: "holderView.mainLabel",
    navigationLabel: "holderView.navigationLabel",
    nav: {
      home: "holderView.nav.home",
      history: "holderView.nav.history",
      rewards: "holderView.nav.rewards",
    },
    eyebrow: "holderView.eyebrow",
    title: "holderView.title",
    welcome: "holderView.welcome",
    balanceExplanation: "holderView.balanceExplanation",
    balances: "holderView.balances",
    signInRequired: "holderView.signInRequired",
    noBalance: "holderView.noBalance",
    noBalanceDescription: "holderView.noBalanceDescription",
    recentHistory: "holderView.recentHistory",
    seeAll: "holderView.seeAll",
    journalEvent: "holderView.journalEvent",
    noHistory: "holderView.noHistory",
    noHistoryDescription: "holderView.noHistoryDescription",
    historyTitle: "holderView.historyTitle",
    historyDescription: "holderView.historyDescription",
    historyListLabel: "holderView.historyListLabel",
    pendingTitle: "holderView.pendingTitle",
    noPending: "holderView.noPending",
    rewardRequest: "holderView.rewardRequest",
    rewardsTitle: "holderView.rewardsTitle",
    rewardsDescription: "holderView.rewardsDescription",
    cost: "holderView.cost",
    redeem: "holderView.redeem",
    noEligibleGrant: "holderView.noEligibleGrant",
    noRewards: "holderView.noRewards",
    noRewardsDescription: "holderView.noRewardsDescription",
    redemptionRecorded: "holderView.redemptionRecorded",
    redemptionRefused: "holderView.redemptionRefused",
  },
  grants: {
    title: "grants.title",
    description: "grants.description",
    issueTitle: "grants.issueTitle",
    issue: "grants.issue",
    tokenType: "grants.tokenType",
    holder: "grants.holder",
    source: "grants.source",
    authorizer: "grants.authorizer",
    catalogScope: "grants.catalogScope",
    rules: "grants.rules",
    rule: "grants.rule",
    noRules: "grants.noRules",
    condition: "grants.condition",
    operand: "grants.operand",
    allowScope: "grants.allowScope",
    denyScope: "grants.denyScope",
    requireEvidence: "grants.requireEvidence",
    rulePreview: "grants.rulePreview",
    anyScope: "grants.anyScope",
    tableCaption: "grants.tableCaption",
    empty: "grants.empty",
  },
  catalog: {
    title: "catalog.title",
    description: "catalog.description",
    createTitle: "catalog.createTitle",
    create: "catalog.create",
    tokenType: "catalog.tokenType",
    cost: "catalog.cost",
    approval: "catalog.approval",
    needsApproval: "catalog.needsApproval",
    immediate: "catalog.immediate",
    tableCaption: "catalog.tableCaption",
    empty: "catalog.empty",
  },
  approvals: {
    title: "approvals.title",
    description: "approvals.description",
    holder: "approvals.holder",
    reward: "approvals.reward",
    decision: "approvals.decision",
    reason: "approvals.reason",
    defaultApprovalReason: "approvals.defaultApprovalReason",
    defaultDenialReason: "approvals.defaultDenialReason",
    approve: "approvals.approve",
    deny: "approvals.deny",
    tableCaption: "approvals.tableCaption",
    empty: "approvals.empty",
  },
  journal: {
    title: "journal.title",
    description: "journal.description",
    kind: "journal.kind",
    reason: "journal.reason",
    actor: "journal.actor",
    noActor: "journal.noActor",
    verified: "journal.verified",
    unverified: "journal.unverified",
    holderFilter: "journal.holderFilter",
    tokenFilter: "journal.tokenFilter",
    export: "journal.export",
    tableCaption: "journal.tableCaption",
    empty: "journal.empty",
  },
  earning: {
    title: "earning.title",
    description: "earning.description",
    submitTitle: "earning.submitTitle",
    submit: "earning.submit",
    holder: "earning.holder",
    tokenType: "earning.tokenType",
    reason: "earning.reason",
    path: "earning.path",
    operatorAdapter: "earning.operatorAdapter",
    replayed: "earning.replayed",
    recorded: "earning.recorded",
    sharedPathNote: "earning.sharedPathNote",
    tableCaption: "earning.tableCaption",
    empty: "earning.empty",
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
