// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  $rowKey: "$rowKey",
  $schema: "$schema",
  $text: "$text",
  "Changes saved successfully": {
    "": "Changes saved successfully.",
  },
  "Disabled states retain the same geometry and clearly communicate that the action is unavailable": {
    "": "Disabled states retain the same geometry and clearly communicate that the action is unavailable.",
  },
  "Request in progress": "Request in progress",
  Saved: "Saved",
  app: {
    title: "app.title",
  },
  approvals: {
    approve: "approvals.approve",
    decision: "approvals.decision",
    defaultApprovalReason: "approvals.defaultApprovalReason",
    defaultDenialReason: "approvals.defaultDenialReason",
    deny: "approvals.deny",
    description: "approvals.description",
    empty: "approvals.empty",
    holder: "approvals.holder",
    reason: "approvals.reason",
    reward: "approvals.reward",
    tableCaption: "approvals.tableCaption",
    title: "approvals.title",
  },
  "aria-label": "aria-label",
  ascending: "ascending",
  asset: "asset",
  "border-app-primary bg-app-primary text-app-primary-foreground": "border-app-primary bg-app-primary text-app-primary-foreground",
  capability: "capability",
  caption: "caption",
  catalog: {
    approval: "catalog.approval",
    cost: "catalog.cost",
    create: "catalog.create",
    createTitle: "catalog.createTitle",
    description: "catalog.description",
    empty: "catalog.empty",
    immediate: "catalog.immediate",
    needsApproval: "catalog.needsApproval",
    tableCaption: "catalog.tableCaption",
    title: "catalog.title",
    tokenType: "catalog.tokenType",
  },
  children: "children",
  clsx: "clsx",
  common: {
    actions: "common.actions",
    active: "common.active",
    amount: "common.amount",
    description: "common.description",
    identifier: "common.identifier",
    inactive: "common.inactive",
    loading: "common.loading",
    name: "common.name",
    pending: "common.pending",
    requestError: "common.requestError",
    retire: "common.retire",
    retired: "common.retired",
    search: "common.search",
    status: "common.status",
  },
  component: "component",
  dashboard: {
    current: "dashboard.current",
    holders: "dashboard.holders",
    pendingApprovals: "dashboard.pendingApprovals",
    rewards: "dashboard.rewards",
    tokenTypes: "dashboard.tokenTypes",
  },
  default: "default",
  defaultValue: "defaultValue",
  desc: "desc",
  description: "description",
  detail: "detail",
  dialog: "dialog",
  earning: {
    description: "earning.description",
    empty: "earning.empty",
    holder: "earning.holder",
    operatorAdapter: "earning.operatorAdapter",
    path: "earning.path",
    reason: "earning.reason",
    recorded: "earning.recorded",
    replayed: "earning.replayed",
    sharedPathNote: "earning.sharedPathNote",
    submit: "earning.submit",
    submitTitle: "earning.submitTitle",
    tableCaption: "earning.tableCaption",
    title: "earning.title",
    tokenType: "earning.tokenType",
  },
  emptyMessage: "emptyMessage",
  equals: "equals",
  errorBoundary: {
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
    title: "errorBoundary.title",
  },
  errors: {
    aborted: "errors.aborted",
    already_exists: "errors.already_exists",
    canceled: "errors.canceled",
    data_loss: "errors.data_loss",
    deadline_exceeded: "errors.deadline_exceeded",
    failed_precondition: "errors.failed_precondition",
    internal: "errors.internal",
    invalid_argument: "errors.invalid_argument",
    not_found: "errors.not_found",
    out_of_range: "errors.out_of_range",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    unauthenticated: "errors.unauthenticated",
    unavailable: "errors.unavailable",
    unimplemented: "errors.unimplemented",
    unknown: "errors.unknown",
  },
  example: "example",
  export: "export",
  field: "field",
  fixture: "fixture",
  format: "format",
  grants: {
    allowScope: "grants.allowScope",
    anyScope: "grants.anyScope",
    authorizer: "grants.authorizer",
    catalogScope: "grants.catalogScope",
    condition: "grants.condition",
    denyScope: "grants.denyScope",
    description: "grants.description",
    empty: "grants.empty",
    holder: "grants.holder",
    issue: "grants.issue",
    issueTitle: "grants.issueTitle",
    noRules: "grants.noRules",
    operand: "grants.operand",
    requireEvidence: "grants.requireEvidence",
    rule: "grants.rule",
    rulePreview: "grants.rulePreview",
    rules: "grants.rules",
    source: "grants.source",
    tableCaption: "grants.tableCaption",
    title: "grants.title",
    tokenType: "grants.tokenType",
  },
  header: "header",
  health: {
    error: "health.error",
    loading: "health.loading",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
    title: "health.title",
  },
  holderView: {
    appDescription: "holderView.appDescription",
    appTitle: "holderView.appTitle",
    balanceExplanation: "holderView.balanceExplanation",
    balances: "holderView.balances",
    cost: "holderView.cost",
    eyebrow: "holderView.eyebrow",
    historyDescription: "holderView.historyDescription",
    historyListLabel: "holderView.historyListLabel",
    historyTitle: "holderView.historyTitle",
    journalEvent: "holderView.journalEvent",
    mainLabel: "holderView.mainLabel",
    nav: {
      history: "holderView.nav.history",
      home: "holderView.nav.home",
      rewards: "holderView.nav.rewards",
    },
    navigationLabel: "holderView.navigationLabel",
    noBalance: "holderView.noBalance",
    noBalanceDescription: "holderView.noBalanceDescription",
    noEligibleGrant: "holderView.noEligibleGrant",
    noHistory: "holderView.noHistory",
    noHistoryDescription: "holderView.noHistoryDescription",
    noPending: "holderView.noPending",
    noRewards: "holderView.noRewards",
    noRewardsDescription: "holderView.noRewardsDescription",
    pendingTitle: "holderView.pendingTitle",
    recentHistory: "holderView.recentHistory",
    redeem: "holderView.redeem",
    redemptionRecorded: "holderView.redemptionRecorded",
    redemptionRefused: "holderView.redemptionRefused",
    rewardRequest: "holderView.rewardRequest",
    rewardsDescription: "holderView.rewardsDescription",
    rewardsTitle: "holderView.rewardsTitle",
    seeAll: "holderView.seeAll",
    signInRequired: "holderView.signInRequired",
    title: "holderView.title",
    welcome: "holderView.welcome",
  },
  holders: {
    add: "holders.add",
    addTitle: "holders.addTitle",
    authenticatorSubject: "holders.authenticatorSubject",
    description: "holders.description",
    empty: "holders.empty",
    tableCaption: "holders.tableCaption",
    title: "holders.title",
  },
  iconName: "iconName",
  id: "id",
  journal: {
    actor: "journal.actor",
    description: "journal.description",
    empty: "journal.empty",
    export: "journal.export",
    holderFilter: "journal.holderFilter",
    kind: "journal.kind",
    noActor: "journal.noActor",
    reason: "journal.reason",
    tableCaption: "journal.tableCaption",
    title: "journal.title",
    tokenFilter: "journal.tokenFilter",
    unverified: "journal.unverified",
    verified: "journal.verified",
  },
  kind: "kind",
  label: "label",
  layout: {
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      approvals: "layout.nav.approvals",
      catalog: "layout.nav.catalog",
      dashboard: "layout.nav.dashboard",
      earning: "layout.nav.earning",
      grants: "layout.nav.grants",
      holders: "layout.nav.holders",
      journal: "layout.nav.journal",
      settings: "layout.nav.settings",
      tokens: "layout.nav.tokens",
    },
    sidebarLabel: "layout.sidebarLabel",
  },
  libraryId: "libraryId",
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  "lucide-react": "lucide-react",
  mints: {
    capAmount: "mints.capAmount",
    capped: "mints.capped",
    color: "mints.color",
    create: "mints.create",
    createTitle: "mints.createTitle",
    description: "mints.description",
    empty: "mints.empty",
    fixed: "mints.fixed",
    identity: "mints.identity",
    mint: "mints.mint",
    mintAmount: "mints.mintAmount",
    minterSubject: "mints.minterSubject",
    supply: "mints.supply",
    supplyPolicy: "mints.supplyPolicy",
    symbol: "mints.symbol",
    tableCaption: "mints.tableCaption",
    title: "mints.title",
    unbounded: "mints.unbounded",
  },
  mode: "mode",
  module: "module",
  name: "name",
  notifications: {
    summary: "notifications.summary",
    summary_one: "notifications.summary_one",
    summary_zero: "notifications.summary_zero",
  },
  pages: {
    dashboard: {
      description: "pages.dashboard.description",
      title: "pages.dashboard.title",
    },
    settings: {
      localeHeading: "pages.settings.localeHeading",
      themeHeading: "pages.settings.themeHeading",
      title: "pages.settings.title",
    },
  },
  path: "path",
  placeholder: "placeholder",
  provenance: "provenance",
  purpose: "purpose",
  react: "react",
  "react-component-library:useEscapeKey": "react-component-library:useEscapeKey",
  ref: "ref",
  region: "region",
  resolvedAt: "resolvedAt",
  role: "role",
  schema: "schema",
  schemaVersion: "schemaVersion",
  selector: "selector",
  size: "size",
  statement: "statement",
  status: "status",
  storyRef: "storyRef",
  "tailwind-merge": "tailwind-merge",
  testid: "testid",
  theme: {
    choice: {
      dark: "theme.choice.dark",
      light: "theme.choice.light",
      system: "theme.choice.system",
    },
    switcherLabel: "theme.switcherLabel",
  },
  tier: "tier",
  title: "title",
  tone: "tone",
  true: "true",
  type: "type",
  value: "value",
  variant: "variant",
  version: "version",
} as const;

export type Strings = typeof strings;
