// AUTO-GENERATED — do not edit by hand.
//
// Source : src/i18n/locales/en.json
// Codegen: scripts/gen-strings.mjs (invoked automatically by
//          vite-plugin-strings-codegen on dev start, HMR of en.json, and
//          build start; also available as `pnpm strings:gen` and
//          `pnpm strings:check`).
//
// See src/consts/strings.ts for the registry's purpose, why it exists, and
// how to use it. This file mirrors the shape of en.json with each leaf
// replaced by its dotted key path — that's the value the i18next `t()`
// function takes as its first argument.

export const strings = {
  app: {
    title: "app.title",
  },
  layout: {
    sidebarLabel: "layout.sidebarLabel",
    bottomNavLabel: "layout.bottomNavLabel",
    mainLabel: "layout.mainLabel",
    nav: {
      dashboard: "layout.nav.dashboard",
      plans: "layout.nav.plans",
      authoring: "layout.nav.authoring",
      execution: "layout.nav.execution",
      validation: "layout.nav.validation",
      triage: "layout.nav.triage",
      velocity: "layout.nav.velocity",
      settings: "layout.nav.settings",
    },
  },
  theme: {
    switcherLabel: "theme.switcherLabel",
    choice: {
      light: "theme.choice.light",
      dark: "theme.choice.dark",
      system: "theme.choice.system",
    },
  },
  common: {
    loading: "common.loading",
    empty: "common.empty",
    none: "common.none",
    degraded: "common.degraded",
    degradedBadge: "common.degradedBadge",
    unknownDate: "common.unknownDate",
    selectPlaceholder: "common.selectPlaceholder",
  },
  planStatus: {
    unspecified: "planStatus.unspecified",
    draft: "planStatus.draft",
    active: "planStatus.active",
    complete: "planStatus.complete",
    archived: "planStatus.archived",
  },
  phaseStatus: {
    unspecified: "phaseStatus.unspecified",
    todo: "phaseStatus.todo",
    active: "phaseStatus.active",
    done: "phaseStatus.done",
    blocked: "phaseStatus.blocked",
  },
  staleness: {
    unspecified: "staleness.unspecified",
    fresh: "staleness.fresh",
    lightlyStale: "staleness.lightlyStale",
    definitelyStale: "staleness.definitelyStale",
  },
  verdict: {
    unspecified: "verdict.unspecified",
    pass: "verdict.pass",
    fail: "verdict.fail",
    unknown: "verdict.unknown",
  },
  pages: {
    dashboard: {
      title: "pages.dashboard.title",
      description: "pages.dashboard.description",
      statPlans: "pages.dashboard.statPlans",
      statActive: "pages.dashboard.statActive",
      statStale: "pages.dashboard.statStale",
      statCandidates: "pages.dashboard.statCandidates",
      recentHeading: "pages.dashboard.recentHeading",
      quickLinksHeading: "pages.dashboard.quickLinksHeading",
    },
    settings: {
      title: "pages.settings.title",
      themeHeading: "pages.settings.themeHeading",
      localeHeading: "pages.settings.localeHeading",
    },
    plans: {
      title: "pages.plans.title",
      description: "pages.plans.description",
      newFromTemplate: "pages.plans.newFromTemplate",
      templateLabel: "pages.plans.templateLabel",
      titleLabel: "pages.plans.titleLabel",
      titlePlaceholder: "pages.plans.titlePlaceholder",
      create: "pages.plans.create",
      phasesLabel: "pages.plans.phasesLabel",
      phaseProgress: "pages.plans.phaseProgress",
      updatedLabel: "pages.plans.updatedLabel",
      empty: "pages.plans.empty",
      archive: "pages.plans.archive",
      viewDetail: "pages.plans.viewDetail",
      detail: {
        purposeHeading: "pages.plans.detail.purposeHeading",
        scopeHeading: "pages.plans.detail.scopeHeading",
        constraintsHeading: "pages.plans.detail.constraintsHeading",
        nonGoalsHeading: "pages.plans.detail.nonGoalsHeading",
        dodHeading: "pages.plans.detail.dodHeading",
        phasesHeading: "pages.plans.detail.phasesHeading",
        referencesHeading: "pages.plans.detail.referencesHeading",
        anchorHeading: "pages.plans.detail.anchorHeading",
        graphHeading: "pages.plans.detail.graphHeading",
        markdownHeading: "pages.plans.detail.markdownHeading",
        showMarkdown: "pages.plans.detail.showMarkdown",
        hideMarkdown: "pages.plans.detail.hideMarkdown",
        anchorStrategy: "pages.plans.detail.anchorStrategy",
        anchorScenario: "pages.plans.detail.anchorScenario",
        anchorBaseline: "pages.plans.detail.anchorBaseline",
        anchorHeadSha: "pages.plans.detail.anchorHeadSha",
        anchorCommands: "pages.plans.detail.anchorCommands",
        anchorAllowlist: "pages.plans.detail.anchorAllowlist",
        anchorUnavailable: "pages.plans.detail.anchorUnavailable",
        anchorNone: "pages.plans.detail.anchorNone",
        noPhases: "pages.plans.detail.noPhases",
        noReferences: "pages.plans.detail.noReferences",
        phaseAcceptance: "pages.plans.detail.phaseAcceptance",
        globalContextHeading: "pages.plans.detail.globalContextHeading",
        phaseContext: "pages.plans.detail.phaseContext",
        phaseLegacyRequiredReading: "pages.plans.detail.phaseLegacyRequiredReading",
        noContext: "pages.plans.detail.noContext",
        phaseReminders: "pages.plans.detail.phaseReminders",
        phaseBaselineScope: "pages.plans.detail.phaseBaselineScope",
        supersedes: "pages.plans.detail.supersedes",
        supersededBy: "pages.plans.detail.supersededBy",
        edgeNone: "pages.plans.detail.edgeNone",
        notFound: "pages.plans.detail.notFound",
        problemHeading: "pages.plans.detail.problemHeading",
        targetOutcomeHeading: "pages.plans.detail.targetOutcomeHeading",
        assumptionsHeading: "pages.plans.detail.assumptionsHeading",
        technicalApproachHeading: "pages.plans.detail.technicalApproachHeading",
        prohibitedApproachesHeading: "pages.plans.detail.prohibitedApproachesHeading",
        validationStrategyHeading: "pages.plans.detail.validationStrategyHeading",
        finalValidationCommands: "pages.plans.detail.finalValidationCommands",
        risksHeading: "pages.plans.detail.risksHeading",
        workPostureHeading: "pages.plans.detail.workPostureHeading",
        workPostureDetail: "pages.plans.detail.workPostureDetail",
        importProvenanceHeading: "pages.plans.detail.importProvenanceHeading",
        importSource: "pages.plans.detail.importSource",
        preservedLegacyHeading: "pages.plans.detail.preservedLegacyHeading",
        preservedLegacyNote: "pages.plans.detail.preservedLegacyNote",
        phaseAffectedAreas: "pages.plans.detail.phaseAffectedAreas",
        phaseSteps: "pages.plans.detail.phaseSteps",
        phaseExpectedOutputs: "pages.plans.detail.phaseExpectedOutputs",
        phaseValidation: "pages.plans.detail.phaseValidation",
        phaseRisks: "pages.plans.detail.phaseRisks",
        phaseHandoff: "pages.plans.detail.phaseHandoff",
      },
    },
    authoring: {
      title: "pages.authoring.title",
      description: "pages.authoring.description",
      startHeading: "pages.authoring.startHeading",
      startTitleLabel: "pages.authoring.startTitleLabel",
      startTitlePlaceholder: "pages.authoring.startTitlePlaceholder",
      startTemplateLabel: "pages.authoring.startTemplateLabel",
      start: "pages.authoring.start",
      sectionsHeading: "pages.authoring.sectionsHeading",
      sectionContentLabel: "pages.authoring.sectionContentLabel",
      sectionContentPlaceholder: "pages.authoring.sectionContentPlaceholder",
      submitSection: "pages.authoring.submitSection",
      mandatory: "pages.authoring.mandatory",
      autofilled: "pages.authoring.autofilled",
      filled: "pages.authoring.filled",
      violationsHeading: "pages.authoring.violationsHeading",
      noViolations: "pages.authoring.noViolations",
      validateStructure: "pages.authoring.validateStructure",
      autofillHeading: "pages.authoring.autofillHeading",
      autofill: "pages.authoring.autofill",
      autofillEmpty: "pages.authoring.autofillEmpty",
      phasesHeading: "pages.authoring.phasesHeading",
      phaseTitleLabel: "pages.authoring.phaseTitleLabel",
      phaseTitlePlaceholder: "pages.authoring.phaseTitlePlaceholder",
      phaseIntentLabel: "pages.authoring.phaseIntentLabel",
      phaseIntentPlaceholder: "pages.authoring.phaseIntentPlaceholder",
      addPhase: "pages.authoring.addPhase",
      nextPhase: "pages.authoring.nextPhase",
      noPhases: "pages.authoring.noPhases",
      phaseFieldLabel: "pages.authoring.phaseFieldLabel",
      phaseFieldContentLabel: "pages.authoring.phaseFieldContentLabel",
      phaseFieldContentPlaceholder: "pages.authoring.phaseFieldContentPlaceholder",
      savePhaseField: "pages.authoring.savePhaseField",
      contextHeading: "pages.authoring.contextHeading",
      contextKindLabel: "pages.authoring.contextKindLabel",
      contextPhaseScoped: "pages.authoring.contextPhaseScoped",
      contextLabelLabel: "pages.authoring.contextLabelLabel",
      contextLabelPlaceholder: "pages.authoring.contextLabelPlaceholder",
      contextReasonLabel: "pages.authoring.contextReasonLabel",
      contextReasonPlaceholder: "pages.authoring.contextReasonPlaceholder",
      contextInstructionLabel: "pages.authoring.contextInstructionLabel",
      contextInstructionPlaceholder: "pages.authoring.contextInstructionPlaceholder",
      contextCommandLabel: "pages.authoring.contextCommandLabel",
      contextCommandPlaceholder: "pages.authoring.contextCommandPlaceholder",
      contextTargetLabel: "pages.authoring.contextTargetLabel",
      contextTargetPlaceholder: "pages.authoring.contextTargetPlaceholder",
      contextConceptsLabel: "pages.authoring.contextConceptsLabel",
      contextConceptsPlaceholder: "pages.authoring.contextConceptsPlaceholder",
      contextComplexityLabel: "pages.authoring.contextComplexityLabel",
      contextComplexityPlaceholder: "pages.authoring.contextComplexityPlaceholder",
      contextDiscover: "pages.authoring.contextDiscover",
      contextCandidates: "pages.authoring.contextCandidates",
      contextCandidatesEmpty: "pages.authoring.contextCandidatesEmpty",
      contextAccept: "pages.authoring.contextAccept",
      contextReject: "pages.authoring.contextReject",
      contextRejectReasonLabel: "pages.authoring.contextRejectReasonLabel",
      contextRejectReasonPlaceholder: "pages.authoring.contextRejectReasonPlaceholder",
      contextSubmit: "pages.authoring.contextSubmit",
      contextEmpty: "pages.authoring.contextEmpty",
      globalContext: "pages.authoring.globalContext",
      phaseContext: "pages.authoring.phaseContext",
      finalize: "pages.authoring.finalize",
      finalized: "pages.authoring.finalized",
      viewFinalizedPlan: "pages.authoring.viewFinalizedPlan",
    },
    execution: {
      title: "pages.execution.title",
      description: "pages.execution.description",
      startHeading: "pages.execution.startHeading",
      planLabel: "pages.execution.planLabel",
      runIdLabel: "pages.execution.runIdLabel",
      start: "pages.execution.start",
      contextHeading: "pages.execution.contextHeading",
      currentPhaseHeading: "pages.execution.currentPhaseHeading",
      nextPhaseHeading: "pages.execution.nextPhaseHeading",
      noCurrentPhase: "pages.execution.noCurrentPhase",
      noNextPhase: "pages.execution.noNextPhase",
      setupContextHeading: "pages.execution.setupContextHeading",
      noSetupContext: "pages.execution.noSetupContext",
      refreshContext: "pages.execution.refreshContext",
      legacyRequiredReadingHeading: "pages.execution.legacyRequiredReadingHeading",
      remindersHeading: "pages.execution.remindersHeading",
      lastValidationHeading: "pages.execution.lastValidationHeading",
      stalenessHeading: "pages.execution.stalenessHeading",
      transitionHeading: "pages.execution.transitionHeading",
      transitionTo: "pages.execution.transitionTo",
      transition: "pages.execution.transition",
      decisionsHeading: "pages.execution.decisionsHeading",
      decisionSummaryLabel: "pages.execution.decisionSummaryLabel",
      decisionSummaryPlaceholder: "pages.execution.decisionSummaryPlaceholder",
      decisionDetailLabel: "pages.execution.decisionDetailLabel",
      recordDecision: "pages.execution.recordDecision",
      noDecisions: "pages.execution.noDecisions",
      findingsHeading: "pages.execution.findingsHeading",
      findingTitleLabel: "pages.execution.findingTitleLabel",
      findingTitlePlaceholder: "pages.execution.findingTitlePlaceholder",
      findingDetailLabel: "pages.execution.findingDetailLabel",
      recordFinding: "pages.execution.recordFinding",
      noFindings: "pages.execution.noFindings",
      completeHeading: "pages.execution.completeHeading",
      complete: "pages.execution.complete",
      handoffResume: "pages.execution.handoffResume",
      handoffCompleteness: "pages.execution.handoffCompleteness",
      handoffStaleness: "pages.execution.handoffStaleness",
      handoffProseRef: "pages.execution.handoffProseRef",
      handoffNone: "pages.execution.handoffNone",
      nudgesHeading: "pages.execution.nudgesHeading",
      completenessFull: "pages.execution.completenessFull",
      completenessPartial: "pages.execution.completenessPartial",
      completenessUnspecified: "pages.execution.completenessUnspecified",
      logSummaryHeading: "pages.execution.logSummaryHeading",
      logSummaryEmpty: "pages.execution.logSummaryEmpty",
      logTotal: "pages.execution.logTotal",
      logDecisions: "pages.execution.logDecisions",
      logFindings: "pages.execution.logFindings",
      logCandidates: "pages.execution.logCandidates",
      logPendingSync: "pages.execution.logPendingSync",
      logFailedSync: "pages.execution.logFailedSync",
      handoffLogEntries: "pages.execution.handoffLogEntries",
    },
    validation: {
      title: "pages.validation.title",
      description: "pages.validation.description",
      planLabel: "pages.validation.planLabel",
      referencesHeading: "pages.validation.referencesHeading",
      resolveReferences: "pages.validation.resolveReferences",
      noReferences: "pages.validation.noReferences",
      stalenessHeading: "pages.validation.stalenessHeading",
      computeStaleness: "pages.validation.computeStaleness",
      overallStaleness: "pages.validation.overallStaleness",
      baselineHeading: "pages.validation.baselineHeading",
      deriveBaseline: "pages.validation.deriveBaseline",
      baselineCommands: "pages.validation.baselineCommands",
      baselineLocations: "pages.validation.baselineLocations",
      noBaseline: "pages.validation.noBaseline",
      runHeading: "pages.validation.runHeading",
      runValidation: "pages.validation.runValidation",
      verdictLabel: "pages.validation.verdictLabel",
      commandsRunLabel: "pages.validation.commandsRunLabel",
      commandFindingsLabel: "pages.validation.commandFindingsLabel",
      commandIssuesLabel: "pages.validation.commandIssuesLabel",
      commandSuggestionsLabel: "pages.validation.commandSuggestionsLabel",
      commandGuidanceLabel: "pages.validation.commandGuidanceLabel",
      detailLabel: "pages.validation.detailLabel",
      dodHeading: "pages.validation.dodHeading",
      verifyDod: "pages.validation.verifyDod",
      dodMet: "pages.validation.dodMet",
      dodNotMet: "pages.validation.dodNotMet",
      resolutionUnspecified: "pages.validation.resolutionUnspecified",
      resolutionResolved: "pages.validation.resolutionResolved",
      resolutionUnresolved: "pages.validation.resolutionUnresolved",
      resolutionFuture: "pages.validation.resolutionFuture",
      resolutionMissing: "pages.validation.resolutionMissing",
    },
    triage: {
      title: "pages.triage.title",
      description: "pages.triage.description",
      empty: "pages.triage.empty",
      recordedAt: "pages.triage.recordedAt",
      phase: "pages.triage.phase",
      promote: "pages.triage.promote",
      dismiss: "pages.triage.dismiss",
    },
    velocity: {
      title: "pages.velocity.title",
      description: "pages.velocity.description",
      planLabel: "pages.velocity.planLabel",
      empty: "pages.velocity.empty",
      wallTime: "pages.velocity.wallTime",
      tokens: "pages.velocity.tokens",
      iterations: "pages.velocity.iterations",
      completeness: "pages.velocity.completeness",
      recordedAt: "pages.velocity.recordedAt",
      seconds: "pages.velocity.seconds",
      chartLabel: "pages.velocity.chartLabel",
      runLabel: "pages.velocity.runLabel",
    },
  },
  health: {
    title: "health.title",
    loading: "health.loading",
    error: "health.error",
    refresh: "health.refresh",
    refreshCount: "health.refreshCount",
    refreshCount_one: "health.refreshCount_one",
    statusLabel: "health.statusLabel",
    serviceLabel: "health.serviceLabel",
    timestampLabel: "health.timestampLabel",
  },
  notifications: {
    summary: "notifications.summary",
    summary_zero: "notifications.summary_zero",
    summary_one: "notifications.summary_one",
  },
  errors: {
    canceled: "errors.canceled",
    unknown: "errors.unknown",
    invalid_argument: "errors.invalid_argument",
    deadline_exceeded: "errors.deadline_exceeded",
    not_found: "errors.not_found",
    already_exists: "errors.already_exists",
    permission_denied: "errors.permission_denied",
    resource_exhausted: "errors.resource_exhausted",
    failed_precondition: "errors.failed_precondition",
    aborted: "errors.aborted",
    out_of_range: "errors.out_of_range",
    unimplemented: "errors.unimplemented",
    internal: "errors.internal",
    unavailable: "errors.unavailable",
    data_loss: "errors.data_loss",
    unauthenticated: "errors.unauthenticated",
  },
  locale: {
    switcherLabel: "locale.switcherLabel",
  },
  errorBoundary: {
    title: "errorBoundary.title",
    message: "errorBoundary.message",
    retry: "errorBoundary.retry",
  },
} as const;

export type Strings = typeof strings;
