// Code generated by go run api/cmd/movie-spec-gen/main.go. DO NOT EDIT.
// Generated at 2025-11-02T04:16:42Z

export interface ReplayMovieSpec {
  version: string;
  generated_at: string;
  execution: ReplayMovieExecutionMetadata;
  theme: ReplayMovieTheme;
  cursor: ReplayMovieCursorSpec;
  decor: ReplayMovieDecor;
  playback: ReplayMoviePlayback;
  presentation: ReplayMoviePresentation;
  cursor_motion: ReplayMovieCursorMotion;
  frames: ReplayMovieFrame[];
  assets: ReplayMovieAsset[];
  summary: ReplayMovieSummary;
}

export interface ReplayMovieAssertion {
  mode?: string;
  selector?: string;
  expected?: unknown;
  actual?: unknown;
  success: boolean;
  negated?: boolean;
  caseSensitive?: boolean;
  message?: string;
}

export interface ReplayMovieAsset {
  id: string;
  type: string;
  source: string;
  thumbnail?: string;
  width?: number;
  height?: number;
  size_bytes?: number;
}

export interface ReplayMovieBrowserChrome {
  visible: boolean;
  variant: string;
  title?: string;
  show_address: boolean;
  accent_color: string;
}

export interface ReplayMovieClickPulse {
  enabled: boolean;
  radius: number;
  duration_ms: number;
  opacity: number;
}

export interface ReplayMovieCursorMotion {
  speed_profile: string;
  path_style: string;
  initial_position: string;
  click_animation: string;
  cursor_scale: number;
}

export interface ReplayMovieCursorSpec {
  style: string;
  accent_color: string;
  trail: ReplayMovieCursorTrail;
  click_pulse: ReplayMovieClickPulse;
  scale?: number;
  initial_position?: string;
  click_animation?: string;
}

export interface ReplayMovieCursorTrail {
  enabled: boolean;
  fade_ms: number;
  weight: number;
  opacity: number;
}

export interface ReplayMovieCursorTrailPoint {
  x: number;
  y: number;
}

export interface ReplayMovieDecor {
  chrome_theme?: string;
  background_theme?: string;
  cursor_theme?: string;
  cursor_initial_position?: string;
  cursor_click_animation?: string;
  cursor_scale?: number;
}

export interface ReplayMovieDimensions {
  width: number;
  height: number;
}

export interface ReplayMovieExecutionMetadata {
  execution_id: string;
  workflow_id: string;
  workflow_name?: string;
  status: string;
  started_at: string;
  completed_at?: string;
  progress: number;
  total_duration_ms: number;
}

export interface ReplayMovieFocusedElement {
  selector: string;
  boundingBox?: ReplayMovieRegionBounds;
}

export interface ReplayMovieFrame {
  index: number;
  step_index: number;
  node_id: string;
  step_type: string;
  title: string;
  status: string;
  start_offset_ms: number;
  duration_ms: number;
  hold_ms: number;
  enter: TransitionSpec;
  exit: TransitionSpec;
  screenshot_asset_id?: string;
  viewport: ReplayMovieDimensions;
  zoom_factor?: number;
  highlight_regions?: ReplayMovieRegion[];
  mask_regions?: ReplayMovieRegion[];
  focused_element?: ReplayMovieFocusedElement;
  element_bounding_box?: ReplayMovieRegionBounds;
  normalized_focus_bounds?: ReplayMovieNormalizedRect;
  normalized_element_bounds?: ReplayMovieNormalizedRect;
  click_position?: ReplayMovieCursorTrailPoint;
  normalized_click_position?: ReplayMovieNormalizedPoint;
  cursor_trail?: ReplayMovieCursorTrailPoint[];
  normalized_cursor_trail?: ReplayMovieNormalizedPoint[];
  console_log_count?: number;
  network_event_count?: number;
  final_url?: string;
  error?: string;
  assertion?: ReplayMovieAssertion;
  dom_snapshot_preview?: string;
  dom_snapshot_html?: string;
  resilience: ReplayMovieResilience;
}

export interface ReplayMovieFrameRect {
  x: number;
  y: number;
  width: number;
  height: number;
  radius?: number;
}

export interface ReplayMovieNormalizedPoint {
  x: number;
  y: number;
}

export interface ReplayMovieNormalizedRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ReplayMoviePlayback {
  fps: number;
  duration_ms: number;
  frame_interval_ms: number;
  total_frames: number;
}

export interface ReplayMoviePresentation {
  canvas: ReplayMovieDimensions;
  viewport: ReplayMovieDimensions;
  browser_frame: ReplayMovieFrameRect;
  device_scale_factor: number;
}

export interface ReplayMovieRegion {
  selector: string;
  boundingBox?: ReplayMovieRegionBounds;
  padding?: number;
  color?: string;
  opacity?: number;
}

export interface ReplayMovieRegionBounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ReplayMovieResilience {
  attempt: number;
  max_attempts: number;
  configured_retries: number;
  delay_ms: number;
  backoff_factor: number;
  history?: ReplayMovieRetryHistoryEntry[];
}

export interface ReplayMovieRetryHistoryEntry {
  attempt: number;
  success: boolean;
  duration_ms?: number;
  call_duration_ms?: number;
  error?: string;
}

export interface ReplayMovieSummary {
  frame_count: number;
  screenshot_count: number;
  total_duration_ms: number;
  max_frame_duration_ms: number;
}

export interface ReplayMovieTheme {
  background_gradient: string[];
  background_pattern: string;
  accent_color: string;
  surface_color: string;
  ambient_glow: string;
  browser_chrome: ReplayMovieBrowserChrome;
}

export interface TransitionSpec {
  type: string;
  duration_ms: number;
  easing: string;
}

